### ISSUE TITLE
Feature request: codecell folding

### ISSUE THREAD

**Issue by aseyffert** [nteract/hydrogen#1001]
It would be convenient if the codecell functionality were such that I could hide/fold codecells I'm not currently working on in the source. Something like

```
# <codecell> Boring Code
print 'Hello World'
boringCode.done = True

# <codecell> Fun Code
print 'Here's my current working area...
funCode.done = False
```

would become:

```
# <codecell> Boring Code
# <codecell> Fun Code
print 'Here's my current working area...
funCode.done = False
```

I'm referring to the other codecell varients as well, of course, not just ```<codecell>```. Hope that makes sense... :smile:

**Comment by BenRussert** [comment]
Cool idea. I havent looked into this to know what that would take. 

If you are interested in looking into this and/or making a PR that would be awesome!

**Comment by lgeiger** [comment]
That's a excellent idea!

Unfortunately it looks like Atom's code folding completely relies on indentations instead of selectors specified by grammar packages: https://github.com/atom/first-mate/issues/48
If that is still true this feature might be almost impossible for us to implement.

**Comment by aseyffert** [comment]
That's quite unfortunate. I see this issue (atom/atom#11838) has been around for quite some time. I guess this is me joining the queue waiting for it to get resolved... :neutral_face: 

Thanks for the feedback! :smiley:

**Comment by lgeiger** [comment]
It looks like we might be able to do this once https://github.com/atom/atom/pull/16299 lands.

**Comment by kylebarron** [comment]
It's true that Atom's code folding relies on indentation, but there is a [function](https://atom.io/docs/api/v1.30.0/Selection#instance-fold) in Atom's API to programmatically fold arbitrary sections of the buffer. So it would be possible to have a Hydrogen command that, say, folds the code cell that the cursor is inside. 

This would amount to finding the beginning of the next codecell and folding all intermediate lines.

**Comment by kylebarron** [comment]
Hydrogen already has code to find the [current code cell](https://github.com/nteract/hydrogen/blob/1a41f824e08305415e412061483c18f145a984a7/lib/code-manager.js#L162-L188).

Folding that is as simple as:
```js
var range = codeManager.getCurrentCell(editor);
editor.setSelectedBufferRange(range);
var selection = editor.selections[0];
selection.fold();
```

That converts this:
![image](https://user-images.githubusercontent.com/15164633/47370222-429ee600-d6b3-11e8-9839-6b1ed024f322.png)

into this:
![image](https://user-images.githubusercontent.com/15164633/47370046-e76cf380-d6b2-11e8-8dd9-df1b41cdf35e.png)

It seems preferable to me for `range.start` to be subtracted by one character and for `range.end` to be subtracted by one buffer line. That causes the fold to look like this:
![image](https://user-images.githubusercontent.com/15164633/47370174-256a1780-d6b3-11e8-8fb4-fd9852b13729.png)

Another helpful function might be "fold all code cells except for the current one". In that case we could do something like 
```js
ranges = codeManager.getCells(editor);
currentRange = codeManager.getCurrentCell(editor);
// Remove currentRange from ranges
editor.setSelectedBufferRanges(ranges);
selections = editor.selections
for (var i = 0; i < selections.length; i++) {
  selections[i].fold()
}
```
That looks like 
![image](https://user-images.githubusercontent.com/15164633/47370844-95c56880-d6b4-11e8-89a3-6eb67aa36e42.png)

I'll try to submit a PR for this soon.
