### ISSUE TITLE
Blank Hydrogen Inspector

### ISSUE THREAD

**Issue by eskemojoe007** [nteract/hydrogen#1004]
**Description:**

After upgrading to Hydrogen 1.22.0 (with Atom 1.20.0 ia32) hydrogen inspector loads with no information using a miniconda python2 kernel.  It previosly worked.

![image](https://user-images.githubusercontent.com/22135005/30699648-45edf1f4-9eb3-11e7-9f8c-a5727a7bfb39.png)

**Comment by lgeiger** [comment]
Checkout #996

We'll release a new version with a proper fix very soon.

**Comment by eskemojoe007** [comment]
I must have done a poor search.  Sorry to pen another issue when you were already aware.

**Comment by lgeiger** [comment]
We shipped v1.23.0. This is now fixed.
