### ISSUE TITLE
'python3' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

### ISSUE THREAD

**Issue by accmohamedsaber** [nteract/hydrogen#1006]
<!-- If this is a bug report fill out this template (otherwise you can exclude it)

**Description:**

I am facing this error message in Atom when I tried to install Python packages on atom. I've already anaconda 3 installed on the machine (Windows 10).

![atom issue](https://user-images.githubusercontent.com/29353784/30767606-d623585c-9ff5-11e7-85e1-797c9ca29c49.PNG)

**Versions:**

OS: Windows 10

Atom 1.20.0 X64 

**Logs:**

Atom console's log:

Uncaught Error: spawn python3 ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
internal/process/warning.js:21 (node:12340) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by BenRussert** [comment]
Have you confirmed that python3 is installed and on your path?

**Comment by accmohamedsaber** [comment]
no, I have not - im fairly new to atom .. how can i do that?

**Comment by accmohamedsaber** [comment]
![atom issue](https://user-images.githubusercontent.com/29353784/30768021-3df5bea8-9ffa-11e7-946a-cf098c919c0d.PNG)

**Comment by BenRussert** [comment]
The issue looks like it is with your system installation of python3. Have you installed this recently or used it outside of atom, e.g in a console?

**Comment by accmohamedsaber** [comment]
I had installed python 3 then installed atom .. i've not used console to to install it.

**Comment by BenRussert** [comment]
Check out [this new section](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) of our docs. I saw your comment on Issue #67, it is an old but still relevant issue with tons of info.

Take a look and let me know if have questions!

**Comment by accmohamedsaber** [comment]
I've followed the instructions add python on environment variables on Windows , however I still get the same issue:

IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:116302
events.js:160 Uncaught Error: spawn python3 ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
internal/process/warning.js:21 (node:2572) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by BenRussert** [comment]
Looks like that was thrown from the [python-suite](https://github.com/Romaine/python-suite) package. If you want you can open an issue there. 

If you want to try to get hydrogen working I would just disable that package for now and restart atom. 

Also, just to rule out issues outside of atom/hydrogen I would try opening up cmd.exe or powershell and running `jupyter kernelspec list --json` in the console to ensure jupyter and at least one kernelspec is installed correctly. You should see some json output which you can paste in a comment here.

**Comment by dmarx** [comment]
I was getting the same error and managed to resolve it while writing up my observations! Rubber duck debugging with Github Issues! 

In the Hydrogen settings config, this was what I had for my kernelspec string (I think I might've modified the resource_dir from it's original setting as part of my original attempt to fix to this error):

```
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/anaconda/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "python3",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}
```

And this is what I had when running the jupyter command in my console:

```
{
  "kernelspecs": {
    "python": {
      "resource_dir": "/Users/davimarx/Library/Jupyter/kernels/python",
      "spec": {
        "argv": [
          "/anaconda/bin/python3",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    },
    "python3": {
      "resource_dir": "/Users/davimarx/Library/Jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/anaconda/bin/python3",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}
```

I was able to get Hydrogen working properly by pasting the output from `jupyter kernelspec list --json` into the kernelspec setting in the Hydrogen configuration pane. 

------------------------------------------------------

For posterity (and maybe to help googlers find their way here), here're the errors I saw in the developer console:

```
warning: /bin/false -ilc "command env" failed with signal (undefined)
<embedded>:16263 Error: spawn /bin/false ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
<embedded>:16262 warning: /bin/false -ilc "command env" failed with signal (undefined)
<embedded>:16263 Error: spawn /bin/false ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
events.js:160 Uncaught Error: spawn python3 ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
<embedded>:16262 warning: /bin/false -ilc "command env" failed with signal (undefined)
<embedded>:16263 Error: spawn /bin/false ENOENT
    at exports._errnoException (util.js:1022)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:359)
    at _combinedTickCallback (internal/process/next_tick.js:74)
    at process._tickCallback (internal/process/next_tick.js:98)
```

Relevant specs:
* macOS Sierra v10.12.6
* Atom 1.20.1 x64
* Hydrogen 1.23.0
* Python 3.6.1 is my default python interpreter via an anaconda installation (conda 4.3.27).

**Comment by lgeiger** [comment]
In Hydrogen 2.0.0 we changed our kernel detection method to improve the startup time and make setup easier. Checkout the updated [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html) and the [release notes](https://github.com/nteract/hydrogen/releases/tag/v2.0.0) for more information.

Feel free to open a new issue if you still experience problems with version 2.0.0.
