### ISSUE TITLE
Javascript/React cannot find module (for custom modules defined within the project)

### ISSUE THREAD

**Issue by giovannipbonin** [nteract/hydrogen#1007]
Hi guys,

I'm trying to use hydrogen with a project that has a lot of custom dependencies, and when importing them I get the following: "Error: cannot find module 'bundles/page/components/TrackedButton';

Here's a screenshot:

https://www.dropbox.com/s/i2we272w9mqmenu/Screenshot%202017-09-24%2014.41.12.png?dl=0

Is there a way to use this with custom imports? I noticed that I get the same error if I try running the jp-babel kernel on jupyter and running that same line in the notebook. Might be something to do with how jp-babel is being initialized, here's the kernel specs:

```json
{
    "kernelspecs": {
        "babel": {
            "spec": {
                "display_name": "jp-Babel",
                "argv": [
                    "jp-babel-kernel",
                    "--hide-undefined",
                    "--protocol=5.0",
                    "{connection_file}"
                ],
                "language": "Babel ES6 JavaScript"
            }
        }
    }
}
```

**Comment by rgbkrk** [comment]
Is `bundles` an npm package or is it a local package? If it's local, you'll need to import from `./bundles`

**Comment by giovannipbonin** [comment]
It's a local package, the ./ worked with the caveat that i also needed to add the parent directory to bundles "static", but this can be omitted when running the app that's why it wasn't added before. I'll close this.

Thanks

**Comment by jdpigeon** [comment]
Hey guys, I'm running into something similar. Can't get Hydrogen w/ jp-babel to successfully import modules.

Ideally, I'd love to be able to do:
```
import React, { Component } from "react";
import Button from "./components/button"
```
However, both of these throw the same cannot find module @giovannipbonin linked above. No amount of fiddling with paths, adding parent dirs in and everything seems to help.

Seems like pretty basic functionality. Have I messed something up with my install? Here's my kernel specs
```
{
 "kernelspecs": {
    "babel": {
      "resource_dir": "/home/dano/.local/share/jupyter/kernels/babel",
      "spec": {
        "argv": [
          "jp-babel-kernel",
          "--hide-undefined",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "env": {},
        "display_name": "jp-Babel (Node.js)",
        "language": "babel"
      }
    }
```

**Comment by lgeiger** [comment]
Hi @jdpigeon, I'm not very familiar with the `jp-babel` kernel but here are some general notes:

The first time you run code Hydrogen starts a new kernel in the directory specified via the Hydrogen settings.
Depending on your configuration Hydrogen will start the kernel either in the first project's directory opened in the tree view (default), the project directory relative to the file or the current directory of the file.

Can you double check if the kernel is started in the correct directory to make the imports work?

**Comment by jdpigeon** [comment]
Aha! That's it. Of course. I always set my root in this one project one directory above where all the node_modules are.

Now I seem to be in the situation giovanni was in, though. I can import local stuff, but I have to use the path from the project root rather than the local path. I can temporarily change things in order to test with Hydrogen, but do you think there's a way of having Hydrogen figure those local paths based on which file you're running it in?
