### ISSUE TITLE
Can't find kernel and crashing when run

### ISSUE THREAD

**Issue by csmith23** [nteract/hydrogen#1021]
Hydrogen cannot find jupyter kernels, so I input them manually. When I run "jupyter kernelspec list --json" in Anaconda Prompt and copy that into Kernel Specs for Hydrogen, and then run a python file with Shift+Enter, atom crashes and a window pops up that says "the editor has crashed" and lets me either "close window", "reload", or "keep it open." I'm not sure if this is because I'm using Anaconda's Jupyter and IPython installs or not, or what could be causing this issue.

The response I get from "jupyter kernelspec list --json":

{
  "kernelspecs": {
    "python3": {
      "resource_dir": "C:\\Anaconda3\\share\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}

**Versions:**

Windows 10
Anaconda 4.3.27
Jupyter 4.3 (came with Anaconda)
IPython 5.3 (came with Anaconda)
Atom 1.20.1

**Comment by BenRussert** [comment]
Anaconda should be fine, in fact that's what I recommend. 

Can you post the code you are trying to run? Are you able to run that same code without issue outside of atom e.g. in an ipython console?

**Comment by csmith23** [comment]
I actually realized that I didn't add anaconda to my path when I reinstalled recently, but I added it and all is working now

**Comment by BenRussert** [comment]
Glad you got it working!
