### ISSUE TITLE
History slider CSS is broken

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#1030]
The CSS of the history slider needs some tweaking:
![bildschirmfoto 2017-10-03 um 19 00 32](https://user-images.githubusercontent.com/13285808/31138222-04c81398-a86e-11e7-8770-e00aa60ed617.png)

It would be cool to test it with other themes as well.

**Comment by xanecs** [comment]
I'll try to fix this

**Comment by lgeiger** [comment]
Awesome! 🎉 

Feel free to join https://slack.nteract.io if you have questions.

**Comment by lgeiger** [comment]
Closed by #1049
