### ISSUE TITLE
cant install hydrogen on windows 8 64 bit

### ISSUE THREAD

**Issue by Khalilsqu** [nteract/hydrogen#1033]
**Description:**

I could not install hydrogen on my pc. it kept in the status of installing for ages and my pc freezed without hydrogen being installed. while installing it the pc becomes unresponsive and very slow.

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
Which version of Atom are you using?
Could you try installing it by running `apm install hydrogen` in your command line and post the logs?

**Comment by lgeiger** [comment]
It looks like installing from the command line should fix your issue. Feel free to reopen if you still need help.
