### ISSUE TITLE
webpage https://nteract.io/kernels is broken

### ISSUE THREAD

**Issue by Datseris** [nteract/hydrogen#1040]
The webpage that gives the commands on how to install popular kernels is inaccessible from both my phone and mozilla firefox.

Mozilla gives the error:
```
Secure Connection Failed

An error occurred during a connection to nteract.io. Peer reports it experienced an internal error. Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

And at some point told me to tell the developers to update the TSL...?

FYI, I am trying to access the page from a research institute in Germany. From my home connection yesterday, I could access it no problem.

In the meantime, could somebody that can access the page simply copy paste the 2-line command for installing python kernel?... I just used it yesterday and I Was so amazed by Hydrogen I wanted to use it at work too!

**Comment by Datseris** [comment]
Hm, maybe this happened due to the `use prettier` commit to the docs github page?

**Comment by lgeiger** [comment]
Yep we're down. We tried to migrate DNS yesterday but that didn't workout the way we expected 😞 

You can install the Python Kernel by running:
```
python -m pip install ipykernel
python -m ipykernel install --user
```

**Comment by rgbkrk** [comment]
Alright, it's back up!
