### ISSUE TITLE
Shipping 2.0.0

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#1045]
We've had two breaking changes (#1031, #1008) since the latest release, therefor the next release will be a major version bump.

I cannot think of any blockers for this release. I'm happy to wait for #1022, is there anything I forgot?

**Comment by BenRussert** [comment]
I don't think #1022 should hold up H2O.

**Comment by lgeiger** [comment]
Published [`v2.0.0`](https://github.com/nteract/hydrogen/releases/tag/v2.0.0). Feel free to edit the release notes.
