### ISSUE TITLE
Hydrogen never shows plots and loads forever (%matplotlib inline IS included)

### ISSUE THREAD

**Issue by MikkelOJ** [nteract/hydrogen#1048]
Hi.

I hope someone can help me out. I have moderate programming experience (Matlab and Java), but I'm starting to learn Python as well. 

I'm having issues when trying to plot a graph: I can execute each line until the plot() line: they all get a checkmark and I can output stuff like "Hello world". When I try to run the plot() command, Hydrogen never stops to show the loading symbol and the code never gets past this point. 

I have included %matplotlib inline and show() in the end. 
Here's my code:
`import sys
sys.path.append("/anaconda3/lib/python3.6/site-packages")

%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()`

But nothing happens
![image](https://user-images.githubusercontent.com/7093377/31609037-d51c7350-b272-11e7-94f6-f739f658c5e1.png)

If i run this from the terminal (and comment out %matplotlib inline), it plots the graph. 

Here are the versions that I'm running: 

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS X: 10.11.4

Any hints on what could be wrong? I've done a lot of googling but i can't find anyone with this exact problem.
 
All help is much appreciated! :) 
- Thanks.

**Comment by rgbkrk** [comment]
The python used needs to match the version for native modules. If I had to guess I'd say that you're adding the path for a different binary python.

**Comment by MikkelOJ** [comment]
Thanks a lot for your reply! It is very much appreciated!
Sorry for the very basic questions: 
If I print(sys.version) inside hydrogen it gives me 

`3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]`

So i guess that I should be running python 3.6, the same as the matplotlib location that I'm pointing to? 

And by the way, Hydrogen says it using Python 3, so i guess that's not the issue? 
Thanks again

**Comment by MikkelOJ** [comment]
I remember that I created a Python 3.5 environment to install OpenCV3 on my Mac. Could that be related to this?
Thanks!

**Comment by BenRussert** [comment]
Can you try opening the atom devtools and seeing if there are any messages there?( You'll need to make sure debug logging is enabled in your config for hydrogen first.)

**Comment by MikkelOJ** [comment]
When i run the plot command, the console prints:

"Hydrogen: ZMQKernel: stdout: Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib."

In the beginning, is also see two warnings:
<embedded>:119170 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:119170
<embedded>:21206 'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}

Any idea what could be wrong? Can i provide other information? 
Thanks a lot for the help! I really appreciate it!

**Comment by rgbkrk** [comment]
This is looking like something is corrupt in the python installation, or that the kernel being used is using mismatching binaries (for numpy, matplotlib, etc.). That intel library is the Math Kernel Library. From Hydrogen and also in a separate jupyter console, run this for me and see if the paths, prefix, and executable make sense:

```python
import sys
display({ 'prefix': sys.prefix, 'path': sys.path, 'executable': sys.executable })
```
