### ISSUE TITLE
Add option to hide status bar item

### ISSUE THREAD

**Issue by danielbayley** [nteract/hydrogen#1055]
There is limited space down there, and this takes up a large chunk of it. No package should be adding stuff to the status bar without a corresponding option to hide it…

**Comment by dwolfschlaeger** [comment]
I'll have a look at that.

**Comment by dwolfschlaeger** [comment]
Short-term solution:
There is already a command "Status Bar: Toggle" for hiding and unhiding the status bar.

Alternative solution:
We can provide a user option which defines whether the status bar is hidden by default using hydrogen. What do you think @lgeiger?

**Comment by danielbayley** [comment]
@dwolfschlaeger I wasn't referring to the entire status bar! Packages shouldn't be interfering with that… I mean the option to hide the status bar _item_ added by this package when a kernel is running…

**Comment by danielbayley** [comment]
![screenshot 10 18 21 03 22](https://user-images.githubusercontent.com/7797479/31740039-edbeddd6-b447-11e7-85fb-f9ef1226056e.png)
