### ISSUE TITLE
Windows InstallationTips

### ISSUE THREAD

**Issue by SiggiGue** [nteract/hydrogen#106]
Additionally to the given tips in the README, installing VS2013, be sure that a python 2.7 is in the system PATH, otherwise (e.g. if `python3` is in the path) the installation `apm install hydrogen` will fail.

**Comment by n-riesco** [comment]
Closing since this is now documented [README.md](https://github.com/nteract/hydrogen/blob/master/README.md) and [TROUBLESHOOTING.md](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).
