### ISSUE TITLE
No kernel for grammar python

### ISSUE THREAD

**Issue by vader333** [nteract/hydrogen#1060]
Description:
Installed ipykernel and jupyter using:

`python -m pip install ipykernel`
`python -m ipykernel install -user`
`pip install jupyter`

When I update hydrogen kernels, it succeeds in finding ipykernel for Python 3
![2](https://user-images.githubusercontent.com/19439978/31865227-e074db86-b79d-11e7-9650-169089735424.jpg)

However, when I try to run hydrogen, there is no result, and if I try to restart the kernel, it says "No Kernel for Grammar Python"
![1](https://user-images.githubusercontent.com/19439978/31865231-f8f1726e-b79d-11e7-86ad-4d1824b4e08d.jpg)

When I run kernel `jupyter kernelspec list --json`, i get this:

```
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "C:\\Users\\brian\\AppData\\Roaming\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "C:\\Users\\brian\\AppData\\Local\\Programs\\Python\\Python36\\python.exe",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "Python"
      }
    }
  }
}
```
Versions:

Atom: 1.21.1 x64
Python 3.6.3 x64

**Comment by crazypenguin** [comment]
save your untitled file as .py file，does it works？

**Comment by vader333** [comment]
Oh, thank you for that suggestion. Apparently, I don't have python-language-server, which is required for hydrogen to work. When I saved it as a py file, it gave me that error, so I installed it, and after that, it worked. Thanks again!

**Comment by lgeiger** [comment]
Glad it's working now 🎉 

Thanks @crazypenguin for helping debug.

>Apparently, I don't have python-language-server, which is required for hydrogen to work

For the record, Hydrogen doesn't require `python-language-server`.
@vader333 You probably have [`ide-python`](https://github.com/lgeiger/ide-python) installed which requires `python-language-server` as a external dependency.

@BenRussert We should check the behavior when trying to start a Kernel in a unsaved file. At least we should throw a helpful error message.
