### ISSUE TITLE
Hydrogen kernel will not start on grammar change

### ISSUE THREAD

**Issue by vader333** [nteract/hydrogen#1063]
Hydrogen Kernel will not start. Need to save as .py file first, close file and reopen for kernel to start.
Choosing grammar in bottom right will not trigger hydrogen kernel. Attempting to restart kernel will give "No kernel for grammar Python installed"

Versions:
Atom: 1.21.1
Hydrogen: 2.0.1

**Comment by lgeiger** [comment]
Thanks for opening the issue.

Currently we require the file to be saved in order to properly start a kernel. Though at the very least we should provide a helpful error message.

**Comment by BenRussert** [comment]
Closing in favor of #1064
