### ISSUE TITLE
Support MagicPython per default

### ISSUE THREAD

**Issue by msoedov** [nteract/hydrogen#1065]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. Install MagicPython

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
Checkout the language mapping setting.
Setting it to `{ "python": "magicpython" }` should fix it.

@BenRussert @rgbkrk I wonder if we should set a few common language mappings per default to make it easier for new users who use a custom grammar.

**Comment by rgbkrk** [comment]
I think setting the magic python one by default is good, especially if they can still override it (if they need 2, 3, or a special env)

**Comment by msoedov** [comment]
Agreed with @rgbkrk , it should works by default

**Comment by lgeiger** [comment]
@msoedov Would you be interested in sending a PR to fix this? Feel free to join us at slack.nteract.io if you have any questions.

**Comment by WolfLo** [comment]
I am sorry for the ignorance but...where do I find the language mapping settings please?

**Comment by lgeiger** [comment]
In the code it's defined here:
https://github.com/nteract/hydrogen/blob/9d595258c9619b3b106b796c7b1305e3109bcf9e/lib/config.js#L86-L93

In the user interface you'll find it by opening the Atom settings pane and search for the hydrogen package.

**Comment by WolfLo** [comment]
Thank you @lgeiger. I set it as `languageMappings: { "python": "magicpython" },` as you suggested but I keep receiving the error 

> No kernel for grammar MagicPython found

I am working in a virtualenv, calling Atom from within. Do you have any further suggestion? should the language mapping chenge in case I am using python3?

Typing  `python3 -m ipykernel install --user` i get the following:

> Installed kernelspec python3 in /home/lupol/.local/share/jupyter/kernels/python3

**Comment by kylebarron** [comment]
@WolfLo 
I use MagicPython and the following is what I have as my Language Mapping setting:
![image](https://user-images.githubusercontent.com/15164633/43555746-19f05fa6-95ca-11e8-9d0b-27fb897f3a74.png)

You could also try `{"python3": "magicpython"}` since your kernel is registered with the name `python3`.
