### ISSUE TITLE
Issue: hydrogen:clear-results does not clear dock

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1067]
Issue: hydrogen:clear-results does not clear dock

Is there a way to clear the dock via keyboard shortcut? hydrogen:clear-results only clears outputs in code, if any, but does not clear the dock if dock is used for results. Thanks in advance for you help.
 
Windows 10 Home Premium 64bit 
Atom 64bit v 1.21.1
Hydrogen 2.0.1

**Comment by dsanalytics** [comment]
Can store.kernel.outputStore.clear() be mapped to a keyboard shortcut? If so, that would solve this PR-free.

**Comment by BenRussert** [comment]
> Can store.kernel.outputStore.clear() be mapped to a keyboard shortcut?

Not exactly. You would need a custom command in your init script and even then it would be a bit of a hack and could break if we changed something in the future. 

I think it's a good point that clearing results should include the output area (I would like it to as a user as well). This change is also the simplest solution to get the custom keyboard shortcut to work so its win-win.

**Comment by BenRussert** [comment]
@lgeiger I am tagging this as "good first issue", let me know if I am wrong about in case i've forgotten something that will come up :thinking:.

**Comment by dsanalytics** [comment]
Ben, once Dock Clear is successfully implemented, what should my configs look like in order to combine clear dock and execute cell in hydrogen in a single shortcut? See my starting point below - thx in advance.

init.coffee
atom.commands.add 'atom-text-editor', 'hydrogen:clear-results-run-cell', ->
???

keymap.cson
'.platform-win32 atom-text-editor:not([mini]), .platform-linux atom-text-editor:not([mini])':
  'ctrl-alt-enter': 'hydrogen:clear-results-run-cell'

**Comment by BenRussert** [comment]
I'm on mobile at the moment so I'll post [a link](https://discuss.atom.io/t/how-do-you-run-a-command-from-an-installed-package-from-init-coffee/14388/2) with an example that is almost the same

See also : https://atom.io/docs/api/v1.21.1/CommandRegistry#instance-dispatch

Let me know how that goes!

**Comment by dsanalytics** [comment]
Thanks Ben - I'll check it out.
Any ETA for this issue?

**Comment by BenRussert** [comment]
@dsanalytics I sent a PR for this just now. If interested, check our [CONTRIBUTING.md](https://github.com/nteract/hydrogen/blob/master/CONTRIBUTING.md) to see how to set up a dev version of hydrogen and try it out. I've found hacking on atom to be a really fun way to learn to code.

**Comment by dsanalytics** [comment]
Thank you gentlemen! Atom seems to be fast becoming my primary platform for DS!

**Comment by dsanalytics** [comment]
How long does it usually take to get package update in Atom through Install in Settings? No huge rush - just asking to learn about the process.

**Comment by BenRussert** [comment]
Good question. Anytime features/fixes are added to the development branch they need to be "shipped" to become available as a release on apm

We will ship soon I'm sure, but I really think you should get a development branch working since you seem to have the interest 😀

More on apm release specifics [here](http://flight-manual.atom.io/hacking-atom/sections/publishing/)

**Comment by kerajel** [comment]
Uhm is this still not implemented?
