### ISSUE TITLE
FR: Dock output default view option to be configurable

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1068]
Re: Dock output default view option to be configurable

Currently, default option is the clock icon and it'd be nice if the default could be configurable. See attachment.

![atom-hydrogen-output-view-options](https://user-images.githubusercontent.com/32625394/32131265-831076c8-bb6f-11e7-9ea6-e24c97012c43.png)

**Comment by dsanalytics** [comment]
I think Ben's idea is better for being simpler and easier to implement I'd guess. Thanks Ben!

**Comment by BenRussert** [comment]
Closing in favor of #1327
