### ISSUE TITLE
Hydrogen is not able to locate python3 modules

### ISSUE THREAD

**Issue by moharsen** [nteract/hydrogen#1071]
**Description:**
Hydrogen does not seem to find the modules installed in python3. I have both python 2.7 (/usr/bin/python) and python 3.6 (/usr/bin/python3) installed in Ubuntu 17.10.   
If I enter python3 from Ubuntu Terminal, I have access to all packages that I installed with pip3. If I open jupyter and select python3, I have no problems.   
![screenshot from 2017-10-30 00-35-00](https://user-images.githubusercontent.com/8618330/32154882-3426d330-bd0a-11e7-927b-86e019f81b22.png)

However, from inside Atom, whenever I attempt to import a module like pandas I receive an error:

```
**ImportErrorTraceback (most recent call last)
<ipython-input-6-af55e7023913> in <module>()
----> 1 import pandas as pd

ImportError: No module named pandas**
```
No such problems importing a standard module. It seems that hydrogen is not able to locate python3 packages that were additionally installed.

**Steps to Reproduce:**

1. Open a python script in atom
2. Try to execute (Ctrl+Enter) `import pandas`
![screenshot from 2017-10-30 00-30-10](https://user-images.githubusercontent.com/8618330/32154854-f829f63c-bd09-11e7-8237-4b376a10275f.png)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Atom    : 1.21.1
OS: Ubuntu 17.10

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by Goochimagne** [comment]
I have the same problem in 

Atom 1.21.2
OS: Windows 10

Please help

**Comment by lgeiger** [comment]
Have you installed the Python kernels for both versions according to https://nteract.io/kernels/python?

**Comment by moharsen** [comment]
I went to nteract and ran `python -m pip install ipykernel`. No difference in the results.
![screenshot from 2017-11-05 10-11-27](https://user-images.githubusercontent.com/8618330/32416193-816a3214-c213-11e7-80cb-f6646fd5cfb2.png)

It seems the python 2 is getting selected no matter what. In the beginning, when I attempt a Ctrl+Enter on the first import line, I get to choose the kernel in the following screen:
![screenshot from 2017-11-05 09-54-15](https://user-images.githubusercontent.com/8618330/32416128-07e71552-c212-11e7-9d50-a9af0333b1f6.png)
The text in the lower left corner of the screen shows that Python 3 has been selected
![screenshot from 2017-11-05 10-06-28](https://user-images.githubusercontent.com/8618330/32416133-328dab7c-c212-11e7-8fa1-516ece011d25.png)
However, if I `import platform` and `print platform.python_version()` I still see Python 2.7.14 being used. 
![screenshot from 2017-11-05 10-08-22](https://user-images.githubusercontent.com/8618330/32416154-ca8a243c-c212-11e7-8e1b-47f63155dded.png)
No wonder it can not find the modules installed with python 3.
![screenshot from 2017-11-05 10-09-28](https://user-images.githubusercontent.com/8618330/32416160-e226771c-c212-11e7-8a4a-3de9a9b95792.png)
No such problems with Jupyter notebooks using python 3:
![screenshot from 2017-11-05 10-23-39](https://user-images.githubusercontent.com/8618330/32416190-7340aa1a-c213-11e7-86f2-1ef1b3ac9a69.png)

**Comment by Goochimagne** [comment]
I got mine to work by using the conda install instead of python

**Comment by lgeiger** [comment]
Sorry for the truble.

Have you also run the same command for Python 3?
```bash
pip3 install ipykernel --upgrade
python3 -m ipykernel install --user
```

**Comment by moharsen** [comment]
@lgeiger That solved the problem. Thanks a lot.

**Comment by sohamchoudhury18** [comment]
@Lgeiger python3 -m ipykernel install --user this one helped me out Thanks

**Comment by HatemAlamir90** [comment]
@lgeiger Worked for me also. THANKS!

**Comment by jesusloplar** [comment]
Thanks a lot. I have been the whole day with this thing. Finally worked out 🥵

**Comment by wayneotweezy** [comment]
Thanks also this worked for me
