### ISSUE TITLE
Issue: Pweave "No kernel for grammar pweave markdown found"

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1073]
Not sure whether this is pweave or hydrogen issue - I'm getting "No kernel for grammar pweave markdown found" error from Hydrogen in Atom when I open and try to run a valid pmd. Hydrogen and python (py files) are running just fine. I can also see md files rendered properly in Markdown Preview in Atom. I have inserted [{"pweave markdown": "Python 3"}] under Kernel Gateways in Settings to no avail (I also tried uppercase - Pweave) - it didn't work with that setting blank either.

File tried (FIR_designp.pmd) - first one listed in examples: http://mpastell.com/pweave/examples/index.html

Any ideas?

Windows 10 Home Premium 64bit
Atom 64bit v 1.21.1
Hydrogen 2.0.1

![no-kernel-for-grammar-pweave-markdown-found](https://user-images.githubusercontent.com/32625394/32256819-6b6eb63e-be7f-11e7-8d4f-1747c4c37879.png)

![atom-community-packages-list](https://user-images.githubusercontent.com/32625394/32256823-6fa94a02-be7f-11e7-986a-63976ccb6a14.png)

**Comment by mpastell** [comment]
You typically get this error if you try to execute a line of markdown from `.pmd`. Try moving your cursor to a code block. Also remove the setting from kernel gateways, it is not needed.

**Comment by dsanalytics** [comment]
Pweave is supposed to render the entire file and not just execute one code block. Code block does execute, but how do I execute all code cells at once along with all markdown being properly rendered so that the entire file produces formatted rich text report?

Even if I execute each code cell manually, markdown still doesn't render - so how does one initiate that part?

If you don't mind my asking, how did you generate md and 2 html files from pmd files provided on your example page? See the screenshot.

![pweave-examples](https://user-images.githubusercontent.com/32625394/32263874-c2faadb6-bea9-11e7-9d1f-320a2429cd4a.png)

**Comment by dsanalytics** [comment]
Related: https://github.com/atom/atom/issues/16061

**Comment by mpastell** [comment]
Hydrogen doesn’t run pweave, but it can be used to execute code during development. You need to run pweave from command line to get html etc. The commands are in the examples page (below the table)

**Comment by dsanalytics** [comment]
@mpastell 

I checked two main packages shown on your examples page in relation to my how-did-you-generate-those-files question I asked above - md2html and pandoc (other people's packages you ship with pweave) - and none of them run python code contained in a pmd file in order to capture its output and generate the final document - i.e. markdown rich format combined with python output including plain text/charts/graphics if any. Those packages just convert static md to html. All those examples seem created manually by you - by running python separately, capturing python generated images manually (saving them to hdd, etc), and then going back and linking them in md after which you used md2html and/or pandoc to generate html - that is not literate programming! 

If not so, then please feel free to outline precisely on how one would go from a pmd file to a rich document (like pdf) automatically. By that I mean simply executing a command that would take pmd file, automatically execute all python code in each cell/section, capture all outputs of that automatically as well, render markdown too of course, and put all that together without any manual intervention from me. And no, what I'm asking is not explained anywhere on your pages. Thank you in advance.

**Comment by mpastell** [comment]
Run this from command line:

```
pweave -f md2html FIR_designp.pmd
```

Rest of the commands are also included in the example gallery,

**Comment by dsanalytics** [comment]
My apologies to @mpastell - I removed the post made in ignorance.

**Comment by BenRussert** [comment]
@dsanalytics Sounds like @mpastell answered the question here so I will close. Feel free to reply if you still have questions!
