### ISSUE TITLE
Hydrogen can't find jupyter kernel anymore

### ISSUE THREAD

**Issue by Elias427** [nteract/hydrogen#1078]
**Description:**

Hey, I was a happy hydrogen user until yesterday I updated Hydrogen to the current version 2.0.1. Now, when trying to execute code I get the following error

'/Users/username/anaconda3/envs/py36/bin/python' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Unfortunately you removed the kernel-specs settings, so I have no idea how to check, why hydrogen can't find my kernel anymore.

**Versions:**

Mac OSX
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by lgeiger** [comment]
Have you followed the [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html), especially https://nteract.io/kernels/python?

For more information see the [release notes of hydrogen 2.0](https://github.com/nteract/hydrogen/releases/tag/v2.0.0).

**Comment by BenRussert** [comment]
@Elias427 Were you able to try the installation instructions above? Let us know if you have questions or if we can close the issue.

**Comment by Elias427** [comment]
Thank you for your support. I reinstalled my jupyter kernel in the same way I did before and for some reason this solved the issue.
