### ISSUE TITLE
Output Area output area 

### ISSUE THREAD

**Issue by dayvidwesley** [nteract/hydrogen#1094]
I can only visualize in the "Output Area" shown in image 1
![captura de tela 2017-11-10 as 02 04 43](https://user-images.githubusercontent.com/30307097/32642615-ad0d9a6c-c5bc-11e7-8b6c-597e78508877.png)

I would like to get a similar view of image 2
![68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f31333238353830382f32303336303838362f37653033653532342d616330332d313165362d393137362d3337363737663232363631392e676966](https://user-images.githubusercontent.com/30307097/32642621-b55b5010-c5bc-11e7-9826-edc2256f1d61.gif)

**Comment by BenRussert** [comment]
If you want to switch back to inline output you will need to close the pane and it should switch back.  Also, check your hydrogen settings to make sure you don't have output area as the default.

**Comment by dayvidwesley** [comment]
Thank you, solved
