### ISSUE TITLE
'Hydrogen.kernelspec' could not set the default.

### ISSUE THREAD

**Issue by 6ubLunbI** [nteract/hydrogen#1096]
**Description:**

Hydrogen is not running recently. I can't recall I have done anything wrong in recent days. It used to work well. Now, it could not return the result. I check with the error message.
![capture](https://user-images.githubusercontent.com/24698757/32685758-909e63e0-c6d2-11e7-9b56-d3ee5d72eacd.JPG)
If I start the local kernel manually, the log shows like this and not result is returning.
![capture](https://user-images.githubusercontent.com/24698757/32685793-500238ba-c6d3-11e7-9c4e-ec491ef7cc84.JPG)
I have followed the procedures described in hydrogen site like below.
python -m pip install ipykernel
python -m ipykernel install --user

Anyone knows what's going on?

**Versions:**
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by 6ubLunbI** [comment]
For those who may suffer from the same issue, just downgrade your atom from 1.22 to 1.21 and downgrade your hydrogen to 1.23.0, everything just work fine then.

**Comment by BenRussert** [comment]
You probably needed to save your file. The kernelspec config error can be ignored after 2.0 it is not used.

**Comment by 6ubLunbI** [comment]
Thanks, I do not realize it need to be saved, which works previously.
