### ISSUE TITLE
Problem with Jupytor Kernel

### ISSUE THREAD

**Issue by JakartaLaw** [nteract/hydrogen#1099]
**Description:**

I have used Jupyter Notebooks for some time but i want to change to Atom and have therefore installed the Hydrogen. However when i run script i get following error message:

"No kernel for grammar Python found

Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it. "

**Steps to Reproduce:**

1. create .py file and save.

"import pandas as pd"

2. try to run the code.
Then i get the error message.

If i from the terminal run: 

I get: jupyter kernelspec list --json
{
  "kernelspecs": {
    "ir": {
      "resource_dir": "/Users/Jeppe/anaconda/share/jupyter/kernels/ir",
      "spec": {
        "argv": [
          "R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "R",
        "language": "R"
      }
    },
    "python3": {
      "resource_dir": "/Users/Jeppe/anaconda/lib/python3.6/site-packages/ipykernel/resources",
      "spec": {
        "argv": [
          "/Users/Jeppe/anaconda/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

hydrogen: 2.0.1
atom: 1.22.0

**Comment by lgeiger** [comment]
Have you followed the [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html), especially the kernel installation as outlined at https://nteract.io/kernels/python?

**Comment by randomstuff** [comment]
I had a similar problem when trying to use a kerel from a venv. Hydrogen apparently does not lookup kernels in the current venv (which kind-of make sense) and I needed to do:

    JUPYTER_PATH=/path/to/my/venv/share/jupyter

If you do not want to install the kernel in [`--user`](https://nteract.io/kernels), you might want to use something similar:

    JUPYTER_PATH=/Users/Jeppe/anaconda/share/jupyter

**Comment by kylebarron** [comment]
Closing as stale
