### ISSUE TITLE
Cant use kernel interupt. Get Error "Kernel Interruption is Currently Not Supported in Windows"

### ISSUE THREAD

**Issue by nmittleman-toast** [nteract/hydrogen#1109]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
Closing as a duplicate of #597
