### ISSUE TITLE
Display a folium map inline

### ISSUE THREAD

**Issue by mdmadhu** [nteract/hydrogen#1112]
When I try to display a folium map inline (which works in Jupyter Notebook and Jupyter Lab) within Hydrogen, I get a small box with an 'x' below, but nothing else appears. Is there something I am not doing right? The code I am trying to run is:
```
import folium
map_osm = folium.Map(location=[45.5236, -122.6750])
map_osm
```

Which OS and which version of Hydrogen and Atom are you running?
Atom 1.22.1 / Hydrogen 2.10

**Comment by lgeiger** [comment]
Closing in favor of #1069
