### ISSUE TITLE
No Kernels Installed

### ISSUE THREAD

**Issue by robtarr** [nteract/hydrogen#1114]
**Description:**
Installed Hydrogen and the IJavascript kernel. When I run `Hydrogen: Update Kernels` I get a message back that says: `No Kernels Installed - No kernels are installed on your system so you will not be able to execute code in any language.`

[Description of the issue]

**Steps to Reproduce:**

1. Installed Hydrogen
2. `npm install -g ijavascript`
3. Execute `Hydrogen: Update Kernels`

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Mac OS X 10.12.6
Atom 12.22.1
Hydrogen 2.1.0
IJavascript 5.0.20

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**
I turned on debugging, the only thing I see in the console is `Hydrogen: findCodeBlock: 0`

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
I think you need to run `ijsinstall` to fully setup `ijavascript`: https://github.com/n-riesco/ijavascript#ijsinstall-ijavascript-kernel-spec-installer

**Comment by lgeiger** [comment]
Feel free to reopen if you need more help.

**Comment by rpalloni** [comment]
I tried to install ijsinstall but does not work.

In the pic  the log (running as admin)
![error](https://user-images.githubusercontent.com/17080117/36024633-9f77a49e-0d90-11e8-8844-40f10bd7a59d.PNG)

And actually this page **https://registry.npmjs.org/ijsinstall** is empty

**Comment by BenRussert** [comment]
Did you already `npm install -g ijavascript`? If so try running `ijsinstall` since it is a part of `ijavascript` once that is installed

**Comment by rpalloni** [comment]
That was the first thing I did as recommended. But the only thing that worked for me was to put the JS kernel here: 
![image](https://user-images.githubusercontent.com/17080117/36088986-eca80952-0fd9-11e8-89a8-948fd82e1749.png)

Anyway, I would recommend to follow "the Python way" to structure the folder tree. It is much more intuitive
![image](https://user-images.githubusercontent.com/17080117/36089071-58a92474-0fda-11e8-9394-11018602f476.png)

**Comment by n-riesco** [comment]
For future readers:
- I don't recommend the installation of `ijavascript` using the admin account (unless you know what you're doing)
- if after running `npm install -g ijavascript`, you can't run `ijsinstall` (because it isn't in your PATH), it can be run using the following command instead `%appdata%\npm\ijsinstall`
