### ISSUE TITLE
Can’t get latex render via sympy to work

### ISSUE THREAD

**Issue by renec112** [nteract/hydrogen#1119]
I can’t get latex output from the sympy package. I use the command init_printing(), and i tried updating all my packages (with anaconda). I also have mathjax and matplotlib installed.

I get this unicode output:
![387bdb7e-f33f-49b0-af61-0702671d0950](https://user-images.githubusercontent.com/18447239/33116671-e7e1291c-cf65-11e7-910a-442ee9e4d46b.png)

But i’m looking to get rid of the Unicode output and get some clean latex like so:

![4f38b3a7-582a-43b7-aff2-7af7c7b481be](https://user-images.githubusercontent.com/18447239/33116701-02bf333c-cf66-11e7-983d-db652217ad29.png)

Anyone know what I could try? Would love your input

**Comment by lgeiger** [comment]
Checkout this example: https://nteract.gitbooks.io/hydrogen/docs/Usage/Examples.html#latex

**Comment by renec112** [comment]
Thank you very much @lgeiger ! somehow pprints messes things up.
Have experinced this error before?
![image](https://user-images.githubusercontent.com/18447239/33137118-542dccf6-cfa7-11e7-943d-8421bc68ea92.png)

Now the latex isn't being rendered, but python understands it's latex.. I tried updating miktex and installed mathjax.. No luck :/

**Comment by lgeiger** [comment]
You won't need miktex or separately install mathjax. This won't have any effect.

What is the output of the example run in a new file?
```python
import sympy as sp
sp.init_printing(use_latex='mathjax')

x, y, z = sp.symbols('x y z')
f = sp.sin(x * y) + sp.cos(y * z)
sp.integrate(f, x)
```

**Comment by renec112** [comment]
Thank you @lgeiger  i really appreciate your suggestions. This is what i get, same error in a brand new file:
![image](https://user-images.githubusercontent.com/18447239/33140011-1c76884a-cfaf-11e7-8526-4d91e01b31e9.png)

**Comment by lgeiger** [comment]
Which versions of Atom, Hydrogen and sympy are you using?

**Comment by renec112** [comment]
Atom version:
1.22.1

Hydrogen version:
2.10

Sympy version:
1.1.1

**Comment by renec112** [comment]
Do you have any ideas i could try @lgeiger? I would very much  appreciate your tips

**Comment by lgeiger** [comment]
Does it work in jupyter notebook?

Could you post a screenshot of the Developer console as shown in our [debugging guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#debugging-guide)

**Comment by renec112** [comment]
Thank you @lgeiger.  
This is the output from hydrogen:
![errors](https://user-images.githubusercontent.com/18447239/33212087-b776f7a8-d121-11e7-8e93-27507a652320.png)

And running this in jupyter notebook is no problem:
![test](https://user-images.githubusercontent.com/18447239/33212088-b7906774-d121-11e7-8b89-6fd61c00ea22.png)

strangely i tried installing everything on another computer, and it worked like a charm

**Comment by renec112** [comment]
ah i found the error!
apparently my package:
Latex: [preview-inline](https://github.com/mangecoeur/preview-inline) blocks between $$ and $$. I thought this package only worked on .tex files, and was disabled on .py files. 

@lgeiger  Thank you very much for your help. Checking error messages as you suggested, and seeing the kite package throwing many errors, made me disable all packages too see if it made a difference :) !

**Comment by lgeiger** [comment]
Glad it's working.

If we go with https://github.com/nteract/nteract/issues/2115 we'll be able to support latex rendering without modifying the global HTML header.

**Comment by tribbloid** [comment]
@renec112 good discovery, my tests suggest that it also affects hydrogen
