### ISSUE TITLE
ipython plots not showing

### ISSUE THREAD

**Issue by schlichtanders** [nteract/hydrogen#112]
Dear Hydrogen team,

I just started to use hydrogen and everything is working but the plots.
It shows ``[<matplotlib.lines.Line2D at 0x7f009fd1b950>`` instead of a nice plot

I tried plotting within qtconsole solely and get the same output. Here I have to enable ``%matplotlib inline`` to get the nice plots.
Maybe such is missing when starting the ipython kernel?

hoping for help,
best,
Stephan

**Comment by willwhitney** [comment]
You'll definitely have to run `%matplotlib inline` to make them work. This is because the IPython kernel  doesn't do this itself.

I don't want to add any kernel-specific code to Hydrogen, but I do have plans to (when I get the time...) implement a language plugin system for Hydrogen that would allow code to be run when the kernel is started and/or before user code.

**Comment by schlichtanders** [comment]
Thank you very much for this fast clarification - and of course for
creating such a lovely plugin.
I am looking forward to language specific configurations

a simple json configuration file keyworded by standard filenames, referring
to values which represent the lines to be executed in the beginning could
do the trick already, doesn't it? (or is this too insecure?)

**Comment by willwhitney** [comment]
My rationale for doing it with extensions is that there are several pressing language-specific features* which are going to take a nontrivial amount of code. By building an API for Hydrogen extensions, any language-specific features can be independently maintained and distributed by the people who use those languages. I don't want to have any language-specific code in the core Hydrogen package, and I don't want every user to have to go add this themselves.

*most notably, a per-language function for finding the preceding block of code to execute from the buffer

**Comment by schlichtanders** [comment]
thanks for explaining,
that would be a great feature,

looking forward to the future,
best,
Stephan

**Comment by rgbkrk** [comment]
> My rationale for doing it with extensions is that there are several pressing language-specific features* which are going to take a nontrivial amount of code. By building an API for Hydrogen extensions, any language-specific features can be independently maintained and distributed by the people who use those languages. I don't want to have any language-specific code in the core Hydrogen package, and I don't want every user to have to go add this themselves.

> *most notably, a per-language function for finding the preceding block of code to execute from the buffer

Wow that's sounding great.

**Comment by n-riesco** [comment]
Closed by #195
