### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by jbsldn75** [nteract/hydrogen#1123]
**Description:**

Unable to install hydrogen. Receive the following error 

(node:6969) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Steps to Reproduce:**

1. apm install hydrogen
2. (or) clicked install hydrogen in atom

**Versions:**
OS: Antergos Linux x86_64
Kernel: 4.13.12-1-ARCH
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

(node:6969) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing hydrogen to /root/.atom/packages ✗

> canvas@1.6.7 install /tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild

> zeromq@4.6.0 install /tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/canvas/build'
gyp ERR! System Linux 4.13.12-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
module.js:544
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
module.js:544
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1171025-6969-1g3x3p4.z8q/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.10.9 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.10.9 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-1171025-6969-1g3x3p4.z8q No description
npm WARN apm-install-dir-1171025-6969-1g3x3p4.z8q No repository field.
npm WARN apm-install-dir-1171025-6969-1g3x3p4.z8q No README data
npm WARN apm-install-dir-1171025-6969-1g3x3p4.z8q No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2017-11-25T18_20_28_570Z-debug.log

**Comment by lgeiger** [comment]
Looks like you're running into https://github.com/atom/apm/issues/680

**Comment by jbsldn75** [comment]
@lgeiger 

Thanks for the link.  Going back to the Arch wiki, it says to install a number of specific apm packages to make sure atom plays nice with Arch.  I didn't see this before.  Thanks for directing me to that.  For those having a problem installing hydrogen using apm in Arch, be sure you have the relevant atom packages identified on the wiki.

After installing the packages recommended on the wiki I was able to install hydrogen.  However, 
I still have the error:

 (node:10598) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

right before. May have to look elsewhere to have it solved.
