### ISSUE TITLE
[Cling kernel] Can't run "C++" on "C++17" kernel.

### ISSUE THREAD

**Issue by Houkime** [nteract/hydrogen#1129]
**Description:**

When trying to run C++ via [Cling](https://github.com/root-project/cling) Jupyter core, there are many versions of C++ that this kernel supports.  
However, in Atom there is only one "C++". Thereby although Hydro detects capability to interpret "C++ 17", "C++ 16" etc. via Cling, it just cannot run vague "C++" that Atom detects since there is no "C++" kernel in Cling.
Atom has no option to set lang to C++ 17.
And Hydrogen has no option to set a default CPP ver to run when it stumbles upon vague "C++".

**Steps to Reproduce:**

1. Install Jupyter and Cling.
2. Install Cling as a Jupyter kernel.
3. Try to run C++ code in Atom with Hydrogen.
(It reports detection of a bunch of Cling CPP cores but not some abstract "C++")

**Versions:**
OS: Arch (5.11.2017)
Atom 1.22.1
Hydrogen 2.1.1
[Cling-git](https://github.com/root-project/cling) (cloned 28.11.2017)

**Comment by nikitakit** [comment]
It appears that the cling kernels do not provide a "language" field (e.g. [see here][1]). Adding a `"language": "C++"` entry to this file would probably solve this issue. Not sure if there is any other solution for getting this to work with a release build of Hydrogen.

This is actually the first time I'm seeing a kernel without a "language" field, as I do believe that it is actually a required field.

[1]: https://github.com/root-project/cling/blob/master/tools/Jupyter/kernel/cling-cpp17/kernel.json

**Comment by Houkime** [comment]
Yep, this works.

**Comment by lgeiger** [comment]
Thanks for investigating. Closing in favor of https://github.com/root-project/cling/pull/196
