### ISSUE TITLE
No Kernel for Grammar HTML found. 

### ISSUE THREAD

**Issue by lagraf05** [nteract/hydrogen#1133]
**Description:**
<img width="454" alt="screen shot 2017-12-02 at 11 19 47" src="https://user-images.githubusercontent.com/34185510/33514918-45d7d03a-d753-11e7-92c7-3cea1a929b5c.png">

[Description of the issue]

Apologies if the answer to this is *painfully* obvious to more experienced users, but - to my end - I've done what I need to do!

I essentially want to be able to 'in real time' view changes to my HTML, which is why I installed Hydrogen. After getting Anaconda Navigator for the purposes of getting the correct kernels (again, I am VERY new to this), I tried to run Hydrogen as a test. The following error popped up, attached. 

I'm not entirely sure where to go from here? Apparently I'm not the only one with this issue, but I also suspect I am somewhat more green than most as well. 

**Steps to Reproduce:**

1. Open Guru3D.html
2. Run Hydrogen from the 'Packages' toolbar. 

Attached error then pops up, and I'm not sure where to go from here. 

**Versions:**

MacOSX High Sierra 10.13.1 (17B1003).

Atom 1.22.1 

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
Hydrogen requires users to have a language-specific kernel installed in order to run code.

I don't think there exists a [Jupyter kernel for HTML](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) therefor we cannot support this workflow in Hydrogen.
You can just open the HTML file in your web-browser of choice to get a preview of the rendered HTML.

**Comment by pbrilius** [comment]
However, I'd require **PHP** kernel grammar.
