### ISSUE TITLE
Fail to install Hydrogen

### ISSUE THREAD

**Issue by pingshunhuangalex** [nteract/hydrogen#1137]
**Description:**

Fail to install Hydrogen on a cleanly installed laptop

**Steps to Reproduce:**

1. Install windows 10
2. Install atom beta
3. Install Hydrogen

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

```
Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\SPHS\.atom\packages\Hydrogen\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by pingshunhuangalex** [comment]
Found the solution here: https://github.com/nteract/hydrogen/issues/1033

It seems installing from console does work, but it doesn't really resolve the issue described above.

I'll leave the ticket open for now and let the you guys decide whether to close it. Thanks.

**Comment by lgeiger** [comment]
Glad it works. This looks like a problem with `apm`.

@pingshunhuangalex Do you want to add a small note to our [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html) recommending users to install via the command line?

**Comment by pingshunhuangalex** [comment]
Done. https://github.com/nteract/hydrogen/pull/1138

**Comment by pingshunhuangalex** [comment]
https://github.com/atom/atom/issues/14913

**Comment by lgeiger** [comment]
Thanks for investigating.

**Comment by kylebarron** [comment]
@lgeiger I also got this error while upgrading to Hydrogen 2.2.0, despite using the command line.
```
> apm install Hydrogen
Installing Hydrogen to /home/kyle/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/kyle/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/usr/share/atom/resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /usr/share/atom/resources/app/apm/lib/install.js:476:42
    at fn (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

It seems that up to 2.1.1, this package used a folder named `~/.atom/packages/hydrogen`, with `hydrogen` in lower case, while in 2.2.0, it tries to install in `~/.atom/packages/Hydrogen`, with `Hydrogen` in title case. Linux is case sensitive, **so these are two different places**. I'm guessing that's the issue at play here.

While debugging, I uninstalled `hydrogen`, and then `apm install hydrogen` gave the traceback above. After also uninstalling `hydrogen-launcher`, `apm install hydrogen` gave a checkmark but then wasn't recognized from Atom. 

```
> apm install hydrogen                
Installing hydrogen to /home/kyle/.atom/packages ✓
> apm install hydrogen-launcher
Installing hydrogen-launcher to /home/kyle/.atom/packages ✓
```
![image](https://user-images.githubusercontent.com/15164633/34133367-5529a60e-e422-11e7-8350-0897619e79d8.png)

**Comment by lgeiger** [comment]
I'm happy to change the name to lower case. This looks like a issue in Atom: https://github.com/atom/settings-view/issues/1018

Though I wonder if we break our publishing if we change the name.

**Comment by kylebarron** [comment]
First, the installation of Hydrogen worked fine until v2.2.0 (I also updated Atom to 1.23.1 recently, so that could be a compounding issue). Even though the package name had been spelled with a capital `H`, the installation folder was with a lower case `h`, and everything worked fine.

I'm definitely not an expert and wouldn't want you to implement a potentially breaking change just on my advice. 

In the thread you linked to, icetee said that NPM packages [can't have uppercase characters](https://docs.npmjs.com/files/package.json), so maybe that is the issue.

**Comment by illpack** [comment]
I am getting the same error.
Updated all my packages on **Atom 1.23.1 x64** inside Windows 7, Hydrogen was working perfectly.
All packages updated. 
Hydrogen failed to install, even from the command line as suggested. 

Traceback:
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\asdf\.atom\packages\Hydrogen\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\asdf\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\asdf\AppData\Local\atom\app-1.23.1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\asdf\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\asdf\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Any hints?

Thanks,

**Comment by kylebarron** [comment]
By the way it might help to reopen this issue so you have fewer new issues being created.

**Comment by DerektheDev** [comment]
I tried `apm install hydrogen` (lowercase), and it worked.

**Comment by illpack** [comment]
Looks fixed and working!
Thanks!

**Comment by kylebarron** [comment]
@lgeiger This still doesn't work on Ubuntu 16.04. Removing Hydrogen and then running `apm install hydrogen` downloads Hydrogen into `~/.atom/packages/hydrogen`, but it isn't found in the command prompt. 

![image](https://user-images.githubusercontent.com/15164633/34233305-9b39746c-e5b2-11e7-9d33-769623f7d237.png)

**Comment by tonydero** [comment]
Installing with lowercase `apm install hydrogen` and then restarting Atom got it to work and show in the command pallet in Ubuntu 16.04 LTS for me.

**Comment by kylebarron** [comment]
FYI @lgeiger @tonydero this doesn't work again when trying to upgrade to 2.2.1. 

```
kyle at desktop in ~/.atom/packages                                       13:26
> apm install hydrogen       
Installing hydrogen to /home/kyle/.atom/packages ✓
kyle at desktop in ~/.atom/packages                                       13:26
> apm list --installed | grep hydrogen
├── hydrogen@2.2.0
├── hydrogen-launcher@1.2.1
kyle at desktop in ~/.atom/packages                                       13:26
> apm uninstall hydrogen              
Uninstalling hydrogen ✓
kyle at desktop in ~/.atom/packages                                       13:28
> apm install hydrogen  
Installing hydrogen to /home/kyle/.atom/packages ✓
kyle at desktop in ~/.atom/packages                                       13:28
> apm list --installed | grep hydrogen
├── hydrogen-launcher@1.2.1
```

**Comment by kylebarron** [comment]
My bad, the package name returned to title case (i.e. the package folder in 2.2.0 was `~/.atom/packages/hydrogen`, while the package folder in 2.2.1 is `~/.atom/packages/Hydrogen` again). After two restarts of Atom the package appeared.

Note however that I still received an error when trying to update from inside Atom.

**Comment by lgeiger** [comment]
As mentioned above this is a upstream issue that will be fixed in the next Atom version: https://github.com/atom/settings-view/issues/1018
