### ISSUE TITLE
Fix failing flow tests

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#1139]
It looks like the latest release of React breaks our flow typings.

This cause our CI builds to fail.

**Comment by BenRussert** [comment]
I'll look into this next chance I get. Has anybody looked at this and run into trouble?

**Comment by lgeiger** [comment]
Awesome. I took a quick look when I created the issue but wasn't able to figure it out right away.

**Comment by BenRussert** [comment]
Should we downgrade React temporarily? Either way, I'll take a look tonight.

**Comment by lgeiger** [comment]
For now I'm good with everything that makes Travis happy :wink:

**Comment by lgeiger** [comment]
Looks like this might be a easy fix: https://github.com/nteract/hydrogen/pull/1144#issuecomment-352131807

**Comment by BenRussert** [comment]
I'm trying this now. Doesnt look like it's working.
