### ISSUE TITLE
Cant install Hydrogen package

### ISSUE THREAD

**Issue by DoblDon** [nteract/hydrogen#1141]
**Description:**Installing Hydrogen@2.1.1 failed

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?Windows 7 /Hydrogen:2.1.1 and Atom:1.23.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:** fs.js:640  Return binding.open(pathMod)

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
Please try installing it from the command line via `apm install hydrogen`

**Comment by DoblDon** [comment]
Worked!Thanks for prompt reply.


Sent from Yahoo Mail. Get the app 

    On Tuesday, December 12, 2017, 3:42:31 PM EST, Lukas Geiger <notifications@github.com> wrote:  
 
 
Please try installing it from the command line via apm install hydrogen
