### ISSUE TITLE
No kernel for grammar Markdown found

### ISSUE THREAD

**Issue by jasonleonhard** [nteract/hydrogen#1153]
Error:

"No kernel for grammar Markdown found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it."

https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html

At the bottom of this link it shows:  "Multiple kernels inside one rich document
If you are working in a markup file that supports highlighted code blocks, we can handle multiple kernels per file. This way you can write your documentation, readme or paper together with your code while retaining the interactivity of Hydrogen."

Unfortunately even when installing language-markdown at the command line or inside atoms package manager, I still get the error. Any thoughts how it might be remedied? 

Looks like a cool feature!

Thanks,
Jason

**Comment by BenRussert** [comment]
Your cursor should be within a code section of the markdown file like in [this gif](https://cloud.githubusercontent.com/assets/13285808/24365090/0af6a91c-1315-11e7-92c6-849031bf9f6a.gif)

This way hydrogen knows what kernel to run based on the grammar inside the code block. If your cursor is in the other sections of the file, the grammar at that cursor point will be markdown and you will see the error you describe.

**Comment by lgeiger** [comment]
I'm confident that this solution will fix the problem.

@jasonleonhard Do you want to send a PR to clarify our documentation for multi language grammars?

**Comment by jasonleonhard** [comment]
Thank you. I found that the file must be saved, opened and closed before it would to execute as well as the cursor placement inside of the block to be executed.

Awesome Hydrogen!
