### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by olegantonyan** [nteract/hydrogen#1154]
I'm probably stupid because I just cannot figure out how to use it.
`apm install hydrogen` successful, I can see hydrogen installed. Now what? I can open `*.ipynb` files, but these are just plain json. How to use atom instead of browser to work with ipynb files? Where to paste `http://localhost:8888/?token=blablabla` or somehow connect to a running `jupyter notebook`?

openSUSE Tumbleweed x86-64
Atom    : 1.25.0-dev-0b52835bc
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by BenRussert** [comment]
Check out our docs, starting with [this page](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html)

Hydrogen works on plain text (e.g. `.py`, `.R`) files if you have a kernel installed. It can connect to notebook servers as you describe, but I would recommend starting a local kernel with hydrogen first to make sure things are working on your machine.

Feel free to reply w/ questions!

**Comment by olegantonyan** [comment]
Thank you @BenRussert 
It works on py files, I can hit ctrl+enter and it will print the output (just like Avdi has in his emacs https://www.rubytapas.com/)

However, what I actually want is to use atom (or any other editor) instead of jupyter notebook web ui to work with ipynb files. Is this doable with hydrogen?

**Comment by BenRussert** [comment]
Hydrogen does not currently support the editing of `.ipynb` files like you describe. Hydrogen can generate ipynb from a text file, but not interactively edit them.

There is an older open issue #75 on this.
