### ISSUE TITLE
Kernel selector displayed when Language Mappings set

### ISSUE THREAD

**Issue by scriptjs** [nteract/hydrogen#1156]
**Description:**
Hello. Display kernel selector pops up offering a choice of the jp-Babel (Node.js) and JavaScript (Node.js) kernels. Selecting  jp-Babel works with ES6 code but not sure why I am offered a kernel selection when configured in Hydrogen settings.

**Steps to Reproduce:**
Install babel kernel 
```
npm install -g jp-babel
jp-babel-install
```

Set Language Mappings in Atom
```
{"babel": "JavaScript"}
```

**Versions:**
OS: MacOS: 10.12.6
Hydrogen: 2.2.0
Atom:

**Comment by lgeiger** [comment]
This is intended behavior. The language mapping is only used to figure out the language from a Atom grammar which can have different names than the ones used in Jupyter land or vice versa.

We're happy to receive PRs clarifying this better in the settings 😄

**Comment by scriptjs** [comment]
I'm sorry, could you please clarify. I believed the mapping to mean one kernel to one language grammer in Atom. The settings make that explicit. I don't understand how I am getting an implicit mapping to two kernels. There is nothing in the settings that would make a one to one mapping more explicit and the implicit behaviour is confusing.
