### ISSUE TITLE
Hydrogen gateways option is not found

### ISSUE THREAD

**Issue by yelled1** [nteract/hydrogen#1164]
I am behind corp wall/proxy. So, I cannot install anything. So, I copied over all packages from ~/.atom for my Win7 (From Win10 machine at home).
For some reason I do not get Hydrogen gateways in Settings menu, which is available in the original home machine I copied the packages from. Not sure if some protocol is not available due to corp policy.
What would make this happen? How do I ask someone to open, tweak, or set something.
I need to connect to my Data Sci Linux cloud.
Need a clue. 
Thanks much in Adv!

**Comment by nikitakit** [comment]
Maybe there's a chance that simply copying over the package folders doesn't correctly set up the settings? To test this you could check if hydrogen has any other settings available, and whether the other packages you copied over do, too.

I haven't experienced this myself and don't know of any recommended solution, but here are some workarounds that might help:
* Installing packages directly, while setting up apm to [use a proxy](https://github.com/atom/apm#using-a-proxy)
* Install hydrogen from github at home. Then copy over the source checkout (including the node_modules folder) and use apm to install from the repo at work. By going through the official install process maybe settings will work. See also [here](https://stackoverflow.com/a/44964573/521933)
* If hydrogen works, but the settings pane doesn't, you can always edit `config.cson` manually (you can access it as "Config..." somewhere from Atom's menu). You may have to try this on your home computer to figure out the syntax.

**Comment by yelled1** [comment]
Than u for pointing thoese, but still seems like a proxy prob:
(My apologies for Long lines Below)
1st:
➤ ./apm.cmd install hydrogen
Installing hydrogen to C:\Users\myself.NAM\.atom\packages failed
Request for package information failed: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
 (5 attempts) (ECONNRESET)
2nd: npm install gives me                          
➤./npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myself.NAM\AppData\Local\atom\app-1.23.1\resources\app\apm\bin\npm-debug.log

here's my apm config
 ➤ ./apm.cmd config list
; cli configs
globalconfig = "C:\\Users\\myself.NAM\\.atom\\.apm\\.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 win32 x64"
userconfig = "C:\\Users\\myself.NAM\\.atom\\.apmrc"

; environment configs
node-gyp = "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\\\..\\node_modules\\node-gyp\\bin\\node-gyp.js"

; userconfig C:\Users\myself.NAM\.atom\.apmrc
http-proxy = "http://ourproxy.root.net:9999"
https-proxy = "https://ourproxy.root.net:9999/"
progress = true
strict-ssl = false

; globalconfig C:\Users\myself.NAM\.atom\.apm\.apmrc
cache = "C:\\Users\\myself.NAM\\.atom\\.apm"

; node bin location = C:\Users\myself.NAM\AppData\Local\atom\app-1.23.1\resources\app\apm\bin\node.exe
; cwd = C:\Users\myself.NAM\AppData\Local\atom\app-1.23.1\resources\app\apm\bin
; HOME = C:\Users\myself.NAM
; "npm config ls -l" to show all defaults.

# here proxy(s) are null or not set
➤ ./npm.cmd config ls -l
; cli configs
long = true
user-agent = "npm/3.10.10 node/v6.9.5 win32 x64"

; environment configs
node-gyp = "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\\\..\\node_modules\\node-gyp\\bin\\node-gyp.js"

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\myself.NAM\\appdata\\roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "/bin/vim.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\etc\\npmrc"
globalignorefile = "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\myself.NAM\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "6.9.5"
npat = false
onload-script = null
only = null
optional = true
parseable = false
prefix = "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin"
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "C:\\Users\\myself.NAM\\AppData\\Local\\Temp\\39\\Mxt104\\tmp"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\myself.NAM\\.npmrc"
version = false
versions = false
viewer = "browser"

**C:\Users\myself.NAM\AppData\Local\atom\app-1.23.1\resources\app\apm\bin\npm-debug.log**
**Here are the errors:**
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
41 verbose stack     at errnoException (dns.js:28:10)
41 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 verbose cwd C:\Users\myself.NAM\AppData\Local\atom\app-1.23.1\resources\app\apm\bin
43 error Windows_NT 6.1.7601
44 error argv "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\myself.NAM\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "install"
45 error node v6.9.5
46 error npm  v3.10.10
47 error code ENOTFOUND
48 error errno ENOTFOUND
49 error syscall getaddrinfo
50 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
51 error network This is most likely not a problem with npm itself
51 error network and is related to network connectivity.
51 error network In most cases you are behind a proxy or have bad network settings.
51 error network
51 error network If you are behind a proxy, please make sure that the
51 error network 'proxy' config is set properly.  See: 'npm help config'
52 verbose exit [ 1, true ]
