### ISSUE TITLE
No kernel for grammar Sage found

### ISSUE THREAD

**Issue by Doekeb** [nteract/hydrogen#1185]
**Description:**

I can't seem to get hydrogen to recognize sagemath jupyter kernel.

**Steps to Reproduce:**

1. Set "Sage" as atom language in my document

![screen shot 2018-01-10 at 9 31 01 pm](https://user-images.githubusercontent.com/13689478/34810004-9c8673b4-f64d-11e7-8422-60a2336cffa3.png)

2. In Hydrogen settings, use {"sagemath": "Sage"} for Language Mappings

![screen shot 2018-01-10 at 9 29 52 pm](https://user-images.githubusercontent.com/13689478/34809984-77dffc2e-f64d-11e7-899d-84be06430514.png)

3. Receive "No kernel for grammar Sage found" error message

![screen shot 2018-01-10 at 9 31 36 pm](https://user-images.githubusercontent.com/13689478/34810015-ae593f36-f64d-11e7-8ccc-f7c563cf4c74.png)

**Versions:**

macOS 10.12.6
Hydrogen 2.2.1
Atom 1.23.3

**Logs:**

Atom Console:

![screen shot 2018-01-10 at 9 32 34 pm](https://user-images.githubusercontent.com/13689478/34810038-cf19a684-f64d-11e7-84b3-d98484b57440.png)

Output of "jupyter kernelspec list":

![screen shot 2018-01-10 at 9 34 11 pm](https://user-images.githubusercontent.com/13689478/34810086-2695c032-f64e-11e7-822c-ddce77208378.png)

@n-riesco
@gmd7

**Comment by lgeiger** [comment]
Could you also post the output of
`jupyter kernelspec list --json`?

**Comment by Doekeb** [comment]
Output of "jupyter kernelspec list --json":

![screen shot 2018-01-11 at 11 29 48 am](https://user-images.githubusercontent.com/13689478/34843260-cec58f7a-f6c2-11e7-9050-2c3e614a5949.png)

Figured out what was wrong, but for posterity:

Needed {"language": "sage"} instead of {"language": ""} so I added the entry {"language": "sage"} in /path/to/kernel/kernel.json. Everything works now!

**Comment by fippu** [comment]
I have the same problem:

`jupyter kernelspec list --json`:

```
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/Users/imh/Library/Jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/opt/local/bin/python3",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "sagemath": {
      "resource_dir": "/opt/local/share/jupyter/kernels/sagemath",
      "spec": {
        "argv": [
          "/Applications/SageMath/local/bin/sage",
          "--python",
          "-m",
          "sage.repl.ipython_kernel",
          "-f",
          "{connection_file}"
        ],
        "env": {
          "SAGE_ROOT": "/Applications/SageMath/sage"
        },
        "display_name": "SageMath 8.8",
        "language": "sage",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}
```

When I run `Hydrogen: Update kernels` it only shows the `Python 3` kernel, which I find strange.

**Comment by wadethestealth** [comment]
Did you follow the same steps as the user above ie language mapping and using a sage grammar?

**Comment by fippu** [comment]
@wadethestealth Yes, I would say so. 

Atom 1.40.1
Hydrogen 2.12.0
language-sage 0.3.2

New file, setting grammar do `source.Sage`. Kernel is installed in jupyter as shown above. Hydrogen has language mappings set to `{ "sagemath":"Sage", "python": "magicpython"}`.

However, as I wrote, is consistent in its behaviour, as it clearly states it is aware of the `Python 3` kernel only whenever I have it update de kernels.

**Comment by wadethestealth** [comment]
@benrussert @aviatesk

**Comment by fippu** [comment]
I was able to solve the issue by following this comment: <https://github.com/nteract/hydrogen/issues/1074#issuecomment-514080192>

I copied `/opt/local/share/jupyter/kernels/sagemath` to `~/Library/Jupyter/kernels/` and now it works.

I have read that hydrogen searches for kernels in all paths listed in the `data` section of `jupyter --paths`.  Maybe that's not working correctly. The path `/opt/local/share/jupyter` is listed there, but as the last line. The path `~/Library/Jupyter` is the first entry. And now that the kernel is in there, hydrogen finds it.

**Comment by wadethestealth** [comment]
@fippu I am glad you figured it out. We still may need to investigate further on our side 

cc: @aviatesk @BenRussert
