### ISSUE TITLE
Cannot install hydrogen from apm (self signed certificate)

### ISSUE THREAD

**Issue by SteveBronder** [nteract/hydrogen#1188]
**Description:**

Attempting to install hydrogen produces the error
```
Unable to download https://www.atom.io/api/packages/hydrogen/versions/2.2.2/tarball: self signed certificate in certificate chain
```

**Steps to Reproduce:**

```bash
apm install hydrogen
```

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

```bash
$ atom --version
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```bash
apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 3.6.1
git 2.15.1
```

**Comment by lgeiger** [comment]
Looks like you're behind a firewall. Checkout https://github.com/atom/apm#behind-a-firewall

**Comment by SteveBronder** [comment]
Yep! apologies and ty
