### ISSUE TITLE
Imported file: output only changes when you restart the kernel

### ISSUE THREAD

**Issue by tweakimp** [nteract/hydrogen#1189]
**Description:**
You change something in a file that you import.
In order to see output changes in the file that imports that file, you have to restart the kernel. Very annoying, thats two extra clicks every time I want to change something and test it.

**Steps to Reproduce:**
1. Create main.py:
```python
import foo

foo.testprint()
```
2. Create foo.py (in the same directory):
```python
def testprint():
    print("test")
```
3. Run main py.
Output: `test`

4. Change foo.py to:
```python
def testprint():
    print("test1")
```
(Save foo.py, doesn't change anything.)
5. Run main.py:
Output: `test` 

6. Restart kernel and run main.py
Output: `test1` 

**Versions:**
Which OS and which version of Hydrogen and Atom are you running?
Windows 10 x64, Hydrogen 2.2.2, Atom 1.23.3 x64

**Logs:**
I don't think the log file helps, but I added a log.txt.
[log.txt](https://github.com/nteract/hydrogen/files/1630470/log.txt)

**Comment by n-riesco** [comment]
This is actually a Python question. See the answer [here](https://stackoverflow.com/questions/437589/how-do-i-unload-reload-a-python-module#437591) on StackOverflow.

**Comment by tweakimp** [comment]
You were right, thanks.

**Comment by lgeiger** [comment]
There is a option for this in IPython: http://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html?highlight=autoreload

This can be configured as the default behaviour via the IPython config which will effect IPython, Jupyter Notebook, nteract and hydrogen.
