### ISSUE TITLE
Hydrogen 2.2.2 update appears(?) to break py2neo Library.

### ISSUE THREAD

**Issue by OscarSouth** [nteract/hydrogen#1190]
Bug Report!
Also posted here:
https://github.com/technige/py2neo/issues/647

**Description:**

This morning I was working with the py2neo Library, all working fine until I clicked update and after Atom rebooted, py2neo would no longer import correctly.

Uninstalled and reinstalled both py2neo and Hydrogen, no change.  

Additionally, py2neo still imports without issue in the terminal or in PyCharm.

**Steps to Reproduce:**

Attempt to import 'Graph' from py2neo.  This will be (attempted to be) imported with pretty much any part of the Library.

I was running:
from py2neo import Graph, Node, Relationship

**Versions:**

Ubuntu 17.10
Atom 1.22.1
Hydrogen 2.2.2
py2neo 3.1.2 
Anaconda Python installation

**Logs:**

ImportError                               Traceback (most recent call last)
<ipython-input-3-e83650757529> in <module>()
----> 1 from py2neo import Graph, Node, Relationship

ImportError: cannot import name 'Graph'

**Comment by OscarSouth** [comment]
Apologies, I already found the cause:
I had named the .py 'testing' file in my Atom projects folder 'py2neo.py' and this was the cause of the problem.  After renaming this file, the library imports without issue.

**Comment by lgeiger** [comment]
👍 Glad you got it working.
