### ISSUE TITLE
Hydrogen error in Atom

### ISSUE THREAD

**Issue by cindycc123** [nteract/hydrogen#1191]
I installed Hydrogen using Atom. Trying to use it in Atom - but when I ask code to run in Atom, get a Hydrogen error: 

"your file must be saved in order to start a new kernel"

I have saved the file. 

Here is the jupyter kernel info from my machine: 

```
{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/Users/cindy/anaconda/lib/python2.7/site-packages/ipykernel/resources", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/Users/cindy/anaconda/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}

```

**Comment by BenRussert** [comment]
Can you try closing and reopening the file?

 If that works it will get you going and narrow down the issue.

**Comment by guillefix** [comment]
I had the same issue and opening and closing the file fixed it.
