### ISSUE TITLE
figsize IRkernel

### ISSUE THREAD

**Issue by HenrikEckermann** [nteract/hydrogen#1192]
Hi,

the package keeps getting greater. Thanks guys!

How can I change the figsize in R for the inline plots? In Python the figures have a good size for watching them in the editor but when I use the IRkernel, the figures are too large and I need to scroll too much.

**Comment by wadethestealth** [comment]
This is not related to hydrogen, since hydrogen does not control figure size. Heres a solution I found on google, if this does not work for you I recommend exploring R or IRkernel more.
