### ISSUE TITLE
cannot install hydrogen on linux mint

### ISSUE THREAD

**Issue by hjlgood** [nteract/hydrogen#1196]
**Description:**

Cannot install hydrogen on linux mint 18.3
I wonder if anyone else experienced a same problem on linux.
It would be grateful if anyone could help me.  :(

**Steps to Reproduce:**

sudo apm install hydrogen 
produces the following error at the bottom 

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

Linux Mint 18.3
~ $ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

--------------------------------------------------------------------------------------------------------------------------------

> canvas@1.6.9 install /tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild

> zeromq@4.6.0 install /tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

/tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor
└── (empty)

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/canvas/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.13.0-26-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-118023-7250-jqk22i.3279vvlsor No description
npm WARN apm-install-dir-118023-7250-jqk22i.3279vvlsor No repository field.
npm WARN apm-install-dir-118023-7250-jqk22i.3279vvlsor No README data
npm WARN apm-install-dir-118023-7250-jqk22i.3279vvlsor No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jeong/.atom/.apm/.apmrc" "--userconfig" "/home/jeong/.atom/.apmrc" "install" "/tmp/d-118023-7250-1cdnk7r.d7xi2xd2t9/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118023-7250-jqk22i.3279vvlsor/npm-debug.log
npm ERR! code 1

**Comment by hjlgood** [comment]
Fixed by removing .atom folder and reinstalling atom. type the following
1) mv ~/.atom ~/.atom-backup
2) sudo apt-get purge atom
3) sudo apt-get install atom
4) install hydrogen from 'settings' menu

**Comment by hjlgood** [comment]
also try the following if the above solution does not fix the problem
apm rebuild
apm install hydrogen

**Comment by yjhung** [comment]
I am getting this same error on linux mint but the steps above did not work for me. Were there any permissions that you have to change?

**Logs**
> canvas@1.6.9 install /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild


> canvas-prebuilt@1.6.0 install /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/canvas-prebuilt
> node-pre-gyp install

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz

> zeromq@4.6.0 install /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


/bin/sh: 1: prebuild-install: Permission denied

Building libzmq for linux
/tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor
└── (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-112-generic
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/local/bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at buildZMQ (/tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:17:15)
    at IncomingMessage.<anonymous> (/tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:106:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11811-23884-q37t7h.7hqa9ssjor No description
npm WARN apm-install-dir-11811-23884-q37t7h.7hqa9ssjor No repository field.
npm WARN apm-install-dir-11811-23884-q37t7h.7hqa9ssjor No README data
npm WARN apm-install-dir-11811-23884-q37t7h.7hqa9ssjor No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 (node_modules/Hydrogen/node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/joseph/.atom/.apm/.apmrc" "--userconfig" "/home/joseph/.atom/.apmrc" "install" "/tmp/d-11811-23884-z9vpsn.9p8rara4i/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11811-23884-q37t7h.7hqa9ssjor/npm-debug.log
npm ERR! code 1
