### ISSUE TITLE
Runtime problem in python

### ISSUE THREAD

**Issue by Nanoboss** [nteract/hydrogen#1197]
**Description:**

hi,

I have a few issues with hydrogen. The first one is that the autoscroll after running does not work (it's activated in the settings, tried to select/unselect) and that when I make a modification in on of my files, it's not taken into consideration at runtime, I have to restart atom or reload my files to make it work. 
Any ideas on how to troubleshoot that problem? I don't know if it's a bug or not since otherwise hydrogen eprforms well.
Best regards

**Steps to Reproduce:**

1. [First Step]
run a program that import a module in python that creates an error
2. [Second Step]
fix the error in the module and run again, you will get the same error.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Windows 10 pro x64
atom 1.23.3 x64
hydrogen 2.2.2

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by wadethestealth** [comment]
@Nanoboss you probably just need to call restart kernel and run you code again, since the module is already imported, the kernel will not import it again.
