### ISSUE TITLE
Re: How to stop a running python script by hydrogen?

### ISSUE THREAD

**Issue by junarry** [nteract/hydrogen#1199]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
You can try interrupting the kernel with `hydrogen:interrupt-kernel`, if that doesn't work there is a discussion in #1117 about this.

**Comment by keaiwangwang** [comment]
> You can try interrupting the kernel with `hydrogen:interrupt-kernel`, if that doesn't work there is a discussion in #1117 about this.

where should I put this command in?

**Comment by wadethestealth** [comment]
using `ctrl + p` inside atom brings up the command palette where you can enter or search commands @keaiwangwang

**Comment by keaiwangwang** [comment]
Thanks, it still can't let my kernel stop but quit the running page which makes me able to close it manually on the bottom-left corner.

**Comment by wadethestealth** [comment]
Not sure what you mean by kernel stop. But you could use the shutdown command inside the command palette after the interupt
