### ISSUE TITLE
Question: Are there instructions on how to install hydrogen with local scala kernel?

### ISSUE THREAD

**Issue by tomer-ben-david** [nteract/hydrogen#1205]
For some reason I went through the documentation and couldnt find such step by step howto install local scala kernel and how to then run it.  If someone could explain to me I would then be more than happy to contribute back to this documentation such a step by step instructions.  Thank you.

**Comment by rgbkrk** [comment]
I'd use https://github.com/jupyter-scala/jupyter-scala

**Comment by tomer-ben-david** [comment]
ok cool.  so now got stuck installing jupyter-scala ;) will close this one and continue working on the jupyter-scala installation..
