### ISSUE TITLE
R kernel error messages displayed in French in Hydrogen only

### ISSUE THREAD

**Issue by mollenburger** [nteract/hydrogen#1206]
**Description:**

Not a bug exactly, or an odd one at least: When executing R code in Hydrogen, error messages are displayed in French...sort of. Nothing against the French language, but I do prefer my error messages in English.

**Steps to Reproduce:**
1. Do something dumb. In this example I use dcast(thing) where thing doesn't exist.
2. Error message produced: "Error in inherits(x, "formula"): _l'argument "formula" est manquant, avec aucune valeur par d'efaut_"

**Versions:**
Atom 1.23.3
Hydrogen 2.2.2 
(although this has been happening since I started using Hydrogen for R code maybe 6 months ago)
Mac OSX Sierra

The default language everywhere on my machine is English. I get English error messages in R when I run it from the Terminal, in a Jupyter qtconsole (using the same kernel Hydrogen would presumably be using) or the standard R for mac app. So I'm stumped.

**Comment by BenRussert** [comment]
Have you tried it in a jupyter notebook? I'm not sure there is anything hydrogen does that would cause this. 

There are a few suggestions for changing your language settings via dotfiles etc in [this stackoverflow post](https://stackoverflow.com/questions/13575180/how-to-change-language-settings-in-r). If need be you could add startup code for r in the hydrogen settings.
