### ISSUE TITLE
Unable to install hydrogen on Linux Mint

### ISSUE THREAD

**Issue by yjhung** [nteract/hydrogen#1207]
**Description:**
I tried installing hydrogen on the command line but have been unsuccessful. Have been on it for hours searching forums/bug reports for a solution without success. 

**Steps to Reproduce:**
1. apm install hydrogen
2. Install with Atom's package manager

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
OS: Linux Mint 18

$ atom --version
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.7.4

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

$ apm install hydrogen
Installing hydrogen to /home/jh/.atom/packages ✗

> canvas@1.6.9 install /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild

> canvas-prebuilt@1.6.0 install /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/canvas-prebuilt
> node-pre-gyp install

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz

> zeromq@4.6.0 install /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

/bin/sh: 1: prebuild-install: Permission denied

Building libzmq for linux
/tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi
└── (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-112-generic
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/local/bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at buildZMQ (/tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:17:15)
    at IncomingMessage.<anonymous> (/tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:106:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11811-27598-16zbn0k.xawuvunmi No description
npm WARN apm-install-dir-11811-27598-16zbn0k.xawuvunmi No repository field.
npm WARN apm-install-dir-11811-27598-16zbn0k.xawuvunmi No README data
npm WARN apm-install-dir-11811-27598-16zbn0k.xawuvunmi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 (node_modules/Hydrogen/node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/joseph/.atom/.apm/.apmrc" "--userconfig" "/home/joseph/.atom/.apmrc" "install" "/tmp/d-11811-27598-1piy3w.zwaikvs4i/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11811-27598-16zbn0k.xawuvunmi/npm-debug.log
npm ERR! code 1

**Comment by nikitakit** [comment]
I'm not quite sure how to read the entirety of the error message, but one thing that stands out is the attempt to use python 3 when python 2 is required.

Have you tried following the [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#installation-fails-on-linux-32-bit) and explicitly specifying a path to python2? e.g. `PYTHON=python2.7 apm install hydrogen`

**Comment by yjhung** [comment]
Thanks for the quick response! Sorry, my mistake when sending the logs. I have been developing on version python 3.6 and forgot i was in that specific environment when reproducing the error.

I have followed the guide previously using python 2.7, but the end result is the same. I am not sure if this is related since there is a 404 error code when it was fetching a package?

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz

Thanks again!
**Logs**

$ python --version
Python 2.7.12

$ apm install hydrogen
Installing hydrogen to /home/jh/.atom/packages ✗

> canvas@1.6.9 install /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild


> canvas-prebuilt@1.6.0 install /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/canvas-prebuilt
> node-pre-gyp install

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz

> zeromq@4.6.0 install /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


/bin/sh: 1: prebuild-install: Permission denied

Building libzmq for linux
/tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi
└── (empty)


/bin/sh: 1: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-112-generic
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/local/bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at buildZMQ (/tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:17:15)
    at IncomingMessage.<anonymous> (/tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:106:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi No description
npm WARN apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi No repository field.
npm WARN apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi No README data
npm WARN apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 (node_modules/Hydrogen/node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/joseph/.atom/.apm/.apmrc" "--userconfig" "/home/joseph/.atom/.apmrc" "install" "/tmp/d-11811-21483-1g06b2w.tnk22tvs4i/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11811-21483-1duxhrm.zhnse5ewmi/npm-debug.log
npm ERR! code 1

**Comment by nikitakit** [comment]
I think the 404 is normal, but the "permission denied" errors are not.

**Comment by yjhung** [comment]
I tried with sudo but met with the same errors too so am out of ideas.
Appreciate if you have any suggestions.

**Comment by BenRussert** [comment]
I just had this issue pop up after upgrading ubuntu from version 16.04 to 17.10, but im not sure if that is a coincidence.

What is happening is apm is using your default `python` version when it needs to use 2.7 to work with gyp. There should be some way to set your apm config python variable to point to python2.7 but I am not sure the correct way to do this. I tried `apm config set python $(which python2.7)` but it wouldnt persist. This may need to be done in a `.apmrc` dotfile somewhere.

The way I resolved it for now was by editing `/usr/share/atom/resources/app/apm/bin/python-interceptor.sh` lines 37 and 40 to say `python2.7` instead of just `python`. Then just install hydrogen and make sure you rebuild modules next time atom loads up (it will prompt you to).

**Comment by yjhung** [comment]
Thanks for your suggestion Ben! Unfortunately i am still getting permission errors.

I updated the python-interceptor.sh that you have suggested. 
```
 37     exec python2.7 "${ARGS[@]}"
 38     ;;
 39   *)
 40     exec python2.7 "$@"
```

I am going without hydrogen at the moment, but very keen to give it a go again.

**Logs**
$ PYTHON=python27 apm install hydrogen
Installing hydrogen to /home/joseph/.atom/packages ✗

> canvas@1.6.9 install /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild


> canvas-prebuilt@1.6.0 install /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/canvas-prebuilt
> node-pre-gyp install

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz

> zeromq@4.6.0 install /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


/bin/sh: 1: prebuild-install: Permission denied

Building libzmq for linux
/tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor
└── (empty)


/bin/sh: 1: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-112-generic
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/local/bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at buildZMQ (/tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:17:15)
    at IncomingMessage.<anonymous> (/tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js:106:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11816-29674-1avczbh.8rddsd1jor No description
npm WARN apm-install-dir-11816-29674-1avczbh.8rddsd1jor No repository field.
npm WARN apm-install-dir-11816-29674-1avczbh.8rddsd1jor No README data
npm WARN apm-install-dir-11816-29674-1avczbh.8rddsd1jor No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 (node_modules/Hydrogen/node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/joseph/.atom/.apm/.apmrc" "--userconfig" "/home/joseph/.atom/.apmrc" "install" "/tmp/d-11816-29674-5ft68p.wjgpynwmi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11816-29674-1avczbh.8rddsd1jor/npm-debug.log
npm ERR! code 1

**Comment by BenRussert** [comment]
@yjhung what does `apm -v` output for you? For example, here is mine after applying the quick fix described above:

```apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.14.1
```

**Comment by yjhung** [comment]
Hi Ben,

This is my apm -v output.

$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.7.4

**Comment by yjhung** [comment]
I finally got Hydrogen installed! 
It was because my tmp folder was set to noexec. After remounting it to executable, it installed just fine.

**Comment by BenRussert** [comment]
Glad to hear it works!
