### ISSUE TITLE
Using getpass to input password brings up input box that uses plaintext.

### ISSUE THREAD

**Issue by phillynch7** [nteract/hydrogen#1208]
**Description:**

Using the Python library getpass to input passwords uses an input box that displays in plain text instead of *'s.

**Versions:**

MacOS 10.12.6
Atom 1.23.1
Hydrogen 2.2.2

**Comment by amansheim-bm-net** [comment]
Also Windows 10, Atom 1.24.0 x64, Hydrogen 2.2.3
