### ISSUE TITLE
How to plot with JavaScript kernel?

### ISSUE THREAD

**Issue by sheegl** [nteract/hydrogen#1210]
Are there examples of how to plot in JavaScript? All the info I found is for Python.

I ran the [jp-babel](https://github.com/n-riesco/jp-babel) (and ijavascript) kernel and tried to use [plotly](https://github.com/plotly/plotly-notebook-js) to plot but all I got was an empty box. I get a string back that contains all the html but I don't know how to display it in hydrogen.

This is the code I ran
```js
var Plot = require('plotly-notebook-js');
var myPlot = Plot.createPlot([{ x: [1,2,3], y: [3,4,5] }], { title: 'Plotly in Jupyter!' });
$$.html(myPlot.render());
```

**Comment by n-riesco** [comment]
Hydrogen supports plotly graphs and I've written a small package to take advantage of this support: [ijavascript-plotly](https://github.com/n-riesco/ijavascript-plotly)

```js
var Plotly = require("ijavascript-plotly");

Plotly([{y: [10, 30, 20]}], {title: "Plotly from IJavascript"});
```


![usage](https://user-images.githubusercontent.com/6199391/36138427-491a34e6-1091-11e8-93dc-ea008f9f06fc.png)

---

@rgbkrk Thanks for bringing my attention to this issue. I'm sorry I missed it for so long. I don't get any emails when an issue is assigned to me (mentions catch my attention better)
