### ISSUE TITLE
Rsizing of output area (with too much data?) generates error.

### ISSUE THREAD

**Issue by florianfelix** [nteract/hydrogen#1215]
**Description:**
Resizing of output area to maximum generates error
**Steps to Reproduce:**

**Steps:**
Download Data:
https://www.statistik-nord.de/fileadmin/Dokumente/Statistische_Berichte/bevoelkerung/A_I_S_1_j_H/A_I_S1_j16.xlsx

run script:

```
# %%
import pandas as pd
path = 'A_I_S1_j16.xlsx'
data = pd.read_excel(path, sheet_name='T3_1')
data.head(8)

```
then resize output area to maximum width

**Versions:**

Atom    : 1.23.3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

[error-log.txt](https://github.com/nteract/hydrogen/files/1699809/error-log.txt)

**Comment by wadethestealth** [comment]
I believe this to be fix. Please test this on a current version of hydrogen. If you still get an error, feel free to open a new issue.
