### ISSUE TITLE
Issues with installing Hydrogen on Linux running on Chromebook

### ISSUE THREAD

**Issue by archanatikayatray** [nteract/hydrogen#1216]
I have linux running on my Chromebook and I cant get to install Hydrogen.

**Comment by n-riesco** [comment]
What error message do you get?

If your chromebook  is 32bit, then you'll need to install some additional requirements. See instructions [here](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#installation-fails-on-linux-32-bit).

**Comment by archanatikayatray** [comment]
This is the error message I am getting: 
> zeromq@4.6.0 install /tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/jmp/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install info begin Prebuild-install version 2.5.0
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.6.0-node-v14-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/archanatikayatray/.atom/.apm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v14-linux-x64.tar.gz

**Comment by n-riesco** [comment]
@archanatikayatray The log message looks truncated (I don't see any error message there)

**Comment by archanatikayatray** [comment]
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.8.11
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/@nteract/vega-embed2/node_modules/vega/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing canvas@1.6.9
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.8.11
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.22.0
node-pre-gyp ERR! stack     at get_runtime_abi (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/util/versioning.js:172:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/util/versioning.js:293:19)
node-pre-gyp ERR! stack     at install (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:165:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 3.8.11
node-pre-gyp ERR! command "node" "/tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-11817-16180-1ei67du/node_modules/Hydrogen/node_modules/@nteract/transform-vega/node_modules/vega-embed/node_modules/vega/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
npm WARN optional dep failed, continuing canvas@1.6.9
npm WARN optional dep failed, continuing canvas-prebuilt@1.6.0
npm ERR! Linux 3.8.11
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/archanatikayatray/.atom/.apm/.apmrc" "--userconfig" "/home/archanatikayatray/.atom/.apmrc" "install" "/tmp/d-11817-16180-9fscx9/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package commonmark does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer commonmark-react-renderer@4.3.4 wants commonmark@^0.27.0 || ^0.26.0 || ^0.24.0

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11817-16180-1ei67du/npm-debug.log

**Comment by n-riesco** [comment]
The error message is telling us that the installation failed because the header files of the library `cairo` haven't been installed in your machine.

I'm not familiar with the installation of packages in a Chromebook.
