### ISSUE TITLE
Hydrogen making atom editor freeze

### ISSUE THREAD

**Issue by manohar9600** [nteract/hydrogen#1219]
Atom stops responding while running keras classifier that giving large output.

Atom is freezing after 22- 25 epochs.

Which OS and which version of Hydrogen and Atom are you running?
Win 10
![screenshot 1](https://user-images.githubusercontent.com/14134763/36065880-c899ea30-0ec6-11e8-845a-d808014baf9b.png)

**Comment by wadethestealth** [comment]
If this still occurs on the current version of hydrogen please submit an issue with better steps to reproduce your error. 😄
