### ISSUE TITLE
ctrl - enter is going to the next line. 

### ISSUE THREAD

**Issue by vishal786btc** [nteract/hydrogen#1220]
Hi All, 
While pressing the ctrl - enter to compile the python code, it cursor is going to the next line. 

Any quick help to resolve. I'm in the middle of some important code debugging.

Appreciate your help.

Thanks, 
Vishal

**Comment by BenRussert** [comment]
Can you try opening up your keybinding resolver w/ atom `ctrl-.`? See what command is actually running when you press `ctrl-enter`. 

`ctrl-enter` (or `cmd-enter` on mac) is mapped to `hydrogen:run`, which should not be moving the cursor at all with our default keybindings. If you are pressing `shift-enter`, this is mapped to `hydrogen:run-and-move-down` and the cursor moving to the next line is expected.

**Comment by vishal786btc** [comment]
Currently it is set to newline.
![image](https://user-images.githubusercontent.com/20676154/36190179-549754e4-111c-11e8-8627-1df88e63e38d.png)
Can you please tell how to fix this? It'll be really helpful.

**Comment by BenRussert** [comment]
I dont see hydrogen anywhere in your screenshot. Are you sure you have it installed?

Try running `hydrogen:run` from the atom command palette, does that work as expected?

**Comment by vishal-nas** [comment]
Yes Ben. I have it installed.
I just sent the screenshot of Keybindings.

**Comment by vishal-nas** [comment]
pfa-
![image](https://user-images.githubusercontent.com/36178820/36347270-e0684556-1418-11e8-87ef-e4c93ace2ea1.png)

**Comment by vishal786btc** [comment]
yes Ben. I have installed it.
I just sent the screenshot of keybindings.
pfa-
![image](https://user-images.githubusercontent.com/20676154/36347273-16a5ee3e-1419-11e8-82d1-b23c18b66501.png)

**Comment by BenRussert** [comment]
Can you try the key bind resolver with `ctrl-.` Either `hydrogen:run` is not running at all, or another command is running on top of it causing the cursor position to change.

**Comment by krystalzeng** [comment]
I am having similar issues. hydrogen:move-and-run-down runs the entire document instead of moving to the next line. It seems to only run till the end of document when the cursor is on a def/class line. I used ctrl-. to see what key binding is getting called, here's a screenshot.

<img width="891" alt="screen shot 2018-02-19 at 08 01 35" src="https://user-images.githubusercontent.com/21279466/36367615-620989b6-154b-11e8-8ede-4819a9cc378e.png">

**Comment by lgeiger** [comment]
@vishal786btc It looks like Hydrogen isn't correctly installed. Could you try and reinstall it?

**Comment by jollymike** [comment]
I have had the same issue occur a few times recently. It seems to be related to the hydrogen installation getting corrupted somehow. A reinstall fixes it.

**Comment by kylebarron** [comment]
Closing as stale
