### ISSUE TITLE
Failed installing canvas

### ISSUE THREAD

**Issue by okonomiyaki3000** [nteract/hydrogen#1221]
**Description:**

Installation fails because `canvas-prebuilt@1.6.0` can't be found. This url https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-win32-x64.tar.gz is 404. 

**Steps to Reproduce:**

1. At the command line: `apm install hydrogen`
2. Fail

**Versions:**

Windows7

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-electron-v1.6-win32-x64.tar.gz

**Comment by wadethestealth** [comment]
Please try installing our newest version our hydrogen. If you still have issues feel free to open a new issue.

**Comment by okonomiyaki3000** [comment]
Thanks. That was a year and a half ago. I use VSCode now.

**Comment by wadethestealth** [comment]
@okonomiyaki sorry for your lost 😆
