### ISSUE TITLE
Feature Request: Ability to Hyperclick/Go To Definition via keyboard from a Hydrogen Notebook

### ISSUE THREAD

**Issue by RAbraham** [nteract/hydrogen#1223]
I enjoy using Hydrogen for interactive development. It would be really nice to have the HyperClick/'Go To Definition via a keyboard shortcut'  feature where I can navigate via the keyboard to the method definition from the Hydrogen notebook.

Update: I just found out that it works if the function I want to go into is in a file within the same folder as my hydrogen notebook. It does not work if the file is in another directory. However, if I execute that function in the notebook, it will run.

**Comment by kylebarron** [comment]
Go to definition is language specific and won't be implemented in Hydrogen. Plus, this exists in the Atom IDE project.
