### ISSUE TITLE
Cannot import project modules when working with virtual env

### ISSUE THREAD

**Issue by Locustv2** [nteract/hydrogen#1225]
Using Atom with python3.6 and platformio ide terminal.

I set an autorun command in my platformio terminal: `python3.6 -m venv .env && source .env/bin/activate;.env/bin/pip install ipykernel;.env/bin/python -m ipykernel install --prefix=.env --name .env --display-name "Python (.env)"`

Which creates a venv in my project and activate it when i launch the terminal. It also install the ipykernel etc.

When i import modules that have been installed using `pip` it works, but if i have a module inside my project directory and i try to import from there, i get a module not found error. But running  the script in terminal works.

**Comment by hugeme** [comment]
@Locustv2 did you resolve the problem? I have the same issue

**Comment by kylebarron** [comment]
I can't tell if the original question is regarding Hydrogen or Platformio terminal. Those are two different things.

In order to work with Hydrogen in a virtual environment, you need to start Atom from the command line with the environment activated. So something like

```
source .env/bin/activate
atom .
```

or with conda
```
source activate env_name
atom .
```

**Comment by kylebarron** [comment]
Closing as stale
