### ISSUE TITLE
Local Import doesn't work

### ISSUE THREAD

**Issue by nagyj2** [nteract/hydrogen#1226]
**Description:**
I have a local Python 3 file that I am trying to import into another and I get the error:

```python-traceback
ImportErrorTraceback (most recent call last)
<ipython-input-2-e3b2c7b11e71> in <module>()
----> 1 from SeqServices import *
ImportError: No module named SeqServices
```

The "SeqServices".py file is in the same directory as the file I am working on.
I don't get any errors from default imports (random and math) or pip3 installed packages (numpy and scipy).
I am running the IPython from the terminal command "pip3 install jupyter"

**Steps to Reproduce:**
1. Create 2 python files in the same directory
2. In one of the files, try to import the other

**Versions:**
I am running High Sierra with Atom 1.24 and Hydrogen 2.2.2.

**Comment by lookbehindyoo** [comment]
I have the same issue. Its something to do with the path of the kernel vs your local file I think. There is a workaround which can help you until someone responds - transfer your file to the site-packages directory of your python installation.

**Comment by nagyj2** [comment]
I tried the above, and now it works, thanks! :)

**Comment by lookbehindyoo** [comment]
Happy to hear it. This had me stumped for a couple hours! If this has resolved the problem, I think you are able to close the issue. I'm not a contributor to the project so I dont have that power. If a dev reads this however, perhaps it is worth adding this topic to the FAQs or something, as this is not immediately obvious.

**Comment by BenRussert** [comment]
@lookbehindyoo Thanks for helping out with this. It does look like our docs are not clear on the kernel start up configuration options (I don't think it is mentioned at all). If you are interested please submit a PR with the info you discovered!

**Comment by andybrnr** [comment]
Modification of this question... how should this work with remote kernels? I tried changing the kernel start directory, but when it's remote, I'm not sure how this alters things... haven't been able to make my local imports behave when running against a remote kernel yet.

**Comment by nikitakit** [comment]
For python, I use the `%cd` magic. This does require adding an extra line to the file to ensure the correct start location. I do think this issue deserves a better solution, though.

If applicable, you can also try changing the folder you're in when you start the notebook server. Maybe that will change the default directory assumed for remote kernels.

**Comment by andybrnr** [comment]
Hi @nikitakit,

Thanks for the quick response. Just so I'm clear about my use case and so I understand the proposed fix, let me walk through my scenario.

1) Clone my python project from bitbucket to a local repo on my MacBook
2) Open repo up in Atom, use Hydrogen to launch a remote kernel on an AWS instance with the RAM needed to chew on a large dataset hosted in S3
3) Attempt to run imports in first cell that load functions from a local module within the project <this fails>

If I run a %cd magic, it just tells me where the kernel on the AWS instance has been launched. I guess since the remote kernel can't put my local filesystem on the path, it's natural that it can't find the local imports, but was hoping there was a workaround that didn't involve cloning the repo to the AWS instance, launching the kernel in the remote repo, which would then work... but would require a commit/push/pull with every code change to the local modules. Is there a way to deal with this?

Thanks!

**Comment by andybrnr** [comment]
After digging into the old issues more thoroughly, discovered this was addressed in #629 to some extent (i.e. need some sort of file synchronization in place). I haven't poked around the code base for hydrogen much yet, and not sure my dev skills would be up to it (though I'm willing to look!), but it seems like it should be possible to implement a solution to this that doesn't involve a file sync. I found an old SO post where a Spyder dev was talking about this issue, and they apparently had a mechanism to search the local path and push local modules up to the remote kernel, run them, and drop back into the importing file. Any sense of how doable it would be to implement a similar mechanism?

**Comment by matanster** [comment]
One missing piece following [the answer](https://github.com/nteract/hydrogen/issues/1226#issuecomment-366963777) to the original question before the thread was modified/hijacked :)
You need to restart atom after making this change (at least, I couldn't make it work without that extra step).

**Comment by matanster** [comment]
May I suggest that the default setting in this regard is just the most unreasonable one? any major cons to making it the current directory by default?

**Comment by KLzC** [comment]
I'm upload Mac solution on here, 
<img width="276" alt="Screenshot 2019-03-29 15 42 05" src="https://user-images.githubusercontent.com/5106837/55217000-4b36b200-5239-11e9-86bc-b83ce00312d5.png">
<img width="955" alt="Screenshot 2019-03-29 15 46 15" src="https://user-images.githubusercontent.com/5106837/55217172-cf893500-5239-11e9-8a18-f9056890c122.png">
<img width="797" alt="Screenshot 2019-03-29 15 47 35" src="https://user-images.githubusercontent.com/5106837/55217252-ffd0d380-5239-11e9-9c04-07ebbf44520c.png">

**Restart your Atom**

test : `command + enter`
<img width="676" alt="Screenshot 2019-03-29 15 48 45" src="https://user-images.githubusercontent.com/5106837/55217791-5559b000-523b-11e9-8467-2794e56f6cd3.png">

**Comment by Kevin-Chen0** [comment]
Thank you! I've been looking for this. Imo, I think it is better for the Current directory option to be default.

**Comment by hagen-wende** [comment]
Thank you!!! I was going nuts over this problem!
