### ISSUE TITLE
IPython.display.clear_output doesn't work

### ISSUE THREAD

**Issue by a-bochkarev** [nteract/hydrogen#1227]
**Description:**

clear_output() function has no effect on the output in the Hydrogen. This is very useful feature in Jupyter Notebook to draw plots in real time (i.e. in the loop)

**Steps to Reproduce:**

**Versions:**

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by kylebarron** [comment]
The function definition is here: https://github.com/ipython/ipython/blob/512d47340c09d184e20811ca46aaa2f862bcbafe/IPython/core/display.py#L1394-L1408

```py
def clear_output(wait=False):
    """Clear the output of the current cell receiving output.
    Parameters
    ----------
    wait : bool [default: false]
        Wait to clear the output until new output is available to replace it."""
    from IPython.core.interactiveshell import InteractiveShell
    if InteractiveShell.initialized():
        InteractiveShell.instance().display_pub.clear_output(wait)
    else:
        print('\033[2K\r', end='')
        sys.stdout.flush()
        print('\033[2K\r', end='')
        sys.stderr.flush()
```

I'm not sure how that would be understood as "clear output" by Hydrogen

**Comment by leonelgalan** [comment]
I came here looking for a way to programmatically clear the "Hydrogen Output Area" or a setting that will only show the results from the latest run. When not using the output area, I'm not sure, maybe the "bubbles" should clear?

**Comment by wadethestealth** [comment]
We already have an atom command in hydrogen for clearing results. If you would like to request a new feature, please open a new issue. 😄
