### ISSUE TITLE
Hydrogen: Run running everything after function definition

### ISSUE THREAD

**Issue by onepan** [nteract/hydrogen#1229]
**Description:**

Calling Hydrogen: Run or Hydrogen: Run And Move Down when the cursor is on a def line runs the entire document. E.g., below code would immediately output "bye again" "hi again" when you start at either def a(): or def b():.

This happens whether it's called via hotkey or from command palette

example code:
```Python
def a():
    print("hi")

def b():
    print("bye")

print("bye again")
print("hi again")
```
**Steps to Reproduce:**

1. put cursor on either def line in example code
2. call Hydrogen: Run or Hydrogen: Run And Move Down

**Versions:**

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10
Hydrogen: 2.2.2

**Logs:**
[-1518819562665.log](https://github.com/nteract/hydrogen/files/1733012/-1518819562665.log)

**Comment by krystalzeng** [comment]
I am having the same issues.
