### ISSUE TITLE
Run-and-move-down no longer works

### ISSUE THREAD

**Issue by krystalzeng** [nteract/hydrogen#1230]
Issue: hydrogen:Run-and-move-down automatically goes to end of file

Was using atom earlier running my python code, not sure what I pressed but now after going through imports in the beginning, it runs through the entire file instead of going line by line. Is this an atom editor issue or Hydrogen? 
I have tried uninstall atom and uninstall Hydrogen, both did not solve the issue.

Mac 
Atom v 1.24.0
Hydrogen 2.2.2

**Comment by krystalzeng** [comment]
It appears that it will only skip to the end of file if the file starts with classes or functions. However, I was able to run class by class before.

**Comment by sunt05** [comment]
same here. really annoying.

**Comment by lgeiger** [comment]
This looks like Atom changed something with their grammar handling. Could you provide a code example where run-and-move-down isn't working?

**Comment by sunt05** [comment]
Hi @lgeiger, this issue can be merged with this one: https://github.com/nteract/hydrogen/issues/1229, where a code example is presented.

**Comment by lgeiger** [comment]
Thanks for the link. Closing in favor of #1229
