### ISSUE TITLE
Problems when runnning functions

### ISSUE THREAD

**Issue by xudongmit** [nteract/hydrogen#1232]
Hydrogen will run all the way to the last line when running a python function

**Steps to Reproduce:**

In Atom (with Hydrogen), when I want to run a function and press shift+enter, it will run all the way to the last line. For example:
![image](https://user-images.githubusercontent.com/36244603/36430956-59eeda36-1624-11e8-8e3f-77ab52f9c3c4.png)

This situation just started 2 days ago. I'm not sure if I messed up some settings or it's a bug.

**Versions:**
win10, python3

**Comment by lgeiger** [comment]
Are you using the latest version of Hydrogen?

**Comment by xudongmit** [comment]
The problem is just solved by switching off the "soft tab" setting of Atom. It seems Hydrogen cannot detect Atom's soft tabs. 

I'm using the 2.2.2. Thank you!

**Comment by lgeiger** [comment]
@xudongmit Could you upgrade to 2.2.3 and try again. The problem should've been solved in this version.

**Comment by wadethestealth** [comment]
If this still occurs on the current version of hydrogen please open a new issue. 😃
