### ISSUE TITLE
Utilize Hydrogen UI for script - Question

### ISSUE THREAD

**Issue by chrispahm** [nteract/hydrogen#1235]
For a modelling language (GAMS) I would like to use Hydrogen in order to display parameters and set values inline. As there is no Jupyter Kernel for GAMS, I was thinking about writing a wrapper around the Python Kernel, however I think that it is overkill as GAMS is not a typical programming language where you can actually run code line by line. I'd therefore rather use the Hydrogen UI to call a small script, and then pass the result back to the UI. Is that possible in some way? Thanks a lot!

**Comment by wadethestealth** [comment]
@chrispahm what do you mean by use the Hydrogen UI and "small script" You could always edit our source code to do anything you want. Just for your reference Hydrogen runs on Javascript and relies on kernels for execute any code from the text editor
