### ISSUE TITLE
How to set argv parameter in Hydrogen?

### ISSUE THREAD

**Issue by zhangliqun** [nteract/hydrogen#1236]
**Description:**

How to set the argv parameter in Hydrogen?

**Steps to Reproduce:**

1. Try "Hydrogen:Run" to run the Python source below:

from sys import argv

script, inputfilename = argv

print("The script is called:",script)
print("The input file name is:", inputfilename)

2. I get the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-72571cfad3b8> in <module>()
      1 from sys import argv
      2 
----> 3 script, inputfilename = argv
      4 
      5 print("The script is called:",script)

ValueError: too many values to unpack (expected 2)

**Versions:**

OS: Windows 10
Python: 3.6
Atom: 1.24.0
Hydrogen: 2.2.3

**Logs:**

NA

**Comment by kylebarron** [comment]
I don't think it's possible to set `argv`, because Hydrogen isn't running through a terminal.
