### ISSUE TITLE
Kernel being updated that's not installed

### ISSUE THREAD

**Issue by scienceyeaux** [nteract/hydrogen#1239]
**Description:**

When I run a cell I get the following Atom notification:
![image](https://user-images.githubusercontent.com/36206562/36647460-fd134282-1a53-11e8-8ade-e1b8e1fcb90a.png)

I don't have Julia kernel installed and I'm not sure why it is saying it's being updated.

Here's my Hydrogen settings:
![image](https://user-images.githubusercontent.com/36206562/36647476-3c68e054-1a54-11e8-8269-9df0f367e4cb.png)

**Steps to Reproduce:**

1. Highlight "cell"
2. Ctrl + Shift + Enter to run cell

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

Windows 10
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by stevengj** [comment]
Note that even if you deleted the Julia software from your machine, you might still have a Jupyter kernelspec file for Julia left over from an older installation.  Run `jupyter kernelspec list` to see what kernel specifications are installed.  You can just delete the kernelspec directory for Julia 0.6 if you don't want it anymore.

**Comment by kylebarron** [comment]
After running `jupyter kernelspec list`, I believe you can run `jupyter kernelspec uninstall julia` or whatever the kernel name is you want to uninstall.
