### ISSUE TITLE
'C:\Python3\python.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process. [Python is in System PATH]

### ISSUE THREAD

**Issue by ghost** [nteract/hydrogen#1241]
**Description:**

When trying to run "cell" using Hydrogen, I get the following error:

![image](https://user-images.githubusercontent.com/36206562/36686634-0efcbeb4-1af5-11e8-94de-4e2332d25e43.png)

It asks if I have Python installed in my PATH, which I do, although the file path is not "C:\Python3\python.exe" like the error message states.

![image](https://user-images.githubusercontent.com/36206562/36686779-7f7a2082-1af5-11e8-9665-a6164378490e.png)

I am able to (and have been able to) run Python from my command line as well as within atom using my Script package.

I have tried to to add C:\Python3\python.exe to my system PATH but I still receive the same error. I've since removed it so I don't have multiple instances of Python 3 in my PATH.

**Steps to Reproduce:**

1. Activate venv
2. Launch atom from command line
3. Highlight code within Atom
4. Ctrl + Enter (shortcut for running code as cell via Hydrogen)
5. Error message pops up.

**Versions:**

Atom: 1.24.0
Hydrogen: 2.2.3
Electron: 1.6.16
Chrome: 56.0.2924.87
Node: 7.4.0

**Logs:**

![image](https://user-images.githubusercontent.com/36206562/36687049-6c0ec11e-1af6-11e8-8d5a-e9b28ca5bf35.png)

**Comment by cocomice** [comment]
I have same problem with python 2. Atom is looking for python executable in an old path (`Program File (x86)\Anaconda\python.exe`), which was no more existed. How can I change it.

**Comment by n-riesco** [comment]
To update the IPython's kernel spec, run: `python -m ipykernel install --user`

**Comment by lgeiger** [comment]
This is already part of the installation instructions, but it won't hurt if we add it to the troubleshooting guide too.

@cocomice Want to send a PR?

**Comment by cocomice** [comment]
@lgeiger sorry I am a newbie. What do you mean by "send a PR"? I would like to contribute if possible.

**Comment by BenRussert** [comment]
Looks like `python -m ipykernel install --user` fixes this.
