### ISSUE TITLE
Linking Hydrogen with Conda3

### ISSUE THREAD

**Issue by ViktorAmbrose** [nteract/hydrogen#1242]
Forgive me. I'm super new to this program, and coding in general, so forgive me if this is super simple to fix...
I have conda installed (jupyter, python-language-server and ipykernel installed) and I have updated ATOM + hydrogen. For some reason, hydrogen isn't working for me... Can you guys help me?

![image](https://user-images.githubusercontent.com/33062204/36851868-00652d02-1d73-11e8-9231-e8ae10f90fc6.png)

**Comment by lgeiger** [comment]
Have you followed the kernel install instructions as shown here: https://nteract.io/kernels/python?

**Comment by scienceyeaux** [comment]
@lgeiger could you please explain what needs to be configured after installing ipykernel?

**Comment by ViktorAmbrose** [comment]
@lgeiger Thank you. I didn't see the `python -m ipykernel install --user` portion of the conda install. Thank you :D

**Comment by lgeiger** [comment]
Glad it's working 👍
