### ISSUE TITLE
Cannot find an installed SPARQL kernel

### ISSUE THREAD

**Issue by laughedelic** [nteract/hydrogen#1243]
**Description:**

I installed https://github.com/paulovn/sparql-kernel kernel for SPARQL, but I can't make it work. I installed a couple of other kernels to verify that Hydrogen works with them. So the problem is with this kernel installation.

**Steps to Reproduce:**

1. Install [sparql-kernel](https://github.com/paulovn/sparql-kernel)
2. Open any SPARQL file
3. Try to call "Run" command

<img width="499" alt="screen shot 2018-03-02 at 00 52 50" src="https://user-images.githubusercontent.com/766656/36877343-0ac3a49e-1dba-11e8-88a1-dd645ac7a010.png">

SPARQL kernel is listed in one notification, but it's not found when it's needed. I also checked it like this:

```shell
$ jupyter kernelspec list
Available kernels:
  scala         /Users/laughedelic/Library/Jupyter/kernels/scala
  python2       /usr/local/share/jupyter/kernels/python2
  sparql        /usr/local/share/jupyter/kernels/sparql
```

Tried to change the Language Mappings setting:

```json
{ "sparql": "source.rq rq sparql SPARQL" }
```

And any of those grammar values separately. Didn't help. 

From `language-sparql`:

<img width="372" alt="screen shot 2018-03-02 at 00 51 43" src="https://user-images.githubusercontent.com/766656/36877435-75af7c9c-1dba-11e8-994c-07bcdcbb855a.png">

**Versions:**

```
Atom    : 1.25.0-beta2
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

Hydrogen: 2.2.3

**Logs:**

Only this warning:

```
'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
```

**Comment by lgeiger** [comment]
This is a problem with the SPARQL kernel. It misses the [`language` field in the `kernel.json`](https://github.com/paulovn/sparql-kernel/blob/e06ae94faca0c9a9fe356cfa72a90a76c1a50931/sparqlkernel/install.py#L33) file which is required in the [jupyter messaging protocol](http://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs). Hydrogen uses it to determine the grammar.

Adding  `"language": "sparql"` to `/usr/local/share/jupyter/kernels/sparql/kernel.json` should fix it.

**Comment by laughedelic** [comment]
Oh, thanks! That helped. I'm going to send a PR to fix that JSON.
