### ISSUE TITLE
Manual kernel selection

### ISSUE THREAD

**Issue by mdjaere** [nteract/hydrogen#1251]
First of all, thank you for maintaining this amazing project.
#### I want to suggest a UX enhancement.

Currently, a kernel is selected automatically based on file type. It feels like magic when it _just works_, but when you want to diverge from standards, for example running a matlab .m file in a octave kernel, it can get very fiddly with config files. This is true also for connecting to a remote kernels.

**An improvement could be to have a manual kernel selection.**  When you run a cell you could get a selection of local or external kernels (new session or running), or to connect to an external kernel by pasting notebook-url. You could also choose to cancel. A default kernel could be highlighted based on filetype.

#### Pros:
- Freedom of choice to jump between kernels as you please
- Easily test code in different kernels (py2/py3 etc)
- No ambiguity what kernel will be running
- No configuration files left on system
- Pasting notebok-urls would simplify connecting to remote kernels
- Run unsaved files. Great for ephemeral testing
- Run files with no file extensions
- Check available kernels (new or running) by opening this menu, and cancel with no execution

#### Cons: 
- Added few key-presses every time you start a kernel.

I believe this zero-configuration approach could help to streamline to Hydrogen workflow and help its adoption.

**Comment by kylebarron** [comment]
This is possible with the `Start Local Kernel` command. That gives you the possibility to choose any kernel that can be used with the filetype of the active editor.
