### ISSUE TITLE
Please allow selection of text from inline output

### ISSUE THREAD

**Issue by a-bochkarev** [nteract/hydrogen#1257]
On Mac OS and on Windows it is not possible to select part of the output to copy it unless it is in separate output tab. Please allow selection inline.

**Comment by BenRussert** [comment]
I've tried fixing this a number of times and have not been successful.

In the output area dock and inspect views, we fixed this by adding a `.native-key-bindings` class. The same solution doesn't work inline for whatever reason.

**Comment by wadethestealth** [comment]
@BenRussert Check out my PR #1652
