### ISSUE TITLE
Ubuntu install fails w/a heap of errors. Should just flag dependancies

### ISSUE THREAD

**Issue by amandabee** [nteract/hydrogen#126]
Tried to install Hydrogen via the Package Installer w/in Atom and got a whole heap of errors:

<https://discuss.atom.io/t/troubleshooting-failed-hydrogen-install-croaks-on-fatal-error-zmq-h-no-such-file-or-directory/22061/3>

Coming over here, I found [installation requirements](https://atom.io/packages/hydrogen) and discovered that I needed a few packages, some via `apt` and some via `pip` before I could install Hydrogen. 

It would have been super helpful for the installation failure to end with some helpful information. Maybe something like "Installation failed. Check *a website* and make sure you have all the dependancies in place!"

**Comment by willwhitney** [comment]
Very true. Let me figure out if that's possible with the Atom installation process.

**Comment by terraqout** [comment]
We can use preinstall npm hook and check it:
```
pip show ipython[notebook] || echo "Please install ipython" && exit 1
#Other checks
```

Echo and exit can should be done with crosssystem npm package, of course.

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/pull/147
