### ISSUE TITLE
No Kernels Installed

### ISSUE THREAD

**Issue by dlefcoe** [nteract/hydrogen#1261]
**No Kernels Installed:**

No kernels are installed on your system so you will not be able to execute code in any language.

**Steps to Reproduce:**

1. install atom on windows 10
2. install hydrogen package
3. run hydrogen

**Versions:**
Windows 10 with the version of Hydrogen and Atom.

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Logs:**

No kernels are installed on your system so you will not be able to execute code in any language.

**Comment by lgeiger** [comment]
Have you read the installation instructions: https://nteract.gitbooks.io/hydrogen/docs/Installation.html?

**Comment by dlefcoe** [comment]
yes, i have.  i have done all of this...  does not seem to work.   not sure what to do as they instructions are pretty simple ?!?

**Comment by lgeiger** [comment]
Do you have a kernel installed for the language you want to execute

**Comment by n-riesco** [comment]
@lgeiger here's some context. @dlefcoe reported this issue inside another issue that had been closed. See [his comment and responses below](https://github.com/nteract/hydrogen/issues/944#issuecomment-369422839) for more details. @dlefcoe's tried to install the kernel manually, but Hydrogen still can find it.

**Comment by dlefcoe** [comment]
yes, i have done this.

the language is javascript (node.js).    also tried with python 3.0.    same. am really struggling to figure out what to do ?!?!?

**Comment by nobleach** [comment]
I too am noticing this after installing Atom 1.25. Every kernel I attempt to use gives me an error asking if it's in my path. I did re-compile as suggested.

**Comment by dlefcoe** [comment]
so reinstall node ?   is this the solution ?  you have a link or instruction for installing new version using NVM please ? ?

**Comment by nobleach** [comment]
No, not at all. I just realized _that_ is what was causing _my_ problem. I updated to node 8.10. My suggestion is that you run `npm build` from your terminal with whatever node version you're currently using. And, to test things out, make sure you can run your kernel from the command line or just try `which ijskernel` (or whatever kernel you care to use)

**Comment by n-riesco** [comment]
@vijaykarthik123 What happens when you run the command `hydrogen:update-kernels`?

**Comment by dlefcoe** [comment]
where should i run the suggested command please ?  in atom or in the command prompt ?!?

**Comment by n-riesco** [comment]
@dlefcoe It's under `Packages > Hydrogen` (or you could type after pressing `shift+ctrl+p`).

**Comment by dlefcoe** [comment]
i type `shift+ctrl+p`
and then enter `hydrogen:update-kernels`

it brings up the same error message that am trying to resolve but cannot:
![image](https://user-images.githubusercontent.com/17166744/39366279-63d02e34-4a2b-11e8-9edc-7c279e76a480.png)

**Comment by n-riesco** [comment]
@dlefcoe in your case, please could you also confirm that the file `%APPDATA%\jupyter\kernels\javascript\kernel.json` exists and post the contents here?

(note that, by default, Windows hides file extensions and you may have created a file named `kernel.json.txt` instead of `kernel.json`; you could tell the difference using the file explorer assigns, because the type `JSON File` is assigned to files with the extension `.json`, and the type `Text Document` to files with extention `.txt`).

---

For anyone else having this issue, please could you post here:
- what happens when you run the command `hydrogen:update-kernels`
- your operating system
- whether IPython or Jupyter is installed in your machine
- and if Jupyter is installed, the output of running: `jupyter kernelspec list`

**Comment by n-riesco** [comment]
@dlefcoe I got to reproduce the issue and it seems to be caused one of the libraries used by hydrogen. I've opened an issue on their repo: https://github.com/nteract/kernelspecs/issues/31

**Comment by n-riesco** [comment]
@dlefcoe The issue was actually caused by the kernelspec. The backward slashed need escaping, like this:

```
{ "argv": [ "C:\\Users\\Owner\\AppData\\Roaming\\ijskernel.cmd", "--hide-undefined", "{connection_file}", "--protocol=5.0" ], "display_name": "Javascript (Node.js)", "language": "javascript" }
```

**Comment by n-riesco** [comment]
@dlefcoe It looks like the path `C:\\Users\\Owner\\AppData\\Roaming\\ijskernel.cmd` is wrong.

I reckon it should be: `C:\\Users\\Owner\\AppData\\Roaming\\npm\\ijskernel.cmd`

**Comment by dlefcoe** [comment]
This solves the problem.

The final solution is to update `kernel.json` accordingly:

`{ "argv": [ "C:\\Users\\Owner\\AppData\\Roaming\\npm\\ijskernel.cmd", "--hide-undefined", "{connection_file}", "--protocol=5.0" ], "display_name": "Javascript (Node.js)", "language": "javascript" }
`

**Comment by dlefcoe** [comment]
Welcome to close.  Believe it was never resolved.

**Comment by n-riesco** [comment]
@m-y-reich : in your case the issue seems to be that the tab `untitled` hasn't been assigned a language. Please, save the tab to a file with the appropriate extension and try again.

**Comment by m-y-reich** [comment]
I managed to solve my issue. 
1. I had to only run the third and fourth line of the kernel installation instruction in the  command prompt. (originally I didn't try further than the first line when that one didn't execute)
2. I had to save the file in in Atom as xxx.**py** for it to be recognized as a python file.
