### ISSUE TITLE
Add information about incompatible packages view to docs troubleshooting page

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1264]
Please see https://github.com/atom/atom/issues/16992

Thanks.

**Comment by lgeiger** [comment]
Have you rebuild Hydrogen?

Atom should prompt you to do so after upgrading.
You can manually rebuild Hydrogen from the Panel that opens when executing `Incompatible Packages: View` via the command palette.

**Comment by dsanalytics** [comment]
Atom did not prompt me to do that - can I just reinstall it with apm instead?

**Comment by nikitakit** [comment]
We've had several reports similar to this one on slack. Is it possible that the latest version of Atom is somehow messing up and not showing the rebuild message on first launch? Or is it just the case that the rebuild button is hidden inside the "Incompatible Packages" page and hard to access if you don't know it exists?

**Comment by jlewis91** [comment]
Had the same issue. For the theme I use, `Nord Atom`, the `Rebuild` button is essentially invisible until you hover over it. And unfortunately, while the `Rebuild` button works, the `apm rebuild` command does not. Seems like an unfortunate combination of a UI issue & the fact that the command has no effect.

**Comment by dsanalytics** [comment]
@jlewis91 - have you tried to just install with `apm install ...` vs `apm rebuild`?

**Comment by jlewis91** [comment]
I believe I tried both. `apm rebuild` definitely did not work.

**Comment by dsanalytics** [comment]
@lgeiger so is this atom issue then? They closed my ticket https://github.com/atom/atom/issues/16992 Can you get in touch with atom people and get them to reopen and take a look? Thanks.

**Comment by 77QingLiu** [comment]
Same issue. `apm rebuild hydrogen` not work

**Comment by dsanalytics** [comment]
@77QingLiu have you tried `apm install hydrogen`?

**Comment by 77QingLiu** [comment]
@dsanalytics, tried but not working. even reinstall the hydrogen package.

**Comment by dsanalytics** [comment]
@lgeiger so is this hydrogen or atom issue? Do we know?

**Comment by BenRussert** [comment]
I've seen issues like this before where apm rebuild didn't work, but for whatever reason the atom gui screen for incompatible modules was able to fix it.

See @lgeiger s comment about this view above. Does this fix the issue @77QingLiu?

**Comment by 77QingLiu** [comment]
@BenRussert, not yet. Rebuild or reinstall the package both not work, even reinstall Atom

**Comment by Kriechi** [comment]
I'm experiencing the same issue:
```
Failed to require the main module of 'Hydrogen' because it requires one or more incompatible native modules (canvas, zeromq).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```
Neither rebuild, nor uninstall/install resolves it.
I cannot connect to any servers anymore. Hydrogen is unusable for me.

**Comment by dsanalytics** [comment]
@Kriechi  , @jlewis91  can someone post an image showing rebuild button's GUI location - it seems that due to some bug in Atom it may be hidden unless you hover over it as on of you reported. Thanks.

**Comment by BenRussert** [comment]
Just took one randomly last night! It's that tiny red bug icon at the bottom right if you can see it.

![incompat-packages-view](https://user-images.githubusercontent.com/10860657/38326862-1c5b9cac-3804-11e8-9c08-7d020650288e.png)

**Comment by dsanalytics** [comment]
@BenRussert - yes I can see it. Thanks for posting.

![image](https://user-images.githubusercontent.com/32625394/38327162-2bfa86a6-380d-11e8-8ff5-aab77393a834.png)

**Comment by dsanalytics** [comment]
@77QingLiu based on the screenshots just posted, is that what you tried and didn't work?
If so, can you post the error message for atom|hydrogen people to check?

**Comment by BenRussert** [comment]
Maybe these screenshots and info on [the incompatible packages view](https://github.com/atom/incompatible-packages) need to be added to our docs, the issue comes up each time a new version of atom is installed. 

Any new contributors?
