### ISSUE TITLE
Doesn't allow Atom to preserve code folds

### ISSUE THREAD

**Issue by jrial** [nteract/hydrogen#1266]
**Description:**

In Atom, when you close a window, it remembers which parts of the code were folded. Upon next launch, it launches with your folding just the way you left it. With Hydrogen enabled, Atom starts with the folded sections neatly folded, only to promptly unfold them.

**Steps to Reproduce:**

1. Fold a few sections of your code
2. Restart your editor

With Hydrogen enabled, the folds will initially be preserved, but will get unfolded during Atom's startup window. With Hydrogen disabled, the folds remain folded. Animation of behaviour with Hydrogen enabled:

![output](https://user-images.githubusercontent.com/570247/37761294-8c52cd46-2db9-11e8-81d7-10fec7ef2c8a.gif)

More information on Atom's "remember folds" feature: atom/atom#13258

**Versions:**

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS: Linux Mint 18.3 (Sylvia)
Kernel: 4.13.0-37-generic x86_64

**Logs:**

Not applicable

**Comment by lgeiger** [comment]
That's strange, because Hydrogen only activates when triggering an [activation command](https://github.com/nteract/hydrogen/blob/master/package.json#L21). Meaning Hydrogen doesn't really run on Atom start up.
Are you sure it's not caused by another package?

**Comment by jrial** [comment]
I don't rule anything out, but in my tests I can consistently demonstrate the difference between Hydrogen enabled and Hydrogen disabled.

**Comment by nikitakit** [comment]
Do you have any hydrogen plug-ins installed, by chance?

**Comment by lgeiger** [comment]
I just checked and I can't reproduce this with Hydrogen on Atom 1.25 and Atom 1.26-beta0 on my machine.

**Comment by jrial** [comment]
Sorry to waste your time. I was unable to reproduce with Hydrogen disabled, while being pretty consistently able to reproduce with Hydrogen enabled. I must've relaunched my Atom like 20 times to be sure.

Apparently it takes 25 times to confirm stuff with any semblance of certainty, because I now witnessed this behaviour with Hydrogen disabled. My search continues.
