### ISSUE TITLE
Hydrogen 2.3.0 Not Working..

### ISSUE THREAD

**Issue by lwazin** [nteract/hydrogen#1268]
**Description:**

Hydrogen doesn't work on my system.. fix needed.

**Versions:**

OS: Windows 10, Hydrogen Version: 2.3.0

(https://user-images.githubusercontent.com/37657157/37765126-1bf6fb68-2dcc-11e8-8cf0-7a707ad9f194.PNG)

Thanks in advanced Team

**Comment by lgeiger** [comment]
That's normal when Atom internally upgrades Electron versions. The fix is clicking on the rebuild button.

**Comment by lwazin** [comment]
Thanks..
