### ISSUE TITLE
Using R w/ ggplot + qplot: plots only printed when notice is passed?

### ISSUE THREAD

**Issue by mbroedl** [nteract/hydrogen#1272]
**Description:**

Hydrogen (unlike jupyter notebook) seems to only print graphs when there is a note from ggplot attached with it.
I assume it is related to the notice, as this is the only change from one plot to another.
Reproducing a warning, did not have any results either.

![image](https://user-images.githubusercontent.com/19365355/38027895-1143f5ec-3289-11e8-9ff6-a3346c246927.png)
![image](https://user-images.githubusercontent.com/19365355/38027906-1b4d2d60-3289-11e8-8723-ae6f038948b1.png)

I have not tried different R kernels, because it was a big mess to install one already.
If required I am happy to do so. But given that the Kernel works in Jupyter Notebook, I don't see how this might be an issue. — In Rstudio the minimal example works fine as well.

**Steps to Reproduce:**

(1)
Assuming that the communication between Kernel and Hydrogen is at fault, install Juniper Kernel.
So in R execute:
```
install.packages('JuniperKernel')
library(JuniperKernel)
installJuniper()
```
verify with `JuniperKernel::listKernels()` that the kernel is installed.

(2)
Execute the following minimal example:
```
library(ggplot2)

# displays with notice
qplot(cyl, data=mpg)
# does not display
qplot(cyl, data=mpg, binwidth = 1)

# displays warning and notice in R, only notice in hydrogen
ggplot(mpg, aes(x=cyl)) + geom_histogram() + scale_y_continuous(limits=c(0,1))
# displays warning in R, nothing in hydrogen
ggplot(mpg, aes(x=cyl)) + geom_histogram(binwidth=1) + scale_y_continuous(limits=c(0,1))
```
Output in RStudio with the same script (and all four graphs print):
![image](https://user-images.githubusercontent.com/19365355/38027939-3199de4c-3289-11e8-96af-635adaa0c612.png)

**Versions:**

Up to date Manjaro Linux.

Atom    : 1.25.0
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1

Hydrogen 2.3.0

R 3.4.4
with Juniper Kernel 1.2.3.0
https://cran.r-project.org/web/packages/JuniperKernel/index.html

**Logs:**

```
'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
setDefaults @ /usr/lib/atom/src/config.js:1057
transact @ /usr/lib/atom/src/config.js:1048
transact @ /usr/lib/atom/src/config.js:815
setDefaults @ /usr/lib/atom/src/config.js:1043
transact @ /usr/lib/atom/src/config.js:927
transact @ /usr/lib/atom/src/config.js:815
setSchema @ /usr/lib/atom/src/config.js:926
registerConfigSchemaFromMainModule @ /usr/lib/atom/src/package.js:252
activateNow @ /usr/lib/atom/src/package.js:216
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event @ /usr/lib/atom/src/package.js:860
module.exports.Emitter.simpleDispatch @ /usr/lib/atom/node_modules/event-kit/lib/emitter.js:25
module.exports.Emitter.emit @ /usr/lib/atom/node_modules/event-kit/lib/emitter.js:141
handleCommandEvent @ /usr/lib/atom/src/command-registry.js:360
module.exports.KeymapManager.dispatchCommandEvent @ /usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617
module.exports.KeymapManager.handleKeyboardEvent @ /usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408
handleDocumentKeyEvent @ /usr/lib/atom/src/window-event-handler.js:110
```

**Comment by BenRussert** [comment]
@mbroedl Thanks for the detailed issue report. I tried the juniper R kernel as you described and had the same results.

As a work around, try pasting this into your atom stylesheet `~/.atom/styles.less`:

```
.multiline-container .hydrogen_cell_display{
      min-width: 80ch;
}

```

There is actually an svg image there, but hidden by width too small. Hopefully we can come up with a better solution soon, but this will get you going for now.

**Comment by mbroedl** [comment]
Ah, I hadn't even considered that it could be an auto-scaled svg image.
I tried what you suggested, but the not so neat hydrogen layout bugged me a bit. ;)
So I experimented a bit and came to this solution:

```
.multiline-container .hydrogen_cell_display .cell_display svg {
    width: 600px;
}
```
The 600px is a perfect fit for the hydrogen box, probably only because of which line-length, etc I have though.
This does work neatly, the only thing is that it's a bit too small. (With your solution it wasn't but I had to use the overflow-x scroll bars.) So maybe I can just load a library to pan and zoom, and apply it to the same element. ;)

Thanks so much for your help, quite happy now!

**Comment by BenRussert** [comment]
Glad to hear it works!

I wonder if we should add something like this to our hydrogen styles sheet? The only hesitation I have is that not everyone wants their svg output sized the same (as you pointed out :smile: ).

**Comment by mbroedl** [comment]
Don't ask me why but the following works really well!
First one sets a resize button (a bit tricky to grab) into the bottom right corner of the display.
And then the width 100% (I do not know where it gets the reference from though!) puts it to 300px on my screen, but it's easy to scale. :) It does not go any smaller than that for some reason.

```
.multiline-container .hydrogen_cell_display {
    resize: both;
}

.multiline-container .hydrogen_cell_display .cell_display svg {
    width: 100%;
}
```

Would be nice to add this maybe? Or at least via a `.svg` class (until a css :has(svg) would work) to the hydrogen cell that optionally makes it resizable?
When setting the svg to a fixed with, it is impossible to scale it down, so maybe min-width would be better than my suggestion above? Possibly one could add an option in the settings for "standard graphics width" or something? (I don't know how it's handled at the moment.)

**Comment by mbroedl** [comment]
Maybe one could add some buttons in the future, like in the [preview-inline](https://github.com/mangecoeur/preview-inline) package?

![image](https://user-images.githubusercontent.com/19365355/38619999-59918c62-3d95-11e8-9a7c-36732ba7713a.png)
