### ISSUE TITLE
No utf8 support on mac

### ISSUE THREAD

**Issue by mlangiu** [nteract/hydrogen#1273]
**Description:**
Attempting to run things like

    π = 1

or 

    from numpy import pi as π

the console spits out 

     File "<ipython-input-5-9b26ab3f94f3>", line 1
        π = 1
        ^
    SyntaxError: invalid syntax

or 

    File "<ipython-input-4-9a9584e0e11b>", line 1
       from numpy import pi as π
                               ^
    SyntaxError: invalid syntax

despite the magic comment

    # -*- coding: utf-8 -*-

at the beginning of the file

**Versions:**

macOS    :10.12.6 (16G29)
Atom       : 1.25.0
Electron  : 1.7.11
Chrome   : 58.0.3029.110
Node    : 7.9.0

**Comment by lgeiger** [comment]
That probably depends on the Python installation you're using. If I recall correctly Python 2 doesn't fully support unicode, so I suspect you're using Python 2?

I just checked with Python 3 and it works as it should.

**Comment by mlangiu** [comment]
I am using python3

![screen shot 2018-03-29 at 08 33 13](https://user-images.githubusercontent.com/15340151/38073575-f44a5ce4-332b-11e8-9ec1-36fee450c2c3.png)

**Comment by lgeiger** [comment]
Could you run
```python
import sys
print(sys.version)
```
in Hydrogen to check which exact version you're using?

Also upgrading ipython with:
```shell
python3 -m pip install ipykernel --upgrade
python3 -m ipykernel install --user
```
might help.

**Comment by mlangiu** [comment]
Still no progress, the kernel was already up to date...

The system version printed is:

2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

**Comment by lgeiger** [comment]
>The system version printed is:
2.7.14 (default, Mar 22 2018, 15:04:47)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

Looks like your Python 3 executable is symlinked to Python 2 so you're using 2.7 instead of 3.x

**Comment by mlangiu** [comment]
Hmm you were right!
But I still think it is a bit strange, I would have assumed that either selecting the Python 3 kernel upon first execution of Hydrogen or the magic comment at the top of the file should have resulted in loading the correct version.

Instead I had to manually change all occurrences of `python` to `python3` in 
`.atom/packages/script/lib/grammars/python.coffee`, which seems sort of twisted.

What if I want to run a python2 script at some point, will I have to edit the coffee scripe everytime I want to switch back and forth between the two?

I'd appreciate if you could point me towards some more elegant solution to this.
In any case: thanks for the help so far! :)

**Comment by lgeiger** [comment]
> But I still think it is a bit strange, I would have assumed that either selecting the Python 3 kernel upon first execution of Hydrogen or the magic comment at the top of the file should have resulted in loading the correct version.

Hydrogen will prompt you to select a kernel on startup if you have multiple kernels installed. If you run:
```shell
python3 -m pip install ipykernel --upgrade
python3 -m ipykernel install --user
python2 -m pip install ipykernel --upgrade
python2 -m ipykernel install --user
```
After Atom restart Hydrogen will then prompt you which kernel to use. This is inline with the behavior of jupyter.

**Comment by lgeiger** [comment]
If you want to be extra verbose you can remove the python folders in `~/Library/Jupyter/kernel` before running the above commands.

**Comment by mlangiu** [comment]
This prompt is exactly what I meant! What confuses me is that **despite** selecting the python3 kernel to use with Hydrogen for the current file, the `python` command is invoked instead of `python3`.
I would expect that upon selection of a python 2 or 3 kernel that the corresponding version is started

**Comment by lgeiger** [comment]
Have you removed `~/Library/Jupyter/kernels` before running the install commands?

While the above commands should install this correctly, it seams that there's something weird going on with your Python setup. In any case there's an easy manual fix:

Edit `argv` in `~/Library/Jupyter/kernels/python3/kernel.json` to point to the correct Python 3 executable.

For me this looks something like this:
```python
{
 "argv": [
  "/usr/local/opt/python3/bin/python3.6",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

**Comment by mlangiu** [comment]
Aah, I had overlooked your comment on `~/Library/Jupyter/kernels`!
Deleting that directory and reissuing the `pip` commands seems to do it, even after reverting the `python.coffee` script.
Thank you for the help ;)
