### ISSUE TITLE
conflict with Atom 1.25.0

### ISSUE THREAD

**Issue by iceblove** [nteract/hydrogen#1279]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
     error when auto update 

2. [Second Step]

**Versions:**
Atom 1.25.0

Which OS and which version of Hydrogen and Atom are you running?

Mac OS High Sierra，Atom 1.25.0，Hydrogen 2.3.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.225.8:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/icerin/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by BenRussert** [comment]
You will need to rebuild modules using the incompatible packages view. Please see #1264 for more information.

Closing as duplicate, but feel free to reply with questions!

**Comment by iceblove** [comment]
thanks
