### ISSUE TITLE
LaTeX/MathJax support is broken for %%markdown cell.

### ISSUE THREAD

**Issue by tribbloid** [nteract/hydrogen#1283]
**Description:**

The following markdown cell in hydrogen:

```
%%markdown

$$\dot z$$
```

will simply not render the last line into equation.

**Steps to Reproduce:**

create a py file
copy the above code into it
execute Hydrogen: Run Cell

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Hydrogen 2.3.0 Atom 1.25.0

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by kylebarron** [comment]
`%%markdown` is not a cell marker. You need something like `# %%`. Otherwise you need to select all the text:
![image](https://user-images.githubusercontent.com/15164633/52834575-82e60200-30b0-11e9-90dc-3d769f3e88df.png)

**Comment by jacopok** [comment]
I am also encountering this issue, by running the cell in a .py file.

Atom 1.37.0 x64
Hydrogen 2.10.3

![Minimal Working Example](https://user-images.githubusercontent.com/11020774/60959934-5b1a6380-a309-11e9-8fa2-ca979cb167fa.png)

**Comment by aviatesk** [comment]
@jacopok This issue is moved into #1669 and please subscribe it if you want.
