### ISSUE TITLE
Q: Fixed font in hydrogen output area 

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1288]
Anyone knows how to change/config hydrogen output area font? Being able to specifying font size as well would be great. Thanks.

**Comment by BenRussert** [comment]
There is actually an "Output area font size" in the hydrogen config. Try that out and see if it's what you're looking for.

**Comment by dsanalytics** [comment]
I'm looking to change font 1st and foremost - e.g. to fixed font so that formatted numbers line up nicely across rows.

P.S. I could not find that font size option - screenshot would be appreciated.

**Comment by BenRussert** [comment]
![screenshot from 2018-05-03 05-41-46](https://user-images.githubusercontent.com/10860657/39574534-d82328b4-4e94-11e8-86b2-28c68d5fe7d1.png)

**Comment by dsanalytics** [comment]
Thanks. Handy option, but I need an option to change font too.
