### ISSUE TITLE
Q: Pandas dataframe nicely formatted output

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1289]
Does anyone know how to get nicely formatted output, as shown below, anywhere in code? Atom outputs this only if last line. Thanks.

P.S. I do know about tabulate and it's not the same thing.
P.S. to_html does not work either

![image](https://user-images.githubusercontent.com/32625394/38641410-8907763a-3d9c-11e8-8133-e4b66dcad2e9.png)

![image](https://user-images.githubusercontent.com/32625394/38641454-ae37cb9e-3d9c-11e8-930b-216c8ebe58ef.png)

**Comment by sigbjorngrini** [comment]
What about display()?

```Python
import pandas as pd
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
        'year': [2012, 2012, 2013, 2014, 2014],
        'reports': [4, 24, 31, 2, 3]}
df = pd.DataFrame(data)

from IPython.display import display
display(df)
df
```

![bilde](https://user-images.githubusercontent.com/10991790/38776507-2471f458-4098-11e8-9dd4-21ad07778ce6.png)

**Comment by dsanalytics** [comment]
@sigbjorngrini - that's the thing - thanks!
