### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by scienceyeaux** [nteract/hydrogen#1290]
I've been using Hydrogen for awhile now without any problems and now all of a sudden I'm getting the following error when trying to run a cell within Atom: 

![image](https://user-images.githubusercontent.com/36206562/38642315-b7e47362-3da7-11e8-86cc-8ad67c0ba48c.png)

This is what my developer console shows:

![image](https://user-images.githubusercontent.com/36206562/38643172-49641944-3daa-11e8-9f6e-c75915e1c21a.png)

I tried the following:
```
pip3 install ipykernel --upgrade
python3 -m ipykernel install --user
```
I've also scoured through the debugging guide, issues on Github, SO, etc. I can't figure this out.

These are my current settings in Hydrogen:

![image](https://user-images.githubusercontent.com/36206562/38642980-bdbd0108-3da9-11e8-8e76-1e1db3b8eb21.png)

**Steps to Reproduce:**

1. Activate virtual env.
2. Open atom from command line.
3. Run a cell using Hydrogen (causes error)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by nikitakit** [comment]
I believe this is the same issue as https://github.com/jupyter/notebook/issues/3407 (see there for a solution)

**Comment by kylebarron** [comment]
Closing as this can be solved by following the instructions listed in https://github.com/jupyter/notebook/issues/3407. @scienceyeaux 	reopen if you have any issues.
