### ISSUE TITLE
Hydrogen kernel shuts down after each command (doesn't stay running as idle)

### ISSUE THREAD

**Issue by ethan92429** [nteract/hydrogen#1292]
**Description:**

Hydrogen kernel shuts down after each command (doesn't stay running as idle).  This only happened when I switched to 2.4.0 from 2.3.0. 

**Steps to Reproduce:**

1. Imagine the following file (it's markdown):
```Markdown
```python
t=5+10
print(t)
```
2. Now within Atom, use shift-enter to start the kernel and run the first command. In 2.3.0, this runs and leaves a little "Python 3 | idle" flag in the lower left corner to indicate my kernel is idle but still alive. However, in 2.4.0 (and I tested this on Windows and mac), that tag doesn't stay there and the kernel immediately shuts down. Then when running hydrogen on the next line, the kernel starts up again but has cleared its memory, so t is not defined. I've switched multiple times between 2.3.0 and 2.4.0 to confirm there were no confounding variables. 

**Versions:**

2.4.0

Which OS and which version of Hydrogen and Atom are you running?

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Logs:**

The only minor issue I see that comes up in the console (with debug messages enabled) is that I don't have a default kernel defined:

```
'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
```
and in 2.3.0, I did select the kernel I wanted, but it didn't restart each time I used shift-enter.

**Comment by BenRussert** [comment]
Fix incoming for this, thanks for the report!

**Comment by dsanalytics** [comment]
@ethan92429 v2.4.1 has been released - when you get a chance, check for the issues you reported and let us know.

**Comment by ethan92429** [comment]
@dsanalytics 2.4.1 is working well! Thanks for the update.
