### ISSUE TITLE
Is a Jupyter installation required for Hydrogen?

### ISSUE THREAD

**Issue by russellbits** [nteract/hydrogen#1297]
I have installed Hydrogen via apm.
I installed the javascript kernel via npm.
`which ijavascript` yields `/usr/local/bin/ijskernel`
I have language mappings in Atom set to {"javascript":"ijskernel"}

When I try to run in a .js file I get two errors: 1. "No kernels are installed on your system so you will not be able to execute code in any language." and 2. "No kernel for grammar JavaScript found."

Is installing Jupyter required before I can run Hydrogen?
Does the camel-cased JavaScript have something to do with this? 
Suggestions?

**Comment by n-riesco** [comment]
Hydrogen doesn't require the installation of Jupyter any longer.
But IJavascript requires Jupyter to install its kernelspec.
If you don't want to install Jupyter, you could install IJavascript's kernelspec manually as described in https://github.com/n-riesco/ijavascript/issues/148.
