### ISSUE TITLE
error installing hydrogen behind a proxy on Windows 32bit

### ISSUE THREAD

**Issue by justdoGIT** [nteract/hydrogen#1298]
> canvas@1.6.10 install /tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild

> zeromq@4.6.0 install /tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install No prebuilt binaries found (target=1.6.16 runtime=electron arch=ia32 platform=linux)

/tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r
`-- (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/opt/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/opt/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /opt/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
{ Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'github.com',
  host: 'github.com',
  port: 443 }
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-118324-6046-schvki.7vzxj0dx6r No description
npm WARN apm-install-dir-118324-6046-schvki.7vzxj0dx6r No repository field.
npm WARN apm-install-dir-118324-6046-schvki.7vzxj0dx6r No README data
npm WARN apm-install-dir-118324-6046-schvki.7vzxj0dx6r No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.10 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.10 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/kamal/.atom/.apm/.apmrc" "--userconfig" "/home/kamal/.atom/.apmrc" "install" "/tmp/d-118324-6046-1nmeuy.tuz7bq33di/package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118324-6046-schvki.7vzxj0dx6r/npm-debug.log
npm ERR! code 1

**Comment by justdoGIT** [comment]
i guess it is 32 bit ubuntu 16.04 OS , thats why there is some issue..

**Comment by n-riesco** [comment]
@justdoGIT yes, that's the issue. `zeromq` doesn't distribute 32-bit binaries. Instead, `zeromq` tries to build the native module using `node-gyp`. See the requirements [here](https://github.com/nodejs/node-gyp#on-unix).

**Comment by justdoGIT** [comment]
after resolving python 2 issues now i am facing these errors 
@n-riesco  can you please have a look and suggest me something


(py2) kamal ~ $ apm install hydrogen
Installing hydrogen to /home/kamal/.atom/packages ✗

    canvas@1.6.10 install /tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/node_modules/Hydrogen/node_modules/canvas
    node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/node_modules/Hydrogen/node_modules/canvas/build'
SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
COPY Release/canvas-postbuild.node
CXX(target) Release/obj.target/canvas/src/Canvas.o
CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
CXX(target) Release/obj.target/canvas/src/color.o
CXX(target) Release/obj.target/canvas/src/Image.o
CXX(target) Release/obj.target/canvas/src/ImageData.o
CXX(target) Release/obj.target/canvas/src/init.o
CXX(target) Release/obj.target/canvas/src/FontFace.o
SOLINK_MODULE(target) Release/obj.target/canvas.node
COPY Release/canvas.node
make: Leaving directory '/tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/node_modules/Hydrogen/node_modules/canvas/build'

    zeromq@4.6.0 install /tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/node_modules/Hydrogen/node_modules/zeromq
    node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install No prebuilt binaries found (target=1.6.16 runtime=electron arch=ia32 platform=linux)

/tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i
`-- (empty)

In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(j_compress_ptr)’:
../src/JPEGStream.h:42:108: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)dest->closure->fn, 2, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function ‘void term_closure_destination(j_compress_ptr)’:
../src/JPEGStream.h:63:113: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)dest->closure->fn, 2, data_argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h:71:112: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)dest->closure->fn, 2, end_argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
../src/Canvas.cc: In static member function ‘static void Canvas::ToBufferAsyncAfter(uv_work_t)’:
../src/Canvas.cc:221:31: warning: ‘v8::Localv8::Value Nan::Callback::Call(int, v8::Localv8::Value) const’ is deprecated [-Wdeprecated-declarations]
closure->pfn->Call(1, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:1618:3: note: declared here
Call(int argc, v8::Localv8::Value argv[]) const {
^
../src/Canvas.cc:226:31: warning: ‘v8::Localv8::Value Nan::Callback::Call(int, v8::Localv8::Value) const’ is deprecated [-Wdeprecated-declarations]
closure->pfn->Call(2, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:1618:3: note: declared here
Call(int argc, v8::Localv8::Value argv[]) const {
^
../src/Canvas.cc: In function ‘cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)’:
../src/Canvas.cc:377:102: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)closure->fn, 3, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:446:103: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)closure.fn, 1, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
../src/Canvas.cc:452:103: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Localv8::Function)closure.fn, 1, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
../src/Canvas.cc: In function ‘cairo_status_t streamPDF(void, const uint8_t*, unsigned int)’:
../src/Canvas.cc:476:77: warning: ‘v8::Localv8::Value Nan::MakeCallback(v8::Localv8::Object, v8::Localv8::Function, int, v8::Localv8::Value)’ is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), closure->fn, 3, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Canvas.cc:7:
../../nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Localv8::Value MakeCallback(
^
../src/Image.cc: In member function ‘void Image::loaded()’:
../src/Image.cc:380:25: warning: ‘v8::Localv8::Value Nan::Callback::Call(int, v8::Localv8::Value) const’ is deprecated [-Wdeprecated-declarations]
onload->Call(0, NULL);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Image.cc:7:
../../nan/nan.h:1618:3: note: declared here
Call(int argc, v8::Localv8::Value argv[]) const {
^
../src/Image.cc: In member function ‘void Image::error(v8::Localv8::Value)’:
../src/Image.cc:393:26: warning: ‘v8::Localv8::Value Nan::Callback::Call(int, v8::Localv8::Value*) const’ is deprecated [-Wdeprecated-declarations]
onerror->Call(1, argv);
^
In file included from ../src/Canvas.h:22:0,
from ../src/Image.cc:7:
../../nan/nan.h:1618:3: note: declared here
Call(int argc, v8::Localv8::Value argv[]) const {
^
{ Error: getaddrinfo EAI_AGAIN github.com:443
at Object.exports._errnoException (util.js:1022:11)
at errnoException (dns.js:33:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
code: 'EAI_AGAIN',
errno: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'github.com',
host: 'github.com',
port: 443 }
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-118325-4953-1utuiku.zqimxtj4i No description
npm WARN apm-install-dir-118325-4953-1utuiku.zqimxtj4i No repository field.
npm WARN apm-install-dir-118325-4953-1utuiku.zqimxtj4i No README data
npm WARN apm-install-dir-118325-4953-1utuiku.zqimxtj4i No license field.
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/kamal/.atom/.apm/.apmrc" "--userconfig" "/home/kamal/.atom/.apmrc" "install" "/tmp/d-118325-4953-qaic0g.2m743ac3di/package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/apm-install-dir-118325-4953-1utuiku.zqimxtj4i/npm-debug.log
npm ERR! code 1

**Comment by n-riesco** [comment]
Now the problem is with `canvas`. See the requirements [here](https://github.com/Automattic/node-canvas#compiling).

**Comment by n-riesco** [comment]
@justdoGIT `zeromq` needs access to github to download `libzmq`.

**Comment by justdoGIT** [comment]
so should i manually install libzmq with python 2.7

**Comment by eskemojoe007** [comment]
@n-riesco running into a similar issue.  I've used Hydrogen for quite some time.  Updating atom to 1.28 broke everything on my windows rigs.  I fixed the python issue by using `apm config set python c:\path\to\python2`, but now run into canvas issues a little different than above. 

    Installing hydrogen to C:\Users\<username>\.atom\packages failed

    > canvas@1.6.11 install C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\canvas
    > node-gyp rebuild


    C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )

    > zeromq@4.6.0 install C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\zeromq
    > node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


    The system cannot find the path specified.

    Downloading libzmq for Windows
    Download finished

    C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
    C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi
    `-- (empty)


    The system cannot find the path specified.
    gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:305:16)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Windows_NT 10.0.15063
    gyp ERR! command "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\canvas
    gyp ERR! node -v v6.9.5
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok
    The system cannot find the path specified.
    gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\<username>\AppData\Local\atom\app-1.28.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:305:16)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Windows_NT 10.0.15063
    gyp ERR! command "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\node_modules\Hydrogen\node_modules\zeromq
    gyp ERR! node -v v6.9.5
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok
    npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\package.json'
    npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
    npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
    npm WARN apm-install-dir-11862-12176-m0scbf.01h1cq5mi No description
    npm WARN apm-install-dir-11862-12176-m0scbf.01h1cq5mi No repository field.
    npm WARN apm-install-dir-11862-12176-m0scbf.01h1cq5mi No README data
    npm WARN apm-install-dir-11862-12176-m0scbf.01h1cq5mi No license field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules\Hydrogen\node_modules\canvas):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
    npm ERR! Windows_NT 10.0.15063
    npm ERR! argv "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<username>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<username>\\.atom\\.apmrc" "install" "C:\\Users\\<usershort>~1\\AppData\\Local\\Temp\\d-11862-12176-9a9b1g.qpewixusor\\package.tgz" "--runtime=electron" "--target=2.0.3" "--arch=x64" "--global-style" "--msvs_version=2015"
    npm ERR! node v6.9.5
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE

    npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the zeromq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs zeromq
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls zeromq
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\<usershort>~1\AppData\Local\Temp\apm-install-dir-11862-12176-m0scbf.01h1cq5mi\npm-debug.log
    npm ERR! code 1

I have installed `GTK2` and `libjpeg-turbo` per the canvas documentation and get the same errors.  Is the `nan` package missing?  I navigated to `\AppData\Local\atom\app-1.28.0\resources\app\apm\bin` and ran `npm install nan` with no luck.

**Comment by n-riesco** [comment]
@eskemojoe007 Could you open a new issue, please?

Judging by the logs you've posted, the issue you see is that `zeromq` doesn't provide binaries for `electron v2` and the install script fails while running `node-gyp rebuild` to build the native module.

**Comment by eskemojoe007** [comment]
@n-riesco It seems as though #1352 discusses the same issue I am having.

**Comment by n-riesco** [comment]
@eskemojoe007 I've edited the title of this issue to make clear this issue is caused by being behind a proxy. And it'll be fixed, when https://github.com/zeromq/zeromq.js/issues/260 is fixed.

**Comment by mhumayoonkh** [comment]
I am also facing this problem downloading hydrogen.

npm ERR! Invalid Version:

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mhuma\AppData\Local\npm-cache\_logs\2023-04-16T04_35_22_289Z-debug-0.log
