### ISSUE TITLE
Q: Selecting all text in hydrogen output area

### ISSUE THREAD

**Issue by dsanalytics** [nteract/hydrogen#1302]
Does anyone know a shortcut to select all text in hydrogen output area? I'm trying to select it all and copy to clipboard. Ctrl-A selects everything - both hydrogen output area and code window text, so it's not doing what I'm looking for. Right now, I have to use a mouse to select which is time consuming if output is very long - pages and pages of output text. Thanks in advance.

OS: Windows 10
Atom: 1.23.3

**Comment by hughcameron** [comment]
Hey @dsanalytics - does this button appear for you above the output area?
<img width="547" alt="copy button" src="https://user-images.githubusercontent.com/5008884/40148267-81020a4c-59b0-11e8-9459-745467eddd52.png">

**Comment by dsanalytics** [comment]
No, because I use the other option for that one auto-scrolls till the end while the 1st one does not for some strange reason. So, I wonder:
1) why there's no Copy button for the 2nd option, and 
2) why the 1st option does not auto-scroll? 

As you can see, it's catch-22 for me.

![image](https://user-images.githubusercontent.com/32625394/40148771-691ea9ec-5935-11e8-9732-1250a8a66538.png)

**Comment by wadethestealth** [comment]
You should be able to `ctrl+a` inside of the list view (the 3 bar option) as well. It should just select everything in the output area. Just make sure you click inside the output area. As for the history view not scrolling this must be a bug from us combining the outputs together.

**Comment by wadethestealth** [comment]
If you still have issues with the ctrl+a, open a new issue with a gif clicking in the output area and then using ctrl+a
