### ISSUE TITLE
Failed to upgrade/install to 2.5.0 using Atom 1.26.1 x64

### ISSUE THREAD

**Issue by taobo33** [nteract/hydrogen#1308]
**Description:**
When I try to upgrade to 2.5.0 within Atom, it failed and I get the same error every time when I try to install Hydrogen

[Description of the issue]
I was using previous version of Hydrogen fine, however an upgrade icon appeared on the right bottom corner of Atom today. After I clicked on it, an error message pop up saying hydrogen install failed.

**Steps to Reproduce:**

1. Install Atom 1.26.1 x64 
2. Go to settings, click "Install Packages"
3. search 'Hydrogen' and click on 'Install' on first result (Hydrogen 2.5.0 in this case)
4. 

**Versions:**

Windows_NT 10.0.17134 x64 (Windows 10 Home with latest 1803 version)
Atom is 1.26.1 x64
Hydrogen 2.5.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**
```
npm ERR! not a package C:\Users\taobo33\AppData\Local\Temp\d-118413-2776-18r5k0n.6y9umr6bt9\package.tgz
npm ERR! addLocal Could not install C:\Users\taobo33\AppData\Local\Temp\d-118413-2776-18r5k0n.6y9umr6bt9\package.tgz
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\taobo33\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\taobo33\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\taobo33\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\taobo33\\.atom\\.apmrc" "install" "C:\\Users\\taobo33\\AppData\\Local\\Temp\\d-118413-2776-18r5k0n.6y9umr6bt9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\taobo33\AppData\Local\Temp\npm-12044-db0b0662\unpack-055defe9\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\taobo33\AppData\Local\Temp\npm-12044-db0b0662\unpack-055defe9\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\taobo33\AppData\Local\Temp\npm-12044-db0b0662\unpack-055defe9\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\taobo33\AppData\Local\Temp\apm-install-dir-118413-2776-ao9sve.wxua6ecdi\npm-debug.log
```
Thanks for checking on this issue.
Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
Have you tried restarting atom and trying again? It looks like it just didn't download properly.

**Comment by taobo33** [comment]
Hi Ben, thanks for the fast response! 
I have tried restarting atom. I even tried restarting the PC a few times. :(
It might have something to do with the new 1803 upgrade :(

**Comment by taobo33** [comment]
after several reboot the same issue persists :(

can I manually place the file that needs download somewhere (in order to )to fix this? Thank you for the advise.

**Comment by taobo33** [comment]
I also tried " apm install hydrogen" in Windows Power Shell as admin.
```
npm ERR! not a package C:\Users\taobo33\AppData\Local\Temp\d-118414-11448-1vlqq6t.72bxd2t9\package.tgz
npm ERR! addLocal Could not install C:\Users\taobo33\AppData\Local\Temp\d-118414-11448-1vlqq6t.72bxd2t9\package.tgz
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\taobo33\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\taobo33\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\taobo33\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\taobo33\\.atom\\.apmrc" "install" "C:\\Users\\taobo33\\AppData\\Local\\Temp\\d-118414-11448-1vlqq6t.72bxd2t9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\taobo33\AppData\Local\Temp\npm-5276-ad413ca5\unpack-de41dcbb\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\taobo33\AppData\Local\Temp\npm-5276-ad413ca5\unpack-de41dcbb\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\taobo33\AppData\Local\Temp\npm-5276-ad413ca5\unpack-de41dcbb\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\taobo33\AppData\Local\Temp\apm-install-dir-118414-11448-1i9sc4f.p87rkbuik9\npm-debug.log
```

However I could not provide the log it mentioned. I can not find such log file in my ..AppData/local/Temp folder. Also tried to un-install Atom. Still can not install Hydrogen 🤕

**Comment by BenRussert** [comment]
Wish I had a better answer for you, I'll have to try on Windows next chance I get and see if I can reproduce.

**Comment by n-riesco** [comment]
@taobo33 are you able to install any other packages in Atom?

**Comment by taobo33** [comment]
No worries Ben, I blame the new 1803 windows update. Other than Atom, it also caused some issue in my taskbar. 
Hi @n-riesco, yes I can install other packages, I have color-picker, indent- guide-improved, emmet and script installed just fine. I will try install more and see if it works. Thanks :)

**Comment by taobo33** [comment]
I've copied the Hydrogen folder from another PC and put it into the package install folder (in my case it is"C:\Users\taobo33\.atom\packages")
Then when I open Atom, the Hydrogen is installed ... Guess this will work if anyone has similar issue with me on PC.
