### ISSUE TITLE
Error executing argument parser 

### ISSUE THREAD

**Issue by josefondrej** [nteract/hydrogen#1313]
**Description:**

The following code does not work if it is run in hydrogen however works fine when executed in python console. 

```
import argparse
parser = argparse.ArgumentParser()
args = parser.parse_args()
```

Probably same problem as in [this issue](https://github.com/spyder-ide/spyder/issues/3883).

**Steps to Reproduce:**

1. Install WinPython
2. Install atom and hydrogen
3. Run the code snippet 

**Versions:**

- Windows 10 Pro
- WinPython 3.7.0
- Atom 1.27.0
- Hydrogen 2.1.1

**Comment by BenRussert** [comment]
The solution from your link works for me. You can add this snippet or put in your startup code in the hydrogen settings if you always want it to run.

```python
import sys
sys.argv=['']
del sys
```
