### ISSUE TITLE
Numpy & Matplotlib suddenly cannot be imported in Hydrogen although it works fine in the Terminal

### ISSUE THREAD

**Issue by bjce** [nteract/hydrogen#1315]
### Description

Numpy & Matplotlib suddenly cannot be imported in Hydrogen in Atom although it works fine in the Terminal

### Steps to Reproduce

I'm regularly importing `Numpy` and `Matplotlib` with `Hydrogen`. They unexpectedly cannot be import for an unknown reason and then appear to be again re-importable, again unexplained.

When trying to import matplotlib with the following command

    import matplotlib.pyplot as plt

This scripts runs without problems when I run in a `Jupyter notebook` or through the `Terminal`. But When trying to run on `Hydrogen` in `Atom`, I get the following error message: 

    File "<ipython-input-3-3dc8365ef973>", line 6
    ModuleNotFoundError: No module named 'matplotlib.backends'; 'matplotlib' is not a package
                                 ^
    SyntaxError: invalid syntax

I get the same error with Pyside2 when trying to run the line 

    from PySide2.QtWidgets import QApplication, QLabel

I get the error message

    ModuleNotFoundError: No module named 'PySide2.QtWidgets'; 'PySide2' is not a package

Here is the path of python (after having typed `which python` in the Terminal): `/anaconda3/bin/python`

I checked that the matplotlib is installed by running the command `conda list` in the Terminal and got (among all the other packages) those lines:

    matplotlib 2.1.2 py36h6d6146d_0
    matplotlib 2.2.2 <pip>
    PySide2 5.9.0a1.dev1525348214

I tried to run the following command in the Terminal but didn't solve the problem

`sudo apt-get install python3-matplotlib`
`sudo pip3 install matplotlib`

I had a similar issue with `numpy` when trying to import `import numpy`. Although import `numpy` was not a problem an hour ago, I get now the following error message (it seems it wants to connect to a previously used script in which numpy was used, to open numpy itself): 

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-5-592c151f282b> in <module>()
          1 # from numpy import genfromtxt as gft
    ----> 2 import numpy

    ~/Downloads/numpy.py in <module>()
    ----> 1 from numpy import genfromtxt
          2 my_data = genfromtxt('/Users/mymac/Documents/PyQt/image_viewer/csv_file_generator/eggs.csv',
          3     delimiter=',',
          4     dtype=None,
          5     encoding=None)

    ImportError: cannot import name 'genfromtxt'

I had the same issue when tryin to import opencv2: I got the following error message:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import--------------------------- 
------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8f6675581547> in <module>()
      5 from PySide2.QtCore import *
      6 from PySide2.QtGui import *
----> 7 import cv2
      8 import numpy
      9 import csv

ImportError: numpy.core.multiarray failed to import
```

I also enter the following line in the Terminal: 
```atom --clear-window-state```
but it didn't help either

I visited the following site which didn't help me (or I didn't understand how to implement exactly the steps to fix the problem)

[ImportError: No module named matplotlib.pyplot][1]

[Importing matplotlib.pyplot in atom editor][2]

[matplotlib Error: No module named matplotlib even though it is installed][3]

I also posted

  [1]: https://stackoverflow.com/questions/18176591/importerror-no-module-named-matplotlib-pyplot
  [2]: https://stackoverflow.com/questions/43306980/importing-matplotlib-pyplot-in-atom-editor
  [3]: https://askubuntu.com/questions/427708/matplotlib-error-no-module-named-matplotlib-even-though-it-is-installed

**Expected behavior:** I want to be able to import package in a python script

**Actual behavior:** I get a message of the form `ModuleNotFoundError: No module named 'matplotlib.backends'; 'matplotlib' is not a package`

**Reproduces how often:** it varies, but it come and goes without a clear time pattern. I also cannot tell why it comes at a certain point. It seems to happen with `matplotlib` and `numpy`

### Versions

`python 3.6.5`
`macOS 10.13.4`
`Atom 1.26.1 x64`
`Hydrogen 2.4.1`

### Additional Information

When the problem happens, Atom seems to want to connect to a previously used script in which numpy was used, to open numpy itself

Please let me know if something is not clear or if more informations are needed

I first posted this issue on the Github page of Atom  [https://github.com/atom/atom/issues/17375](url) but the maintainers told me that it was probably a problem regarding `Hydrogen` so this is why I'm writing you 

Many thanks in advance for your time!

**Comment by bjce** [comment]
The same happened when I tried to import "mayavi"

**Comment by BenRussert** [comment]
Sorry you haven't received a reply yet. 

Can you run `jupyter kernelspec list --json` from your terminal and check where your python kernels are pointing? Post the ouput here for help.

**Comment by bjce** [comment]
Thank you for your answer @BenRussert ! 

Here is the terminal output from `jupyter kernelspec list --json`:

```
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/Users/mymac/Library/Jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/anaconda3/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "julia-0.6": {
      "resource_dir": "/Users/mymac/Library/Jupyter/kernels/julia-0.6",
      "spec": {
        "argv": [
          "/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia",
          "-i",
          "--startup-file=yes",
          "--color=yes",
          "/Users/mymac/.julia/v0.6/IJulia/src/kernel.jl",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Julia 0.6.2",
        "language": "julia",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}

```

**Comment by bjce** [comment]
I have to add that now when running the line :
`import mayavi`

I get the following error message: 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-e39ff6bba53e> in <module>()
      1 import matplotlib.pyplot as plt
----> 2 import mayavi

ModuleNotFoundError: No module named 'mayavi'
```
but the line `import matplotlib.pyplot as plt` works fine

**Comment by bjce** [comment]
Well @BenRussert It seems that it is related to the problem that I have several versions of python: I had to install the `mayavi` packages into anaconda bin running the following commands: 

`$ cd /anaconda3/bin`
`$ ./pip install mayavi`

And then I could run the line

`import mayavi` with Hydrogen

I hope this solves the problem on long term basis. 
Sorry for the inconvenience and many thanks for your time

**Comment by BenRussert** [comment]
Try running `conda env list` and make sure you have the env you expect active. Right now it looks like you have the root environment active (based on the kernelspec). This means you will need the packages installed within that environment.

Additionally, you will need to make sure the environment you want is active in atom's environment. If you start atom from the command line (recommended), the env that is active in your terminal should be passed to atom and you will have access to packages installed in that env.

**Comment by BenRussert** [comment]
I didn't see your edit before the last comment. The suggestion still applies though.

Glad you got it working!

**Comment by bjce** [comment]
This is the output of `conda env list`

```
# conda environments:
#
                         /Users/mymac/.julia/v0.6/Conda/deps/usr
                         /Users/mymac/.platformio/penv
base                  *  /anaconda3
```

Inbetween as `mayavi` needs to run with `PySide` which is not supported for version ulterior to Python 3.5, I downgraded the conda packages from Python 3.6 to Python 3.5 with the line `conda install python=3.5.0` [https://github.com/enthought/mayavi/issues/552](url) . Now, I cannot even run a simple python script and I get the following error message upon running the script 

<img width="473" alt="screen shot 2018-06-16 at 18 43 31" src="https://user-images.githubusercontent.com/27978044/41500801-a9860e14-7198-11e8-9dbe-c078f5526c1f.png">

I then installed Python 3.6.5 back with `conda install python=3.6.5` but didn't solve the problem. I'm not sure that the problem is related to hydrogen anymore but probabley more related to the fact that it's a beginner problem having trouble with installation... :n(.

**Comment by bjce** [comment]
Well now I run 

`import numpy`

I get the error: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-d4cdadb62aa7> in <module>()
----> 1 import numpy

~/Downloads/numpy.py in <module>()
----> 1 from numpy import genfromtxt
      2 my_data = genfromtxt('/Users/mymac/Documents/PyQt/image_viewer/csv_file_generator/eggs.csv',
      3     delimiter=',',
      4     dtype=None,
      5     encoding=None)

ImportError: cannot import name 'genfromtxt'
```
