### ISSUE TITLE
how can i fix No kernel for grammar MagicPython found

### ISSUE THREAD

**Issue by lovezeropython** [nteract/hydrogen#1316]
No kernel for grammar MagicPython found

atom 1.27
Hydrogen 2.5

mac os 10.13.4 (17E202)

run cmd+enter raise No kernel for grammar MagicPython found

**Comment by n-riesco** [comment]
In Hydrogen's settings, see `Language Mappings`. For MagicPython, setting Language Mappings to `{"python": "magicpython"}` should do the trick.

**Comment by n-riesco** [comment]
@lovezeropython See the [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#debugging-guide). It's described in the first section.

**Comment by JonnyCBB** [comment]
I had the same issue and @n-riesco 's solution to set the Language Mappings to `{"python": "magicpython"}` worked for me

**Comment by kylebarron** [comment]
This should be fixed for the future in https://github.com/nteract/hydrogen/pull/1368 and will go out in the next release.
