### ISSUE TITLE
Error when using R and entering ctrl + enter

### ISSUE THREAD

**Issue by rwatts3** [nteract/hydrogen#1318]
**Description:**
I receive the following error when trying to use R in hydrogen. 
I have confirmed that the R bin is in the environment variables for PATH
```sh
'C:/PROGRA~1/R/R-33~1.3/bin/x64/R' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

[Description of the issue]
**Steps to Reproduce:**

1. Open R file and attempt to run code with `ctrl+enter`
2. Two error windows open 1 opens the console, the other is reported in the notifications UI.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
- Windows 7
- 1.28.0-beta.1 (Beta)

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

```sh
Uncaught Error: spawn C:/PROGRA~1/R/R-33~1.3/bin/x64/R ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
Which R kernel did you install? Does the R kernel work when you use it with other front-ends, e.g. jupyter notebook?

**Comment by kylebarron** [comment]
Closing as stale
