### ISSUE TITLE
no inspector for jupyter-scala?

### ISSUE THREAD

**Issue by frejonb** [nteract/hydrogen#1321]
When I hit toggle inspector in scala nothing happens. Is this intended? is there no documentation for this kernel?

scala 2.12.6
jupyter-scala 0.4.2
hydrogen 2.5.0
atom 1.27.1

**Comment by BenRussert** [comment]
I don't know anything about the Scala kernel, so I'll assume inspection normally works on it with other front ends like Jupyter notebook.

What code do you have selected when you ran the inspection command? Even if there were no results it should show you an info box telling you that. Are you sure the command ran?

**Comment by frejonb** [comment]
I'm not sure how to check if the command ran. There's no box telling anything. Even selecting simple functions like `println`, nothing happens.

**Comment by BenRussert** [comment]
> When I hit toggle inspector 

What do you mean by this? Keyboard shortcut, command palette or some other method?

**Comment by frejonb** [comment]
Neither ⌥ + i or the command palette works (only in scala, other kernels work just fine). I'm also not too familiar with the kernel as I was just using hydrogen to learn scalar but without easy access to docstrings it's proving quite challenging. Do you know how I could go ahead and check what is going on under the hood when I try to open the inspector to figure out wether it's a kernel problem?
Otherwise I think I'm better off learning in IntelliJ.

**Comment by BenRussert** [comment]
I'll look at this later today, I've been meaning to. Let me know if there is a specific Scala kernel, otherwise I'll just use first search hit.

**Comment by BenRussert** [comment]
@frejonb I'm having some trouble getting [jupyter-scala](https://github.com/jupyter-scala/jupyter-scala/) installed on ubuntu 18.04, it looks like there are some maintenance issues there.

Can you try turning on debug/logging in the hydrogen settings? Then, right after you try to inspect something look in the atom devtools console for a message like: "Inspector: Result:" followed by the object.

You may want to check it out on a kernel you know works first to see what it should look like.

**Comment by frejonb** [comment]
In scala I get 
```
utils.js? [sm]:162 Hydrogen: ZMQKernel.inspect: print('a') 5
```

while python gives 
```
Hydrogen: ZMQKernel.inspect: print('a') 5
utils.js? [sm]:162 Hydrogen: IO message: Message {idents: Array(1), header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js? [sm]:162 Hydrogen: Invalid reply: wrong channel
utils.js? [sm]:162 Hydrogen: IO message: Message {idents: Array(1), header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js? [sm]:162 Hydrogen: Invalid reply: wrong channel
utils.js? [sm]:162 Hydrogen: shell message: Message {idents: Array(0), header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js? [sm]:162 Hydrogen: Inspector: Result: Object {data: Object, found: true}
```

**Comment by wadethestealth** [comment]
The documentation for this kernel seems frantic and leads to almond, which I believe is the rebrand of this kernel. Maybe try using almond instead or also try IScala

**Comment by wadethestealth** [comment]
Seems like Code inspection was not added until Oct-2018 which is well after most of these comments. Because that solves the original issue, I am going to close this, but if people have problems with this still, they are welcome to open a new issue about it.
