### ISSUE TITLE
Python 3 and 2 confusion

### ISSUE THREAD

**Issue by adrianoesch** [nteract/hydrogen#1322]
First of all, I love hydrogen. Huge thanks!

Then, having both versions installed (using brew), I'm being asked which kernel I want to use, when executing code. But even when I select Python3 it uses an a Python 2 kernel (screenshot). 

![image](https://user-images.githubusercontent.com/4437435/40721432-6a530c86-6411-11e8-99c9-0a13d8ade7cd.png)

After some digging I found a kernel.json file which used python instead of python3 as startup command, so I changed it to the following and restarted the computer:
```
{
 "argv": [
  "python3",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
``` 

Unfortunately it didn't make any difference. Any recommendations would be highly appreciated!

**Versions:**
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
macOS: 10.13.4
Hydrogen: 2.5.0

**Comment by BenRussert** [comment]
Can you run `jupyter kernelspec list --json` in terminal and check the output for the python3 kernel? If the first `argv` listed is not `python3` then you may have edited the wrong `kernel.json` file.

If that doesnt help post your output here and i'll try to help. Let me know how it goes!

**Comment by adrianoesch** [comment]
That was it, thanks a lot @BenRussert!

**Comment by lgeiger** [comment]
Awesome, glad it works :+1:

**Comment by datasurfergtx** [comment]
How do I open this JSON file? I have the same problem
