### ISSUE TITLE
为什么我的一直安装报错

### ISSUE THREAD

**Issue by Franklyn1987** [nteract/hydrogen#1323]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
Are you having issues installing hydrogen? If you can give some more detail I may be able to help.
