### ISSUE TITLE
Cannot install hydrogen

### ISSUE THREAD

**Issue by MrKuggie** [nteract/hydrogen#1324]
**Description:**
I'm having difficulties installing Hydrogen through atom or through command lines. Any help would be greatly appreciated.

[Description of the issue]
Every time I try to install Hydrogen I get the same error log. I've tried reopening atom, and two different installation methods. I'm using Windows 10- 64bit.
**Steps to Reproduce:**

1. Find Hydrogen through Atom install settings
2. Attempt install -> See log

1a. Try 'apm install hydrogen' through command.
2a. Same error log as below.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
I'm using Windows 10-64 bit. Trying to install Hydrogen 2.5.0 on the update Atom for 1.27.2 x64bit
You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\acb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\acb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\acb\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\acb\\.atom\\.apmrc" "install" "C:\\Users\\acb\\AppData\\Local\\Temp\\d-11851-9352-1updmjr.o0ups3jtt9\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\acbou\.atom\.apm\uuid\3.2.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\acbou\.atom\.apm\uuid\3.2.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by BenRussert** [comment]
Is `C:\Users\acbou.atom.apm\uuid\3.2.1\package\package.json` a valid path? Looks like there is a missing backslash after `C:\Users\acb\...`. not sure what would cause that.

Are other packages installing correctly?

**Comment by MrKuggie** [comment]
I've been unable to reply but started playing with it tonight. I found this link which fixed my issue;

https://github.com/atom/apm/issues/593

I followed it by deleting .apm
Followed by simply reinstalling hydrogen using apm install hydrogen

Hope this helps anyone having my issues.
