### ISSUE TITLE
inline rendering of triple-quoted multi-line strings

### ISSUE THREAD

**Issue by jonschull** [nteract/hydrogen#1330]
**Description:**

ctrl-enter renders """ a single-line triple-quote string like this"""
but fails with a   
 """ a multi-line triple-quote string
                                     like this
                               """

**Steps to Reproduce:**

see illustration
![](https://www.evernote.com/l/AAE-SFSpjutK75wH8DNGoZ3ka9OS2Uh01dwB/image.png)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Mac 10.13.4
Atom 1.27.2
Hydrogen 2.50 

**Logs:**
Console is empty, as illustrated

**Comment by BenRussert** [comment]
Try selecting the entire code you want to run, or [use cells]( https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell) and run the cell. See #541 for more info.
