### ISSUE TITLE
How to add a permanent path for Hydrogen to look for packages

### ISSUE THREAD

**Issue by bjce** [nteract/hydrogen#1337]
I posted an issue earlier, thought that the problem was resolved but still run into trouble (Sorry!)

### Description

In order to import `Numpy` I have to manually add several path where packages are located each time I run a script in Atom. How could I set the list of path where Hydrogen is looking as permanent

### Steps to Reproduce

If I run
`import numpy` 

I get the error message: 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d4cdadb62aa7> in <module>()
----> 1 import numpy

~/Downloads/numpy.py in <module>()
----> 1 from numpy import genfromtxt
      2 my_data = genfromtxt('/Users/mymac/Documents/PyQt/image_viewer/csv_file_generator/eggs.csv',
      3     delimiter=',',
      4     dtype=None,
      5     encoding=None)

ImportError: cannot import name 'genfromtxt'
```

If I add manually the path at the beginning of the script, it works:

```
import sys
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages')
```

How can those path be set in a permanent manner so that I don't have to write manually those lines at the beginning of each script?

Many thanks in advance

**Comment by BenRussert** [comment]
How did you install python? It could be that the install did not add the new python location to your path.

If you Google "add to path" with your OS, you will get all sorts of info on how to do this in your environment.

**Comment by bjce** [comment]
Thanks for your feedback @BenRussert 

> How did you install python? It could be that the install did not add the new python location to your path.

I ran the the `python-3.6.5-macosx10.6.pkg` downloaded from [https://www.python.org/downloads/](url)

However I'm still running into trouble : I'm trying to run a script from Atom/Hydrogen and get an error `ModuleNotFoundError: No module named 'PySide'`. When running the exact same script in Spyder, it works fine.

When looking at the `sys.path` in Atom/Hydrogen and Spyder, they turn out to be exactly the same

- from Atom/Hydrogen:

```
import sys
sys.path

['',
 '/anaconda3/lib/python36.zip',
 '/anaconda3/lib/python3.6',
 '/anaconda3/lib/python3.6/lib-dynload',
 '/anaconda3/lib/python3.6/site-packages',
 '/anaconda3/lib/python3.6/site-packages/aeosa',
 '/anaconda3/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 '/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/Users/mymac/.ipython']
```

- In Sypder: 

```
import sys

sys.path
Out[5]: 
['',
 '/anaconda3/lib/python36.zip',
 '/anaconda3/lib/python3.6',
 '/anaconda3/lib/python3.6/lib-dynload',
 '/anaconda3/lib/python3.6/site-packages',
 '/anaconda3/lib/python3.6/site-packages/aeosa',
 '/anaconda3/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 '/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/Users/mymac/.ipython']
```

**Comment by kylebarron** [comment]
@bjce

Are you opening Atom by clicking it's icon or with `atom .` from the command line? When you start Atom from the command line, it inherits all the current environment variables from the Shell, so that might help. 

Additionally, you say you installed Python from Python.org, but your paths say that you're using anaconda Python.

**Comment by kylebarron** [comment]
Closing as stale

**Comment by bjce** [comment]
Thank you very much for your answer @kylebarron. Sorry that I didn't reply to your comment before. I think that in the meantime I `cd` the file indicated when writing the command `jupyter kernelspec list` and changed the path from there. Thank you very much for your attention again
