### ISSUE TITLE
Attempting to Catch Kernel Response for Further JavaScript Processing

### ISSUE THREAD

**Issue by jefftrevino** [nteract/hydrogen#1338]
Following up here on benrussert's Slack invitation to open an issue here:

I'm making a Hydrogen plugin that needs to (1) run Python to write a file to a temporary directory, (2) return the path to that file, and then (3) pass the file path to some existing JavaScript code (an Atom plugin that will render the file as a .pdf for display in Atom).

While the plugin example showed me clearly how to consume Hydrogen via the Services API, and existing plugins (especially hydrogen-python) showed clearly how I can alter Python code before execution, I'd like to see a minimal example of how I might catch the kernel's response -- the path returned by a Python function, in my case -- in a variable and do something further with it in my Hydrogen plugin code.

**Comment by nikitakit** [comment]
You may want to look at the "Variable Explorer" feature of hydrogen-python, which displays values of current Python variables every time code is run.

Code links:
* https://github.com/nikitakit/hydrogen-python/blob/master/lib/main.js#L169
* https://github.com/nikitakit/hydrogen-python/blob/master/lib/main.js#L128
* https://github.com/nikitakit/hydrogen-python/blob/master/py/install_kernel_plugin.py#L30

**Comment by jefftrevino** [comment]
Thank you for this recommendation. This is a  useful example, but quite a bit more complex than what I'm trying to do. I really just need to run Python code in a locally running  kernel and have that code return a string (a path) back to my JavaScript code in my hydrogen plugin, so that my hydrogen plugin can use the path to open a .pdf file in a new Atom pane. Perhaps there is a more minimal example I can refer to?

**Comment by BenRussert** [comment]
I made a minimal kernel middleware plugin based on a discussion with @jefftrevino on slack. Check out [this branch](https://github.com/BenRussert/hydrogen-example-plugin/tree/middleware-example) for the package and [this commit](https://github.com/BenRussert/hydrogen-example-plugin/commit/9f046cae59e3086594f1f34e52ffe5cff4e03b97) for the middleware specific part.

You might want to check out [the type definitions](https://github.com/nteract/hydrogen/blob/master/lib/plugin-api/hydrogen-types.js) here for additional comments on kernel middleware.
