### ISSUE TITLE
Hyrogen Run not working correctly with if/else statements in python

### ISSUE THREAD

**Issue by mlangiu** [nteract/hydrogen#1341]
Pictures say more than words... 

**When attempting to run** the following scenarios (i.e. execute the selected lines by hitting <kbd>shift</kbd> + <kbd>enter</kbd>) we'l run into some issues:

![grafik](https://user-images.githubusercontent.com/15340151/41656249-a8a0a7bc-748f-11e8-9323-368da0c97553.png) only runs the `if` part: ![grafik](https://user-images.githubusercontent.com/15340151/41656285-bf5368c8-748f-11e8-9618-941c0ee5fdb4.png)
This is unfortunate but could be considered a beauty problem, as
![grafik](https://user-images.githubusercontent.com/15340151/41656354-ed06f19a-748f-11e8-8414-72c8c49696e8.png) circumvents this issue: ![grafik](https://user-images.githubusercontent.com/15340151/41656379-0572171e-7490-11e8-88e4-e4b87e210abb.png)

However, within indented sections (where usually this is possible: 
![grafik](https://user-images.githubusercontent.com/15340151/41656455-53f153d2-7490-11e8-964b-be69a3a28594.png) -> ![grafik](https://user-images.githubusercontent.com/15340151/41656496-7270fccc-7490-11e8-865c-58574c9db73a.png))
This: ![grafik](https://user-images.githubusercontent.com/15340151/41656630-f66ce270-7490-11e8-911f-4ef740533b30.png) will now also fail: ![grafik](https://user-images.githubusercontent.com/15340151/41657039-4425e9e8-7492-11e8-99f8-abfde18dcae2.png)

      File "<tokenize>", line 3
        else:
        ^
    IndentationError: unindent does not match any outer indentation level

**Versions:**

OS: Win 10 Enterprise
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by mbroedl** [comment]
You may want to try this package, which takes care of the whitespace problem.
https://atom.io/packages/hydrogen-python

And then you may want to file the if/else behaviour as a feature request to that package, because it's a language specific issue?
#862 #1285

**Comment by kylebarron** [comment]
This specific issue should have been fixed from https://github.com/nteract/hydrogen/pull/1363 when selecting indented if/else blocks. For automatic if/else completion, see hydrogen-python.
