### ISSUE TITLE
How to call Hydrogen from outside of Atom?

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/hydrogen#1342]
I'm looking for advice. Is there a way implement calling Hydrogen from outside of Atom? I develop [pandoctools](https://github.com/kiwi0fruit/pandoctools) - profile manager of text processing pipelines: Pandoc filters, any text CLI filters.

Pipelines are defined in the bash script. And at the moment there is a Pandoc filter that collects Jupyter code blocks outputs and inserts them into the output document - a CLI app. For this it starts Jupyter every time it's called (this filter is a fork of Stitch actually).

I think it would be better to use Hydrogen for this (and more consistent as I use Hydrogen for writing such a document). But this needs creating some kind of API to access Hydrogen from other applications. Do you have any advice? The only thing I can now think about is to create an Atom package that starts web server and communicate with Hydrogen via Atom commands API. And the outer apps communicate with that web server.

Maybe there is a better way? Not a web server but another API?

**Comment by kiwi0fruit** [comment]
At the moment the idea is try to comminicate python app with new Atom package via json-rpc. But I still need a way to call `atom.commands.dispatch` from new package in order to ask Hydrogen to evaluate code chunk and to give me the output. I guess there is no such command in Hydrogen yet - as it wasn't needed.

**Comment by n-riesco** [comment]
It sounds like what you're after is [nbconvert](https://nbconvert.readthedocs.io/en/latest/).

**Comment by n-riesco** [comment]
Oh, I read your post too quickly. If you want to access Hydrogen API see https://github.com/nteract/hydrogen#plugins-for-hydrogen

@nikitakit In the README, the link https://nteract.gitbooks.io/hydrogen/docs/PluginAPI.md is broken.

**Comment by kiwi0fruit** [comment]
Thanks! Looks promising. Closing until I'll test and get new questions.

**Comment by n-riesco** [comment]
The PR that introduced the latest API is #1179 and the little documentation we have is in https://github.com/nteract/hydrogen/blob/master/docs/PluginAPI.md

**Comment by kiwi0fruit** [comment]
@nikitakit Hello. It would be a timesaver for me if you could tell if there is a functinality in the plugin API that can be used to send code from another Atom package (text is not even present in the editor), then wait for Hydrogen to execute it and send (JSON?) output back to that Atom package.
