### ISSUE TITLE
Startup code doesn't get re-run when restarting Jupyter kernel

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/hydrogen#1343]
Startup code doesn't get re-run when restarting Jupyter kernel.

(Hydrogen version 2.5.0. Windows 7)

**Comment by kiwi0fruit** [comment]
Hydrogen 2.6.0 Windows 7. Startup code still doesn't get re-run after kernel restart.

@BenRussert @lgeiger

**Comment by kylebarron** [comment]
It works for me when restarting the Python kernel.

When I set my `Startup Code` setting to:
```json
{"Python 3": "a = 1\n%matplotlib inline\n%config InlineBackend.figure_format='svg'"}
```
and I run `a`, I see 1.

![peek 2018-11-21 10-42](https://user-images.githubusercontent.com/15164633/48851883-222d7e80-ed7a-11e8-8a92-2992e4331b1e.gif)

**Comment by kiwi0fruit** [comment]
But it doesn't work for me. When I "Shutdown Kernel" then start it again - startup code runs. But when I "Restart Kernel" - it doesn't run. I've just tested on (Hydrogen version 2.6.0. Windows 7 x64).

**Comment by kiwi0fruit** [comment]
May be relevant: I have a custom named kernel: "research".

**Comment by BenRussert** [comment]
> I've just tested on (Hydrogen version 2.6.0. Windows 7 x64).


I was just putting together some release notes and realized we haven't shipped this fix yet. I will ship 2.7 tonight! Sorry for the confusion!
