### ISSUE TITLE
Hydrogen run not working properly for multiline definitions in python

### ISSUE THREAD

**Issue by mlangiu** [nteract/hydrogen#1344]
**Description:**
When defining a function that has a long name or many arguments, such that you may want to split it into multiple lines for better readability, Hydrogen Run appears to work incorrectly.
This may be related to #1341 

**Steps to Reproduce:**

When writing a long function such as below, the Hydrogen Run command fails:
![grafik](https://user-images.githubusercontent.com/15340151/41710478-052abcdc-7546-11e8-8db3-c6470df26047.png)
With the error:

    IndentationError: expected an indented block
      File "<ipython-input-38-872b2e2fcfdd>", line 3
        """Do amazing things."""

We need to add several indents to make this work:
![grafik](https://user-images.githubusercontent.com/15340151/41710381-d04027b4-7545-11e8-8f6e-76f1472eb83c.png)

**Versions:**

OS: Win 10 Enterprise
Atom : 1.27.2
Electron: 1.7.15
Chrome : 58.0.3029.110
Node : 7.9.0

**Comment by BenRussert** [comment]
Hi, does the first format work if you run it as a script? `python my-filename.py` from the cli.

**Comment by kylebarron** [comment]
@mlangiu This works fine for me in Hydrogen. Just make sure your cursor is on the line with `def`.

![image](https://user-images.githubusercontent.com/15164633/43240020-a120ee7c-9062-11e8-9d63-8d6288909913.png)

**Comment by kylebarron** [comment]
Oh wait, @mlangiu , you must be using the hydrogen-python extension?

This is an open issue I raised back in March and has nothing to do with Hydrogen proper. https://github.com/nikitakit/hydrogen-python/issues/3

**Comment by mlangiu** [comment]
Indeed I am!

**Comment by kylebarron** [comment]
There are some bugs with that extension. I recommend you turn it off/disable it until some bugs have been fixed.

**Comment by mlangiu** [comment]
I did, thanks for the info

**Comment by kylebarron** [comment]
Hydrogen-python has been updated and should handle this situation correctly. Open an issue there if you still have issues.

**Comment by garciadias** [comment]
> Hydrogen-python has been updated and should handle this situation correctly. Open an issue there if you still have issues.

I am not using the extension and it is not working in 2.16.3 version. Is it possible that something broke it in the latest updates?
Thank you.

**Comment by ddcgchow94** [comment]
I got the same error. using hydrogen 2.16.3 without the extension
