### ISSUE TITLE
Just sit on the "install" graphic button

### ISSUE THREAD

**Issue by Jvalal** [nteract/hydrogen#1345]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
Hi, we would need more information to help out. Can you elaborate?

If you are having trouble installing with the GUI, can you try `apm install hydrogen` from the command line?
