### ISSUE TITLE
Own modules import mistake

### ISSUE THREAD

**Issue by newturok** [nteract/hydrogen#1347]
Hi. I have some troubles with own modules import with hydrogen

So if I import **db.py** that imports **cd.py**, both in **libs** folder to main script it fails if i use
`import cd`
![fail](https://user-images.githubusercontent.com/5757827/41818985-d4679498-77c1-11e8-8af7-d04320bda780.png)

It returns success only if I import as on the second image, with
`import libs.cd as cd`
![succes](https://user-images.githubusercontent.com/5757827/41819034-8a906182-77c2-11e8-84b5-3c18139533ee.png)

Is there any way to make it work with 
`import cd`
as on the first image?

**Comment by kylebarron** [comment]
This is a Python issue, not Hydrogen.

https://stackoverflow.com/questions/43728431/modulenotfounderror-no-module-named-x

If you add an empty file named `__init__.py` to your `libs/` folder, and change `import cd` to `from . import cd`, it'll work.

With `print('hello world')` as the text inside `cd.py`:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/15164633/43464264-a4d36438-94a8-11e8-8899-f6192ec90e64.png">

**Comment by kylebarron** [comment]
Closing for now, as it's likely not a Hydrogen issue. Let us know/reopen the issue if you still have trouble.
