### ISSUE TITLE
can't install hydrogen. It just hangs there and does nothing. Used "apm install hydrogen" from command line

### ISSUE THREAD

**Issue by ekaydee** [nteract/hydrogen#1349]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
Hi, thanks for the issue. Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version` from the command line.

**Comment by BenRussert** [comment]
Closing for now as we need more info to debug. If you are still facing the issue please reply with the details requested and we can reopen the issue.

**Comment by mrciolino** [comment]
Hanging apm install hyodgen --verbose

(DS) C:\Users\name.last\.atom\packages>apm install hydrogen --verbose
Installing hydrogen to C:\Users\name.last\.atom\packages REQUEST { url: 'https://atom.io/api/packages/hydrogen',
  json: true,
  retries: 4,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/6.2.0 node/v8.9.3 win32 x64' },
  callback: [Function],
  method: 'GET' }
REQUEST make request https://atom.io/api/packages/hydrogen
REQUEST onRequestResponse https://atom.io/api/packages/hydrogen 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 26 Jul 2019 14:03:04 GMT',
  status: '200 OK',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=631139040',
  'x-frame-options': 'DENY',
  'content-security-policy': 'default-src \'self\'; font-src https://github-atom-io-herokuapp-com.freetls.fastly.net https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-src \'self\' https://www.youtube.com; img-src https: \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net data:; media-src \'self\'; object-src \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.freetls.fastly.net; style-src \'self\' \'unsafe-inline\' https://github-atom-io-herokuapp-com.freetls.fastly.net;',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'x-download-options': 'noopen',
  'x-permitted-cross-domain-policies': 'none',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"d7f8b3dee1cd376f79f76ec48a919b73"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': 'b7862c07-1b8f-4a50-8069-1d319d27275c',
  'x-runtime': '0.008668',
  'x-rack-cache': 'miss',
  vary: 'Accept-Encoding, Origin',
  via: '1.1 vegur' }
REQUEST reading response's body
REQUEST finish init function https://atom.io/api/packages/hydrogen
REQUEST response end https://atom.io/api/packages/hydrogen 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 26 Jul 2019 14:03:04 GMT',
  status: '200 OK',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=631139040',
  'x-frame-options': 'DENY',
  'content-security-policy': 'default-src \'self\'; font-src https://github-atom-io-herokuapp-com.freetls.fastly.net https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-src \'self\' https://www.youtube.com; img-src https: \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net data:; media-src \'self\'; object-src \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.freetls.fastly.net; style-src \'self\' \'unsafe-inline\' https://github-atom-io-herokuapp-com.freetls.fastly.net;',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'x-download-options': 'noopen',
  'x-permitted-cross-domain-policies': 'none',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"d7f8b3dee1cd376f79f76ec48a919b73"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': 'b7862c07-1b8f-4a50-8069-1d319d27275c',
  'x-runtime': '0.008668',
  'x-rack-cache': 'miss',
  vary: 'Accept-Encoding, Origin',
  via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/hydrogen
REQUEST has body https://atom.io/api/packages/hydrogen 77167
REQUEST emitting complete https://atom.io/api/packages/hydrogen
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\name.last \\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\name.last\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--runtime=electron',
gyp verb cli   '--target=3.1.10',
gyp verb cli   '--dist-url=https://atom.io/download/electron',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command install []
gyp verb download using dist-url https://atom.io/download/electron
gyp verb install input version string "3.1.10"
gyp verb install installing version: iojs-3.1.10
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 0
gyp verb needs "installVersion" 9
gyp verb install version is no good; reinstalling
gyp verb ensuring nodedir is created C:\Users\name.last\.atom\.node-gyp\.node-gyp\iojs-3.1.10
gyp http GET https://atom.io/download/electron/v3.1.10/iojs-v3.1.10-headers.tar.gz
REQUEST { uri: 'https://atom.io/download/electron/v3.1.10/iojs-v3.1.10-headers.tar.gz',
  headers: { 'User-Agent': 'node-gyp v3.7.0 (node v8.9.3)' },
  callback: undefined }
REQUEST make request https://atom.io/download/electron/v3.1.10/iojs-v3.1.10-headers.tar.gz
REQUEST onRequestResponse https://atom.io/download/electron/v3.1.10/iojs-v3.1.10-headers.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 26 Jul 2019 14:03:05 GMT',
  status: '302 Found',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=631139040',
  'x-frame-options': 'DENY',
  'content-security-policy': 'default-src \'self\'; font-src https://github-atom-io-herokuapp-com.freetls.fastly.net https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-src \'self\' https://www.youtube.com; img-src https: \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net data:; media-src \'self\'; object-src \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.freetls.fastly.net; style-src \'self\' \'unsafe-inline\' https://github-atom-io-herokuapp-com.freetls.fastly.net;',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'x-download-options': 'noopen',
  'x-permitted-cross-domain-policies': 'none',
  location: 'https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': 'c85fbee5-49b1-416d-8ea4-7d2a0550f69a',
  'x-runtime': '0.004762',
  'x-rack-cache': 'miss',
  vary: 'Accept-Encoding',
  via: '1.1 vegur' }
REQUEST redirect https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz
REQUEST redirect to https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz
REQUEST {}
REQUEST make request https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz
REQUEST response end https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 26 Jul 2019 14:03:05 GMT',
  status: '302 Found',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=631139040',
  'x-frame-options': 'DENY',
  'content-security-policy': 'default-src \'self\'; font-src https://github-atom-io-herokuapp-com.freetls.fastly.net https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-src \'self\' https://www.youtube.com; img-src https: \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net data:; media-src \'self\'; object-src \'self\' https://github-atom-io-herokuapp-com.freetls.fastly.net; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.freetls.fastly.net; style-src \'self\' \'unsafe-inline\' https://github-atom-io-herokuapp-com.freetls.fastly.net;',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'x-download-options': 'noopen',
  'x-permitted-cross-domain-policies': 'none',
  location: 'https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v3.1.10/iojs-v3.1.10-headers.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': 'c85fbee5-49b1-416d-8ea4-7d2a0550f69a',
  'x-runtime': '0.004762',
  'x-rack-cache': 'miss',
  vary: 'Accept-Encoding',
  via: '1.1 vegur' }

**Comment by mrciolino** [comment]
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

Community Packages (28) C:\Users\name.last\.atom\packages
├── atom-beautify@0.33.4
├── atom-clock@0.1.17
├── atom-ide-ui@0.13.0
├── autocomplete-python@1.14.1
├── black-v-syntax@0.2.1
├── city-lights-syntax@1.1.8
├── city-lights-ui@1.5.3
├── color-picker@2.3.0
├── context-menu-manager@0.2.0
├── duotone-dark-earth-syntax@2.1.0
├── file-icons@2.1.33
├── flex-tool-bar@2.1.3
├── highlight-selected@0.16.0
├── jupyter-notebook@0.0.10 (disabled)
├── minimap@4.29.9
├── minimap-highlight-selected@4.6.1
├── monokai-seti@0.9.0
├── native-ui@0.27.0
├── pigments@0.40.2
├── polymorph-ui@1.8.8
├── python-tools@0.6.9
├── script@3.18.1
├── scroll-editor-on-middle-click@0.7.0
├── seti-ui@1.11.0
├── split-diff@1.6.0
├── teletype@0.13.4
├── theme-switch@0.6.0
└── tool-bar@1.1.11

**Comment by wadethestealth** [comment]
@BenRussert Maybe you know how to diagnose this?

**Comment by wadethestealth** [comment]
I am not seeing any errors here, if we can get a better error report, maybe this could be diagnosed.
Suggestions for potential solutions:
- Check your internet connection (are you using proxy, we have had issues before)
- Check if you can install and build other projects
- Check your apm version (is it up to date)

Closing until more info is recovered.
