### ISSUE TITLE
ENH: Don't clear bubbles when reconnecting to dead remote kernel

### ISSUE THREAD

**Issue by kylebarron** [nteract/hydrogen#1354]
This is somewhat similar to #1332, which discusses clearing bubbles when restarting a local kernel. 
@nikitakit [detailed how this behavior is helpful](https://github.com/nteract/hydrogen/issues/1332#issuecomment-397843919):
> Personally, the fact that bubbles aren't cleared has been a huge improvement for me. About a year ago hydrogen would always delete all bubbles when a kernel was restarted, which caused me to lose important experimental results more times than I can count. This behavior was changed in part to support #861 (the "Restart and Re Evaluate Bubbles" command).

I'd like to propose that this same behavior is implemented for remote kernels. I work with remote kernels that become disconnected when my VPN times out. By using tmux on the server, I can connect to the same jupyter kernel after logging into the VPN again, but when I connect through Hydrogen again, Hydrogen clears all results.

I'm assuming that Hydrogen stores some information about the currently connected kernel, and that it would be possible for Hydrogen to know when the reconnected kernel is the same as the disconnected/dead one.

The decision to clear results might be different when starting a new remote kernel.

**Comment by BenRussert** [comment]
I don't know all of the details off hand as I dont use remote kernels much. Feel free to look into or send a PR if you think it's worth while

**Comment by wadethestealth** [comment]
That command has been removed and is no longer being maintained

**Comment by aviatesk** [comment]
@wadethestealth This issue doesn't only talking about the `Hydrogen: Restart and Re Evaluate Bubbles` command but rather "not clearing bubbles when a connection to a remote kernel is destroyed".

When the remote kernel is _really_ destroyed, it would better to clear all results as when a local kernel is shutdown, but if it's actually alive and we can reconnect to it, the results are better not to be cleared like when a local kernel is restarted.

**Comment by wadethestealth** [comment]
Shouldn't we just remove line 624 in lib/main then.

**Comment by aviatesk** [comment]
Maybe ? But I'm not too sure about remote kernels thus I want to stay this open until @kylebarron returns us updates.

**Comment by wadethestealth** [comment]
Closed in favor of #635
