### ISSUE TITLE
Uncaught+TypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function

### ISSUE THREAD

**Issue by masoodimran** [nteract/hydrogen#1355]
**Description:**
Uncaught+TypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function
[Description of the issue]
Uncaught+TypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function
**Steps to Reproduce:**

1. Run any python command
**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
OS: Windows 7
Atom: 1.28.2
Hydrogen: 2.5.1
You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

title=Uncaught+TypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function&body=%5BEnter+steps+to+reproduce:%5D%0A%0A1.+...%0A2.+...%0A%0A**Atom**:+1.28.2+x64%0A**Electron**:+2.0.5%0A**OS**:+Microsoft+Windows+7+Professional+%0A**Thrown+From**:+%5Bgreyatom-hydrogen%5D(https://github.com/greyatom-edu-tech/greyatom-hydrogen)+package+1.9.0%0A%0A%0A%23%23%23+Stack+Trace%0A%0AUncaught+TypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function%0A%0A%60%60%60%0AAt+C:%5CUsers%5CMasood%5C.atom%5Cpackages%5Cgreyatom-hydrogen%5Clib%5Ccode-manager.js:37%0A%0ATypeError:+this.editor.languageMode.rowRangeForCodeFoldAtBufferRow+is+not+a+function%0A++++at+CodeManager.findCodeBlock+(/packages/greyatom-hydrogen/lib/code-manager.js:37:48)%0A++++at+Object.run+(/packages/greyatom-hydrogen/lib/main.js:358:40)%0A++++at+HTMLElement.hydrogenRun+(/packages/greyatom-hydrogen/lib/main.js:55:34)%0A++++at+CommandRegistry.handleCommandEvent+(~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:384:49)%0A++++at+KeymapManager.module.exports.KeymapManager.dispatchCommandEvent+(~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)%0A++++at+KeymapManager.module.exports.KeymapManager.handleKeyboardEvent+(~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)%0A++++at+WindowEventHandler.handleDocumentKeyEvent+(~/AppData/Local/atom/app-1.28.2/resources/app/src/window-event-handler.js:110:40)%0A%60%60%60%0A%0A%23%23%23+Commands%0A%0A%60%60%60%0A+++++-2:30.1.0+tabs:close-all-tabs+(atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)%0A+++++-2:13+tree-view:remove-project-folder+(span.name.icon.icon-file-directory)%0A+++++-2:09.0+application:add-project-folder+(atom-pane.pane.active)%0A++2x+-1:25.7.0+hydrogen:run+(input.hidden-input)%0A%60%60%60%0A%0A%23%23%23+Non-Core+Packages%0A%0A%60%60%60%0Agreyatom-hydrogen+1.9.0+%0AHydrogen+2.5.1+%0Ahydrogen-auth+0.0.2+%0Ahydrogen-launcher+1.2.2+%0Ahydrogen-python+0.0.6+%0Ahydrogen-xdbg+0.0.4+%0A%60%60%60%0A%0A

**Comment by BenRussert** [comment]
Looks like this is thrown from a [fork of hydrogen](https://github.com/greyatom-edu-tech/greyatom-hydrogen) which is unmaintained and might not be compatible with your version of atom. You can install hydrogen by running: `apm uninstall greyatom-hydrogen`  and `apm install hydrogen` from your command line.

**Comment by masoodimran** [comment]
Thanks Ben! I will try your suggestion on a fresh install of Atom and let you know if it worked. Thanks again for taken time to analyze this issue and respond.

**Comment by masoodimran** [comment]
Hello Ben, just wanted to update you that after doing a fresh install and only installing the hydrogen package has fixed the issue. As per your suggestion, it worked. Thanks a lot!

**Comment by contang0** [comment]
I am having this issue with a freshly installed version of Pulsar. I can execute rows if I highlight them, but if I execute the "Run and Move Down" command while the cursor is at the end of the line.

**Comment by TollefsonJ** [comment]
I'm having the same issue with a fresh Pulsar install - running highlighted rows works fine, but executing row-by-row throws the same error.
