### ISSUE TITLE
Display HTML Images

### ISSUE THREAD

**Issue by tobiasbj** [nteract/hydrogen#1364]
**Description:**

I'm unable to view images embeded as html in Hydrogen (using the IPython display methods).
I'm however able to view them in Jupyter-Notebook. 
Is this a bug on my side or is it as intended?

**Steps to Reproduce:**

```
from IPython.display import Image, HTML

img = './test_image.png'

def path_to_image_html(path):
    return '<img src="'+ path + '"/>'

img_html = path_to_image_html(img)
display(HTML(img_html))

```

The funny thing is that this works:
```
from IPython.display import HTML
HTML("<iframe src='https://nteract.io/' width='900' height='490'></iframe>")

```
**Versions:**

Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
To get it to work for now you can try using the absolute path. For example `/home/ben/test_image.png` instead of relative path `./test_image.png`

**Comment by BenRussert** [comment]
Thanks for opening the issue @tobiasbj. We have the same behavior on the nteract desktop app. It has something to do with the path of the html document inside atom/electron itself.

**Comment by wadethestealth** [comment]
This is not an issue. You are using the function correctly, but you are expecting it to parse your relative path into an absolute path. This is not a feature of the HTML module. To get the full path from a relative path use [IPython.utils.path.filefind](https://ipython.readthedocs.io/en/stable/api/generated/IPython.utils.path.html#IPython.utils.path.filefind) Then use the full path to parse to the HTML.

@BenRussert so he knows this isn't a bug
