### ISSUE TITLE
Emulating Spyder's IDE in Atom using Hydrogen

### ISSUE THREAD

**Issue by adragott** [nteract/hydrogen#1369]
I'm currently trying to use hydrogen to emulate the Spyder layout, which consists of 4 main parts: File explorer, variable explorer, console. Atom's already got the file explorer (project tree) and the console (any random terminal should do). I need hydrogen to do the following:

- Open whenever I open a .py file

- launch a terminal that is docked inside of atom and connect to the jupyter (or ipython?) kernel

- I have no idea how this part actually works, but I need a variable explorer at the minimum. It would be great if I could also implement a way to check out large tables of data and just view them in excel (which I can do but I mean I just click the variable and boom: table viewer)

- matplotlib needs to be able to plot inside of the jupyter kernel (it will use qtconsole)

I know how to do 3/4 of these things using hydrogen piece by piece, but I'd really like to make some kinda script that atom runs to start hydrogen on a .py open and then some script that hydrogen runs on its startup to create a terminal docked inside atom. So my question is really just:

How do I run startup scripts in Atom and in Hydrogen in order to accomplish this?

**Comment by BenRussert** [comment]
Hi, have you checked out [hydrogen-python](https://github.com/nikitakit/hydrogen-python/blob/master/README.md) and ?

 If you haven't already, make sure to check out the global kernel mode in the hydrogen settings. With this active, you only need to start one python kernel and then can run code from all py files in the shared kernel namespace.

 One challenge regarding variable explorers is that they essentially need to be written custom to a language and hydrogen is intended to be language agnostic, you're probably best off looking into creating a hydrogen plugin like the one above.

Sounds like you have some good ideas that many would appreciate. Feel free to ask questions and I'd love to see what you come up with!

**Comment by kylebarron** [comment]
You should also check out https://github.com/lgeiger/hydrogen-launcher

**Comment by adragott** [comment]
Thanks for the responses. Sorry it took me a bit to get back to this post. After more research, I've given up. I was willing to due anything it took up until it required me to write my own Atom packages. I don't have the knowledge to do this, and I don't have the time to learn how. I'll just have to go back to spyder until either I can find the time to make python ide for data analysis package for atom or until someone else makes one, which is unfortunate because atom is great.

**Comment by tkorach** [comment]
@adragott I also made the move from Spyder to Atom + Hydrogen. The main benefit is the ability to connect to existing **Jupyter** kernels, while Spyder can connect only to **IPython** kernels. Managing Jupyter kernels is much easier -start up a single Jupyter server and create notebooks as needed, in any environment. IPython kernels, on the other hand, require a separate shell (with screen, if using SSH) and synchronizing the kernelspec file. 

Hydrogen's variable explorer is not as good as Spyder's but even that in Spyder is not the functional for remote kernels. 

Overall the move was worth it for me.

**Comment by SergeiDBykov** [comment]
@embeddedpenguin 
If it is still relevant, thee atom plugin platformIO (https://atom.io/packages/platformio-ide-terminal) does approximately the thing you want.  After Hydrogen have run a script, you can connect a platformio terminal to the code via hydrogen launcher.
