### ISSUE TITLE
Client encryption for remote kernel responses?

### ISSUE THREAD

**Issue by kylebarron** [nteract/hydrogen#1372]
I'm curious to learn more about the remote kernel feature of Hydrogen/Jupyter, and specifically where/how interim results are stored. I know the transmission of results from server to client is secure with SSH, but are results stored in plain text on the client? While Hydrogen is running, is each result cached locally on the client in plain text?

I think that the Jupyter kernel sends text-based replies to the client, and then the client decides how to display them? So I'm guessing they're stored in memory on the client?

**Comment by BenRussert** [comment]
> While Hydrogen is running, is each result cached locally on the client in plain text?

Yes, results are cached mainly so we can display them either inline in output "markers" or off in a pane in the "output area".

Below are some snippets for messing around in the devtools with outputs cached by hydrogen.

Start a kernel and get some outputs then try these from the atom devtools console:
```js
// mobx has a handy utility function mobx.toJS(someObservableObject)
var mobx = require(atom.packages.activePackages["Hydrogen"].path + "/node_modules/mobx")

// If inline outputs:
Array.from(hydrogen_store.markers.markers.values()).map(result =>mobx.toJS(result.outputStore.outputs))

// Or if output is in the output pane:
Array.from(hydrogen_store.markers.markers.values()).map(result =>mobx.toJS(result.outputStore.outputs))
```

You will see the ouputs cached by hydrogen which are based on the response message from the kernel.

**Comment by kylebarron** [comment]
Thanks for the info. It seems similar to Jupyter Notebook in the browser.
