### ISSUE TITLE
No Kernels Installed | No Kernels for grammer python found

### ISSUE THREAD

**Issue by gnidnuos** [nteract/hydrogen#1388]
**Description:**

No Kernels Installed | No Kernels for grammer python found.

**Steps to Reproduce:**

1. Install Debian 9 with Xfce 4.12
2. Install atom 1.28.0 x64
3. Install python 2.7
4. Install Hydrogen

**Versions:**

- Linux bongo 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
- ATOM 1.28.0 x64
- Hydrogen 2.5.1

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by kylebarron** [comment]
Have you also installed the ipython kernel?
https://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by gnidnuos** [comment]
Installed PIP 18.0
https://pip.pypa.io/en/stable/installing/

Installed ipykernel
https://ipython.readthedocs.io/en/stable/install/kernel_install.html

Now working, thanks!!!
