### ISSUE TITLE
failed to parse json plz fix package,json

### ISSUE THREAD

**Issue by kinglloyd001** [nteract/hydrogen#1391]
failed to parse json plz fix package,json
tried reinstalling a couple of times.
hydrogen 2.5.1

**Comment by BenRussert** [comment]
@kinglloyd001 What tipped you off that the problem is our `package.json`? This info may help me understand the issue you're running into.

**Comment by kinglloyd001** [comment]
here is the screen shot of the error message i have been getting for the
past couple 'of days, i even tried out a different version of python and
also installing and uninstalling atom. please assist, i am actually new to
atom and python.

**Comment by kylebarron** [comment]
Screenshots don't come through as email replies. You have to upload the screenshot directly to the Github issue.
