### ISSUE TITLE
kernel indicator not appearing

### ISSUE THREAD

**Issue by bradhackinen** [nteract/hydrogen#1393]
**Description:**
The kernel status indicator is no longer appearing in Atom when I run python kernels (the button on the bottom bar of the Atom window that shows the kernel is running and gives options to shutdown or restart the kernel when clicked).

**Steps to Reproduce:**
1. Open a python script
2. Execute a selection
3. Observe that code executes (output appears), but kernel indicator does not appear. Keyboard commands to shutdown kernel still work.

Two days ago this worked fine. I think I updated Hydrogen since then, but I had a lot of things going on (OS crashes, python updates) and I'm not 100% sure that the problem appeared exactly when the Hydrogen updates took effect. I have tried uninstalling and reinstalling Atom and Hydrogen, and clearing window state.

**Versions:**
OS: Windows 10
Python: 2.7.12 and 3.6.6
Hydrogen: 2.51
Atom: 1.29.0
Electron: 2.0.5
Chrome: 61.0.3163.100
Node: 8.9.3

**Logs:**
This is what my debug log looks like. `Enable Debug Messages` is turned on for Hydrogen.

```
C:\Users\Brad\.atom\packages\chary-tree-view\lib\chary-tree-view.js:11 Uncaught (in promise) TypeError: Cannot read property 'entryClicked' of undefined
    at atom.packages.activatePackage.then.treeViewPkg (C:\Users\Brad\.atom\packages\chary-tree-view\lib\chary-tree-view.js:11:45)
    at <anonymous>
<embedded>:105004 Unable to locate git workspace root for C:\Users\Brad\Google Drive\Research\Python3. Expected if C:\Users\Brad\Google Drive\Research\Python3 is not in a git repository. GitError: git rev-parse --show-toplevel in C:\Users\Brad\Google Drive\Research\Python3 exited with code 128
stdout: 
stderr: fatal: not a git repository (or any of the parent directories): .git

    at new GitError (C:\Users\Brad\AppData\Local\atom\app-1.29.0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:121:24)
    at Promise (C:\Users\Brad\AppData\Local\atom\app-1.29.0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:385:29)
    at <anonymous>
revParse @ <embedded>:105004
4<embedded>:22769 'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
setDefaults @ <embedded>:22769
```

**Comment by BenRussert** [comment]
I don't see hydrogen related items in the output there, except for the unrelated kernelspec config thing I've been meaning to fix 

Just to be sure, can you make sure your hydrogen settings have not disabled the status bar? This is an available setting.

**Comment by bradhackinen** [comment]
Thanks Ben, was it. I must have somehow clicked that setting without noticing. I feel a little foolish now.

**Comment by BenRussert** [comment]
Glad you got it working!
