### ISSUE TITLE
Python Inline Markdown not working

### ISSUE THREAD

**Issue by oesst** [nteract/hydrogen#1397]
Hi, 

I really have troubles to display inline markdown in a python file.   
As suggested in a previous [post](https://github.com/nteract/hydrogen/issues/392) I added 

> from IPython.display import Markdown

to the file. That command runs without troubles.

I then create a new cell with  '%%markdown'. If i just run that line magic command I get the message 'UsageError: %%markdown is a cell magic, but the cell body is empty.'

However if I add something to the cell body, the following error message appears: 

> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-11-c99c82175331> in <module>()
> ----> 1 get_ipython().run_cell_magic('markdown', '', 'H')
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
>    2101             magic_arg_s = self.var_expand(line, stack_depth)
>    2102             with self.builtin_trap:
> -> 2103                 result = fn(magic_arg_s, cell)
>    2104             return result
>    2105 
> 
> <decorator-gen-55> in markdown(self, line, cell)
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
>     185     # but it's overkill for just that one bit of state.
>     186     def magic_deco(arg):
> --> 187         call = lambda f, *a, **k: f(*a, **k)
>     188 
>     189         if callable(arg):
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/magics/display.py in markdown(self, line, cell)
>      68     def markdown(self, line, cell):
>      69         """Render the cell as Markdown text block"""
> ---> 70         display(Markdown(cell))
> 
> NameError: name 'Markdown' is not defined

Anyone has an idea? Is that a Ipython or hydrogen error?

**Comment by kylebarron** [comment]
I can't reproduce this. The key is that you have to highlight the code so that Python knows it's a block:

![image](https://user-images.githubusercontent.com/15164633/45391689-fa8b9e80-b5f1-11e8-9c99-fcd51f0bb067.png)

**Comment by BenRussert** [comment]
Thanks, let us know if you have questions!

**Comment by oesst** [comment]
Thanks for you comment and sorry for the late response I was on holidays.

I tried your example but I get the same error message as before. I marked the whole cell (in your example line 218 till 227) and run it with "Shift + Return" 

> ---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-eec5171827ab> in <module>()
----> 1 get_ipython().run_cell_magic('markdown', '', '## Emphasis\n\n** This is bold text ***')

~/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2101             magic_arg_s = self.var_expand(line, stack_depth)
   2102             with self.builtin_trap:
-> 2103                 result = fn(magic_arg_s, cell)
   2104             return result
   2105 

<decorator-gen-55> in markdown(self, line, cell)

~/.local/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.local/lib/python3.5/site-packages/IPython/core/magics/display.py in markdown(self, line, cell)
     68     def markdown(self, line, cell):
     69         """Render the cell as Markdown text block"""
---> 70         display(Markdown(cell))

NameError: name 'Markdown' is not defined

**Comment by BenRussert** [comment]
@oesst Can you provide the code you are trying to run?

It should work with code like below, note the `%%markdown` line must be run with other code or you will get the `UsageError: %%markdown is a cell magic, but the cell body is empty.` error message.

```python
# %%
print('this is a regular code cell')
# %%
%%markdown
# this is a markdown header 1
## this is a markdown header 2
### this is a markdown header 3
hey *this* is markdown

[Here is a link to this issue](https://github.com/nteract/hydrogen/issues/1397)

```

**Comment by kylebarron** [comment]
Cell magics have to be on the first line sent to IPython. You're running the entire block of above code at once. Instead select the specific lines you want or use `run cell` when delimited by `# %%`:
![image](https://user-images.githubusercontent.com/15164633/46673061-ee6e0f00-cba6-11e8-8da2-4ad43ba53b03.png)

**Comment by oesst** [comment]
Hey Kyle,

that is what I have been trying (see the Gif). 
However I get the same error as mentioned in the first comment.

Thanks for your patience.

![hydrogen](https://user-images.githubusercontent.com/2034967/46744564-ac7ac100-ccab-11e8-8a38-23bfdb12ea4f.gif)


> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-9-8c512ff1d02b> in <module>()
> ----> 1 get_ipython().run_cell_magic('markdown', '', '# this is a markdown header 1\n## this is a markdown header 2\n### this is a markdown header 3\nhey *this* is markdown')
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
>    2101             magic_arg_s = self.var_expand(line, stack_depth)
>    2102             with self.builtin_trap:
> -> 2103                 result = fn(magic_arg_s, cell)
>    2104             return result
>    2105 
> 
> <decorator-gen-55> in markdown(self, line, cell)
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
>     185     # but it's overkill for just that one bit of state.
>     186     def magic_deco(arg):
> --> 187         call = lambda f, *a, **k: f(*a, **k)
>     188 
>     189         if callable(arg):
> 
> ~/.local/lib/python3.5/site-packages/IPython/core/magics/display.py in markdown(self, line, cell)
>      68     def markdown(self, line, cell):
>      69         """Render the cell as Markdown text block"""
> ---> 70         display(Markdown(cell))
> 
> NameError: name 'Markdown' is not defined

**Comment by kylebarron** [comment]
That's a different error. Above you got `SyntaxError: invalid syntax`, here you're getting `NameError: name 'Markdown' is not defined`. 

I don't think you have to actually run `from IPython.display import Markdown`; the 	`%%markdown` cell should work anyways. This might mean that your version of IPython is too old.

**Comment by oesst** [comment]
That was my bad. Updated IPython solved the issue.
Thanks for your help.

**Comment by sickerin** [comment]
Could there be an update so that the markdown portion could be run as its own cell?
So that this should also work. 
```
# %%markdown
# this is a markdown header 1
```
Currently, by default importing a jupyter notebook does that, but if I want to preview the markdown, I have to convert it to something like this

```
# %%
%%markdown
```

I could try doing that if anyone is able to point out wants files might have to change, since I'm quite to new to modding and submitting pull-requests
