### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rcliu** [nteract/hydrogen#1401]
**Description:**
Can't install hydrogen through Atom GUI or command line.

**Steps to Reproduce:**

1. [Try installing atom through GUI or shell.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
OS: 10.13.6
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Logs:**
Error message:
> canvas@1.6.11 install /private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9/node_modules/Hydrogen/node_modules/canvas
> node-gyp rebuild

> zeromq@4.6.0 install /private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install self signed certificate in certificate chain

/private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9
└── (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9/node_modules/Hydrogen/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
{ Error: connect ETIMEDOUT 192.30.253.112:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.112',
  port: 443 }
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11884-22463-g1y1cg.6ejczestt9 No description
npm WARN apm-install-dir-11884-22463-g1y1cg.6ejczestt9 No repository field.
npm WARN apm-install-dir-11884-22463-g1y1cg.6ejczestt9 No README data
npm WARN apm-install-dir-11884-22463-g1y1cg.6ejczestt9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules/Hydrogen/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/omo561/.atom/.apm/.apmrc" "--userconfig" "/Users/omo561/.atom/.apmrc" "install" "/private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/d-11884-22463-q2gsaq.hiraspds4i/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/k_/d37m79ld0gx_ysv_hgc56zv499mcyh/T/apm-install-dir-11884-22463-g1y1cg.6ejczestt9/npm-debug.log
npm ERR! code 1

Error log: So this is kind of weird, but I can't find the directory for the npm-debug log. I can see other directories with similar names in /T but can't find 22463.

**Comment by kylebarron** [comment]
See https://github.com/nteract/hydrogen/issues/1326.

Try 
```
apm install hydrogen --python /path/to/python2
```
Alternatively you should be able to do
```
apm config set python /path/to/python2
apm install hydrogen
```

**Comment by kylebarron** [comment]
I actually had the same error today when installing another package (https://github.com/Aerijo/language-latex2e/issues/18#issuecomment-418404191) so it might be an error with Atom 1.30.0.

**Comment by rcliu** [comment]
Got it, any idea how long it usually takes for them to fix bugs like this?

**Comment by kylebarron** [comment]
You can try this patch: https://github.com/atom/apm/issues/698#issuecomment-293814930

**Comment by wadethestealth** [comment]
Because of how outdated this is and since their have been many releases of atom, hydrogen and other libraries, I am closing this issue.
