### ISSUE TITLE
set() class is not working correctly 

### ISSUE THREAD

**Issue by totovr** [nteract/hydrogen#1412]
**Description:**

When I add an element in a set is not ordering the element, example input:
 
```python
setExample = set()
setExample
setExample = {1, 2, 3}
setExample
setExample.add(4)
setExample.add(0)
setExample

setExample.add('H')
setExample
setExample.add('A')
setExample.add('Z')
setExample
```
Output:
```python
{0, 1, 2, 3, 4, 'H', 'A', 'Z'}
```
If I type this in a normal Jupyter Notebook the output is the correct one:
```python
{0, 1, 2, 3, 4, 'A', 'H', 'Z'}
```

**Versions:**

Mac OS Sierra, Hydrogen 2.6.0

**Comment by kylebarron** [comment]
Sets have no defined ordering, and so it's perfectly legal in Python for them to show up with different ordering. Use a list instead if you want to retain ordering.
https://stackoverflow.com/questions/12354515/what-is-the-difference-between-sets-and-lists-in-python

**Comment by totovr** [comment]
Actually in both are defined as sets:

> This using Hydrogen

```Python
setExample = set()
setExample
setExample = {1, 2, 3}
setExample
setExample.add(4)
setExample.add(0)
setExample

setExample.add('H')
setExample
setExample.add('A')
setExample.add('Z')
setExample

{0, 1, 2, 3, 4, 'H', 'A', 'Z'}
```

> This using Jupyter Notebook

```Python
setExample = set()
setExample
setExample = {1, 2, 3}
setExample
setExample.add(4)
setExample.add(0)
setExample

setExample.add('H')
setExample
setExample.add('A')
setExample.add('Z')
setExample

{0, 1, 2, 3, 4, 'A', 'H', 'Z'}
```

**Comment by kylebarron** [comment]
Yes, but it's legal for them to be different. You can never assume that two sets have the same ordering. If you want them to always have the same ordering, use a list.
```py
l = [1, 2, 3]
l.append(4)
l.append(5)
```
