### ISSUE TITLE
Let the user start a local kernel at a given working directory

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#1419]
Moved discussion from https://github.com/n-riesco/ijavascript/issues/171

---

I'm not very familiar with the latest changes in [KernelManager#startKernel](https://github.com/nteract/hydrogen/blob/7ab2379281cbe9c06306a0d4c7a9c96bc5efd95e/lib/kernel-manager.js#L47-L87), so please correct me if I'm mistaken:
- now, it's possible to associate a kernel to a file
- and when a kernel is started, the working directory is set based on the setting [startDir](https://github.com/nteract/hydrogen/blob/8576be93b4ca3656eb2431b7dd6d65966a8d0417/lib/config.js#L49-L69)

If I understand correctly, @slavaGanzin reports in https://github.com/n-riesco/ijavascript/issues/171 a use case, that requires a working directory different from that of the file or the project.

I'd like to propose that we extend Hydrogen, so that it gives users the option to choose a working directory. There are a number of ways to go about this:
1. Add `prompt` as a case for `startDir` and update the command `hydrogen:start-local-kernel` to prompt the user.
2. Add a new command `hydrogen:start-local-kernel-at-given-directory` that prompts the user for a working directory.
3. Any other approaches?

**Comment by slavaGanzin** [comment]
Another option:
4. bubble up through folders until .hydrogenroot file found

It's a way to go to such projects as [direnv](https://github.com/direnv/direnv)
