### ISSUE TITLE
Clarify "no kernel for language found" error message

### ISSUE THREAD

**Issue by bermudaparty** [nteract/hydrogen#1420]
Suggestion: The error message that gets shown when no kernel for the current language is found should include a hint that language mappings can be manually configured. Something like:

> No kernel for grammar Stata Dyndoc found
> Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.

**Comment by BenRussert** [comment]
Seems like a good suggestion. Would you be interested in sending a pull request?

**Comment by bermudaparty** [comment]
I sent one (#1421). Hope this is what you had in mind.

I used the text that I suggested above. It's maybe not perfect, as not every mapping has to be manually specified. But I figured this would then become clear to the user from the description of the language mapping setting.

**Comment by BenRussert** [comment]
closed by #1421
