### ISSUE TITLE
[Feature Request] I/O Redirection in Hydrogen

### ISSUE THREAD

**Issue by imswebra** [nteract/hydrogen#1422]
One feature I can see greatly improving my workflow would be Unix-like I/O Redirection with Hydrogen.

When testing for example, one might use something similar to `python file.py < input.txt` in order to avoid typing in the test input every time the program is run. I would love to be able to use the power of Hydrogen (watches specifically) in combination with the speed of semi-scripted testing.

**Comment by wadethestealth** [comment]
This should be possible already by using an `!` at the beginning of a terminal command
https://jakevdp.github.io/PythonDataScienceHandbook/01.05-ipython-and-shell-commands.html
Comment and I will reopen if you have any more troubles
