### ISSUE TITLE
problem with auto-completion for python package

### ISSUE THREAD

**Issue by goi42** [nteract/hydrogen#1430]
**Description:**

When I import [ROOT](https://root.cern.ch) (a python package I use frequently), I get an error if I type more than three consecutive characters. That is, `tg` is fine.
```
tg yu er bg io
fg aw
df
```
is also fine. But `tgi` produces an error. (See logs below.)

This error does not occur in an iPython session nor in a Jupyter notebook, nor does it occur with any other python package inside Hydrogen (that I've noticed). It also doesn't occur if I've written out a script in advance (that is, I do not see the error unless I am actively _typing_.)

[Possibly this is a problem with libRint](https://root-forum.cern.ch/t/problem-with-tab-completion/30801/2?u=mwilkins). What are the relevant differences between running in a Jupyter notebook or iPython and running in Atom? I would really like to be able to use Hydrogen properly with this package.

**Steps to Reproduce:**

1. import ROOT
2. type more than 3 adjacent characters (not separated by whitespace or line breaks)

**Versions:**
Hydrogen 2.6.0
Atom 1.31.0
ROOT  6.15/01
macOS 10.13.6

**Logs:**

```
IncrementalExecutor::executeFunction: symbol '_ZN7TTabComC1Ev' unresolved while linking symbol ' **cf_16'! You are probably missing the definition of TTabCom::TTabCom() Maybe you need to load the corresponding shared library? IncrementalExecutor::executeFunction: symbol '_ZN7TTabCom4HookEPcPiRNSt3** 113basic_ostreamIcNS2_11char_traitsIcEEEE' unresolved while linking symbol ' **cf_16'! You are probably missing the definition of TTabCom::Hook(char *, int* , std::** 1::basic_ostream&lt;char, std::__1::char_traits &gt;&amp;) Maybe you need to load the corresponding shared library? Error in TClingCallFunc::make_wrapper: Failed to compile ==== SOURCE BEGIN ====

#pragma clang diagnostic push

#pragma clang diagnostic ignored "-Wformat-security" **attribute** ((used)) extern "C" void __cf_16(void  *obj, int nargs, void** args, void*  ret) { if (ret) { new (ret) (vector) (((vector (&amp;)(const char *))_TTabComHook)(* (const char **)args[0])); return; } else { ((vector (&amp;)(const char *))_TTabComHook)(* (const char** )args[0]); return; } }

#pragma clang diagnostic pop ==== SOURCE END ====
```
See also attached screenshot:
![screenshot 2018-09-27 12 34 42](https://user-images.githubusercontent.com/15774838/46160839-c222cc00-c251-11e8-9a59-379389e3dfea.png)

**Comment by kylebarron** [comment]
This seems to be an issue with autocompletion. By default, the `autocomplete-plus` package is set to generate completions when a word is >= 3 letters long.

1. There's a setting in Hydrogen to turn off Autocomplete. This should allow you to use Hydrogen at least.

> This error does not occur in an iPython session nor in a Jupyter notebook

I believe those use <kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>Space</kbd> respectively to show completions. If you manually ask for completions in those environments, do you get the same bug?

**Comment by goi42** [comment]
> 1. There's a setting in Hydrogen to turn off Autocomplete. This should allow you to use Hydrogen at least.
Yes, this prevents the error. I would really like to be able to use those features, but this is at least a workaround.
> 2. > This error does not occur in an iPython session nor in a Jupyter notebook
>    I believe those use Tab and Ctrl+Space respectively to show completions. If you manually ask for completions in those environments, do you get the same bug?
Tab completion works fine in iPython. It does break in Jupyter though...

**Comment by kylebarron** [comment]
I'm not familiar with how IPython actually collects the autocomplete suggestions to return to Hydrogen/Jupyter. You might want to look for some similar issues on the Jupyter Notebook repository (https://github.com/jupyter/notebook). Since it's also broken in Jupyter, this sounds like an issue that's out of Hydrogen's control.

**Comment by goi42** [comment]
Yes, thank you for your help. Sorry for dragging you into my debugging.

**Comment by goi42** [comment]
As of now, this error is still present in Hydrogen but is no longer present in a Jupyter notebook. Is there a relevant difference between tab-completion in Jupyter and autocomplete in Hydrogen?

**Comment by wadethestealth** [comment]
The way we ask for autocompletes is by sending a message to an idle kernel in the message format "connect_${v4}" and we wait for a reply. Unfortunately this really isn't an issue that we can fix it have to do with either you kernel, environment, or library

**Comment by wadethestealth** [comment]
You can see the `complete` methods inside the ws kernel class (remote kernel) and zmq kernel class (local kernel)

**Comment by goi42** [comment]
Thanks for pointing me to the relevant code. I am not able to further investigate the exact point of the breakdown, but it still seems not to be a problem with Hydrogen, so I will close this for now. Thanks again.
