### ISSUE TITLE
Hydrogen Output Area Scalable Figure Issue

### ISSUE THREAD

**Issue by ericxyun** [nteract/hydrogen#1443]
**Description:**

Hi there,

I'm a new user to Atom and  generally new to the coding .

I've been using Jupyter Notebook but I do not like their layout and I am really glad I discovered the Hydrogen package for Atom.

I have been having one issue where my matplotlib figure outputs to the "Hydrogen Output Area" seems to have a limitation in size and a locked ratio. I was wondering if there was a way I can have the figure output to behave just like how the figures would if it were to be outputted with the `%inline qt` command. In other words, a way that I can increase or decrease the size of the figure without a size and ratio constraint. I was able to have the effect without the constraints on the "Hydrogen Output Area" the first time I plotted something. I'm not sure what I did but it switched over the next time I plotted the same code. I hope I am explaining this clearly enough, I'm not too familiar with the terminology.

**Steps to Reproduce:**

This is the code I am running to get the figure.

`%matplotlib inline`
`import numpy as np`
`import pandas as pd`
`import matplotlib.pyplot as plt`

`train = pd.read_csv('train.csv')`
`missing = train.isnull().sum()`
`missing = missing[missing > 0]`
`missing.sort_values(inplace=True)`
`missing.plot.bar()`

**Versions:**
OS: macOS Mojave
Atom: 1.31.2 x64
Hydrogen: 2.6.0

![Output](https://ibb.co/dXjb3p)

Thank you for your time and your effort!

**Comment by kylebarron** [comment]
@eyun89 	
Can you upload your image again? It doesn't seem to have uploaded correctly.

**Comment by BenRussert** [comment]
Are you still having the issue @eyun89 ? 

Does the same issue occur with other plots? We can't see the screenshot and dont have your `train.csv` to try and repro.

**Comment by wadethestealth** [comment]
Stale

**Comment by alexisthual** [comment]
I solved this by appending the following to `~/.atom/styles.less`:

```less
.hydrogen .sidebar img {
  object-fit: contain !important;
}
```

**Comment by aminya** [comment]
@alexisthual Could you make a PR?

**Comment by aminya** [comment]
This is fixed in the latest version
