### ISSUE TITLE
'No kernel for grammar Python found' - terminal requires 'python3'

### ISSUE THREAD

**Issue by jonahsimon36** [nteract/hydrogen#1451]
**Description:**

Hydrogen unable to open a kernel for Python 3. I am working on a mac with both python 2.7 and python 3. in order to install ipykernel, i ran:

python3 -m pip install ipykernel
python3 -m ipykernel install --user

However I cannot get Hydrogen to recognize the just downloaded kernel. I have "Python" selected in the bottom right, and am attempting to run a line in script.py.

**Steps to Reproduce:**

Open Atom. Run line using hydrogen.

**Versions:**
Atom : 1.31.2
macOS High Sierra 10.13.6

Thank you!

**Comment by kylebarron** [comment]
The default language mapping in the settings is
```json
{ "python": "magicpython" }
```
If you have both Python 2 and 3 you probably need to set the language mapping for `python3`.

**Comment by Ornataweaver** [comment]
Does it mean Hydrogen doesn't work with python2?

**Comment by sagitaninta** [comment]
> Thank you for the response. I was not able to actually figure out how to change the language mappings (or even view them), but running the "Hydrogen: Update Kernels" command solved my problem.

I got the same problem and would like to try this but I didn't see the Update Kernels option in my Atom anywhere

**Comment by vanderaalle** [comment]
Same issue here on ubuntu 18.04. I have everything working on python3, can't see how to avoid the  'No kernel for grammar Python found'
