### ISSUE TITLE
How to cancel autocomplete-plus when running a line or cell in Hydrogen?

### ISSUE THREAD

**Issue by wtadler** [nteract/hydrogen#1452]
Not sure whether this question is best posted here, in the [autocomplete-plus issues](https://github.com/atom/autocomplete-plus/issues) or on StackOverflow, but I figured I'd give it a shot.

When I hit cmd-enter to run a line in Hydrogen, the autocomplete-plus suggestion box stays open and I have to then hit escape to close it. How can I get cmd-enter to both run a line and cancel autocomplete-plus?

I can add this to my keymap:
```
'body atom-text-editor.autocomplete-active':
  'cmd-enter': 'autocomplete-plus:cancel'
```
but then cmd-enter overrides Hydrogen, so I have to hit it again to run the line.

Per [this](https://github.com/atom/atom-keymap/issues/84), I probably have to do a [composed command](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#composed-commands) but I don't know what code to put in there for either the Hydrogen or the autocomplete-plus command.

Would love any suggestions, thanks!

**Comment by kylebarron** [comment]
I believe that autocomplete-plus automatically removes the tooltip when the cursor moves. So I never have this problem because I always use <kbd>Shift</kbd>+<kbd>Enter</kbd> instead of <kbd>Ctrl</kbd>+<kbd>Enter</kbd>.

Regardless, for <kbd>Ctrl</kbd>+<kbd>Enter</kbd> we could probably tell the autocomplete tooltip to close, assuming that it wouldn't raise an exception if the tooltip is already closed.

**Comment by wtadler** [comment]
That's right that there's no issue with shift-enter (which I never use).

Would be great to close the tooltip on cmd/ctrl-enter as well as cmd/ctrl-alt-enter (which runs the cell and also doesn't move the cursor and close the tooltip).

**Comment by BenRussert** [comment]
Put this in your init script. Kind of an edge case in my view, but you can make a pull request if you think this should be built in to hydrogen.

```js
function cancelAutoComplete() {
  // `this` will be bound to the dom node that `hydrogen:run`
  // was called on https://atom.io/docs/api/v1.31.2/CommandRegistry#instance-add
  atom.commands.dispatch(this, "autocomplete-plus:cancel");
}
atom.commands.add("atom-text-editor.autocomplete-active", {
  "hydrogen:run": cancelAutoComplete,
  "hydrogen:run-cell": cancelAutoComplete
});
```

**Comment by wtadler** [comment]
Thanks, love it! I would expect that I'm not the only person running hydrogen and autocomplete-plus (both at about 700k downloads) who would like this to be built in. I'd do a PR but I just took a spin through the code and am not sure where your addition would go.

**Comment by BenRussert** [comment]
I think I'd do this differently if I were building this into hydrogen, as opposed to an init script solution. 

I would probably put this line in both [`run()`](https://github.com/nteract/hydrogen/blob/8af7b1d295f93bd92833b10141370fda6c0b76e4/lib/main.js#L436) and [`runCell()`](https://github.com/nteract/hydrogen/blob/8af7b1d295f93bd92833b10141370fda6c0b76e4/lib/main.js#L453) in `lib/main.js` right after the `if (!editor) return;` line:

```js
// https://github.com/nteract/hydrogen/issues/1452
atom.commands.dispatch(editor.element, "autocomplete-plus:cancel");
```

**Comment by kylebarron** [comment]
@BenRussert 	I agree about how you would implement that if you put it into Hydrogen. Do you think it should be included rather than via init? It's something I've never come across because 1) I usually use `run-and-move-down` and 2) when using `run` I never call it while my cursor is in the middle of an autocomplete suggestion... I always would hit tab to complete first...

**Comment by wtadler** [comment]
> when using run I never call it while my cursor is in the middle of an autocomplete suggestion... I always would hit tab to complete first...

In my case, I rarely actually use autocomplete. 95% of the time my habit is just to finish typing the command. I only complete the suggestion when, e.g., a variable name is particularly long, or I'm using autocomplete to browse through an object's methods. Perhaps other users use it like this too.

**Comment by kylebarron** [comment]
I'll defer to @BenRussert

**Comment by BenRussert** [comment]
I'd be ok with a pull request, I'll leave it up for grabs.

**Comment by BenRussert** [comment]
Oh, and @kylebarron, there shouldn't be side effects as the dispatch will fail silently if auto complete isn't active.
