### ISSUE TITLE
Python/Jupyter/PyCharm/Hydrogen experience + report generation with Pandoc filters

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/hydrogen#1453]
I'm going to share with you my favourite way of using Python and Jupyter for research and reports. And it's not simply using Jupyter or Atom/Hydrogen. I want to write code in PyCharm and use Pandoc filters for reports.

Hydrogen provides great and convenient interface and experience for it's users. So the description below might be of interest for Hydrogen defvelopers as it's also about convenient UX as I see it. 

* Write code in [PyCharm](https://www.jetbrains.com/pycharm/) - best python IDE with code [completion](https://www.jetbrains.com/help/pycharm/auto-completing-code.html), [inspection](https://www.jetbrains.com/help/pycharm/code-inspection.html), quick documentation pop ups (Ctrl+Q, Alt+MouseButton2), quick navigation to declaration (Mouse Button2),
* [Atom editor](https://atom.io/) + [hydrogen](https://atom.io/packages/hydrogen) + [MagicPython](https://atom.io/packages/MagicPython) for interactive code execution and instanty seeing plots, dataframes and more,
* Sync Atom with PyCharm via [file-watcher](https://atom.io/packages/file-watcher) (but first [disable PyCharm safe write](https://github.com/kiwi0fruit/pandoctools/blob/master/atom.md#useful-atom-packages)),
* With this combo you also may need to [reload imported custom external modules in Hydrogen](https://github.com/kiwi0fruit/pandoctools/blob/master/tips.md#reload-imported-modules-in-hydrogen),
* Write Unicode fast in Atom via [sugartex-completions](https://atom.io/packages/sugartex-completions) or [latex-completions](https://atom.io/packages/latex-completions),
* Export Hydrogen document to static Markdown document or Jupyter notebook via [Pandoctools](https://github.com/kiwi0fruit/pandoctools) based on [Pandoc](https://pandoc.org/) (or export to PDF but this unfortunately needs tuning...),
* During export via Pandoctools use any pandoc or text filter like [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) (so you can have cross-references for equations, figures and tables), [SugarTeX](https://github.com/kiwi0fruit/sugartex) LaTeX transpiler or a custom filter via [panflute](https://github.com/sergiocorreia/panflute),
* Pandoctools stores [reusable profiles](https://github.com/kiwi0fruit/pandoctools/tree/master/pandoctools/cli) that define text conversion (written as bash/batch pipeline with CLI text filters),
* Preview static Markdown in Atom via [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus),
* Run Pandoctools from Atom via cross-platform [unix-filter](https://atom.io/packages/unix-filter) ([setup pandoctools in unix filter](https://github.com/kiwi0fruit/pandoctools/blob/master/atom.md#unix-filter)),
* ...
* more details about tuning [Atom packages](https://github.com/kiwi0fruit/pandoctools/blob/master/atom.md) and [using Pandoctools](https://github.com/kiwi0fruit/pandoctools).

### Example

There is an [**example**](https://github.com/kiwi0fruit/pandoctools/blob/master/examples/notebook.py) (from [here](https://github.com/kiwi0fruit/pandoctools/tree/master/examples)) that can be edited in PyCharm, interactively run in Atom+Hydrogen and exported via Pandoctools.

**Comment by kylebarron** [comment]
This looks great for a blog post, but I don't think there's anything actionable here for Hydrogen.

**Comment by SemanticBeeng** [comment]
> * Export Hydrogen document to static Markdown document or Jupyter notebook via [Pandoctools](https://github.com/kiwi0fruit/pandoctools)

@kiwi0fruit is this supposed to run the Python code and generate the output it would generate when ran from Atom? Would you be kind to provide more details how this is supposed to work?

**Comment by kiwi0fruit** [comment]
If you run the very same documents from [examples](https://github.com/kiwi0fruit/pandoctools/tree/master/examples) you should get the very same output pdf and ipynb documets from there (actually CI automatically generates then [here](https://github.com/back0up/pandoctools-ci/blob/master/README.md) so I test it periodically on Windows, Ubuntu and macOS). If it's not the same then please check that you use the lasest version of pandoctools and do not use custom panbdoctools profiles (is would be the case with default installation with no modifications).

After you get the very same behaviour you can see knitty documentation and make tweaks. Note that pandoctools is a separate CLI app and it doesn't use Atom-Hydrogen. But it uses registered jupyter kernels. Differences of jupyter kernerls can also be the source of the differences. For example this code from [CI script](https://github.com/kiwi0fruit/pandoctools/blob/master/.travis.yml) installs conda environments:

```
  - git clone https://github.com/kiwi0fruit/pyappshare
  - bash ./pyappshare/other_envs/python3/install "${_pref}"
  - bash ./pyappshare/other_envs/r/install "${_pref}"
```
