### ISSUE TITLE
Not working with Julia

### ISSUE THREAD

**Issue by hajsf** [nteract/hydrogen#1467]
I got the below error once I pressed `Ctrl +  Enter` in Windows 10.
I'm using `Atom` not `Juno`

<img width="352" alt="jul" src="https://user-images.githubusercontent.com/26045838/47901922-31fc2600-de92-11e8-893c-3e3bc9db0977.PNG">

**Comment by kylebarron** [comment]
Null grammar means that either
1. You haven't saved the file
2. You haven't saved the file with extension `.jl`
3. Most likely, you need to install the `language-julia` package, so that Atom knows that files that ends in `.jl` are Julia files.

**Comment by BenRussert** [comment]
Looks like you found the solution above, thanks!
