### ISSUE TITLE
Shell script / Bash kernel not working

### ISSUE THREAD

**Issue by Beatzekatze** [nteract/hydrogen#1471]
I am trying to get the bash kernel to work, but I've not been successful until now.  I tried to add {"Shell Script": "bash"} to the language mapping, but it isn't helping. My guess is that it is just a capital / small letter issue, but trying all combination didn't work either. 
The Bash kernel works in a Jupyter Notebook, bash kernel is also recognised by the hydrogen (the blue box showing updated kernels). Nonetheless I get the following error when I try to execute a random bash script in Atom.
```
No kernel for language Shell Script found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.
``` 
In the developer console of Atom I see the following message when I try to execute the script (or navigate to the settings of Hydrogen in the preferences), even when the language mapping is kept to default 
`'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}`
I tried to follow the steps in the issue https://github.com/nteract/hydrogen/issues/17, but the error seems to be different and the JSON JavaScript commands seem to be from a different version, so I had no luck there. I worked through multiple similar issues here, but couldn't find the solution.

I use Ubuntu 16.04, Atom 1.32.2 and Hydrogen 2.6.0
The output of `jupyter kernelspec list  --json` is:

```
{
  "kernelspecs": {
    "ir": {
      "resource_dir": "/home/rad/.local/share/jupyter/kernels/ir", 
      "spec": {
        "interrupt_mode": "signal", 
        "display_name": "R", 
        "env": {}, 
        "language": "R", 
        "argv": [
          "/usr/local/lib64/R/bin/R", 
          "--slave", 
          "-e", 
          "IRkernel::main()", 
          "--args", 
          "{connection_file}"
        ], 
        "metadata": {}
      }
    }, 
    "python3": {
      "resource_dir": "/home/rad/.local/share/jupyter/kernels/python3", 
      "spec": {
        "interrupt_mode": "signal", 
        "display_name": "Python 3", 
        "env": {}, 
        "language": "python", 
        "argv": [
          "/usr/bin/python3", 
          "-m", 
          "ipykernel_launcher", 
          "-f", 
          "{connection_file}"
        ], 
        "metadata": {}
      }
    }, 
    "bash": {
      "resource_dir": "/home/rad/.local/share/jupyter/kernels/bash", 
      "spec": {
        "interrupt_mode": "signal", 
        "display_name": "Bash", 
        "env": {
          "PS1": "$"
        }, 
        "language": "bash", 
        "argv": [
          "/usr/bin/python3", 
          "-m", 
          "bash_kernel", 
          "-f", 
          "{connection_file}"
        ], 
        "metadata": {}
      }
    }, 
    "python2": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python2", 
      "spec": {
        "interrupt_mode": "signal", 
        "display_name": "Python 2", 
        "env": {}, 
        "language": "python", 
        "argv": [
          "python", 
          "-m", 
          "ipykernel_launcher", 
          "-f", 
          "{connection_file}"
        ], 
        "metadata": {}
      }
    }
  }
}
```

**Comment by kylebarron** [comment]
The bash kernel works for me with:
```json
{"bash": "shell script"}
```
The direction is programming language -> Atom grammar name.

**Comment by Beatzekatze** [comment]
Ah, didn't know which is which. Thanks for the help!
