### ISSUE TITLE
Stata could not be spawned

### ISSUE THREAD

**Issue by arnold-c** [nteract/hydrogen#1477]
I've tried to set up atom with the Stat kernel, and whilst the kernel works with jupyter notebooks and shows as an available kernel when I load up atom, it does not load with stata files. Instead I get the message "Winax not correctly installed", and "'C:\Program Files (x86)\Stata15\StataSE-64.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process." Regarding the second point, it is in my path so I'm not sure why this is showing. Apologies if it's a simple issue, but I couldn't find a way around it.

**Comment by kylebarron** [comment]
The issue is that you need to uninstall or disable the `stata-exec` package, since that overrules the `ctrl-enter`of Hydrogen when you have a file with extension `.do`. Maybe I should change that

**Comment by arnold-c** [comment]
That worked! Thanks for the help (and your work with Hydrogen - it's awesome!)
