### ISSUE TITLE
Change Markdown parcer to compatible with Jupyter

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/hydrogen#1485]
I've noticed that Markdown renderer works differently in Hydrogen in comparison with Jupyter notebooks. In particular `display(Markdown(...))` doesn't render tables. As if Markdown flavor in Hydrogen doesn't support tables (standard GFM tables).

**Comment by lgeiger** [comment]
This is fixed on master by #1460 since we're now using `@nteract/markdown` which supports tables.

We should ship a new release 🔜
