### ISSUE TITLE
Anaconda + Hydrogen Appears to be Broken

### ISSUE THREAD

**Issue by robotdna** [nteract/hydrogen#1489]
**Description:**

Executing code containing things like matplotlib and numpy run into errors. Hydrogen appears to be using a kernel other than Anaconda. I have Anaconda installed for Python 3.7. 

I'd like to note that I have searched for this issue before I posted here, and was unable to find a solution that worked for me. I looked into setting environment paths but I believe they are all okay when tested in conda. I am sure this is just a problem on my end and not a bug in hydrogen. 

**Steps to Reproduce:**

1. Open Python 3 script in Atom
2. Attempt to run script. 
3. Error occurs due to missing packages

**Versions:**

I am running Hydrogen 2.6.0 and KDE Neon:

Operating System: KDE neon 5.14
KDE Plasma Version: 5.14.4
Qt Version: 5.11.2
KDE Frameworks Version: 5.52.0
Kernel Version: 4.15.0-39-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM

**Plugins:**

I do not have any hydrogen plugins

**Logs:**
Here is an example of the error output. 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-0aa0b027fcb6> in <module>()
----> 1 import numpy as np

ModuleNotFoundError: No module named 'numpy'
```

**Comment by kylebarron** [comment]
Have you tried opening Atom on the command line after sourcing the environment?

**Comment by robotdna** [comment]
> Have you tried opening Atom on the command line after sourcing the environment?

I'd love to try this, but have not; can you walk me through how I'd do this?

**Comment by kylebarron** [comment]
If you're using conda environments
```
conda create -n conda_env -c conda-forge jupyter pandas numpy ...
source activate conda_env
atom .
```
If you're not using conda environments, you just need to make sure your `PATH` is correct.

**Comment by kylebarron** [comment]
If you type `ipython` in your terminal, are you able to load numpy?

**Comment by robotdna** [comment]
> If you type `ipython` in your terminal, are you able to load numpy?

Bringing up a generic terminal, iPython works and numpy is recognized and able to be imported.

**Comment by kylebarron** [comment]
And how are you starting atom? Are you starting it by clicking an icon or from the terminal? When you start Atom from the terminal, Atom receives all the environment variables from the terminal, and should find the same `python` executable.

Try `atom path/to/dir`.

**Comment by robotdna** [comment]
> And how are you starting atom? Are you starting it by clicking an icon or from the terminal? When you start Atom from the terminal, Atom receives all the environment variables from the terminal, and should find the same `python` executable.
> 
> Try `atom path/to/dir`.

I was opening it from an icon, in a Plasma dock. Opening via terminal seems to have everything working! Thank you for your assistance!
