### ISSUE TITLE
Merge and release policy

### ISSUE THREAD

**Issue by willwhitney** [nteract/hydrogen#149]
Now that there are several people actively working on Hydrogen, we should establish a better strategy for merging PRs and cutting releases.

Here's my proposal:
## PRs and releases
- Anybody with permissions on the repo can merge minor PRs, including their own. I don't think we're currently at a size where we need a strict code review policy. You folks write good code.
- For major changes (new UI or interactions for the user) the PR should have the concept vetted by another contributor before merging. The PR should include images/gifs/video as appropriate to make this easier.
- We treat `master` as a beta build. Everybody who's developing, and anyone else who's feeling adventurous, should use `master` as their daily driver.
- Periodically when things are stable, I'll ship a release from master. If I haven't done this in a while and there are things you want shipped, please ping me.
- No code should be added to Hydrogen that is specific to a particular kernel language.
## Becoming a contributor
- If you want to become a contributor with push access to the repo, build a feature or two! I'm always looking to have more people involved in the project. After a couple of good PRs, I'll probably add you as a contributor. Please ping me if there's someone who should be added.

My goal here is to remove myself as a bottleneck for development. You own Hydrogen just as much as I do, and I trust you to take care of it.

@slavaGanzin @n-riesco @rgbkrk Does this seem like a reasonable policy? Please suggest changes!

**Comment by slavaGanzin** [comment]
I prefer having a reviews on every PR. Just to understand where we are moving. 
If I don't give a care to something like this: https://github.com/willwhitney/hydrogen/pull/131, I'll just give my :+1: and that all.

Couple line bugfixes should be silently merged in master of course.

I understand that everyone is busy with their life. But having a five minute review, couple times a month, while drinking your morning coffee, is not a big deal. For a tool (i hope so) we are using everyday.

Now I have 5 open PR's and I don't want to merge them, without any approve (even if works for me and a couple of guys), to prevent any WTF situations.

**Comment by rgbkrk** [comment]
I'm not using hydrogen right now, though that's related to the work I'm doing during the day as well as language (primarily Go). Policy looks good to me, especially *No code should be added to Hydrogen that is specific to a particular kernel language*. If there's an issue with an upstream kernel, get it patched there instead of having to maintain it here.

**Comment by willwhitney** [comment]
That's fair. Certainly for bigger things they should get checked over.

I can go over the PRs this week!

**Comment by n-riesco** [comment]
I agree with Slava's comments. Also, like Kyle, I'm not using Hydrogen
right now and for this reason I appreciate when some else also tests my
changes.

I think Slava brings up the important question of understanding where the
project is moving. To help define this direction we could:

- collect policies like "*No code should be added to Hydrogen that is
specific to a particular kernel language*" into a document like
`CONTRIBUTING.md`).

- open issues to discuss design changes, e.g. shortcut keys, design of
kernel manager, ...
