### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by hyperfraise** [nteract/hydrogen#1495]
Hi.

Is there any plan to make hydrogen natively compatible with python3.7 ? Even manually I haven't managed to make hydrogen use the latest python version.

Thanks.

**Comment by kylebarron** [comment]
Hydrogen will work with Python 3.7 as long as you've set up the Python kernel using Python 3.7.
https://nteract.io/kernels/python

**Comment by hyperfraise** [comment]
It uses 3.6 by default and I haven't found anything that works to make it change.

**Comment by kylebarron** [comment]
That means you have Python 3.6 installed and first on your `PATH`. When you type `python --version`, does it show 3.6 or 3.7?

**Comment by hyperfraise** [comment]
`python --version
Python 3.7.0
`
:/

**Comment by hyperfraise** [comment]
I've successfully ran `python3.7 -m pip install ipykernel  # install the python kernel (ipykernel) globally
python3.7 -m ipykernel install      # install python kernel into nteract's available kernel list` but it still uses 3.6

**Comment by kylebarron** [comment]
If you type `jupyter kernelspec list --json`, what Python entries are there?

**Comment by lgeiger** [comment]
Have you restarted Atom after installing the kernel?

**Comment by hyperfraise** [comment]
`
$ jupyter kernelspec list --json
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/home/damien/.local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/usr/bin/python3",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}

`

**Comment by kylebarron** [comment]
So if you type `/usr/bin/python3 --version`, does that show 3.6 or 3.7?

**Comment by hyperfraise** [comment]
Oh, it does show 3.6. THis is th epath of my 3.7 interpreter :

`/home/user/miniconda3/bin/python3.7`

**Comment by kylebarron** [comment]
So you need to reinstall the kernelspec using the correct Python executable.

**Comment by kylebarron** [comment]
I thought it should've been fixed with 
```
python3.7 -m pip install ipykernel  # install the python kernel (ipykernel) globally
python3.7 -m ipykernel install      # install python kernel into nteract's available kernel list
```
but if not, then first do
```
jupyter kernelspec uninstall python3
```

**Comment by hyperfraise** [comment]
I did all of this with absolute paths to interpreters in with `sudo su` and it worked. Thanks a lot.
