### ISSUE TITLE
Evaluating each line mode

### ISSUE THREAD

**Issue by slavaGanzin** [nteract/hydrogen#150]
I think it would be interesting mode for hydrogen:
https://github.com/JoshCheek/seeing_is_believing

![](https://camo.githubusercontent.com/28417dbca9d0a47b64c10be40d2e2fe0e55ff4df/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6a6f73682e636865656b2f696d616765732f736372617463682f7369622d6578616d706c65312e676966)

p.s. Why this had more github stars than hydrogen? :smile:

**Comment by willwhitney** [comment]
This is really cool.

I don't know if it makes sense to add to Hydrogen, though — it won't work without modification for many languages, and it looks like it requires a certain amount of rewriting your code to fit the tool (which I've tried to avoid in Hydrogen where possible).

**Comment by wadethestealth** [comment]
This is possible with selections as long as each selection ends on a new line. This issue is probably good to be closed.
