### ISSUE TITLE
Unable to install Hydrogen  Atom on my Windows 10 Operating System 

### ISSUE THREAD

**Issue by onwuegbuchulem** [nteract/hydrogen#1507]
This is the error message i got: 

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end
npm ERR! A complete log of this can be found at C:\Users\........
npm ERR!.....
...........
.............

**Comment by BenRussert** [comment]
How did you install? From the exe?

Since this was a while back can you try [reinstalling the latest download](https://nteract.io/)?

**Comment by wadethestealth** [comment]
Closing because of insufficient information without any update
