### ISSUE TITLE
DLL Load failed error importing numpy

### ISSUE THREAD

**Issue by jpenev** [nteract/hydrogen#1517]
**Description:**

New to Python, and I'm trying to import numpy. I'm getting a Traceback Dll load failed error
**Steps to Reproduce:**

The code is:

import numpy as np

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Running Windows 10 Pro Version 1803
Atom 1.34.0
Hydrogen 2.7.0

**Logs:**
Error verbatim:
Traceback (most recent call last): File "C:\Users\jrp_3\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\jrp_3\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\jrp_3\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\jrp_3\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\jrp_3\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\jrp_3\Anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\jrp_3\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\jrp_3\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.

**Comment by kylebarron** [comment]
I'm not exactly sure what causes that, but I'd try reinstalling Anaconda

**Comment by jpenev** [comment]
Tried reinstalling, ran it, same error.
Did the conda install:

(base) C:\Users\jrp_3>conda install -c conda-forge pyzmq
Solving environment: done

## Package Plan ##

  environment location: C:\Users\jrp_3\Anaconda3

  added / updated specs:
    - pyzmq


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.12               |        py37_1000         660 KB  conda-forge

The following packages will be UPDATED:

    conda: 4.5.12-py37_0 --> 4.5.12-py37_1000 conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.5.12         | 660 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\jrp_3>

Tried rerunning it, same error

**Comment by kylebarron** [comment]
Also, this looks like a Jupyter error. Are you able to run code through the Jupyter notebook?

**Comment by Nicbecoz** [comment]
HI, 

Facing similar issue. also mentioned in #1550 

Install Hydrogen 2.8 successfully. 
Selected Hydrogen: Start local kernel, then selected Python 3
No error up to this point

Tried to run some code but got this error below:

**Traceback (most recent call last): File "C:\Users\Nic\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\Nic\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\Nic\Anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\Nic\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.**

Windows 10 Pro Version	10.0.17763 Build 17763
Atom 1.35.1 x64
Hydrogen 2.8
Python 3.7.2 installed via Anaconda - Conda 4.6.8

Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

no other plugins installed

Debug console did not show anything
![image](https://user-images.githubusercontent.com/37495541/54927974-26e38880-4f4e-11e9-90b2-f8b9afb6aaa4.png)

**Comment by Nicbecoz** [comment]
> Also, this looks like a Jupyter error. Are you able to run code through the Jupyter notebook?

No issue running in Jupyter Notebook and Spyder

**Comment by Nicbecoz** [comment]
Tried to use the suggestion here https://github.com/jupyter/help/issues/62#issuecomment-232085082. The earlier errors did not appear but instead i got this:
![image](https://user-images.githubusercontent.com/37495541/55041347-9d27de00-5067-11e9-9b6f-b79c743079dd.png)

**Comment by Nicbecoz** [comment]
Finally, I gave up on Anaconda and decided to install Python on its own. it is working now. just a drag..

**Comment by l-MrMP-l** [comment]
Maybe a stupid Question, but i had the same issue and I just installed numpy
try:
 `conda install numpy -y`
in the envoirement of your desire

**Comment by Nicbecoz** [comment]
All libraries will face the same issue. Sadly, I have given up and moved on to VSCode.

**Comment by Turanga1** [comment]
I can reproduce this error if I open Atom via the start menu. When I am working with conda environments, I need to activate the environment and start Atom from the command line within the environment. Unfortunately it appears that Atom/Hydrogen don't allow easy switching between environments.

**Comment by electiondaze** [comment]
Same issue here. Installed anaconda, and updated. Installed Atom, then hydrogen. Uninstalled & reinstalled with the same issue.

Followed this same process on ubuntu and it worked fine. Work has us using Windows and I'd really love to have this working in Win10.

**Comment by wadethestealth** [comment]
All related issues: 
#1684, #1665, #1550, #1517, #1500, #1405 
Solutions:
#1405
https://github.com/ContinuumIO/anaconda-issues/issues/10422#issuecomment-448185070
https://stackoverflow.com/questions/52821162/jupyter-notebook-failed-to-load-dll

**Comment by al-yakubovich** [comment]
If someone has the same problems here рщц fix it:

Fist solution:
For win10, add the next environment variables into PATH (windows search-> "env" -> edit the system environment variable -> environment variable -> system variable -> path-> edit):
C:\Anaconda3
C:\Anaconda3\Scripts
C:\Anaconda3\Library\bin to your path variable.
(in your case Anaconda can be in the other place)


Second solution:
in Admin Command prompt:
activate base
atom .
(Always launch atom like this)

**Comment by jrgant** [comment]
@al-yakubovich, the first solution worked for me. Thank you!

**Comment by devSauron** [comment]
@al-yakubovich , i know its an old issue, but the first solution worked for me. Thanks!!

**Comment by mwilson19** [comment]
Also worked for me windows 10, using mini conda
