### ISSUE TITLE
Just wanted to report success with spark/scala kernel

### ISSUE THREAD

**Issue by sbromberger** [nteract/hydrogen#152]
Hi,

I just wanted to report that I've successfully gotten Hydrogen working with https://github.com/ibm-et/spark-kernel - in order for it to work, I just needed to specify `{"Scala":"spark", "Spark 1.5.2 (Scala 2.10.4)":"spark"}` in the language mappings. I hope this helps others.

**Comment by slavaGanzin** [comment]
@sbromberger Nice to hear this. Thanks.

**Comment by rgbkrk** [comment]
Awesome.

We should really make the language mappings a separate package sometime soon for both atom-notebook and hydrogen. /cc @gnestor

**Comment by gnestor** [comment]
Roger that

**Comment by willwhitney** [comment]
I've also got early designs for a plugin architecture that should smooth
out a lot of the rough spots with Hydrogen:
https://gist.github.com/willwhitney/57b0bcfc03f37d828f6c

No idea if this still seems like a good idea, but it's on the table.
