### ISSUE TITLE
install take forever

### ISSUE THREAD

**Issue by nashatalani** [nteract/hydrogen#1521]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [x] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
I'll close since I don't think there is anything actionable here.
