### ISSUE TITLE
A style customization example seems incompatible with the current version

### ISSUE THREAD

**Issue by aviatesk** [nteract/hydrogen#1527]
First of all, thanks for your great package !

**Description:**

I found the documentation for "Style Customization of Multiline Result View" does not seem to be compatible with the current release.

The example code chunk in problem is:
> https://nteract.gitbooks.io/hydrogen/docs/StyleCustomization.html
```
.hydrogen {
  .multiline-container {
    .cell_display {
      background-color: @background-color-highlight;
    }
  }
}
```
But `.cell_display` should be replaced by `.hydrogen_cell_display` in order to get the expected result attached within the documentation, like:
```
.hydrogen {
  .multiline-container {
    .hydrogen_cell_display {
      background-color: @background-color-highlight;
    }
  }
}
```

This is kind of just a typo, but I'm welcome to create a PR if you approve it.

**Versions:**

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Plugins:**

No Hydrogen plugin is installed.

**Comment by BenRussert** [comment]
> This is kind of just a typo, but I'm welcome to create a PR if you approve it.

I'm so sorry I didn't see this earlier. I'd approve and merge this PR so fast @aviatesk!

**Comment by aviatesk** [comment]
Ok, crafted my very first PR !

**Comment by BenRussert** [comment]
Closing now that your PR is merged, thanks again!
