### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by AlJZ** [nteract/hydrogen#1528]
**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Windows 10 version 1809

You can get this information from copy and pasting the output of `atom --version`  from the command line.
prebuild-install WARN install self signed certificate in certificate chain

Downloading libzmq for Windows

{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm WARN enoent ENOENT: no such file or directory, open 'E:\TEMP\apm-install-dir-11913-12636-44xr7x.8dejs\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-11913-12636-44xr7x.8dejs No description
npm WARN apm-install-dir-11913-12636-44xr7x.8dejs No repository field.
npm WARN apm-install-dir-11913-12636-44xr7x.8dejs No README data
npm WARN apm-install-dir-11913-12636-44xr7x.8dejs No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JZC\.atom\.apm\_logs\2019-02-03T21_57_27_234Z-debug.log

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [no] hydrogen-python
- [no] Hydrogen Launcher
- [no] Data Explorer

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by kylebarron** [comment]
Can you try again now? I'm able to install Hydrogen just fine on my Windows 10 virtual machine.

**Comment by SiSeUniBE** [comment]
I had the same issue when updating Hydrogen.
`conda update --all` solved the issue (sorry, I don't have time to check which outdated package caused it)
