### ISSUE TITLE
Hydrogen Run not available

### ISSUE THREAD

**Issue by dschien** [nteract/hydrogen#153]
Hi,

I just installed atom on OSX, then installed hydrogen via command line.
On the first run, the `hydrogen: run` option was available. 

When I selected my nb it failed with "no kernel available for language json".

I restared atom and since then the `hydrogen: run` is no longer available.

Any clues?

**Comment by n-riesco** [comment]
@dschien I'm really sorry for such a late reply. Somehow I missed this issue. My guess is that you're trying to open a .ipynb file. Hydrogen doesn't work on .ipynb files. It runs directly on Python files or any other language for which there is a kernel available. See [here](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages) for a list of kernels.

**Comment by n-riesco** [comment]
@dschien Please, don't hesitate to reopen this issue, if you still need help.
