### ISSUE TITLE
How do you install irkernel to work with Hydrogen?

### ISSUE THREAD

**Issue by OnlineVagrant** [nteract/hydrogen#1535]
I'm trying to run R in atom. I have installed the language-r and hydrogen packages. and have also downloaded both R and Anocanda. However I have no idea how to install the IRkernel. The instructions here https://github.com/IRkernel/IRkernel makes no sense to me.

**Comment by kylebarron** [comment]
https://irkernel.github.io/installation/

**Comment by OnlineVagrant** [comment]
@kylebarron  running the first command in the R terminal executes but 

> IRkernel::installspec()
gives the following error
```
Error in IRkernel::installspec() :
  jupyter-client has to be installed but "jupyter kernelspec --version" exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  '"jupyter"' not found
```

isn't jupyter installed by default anocanda?

**Comment by kylebarron** [comment]
Usually yes, but you may have to install it manually

**Comment by OnlineVagrant** [comment]
How do I go about doing that?

**Comment by kylebarron** [comment]
If you use Anaconda terminal, it's already installed

**Comment by OnlineVagrant** [comment]
I figured out the problem. It wasn't installing because I was executing the commands in the R terminal rather than running R from the anaconda terminal and then executing the commands.
