### ISSUE TITLE
No newline after display call in julia

### ISSUE THREAD

**Issue by fredcallaway** [nteract/hydrogen#1536]
When I have the output area in the continuous history mode (icon on the right, three horizontal lines), and I run a command like `display(1)`, I see a `1` but there's no new line, so if I run the command multiple times, I get `111111`. As you can imagine, this makes the output difficult to read, especially if I'm displaying more complex objects. 

Is this expected behavior? I think Julia _does_ append the newline, based on the behavior at the console:
```
julia> display(1)
1

julia>
```

**Comment by kylebarron** [comment]
What matters is not how the console returns text, but rather the messages that IJulia  returns. It appears that IJulia does not by default return a newline with commands, which you can tell from the normal bubbles:
![image](https://user-images.githubusercontent.com/15164633/52424065-4110f680-2ac7-11e9-808c-722e5e682688.png)

A separate issue is how to group commands using the dock output mode. I haven't worked on that part of the code, but it appears that that mode just appends stream messages, which might not be ideal

**Comment by fredcallaway** [comment]
I don't think it is an IJulia problem because I don't get this behavior in a Jupyter notebook running the IJulia kernel. Running these lines in a notebook cell vs. a Hydrogen cell (with the Run Cell command), I get newlines separating each line in the notebook only.
```
display(1)
display(2)
display(3)
```
Of course, if I replace `display` with `println`, I get the behavior you'd expect. So it appears to be something unique to `display` which is quite odd, but also unfortunate because it is what implicitly gets run to display results whenever you run e.g. a line of code.

**Comment by kylebarron** [comment]
When I run `display(1)`, here are the messages sent between Hydrogen and Jupyter/IJulia:
![image](https://user-images.githubusercontent.com/15164633/52577598-73d12c80-2df0-11e9-97d1-81eeb0c0c4d6.png)

The 4th message, which has `output_type: "display_data"`, shows that the only information returned from Julia is `"1"`.

So the two options are

1. Convince the `IJulia` project that it should return `"1\n"` (i.e. include the newline)
2. Convince us that we should handle a string without a trailing newline differently.

It might be of interest that running `print('hi')` in Python returns 
![image](https://user-images.githubusercontent.com/15164633/52577826-e93cfd00-2df0-11e9-8f58-d374e31dfc9f.png)
I.e. the returned text includes the newline.

**Comment by fredcallaway** [comment]
Huh! I am not sure how to reconcile that logging with the behavior in the notebook. Very mysterious. I will create an issue on the IJulia repo, as I think this is incorrect behavior on their end.

If Hydrogen wants to do something about this (and I understand why you might not), I think the thing to do would be to append a newline onto output that has `output_type: "display_data"`. In some cases, you actually don't want a newline (e.g. when using `print` as opposed to `println`). But I think it's clear that a newline _should_ be appended to the output of `display` (to match the behavior in the notebook and the console).

Thanks for your time spent debugging this issue!

**Comment by fredcallaway** [comment]
https://github.com/JuliaLang/IJulia.jl/issues/810

**Comment by kylebarron** [comment]
> When I have the output area in the continuous history mode (icon on the right, three horizontal lines), and I run a command like `display(1)`, I see a `1` but there's no new line, so if I run the command multiple times, I get `111111`.

Also I have no idea what you mean by continuous history mode.

**Comment by kylebarron** [comment]
Are you talking about the output area? If so, I can't reproduce:
![image](https://user-images.githubusercontent.com/15164633/52581568-14c3e580-2df9-11e9-96bf-33005b509708.png)

**Comment by fredcallaway** [comment]
Well this is embarrassing. I only just now thought to update my hydrogen (2.6.0 -> 2.8.0) and now it works correctly. Sorry to waste your time...
