### ISSUE TITLE
Hydrogen successfully installed but wont execute

### ISSUE THREAD

**Issue by zachlanger19** [nteract/hydrogen#1538]
**Description:**

This issue is very similar to https://github.com/nteract/hydrogen/issues/499 but that issue is very old and closed.

Hydrogen doesn't execute anything. When I use hydrogen run/runAll it does't produce any output: No loading, checkmark, result, or debug console output. The first time I try running, it properly says "hydrogen kernels updated" but nothing after that. A difference between this issue and the one mention above, the hydrogen commands do not go away after the first attempt, I can keep attempting. I have tried uninstalling atom and hydrogen.

**Steps to Reproduce:**

cmd-enter
cmd-shift-enter
cmd-ctrl-enter
cmd-alt-enter
Packages -> Hydrogen -> Run
Packages -> Hydrogen -> Run All

**Versions:**

Atom 1.34.0
Hydrogen 2.8.0
Python 3.7
MacOS Mojave 10.14.2

**Logs:**

No logs appear, so let me know if there's anything I can do to provide more debug information

<img width="1244" alt="screen shot 2019-02-08 at 11 23 29 am" src="https://user-images.githubusercontent.com/11550243/52500956-0923b500-2b94-11e9-976f-baadd1b0b4bb.png">

**Comment by BenRussert** [comment]
Can you try setting the logging on in the hydrogen settings? You should see some logging outputs in the devtools there if you do this and run a command?

I see you have teletype there, is there an off chance you are in a shared session trying to run another kernel? I don't know what would happen if that's the case.

**Comment by zachlanger19** [comment]
I have 'Enable Debug Messages' enabled. I also tried disabling teletype, same result as above minus the teletype messages.

**Comment by kylebarron** [comment]
Two questions:

1. Does Jupyter work outside of Hydrogen?
2. What's the output of `jupyter kernelspec list --json`?

**Comment by zachlanger19** [comment]
Ah, thank you! When I ran `jupyter kernelspec list --json`, under _argv_ it showed that is was still pointing to python3.6 rather than python3.7. This can be fixed with:

`python3.7 -m ipykernel install --user`

**Comment by kylebarron** [comment]
Ideally we would catch this error and present it to the user so it's not just silently failing
