### ISSUE TITLE
[Bug] Hydrogen long running command loses output stream

### ISSUE THREAD

**Issue by pashashocky** [nteract/hydrogen#1542]
Having a long-running command in one tab that produces some output, and shutting down a kernel in another tab will ease all output in all tabs running hydrogen.

**Steps to Reproduce:**

1. Run a Hydrogen tab with say, python [Tab 1]. Run the following code:
```
from time import sleep
print("Starting")  # I will soon disappear
for i in tqdm(range(1000)):
    sleep(1)
```
2. While this is running and providing output. Open a different python file in a new tab [Tab 2].
3. Inside [Tab 2] run: 
```
import os
os.getcwd()
```
4. Confirm there is output
5. Shut down kernel running in [Tab 2]
6. Switch over to [Tab 1] and observe that the previously printed string and output from the tqdm command no longer show. However, the kernel in this tab is still executing the sleep loop.

**Versions:**

OS: Archlinux
Hydrogen: 2.7.0

Atom    : 1.34.0
Electron: 3.1.3
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Plugins:**

- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**

No logs required. No logs printed :(

**Comment by pashashocky** [comment]
Is there a way to recover the missing communications from my currently running kernel? This would be very useful as I will miss out on roughly 12 hours of output.

**Comment by kylebarron** [comment]
This is an important bug to fix, same as https://github.com/nteract/hydrogen/issues/1539, https://github.com/nteract/hydrogen/issues/1496.

There isn't a way to do this on the hydrogen side, but I believe ipython stores all inputs and outputs in a dictionary named something like `In` and `Out`. If I'm right you should be able to do something like

```
Out[len(Out)]
```

As long as you haven't closed the Jupyter kernel yet.

**Comment by pashashocky** [comment]
Thank you, can you point me to how I can find that dictionary? That would be amaze!

Meanwhile, looking at the issues. Thank you

**Comment by kylebarron** [comment]
https://jakevdp.github.io/PythonDataScienceHandbook/01.04-input-output-history.html

**Comment by pashashocky** [comment]
@kylebarron #1539 is slightly different. It's talking about the output window allowing you to keep output from a different file. When you switch back to that tab, it would still be there though.

**Comment by kylebarron** [comment]
I have to look at it more closely and I'm away from my computer, but in general there are a few issues with unwanted clearing output, and they're all pretty related internally I think

**Comment by pashashocky** [comment]
@kylebarron Understood, thank you. Unfortunately the Out dictionary will not store printed output... or output that is printed by tqdm... or any other status updates as it seems.
