### ISSUE TITLE
Is it possible to connect to remote server via SOCKS? 

### ISSUE THREAD

**Issue by risaueno** [nteract/hydrogen#1543]
I want to run my code on a remote jupyter kernel - first I SSH into the machine with `ssh -D 10001 server.com`, launch jupyter notebook on port 8888 and set up a SOCKS proxy localhost:10001 on my mac. I can then access the notebook through the local browser at server.com:8888. However when I set up my Hydrogen to be configured “baseUrl”: “http://server.com:8888” and do ‘Hydrogen: connect to remote kernel’ on Atom, I get the connection gateway failed error.

**Comment by kylebarron** [comment]
You have to use
```
ssh user:server -L $localport:localhost:$remoteport
```
i.e. for you it sounds like
```
ssh user:server -L 8888:localhost:10001
```
if Jupyter is running on port 10001 on the remote server.

**Comment by wadethestealth** [comment]
Assuming this works as a fix.
