### ISSUE TITLE
Hydrogen config is Broken: languageMappings

### ISSUE THREAD

**Issue by WyRe** [nteract/hydrogen#1549]
First time I open Atom and run `R` code I get a popup informing about issues in a `.json` file regarding to language-mappings.

![peek 17-02-2019 16-36](https://user-images.githubusercontent.com/4059108/52915408-059ad700-32d4-11e9-9aa9-cb264aac8310.gif)

**Steps to Reproduce:**

1. Open Atom for the first time (with no other windows in the background)
2. Select an `R` code portion and run it using `ctrl + enter` shortcut
3. popup spawns

**Versions:**

```
                   -`                    wyre@GibyArch 
                  .o+`                   ------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: GA-880GM-UD2H 
               `+oooooo:                 Kernel: 4.20.8-zen1-1-zen 
               -+oooooo+:                Uptime: 1 hour, 20 mins 
             `/:-:++oooo+:               Packages: 2084 (pacman), 6 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.7.1 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 3.30.2 
         ./ooosssso++osssssso+`          WM: GNOME Shell 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Numix-Circle [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Athlon II X4 640 (4) @ 3.000G 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GT 740 
 `++:.                           `-/+/   Memory: 5743MiB / 16036MiB 
 .`                                 `/   GPU Driver: NVIDIA 415.22.05 

[wyre:~] % atom --version
Atom    : 1.34.0
Electron: 3.1.3
Chrome  : 66.0.3359.181
Node    : 10.2.0
[wyre:~] % 
```

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [x] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**
![peek 17-02-2019 17-00](https://user-images.githubusercontent.com/4059108/52915540-b35ab580-32d5-11e9-9a80-7005fcabbf27.gif)

I also have got the logs, but they are not expanded. So I think the gif could provide more info even.

It is not a big issue, cause IRkernel does work and handles the code. But I think that popup should not be there. Something is going wrong. **And this just happens the first time do you execute first `R` code piece.**

Maybe is this a duplicate? I did not find anything similar, sorry if it is. 

Thank you, I love so much your plugin, it does provide a very similar behavior and dynamic than powerful and proprietary software _Mathematica_

**Comment by BenRussert** [comment]
Your language mapping needs to be in the form of `{ key1 : value1, key2: value2 }` 

It's also very possible you won't need to customize that in your config at all and you can just leave it as the default. Hydrogen will try to start a kernel based on your current atom language/grammar in your active editor.

**Comment by WyRe** [comment]
Oh, then it was my bad, sorry, I thought I had to add simply there the language. I did not noticed about that syntax 

`{"kernel1": "grammar_kernel1", "kernel2": "grammar_kernel2"}`

I guess I do not need to add anything extra for IRkernel, right? @BenRussert
