### ISSUE TITLE
code is only considered a block if indent is maintained

### ISSUE THREAD

**Issue by jlowin** [nteract/hydrogen#155]
Absolutely love this package, but... Hydrogen will run this block from the first line:

```python
x = (
    "a",
    "b",
    "c")
```

but not this one:

```python
x = (
    "a",
    "b",
    "c"
)
```

This is problematic since the second example is the default behavior in atom (type `x = (<enter>` and the closing bracket moves to that location)

**Comment by willwhitney** [comment]
Yup, unfortunately this is a side effect of how Hydrogen is finding blocks
at the moment. If Atom doesn't think something is foldable, Hydrogen uses
the indentation.

After I wrap up my thesis (in the next couple of weeks) I'll work on
implementing an API for language-specific plugins that will be able to do a
much better job of this.

**Comment by jlowin** [comment]
Got it! Sounds like you have far more important things to deal with than my desire to not have to highlight *all* my text before executing it inline. :) Hydrogen is fantastic, well done.

**Comment by lgeiger** [comment]
@jlowin Since we still rely heavily  on Atom's folding. You could open a issue for this at [atom/language-python](https://github.com/atom/language-python/).
