### ISSUE TITLE
Hydrogen Watch Pane could offer suggestions/auto-completes

### ISSUE THREAD

**Issue by MichaelSchmidt82** [nteract/hydrogen#1557]
When I brought up the Hydrogen Watch pane to add some code to inspect an object and use some built-in Python functions such as `print()`, I was surprised the entry did not provide any suggestions or auto-completions such as those that occur in the editor.

I could understandingly see a floating box with the suggestions useful if placed below the last line of the entry box.

**Comment by BenRussert** [comment]
I see what you mean, but i'd recommend just writing your code in the editor, then copy/pasting or selecting it and running `add watch from editor` from the command palette.

**Comment by wadethestealth** [comment]
This could be added with #1558.

**Comment by wadethestealth** [comment]
@MichaelSchmidt82 Look forward to this in the next release 👍
