### ISSUE TITLE
Hydrogen Watch Pane could use syntax highlighting

### ISSUE THREAD

**Issue by MichaelSchmidt82** [nteract/hydrogen#1558]
The Hydrogen Watch pane offers an area to input code (such as `plt.plot(x, sin(x)); plt.show()` as the given example), but these entries do not offer any syntax highlighting.  It would seem both consistent and convenient to offer syntax highlighting on this code with respect to the editor itself.

**Comment by kylebarron** [comment]
I think those are a `TextEditor` object, so it should be possible to add syntax highlighting if we assign a grammar to them? @BenRussert

**Comment by BenRussert** [comment]
> if we assign a grammar to them?

I thought so when you said this, [but it looks like we do this.](https://github.com/nteract/hydrogen/blob/9d595258c9619b3b106b796c7b1305e3109bcf9e/lib/store/watch.js#L20) 
 
@MichaelSchmidt82 Interested in working on this? You could start with that link above if you're interested.

**Comment by MichaelSchmidt82** [comment]
Sounds great!  You'll have to excuse my ignorance, but I haven't actually contributed anything outside my own personal project.  Should I just submit a PR thats a fix for #1558 then?

**Comment by BenRussert** [comment]
> Sounds great! You'll have to excuse my ignorance, but I haven't actually contributed anything outside my own personal project. Should I just submit a PR thats a fix for #1558 then?

Yep! Please feel free to ask questions here or [on slack](https://slack.nteract.io/) if you prefer. If you are googling or asking around atom community for info, i'd look for something like "syntax highlighting in a mini TextEditor". 

Possible we aren't setting the grammar like intended when constructing the `TextEditor` that is the first thing I'd check.

**Comment by wadethestealth** [comment]
Seems like this is still up for grabs, since I don't see a linked PR

**Comment by wadethestealth** [comment]
@BenRussert that's not the proper way to assign grammars, and that's why it's not working

**Comment by wadethestealth** [comment]
@MichaelSchmidt82 This will be fixed in the next release 👍
