### ISSUE TITLE
Valid Pandas Dataframe outputs Blank Box in Hydrogen?

### ISSUE THREAD

**Issue by grahamanderson** [nteract/hydrogen#1559]
Hi. How do I get Hydrogen to output a Pandas dataframe...as would jupyter? 
Hydrogen gives me a blank box when I try to output it.
I can 'print' the dataframe.

Any help is appreciated 
Mac OS 10.14
Jupyter 4.4.0
Atom 1.34.0
Hydrogen 2.8.0
Python 3.6.3 (edited) 
![image](https://user-images.githubusercontent.com/5177687/53366401-1ae1b800-3909-11e9-9fb2-e817e4fc20b0.png)

**Comment by kylebarron** [comment]
You don't need `display`.
![image](https://user-images.githubusercontent.com/15164633/53367816-1fac6900-3915-11e9-9f0a-22b579415852.png)

I have no issues displaying a table. You should make sure that `display.notebook_repr_html` is `True` and `display.html.table_schema` is `False` in the Pandas options:
https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

**Comment by grahamanderson** [comment]
Strange. This is what I get.  Anything else it could be?
![image](https://user-images.githubusercontent.com/5177687/53368361-27b4da80-390e-11e9-9300-898ad7138101.png)

**Comment by kylebarron** [comment]
Does it work fine in Jupyter notebook?

**Comment by grahamanderson** [comment]
works fine :\
![image](https://user-images.githubusercontent.com/5177687/53368681-01dc0580-390f-11e9-9d49-6ed0837e6958.png)

**Comment by kylebarron** [comment]
Are there any error messages in the Atom dev console?

**Comment by grahamanderson** [comment]
I'm not familiar with atom's console. Here is the output. 
![image](https://user-images.githubusercontent.com/5177687/53369425-cf330c80-3910-11e9-90cc-fd52cbff75ee.png)

**Comment by kylebarron** [comment]
None of that is related to Hydrogen. Do non-pandas outputs show up fine?

**Comment by grahamanderson** [comment]
yes. https://www.dropbox.com/s/k4y2xtcxopxx4u6/Screenshot%202019-02-25%2015.28.56.png?dl=0

**Comment by kylebarron** [comment]
I think to inspect more closely it'll be necessary to see the responses that Jupyter is sending back and why the html element isn't being filled correctly. I don't have more time to debug right now. Maybe @BenRussert 	has an idea

**Comment by grahamanderson** [comment]
Ok. Thanks. Hopefully, it's an easy fix

**Comment by grahamanderson** [comment]
@BenRussert did you get a chance to look at this? I'll happily provide whatever info I can to get a dataframe to display in Hydrogen-Atom :) FYI, this was working properly--months ago when I last used it. Thanks in advance

**Comment by BenRussert** [comment]
Does other output work fine? What about a numpy array or something similar (without print)? What ipython version are you on?

**Comment by grahamanderson** [comment]
numpy arrays work fine
![image](https://user-images.githubusercontent.com/5177687/53532070-0513f480-3abb-11e9-8d72-cd7c86a15dc9.png)
my ipython version is: 6.2.1

lmk what other questions I can answer

**Comment by kylebarron** [comment]
The latest release of IPython is [7.3.0](https://ipython.readthedocs.io/en/stable/index.html). Could you upgrade?
```
pip install ipython --upgrade
```

**Comment by grahamanderson** [comment]
I upgraded to 7.3.0 ...restarted Atom in my virtual environment...
still a blank box
![image](https://user-images.githubusercontent.com/5177687/53577214-dfc6cb00-3b3a-11e9-81e6-055cadc18c0b.png)

**Comment by kylebarron** [comment]
What pandas version?

**Comment by kylebarron** [comment]
Pandas should be returning a dataframe as an HTML element.

You can test if HTML isn't working by running:
```py
from IPython.display import HTML
HTML('<b>this should be bold</b>')
```
You should see bolded output:
![image](https://user-images.githubusercontent.com/15164633/53578952-aac07580-3b46-11e9-9cad-2d18a033db51.png)

**Comment by BenRussert** [comment]
The HTML suggestion above is a good one.

You can also give us more debugging info if you run, where `df` is that dataframe above:

```python

from IPython import get_ipython
ip = get_ipython()
ip.display_formatter.format(df)

```

**Comment by BenRussert** [comment]
Also, would you want to join our nteract slack and hydrogen channel? I'm hoping to help you and sorry for the all the back and forth.

**Comment by grahamanderson** [comment]
![image](https://user-images.githubusercontent.com/5177687/53586383-aea3c600-3b4d-11e9-96bc-2254fc2bdf2a.png)

I'll join the slack channel.

**Comment by kylebarron** [comment]
I think it has to be a pandas setting, and not on our side. 
For example, I see:
```
import pandas as pd
df = pd.DataFrame({'a': [1, 3, 4]})
ip = get_ipython()
ip.display_formatter.format(df)
```
```
({'text/plain': '   a\n0  1\n1  3\n2  4',
  'text/html': '<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>'},
 {})
```

**Comment by kylebarron** [comment]
Pandas isn't responding with any output when you run `df`

**Comment by kylebarron** [comment]
@grahamanderson 	Can you run:
```
pd.reset_option("all")
```

**Comment by grahamanderson** [comment]
![image](https://user-images.githubusercontent.com/5177687/53587925-40610280-3b51-11e9-9ae2-e726fb30bb61.png)

**Comment by kylebarron** [comment]
Right and then try to run `df` again

**Comment by grahamanderson** [comment]
![image](https://user-images.githubusercontent.com/5177687/53588199-00e6e600-3b52-11e9-8edf-2f7af594d5a9.png)

**Comment by kylebarron** [comment]
Personally I think this is a Pandas error. You're able to see HTML just fine through Hydrogen.
You can run the following to see what I see from Pandas.
```py
from IPython.display import HTML
HTML('<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>')
```

But I don't know how it would work fine in Jupyter Notebook and not in Hydrogen. Any thoughts @BenRussert 	?

**Comment by kylebarron** [comment]
@grahamanderson 	Can you try updating Jupyter as well? You say you're on Jupyter version 4.4.0 (I assume you're referring to the notebook version). The newest version is 5.7.4: https://jupyter-notebook.readthedocs.io/en/stable/changelog.html

**Comment by grahamanderson** [comment]
ack...I updated jupyter which completely broke my jupyter...ugh

[C 11:40:26.167 NotebookApp] Bad config encountered during initialization:
[C 11:40:26.168 NotebookApp] The 'kernel_spec_class' trait of <jupyter_client.kernelspec.KernelSpecManager object at 0x10e3019e8> instance must be a type, but 'beakerx.kernel_spec.BeakerXKernelSpec' could not be imported

**Comment by grahamanderson** [comment]
my notebook version is 5.74
jupyter version is 4.4.0
upgraded both

**Comment by grahamanderson** [comment]
Post somewhat rocky updates, the dataframe are displaying properly in Hydrogen :)
The bad news is that Jupyter notebooks no longer display notebooks--filed [issue].(https://github.com/jupyter/notebook/issues/4438) with jupyter.
Thank the gods for virtual environments
