### ISSUE TITLE
execute python script after start of ipython kernel

### ISSUE THREAD

**Issue by Jogala** [nteract/hydrogen#1563]
When starting ipython kernel, I would always like to execute the same python script.

For example in a terminal I would type: 

`ipython -i my_script.py
`

**Comment by kylebarron** [comment]
You can set a command to be run every time you start a kernel in the settings

**Comment by Jogala** [comment]
I guess you mean Settings->Startup Code.  I had tried that but had no success with the syntax. 
How would the above example look like if using the "hydrogen Startup Code"?

**Comment by lgeiger** [comment]
I think you can use the `%run` magic. Try adding `%run my_script.py`.

**Comment by Jogala** [comment]
Sorry but what is the exact syntax that is accepted by Startup Code? I tried:

`{"Python3": %run ~/output_python/start_up_script.py}`

and 

`{%run ~/output_python/start_up_script.py}`

but got the error

Your Hydrogen config is broken: startupCode
SyntaxError: Unexpected token % in JSON at position ...

**Comment by Jogala** [comment]
`{"Python 3" : "%run ~/output_python/start_up_script.py"}`

worked!!! Wuuuh!!

**Comment by lgeiger** [comment]
Make sure to enter valid JSON in this field.
You'll need additional quotes:
`{"Python3": "%run ~/output_python/start_up_script.py"}`

**Comment by lgeiger** [comment]
Nice, glad it worked.

**Comment by Jogala** [comment]
And the name of the field does not matter? I chose "Python 3" because I saw it in the above example. But could I really choose just anything or what is the logic behind that name?

Thanks a lot!

**Comment by kylebarron** [comment]
The name has to be the display name of the kernel. I think this should be changed to allow the actual kernel name, but haven't gotten around to that PR yet.
