### ISSUE TITLE
Syntax for multiple StartUp Commands for same key

### ISSUE THREAD

**Issue by Jogala** [nteract/hydrogen#1564]
So far I understand that  the syntax for the Settings->StartUp Code is the following:

`{"display_name_of_the_kernel" : "command_that_should_be_interpretet"}`

In my case 
`display_name_of_the_kernel = Python 3`
and 
`command_that_should_be_interpretet = %run ~/output_python/start_up_script.py `

I thought I could add commands to the start_up_script.py, such as
`%matplotlib qt`. But the command got ignored. 

Also if I append it like this

`{"Python 3" : "%run ~/output_python/start_up_script.py %matplotlib qt"}`

the `%matplotlib qt ` command gets ignored. Howevery using it as a single command works:

`{"Python 3" : "%matplotlib qt"}`

What is the correct syntax of adding multiple StartUp Commands?

**Comment by kylebarron** [comment]
Just use `%run ~/output_python/start_up_script.py\n%matplotlib qt` so that the latter is on a new line when sent to python

**Comment by Jogala** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/questions/5306741/do-json-keys-need-to-be-unique) there is no point in repeating JSON keys, but one needs to pass an array as value.

Hence I tried:

`{"Python 3" : ["%matplotlib qt","%run ~/output_python/start_up_script.py"]}`

But it does not work. Non of the two commands gets executed.

**Comment by Jogala** [comment]
Thanks a lot @kylebarron ! `{"Python 3" : "%run ~/output_python/start_up_script.py\n%matplotlib qt"}`That worked! Do you have an idea why adding it to the `start_up_script.py` did not work? It looks like` %run `can not execute `%matplotlib`.

**Comment by kylebarron** [comment]
That doesn't work because Hydrogen expects to value to be a string, not an array of strings. Did you try 
```json
{"Python 3": "%run ~/output_python/start_up_script.py\n%matplotlib qt"}
```
?

**Comment by Jogala** [comment]
That is what I did and it works (the order does not matter as it is two lines of code). But what I ment is that if you write `%matplotlib qt` into `start_up_script.py`  which is executed by %run, then it does not work.

**Comment by kylebarron** [comment]
That's an ipython limitation. I don't think you can put magics inside scripts.

**Comment by Jogala** [comment]
Ja that is what it looks like, it is also not working with

**Comment by kylebarron** [comment]
Ok I'll mark this as fixed.

**Comment by jzazo** [comment]
Hi! Can I ask why the following might not work?
```
"Python 3" : "%load_ext autoreload\n%autoreload 2"}
```
It turns out that if I run `%load_ext autoreload` I get the following message:
```
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
```
At least the first line is loaded, but not the second (because it does not do what it is supposed to do). If I run the second line manually, then it works. Any idea how to make it run automatically?

Thanks.

**Comment by kylebarron** [comment]
I think it has to do with IPython internals. I.e. try pasting both lines into IPython at once and see if it works. Hydrogen just passes the text on so there's not as much we can do

**Comment by jzazo** [comment]
Thanks! But do you know what's the difference with the previous question on this thread? Why before it interprets two lines, and now iPython interprets a single line?

**Comment by kylebarron** [comment]
IPython should interpret both inputs the same.

**Comment by jzazo** [comment]
If I pass the line directly to IPython, it escapes the new line character and runs `%load_ext autoreload\\n%autoreload 2`, giving an error.

But by giving it to Hydrogen's Startup Code, it successfully runs the first line and not the second. I am confused of why it does that, and doesn't fully work.

Is it possible to run the second line in a different way?

**Comment by kylebarron** [comment]
If you copy and paste a block with multiple lines into IPython it keeps the newline

**Comment by jzazo** [comment]
Thanks for your patience. Indeed, if I pass as a string, it keeps the newline. If I pass it directly without quotes, then it adds a `/` character, but I guess this is not intended.

In any case, `{"Python 3" : "%load_ext autoreload\n%autoreload 2"}` does not seem to process the second line.

**Comment by wadethestealth** [comment]
@jzazo This seems to be on our end. However I am not to sure exactly why there is an issue with your code. I have opened a PR addressing the issue
