### ISSUE TITLE
Subprocess calls not executed correctly

### ISSUE THREAD

**Issue by leobunga** [nteract/hydrogen#1565]
**Description:**

Calling an external application with
`subprocess.call('$PATH/app',shell=True)` or `subprocess.Popen('$PATH/app',shell=True)`
results in an incorrect execution, giving the error message 

> $PATH/app: 78: exec: /start: not found

This issue does not occur when executing the same command within the python shell.

**Versions:**

Running on 
Ubuntu  : 18.04, kernel 4.15.0-45
Atom     : 1.34.0
Electron : 2.0.16
Chrome : 61.0.3163.100
Node     : 8.9.3
Hydrogen: 2.8.0

**Comment by kylebarron** [comment]
This is probably a duplicate of https://github.com/nteract/hydrogen/issues/1479
