### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by carter-lavering** [nteract/hydrogen#157]
I'm trying _really_ hard to install this package on Windows 10, but it's just not working!

I've installed Python 2.7 to C:/Python27, as well as Visual Studio 2015 Community, ZeroMQ, `npm`, and `ipython[notebook]`. [This gist](https://gist.github.com/carter-lavering/59784faa5af6dbc20120) shows what output I get when I try to run `apm install hydrogen`.

I thought it might be because `python` opens 3.5, so I went and changed the PATH variable to Python27 rather than Python35 but that didn't change the symlink (as you can tell, I'm new to this). Still didn't work.

I really have no idea where to go with this. Please help!

**Comment by TKCen** [comment]
You need Visual Studio 2013, as it is described in the Windows instructions. ZMQ is a Visual Studio 2013 project, that's why it's not working.

**Comment by carter-lavering** [comment]
I installed the 2013 version and now it's working. Still, the installation
could be a little more straightforward...

**Comment by slavaGanzin** [comment]
@carter-lavering We work on this. Thanks
