### ISSUE TITLE
Can't show inline outputs on atom.

### ISSUE THREAD

**Issue by utibeno** [nteract/hydrogen#1573]
Hi, I installed the hydrogen package on atom but when I try running it doesn't generate inline results, however the shift+tab works. Also on the side panel, it says all python kernels updated and also displays this error:

![Screenshot (1)](https://user-images.githubusercontent.com/43590038/54692245-0ef9a800-4afb-11e9-8ce6-73c15851b863.png)

I'm using versions:
Atom: 1.35.1
Hydrogen: 2.8.0

Any help please?

**Comment by kylebarron** [comment]
If you look at the traceback, it says "no module named requests". If you google that, you see that you need to install the package, aka `pip install requests`.

**Comment by utibeno** [comment]
I understand that, but shouldn't that be an inline output instead of it being a pop-up?

**Comment by kylebarron** [comment]
No because the error occurs before `ipykernel` has started.

**Comment by utibeno** [comment]
I pip installed requests and it works with IDLE and my other text editor, but it's not working here

**Comment by kylebarron** [comment]
The question is whether it works with `ipython`, not whether it works with `python`
