### ISSUE TITLE
Connect to Remote IRkernel - No Kernel Specs Available

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [nteract/hydrogen#1575]
I followed all the instructions, and the kernel also shows up on my Ubuntu server.
Other kernels work, yet R isn't.

- I open an ".r" file, write some R code.
- when i go trough the shift+p ... remote kernel procedure, i get this NO Kernel Specs Available

I'm in no way an experienced user, this is first run.

**Comment by kylebarron** [comment]
1. Make sure `language-r` is installed
2 Are you able to do `jupyter console --kernel ir` on the server?

**Comment by hp8wvvvgnj6asjm7** [comment]
1. 
language-r: command not found

2.
Jupyter console 5.2.0

R version 3.5.3 (2019-03-11)


In [1]:

**Comment by hp8wvvvgnj6asjm7** [comment]
Still no kernelspecs available...

**Comment by hp8wvvvgnj6asjm7** [comment]
i used installspec 3.3 now, and 
hydrogen is stuck in Loading sessions...

**Comment by hp8wvvvgnj6asjm7** [comment]
jupyter kernelspec list
Available kernels:
  ir            /root/.local/share/jupyter/kernels/ir
  javascript    /root/.local/share/jupyter/kernels/javascript
  python2       /usr/local/share/jupyter/kernels/python2

**Comment by kylebarron** [comment]
If `language-r` is installed and IR is installed on the server, you should be able to make a connection

**Comment by hp8wvvvgnj6asjm7** [comment]
I run the notebook on my server just as I do for the other kernels
Maybe i did something wrong in atom?
Is the filetype i use the problem?
Whats the file ending for IR files?

**Comment by hp8wvvvgnj6asjm7** [comment]
> languageR
Error: object 'languageR' not found
> install:languageR
Error: object 'install' not found
> install.packages(language-r)
Error in install.packages(language - r) : object 'language' not found
> install.packages(languageR)
Error in install.packages(languageR) : object 'languageR' not found
>

**Comment by hp8wvvvgnj6asjm7** [comment]
I don't know what is meant by language-r
R is installed and IR is installed.
but what is language-r ? 

i searched for a package, and only found languageR which is not language-r
what is meant by that?
After installing this package, i still cant get this working.

**Comment by hp8wvvvgnj6asjm7** [comment]
Fille: r.r 
Contents: print("Hello World!")

no kernel specs available.

**Comment by hp8wvvvgnj6asjm7** [comment]
trying to look into language mappings, maybe thats what you meant

**Comment by hp8wvvvgnj6asjm7** [comment]
{ "python": "magicpython", "language-r" : "language-r" }

[x]

{ "python": "magicpython", "language-r" : "r" }

[x]

{ "python": "magicpython", "r" : "language-r" }

[x]

**Comment by hp8wvvvgnj6asjm7** [comment]
oh well i get it. language-r installed in atom editor. hehe. thanks for missing that detail.

**Comment by hp8wvvvgnj6asjm7** [comment]
thanks its working now
