### ISSUE TITLE
Shift enter in Markdown documents not working 

### ISSUE THREAD

**Issue by RaghuNaik** [nteract/hydrogen#1580]
I seem to loose shift+enter functionality in the markdown document. Only control+enter works. I am not sure if this is related to my using Markdown preview enhanced. 

Has anyone else encountered and fixed it?

I am working on Windows 10 and Hydrogen 2.8 

I have the following plug-ins installed. 
- [x ] hydrogen-python
- [ x] Hydrogen Launcher
- [ ] Data Explorer

Thanks for the this package.

**Comment by kylebarron** [comment]
This probably means some other command you've installed is overriding `shift+enter`. Bring up the keybinding resolver `cntr+.` then see `shift+enter` to see what it calls.

**Comment by RaghuNaik** [comment]
Thanks Kyle.
