### ISSUE TITLE
Hydrogen don't detect my iPython installation

### ISSUE THREAD

**Issue by markeyser** [nteract/hydrogen#1584]
**Description:**

I am running a Windows 7 machine and I have installed Anaconda. I followed all steps to use  iPython kernel, however Hydrogen doesn't seem to find my Anaconda installation. 

I have two Python 3 installations:

C:\Python37\python.exe
C:\Users\t93kqi0\AppData\Local\Continuum\Anaconda3\python.exe

For whatever the reason, hydrogen is always using the first one but not the Anaconda-based one. I want to use my Anaconda installation and not the regular Python 3 installation (first one)

**Versions:**

OS: Windows 7 
Hydrogen:  2.8.0
Atom: 1.35.1 x64

**Plugins:**
Do you have any Hydrogen plugins installed and active?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

By the way, hydrogen works fine with Python 3. But this is not the kernel I want to use. I would like to use the Anaconda kernel instead.

Thanks

Marcos

**Comment by markeyser** [comment]
Hi, I fixed the issue running:

python -m ipykernel install --user

To update the IPython's kernel spec. I did this after following the kernel instruction for Conde from here:

https://nteract.io/kernels

Sorry, I didn't aware that after following the instruction for the Conda kernel you need to update the IPython kernel using:

python -m ipykernel install --user

I've found the solution on the isse #1241

Thanks

Marcos

**Comment by BenRussert** [comment]
Glad you got it working!
