### ISSUE TITLE
Mac Install Failed (behind a proxy)

### ISSUE THREAD

**Issue by jchaps** [nteract/hydrogen#1585]
**Description:**

I have tried and failed to install hydrogren on my Mac. I am on a company computer which needs to tunnel through proxy and firewall. Based on tips in other installation issues, I have made many changes and configurations, but am still running into problems. Alas, I am here to request help.

I have confirmed that apm is functioning and navigating my proxy by installing other atom plugins (atom-beautify, autocomplete-python, etc.)

**Steps to Reproduce:**

`apm install hydrogen` 

**Troubleshooting**
* Uninstall/resinstall Atom
* Uninstall/Reinstall node
* config set python2.7
* config set https-proxy
* brew uninstall/install pkg-config
* brew uninstall/install zeromq
* Reviewed every Mac installation issue and tried many other things..

At this point I'm at the end of my rope and nearly ready to pony up for PyCharm. But I'd prefer not.  Please help!

**Versions:**
atom --version
```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

apm --version
```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 2.7.10
git 2.21.0
```

**Logs:**
```
$❯ PYTHON=python2.7 apm install hydrogen
Installing hydrogen to /Users/{user}/.atom/packages ✗

> zeromq@5.1.0 install /private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-11934-44197-1rgzae5.8r7c/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install self signed certificate in certificate chain


npm WARN deprecated @nteract/display-area@4.4.8: This package has been deprecated in favor of @nteract/outputs.
npm WARN deprecated @nteract/transforms@4.4.7: This package has been deprecated. Please access each transform through its own package.
{ Error: connect ETIMEDOUT 192.30.253.113:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-11934-44197-1rgzae5.8r7c/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vega-themes@2.3.0 requires a peer of vega@* but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-11934-44197-1rgzae5.8r7c No description
npm WARN apm-install-dir-11934-44197-1rgzae5.8r7c No repository field.
npm WARN apm-install-dir-11934-44197-1rgzae5.8r7c No README data
npm WARN apm-install-dir-11934-44197-1rgzae5.8r7c No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{user}/.atom/.apm/_logs/2019-04-05T02_31_17_300Z-debug.log
```

Full error log was posted to gist here: https://gist.github.com/jchaps/ed5f4068638f730e685aacbacee12294

**Comment by BenRussert** [comment]
That's frustrating. It's definitely something to do with your corporate network. I've seen people suggest [this ](https://github.com/atom/atom/issues/16961#issuecomment-373751735), but I dont know how unsafe that is. There might be a way to configure npm somehow to play well with with your internal network.

**Comment by n-riesco** [comment]
@jchaps Judging by [this](https://github.com/prebuild/prebuild-install/blob/8517efc85cd74da9ec0a37562cf1adb20c0e8569/rc.js#L36-L37), I'm not sure if `npm config set https-proxy` does the trick. Is `HTTPS_PROXY` set in your machine?

**Comment by jchaps** [comment]
Thanks for both for the input.  

I do have `strict-ssl=false` set in my config:
```
$❯ npm config ls
; cli configs
metrics-registry = "{internal artifactory registry, redacted}"
scope = ""
user-agent = "npm/6.9.0 node/v10.15.3 darwin x64"

; userconfig /Users/{user}/.npmrc
https-proxy = "{proxy redacted}"
python = "python2.7"
registry = "{artifactory registry redacted}"
strict-ssl = false

; node bin location = /Users/{user}/.nvm/versions/node/v10.15.3/bin/node
; cwd = /Users/{user}
; HOME = /Users/{user}
; "npm config ls -l" to show all defaults.
```

I also have environment variables set, including `HTTPS_PROXY`, `https_proxy`, `HTTP_PROXY`, and `http_proxy`.  I had previously set `apm config set https-proxy` but not `npm config set https-proxy=$HTTPS_PROXY`... so I tried that just in case, but got the same result.

```
{ Error: connect ETIMEDOUT 192.30.253.112:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.112',
  port: 443 }
```

Then it occured to me that the artifactory metrics registry might be the issue, so I did `npm config delete registry`.  I confirmed that I could `curl https://registry.npmjs.org/` through the proxy successfully.  `apm install hydrogen` still fails with the same result.

I'm confident this is a network/proxy issue.  Just can't seem to figure out how to correct or work around it.

**Comment by n-riesco** [comment]
@jchaps Since you have `npm` (and hence `node`), would you be able to check if `npm install zeromq` yields the same error?

**Comment by jchaps** [comment]
OK!  So, it looks like the issue is isolated to the zeromq install.

```
$ ❯ npm install -g zeromq

> zeromq@5.1.0 install /Users/{user}/.nvm/versions/node/v10.15.3/lib/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install self signed certificate in certificate chain

{ Error: connect ETIMEDOUT 192.30.253.113:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{user}/.npm/_logs/2019-04-12T18_30_51_219Z-debug.log
```

Full log in [gist here](https://gist.github.com/jchaps/9e1905b29ecabe5945a71aae1e5a8e5a).  Any thoughts or recommendations? Or should I head over to https://github.com/zeromq/zeromq.js for assistance?

**Comment by jchaps** [comment]
OK, so...

I manually installed the dependencies:
```
npm install -g nan
npm install -g prebuild-install@5.2.1
```
Still got an error from the prebuild-install.js script:
```
prebuild-install info begin Prebuild-install version 5.2.1
prebuild-install info looking for cached prebuild @ /Users/{user}/.npm/_prebuilds/5fc35e-zeromq-v5.1.0-node-v64-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v5.1.0/zeromq-v5.1.0-node-v64-darwin-x64.tar.gz
prebuild-install http request Proxy setup detected (Host: {proxy-redacted}, Port: 8099, Authentication: No) Tunneling with httpsOverHttp
prebuild-install WARN install self signed certificate in certificate chain

{ Error: connect ETIMEDOUT 192.30.253.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.112',
  port: 443 }
npm verb lifecycle zeromq@5.1.0~install: unsafe-perm in lifecycle true
npm verb lifecycle zeromq@5.1.0~install: PATH: /Users/{user}/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/{user}/.nvm/versions/node/v10.15.3/lib/node_modules/zeromq/node_modules/.bin:/Users/{user}/.nvm/versions/node/v10.15.3/lib/node_modules/.bin:/Users/{user}/miniconda/bin:/Users/{user}/miniconda/condabin:/Users/{user}/.nvm/versions/node/v10.15.3/bin:/Users/{user}/projects/dotfiles/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/bin/getconf
npm verb lifecycle zeromq@5.1.0~install: CWD: /Users/{user}/.nvm/versions/node/v10.15.3/lib/node_modules/zeromq
npm info lifecycle zeromq@5.1.0~install: Failed to exec install script
```

I even found [this issue](https://github.com/nodejs/node-gyp/issues/448) and tried `set NODE_TLS_REJECT_UNAUTHORIZED=0`.  I've had to use `strict-ssl=false` previously due to the certificates in the proxy so this seemed reasonable,  but it still didn't resolve the issue.  (Notably, I have `npm config set strict-ssl=false` already set, but looks like `prebuild-install` maybe doesn't honor it?)


A potential workaround... I was able to download `zeromq-v5.1.0-node-v64-darwin-x64.tar.gz` directly from [https://github.com/zeromq/zeromq.js/releases](https://github.com/zeromq/zeromq.js/releases).  I put that in the path that `prebuild-install` was looking for (`/Users/{user}/.npm/_prebuilds/5fc35e-zeromq-v5.1.0-node-v64-darwin-x64.tar.gz`), and then `npm install -g zeromq` worked.  Finally.


So, now I have zeromq installed...
```
$ ❯ npm list -g zeromq
/Users/{user}/.nvm/versions/node/v10.15.3/lib
└── zeromq@5.1.0 
```
... but `apm install hydrogen` is still throwing errors. Extract from the log file below...
```
8802 silly install zeromq@5.1.0
8803 info lifecycle zeromq@5.1.0~install: zeromq@5.1.0
8804 verbose lifecycle zeromq@5.1.0~install: unsafe-perm in lifecycle true
8805 verbose lifecycle zeromq@5.1.0~install: PATH: /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-119312-51137-az1lhc.5inpl/node_modules/Hydrogen/node_modules/zeromq/node_modules/.bin:/private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-119312-51137-az1lhc.5inpl/node_modules/Hydrogen/node_modules/.bin:/private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-119312-51137-az1lhc.5inpl/node_modules/.bin:/Applications/Atom.app/Contents/Resources/app/apm/bin:/Users/{user}/miniconda/bin:/Users/{user}/miniconda/condabin:/Users/{user}/.nvm/versions/node/v10.15.3/bin:/Users/{user}/projects/dotfiles/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/bin/getconf
8806 verbose lifecycle zeromq@5.1.0~install: CWD: /private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-119312-51137-az1lhc.5inpl/node_modules/Hydrogen/node_modules/zeromq
8807 silly lifecycle zeromq@5.1.0~install: Args: [ '-c',
8807 silly lifecycle   'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)' ]
8808 silly lifecycle zeromq@5.1.0~install: Returned: code: 1  signal: null
8809 info lifecycle zeromq@5.1.0~install: Failed to exec install script
8810 timing action:install Completed in 17700ms
8811 verbose unlock done using /Users/{user}/.atom/.apm/_locks/staging-717c1c613337076f.lock for /private/var/folders/23/4xvmh1jd74z4q9z1b6ynn13h0000gp/T/apm-install-dir-119312-51137-az1lhc.5inpl/node_modules/.staging
8812 timing stage:rollbackFailedOptional Completed in 1649ms
8813 timing stage:runTopLevelLifecycles Completed in 178754ms
```

Why does Hydrogen insist on using its own copy of zeromq and not using what is already installed?

**Comment by n-riesco** [comment]
@jchaps

> Full log in gist here. Any thoughts or recommendations? Or should I head over to https://github.com/zeromq/zeromq.js for assistance?

There is already an issue open at zeromq since October 2018 :disappointed: (https://github.com/zeromq/zeromq.js/issues/287)

> Is it possible to either have Hydrogen use the existing install of zeromq, or use a similar workaround where I download the tarball and place it where it can get picked up?

Perhaps, something like the solution described [here](https://github.com/n-riesco/ijavascript/issues/184#issue-399320815) could work for you.

```
$ sudo apt install libzmq3-dev build-essential python2.7
$ apm install hydrogen --zmq-external
```

**Comment by jchaps** [comment]
So, I was able to install zeromq on my Mac (zmq docs recommend homebrew on Mac, and my proxy allows it).

```
$ ❯ brew list zmq
/usr/local/Cellar/zeromq/4.3.1_1/bin/curve_keygen
/usr/local/Cellar/zeromq/4.3.1_1/include/ (2 files)
/usr/local/Cellar/zeromq/4.3.1_1/lib/libzmq.5.dylib
/usr/local/Cellar/zeromq/4.3.1_1/lib/pkgconfig/libzmq.pc
/usr/local/Cellar/zeromq/4.3.1_1/lib/ (2 other files)
/usr/local/Cellar/zeromq/4.3.1_1/share/man/ (66 files)
```

I confirmed that the library was installed:
```
$ ❯ ls -l /usr/local/lib |grep libzmq
lrwxr-xr-x   1 hxy618    admin   43 Apr 15 14:43 libzmq.5.dylib -> ../Cellar/zeromq/4.3.1_1/lib/libzmq.5.dylib
lrwxr-xr-x   1 hxy618    admin   37 Apr 15 14:43 libzmq.a -> ../Cellar/zeromq/4.3.1_1/lib/libzmq.a
lrwxr-xr-x   1 hxy618    admin   41 Apr 15 14:43 libzmq.dylib -> ../Cellar/zeromq/4.3.1_1/lib/libzmq.dylib
```

And I think this means I should be able to use external zmq rather than build. However, `apm install hydrogen --zmq-external` does not seem to work. I run into the same issues as when I don't use the `--zmq-external` flag. I found this portion in `/node_modules/zeromq/scripts/prebuild-install.js`...
```
if (process.env.npm_config_zmq_external == "true") {
  console.log('Requested to use external libzmq. Skipping download of prebuilt binaries.');
  process.exit(1);
}
```
...but for some reason it doesn't look like `--zmq-external` actually works.  Any guidance on what I'm doing wrong here?

**Comment by n-riesco** [comment]
@jchaps How about:
```
npm_config_zmq_external==true apm install hydrogen
```
?

And make sure you have installed `libzmq3-dev` (i.e. the header files needed for compilation).

**Comment by jchaps** [comment]
Success!!!  Though it took some more trouble-shooting.  Info below...

I followed the standard Mac install for zeromq: `brew install zeromq`.  Then `npm_config_zmq_external=true apm install hydrogen` passed the correct flag for external libzmq. This was showing up in the logs:
```
Requested to use external libzmq. Skipping download of prebuilt binaries.
Requested to use external libzmq. Skipping libzmq build
```

But then I had issues with the `python-interceptor.sh`:
```
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.7.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
```

I tried setting python to 2.7 in many ways... `python=python2.7`, `--python=python2.7`, `python=/usr/bin/python2.7`, and even `npm_config_python=/usr/bin/python2.7`, but none worked until I commented [line 53](https://github.com/atom/apm/blob/60b1efd07345f41e9c6263788bb52287f48aa0a7/bin/apm#L53) of `apm` according to [this comment](https://github.com/atom/apm/issues/179) in atom/apm#179.  After that I could `apm config set python=python2.7` and the config would stick.

Next, I was missing xcode. I had xcode command line tools, but not the full program, and needed the full xcode to run the build.  So I downloaded Xcode from the Mac App Store. I also ran `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` to ensure command line tools were linked to the full app.

After that, it finally worked!
```
$❯ npm_config_zmq_external=true apm install hydrogen
Installing hydrogen to /Users/hxy618/.atom/packages ✓
```

Clearly there are bugs in `apm` (python-interceptor.sh) and `prebuild-install` (not following the proxy and/or strict-ssl flags in apm/npm), but I don't think those are `hydrogen` issues.  I'm closing the issue as a result, but happy to engage with the dev team if you need me to run any testing to help isolate or fix the issues.

**Comment by n-riesco** [comment]
@jchaps Thank you for reporting back!

**Comment by jchaps** [comment]
An update... I recently had to reinstall Atom and extensions on my work machine, and really wanted to get this done without disabling strict-ssl and opening up MITM risk. With a bit of research, I found a new setting that I thought may be useful (NODE_EXTRA_CA_CERTS). More info [here](https://levelup.gitconnected.com/how-to-resolve-certificate-errors-in-nodejs-app-involving-ssl-calls-781ce48daded).

I have proxy environment variables established (HTTP_PROXY and HTTPS_PROXY). 
I have my proxy certificate file downloaded locally, and set a new env variable `export NODE_EXTRA_CA_CERTS=/path/to/SystemCertificates.cer`.

Once these env variables were set, I was able to `apm install Hydrogen`, without any other configured settings.

```
❯ apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 3.7.6
git 2.21.1
```

```
❯ apm config ls
; cli configs
globalconfig = "/Users/{user}/.atom/.apm/.apmrc"
metrics-registry = "{artifactory registry}"
scope = ""
user-agent = "npm/6.2.0 node/v10.2.1 darwin x64"
userconfig = "/Users/{user}/.atom/.apmrc"

; environment configs
python = "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"

; project config /Users/{user}/.npmrc
registry = "{artifactory registry}"

; globalconfig /Users/{user}/.atom/.apm/.apmrc
cache = "/Users/{user}/.atom/.apm"
progress = false

; node bin location = /Applications/Atom.app/Contents/Resources/app/apm/bin/node
; cwd = /Users/{user}
; HOME = /Users/{user}/.atom/.node-gyp
; "npm config ls -l" to show all defaults.
```

A sanitized copy of my verbose install output is on [gist for reference](https://gist.github.com/jchaps/3bf937cde84d6257a79ccc65e1d0c67b).
