### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by nagymusic** [nteract/hydrogen#1587]
Hello!
I'm new to Hydrogen, mainly using it compile Python code with [abjadcompile](https://atom.io/packages/abjadcompile) package. Both Hydrogen and abjadcompile package work great on Mac and Linux, but when used on Windows, they produce an error message (see below). Reading the documentation ([Troubleshooting Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#hydrogen-fails-to-import-modules)), it appears that one may need to set the PATH variable for the given module. I'm writing if perhaps one of the users on this list may be able to have a look at the error message below and advise on how to set the required path variable so that this package can be used on Windows.

I contacted the author and it turns out that the abjadcompile package has only been tested on Mac. However, since all other components (Abjad Python package, Lilypond, etc) work just fine on Windows on their own, it may be the question of setting up the correct path so that can be used within Atom.

Thank you!

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4daa33e37706> in <module>
----> 1 import abjad

~\AppData\Local\Programs\Python\Python37-32\lib\site-packages\abjad\__init__.py in <module>
     10 # ensure that the ~/.abjad directory and friends are setup
     11 # and instantiate Abjad's configuration singleton
---> 12 from abjad.system.AbjadConfiguration import AbjadConfiguration
     13 abjad_configuration = AbjadConfiguration()
     14 del AbjadConfiguration

ModuleNotFoundError: No module named 'abjad.system'

**Comment by BenRussert** [comment]
I'm not sure the path is the issue since the kernel looks like it finds abjad, but it's missing something or not able to install it.

What method did you use to install abjad?

**Comment by nagymusic** [comment]
Thanks, Ben. I reinstalled Abjad via `pip install abjad` and it all works great. I'm still not sure why installing abjad via git doesn't seem to work: 
``
~$ git clone https://github.com/Abjad/abjad.git
``
``
~$ cd abjad
``
``
abjad$ pip install .
``
In fact, Installing Abjad in Windows this way produces the same error message as before (see my earlier post), even when abjad is run outside Atom.

**Comment by nagymusic** [comment]
It all worked just fine after I manually installed abjad module (moved all the required files) into the Python environment. Thanks again for pointing me in the right direction!

**Comment by BenRussert** [comment]
Happy you got it working!
