### ISSUE TITLE
Atom Hydrogen error "unexpected EOF while parsing" for python `if` statement!? (but not other statements) 

### ISSUE THREAD

**Issue by bridgesra** [nteract/hydrogen#1589]
Seems to be a problem w/ how Atom / Hydrogen interprets the code when using Shift+Enter on and cursor on a single line of an `if` statement/block of code. Highlighting the whole `if` statement executes correctly. Putting cursor on the first line of an `if` statements produces the EOF error. 

```
## this works:
for i in range(10):
    print( i)

## this doesn't:
if not False:
    print("test worked")

## this example doesn't throw an error, but only executes the "if" and not the else parts:
x= False
if x == True:
    print("test")
elif x == None:
    print ('test anyway')
else:
    print('test again')
```

![screenshot](https://i.stack.imgur.com/c7JP4.png)

How often:
100%

Versions
Editor name and version:
Atom 1.35.1
hydrogen 2.9.0
apm 2.1.3
npm 6.2.0
node 8.9.3 x64
atom 1.35.1
python 2.7.15
git 2.14.3

Platform: Mac OS Sierra 10.12.6

Color scheme: One Dark/Solarized Dark

seems related to [this folding issue](https://github.com/atom/language-python/issues/299)

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [no ] hydrogen-python
- [no  ] Hydrogen Launcher
- [no  ] Data Explorer

**Comment by bridgesra** [comment]
also see https://github.com/atom/language-python/pull/300 (folding of python `if` statements) now fixed

**Comment by BenRussert** [comment]
> I believe the solution will be to upgrade once versions are rolled up.

Yep, you've got it. 

Anyone looking for a workaround in the meantime, see [the stackoverflow discussion](https://stackoverflow.com/a/55624303/3622885)

**Comment by bridgesra** [comment]
FYSA: upgraded to Atom 1.36, but folding of python if statement (w/ no else) still fails and execution of python if statements w/o highlighting the whole if statement is still executing w/ an error (no else) or improperly (if/else)--no change yet or it's still persisting
