### ISSUE TITLE
R kernel loops

### ISSUE THREAD

**Issue by ahsen1402** [nteract/hydrogen#1598]
Hi,

I am running R with hydrogen and I am using cmd+Enter to run the code. However, when I try this before a for loop it gives error as it runs only the line with the for. However, when I select all the code inside the for loop and then run the code it runs. Is there any fix for this.

**Comment by wadethestealth** [comment]
@ahsen1402 If `cmd+Enter` does not work for you, you could always use cells and run them with `cmd+alt+enter`. Please view the [Getting Started guide](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html) for explanation on cells and other Hydrogen behaviors.
