### ISSUE TITLE
Result font size

### ISSUE THREAD

**Issue by dpavlic** [nteract/hydrogen#160]
Is it possible to change the font size in the bubble pop up?  I am getting tiiiiny fonts on my display and my eyes are having a difficult time with it.
![hydrogen](https://cloud.githubusercontent.com/assets/1075079/13041027/6771d61e-d381-11e5-81ef-17fdbc8c795e.png)

**Comment by slavaGanzin** [comment]
You can edit your stylesheet and add something like that:
```
.bubble-output-container { 
  font-size: 24px;
}
```

**Comment by dpavlic** [comment]
That does it.  Thanks for the prompt reply, this is exactly what I had in mind.  I will close this now.

**Comment by mackdata** [comment]
I found that the following code, allows me to change the text size in 2017.

```
.hydrogen.output-bubble .bubble-result-container code {
    font-size: 14px;
}

```

**Comment by BenRussert** [comment]
@mackdata we have a style customization page started in our docs. Would love a PR if you are interested!
