### ISSUE TITLE
Traceback error when trying to run any python code

### ISSUE THREAD

**Issue by Pytonkode** [nteract/hydrogen#1604]
**Description:**
![image](https://user-images.githubusercontent.com/28710509/56816237-68b06900-6843-11e9-9720-0024bd7a3ad8.png)

Running a fresh install of Atom 1.36.1 on win10, my conda seems to have everything updated and the paths on windows are set.
![image](https://user-images.githubusercontent.com/28710509/56816607-26d3f280-6844-11e9-94da-eb3e5a4ad345.png)

**Comment by BenRussert** [comment]
Did you launch atom from that anaconda prompt with `atom .`? Sometimes we see mismatched environment variables otherwise.

**Comment by Pytonkode** [comment]
![image](https://user-images.githubusercontent.com/28710509/56890156-f88b2880-6a78-11e9-97b8-ce556129d5d9.png)
