### ISSUE TITLE
Cannot see the python3 output inline after Hydrogen update

### ISSUE THREAD

**Issue by Run-Hadid** [nteract/hydrogen#1605]
**Description:**

print(2+3) does not show an output inline. Was working before the Hydrogen and Atom update. 
Tried changing the config settings in Hydrogen but still isn't working for me.

I'm using MacOSX 10.14.4 Mojave.
I've reinstalled python3 using Homebrew and have reinstalled Atom.

**Steps to Reproduce:**

1. Install Python3
2. Install Atom
3. print (2+3)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
OS : MacOSX 10.14.4 Mojave
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [ No] hydrogen-python
- [ No] Hydrogen Launcher
- [ No] Data Explorer

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
You're sure the kernel starts though?

**Comment by shr00mie** [comment]
possibly related issue to this. after recent update of both hydrogen and atom, I'll only get 3 lines of logger output while kernel is showing as busy, then I'll remaining output when the program finishes. haven't seen this behavior before.

**Comment by shr00mie** [comment]
reverted back to 2.9.0 and the issue was resolved. someone definitely borked up something big with the inline output between 2.9 and 2.10. pinning this one for now. Would love to be able to have a chat with one of the devs about this as behavior in 2.10 is currently unworkable for my use case.

**Comment by BenRussert** [comment]
Could you open a new issue? This one predates the release in question.

**Comment by shr00mie** [comment]
> Could you open a new issue? This one predates the release in question.

Sure thing. What info do you need?

**Comment by BenRussert** [comment]
Anything you can provide that would help me understand the problem and especially helpful would be some code to reproduce the issue.

**Comment by wadethestealth** [comment]
assuming this is no longer an issue since there is no follow up and we have had multiple releases since this issue
