### ISSUE TITLE
Group code to section - feature proposal

### ISSUE THREAD

**Issue by Sutyke** [nteract/hydrogen#1609]
Thanks a lot for excellent atom package. I use hydrogen when coding as it is very light and error free comparing to notebook.
 
One feature that hydrogen is missing is to group code to sections and move quickly between sections and run each section  independently.  

I understand that Notebook like feature will be difficult to implement in hydrogen, however matlab cell mode is very simple way how defectively split code in one file to cells. Please implement something similar to hydrogen. 

matlab cell mode example video
https://ch.mathworks.com/videos/managing-code-in-matlab-cell-mode-scripts-97209.html

**Comment by aviatesk** [comment]
I think what you want is already implemented.

`Hydrogen: Run Cell` or `Hydrogen: Run Cell And Move Down` commands allow you run code separated by cell breakpoints.

Refer to [the documentation](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html) for more details.
