### ISSUE TITLE
Other python Kernels not recognized

### ISSUE THREAD

**Issue by kescobo** [nteract/hydrogen#161]
I did some searching around, but couldn't find an answer to this - pardon if it's already been answered. 

Right now, hydrogen only seems to recognize my python 3 kernel, and I don't seem to have the option to change it. I found #138, but when I type "kernel commands" into the command pallet, I only get `interupt` and `restart`. 

I'm using OSX (El Cap) and my default python installation is a python3 installed through Conda, but I've got Jupyter installed on that as well as on the system python 2.7. Not sure where to look for solutions.

**Comment by slavaGanzin** [comment]
This wasn't released yet.

You can:
1. Install hydrogen from repo and use master branch.
2.  Find your kernels with ```jupyter --paths``` (data dirs) and alphabetically rearrange them.

**Comment by slavaGanzin** [comment]
@kescobo We just shipped release. So just update hydrogen and you'll get changing kernel functionality.
