### ISSUE TITLE
Hydrogen kernel and compiler use different system paths

### ISSUE THREAD

**Issue by hanzckernel** [nteract/hydrogen#1610]
**Description:**

In using hydrogen kernel and compiler to import a module, it throws an error. After figuring out, I realized both have different system path to operate.

**Steps to Reproduce:**

1. run sys.path on hydrogen kernel produces something like this:

['/Users/hanzhicheng/Desktop/Jupyter/github/option_pricer/option_pricer', ...,
'/Users/hanzhicheng/anaconda3/lib/python3.7/site-packages/IPython/extensions', '/Users/hanzhicheng/.ipython']

![Screenshot 2019-05-03 at 22 05 30](https://user-images.githubusercontent.com/43314240/57163841-9290ff00-6df2-11e9-92cb-70bcb52a9c3e.png)

2. While using debugger the sys.path print different paths:
['/Users/hanzhicheng/Desktop/Jupyter/github/option_pricer/option_pricer/pde', ...]

![Screenshot 2019-05-03 at 22 05 47](https://user-images.githubusercontent.com/43314240/57163842-9290ff00-6df2-11e9-9b9f-8fd2ba3f321a.png)

which I am not sure what is the source of problem.
**Versions:**
OS:
      System Version: macOS 10.14.4 (18E226)
      Kernel Version: Darwin 18.5.0
      System Integrity Protection: Enabled

Atom:
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Plugins:**

hydrogen-python is active.
use script as interpreter

P.S. My first question on Github. Please correct me if any errs on styling, etc.

**Comment by wadethestealth** [comment]
I don't believe this is a Hydrogen issue. If you are having issues with a module its most likely your environment. Sys.path can contain multiple values, and the system uses these for importing/reading/writing/executing files. The kernel in your case IPython/Jupyter, which is not owned by hydrogen, can be started in different directories in the package settings of hydrogen. To solve your issue, review your environment paths and be sure where ever you start your kernel that you have access to your needed module from the kernel via your path variable.

**Comment by wadethestealth** [comment]
Has grown stale
