### ISSUE TITLE
shift+enter in atom not working

### ISSUE THREAD

**Issue by osterburg** [nteract/hydrogen#1611]
**Description:**

I am getting the following message when I am trying to execute a simple line of code. For example:

```python
print("hello")
```
 `
my-virtualenv-name
dyld: Library not loaded: @executable_path/../.Python Referenced from: /Users/stephanosterburg/.local/share/virtualenvs/learnco_projects-hegMt5go/bin/python Reason: image not found
`

**Steps to Reproduce:**

0. go into **anaconda env**
1. start atom
2. new file
3. write some python code
4. shift-enter

**Versions:**

macOS Mojave 10.14.4
Hydrogen 2.9.0 
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

Other plugins installed and active are:
- atom-beautify
- file-icons
- git-plus
- git-status
- indent-detective
- ink
- jekyll
- julia-client
- kite
- language-fish-shell
- language-julia
- latex-completions
- markdown-writer
- python-autopep8
- python-black
- teletype
- tool-bar
- uber-juno

**Comment by aviatesk** [comment]
Can you run IPython or Jupyter from command-line on your environment ?

Here is the [trouble shooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) that seems relative to your problem.

**Comment by BenRussert** [comment]
Is the issue the same if you run `Hydrogen: Run and Move Down` from the command palette? From the title it sounds like you are talking about the keyboard shortcut only so we may want to change the title.

The juno packages you have installed have some similar keyboard shortcuts as hydrogen, so we should rule that out as the problem.

**Comment by osterburg** [comment]
@aviatesk yes I can both in my anaconda env.

**Comment by osterburg** [comment]
@BenRussert I tried to remap the keyboard shortcuts but without any luck (tonight) as well through the menu bar, which didn't work either.
Remapping the keyboard shortcuts seems tricky at best.

**Comment by osterburg** [comment]
I will keep trying tomorrow, too late now.

**Comment by aviatesk** [comment]
@osterburg 
Those two may help you:
- Starting up Atom _from your virtual env_ (I mean something like `conda activate yourenv` then `atom .`)
- Resister your local Jupyter server to [Hydrogen's remote gateways](https://nteract.gitbooks.io/hydrogen/docs/Usage/RemoteKernelConnection.html) and then connect to it from Hydrogen after starting the server outside of Atom

**Comment by osterburg** [comment]
@aviatesk Great thanks for your help, that fixed it.
