### ISSUE TITLE
Unable to install Hydrogen via APM or Atom - Manjaro

### ISSUE THREAD

**Issue by r614** [nteract/hydrogen#1613]
**Description:**

I am unable to install Hydrogen in Atom via the package browser or the command line. I am running Manjaro Linux with KDE Plasma

**Steps to Reproduce:**

1. Install Hydrogen from Packages/Terminal

**Versions:**

Atom: 1.34.0

**Plugins:**

Do you have any Hydrogen plugins installed and active?

- [Y] Hydrogen Launcher

**Logs:**

``` zeromq@5.1.0 install /tmp/apm-install-dir-11948-2634-1jey12y.zj9n/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


npm WARN deprecated @nteract/display-area@4.4.8: This package has been deprecated in favor of @nteract/outputs.
npm WARN deprecated @nteract/transforms@4.4.7: This package has been deprecated. Please access each transform through its own package.
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11948-2634-1jey12y.zj9n/node_modules/Hydrogen/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11948-2634-1jey12y.zj9n/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11948-2634-1jey12y.zj9n/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vega-themes@2.3.0 requires a peer of vega@* but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-11948-2634-1jey12y.zj9n No description
npm WARN apm-install-dir-11948-2634-1jey12y.zj9n No repository field.
npm WARN apm-install-dir-11948-2634-1jey12y.zj9n No README data
npm WARN apm-install-dir-11948-2634-1jey12y.zj9n No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by wadethestealth** [comment]
Hi @r614 Have you viewed the Troubleshooting Guide?
[This may be related to your issue.](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#hydrogen-stopped-working-after-updating-atom)

**Comment by r614** [comment]
@wadethestealth I looked the troubleshooting guide but didn't find anything that could fix my problem. However, I also realized that the installation passes if I remove sudo, though I have no idea why.

At the moment, launching atom without sudo initializes a completely different ide which cannot load packages/access files so its a bit useless for me. ):

**Comment by wadethestealth** [comment]
@r614 I am sorry, I am unaware of how to solve this issue. I'll leave this open in hopes someone else can help. @BenRussert @aviatesk

**Comment by BenRussert** [comment]
You should be able to launch atom without sudo. I wonder if your installation is messed up and needs to be reinstalled. How are you installing atom?

 `apm install hydrogen` should run without sudo also.

**Comment by r614** [comment]
Hey Ben!

I did a fresh install of Arch, and Atom to check and I am still facing the issue. 
I can successfully install hydrogen using `apm install hydrogen`
The problem is that, Atom handles permissions in a weird way. For example, if I run `sudo atom` I get a different instance of Atom which has a different set of packages installed as opposed to if I launch atom without sudo - something to do with where packages are saved. ( https://discuss.atom.io/t/sudo-su-permissions-per-file/14204/2 )

The workaround for that is installing packages by using `sudo apm install`, which has worked for pretty much every package I have so far, but I am unable to install Hydrogen.

**Comment by wadethestealth** [comment]
@r614 you could try going in the directory of hydrogen that is normally installed (which is in atoms packages, and open a terminal there. Inside the terminal type `sudo apm link` if it really is a different instance you should be able to link existing packages to it.

**Comment by wadethestealth** [comment]
If you can get any installation passing, the solution is to use apm link. Because atom is not technically supported on Manjaro, we can't really fix the issue from a hydrogen stand point and you are much better off addressing the atom team about installations. atomio.slack.com is very helpful and probably wouldn't mind helping you. Unless there is something we can do code/packaging wise over at hydrogen I am going to close this issue.
