### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by slavaGanzin** [nteract/hydrogen#162]
It's time to make a release. So how now, with nteract this would be handled?
@rgbkrk

**Comment by rgbkrk** [comment]
I can give it a shot and see what happens, let me look into the state of things.

**Comment by rgbkrk** [comment]
Done, shipped it as a minor release.

Hopefully we can start honing in #158 next.

**Comment by rgbkrk** [comment]
Anyone with push access can make a release (technically speaking that is) and if things are well tested we should ship fairly often.
