### ISSUE TITLE
Jasmine link is dead

### ISSUE THREAD

**Issue by wadethestealth** [nteract/hydrogen#1625]
Inside the contributing guide, the link to jasmine has been removed from jasmine's webserver. Would have fixed it myself, but was unsure whether you wanted to direct new comers to strictly 3.2 api or the gettting started section.

**Comment by lgeiger** [comment]
I think it makes sense to directly link to the API docs, since the jasmine getting started guide includes a lot of Node.js specific setup which doesn't apply to us since we're using it via Atom.
@wadethestealth Do you want to send a PR?

**Comment by wadethestealth** [comment]
@Igeiger sure
