### ISSUE TITLE
Hydrogen 0.7.0 slow startup

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#163]
First of all this is a great software! In the newest release I noticed a small problem:

The first startup of Hydrogen is slow.
It takes a few seconds to connect to the kernel and execute the command. In previous versions this was almost instant.

If the kernel is running everything is as fast as usual.

![hydrogen](https://cloud.githubusercontent.com/assets/13285808/13070330/042725da-d48c-11e5-976d-ba488e0f0525.gif)

May be you can have a look at this.

**Comment by slavaGanzin** [comment]
I write this code on my SSD and it shines, but on my extra slow HDD it works the same as yours. Besides, for me previous version works slower than new. 

Just to clear situation, please, before ```hydrogen:run``` launch couple of times this: 
```time ipython kernelspec list --json```

And after that run hydrogen. If this will speedup this command and interface freezing will be gone - notify me here. Thanks

**Comment by lgeiger** [comment]
Thanks for the response.

I think I know where the Problem is coming from:

I have the latest version of Jupyter installed.
If I run `time ipython kernelspec list --json` I get the following warning:
```
[TerminalIPythonApp] WARNING | Subcommand `ipython kernelspec` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter kernelspec`... continue in 5 sec. Press Ctrl-C to quit now.
```
The time is `real 0m5.345s`. Notice the 5 second delay.

If I run `time jupyter kernelspec list --json` everythin is fine. The time here is `real 0m0.331s`.
