### ISSUE TITLE
Line rule (hr tag) is invisible in markdown cell

### ISSUE THREAD

**Issue by wadethestealth** [nteract/hydrogen#1633]
If markdown cell contains only '---' the outputted hr has no width

1. Create Python file with the following code
```
#%%md
# ---
```
2. Run line 2 in any way you would like
3. The result will be an `<hr>` with width 0 making it invisible

**Comment by aviatesk** [comment]
@wadethestealth 
If a markdown cell only contains `---`, it wouldn't appear, but if any other character is there, it seems to work properly:
![image](https://user-images.githubusercontent.com/40514306/59960985-ddceb080-950b-11e9-9ad8-0536cc19816d.png)

And it would be very rare case that we want to only render `---`, thus I wonder whether we should treat this as an issue.

**Comment by wadethestealth** [comment]
I am going to mark this as intended behavior based on the html5 specification where an hr tag is semantic rather than visual
