### ISSUE TITLE
Horizontal Scroll Bug

### ISSUE THREAD

**Issue by wadethestealth** [nteract/hydrogen#1644]
## The Issue
When scrolling horizontally in a multi-line result view, the atom editor scrolls horizontally as well.
This should behave like the vertical scroll, where editor scrolling is stalled until at the end/beginning of the result view.

## To Reproduce:
1. Create a `.py` file with the following code: (one long comment line + the loop)
```python
# %% markdown
# First and foremost, the Jupyter Notebook is an interactive environment for writing and running code. The notebook is capable of running code in a wide range of languages. However, each notebook is associated with a single kernel.  This notebook is associated with the IPython kernel, therefore runs Python code.
# %%
for i in range(500):
    print(2**i - 1)
```
2. Run the bottom cell.

**Comment by aviatesk** [comment]
It seems you can fix this by tweaking styles.less sheet.

I'm not sure what style is exactly the one we should modify tho.

**Comment by wadethestealth** [comment]
I'll take a look thanks @aviatesk
