### ISSUE TITLE
Command to open respective QT-console

### ISSUE THREAD

**Issue by schlichtanders** [nteract/hydrogen#166]
Feature-Request

it would be great to have a command which starts a qt-console/jupyter-process on the kernel used by hydrogen.
Extra Feature: If the qt-console/jupyter-process can optionally be embedded into atom directly, this would be nice, of course.

**Comment by rgbkrk** [comment]
Hey @schlichtanders!

Design wise, I'd prefer that we emit an event that another package can listen to for this. That Atom package can then launch the qt-console with:

```bash
jupyter qtconsole --existing /path/to/Jupyter/runtime/kernel-16113.json
```

> If the qt-console/jupyter-process can optionally be embedded into atom directly, this would be nice, of course.

As another pane within Atom with a qt-console like experience? I agree! Probably again as a different Atom package, and should definitely exist.

**Comment by schlichtanders** [comment]
Dear Kyle Kelley,

how would one distinguish the different languages?
E.g. open a qt-console for a running python-kernel and not a R-kernel,
which may run in parallel?

(note, that I lack how events work in atom - maybe my question sounds
rather senseless when having such a background).

**Comment by rgbkrk** [comment]
Generally for Jupyter spec conforming projects, a connection file is created somewhere like `~/Library/Jupyter/runtime`:

```
$ ls ~/Library/Jupyter/runtime/
kernel-20275.json      notebook_cookie_secret
```

Within that file is the information for connecting to that kernel:

```
$ cat ~/Library/Jupyter/runtime/kernel-20275.json
{
  "stdin_port": 51222,
  "ip": "127.0.0.1",
  "control_port": 51223,
  "hb_port": 51224,
  "signature_scheme": "hmac-sha256",
  "key": "17f8a27f-612c-4c63-be5f-95a718243cf6",
  "shell_port": 51220,
  "transport": "tcp",
  "iopub_port": 51221
}
```

Any frontend, including `jupyter console`, `jupyter qtconsole`, [`sidecar`](https://github.com/nteract/sidecar), [`nteract`](https://github.com/nteract/nteract), and others can use this to connect to the backing runtime/language. The rest that flows from there is the [jupyter message spec](http://jupyter-client.readthedocs.org/en/latest/messaging.html).

**Comment by schlichtanders** [comment]
thanks for explaining

**Comment by rgbkrk** [comment]
At the command line, open up `jupyter console` then run `%connect_info`:

```
$ jupyter console
Jupyter Console 4.1.0.dev

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]: %connect_info
{
  "stdin_port": 51357,
  "ip": "127.0.0.1",
  "control_port": 51358,
  "hb_port": 51359,
  "signature_scheme": "hmac-sha256",
  "key": "e45ce22b-907b-4d07-bdb1-f344efcb82d5",
  "shell_port": 51355,
  "transport": "tcp",
  "iopub_port": 51356
}

Paste the above JSON into a file, and connect with:
    $> ipython <app> --existing <file>
or, if you are local, you can connect with just:
    $> ipython <app> --existing /Users/kyle6475/Library/Jupyter/runtime/kernel-20347.json
or even just:
    $> ipython <app> --existing
if this is the most recent IPython session you have started.
```

Using that `--existing` line with the full path, open another terminal on the side and run `jupyter console` with the arguments: 

```
$ jupyter console --existing /Users/kyle6475/Library/Jupyter/runtime/kernel-20347.json
Jupyter Console 4.1.0.dev

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]: 2
Out[2]: 2

In [3]: 3
Out[3]: 3

In [4]: x = 2
```

You'll then see that they're both connected and the second one didn't have to know what language was running.

<img width="1435" alt="screenshot 2016-02-17 08 43 34" src="https://cloud.githubusercontent.com/assets/836375/13116905/9aae0b4c-d552-11e5-94cc-6e551f5e7e56.png">

**Comment by rgbkrk** [comment]
`jupyter console` can also take an argument (for the first one launched) for what language/kernel to use:

```
jupyter console --kernel=javascript
```

> thanks for explaining

No problem.

**Comment by schlichtanders** [comment]
What would the concrete atom event from hydrogen then signalize?

**Comment by rgbkrk** [comment]
Actually, looking at current day Atom APIs, seems like we need to offer [a service that other packages can consume](https://atom.io/docs/v1.5.3/behind-atom-interacting-with-other-packages-via-services). Perhaps a kernel launching service and store?

Just sketching things out here, I don't have a plan for our events. It's worth writing a spec and experimenting with it.

**Comment by schlichtanders** [comment]
I thought about it again and it seems that the `connect_info` is almost
everything what is needed to know for the qt-console-package. Having a
KERNELPATH variable or such would be enough. But ...

Unfortunately, a short description, including the actual language which is
running on that kernel does not seem to be part of this `connect_info`, or
do I miss something?

Is it possible to add language information and maybe even a short extra
description like "Hydrogen kernel" to the connection file? (Relates this
https://github.com/jupyter/jupyter_client/issues/50 to what is needed?)
Or can one extract such manually given the `connect_info` alone?

**Comment by rgbkrk** [comment]
If you connect to a kernel using the connection information and need to know the language information, you can send a [`kernel_info` request](http://jupyter-client.readthedocs.org/en/latest/messaging.html#kernel-info).

Example code from [ick, a prototype cli](https://github.com/nteract/ick/blob/master/index.js#L253-L261):

```
const enchannel = require('enchannel-zmq-backend');
const uuid = require('uuid');

function createMessage(msg_type) {
  const username = process.env.LOGNAME || process.env.USER ||
                   process.env.LNAME || process.env.USERNAME;
  return {
    header: {
      username,
      session,
      msg_type,
      msg_id: uuid.v4(),
      date: new Date(),
      version: '5.0',
    },
    metadata: {},
    parent_header: {},
    content: {},
  };
}

const identity = uuid.v4();
// Passing the connect_info to create a connection to the SHELL socket
const shell = enchannel.createShellSubject(identity, connectInfo);

const kernelInfoRequest = createMessage('kernel_info_request');
const kernelReply = shell.filter(msg => msg.parent_header.msg_id === kernelInfoRequest.header.msg_id)
                         .map(msg => msg.content);

kernelReply.subscribe(content => {
  console.log(content.banner);
});

shell.next(kernelInfoRequest);
```

What do you need to know the language for before launching the Qt Console?

**Comment by schlichtanders** [comment]
I think about a atom package "launch jupyter qt-console" with an
atom-command like 'qt-console: connect' which searches through paths
defined the package's settings and opens a respective list of available
kernels to connect. You pick one and it opens a qt-console (hopefully with
the option to include it directly in atom)

The concrete list should of course include short readable descriptions
making clear which kernel is meant.
The concrete language seems to be one good identifier for differentiating
especially within Hydrogen.

However for completeness it would be great to have also additional
descriptions, for example that the kernel was indeed launched by Hydrogen.
Even better, it would be great if apps would specify a short identifying
description of the concrete kernels they started.
Do you know how to get such additional information?

**Comment by rgbkrk** [comment]
Ah, I see. In the short term case I think that means we need to implement a [service](http://blog.atom.io/2015/03/25/new-services-API.html) for kernels which would store a lot more metadata. This seems like a good package for atom-notebook to use as well.

In the long term case, we would need the jupyter spec to include more information in the connection info to be compatible. A little bit of this was done upstream, https://github.com/jupyter/jupyter_client/pull/96, amusingly at my request in https://github.com/jupyter/jupyter_client/issues/50. We'd need adhere to the same standard within Hydrogen's code base.

> However for completeness it would be great to have also additional descriptions, for example that the kernel was indeed launched by Hydrogen. Even better, it would be great if apps would specify a short identifying description of the concrete kernels they started.

Such information is not currently available. We'd have to track it ourselves if we really need it.

**Comment by schlichtanders** [comment]
according to this https://github.com/ipython/ipykernel/pull/93 it should
also be possible to add own extra keys to the connection file directly, or
do I miss something?

**Comment by m-guggenmos** [comment]
This would be an amazing feature indeed. Currently I do this manually by calling `ipython console --existing /path/to/kernel-XXX.json` within my atom-embedded terminal-plus console. 

I wonder if, until a bigger solution arrives, one could write a simple atom package "connect-to-hydrogen-kernel-from-terminal". This package would connect to the kernel of the currently active code file using the terminal e.g. provided by terminal-plus. The only information this package would need from hydrogen is the path to the respective kernel file. Plus a user-provided info for "command" (something like 'ipython console --existing {kernelPathOfActiveFile}' in my example case of ipython).

**Comment by lgeiger** [comment]
@schlichtanders @m-guggenmos In version `v0.13.0` we added a command to copy the path to the connection file. In order to allow connecting to the same kernel via `jupyter console --existing <path to connectionfile>`.

**Comment by CYHSM** [comment]
Thanks for that! If others like me who use terminal-plus want to open it directly on opening the console, just use this auto run command to open the latest ipython console (after copying path with hydrogen:copy....) : 
`jupyter console --existing /run/user/1000/jupyter/$(cd /run/user/1000/jupyter ; (ls -t | head -n1);)`

**Comment by lgeiger** [comment]
@schlichtanders @m-guggenmos @CYHSM I created a new package called [`hydrogen-launcher`](https://atom.io/packages/hydrogen-launcher) which allows can spawn a new terminal with a `jupyter console` or `qtconsole` connected to the current running Hydrogen kernel.
