### ISSUE TITLE
MathJax can't get rendered more than twice within Markdown result feature

### ISSUE THREAD

**Issue by aviatesk** [nteract/hydrogen#1669]
### Description

With our [markdown result rendering feature](https://github.com/nteract/hydrogen/pull/1628), we can't render MathJax for twice:
![image](https://user-images.githubusercontent.com/40514306/59945199-d5da2680-94a1-11e9-803a-e8fe658fa3f6.png)

### Additional Info

This behaviour doesn't happen if we use `%%markdown` magic within IPython:
![image](https://user-images.githubusercontent.com/40514306/59945288-189bfe80-94a2-11e9-91d0-c4fe0c11f52e.png)

**Comment by wadethestealth** [comment]
To see a more in depth version of the issue please look at nteract/nteract#4461

**Comment by wadethestealth** [comment]
Fixed via nteract/nteract#4586
