### ISSUE TITLE
To detect your current Python install you will need to run:  python -m pip install ipykernel python -m ipykernel install --user

### ISSUE THREAD

**Issue by ald0405** [nteract/hydrogen#1674]
On a windows 10 laptop. 
I do apologise for how basic this question is. 
But where am I meant to run

```
python -m pip install ipykernel
python -m ipykernel install --user
```

I've changed the name of the script to .py and set the language from the drop down menu at the bottom to python

> I still keep getting the message
> 
> 
> Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.
> 
> To detect your current Python install you will need to run:
> 
> 

```
python -m pip install ipykernel
python -m ipykernel install --user
```

**Comment by wadethestealth** [comment]
Hydrogen should automatically detect kernels installed on your disk. These are the steps you should follow:
1. Have Python installed
2. Using pip install jupyter (ipykernel comes with it) or ipykernel
3. Run ipykernels install command
4. Open atom and go into the package settings of hydrogen (click packages and then hydrogen)
5. Make sure you set up a language mapping if you require one.
6. open a .py file, and make sure your grammar is set in the bottom right hand corner of atom
7. try to run a line via `hydrogen:run`

**Comment by ald0405** [comment]
1) I have installed anaconda, is that sufficient?
2)  I don't even know here to run `pip3 install jupyter`
3) Where do I run this?
4) & 5) I have messed around the with the language mapping but unsure exactly what to put in the fields

**Comment by wadethestealth** [comment]
Since you have anaconda you should be able to go to your windows search and open anaconda prompt and use pip inside there

**Comment by ald0405** [comment]
It keeps giving errors

`pip install juypter`
Collecting juypter
  Could not find a version that satisfies the requirement juypter (from versions: )
No matching distribution found for juypter

`pip install --upgrade pip
`Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\ald04\\AppData\\Local\\Temp\\pip-uninstall-fxm00eqq\\pip.exe'

**Comment by wadethestealth** [comment]
Have you read the directions for installing kernels yet. https://nteract.io/kernels
There is a section for using anaconda or python environments or globally. 

For global, If you use anaconda you may have to update your environment variable called path to include your python installation from conda. 

https://jupyter.org/install
This is how to install jupyter, which you should already have. Try running jupyter notebook and seeing if it works. 
If it does screenshot the error you get when you try to use hydrogen.

**Comment by wadethestealth** [comment]
Have you read the directions for installing kernels yet. https://nteract.io/kernels
There is a section for using anaconda or python environments or globally. 

For global, If you use anaconda you may have to update your environment variable called path to include your python installation from conda. 

https://jupyter.org/install
This is how to install jupyter, which you should already have. Try running jupyter notebook and seeing if it works. 
If it does screenshot the error you get when you try to use hydrogen.

**Comment by wadethestealth** [comment]
I am going to close this as the linked docs should have your answers. If you still have trouble or errors, you may open a new issue.
