### ISSUE TITLE
Hydrogen not able to run code - "The system cannot find the path specified", kernel path is ok

### ISSUE THREAD

**Issue by isajacas** [nteract/hydrogen#1675]
**Description:**
I cannot run any python code on Atom/Hydrogen.
I got the same error warning as Issue #1432 (Hydrogen not able to run code - "The system cannot find the path specified")
Kernel's path is ok, and dev console doesn't show any problem

**Steps to Reproduce:**

1. Open .py on Atom (it works on cmd)
2. Try to run "print('Hello')" or "x=2"

**Versions:**
OS: Windows 10
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Logs:**

![2019-06-24](https://user-images.githubusercontent.com/48598714/60057885-2aed8680-96b4-11e9-93ca-2b25a7b44cb8.png)
![2019-06-24 (1)](https://user-images.githubusercontent.com/48598714/60057886-2c1eb380-96b4-11e9-805e-ff1dc41974af.png)

**Comment by isajacas** [comment]
Thanks in advance!

**Comment by wadethestealth** [comment]
Did you try the solution in the issue you referenced?

**Comment by wadethestealth** [comment]
Optionally you could also try https://github.com/jupyter/notebook/issues/2301#issuecomment-383408052

**Comment by isajacas** [comment]
Yes, wadethestealth. I try both cmd solutions that appear on the Issue referenced, and I got the same results that its author.

**Comment by wadethestealth** [comment]
It seems like anyone who runs the code I typed above. It fixes it immediately, but you are saying the install command does nothing?

**Comment by isajacas** [comment]
Apparently, there was a problem with my cmd prompt! 
I recently type "python -m ipykernel install --user" and it worked perfectly!!! Thank you so much

**Comment by UltraVioletCoin** [comment]
https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror, this worked for me.
