### ISSUE TITLE
Time module not working well in Hydrogen

### ISSUE THREAD

**Issue by AstrickHarren** [nteract/hydrogen#1681]
Hey devs:
Somethings happening again like this. 
The example is not working well:
```python
import time

for i in range(10):
    time.sleep(1)
    print(i)
```
Regular inline result view or dock view are both not behaving well: they all give the first 1 or 2 output then wait another 8 secs and give out all the output at once. Same thing happens with `tqdm`.

OS: MacOS Mojave 10.14.2
atom: 1.38.2
python: 3.7.0
tqdm: 4.28.1
hydrogen: 2.10.0

thx.

_Originally posted by @AstrickHarren in https://github.com/nteract/hydrogen/issues/1293#issuecomment-506135743_

**Comment by BenRussert** [comment]
We have an issue with async stream output as of the latest release. #1678 has more discussion on this.
