### ISSUE TITLE
atom/hydrogen wont run python 

### ISSUE THREAD

**Issue by OliverFishCode** [nteract/hydrogen#1684]
I am using python version 3.7.3 and ipykernel 5.1.. Atom and hydrogen recognize kernel, but when I try to run the code this is the error I get. Python.exe, scripts and anaconda folder are all in my path.

![image](https://user-images.githubusercontent.com/36993512/60308278-f8829a00-98fc-11e9-9d51-d0e031d009c0.png)
![image](https://user-images.githubusercontent.com/36993512/60308298-089a7980-98fd-11e9-9d19-7510e99ffdb6.png)

**Comment by wadethestealth** [comment]
All related issues: 
#1684, #1665, #1550, #1517, #1500, #1405 
Solutions:
#1405
https://github.com/ContinuumIO/anaconda-issues/issues/10422#issuecomment-448185070
https://stackoverflow.com/questions/52821162/jupyter-notebook-failed-to-load-dll
