### ISSUE TITLE
Hydrogen not appearing in packages

### ISSUE THREAD

**Issue by kescobo** [nteract/hydrogen#169]
While trying to solve #161 I uninstalled Hydrogen, then got response that v0.7 has the feature I need so I went to reinstall, now it refuses to work or even show up in packages list. I've tried installing through app, and with `PYTHON=python2.7 apm install hydrogen`. In either case `apm list` shows `Hydrogen@0.7.0` in my package list, but when I open the app, it's not listed under community packages.

Also strange, when I have Hydrogen installed, the "Deprecated Packages" section in the app hangs on "loading packages", but when I uninstall Hydrogen that goes away and I have no deprecated packages. Did I screw something up in the uninstall so Atom now thinks the package is broken?

**Comment by rgbkrk** [comment]
Hard to tell without logs, though I'd be a bit afraid of our transition to nteract mucking up Atom metadata. Have you fully restarted Atom?

**Comment by slavaGanzin** [comment]
Try to drop ```~/.atom/packages/Hydrogen``` and reinstall. If this wouldn't help try to reinstall atom - they broke things between versions sometimes.

**Comment by kescobo** [comment]
Uninstalling from command line didn't work. Re-install of Atom worked, but I add to get rid of `~/.atom/ as well. Irritating, but it's working now.

**Comment by rgbkrk** [comment]
Thanks for getting through it @kescobo.
