### ISSUE TITLE
Explanation of the Hydrogen Wiki

### ISSUE THREAD

**Issue by wadethestealth** [nteract/hydrogen#1693]
@n-riesco I know that you haven't contributed in a while, but I would still love to knock off some of the things you original developers left as to-do's/enhancements. The only problem is that for most of it I am unsure of what it all means. Could you provide some explanation on how to abstractly do those tasks or why its beneficial?

We kind of already have rich completions and the plugin api, and we are working on writing test, but what about the other stuff.

**Comment by n-riesco** [comment]
The wiki page is obsolete (the latest incarnation of a roadmap was issue #657).

I've skimmed quickly through all the goals, and here's what I remember/understand:
- **rich completions**: as far as I know, this is an experimental feature (not part of the Jupyter messaging protocol yet).
- **plugin API**: this has been done (@nikitakit led this work)
- **kernelspecs**: done, this is already one of Hydrogen's dependencies
- **Replace `jmp` with `enchannel-zmq-backend`, `enchannel-zmq` or `rx-jupyter`**: @rgbkrk would know better which of nteract's libraries is the most appropriate.
- **Add console support**: not done yet (unless I missed it); this could be part of Hydrogen or a plugin.

All the other items seem to have already been done to some degree. Please, let me know if I missed any.

---

I noticed there were some efforts to move nteract to Typescript, are there any plans for Hydrogen?

**Comment by wadethestealth** [comment]
@n-riesco we considered migrating but we wanted to wait till after the major. Now that we just released I may bring it up again.

**Comment by aviatesk** [comment]
@n-riesco Thanks for your help ! 😄
