### ISSUE TITLE
Q: autocomplete in linux?

### ISSUE THREAD

**Issue by kingjr** [nteract/hydrogen#170]
Hi,

Is there a way to have an autocomplete that behaves in the same way as the `tab` in ipython. Eg.
`foo.` + `tab` => gives `foo` attributes.

Thanks for the beautiful package!

**Comment by slavaGanzin** [comment]
Read this: https://atom.io/docs/latest/behind-atom-keymaps-in-depth
Then press ctrl-. to toggle keymap-resolver, press ctrl-space (default binding for autocomplete) and map to tab your command:

```
"tab": "automcomplete-plus:activate"
```
