### ISSUE TITLE
Support VegaLite3, Vega4 and Vega5

### ISSUE THREAD

**Issue by Mikeymice** [nteract/hydrogen#1700]
### Prerequisites

* [ x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description
the altair chart was not rendering and result in `<VegaLite 3 object>`

### Steps to Reproduce

1. I have Hydrogen 2.10.3 installed
2. I installed the altair as the following
```
pip install -U altair vega_datasets jupyterlab
```
i also install vega in conda 
```
conda install -c conda-forge vega
```
3. 

```
import altair as alt
from vega_datasets import data
iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```

return the following

<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

### Versions

OS version:
macOS Mojave 10.14.5

> `atom --version`

```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

> `apm --version`

```
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 3.6.8
git 2.20.1
```

Hydrogen version:

[Your Hydrogen's version]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [X ] hydrogen-python
- [ X] Hydrogen Launcher
- [ X] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

[A clear and concise description of what you expected to happen.]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
Vegalite 3 is not yet supported. However I believe over at nteract/nteract they began to implement the Vegalite 3, which if is finished we can easily use here. I'll keep you updated @Mikeymice

**Comment by Mikeymice** [comment]
thanks for the quick response!!

I am a bit confused by the answer because the example provided on the hydrogen 

[static plot example](https://nteract.gitbooks.io/hydrogen/docs/Usage/Examples.html#static-plots)

so which version of vegalite is currently supported by hydrogen?

**Comment by wadethestealth** [comment]
Vegalite 1-2 and Vega 2-3

**Comment by Mikeymice** [comment]
Thank you so much!!

I used the following code and it is working now :D 

```
import altair.vegalite.v2 as alt
from vega_datasets import data
iris = data.iris()

test =alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)


```

**Comment by wadethestealth** [comment]
Awaiting nteract/nteract#4442

**Comment by mattbit** [comment]
I don’t know if I’m doing something wrong but I still have problems visualising Altair plots in Hydrogen v2.12.0.

The simple demo code
```python
import altair as alt
from vega_datasets import data

cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```

gives me the usual
```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

Trying to use the old vegalite version with `import altair.vegalite.v2 as alt` doesn’t work anymore and returns `<VegaLite 2 object>`.

The same code works fine in the last version of nteract. What am I missing?

**Comment by wadethestealth** [comment]
@mattbit Its not you its us. I am going to open a new issue tracking this.

**Comment by phromo** [comment]
@wadethestealth do you have a reference to the new issue? any known workarounds?

**Comment by phromo** [comment]
Quick 'n dirty workaround: enable the png renderer and use it instead (requires selenium)

```
alt.renderers.enable('png')
```

**Comment by wadethestealth** [comment]
Unfortunately there are no work arounds to this issue. I haven't opened a new one yet, I had forgotten. I will open it soon though I promise.

**Comment by wadethestealth** [comment]
#1771 @phromo
