### ISSUE TITLE
No kernel for grammar JSON found

### ISSUE THREAD

**Issue by jesusloplar** [nteract/hydrogen#1704]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

I have had a hard time trying to run JSON files with the Hydrogen commands. I have researched several reports, but none of them have worked for me. It may also be because I didn't apply them correctly.

### Steps to Reproduce

1. I have everything set up to work. Whenever I try to run a JSON file or a JSON command in, it doesn't allow me to run because it says: "No kernel for grammar JSON found."
2. I have put the text of jupyter kernelspecs list in the mapping language, but it is still not working out.
3. I have also reinstalled ipython and jupyter, and tried to run within a virtual environment.
4. It may also be that I didn't implement the instructions ok.

I would really appreciate if you could help me.

### Versions

OS version:
ProductName:	Mac OS X
ProductVersion:	10.14.5

> `atom --version`

```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

> `apm --version`

```
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.16
git 2.20.1
```

Hydrogen version:

2.10.3
### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [x] hydrogen-python
- [x] Hydrogen Launcher
- [x] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

Kernel for grammar JSON to be found.

### Screenshots

<img width="1552" alt="Screenshot 2019-07-10 at 10 12 21" src="https://user-images.githubusercontent.com/46565164/60965731-70de5780-a30e-11e9-92cc-93633c2de71b.png">
<img width="1552" alt="Screenshot 2019-07-10 at 10 12 05" src="https://user-images.githubusercontent.com/46565164/60965737-75a30b80-a30e-11e9-8c65-fd1475c3d1b1.png">

Thanks you so much in advance for your help!! Really appreciate.

**Comment by wadethestealth** [comment]
Ipython (the kernel which you have installed) uses python. Therefore to run code in that kernel you must use python code. Please go to our docs and look at examples of python code. Also read the getting started. If you wish to view Json you can still use python code see the examples for that

**Comment by wadethestealth** [comment]
Also I want to note that you don't put kernel specs into language mapping. In language mapping you just use the kernel name and the grammar name in atom.

**Comment by jesusloplar** [comment]
I haven't understood the whole thing from the beginning. The thing was that the other day I was with a .ipynb file which you can find [here](https://github.com/CrazyDaffodils/Interactive-Choropleth-Map-Using-Python/tree/master/bokeh-app).

I had understood that json files could work within a python code (I think I've seen that somewhere). I read that ipynb couldn't work within hydrogen - as the file of the example. So, as I am beginning with these things and I wanted to have everything settled in Atom in case I would need it in the future, I didn't understood why the json format couldn't work within hydrogen.

Just found out that I should have imported the json library and use the python format for the file🥵. So simple was the answer that I've come to realise now after at least 5h trying to solve.

Thanks you so much for your help!! you've made me realise of a few things I should've researched more consciously.

<img width="1552" alt="Screenshot 2019-07-10 at 15 26 29" src="https://user-images.githubusercontent.com/46565164/60977320-25847300-a327-11e9-8e22-0b937e46ae4f.png">

**Comment by jesusloplar** [comment]
> Also I want to note that you don't put kernel specs into language mapping. In language mapping you just use the kernel name and the grammar name in atom.

I've put them because between all the issues I've seen related with this issue about no grammar found, the "language mappings" section was the thing most similar to kernel spec - which I couldn't find anywhere.

Thanks for the clarification @wadethestealth 😁😁

**Comment by wadethestealth** [comment]
I should really update the docs about language mappings making it more specific however we do support .ipynb now. use the `hydrogen:import-notebook` command in the atom command palette

**Comment by wadethestealth** [comment]
It will take all your code and import it into python code

**Comment by jesusloplar** [comment]
I have tried to use the import-notebook. This appeared. Any idea what may it be?

<img width="1552" alt="Screenshot 2019-07-10 at 16 11 57" src="https://user-images.githubusercontent.com/46565164/60981061-89119f00-a32d-11e9-80c8-551e93b63191.png">

**Comment by wadethestealth** [comment]
@jesusloplar since I created this warning yes. I know exactly what it means. It means that the structure of your notebook is not purely Json. .ipynb files only contain Json if you used the file you posted above you need to remove line 1-3 the 4th line should be your first line.
