### ISSUE TITLE
Installation on Manjaro - Archlinux failing

### ISSUE THREAD

**Issue by darshanpandit** [nteract/hydrogen#1707]
### Description:
Installation/Update of Hydrogen is failing after atom-updates. 

### Versions:
apm  2.3.1
npm  6.10.0
node 11.15.0 x64
atom 1.38.2
python 2.7.16
git 2.22.0

### OS:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4

### Logs:
src/err.cpp:389:10: fatal error: libunwind.h: No such file or directory
 #include <libunwind.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:3360: src/src_libzmq_la-err.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:4044: all-recursive] Error 1
child process exited with code 2
../binding.cc:28:10: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
          ^~~~~~~
compilation terminated.
make: *** [zmq.target.mk:101: Release/obj.target/zmq/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by BenRussert** [comment]
We get issues from arch users from time to time. I know nothing about arch, but wonder if there is an official release of atom the way there is for debian etc. We cant support versions of node or electron if atom doesnt support them.

**Comment by dragonator4** [comment]
The simplest solution to this issue is to use the [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) package from AUR, instead of the package in the official repos. It keeps atom as close to the upstream as possible, avoiding such issues.

**Comment by wadethestealth** [comment]
Going to mark this as closed, since this is out of Hydrogen's control. We recommend as stated above that you use the packages from AUR, as them seem to prevent many issues Archlinux users have with atom.
