### ISSUE TITLE
Enable Notebook Auto-Import is selected but doesn't auto-import .ipynb files

### ISSUE THREAD

**Issue by gbstan** [nteract/hydrogen#1719]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Although the Hydrogen call to "Hydrogen: Import Notebook" works as expected, the setting option "Enable Notebook Auto-Import" doesn't for some reason.

### Steps to Reproduce

1. Make sure that the setting "Enable Notebook Auto-Import" is ticked (selected to yes)
2. Select a ipynb file in the Project file view
3. Atom opens the file as a JSON file and not as a converted Notebook file

### Versions

OS version: 10.14.6
[Your OS's version]

> `atom --version`

```
Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

> `apm --version`

```
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0
python 3.7.3
```

Hydrogen version:

2.10.3

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Expected behavior

.ipynb files should automatically be auto-imported.

**Comment by wadethestealth** [comment]
If hydrogen is not active, it is impossible to auto import notebooks. You can press Ctrl + p and type hydrogen to see all the activation commands. You can run any of these commands to activate hydrogen. Once hydrogen is activated you can click on a ipynb file to import. One of this activation commands is import notebook. So the first notebook you could import via the notebook command and then click every notebook like normal afterwards
