### ISSUE TITLE
Introducing ipywidgets in Hydrogen

### ISSUE THREAD

**Issue by pepicello** [nteract/hydrogen#1721]
It would be great if ipywidgets could be integrated in Hydrogen, like the below:

``` python
from ipywidgets import interact
df = pd.DataFrame(np.random.rand(100, 10))
@interact
def test_head(x=10):
    return df.head(x)
```

![ipywidg](https://user-images.githubusercontent.com/15961048/61868082-8b98fa80-aed0-11e9-9559-c4c244164f8a.gif)

So far, the code works in Atom, but it only shows the interactive object:

```python
interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), Output()), _dom_classes=('widget-… 
```

Thanks for the great work!

**Comment by wadethestealth** [comment]
See #27
