### ISSUE TITLE
Hydrogen cannot be loaded because it was compiled for an earlier version of atom.

### ISSUE THREAD

**Issue by H4wk-3yE** [nteract/hydrogen#1723]
### Description
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

The module '\\?\C:\Users\farha\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 57. This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).

### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 3.7.3
git
visual studio

OS version:
Windows 10 1903

> `atom --version`

```
1.39.1
```

> `apm --version`

```
2.2.4
```

Hydrogen version:
```
 2.10.3
```

**Comment by tan10vir** [comment]
Try uninstalling & re-installing the hydrogen package.

**Comment by H4wk-3yE** [comment]
> Try uninstalling & re-installing the hydrogen package.

Did that already.

**Comment by tan10vir** [comment]
Try to delete the hydrogen package from ```.atom/packages/``` and then re-install hydrogen.

**Comment by wadethestealth** [comment]
@tan10vir this is not a normal install error

**Comment by wadethestealth** [comment]
There is only way we have been known to fix this issue is using the red debug button in the bottom right corner provided by atom. Check the troubleshooting guide for visuals

**Comment by H4wk-3yE** [comment]
I don't know if I am right but I think the bug description clearly says that atom now uses Node.js version 64  and hydrogen uses v 57. So I think hydrogen needs an update.

**Comment by aviatesk** [comment]
Yeah that's why you have to _rebuild_ your Hydrogen.

Have you tried that ?

**Comment by wadethestealth** [comment]
Yeah no you have to update it by rebuilding using the red bug.

**Comment by H4wk-3yE** [comment]
> Yeah that's why you have to _rebuild_ your Hydrogen.
> 
> Have you tried that ?

And how exactly I _rebuild_ hydrogen. I have tried reinstalling and deleting the from .atom/packages.

**Comment by wadethestealth** [comment]
Use the red build in the troubleshooting guide

**Comment by wadethestealth** [comment]
Bug

**Comment by H4wk-3yE** [comment]
> Use the red bug in the troubleshooting guide
I dont know where the troubleshooting guide is but the description I gave for the problem is from that red bug,

**Comment by wadethestealth** [comment]
See the visuals in the link above

**Comment by H4wk-3yE** [comment]
> See the visuals in the link above

Fixed, The rebuild package button was not visible because of the theme I was using.
