### ISSUE TITLE
Adding Titles

### ISSUE THREAD

**Issue by ahsen1402** [nteract/hydrogen#1737]
Hi,

I am unable to add title to the plots using the following code:

```
n, bins, patches=plt.hist(np.asarray(dummy_predictions_team), color = 'blue', edgecolor = 'black',
bins = int(30),density=True)
plt.title(i)
plt.show()
```
Am I missing something?

**Comment by wadethestealth** [comment]
This code really isn't enough to debug your code but title is meant to be a string. Unfortunately this isn't a hydrogen issue as titles do work on plots in hydrogen. All I can say is ask for help over at plotly. They have a wonderfully active forum for help too. You could also refer to the plotly documentation for help too.

**Comment by aviatesk** [comment]
FYI, it's not a plot from plotly, but from matplotlib.

If you happen to customise style via `plt.style.use`, the title can appear like disappeared.

But in anyway, it's not the talk of Hydrogen.
