### ISSUE TITLE
BUG: Check ticks above search panel

### ISSUE THREAD

**Issue by kingjr** [nteract/hydrogen#174]
I'm running with Ubuntu 14.04 and atom 1.0.5 and see the tick marks above the search panel:

![bug_hydrogen](https://cloud.githubusercontent.com/assets/4881164/13256646/86169fd4-da19-11e5-878c-b144564bc5e5.png)

**Comment by lgeiger** [comment]
I can reproduce this problem. In the meantime you can add
```
.bottom{
    z-index: 4;
}
```
to your stylesheet to fix this issue.

**Comment by slavaGanzin** [comment]
@lgeiger May I advice you to create separate PR for separate issues.
It easy to merge this: https://github.com/lgeiger/hydrogen/commit/d784006c0987c274ea463f0e9f734017d3c7422e
But not this: https://github.com/nteract/hydrogen/pull/175

**Comment by lgeiger** [comment]
My bad, I'll create an separat PR tomorrow.
