### ISSUE TITLE
Install fails on Windows 10 with anaconda (user installation)

### ISSUE THREAD

**Issue by vincenzooo** [nteract/hydrogen#1740]
Install fails. After internet search, I tried to set PATH and PYTHON env variables, but it didn't work. calling python or %PYTHON% correctly opens the interpeter, and the exe is in the position indicated in the log "C:\Users\kovor\Anaconda3\python.exe".

This is output:

Installing “Hydrogen@2.10.3” failed.Hide output…

> zeromq@5.1.0 install C:\Users\kovor\AppData\Local\Temp\apm-install-dir-119715-14368-1gtlzoq.48c2\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 platform=win32)

Downloading libzmq for Windows
Download finished

C:\Users\kovor\AppData\Local\Temp\apm-install-dir-119715-14368-1gtlzoq.48c2\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\kovor\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kovor\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\kovor\Anaconda3\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\kovor\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\kovor\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\kovor\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\kovor\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kovor\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kovor\AppData\Local\Temp\apm-install-dir-119715-14368-1gtlzoq.48c2\node_modules\Hydrogen\node_modules\zeromq
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\kovor\AppData\Local\Temp\apm-install-dir-119715-14368-1gtlzoq.48c2\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vega-themes@2.3.2 requires a peer of vega@* but none is installed. You must install peer dependencies yourself.
npm WARN vega-lite@3.4.0 requires a peer of vega@^5.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-119715-14368-1gtlzoq.48c2 No description
npm WARN apm-install-dir-119715-14368-1gtlzoq.48c2 No repository field.
npm WARN apm-install-dir-119715-14368-1gtlzoq.48c2 No README data
npm WARN apm-install-dir-119715-14368-1gtlzoq.48c2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kovor\.atom\.apm\_logs\2019-08-15T00_15_55_930Z-debug.log

**Comment by aviatesk** [comment]
The issue you're facing seems to be same to the one reported in #1738, thus please refer to it.
The temporal fix is just to downgrade Atom (the steps are described in the issue)
