### ISSUE TITLE
Cannot install hydrogen all of a sudden

### ISSUE THREAD

**Issue by dshin8** [nteract/hydrogen#1741]
I used hydrogen until this evening, where I had to reinstall the package. 
But, for some reason I cannot below is the log I get: 

![image](https://user-images.githubusercontent.com/54131313/63075088-6101f680-befe-11e9-80b4-dde697a74c7a.png)

At this point, after trying almost everything that I can find online, I am super frustrated. 
Can someone please help me. I am using my home network. 

Please help me use the program I love ..

**Comment by aviatesk** [comment]
The issue you're facing seems to be same to the one reported in #1738, thus please refer to it.
The temporal fix is just to downgrade Atom (the steps are described in the issue)
