### ISSUE TITLE
Delayed/failed run

### ISSUE THREAD

**Issue by warnerwarner** [nteract/hydrogen#1753]
Whenever I try to run a single or multiple lines using hydrogen I'll find that on the first attempt the run will fail and I'll get an 'x' next to the line. If I then attempt to run a different line the first line will start running again, and will take an super long time even for simple functions. Its got the feeling that something is hanging and if I try to run another line it will often prompt the currently running lines to finish. It will also start running the failed lines if I interact with atom in anyway (click on a menu item).

**Comment by aviatesk** [comment]
Follow the issue report steps described here: https://github.com/nteract/hydrogen/blob/master/.github/ISSUE_TEMPLATE/bug_report.md ,
otherwise we can't help you in any meaningful way.

Feel free to reopen this if you prepare the required infos.
