### ISSUE TITLE
Hydrogen not working on atom python

### ISSUE THREAD

**Issue by aseem-hegshetye** [nteract/hydrogen#1754]
I installed hydrogen on atom. Previously it used to work. But then I perhaps uninstalled one of my many virtual env and now it has stopped working. It doesnt give any error but it doesnt show a tick mark next to the line I execute. I have updated my Atom and Hydrogen.

**Comment by wadethestealth** [comment]
Did you check the console? Are you using the shortcut for run line ie shift and enter?

**Comment by aseem-hegshetye** [comment]
Yes I used the correct shortcut but I couldnt see any output
![atom hydrogen not working](https://user-images.githubusercontent.com/5171444/64083202-2ad7bb80-cce1-11e9-918b-e5468977dc01.png)

**Comment by wadethestealth** [comment]
Have you tried running other lines?

**Comment by wadethestealth** [comment]
Also if you hit Ctrl + shift + P and type hydrogen do you see and results

**Comment by aseem-hegshetye** [comment]
Yes I tried running other lines and it still doesnt work. 
Yes I see hydrogen when I do ctrl+shift+p and type hydrogen.
Is there some jupyter kernel that I need to seperately install? I reinstalled hydrogen and it still doesnt work

**Comment by wadethestealth** [comment]
Yes you need a jupyter kernel to run code, but hydrogen should indicate you don't have a kernel installed.

**Comment by aseem-hegshetye** [comment]
I restarted atom and now I see the error of kernel not found. But when I do `python -m pip install ipykernel` My terminal says kernel already installed.
![kernel not found error](https://user-images.githubusercontent.com/5171444/64084448-359a4c80-ccf1-11e9-96f7-10559c381cc3.png)

**Comment by wadethestealth** [comment]
Can you do `jupyter kernelspec list --json` in terminal and let me know the output?

**Comment by aseem-hegshetye** [comment]
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/home/aseem/.local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/home/aseem/anaconda3/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}

**Comment by wadethestealth** [comment]
I am unsure of what could be failing here. I am assuming there is a problem with kernel response. @benrussert @aviatesk how should we go about this now.

**Comment by aseem-hegshetye** [comment]
![autopep8 error](https://user-images.githubusercontent.com/5171444/64091704-00a0f080-cd17-11e9-8fd2-e0ce78116c9b.png)
Now I also get this autopep8 error when I try to save a .py file. I have **beautify** on which uses autopep8. I am using a seperate venv for atom. I install `pip install autopep8` in that venv, but I still get the error
![atom venv](https://user-images.githubusercontent.com/5171444/64091734-3940ca00-cd17-11e9-80f8-ec75482d33e4.png)

**Comment by wadethestealth** [comment]
@aseem-hegshetye 
Try reading this issue thread and seeing if it helps.
https://github.com/nteract/hydrogen/issues/1074

**Comment by wadethestealth** [comment]
for autopep error I recommend insuring you have followed the correct installation steps as it is likely more than just a pip command

**Comment by aseem-hegshetye** [comment]
I removed venv package from atom and then did `pip install autopep8` not in any virtual env. It took care of autopep8 error

**Comment by wadethestealth** [comment]
Now you need to rebuild hydrogen. You can find pictures of how to do it in our troubleshooting guide on our git books website or you can click the red bug in the bottom right hand corner and then hit rebuild.

**Comment by wadethestealth** [comment]
I believe this to be solved, and there has also been no update, so I am closing.

**Comment by arcayn9** [comment]
Hey, 
I'm receiving a different kind of an error. I did follow all the steps mentioned above, but I'm stuck at this point.
![image](https://user-images.githubusercontent.com/46439109/80419531-f14e6300-88f6-11ea-97af-b64bba00a08e.png)

**Comment by saif-shehata** [comment]
Hi, I've installed Hydrogen on Atom for the first time, but it doesn't seem to be working at all. I'm quite new to this, so would really appreciate your help, thanks.

![atom_hydrogen_error](https://user-images.githubusercontent.com/7839163/93447269-849e2a00-f8d2-11ea-9b32-8ddc13e25fdf.jpg)
