### ISSUE TITLE
hydrogen stops after choosing between different envs

### ISSUE THREAD

**Issue by nosratullah** [nteract/hydrogen#1757]
<img width="459" alt="Screen Shot 2019-09-02 at 18 33 05" src="https://user-images.githubusercontent.com/13776994/64120033-71e0b200-cdb0-11e9-86a8-e324a76376cd.png">

**Comment by wadethestealth** [comment]
We are going to need more information. Do you mind filling out the issue template?

**Comment by nosratullah** [comment]
sure.
thanks
