### ISSUE TITLE
failed to load connection file

### ISSUE THREAD

**Issue by nosratullah** [nteract/hydrogen#1758]
### Prerequisites

* [ ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

[Description of the bug]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

OS version:
[macOS Mojave 10.14.6]

> `atom --version`

```
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

```

> `apm --version`

```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 3.7.3
git 2.20.1

```

Hydrogen version:

[2.12.0]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

[A clear and concise description of what you expected to happen.]

### Screenshots

<img width="459" alt="Screen Shot 2019-09-02 at 18 33 05" src="https://user-images.githubusercontent.com/13776994/64120784-63939580-cdb2-11e9-8c30-5d293a09ceff.png">

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
Can you fill out the steps to reproduce? We need to know what you did inside and outside atom to get this error

**Comment by wadethestealth** [comment]
Stale
