### ISSUE TITLE
Unable to install hydrogen with apm in Atom 1.40.1

### ISSUE THREAD

**Issue by coroa** [nteract/hydrogen#1762]
### Prerequisites

* [X] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [X] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Unable to install hydrogen with `apm` on `atom` version 1.40.1, as well as 1.40.1-beta1, while it works for 1.39.1.

Probably not related to #1738.

Problem also appears for other packages with a `postinstall` script, thus I originally filed an issue on Atom itself (https://github.com/atom/atom/issues/19866), but was asked to create downstream issues instead. Related issue for atom-ink (https://github.com/JunoLab/atom-ink/issues/212).

### Steps to Reproduce

1. Atom 1.40.1
2. `apm install hydrogen` fails with
```
➜  ~ grep -E "[0-9]+ (warn|error)" /home/coroa/.atom/.apm/_logs/2019-09-03T09_31_49_440Z-debug.log
10982 warn enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11983-9676-fv0chj.tnbh/package.json'
10984 warn react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
10985 warn apm-install-dir-11983-9676-fv0chj.tnbh No description
10986 warn apm-install-dir-11983-9676-fv0chj.tnbh No repository field.
10987 warn apm-install-dir-11983-9676-fv0chj.tnbh No README data
10988 warn apm-install-dir-11983-9676-fv0chj.tnbh No license field.
10996 error code ELIFECYCLE
10997 error errno 134
10998 error zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
10998 error Exit status 134
10999 error Failed at the zeromq@5.1.0 install script.
10999 error This is probably not a problem with npm. There is likely additional logging output above.
```

### Versions

OS version:
Debian sid/unstable

> `atom --version`
```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

> `apm --version`
```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.16+
git 2.23.0
```

Hydrogen version:
2.12.0

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

No plugins, yet.

### Logs

Debug log by apm: [2019-09-03T09_31_49_440Z-debug.log](https://github.com/nteract/hydrogen/files/3568843/2019-09-03T09_31_49_440Z-debug.log)

### Expected behavior

Installation of hydrogen.

**Comment by iuvbio** [comment]
I have the same issue on Debian/buster. Same version of everything apart from Python (3.7.3) and git (2.20.1).

**Comment by wadethestealth** [comment]
Hi, apologies for not responding sooner because I have little knowledge of this stuff. Most likely what is happening here is an issue hydrogen cannot fix. Thus I would suggest checking your apm version, and I would upgrade it if possible and retry. Also since you are experiencing this on multiple projects I am very confident that we are not responsible for this issue, even if I had the ability to diagnose it.

Closing, as we are most likely not responsible. Comment if you believe we should reopen this. Apologies for the late reply.
