### ISSUE TITLE
Alternate execution model more Bret Victor (speculative)

### ISSUE THREAD

**Issue by piccolbo** [nteract/hydrogen#1772]
Please bear with me in a quite speculative feature discussion and please don't immediately think about implementation challenges. 

I find the current execution model confusing because it's different from the  execution of the file I am editing as a script. If I am editing a script that is divided in two sections A and B, I intend for it to execute A on an fresh instance of the interpreter  in a state S and then B on the state reached after the execution of A, Sa. The final state is Sab. If I go back  and change something in section B and want to see what happens, I rerun B but the initial state is now lost, the execution starts from Sab reaching Sabb. Sabb is a state the script should never reach under its intended mode of execution. 

**Major complaint: Sabb should not be reachable by design, when editing script AB**

I think Bret Victor's vision was  more like a time machine whereby state can be rewound in time. In his presentation, games move back and forth. Animations go back in time. The only alternative currently is to restart the kernel every time and rerun all the code up to a point. Joel Grus gave  a presentation at Pycon about similar criticism of jupyter notebooks.

**Proposal 1: If the execution of a script up to a point A results in an internal state Sa, that should be true every time code up to A is rerun, independent of what follows in the script or intervening user actions. If code up to A is modified to A',  the state reached after its execution should be Sa', every time.**

But what is more beautiful than seeing the consequences of a code change on every watched variable, every printed message or graphics, a la Bret Victor?

**Proposal 2: An (optional) execution mode such that whenever a script in two sections A and B is modified between A and B, B is immediately re-run from the state Sa and all the outputs are updated**

Proposal 2 may require a lot of computation and may be appropriate only for fast scripts with sub-second evaluation. That's why I said this should be optional, kind of auto-run mode.

Now as to the implementation. On the kernel side, I have concrete plans to implement a language-independent undo message that will efficiently undo the last execute_request message. I plan to use techniques that have been used in reversible debuggers before. Not mainstream but not cutting edge either. On the client side, hydrogen could submit statements s1, s2, ..., sn  one for each execute request. When the user changes some code in statement s(n-k), k undo messages would be sent to the kernel to rewind the state to what it was before that statement was run. Then in one mode of execution, s(n-k) would be re-run. In the auto-run mode s(n-k)...s(n) would be rerun and all outputs updated.

This is quite different from what hydrogen does today. Execution is much more manual, more like a hidden console prompt inside the editor.  Users can skip a line if they want and execute the next twice. A script can have any number of outputs depending on user interaction that is not recorded. I believe this more script-like execution model is more reproducible, and allows a more easy transition from experiments to scripts to quality code. It may very well be that even people who find merit in this proposal won't recommend to implement it in Hydrogen because it is such a large departure from the current model. I am looking forward to your feedback.

**Comment by wadethestealth** [comment]
No opposition, I think that I would need to see it working language independently before I got all excited about adding something to hydrogen though.

**Comment by piccolbo** [comment]
Given the lack of enthusiasm and the low probability of getting  the necessary changes into ipykernel, I will close this for now.
