### ISSUE TITLE
Now even Altair VegaLite 2 object cannot be rendered

### ISSUE THREAD

**Issue by piovac** [nteract/hydrogen#1775]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

It is known that Altair VegaLite 3 object rendering is not supported by Hydrogen yet. The trick as explained in #1700 is to importing VegaLite 2 explicitly: `import altair.vegalite.v2 as alt`.

This workaround did work for a while, indeed. But currently is not working anymore: even a VegaLite 2 object cannot be rendered.

Any idea for another workaround?

### Steps to Reproduce

1. The example in the hydrogen documentation:
```python
import altair.vegalite as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()
```
returns:
```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. [...]
```

2. The suggestion in #1700 is to explicitly calling version 2 of VegaLIte:
```python
import altair.vegalite.v2 as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()
```
but even this one cannot be rendered and it returns:
```
<VegaLite 2 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. [...]
```

### Versions

OS version: MacOS 10.14.5
(Also tried on a fresh installation in Ubuntu virtual machine and I get the same error).

> `atom --version`

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.10
git 2.23.0
```

Hydrogen version:

2.12.0

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [x] Hydrogen Launcher
- [x] Data Explorer

### Logs

N/A

### Expected behavior

A plot shout be displayed.

### Screenshots

N/A

### Additional context

```
Python 2.7.10
```
Related Python packages:
```
altair 3.2.0
ipykernel 5.1.2
ipython 7.7.0
jupyter 1.0.0
jupyterlab 1.0.9
vega 2.6.0
vega-datasets 0.7.0
```

**Comment by wadethestealth** [comment]
read the off topic of #1700

**Comment by qchenevier** [comment]
> read the off topic of #1700

Hi @wadethestealth,

You may have closed this one a bit too fast here. Actually, @piovac referenced #1700  in the first comment. :)

I can confirm the issue with Hydrogen version `2.12.0`. Neither VegaLite 3, nor VegaLite 2 are being displayed with altair version `3.2.0`.

Not sure if this is related, but I'm also a mac user: OSX 10.14.6

Workaround: To use altair with Vegalite 2, I downgraded to Hydrogen `2.10.3`:
```
apm remove Hydrogen
apm install Hydrogen@2.10.3
cd ~/.atom/packages/Hydrogen
npm install --save @nteract/presentational-components
```

(The last line is to get around the #1768 bug)

**Comment by wadethestealth** [comment]
@qchenevier I understand that he linked to #1700 but if you actually read the last comments marked as off topic in the thread, you will see exactly how this issue is duplicated. Particularly the issue you need to be watching for updates is #1771. I assure you that it's the same issue and there is no way it's not the same issue.

**Comment by qchenevier** [comment]
Ha ok, I haven't seen #1771 . Thanks.
