### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by niderhoff** [nteract/hydrogen#178]
Hey, I am trying to build hydrogen on OSX 10.11.3 using Atom 1.6.0-beta5. All dependencies are installed (according to installation guide) and everything is available in path for Atom. I managed to build hydrogen twice already (once on OSX 10.10. using an identical setup), however it fails after updating to El Capitan (OSX 10.11).

```
> zmq@2.14.0 install /private/var/folders/4x/c2w2k0717w54fbks4w5xdv140000gn/T/apm-install-dir-116125-1739-11c0epj/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/4x/c2w2k0717w54fbks4w5xdv140000gn/T/apm-install-dir-116125-1739-11c0epj/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/xxxx/.atom/.apm/.apmrc" "--userconfig" "/Users/xxxx/.atom/.apmrc" "install" "/private/var/folders/4x/c2w2k0717w54fbks4w5xdv140000gn/T/d-116125-1739-ouj51i/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/4x/c2w2k0717w54fbks4w5xdv140000gn/T/apm-install-dir-116125-1739-11c0epj/npm-debug.log
```

Getting same error message whether I install from within commandline-started Atom or directly using `apm-beta`. Any pointers?

Added log for inspection.
[npm-debug.txt](https://github.com/nteract/hydrogen/files/147263/npm-debug.txt)

**Comment by slavaGanzin** [comment]
Did you try to remove package first and then install? Did you try to install zmq separately? ```npm install zmq```

**Comment by n-riesco** [comment]
Judging by this line in your log:

    make: *** No rule to make target ../../../../../../../../../../../../Applications/Atom', needed byMakefile'. Stop.

I would guess, it may be a problem with your installation of Atom.

This log message indicates that there is a Makefile that can't locate your installation of Atom.

I'm not familiar with `apm-beta`. Is it perhaps that `Atom` has been renamed `Atom-beta`?

**Comment by niderhoff** [comment]
@n-riesco In my desperation I also tried renaming `Atom.app` back to `Atom.app` but that didn't change anything.

@slavaGanzin Yes I did.

**Comment by n-riesco** [comment]
@niderhoff Oh, I see! it looks like `../../../../../../../../../../../../Applications/Atom` is actually a truncated path `../../../../../../../../../../../../Applications/Atom Beta.app`. If that's the case renaming or linking won't help.

I think this issue has been reported to on the `apm` repository [here](https://github.com/atom/apm/issues/499).

**Comment by niderhoff** [comment]
Well I am not sure if that is the issue exactly though. If I run it on another machine (same setup, same atom version) it works:

```
xxxx@MacBook:~$ apm-beta rebuild hydrogen
Rebuilding modules ✓
```

**Comment by n-riesco** [comment]
Well, at least you now know that it can work with `apm-beta`. Here's another guess: perhaps, node-gyp fails because there are some stale files in ` ~/.atom/.node-gyp/`.

**Comment by niderhoff** [comment]
Completely wiped atom, node and all dependencies and reinstalled it. Same result.

**Comment by n-riesco** [comment]
Perhaps relevant:
https://github.com/nodejs/node-gyp/issues/734
https://github.com/nodejs/node/issues/2933
