### ISSUE TITLE
Progress reports from remote R kernels

### ISSUE THREAD

**Issue by nerutenbeck** [nteract/hydrogen#1785]
Hi there,

I love using Hydrogen! Thanks for the great software.

When working in Atom, I often use R + Stan to fit statistical models on a remote kernel. Some of these models are quite complicated, run in parallel, and can take a long time to identify (many hours). When I run those models from a local environment, Stan provides helpful progress reporting, but when I run through a remote kernel the progress report does not make it through in real time. This makes it impossible to know if / how the model identification process is proceeding, leaving me to guess and hope. I'd love a feature that would transmit these progress updates directly.

Thanks again.

**Comment by wadethestealth** [comment]
Hi and thanks. Great to hear you are loving Hydrogen.

I am a little confused on your wording, but maybe you can help me clarify. You say that this works fine locally but not remotely. Are you using hydrogen for both instances? If so then I am going to assume that the remote kernel is sending updates as fast as it can and we are displaying as fast as we can which means we won't be able to close the gap of latency, however we do have an outdated library for remote kernel connections so it may help for us to upgrade. 

In any case I believe you are requesting for progress reports universally, which I believe is #314, and proves difficult to implement in a language independent way, but could maybe be implemented as plugins or as a whole if a standard becomes widespread.

**Comment by nerutenbeck** [comment]
Ah yes, sorry for the source of confusion - that was a bit imprecise. When I run R + Stan in an R terminal via ssh or on my local machine, I get the progress reports, but not when going through Hydrogen. I think you are correct that this is a specific case of https://github.com/nteract/hydrogen/issues/314. Thanks again.
