### ISSUE TITLE
Failed to load the Hydrogen package

### ISSUE THREAD

**Issue by cxmeronmcgregor** [nteract/hydrogen#1795]
[Enter steps to reproduce:]

1. ... Launched Atom [with Hydrogen] after update.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.1

### Stack Trace

Failed to load the Hydrogen package

```
At Unrecognised input in C:\Users\aircr\.atom\packages\Hydrogen\styles\hydrogen.less:1:0

LessError: Unrecognised input
at C:\Users\aircr\.atom\packages\Hydrogen\styles\hydrogen.less:1:0
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
Hydrogen 2.12.1 
ide-python 1.5.0 
nv-dark-syntax 1.4.1 
nv-dark-ui 3.0.8 
platformio-ide-terminal 2.9.4 
rzx-dark-ui 1.1.0 
script 3.18.1 
```

**Comment by wadethestealth** [comment]
I think this must have been a bad download, because I don't think the less file has changed in a while. The easiest fix is to navigate to that file path it gave you and replace the contents with the contents of the styles/hydrogen.less file on this repo.
