### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by juanferrerm** [nteract/hydrogen#1799]
I was working on atom when suddendly I became unable to run python code. I checked the hydrogen package and try to update it in order to solve the error. The update failed so I uninstall hydrogen. Now, I can't install the package. 

Atom 1.41.0
apm 2.4.3
npm 6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.3
git
visual studio
hydrogen: 2.13.0

Screenshot of the update status, it has been like this for almost an hour.

![Sin título (2)](https://user-images.githubusercontent.com/32652517/67531624-0cf75900-f689-11e9-9438-e626472be8b2.png)

**Comment by wadethestealth** [comment]
Hydrogen does not have to do with the downloading of itself, that is strictly atom/apm or atom/atom. I recommend you open an issue over there, but they will most likely need more information. Things like reproducibility in safe mode, steps to follow, internet connection info like proxy, and an error log.
