### ISSUE TITLE
Incompatible with latest Atom release

### ISSUE THREAD

**Issue by maurice-schleussinger** [nteract/hydrogen#1800]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hydrogen doesn't work at all anymore since the latest update of the Atom editor.

### Steps to Reproduce

1. Install Hydrogen within Atom

### Versions

OS version:
macOS 10.15 (Catalina)

> `atom --version`

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.16
git 2.23.0
```

Hydrogen version:

2.13.0

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]
````
<embedded>:11 Failed to require the main module of 'Hydrogen' because it requires one or more incompatible native modules (zeromq).
Run `apm rebuild` in the package directory and restart Atom to resolve.
````

### Expected behavior

Start Hydrogen.

### Screenshots
<img width="631" alt="image" src="https://user-images.githubusercontent.com/1615089/67689882-49ce9300-f99c-11e9-8a28-619d1642cda4.png">

[If applicable, add screenshots to help explain your problem.]

**Comment by wadethestealth** [comment]
Hit the rebuild packages and then hit the rebuild hydrogen. If you no longer see that notification there is also a red bug icon on the status bar.
