### ISSUE TITLE
Issue writing unicode to text file (works fine in Jupyter notebook)

### ISSUE THREAD

**Issue by jbrussell** [nteract/hydrogen#1815]
### Description

Hydrogen seems to be having issues writing unicode characters to a text file in python 3.5.3. The issue can be simply demonstrated by running the following:

`txt_fle = open('test.txt', 'w')`
`pm = u'\u00b1'`
`txt_fle.write(pm)`
which produces the error:
```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-54-5935e796dbe2> in <module>()
----> 1 txt_fle.write(pm)

UnicodeEncodeError: 'ascii' codec can't encode character '\xb1' in position 0: ordinal not in range(128)
```

This code runs just fine from the terminal as well as in a Jupyter notebook. Any idea what could be going on that prevents Hydrogen from running this?

### Versions

OS version:
OSX 10.12.2

> `atom --version`

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.7
git 2.10.1
```
(Although python 2.7.7 is listed here, the Atom terminal shows Python 3 and
`import python_version`
`print(python_version()))`
returns `python 3.5.3`)

Hydrogen version:
2.13.1

**Comment by wadethestealth** [comment]
This could be how we send the string request. I'll have to do so manual check into how we send requests and how the write function determines string character formatting.

**Comment by wadethestealth** [comment]
If you precede your backslash, with a backslash it may work that's my intuition without debugging this.

**Comment by wadethestealth** [comment]
There is something interesting going on here. Can you explain how you got your error to output? I cannot see this error reported back. Also in jupyter notebook the code you provided doesn't work use must use 2 backslashes instead of 1 and in hydrogen the intended result seems to work if there is no backslash at all.

**Comment by wadethestealth** [comment]
```python
txt_fle = open('test.txt', 'w')
pm = u'\u00b1'
txt_fle.write(pm)
txt_fle.close()
```
Using the above code I was able to create an file name `test.txt` containing `±`. I cannot reproduce the issue, but this may be because of my system. Python opens files in certain text encodings based on the system, however you can specify an encoding like so
```python
txt_fle = open('test.txt', 'w', encoding='utf-8')
pm = u'\u00b1'
txt_fle.write(pm)
txt_fle.close()
```

**Comment by jbrussell** [comment]
You're correct, specifying the encoding worked! I still don't completely understand why Hydrogen and Jupyter would behave differently on the same machine.
