### ISSUE TITLE
cell color stays grey for Python but turns blue for MATLAB

### ISSUE THREAD

**Issue by jbrussell** [nteract/hydrogen#1816]
The cells for Python just look like comments and are basically impossible to see... Is this just a known bug or something wrong with my installation?

MATLAB:
<img width="182" alt="Screen Shot 2019-11-04 at 2 18 24 PM" src="https://user-images.githubusercontent.com/26443926/68150759-5f990680-ff0e-11e9-8516-e761fe38c5aa.png">

Python:
<img width="239" alt="Screen Shot 2019-11-04 at 2 17 29 PM" src="https://user-images.githubusercontent.com/26443926/68150779-67f14180-ff0e-11e9-942a-cdc51bffb3c9.png">

### Versions

OS version:
OSX 10.12.2

> `atom --version`

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`
```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.7
git 2.10.1
```

Hydrogen version:
2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ yes ] hydrogen-python
- [ yes ] Hydrogen Launcher
- [ no ] Data Explorer

**Comment by aviatesk** [comment]
close: dup of https://github.com/nteract/hydrogen/issues/1602
