### ISSUE TITLE
No kernel for grammar Python found

### ISSUE THREAD

**Issue by Zenithvox** [nteract/hydrogen#1817]
I know I'm most likely missing something, but here is everything I have done to try to run Hydrogen
![image](https://user-images.githubusercontent.com/40072606/68232070-4786bd00-ffca-11e9-9033-0ce8d5ce0482.png)

This is the error message that I'm getting. I have installed Jupyter and have done the commands featured 

This is what I get when I run -m ipykernel install --user
![image](https://user-images.githubusercontent.com/40072606/68232154-769d2e80-ffca-11e9-97c8-3679c4c1b957.png)

And here is my language pathing
![image](https://user-images.githubusercontent.com/40072606/68232184-887ed180-ffca-11e9-9c85-78a23247c0cd.png)

Any help would be amazing!

**Comment by Zenithvox** [comment]
> "python3" is the kernel display name, "python" is the kernel language name. Most likely leaving that blank would work fine.

That's funny. It was default {"python": "magicpython"}. I read that it may need to be changed for  python3. But yours worked perfectly.
Thank you!

**Comment by eiyouwangding** [comment]
I meet the same issue. And this is my setting. So, what should I do for it?
<img width="771" alt="Screen Shot 2019-11-07 at 3 07 56 AM" src="https://user-images.githubusercontent.com/47615797/68329298-e8c95c80-010b-11ea-96b2-0ac07ccf07de.png">
