### ISSUE TITLE
Upgraded Windows and Hydrogen no longer runs

### ISSUE THREAD

**Issue by QQMango** [nteract/hydrogen#1818]
Recently upgraded windows, and now I can't run any code in atom. 

![image](https://user-images.githubusercontent.com/53541621/68357799-7c873280-00e4-11ea-8aee-e92404307577.png)
For example, running the code above just gives me this. No output bubble, no checkmark, no hydrogen output, nothing. I updated all packages too.

My version: 
 Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

Thanks for helping out!

**Comment by QQMango** [comment]
I have updated all packages too

**Comment by wadethestealth** [comment]
In the settings enable Hydrogen Debug messages, and open up the console tab which can be seen by pressing `ctrl`+`shift`+`i` and going to the console tab. Run a line of code using the `hydrogen:run` command (if you do this via a shortcut, you must make sure that shortcut isnt in conflict with another package) Paste or screenshot the expanded output here.

**Comment by QQMango** [comment]
![image](https://user-images.githubusercontent.com/53541621/68358451-90339880-00e6-11ea-971d-da7d42424f7f.png)

**Comment by wadethestealth** [comment]
Is that path at the top still where your python exe is? what does `jupyter kernelspec list --json` in your terminal/command prompt output?

**Comment by QQMango** [comment]
ok I just realized that path led to some random file called python which was utterly useless. Deleted that file and now it works perfectly. Thank you so much for the quick response!
