### ISSUE TITLE
run-and-move-down could work on empty line

### ISSUE THREAD

**Issue by galou** [nteract/hydrogen#182]
and simply jump to the next line.

PS: Hydrogen is great! Thanks!

**Comment by n-riesco** [comment]
I will have a look at this issue.

@slavaGanzin , @rgbkrk What are your thoughts? I see two ways to approach this issue:
- change the way Hydrogen identifies what a code block is and allow empty lines
- or change the logic to move down the cursor and ensure it moves to the beginning of the next code block.

**Comment by slavaGanzin** [comment]
I think it "change the way" wouldn't be easy:
https://github.com/nteract/hydrogen/issues/155

So I vote for an easiest approach - check if line isn't empty.
