### ISSUE TITLE
NameError: name 'event' is not defined

### ISSUE THREAD

**Issue by HorselessName** [nteract/hydrogen#1820]
When i try to run pygame script it returns a error...
Error only occurs when using hydrogen

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-9b588b7979ea> in <module>
----> 1 event.wait()  # Vai esperar o evento anterior music.play terminar para encerrar o programa

NameError: name 'event' is not defined
```

**Comment by HorselessName** [comment]
My Script:

```
from pygame import event, init, mixer

mixer.init()  # Inicizaliza o mixer do pygame (Precisa ser inicializado antes dos outros módulos)
init()  # Inicizaliza todos os módulos carregados do pygame
# Linha de comando para carregar o arquivo de áudio
mixer.music.load('./marooned.mp3')
mixer.music.play()  # Função para reproduzir a musica que foi carregada acima
event.wait()  # Vai esperar o evento anterior music.play terminar para encerrar o programa

```

**Comment by wadethestealth** [comment]
You aren't importing according to the documentation.
>The pygame package represents the top-level package for others to use. Pygame itself is broken into many submodules, but this does not affect programs that use pygame.
>
>As a convenience, most of the top-level variables in pygame have been placed inside a module named pygame.localspygame constants. This is meant to be used with from pygame.locals import *, in addition to import pygame.
>
>When you import pygame all available pygame submodules are automatically imported. Be aware that some of the pygame modules are considered optional, and may not be available. In that case, pygame will provide a placeholder object instead of the module, which can be used to test for availability.

https://www.pygame.org/docs/ref/locals.html#module-pygame.locals
