### ISSUE TITLE
hydrogen tempo changes and skips on ubuntu 18.04

### ISSUE THREAD

**Issue by mrmagcore** [nteract/hydrogen#1821]
### Prerequisites

* [* ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ *] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

[Description of the bug]

### Steps to Reproduce

1. Run hydrogen on Ubuntu 18.04, plenty of ram, no processor load
2. start running a simple 1-beat drum track
3. tempo speeds up and slows down, lots of glitchy speed changes

### Versions

OS version:
[Your OS's version]
ubuntu 18.04.02
hydrogen 0.9.7-6
```


Hydrogen version:
<!-- You can check this information in the settings view or via running `apm show hydrogen` -->
[Your Hydrogen's version]

### Plugins

no plugins, straight out of the box.

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

A drum machine should probably play the same tempo and not skip beats or speed up and slow down during one measure.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
I think you are in the wrong repository as this makes no sense.
