### ISSUE TITLE
Kernel dies after any exception is thrown

### ISSUE THREAD

**Issue by guillefix** [nteract/hydrogen#1827]
### Prerequisites

* [X] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [X] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Since a few weeks ago, as soon as an exception is thrown by the python code, the kernel seems to die. Usually, when an exception was thronw, I could keep running other parts of the code.

Now, after the first exception occurs, any line of code that I evaluate, fails to run, and results in an `X` at the end of the line, as well as the following message in the developer console: `kernel.js? [sm]:366 Kernel: ignoring unexpected value for message.content.status`. 

Sometimes running a line fails, showing an `X`, without any exception having occured. However, in that case, I am able to rerun the line, and it usually works.

This is only happening in one computer, but it's making hydrogen a pain to use.

### Steps to Reproduce

I described it above, but I am not yet sure what part of my setup makes it fail, while it works in other computers. I will explore further. But if anyone has encountered the same problem, maybe they can save me some of that time.

### Versions

OS version: Ubuntu 18.10

> `atom --version`

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.16
git 2.19.1

```

Hydrogen version: 2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [X] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Additional context

After more testing, I just found that the error doesn't happen in a virtual environment I have, **it only happens on my vanilla "Python 3" kernel.**. I suppose there must be something in my environment that is breaking it?

**Comment by wadethestealth** [comment]
can you give me some sample code to test this as I am unaware which type of thrown exception could cause this behavior?

**Comment by aviatesk** [comment]
I've actually experienced a weird behaviour like this while I played around IRuby kernel, but I can't even remember I saved the exact code. I will post that if I find that.

And yes, as @wadethestealth pointed, a sample code that contains MRE would really help us debug the problem: @guillefix

**Comment by aviatesk** [comment]
since the original reporter doesn't present
mre, I'm going to close this.

I may open an new issue if I encounter this with valid mre.
