### ISSUE TITLE
Unexpected python3 error when running the codes

### ISSUE THREAD

**Issue by max-ao** [nteract/hydrogen#1828]
### Prerequisites

* [ ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

When I excuted the codes with fresh installed hydrogen, the bug just appeared after 'kernel updated".
I hvae attached the screenshot.
![image](https://user-images.githubusercontent.com/57995939/69245025-01228800-0b9e-11ea-98eb-d4f07547d746.png)
 

### Steps to Reproduce

1. write any codes
2. hydorgen-run

### Versions

Windows 10

> `atom --version`
 Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

```

> `apm --version`
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.5
git
visual studio

```

Hydrogen version:
Hydrogen
├── 2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer
No.
### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

**Comment by wadethestealth** [comment]
You can view this issue at #1405 and there are also many referenced issues that are about the same discussion
