### ISSUE TITLE
Python open() function not working properly

### ISSUE THREAD

**Issue by HorselessName** [nteract/hydrogen#1830]
My code:

```
linhas = set()  # Pesquisa as linhas
fileSaida = open('ips.txt', 'w')  # Arquivo a ser criado com as linhas corretas
for linha in open("duplicados.txt", "r"):  # Arquivo com linhas duplicadas
    if linha not in linhas:  # Se nao encontrar a linha, não é duplicado
        fileSaida.write(linha)
        linhas.add(linha)
fileSaida.close()  # Fechar o arquivo
```

Hydrogen error:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-99bed7d75ce7> in <module>
      1 linhas = set()  # Pesquisa as linhas
      2 fileSaida = open('ips.txt', 'w')  # Arquivo a ser criado com as linhas corretas
----> 3 for linha in open("duplicados.txt", "r"):  # Arquivo com linhas duplicadas
      4     if linha not in linhas:  # Se nao encontrar a linha, não é duplicado
      5         fileSaida.write(linha)

FileNotFoundError: [Errno 2] No such file or directory: 'duplicados.txt'

```

Is there a way around this?
Using 'script' package and windows cmd works perfectly, tho with hydrogen does'nt.

**Comment by wadethestealth** [comment]
Not sure why this works in the script package, but you just need to always have a `duplicados.txt` file if you are trying to access it. If it has the possibility to not exist you should catch the error and handle that how you wish. Everything here is functioning just as how python should.

**Comment by HorselessName** [comment]
I already have a > duplicados.txt file...

See: 
![image](https://user-images.githubusercontent.com/20173635/69266145-60d26080-0ba9-11ea-97c7-01b362e423bf.png)

Are you 100% sure this is'nt a bug?

**Comment by HorselessName** [comment]
The file is in the same directory, i tested using _script_ and directly into the terminal.
It did'nt give me any errors...

**Comment by HorselessName** [comment]
I even changed the code a bit, instead of using with, just using a variable:

```
linhas = set()  # Pesquisa as linhas
fileSaida = open('ips.txt', 'w')  # Arquivo a ser criado com as linhas corretas
duplicados = open('duplicados.txt', 'r')
# with open('duplicados.txt', 'r') as duplicados:
for linha in sorted(duplicados):  # Arquivo com linhas duplicadas
    if linha not in linhas:  # Se nao encontrar a linha, não é duplicado
        fileSaida.write(linha)
        linhas.add(linha)
fileSaida.close()  # Fechar o arquivo
```

Same error:
`FileNotFoundError: [Errno 2] No such file or directory: 'duplicados.txt'
`Tho its in the same directory... Why? Is it a bug?

**Comment by wadethestealth** [comment]
hydrogen's directory is not the same as the terminal's
run `%pwd` in hydrogen to understand which directory you are in

**Comment by HorselessName** [comment]
Thank you. Sorry for opening another issue, you can also change #1832 to 'question' since it's not a bug.

I changed the setting 'Directory to start kernel in' to 'Current directory of the file' and worked,
Thank you again
