### ISSUE TITLE
Python input using ANSI shows weird characters

### ISSUE THREAD

**Issue by HorselessName** [nteract/hydrogen#1833]
When i execute any input command in Hydrogen with some sort of ANSI code, 
```
ascender_luz = input(
    'Deseja acender a luz ? {}S{}/{}N{} '.format('\033[32m', '\033[m', '\033[31m', '\033[m'))
```

This happens:

![image](https://user-images.githubusercontent.com/20173635/69456160-c1e46a80-0d48-11ea-9193-1632a8ca5582.png)

Any way to avoid that?

**Comment by HorselessName** [comment]
This is expected (Image of another terminal)
![image](https://user-images.githubusercontent.com/20173635/69456243-eccebe80-0d48-11ea-9f69-049cd6189b26.png)

**Comment by wadethestealth** [comment]
Hydrogen does not have a terminal, you must open an issue in the package that has the terminal.

**Comment by HorselessName** [comment]
I don't get it. You read terminal but i think you misunderstood.
When i execute a command using Hydrogen and it has a INPUT in it, hydrogen displays weird ANSI characters,

**Comment by wadethestealth** [comment]
The current supported text formats for rendering are plain, markdown, HTML, and latex.
