### ISSUE TITLE
Kernel doesn't respond, can't execute code

### ISSUE THREAD

**Issue by strohmhw** [nteract/hydrogen#1835]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ? YES
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ? YES

### Description

Hydrogen doesn't run code in atom - kernels installed - 'x' boxes

### Steps to Reproduce

1. Install atom and hydrogen to computer
2. Install python kernels
3. Shift-Enter and Cmd-Enter to run code

### Versions

apm:  2.4.3
npm:  6.2.0
node: 10.2.1 x64
atom: 1.41.0
python: 3.8.0
git
visual studio

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

![hyrdogen-issue](https://user-images.githubusercontent.com/24664070/69650722-03bd2b80-103d-11ea-8324-ae95005a803d.jpg)

**Comment by wadethestealth** [comment]
@aviatesk any ideas

**Comment by aviatesk** [comment]
no, did you reproduce this ?

**Comment by wadethestealth** [comment]
@aviatesk no I am not going to be able to reproduce that. It seems like they installed everything correctly because hydrogen recognized their kernel. @strohmhw what did you use to install. Are you able to use jupyter notebooks or console or anything

**Comment by strohmhw** [comment]
I installed within Atom, and then reinstalled using apm in console. Looks like I might have jupyter package issues?

jupyter core     : 4.6.1
jupyter-notebook : not installed
qtconsole        : 4.6.0
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.3

I can use python console

**Comment by wadethestealth** [comment]
Python console is only for your python not your jupyter kernel. Can you use qtconsole?

**Comment by strohmhw** [comment]
No - seem to have an issue there as well. Are these packages I need to install separately?

`
ImportError:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:   None
    PyQt4 installed:                 False
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5', 'pyside2', 'pyside', 'pyqt']
`

**Comment by wadethestealth** [comment]
Potentially I can't remember too well but you definitely should have pyqt5 from an anaconda install did you use pip to install jupyter. If so you are probably missing some things. I would read the ipython docs or jupyter docs

**Comment by strohmhw** [comment]
Ok. I'll install from anaconda and see if it solves some issues here and return to this chat
