### ISSUE TITLE
Hydrogen doesn't run any code, zeroMQ issue?

### ISSUE THREAD

**Issue by JayBee-Str** [nteract/hydrogen#1836]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

When i start Atom and try to run code with Hydrogen for the first time (after launching Atom) I just receive a pop-up windows telling me ``Hydrogen Kernels updated - Python 3``. 

### Steps to Reproduce

1. Install pyzmq
2. Install ipython + atom/hydrogen
3. Try to run code ctrl+enter

### Versions

OS version:
Windows 7 64bit

Hydrogen version:
2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

```
gyp ERR! clean error 
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\Jonas Blickle\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node'
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Jonas Blickle\\AppData\\Local\\atom\\app-1.40.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Jonas Blickle\\AppData\\Local\\atom\\app-1.40.1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jonas Blickle\.atom\packages\Hydrogen\node_modules\zeromq
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Jonas Blickle\.atom\.apm\_logs\2019-11-27T19_36_29_367Z-debug.log
```

### Expected behavior

Run Code

### Screenshots

![5](https://user-images.githubusercontent.com/47690359/69754992-83d7b400-1157-11ea-889e-bc8f57fc87fe.jpg)

### Additional context

The Errorlog somewhat mentiones zeroMQ, maybe this is causing trouble.

In advance thanks a lot!

**Comment by wadethestealth** [comment]
Seems like this is an npm installation problem. I would read this [issue](https://github.com/phoenixframework/phoenix/issues/2464) and follow their solutions as they had multiple. If you have any further troubles, post here and I will reopen the issue.
