### ISSUE TITLE
How to remove and environment in Hydrogen?

### ISSUE THREAD

**Issue by massimilianocomin** [nteract/hydrogen#1840]
### Description

I had 2 Python environments in Hydrogen and everything was ok. I deleted one (I checked that conda info --envs only returns one environment), but Hydrogen still asks me to choose between the two. If I select the deleted one, nothing happens.

How can I tell Hydrogen that the second environment doesn't exist anymore?

Thanks

**Comment by wadethestealth** [comment]
Seems like what you are referring to is your kernels. Hydrogen is asking you to decide between two kernels and while you may have deleted the environment it needs to run your have not deleted the kernel itself. See this [stackoverflow](https://stackoverflow.com/a/42647666).
