### ISSUE TITLE
Bring Hydrogen to VsCode

### ISSUE THREAD

**Issue by AeneasZhu** [nteract/hydrogen#1841]
I am a VSCode user ofter uses Python Interactive Window of VsCode for data science.  But Python Interactive Window is not as conveninent as Hydrogen on some aspects. And VSCode's python team is working on improving VSCode Notebook which is more like Jupyter Notebook itself but cannot be compatible with 3rd-extension like vim. Configuring in my country is not convenient because of firewall, so I don't use Atom as my first IDE.

Therefore, I hope Hydrogen can be brought to VSCode in place of VsCode Notebook.

**Comment by wadethestealth** [comment]
#449
