### ISSUE TITLE
Support Vegalite 4

### ISSUE THREAD

**Issue by piccolbo** [nteract/hydrogen#1847]
### Prerequisites

* [ x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Altair charts empty in atom/hydrogen

### Steps to Reproduce

1. Try to generate any altair chart (one example below)
2. Execute
3. Observe emptiness of output

code

```
import altair as alt

from vega_datasets import data
import pandas as pd
from urllib.request import urlretrieve

urlretrieve(data.stocks.url, "stocks.csv")
stocks = pd.read_csv("stocks.csv")

alt.Chart(stocks).mark_line().encode(x="date:T", y="price:Q", color="symbol:N")
```
Any chart will do. The problem seems to have arisen switching to altair 4.0.0 which uses vega lite 4 from altair 3.2.2. Reverting to that version of altair restores the output

### Versions

OS version:

Os x catalina
> `atom --version`

```
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 3.6.9
git 2.16.2
```

Hydrogen version:

[Your Hydrogen's version]
Hydrogen
├── 2.13.1
### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

Seein charts

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
Hydrogen doesn't yet support Vegalite 4. The nteract Vega library has a published prerelease for Vegalite 4, but for hydrogen to adopt vegalite 4 the package must publish an official release which we do on a monthly schedule

**Comment by piccolbo** [comment]
Could you point me to the nteract vega library which is in prerelease? I'd like to keep an eye on it.
Reason (only if you are interested): I maintain a package called altair-recipe that can be used to produce charts in atom with hydrogen, but I got my (few) users stuck with the latest release. If this lib is imminent, I can tell them to downgrade by one step as a workaround. If it isn't I have to do something harder.

**Comment by wadethestealth** [comment]
@nteract/transform-vega on npm. it's a package in the nteract monorepo. The prelease has vegalite4 support. Hydrogen only works on official releases.

**Comment by aviatesk** [comment]
@piccolbo can you try to play around with the current `master` branch ? There `Vegalite 4` will be supported.

Try `apm dev Hydrogen` and restart Atom.

**Comment by piccolbo** [comment]
Sorry to be unresponsive, life took over. I don't see any changes trying the above steps. If I try `alt.renderers.enable('mimetype')` in analogy with nteract and vscode, I get the following error 
```
SyntaxError: Unexpected token o in JSON at position 1
```

**Comment by andyreagan** [comment]
I just tried `apm dev Hydrogen` and am seeing the same output:

    SyntaxError: Unexpected token o in JSON at position 1
