### ISSUE TITLE
Hydrogen either produces check marks or not output for Atom Python 3 Windows 10

### ISSUE THREAD

**Issue by qwertytam** [nteract/hydrogen#1849]
### Prerequisites
I went through the troubleshooting guide and followed them to the best of my ability, but did not solve the issue. I did not find a relevant fix in the issues already filed - please do point me in the right direction if I've missed something.

### Description
Hydrogen either produces a check mark (or cross depending on what you call them) or not output at all - see screen shots below. On executing the first line of the simple script with `shift-enter`, the blue info box displays with `hydrogen kernels updated, python 3`

### Steps to Reproduce
1. Load simple python script - first seven lines are reproduced below. Remainder capture in screen shots. The script executes all ok and as expected in full from the command line with `python htest.py`
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Simple tests
print('Hello world!')
17+25
```

2. Execute each line with `shift-enter`

### Versions
OS version:
Windows 10

> `atom --version`

```
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 3.8.0
git
visual studio
```

Hydrogen version:

Hydrogen
├── 2.13.1

Jupyter kernel check with `jupyter kernelspec list --json`
```
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "C:\\Users\\Tom\\AppData\\Roaming\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "C:\\Users\\Tom\\AppData\\Local\\Programs\\Python\\Python38\\python.exe",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}
```

### Plugins
Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs
See screenshots below

### Expected behavior
Hydrogen shows `'Hello world!'` against line 6 of the script, and `42` against line 7

### Screenshots
**Showing only check marks**
![Capture01](https://user-images.githubusercontent.com/42878471/71366622-8b308880-2570-11ea-8e13-0c8bdd3e8773.PNG)

**Showing no output**
![Capture02](https://user-images.githubusercontent.com/42878471/71366643-9aafd180-2570-11ea-9958-f4046d6d4d48.PNG)

### Additional context
I have reinstalled Atom and Hydrogen multiple times. I have also removed all other non-core Atom packages.

**Comment by wadethestealth** [comment]
Seems like you aren't getting any response back from your kernel. Have you used your kernel in any other application like jupyter notebook. In the no response case it seems hydrogen is unable to even start up the kernel.

**Comment by qwertytam** [comment]
So traced issue back to Jupyter and saw that it is not compatible and/or has issues with python v3.8. So downgraded to python v3.7.6. Solve problem with Jupyter, however no getting another error from Hydrogen (raised as a separate issue).
