### ISSUE TITLE
Error running Python 3 (on Hydrogen 2.8)

### ISSUE THREAD

**Issue by anitatea** [nteract/hydrogen#1855]
### Description
I am running a simple 'print('hello')' but it does not execute. Every time I open atom and run my code (any code), I receive an 'ImportError: DLL load failed: The specified module could not be found.' I am very new at Python/ using Atom but would appreciate any help to have this going!

### Steps to Reproduce
1. Open atom
2. Run python 'print('hello')'

### Versions

OS version:
Windows

> `atom --version`

```
1.41.0
```

> `apm --version`

```
2.4.3
```

Hydrogen version:

2.8

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior
Atom Hydrogen to print out 'Hello'.

### Error Screenshot

![image](https://user-images.githubusercontent.com/22034445/71627940-83519380-2bc3-11ea-863d-7080543c5837.png)

**Comment by wadethestealth** [comment]
Please read the other issues and information from this comment. https://github.com/nteract/hydrogen/issues/1550#issuecomment-506567440
