### ISSUE TITLE
Uncaught SyntaxError: Unexpected token case

### ISSUE THREAD

**Issue by Godssentralen** [nteract/hydrogen#1860]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise Evaluation
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Uncaught SyntaxError: Unexpected token case

```
At C:\Users\Tor

**Comment by wadethestealth** [comment]
Not enough information.
