### ISSUE TITLE
No output or checkmark

### ISSUE THREAD

**Issue by sdickson02** [nteract/hydrogen#1864]
Hello! Apologies in advance if this was not the correct way to seek help on this -- I'm almost certain there must be something that I'm doing wrong, but I've reached the end of my ability to troubleshoot without advice. I'm brand new with Python and would like to use Atom to practice as it is my favorite text editor, so I've been trying to figure out how to get Hydrogen working because that seems like the best option for running Python scripts.

At first, I was experiencing the issues outlined in #1779, so I had to installed version 2.8.0. Updating Hydrogen does not work, so I am stuck on 2.8.0. 

Then I went through the process of updating the kernels (following the advice on #1538), so I believe that it is now correctly installed. However, the first time I hit Ctrl+Enter (or even try to Run from the Packages menu), all that happens is a popup saying that Hydrogen has updated the kernels and detects Python 3. After that, nothing happens when I try to Run again - the cursor doesn't even jump down to the next line.

I have checked the Console output and it doesn't appear that anything is happening. I've tried closing Atom and reopening, closing my file and reopening, uninstalling Hydrogen and reinstalling. Nothing seems to work -- but there must be something I'm missing?

Any help would be much appreciated!

![image](https://user-images.githubusercontent.com/43976554/72948455-0933ab00-3d3a-11ea-86ea-84b60ce6a91f.png)

**EDIT:** I see that my issue might be the same as #1849 -- about to try downgrading to Python 3.7 and will report back after.

**EDIT 2:** Alright, now that I downgraded Python I'm getting an entirely different error -- seems like something to do with either Hydrogen or Atom being confused that I no longer have Python 3.8 and have instead switched to 3.7. I've also been looking through the issues here and trying to figure out what the  best combination of Hydrogen and Python versions is, but have not been able to find a straightforward answer. Could anyone tell me what the recommended version of Python is, and the recommended version of Hydrogen that works best with Python? Maybe I can start from there.

**EDIT 3:** Completely at a loss here now. Based on what I read from #1849 and #1854, I installed Python 3.7.6 fresh on my MacBook using Homebrew. Everything seems set up correctly -- Python is working. Added the kernels. Then I installed Hydrogen 2.8.0, opened my test Python script... same issue as before. No checkmarks, no output -- just pops up in blue saying that it updated the kernels and recognizes Python 3.

**Comment by shilovedi** [comment]
I have a similar issue. However, it is happening in the windows 10 system. Nothing happens when I try to run hydrogen, and it is installed correctly. Nothing shows up, either.

**Comment by wadethestealth** [comment]
Which python version you used is entirely based on your kernel. The IPython Kernel does not yet support Python 3.8. If your kernel is having a problem running code you should check your `kernels.json` file in your `.jupyter` directory and ensure that your kernel is using the correct executable (i.e. Python 3.7 in this example) You also need to enable debug messages in Hydrogen's settings to see console output. Once doing so you should be able to see some connection logs which can help diagnose this issue further for me.
