### ISSUE TITLE
Hydrogen code not running in atom - no error 

### ISSUE THREAD

**Issue by rinalynne** [nteract/hydrogen#1867]
I recently updated from the Python 3.7 32-bit to Python 3.8 64-bit, and can no longer run python code in Atom using Hydrogen. When I attempt to run a line upon first launching atom, I get the blue popup window saying that my Python3 and Stata kernels have been updated, but the code does not run. There is no error message, but the little checkmark or 'x' that used to appear next to the code doesn't show. 

The new installation of Python has been added to my path (see screenshot), but I assume that's not the issue since there's no error message. 
![Screenshot (28)](https://user-images.githubusercontent.com/41088659/73128191-e3e8ac00-3f88-11ea-9ccd-4b7b517111c0.png)

When I check `jupyter kernelspec list` using the command line I get the following output: 
`Available kernels:
  stata      C:\Users\asus\AppData\Roaming\jupyter\kernels\stata
  python3    c:\users\asus\appdata\local\programs\python\python38\share\jupyter\kernels\python3`

`jupter kernelspec list --json` in the command line also shows that all the file extensions are correct: 
![Screenshot (29)](https://user-images.githubusercontent.com/41088659/73128224-535e9b80-3f89-11ea-8efb-544b1ccea9f8.png)

**Comment by wadethestealth** [comment]
3.8 is not jupyter compatible
