### ISSUE TITLE
Unable to find module from conda environment

### ISSUE THREAD

**Issue by risaueno** [nteract/hydrogen#1868]
### Description

I've followed the documentation but have the same problem as this: https://discuss.atom.io/t/hydrogen-issues-modulenotfounderror/56583/4 

I've installed ipykernel and did `python -m ipykernel install --user --name myenv` (solutions in existing issues #899, #501). I seem to be activating a specific conda environment with hydrogen but it’s not finding the specific modules I’ve installed on the environment when I run an import - perhaps it is still looking globally. Many thanks for any suggestions/help!

**Comment by aviatesk** [comment]
Are you sure you select a kernel which runs in the conda environment ?
For example, I have a conda enviroment named `py36` and have a `C:\\...\AppData\Roaming\jupyter\kernels\py36\kernel.json` file and it looks like:
```
{
 "argv": [
  "C:\\...\\Anaconda3\\envs\\py36\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3.6",
 "language": "python"
}
```

And then I can select this kernel when  I tried to start a Python kernel and it can import modules in the environment (this time `py36`)
