### ISSUE TITLE
No option view debug messages 

### ISSUE THREAD

**Issue by rjbergerud** [nteract/hydrogen#1869]
### Prerequisites

* [ x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

[Description of the bug]
There isn't any option to view debug messages in the settings menu.  
### Steps to Reproduce

1.  Install Hydrogen 2.13.1 on atom 1.42.0
2. Navigate to Hydrogen's settings menu through Settings -> Packages -> Hydrogen
3. Should be visible there according to docs, but isn't https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html

### Versions

OS version:
[Your OS's version]
5.4.6-2-MANJARO

> `atom --version`

```
Atom    : 1.42.0
Electron: 4.2.12
Chrome  : 69.0.3497.128
Node    : 10.11.0

```

> `apm --version`

```
apm  2.4.5
npm  6.13.4
node 13.5.0 x64
atom 1.42.0
python 3.7.4

```

Hydrogen version:

[Your Hydrogen's version]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

[A clear and concise description of what you expected to happen.]
Should be able to see an option to enable debug messages.

### Screenshots

[If applicable, add screenshots to help explain your problem.]
https://imgur.com/g0IpkPn.png
### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
It is still there. It has just been moved further down the settings page. It currently 7th from the top.
