### ISSUE TITLE
Dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by jbinagia** [nteract/hydrogen#1875]
Apologies in advance for essentially re-opening #1873 (which was closed in favor of #1854), but I do think the issue below is distinct from #1854 (the former is an issue when using 2.8 while the latter is related to the latest release). Any help would be greatly appreciated. 

### Steps to reproduce:

1. `apm install hydrogen@2.8.0`

**Atom**: 1.40.1 ia32
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Failed to activate the Hydrogen package

```
At A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
```

### Commands

```
     -0:06.3.0 hydrogen:run-all (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.9.1 
autocomplete-python 1.16.0 
data-explorer 0.7.0 
Hydrogen 2.8.0 
hydrogen-cell-separator 0.4.1 
hydrogen-launcher 1.2.2 
indent-detective 0.4.0 
ink 0.11.8 
julia-client 0.11.3 
kite 0.178.0 
language-fortran 2.1.10 
language-julia 0.19.2 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
latex-completions 0.3.6 
markdown-preview-enhanced 0.17.5 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.9 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
remote-ftp 2.2.4 
script 3.25.0 
split-diff 1.6.1 
tool-bar 1.2.0 
```

**Comment by wadethestealth** [comment]
I agree with the reopening of this issue, since I also believe this is separate.

Unfortunately this has not occured to my knowledge before.

Did you see this comment by @n-riesco

https://github.com/nteract/hydrogen/issues/1873#issuecomment-583476529

**Comment by jbinagia** [comment]
@wadethestealth Yes - I didn't receive any error messages when running `apm install hydrogen@2.8.0`. How can I find where zeromq is installed?

**Comment by wadethestealth** [comment]
\\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node

**Comment by PK2702** [comment]
> Apologies in advance for essentially re-opening #1873 (which was closed in favor of #1854), but I do think the issue below is distinct from #1854 (the former is an issue when using 2.8 while the latter is related to the latest release). Any help would be greatly appreciated.
> 
> ### Steps to reproduce:
> 1. `apm install hydrogen@2.8.0`
> 
> **Atom**: 1.40.1 ia32
> **Electron**: 3.1.10
> **OS**: Microsoft Windows 10 Home
> **Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0
> 
> ### Stack Trace
> Failed to activate the Hydrogen package
> 
> ```
> At A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node
> 
> Error: A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
>     at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
>     at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
>     at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
>     at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
>     at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
>     at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
>     at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
>     at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
>     at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
>     at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
>     at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
>     at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
> ```
> 
> ### Commands
> ```
>      -0:06.3.0 hydrogen:run-all (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> atom-latex 0.9.1 
> autocomplete-python 1.16.0 
> data-explorer 0.7.0 
> Hydrogen 2.8.0 
> hydrogen-cell-separator 0.4.1 
> hydrogen-launcher 1.2.2 
> indent-detective 0.4.0 
> ink 0.11.8 
> julia-client 0.11.3 
> kite 0.178.0 
> language-fortran 2.1.10 
> language-julia 0.19.2 
> language-latex 1.2.0 
> language-markdown 0.37.0 
> latex 0.50.2 
> latex-completions 0.3.6 
> markdown-preview-enhanced 0.17.5 
> markdown-scroll-sync 2.1.2 
> markdown-writer 2.11.9 
> pdf-view 0.72.0 
> pen-paper-coffee-syntax 0.17.0 
> remote-ftp 2.2.4 
> script 3.25.0 
> split-diff 1.6.1 
> tool-bar 1.2.0 
> ```

**Comment by jbinagia** [comment]
@wadethestealth I think I am confused by the suggestion of https://github.com/nteract/hydrogen/issues/1873#issuecomment-583476529. Is the suggestion to delete `zeromq`? Then Atom will not run because it cannot locate `zeromq`, so I must be mistaken.

**Comment by wadethestealth** [comment]
@jbinagia I think the comment was just a suggestion to make sure that when you uninstall, it is completely gone.

**Comment by jbinagia** [comment]
@wadethestealth I see; in that case, yes whenever I uninstall Atom the entirety of the folder (including the `zeromq` subfolder) is removed.

**Comment by jbinagia** [comment]
I recently tried installing the latest version of Atom again and with that, I am no longer receiving this exception so I am going to close this issue.
