### ISSUE TITLE
The Documentation section leads to a dead link

### ISSUE THREAD

**Issue by OivindAlvestad** [nteract/hydrogen#1890]
Trying to look at the documentation linked in the readme, leads to a dead link "https://nteract.gitbooks.io/hydrogen/".

**Comment by aviatesk** [comment]
It does work, no ?

**Comment by paul-grassl** [comment]
I also can't access the documentation for some reason...

**Comment by OivindAlvestad** [comment]
@paul-grassl I actually found out that our router/ISP/DNS was the problem. Check if you can access it from a different Wi-fi, or via 4G on your phone.
The solution for me was to add googles DNS (8.8.8.8) in my wifi settings.

**Comment by paul-grassl** [comment]
thanks that resolved it for me :)
