### ISSUE TITLE
Edit / run Jupyter and R notebooks in RMarkdown format

### ISSUE THREAD

**Issue by matthew-brett** [nteract/hydrogen#1913]
### :memo: Summary

I would love a description of how to use Hydrogen in an RMarkdown document.

### :checkered_flag: Motivation

I now nearly always use RMarkdown for my Jupyter notebooks, using the indispensable [Jupytext](https://github.com/mwouts/jupytext) utility.  I can and do set this utility to always save my notebooks in RMarkdown format, from the Jupyter interface.  I can then edit them much more easily in my editor.

I also use RMarkdown for R notebooks.

But - I would like to be able to execute the notebook cells from my editor, rather than having to use the Jupyter web app, or RStudio.

At least at the moment, the main problem with doing that is RMarkdown code cells have curly brackets identifying the language for each cell, thus:

~~~
```{python}
a = 10
print("This is Python")
```
~~~

or

~~~
```{r echo=FALSE}
a <- 10
print('This is R')
```
~~~

At least in the default configuration, Hydrogen does not recognize `{python}` or `{r}` as describing the kernel name, so I have to edit the curly brackets out to run the code.

However - being able to run this kind of mixed document, in the native format both of R, and an easily-used format for a Jupyter notebook, would be a killer feature, I am sure.

Please forgive me if I missed some description of how to make this work.

**Comment by matthew-brett** [comment]
Ah - sorry - I just discovered Atom [language-markdown](https://atom.io/packages/language-markdown) with some more searching.  That solves the curly-brackets code chunks problem.  I'll close this - sorry for the noise.

**Comment by aviatesk** [comment]
yeah, each grammar package is responsible for defining grammar scopes of each markdown cell.
