### ISSUE TITLE
problem installing Hydrogen in atom v 1.14.00 

### ISSUE THREAD

**Issue by bighit661** [nteract/hydrogen#1922]
I have attached the output log for you to have a look at. 
please let me know if you know what the problem might be.
thanks 
[2020-04-30T23_11_52_597Z-debug.log](https://github.com/nteract/hydrogen/files/4561829/2020-04-30T23_11_52_597Z-debug.log)

**Comment by n-riesco** [comment]
Unfortunately, the log doesn't tell us why zeromq's install script is failing.

One thing, I'd try is to build zeromq's binary yourself. See https://github.com/nteract/hydrogen/issues/1585#issuecomment-487591763
