### ISSUE TITLE
Hydrogen stopped working after updating Atom

### ISSUE THREAD

**Issue by markeyser** [nteract/hydrogen#1931]
After updating Atom 1.47.0 Hydrogen stopped working. I followed Hydrogen troubleshooting guide but still do not work: https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#hydrogen-stopped-working-after-updating-atom

Thanks,

Marcos

**Comment by aviatesk** [comment]
follow our issue template otherwise we can't help
