### ISSUE TITLE
The error:  Cannot find module '../build/Release/zmq.node' Require stack:

### ISSUE THREAD

**Issue by Lee1125** [nteract/hydrogen#1960]
Hydrogen can't run on Atom. I installed the hydrogen using the command line: apm install hydrogen. But the Hydrogen produce bug. I tried to install the old version hydrogen. The hydrogen can't be used on atom. The error is following:
------------------------------------------------------------------------------
Cannot find module '../build/Release/zmq.node'
Require stack:
- /Users/xxx/.atom/packages/hydrogen/node_modules/zeromq/lib/index.js
- /Users/xxx/.atom/packages/hydrogen/node_modules/zeromq/index.js
- /Users/xxx/.atom/packages/hydrogen/node_modules/jmp/index.js
- /Users/xxx/.atom/packages/hydrogen/lib/zmq-kernel.js
- /Users/xxx/.atom/packages/hydrogen/lib/kernel-manager.js
- /Users/xxx/.atom/packages/hydrogen/lib/store/index.js
- /Users/xxx/.atom/packages/hydrogen/lib/utils.js
- /Users/xxx/.atom/packages/hydrogen/lib/panes/inspector.js
- /Users/xxx/.atom/packages/hydrogen/lib/main.js
- /Users/xxx/Documents/Software/Atom/Atom.app/Contents/Resources/app.asar/static/index.html
--------------------------------------------------------------------------------
I checked ../build/Release/.   The file is empty.  May be some files can't be compiled. But I'm not sure. How should I do???
--------------------------------------------------------------------------------
Atom version: 1.48.0
Hydrogen version:2.14.1
Mac version: MaOS 10.15.5

**Comment by aminya** [comment]
Please redownload the latest version.
