### ISSUE TITLE
Make inline results copy&paste'able

### ISSUE THREAD

**Issue by PhilippImhof** [nteract/hydrogen#1962]
# :memo: Summary

At the moment, results showed inline cannot be selected, copied and then pasted elsewhere. This functionality is available for results showed in the dock.

### :checkered_flag: Motivation

I prefer to have my results showed inline, especially for plots and/or tables, because there is just more space available. On the other hand, I sometimes do calculations and would like to copy results into a LaTeX (or other) document. Also, the only way to switch between inline and dock view is by changing the settings, there is no quick toggling of this setting via the command palette.

### :runner: Approach

As I understand, inline results are showed in an additional `div` attached to a marker. An easy solution could be to add the `icon-clippy` button clipboard icon (that is shown in the dock) just below the `x` icon that closes the div. The `onclick` event handler would probably need a few changes.

### :anchor: Drawbacks

I see absolutely no drawbacks.

**Comment by aviatesk** [comment]
inline results are "copy & pastable" already, just click it to copy into clipboard, as the hover message says.

**Comment by PhilippImhof** [comment]
While looking at the code yesterday, I saw that there should be a tool tip. However, there is not. Also, I can click on the result as much as I want, nothing is ever copied.

I will open another issue about the bug.
