### ISSUE TITLE
scrollbar not displaying in output area

### ISSUE THREAD

**Issue by juliuscrn** [nteract/hydrogen#1965]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Scrollbar is not displaying in the first section of the output area (the one with clock icon). Mouse wheel also does nothing, and there is no way to scroll to the bottom of the output area.

### Steps to Reproduce

```
for i in range(1, 200):
    print(f'{i} test')
```

### Versions

OS version:
Windows 10

> `atom --version`

```
 Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

> `apm --version`

```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 3.7.3
git 2.17.1.windows.2
visual studio
```

Hydrogen version:

2.14.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Expected behavior

A scrollbar should appear on the right hand side.

### Screenshots

The first section of output area does not have scrollbar

![image](https://user-images.githubusercontent.com/10067941/85182235-5c2d7200-b288-11ea-9e6a-1b195aa91363.png)

The second one does

![image](https://user-images.githubusercontent.com/10067941/85182252-68b1ca80-b288-11ea-8558-3f79ce5186d3.png)

### Additional context

More people seem to be having the same problem:

https://discuss.atom.io/t/hydrogen-scrollbar-output-not-displaying/75785

**Comment by juliuscrn** [comment]
This is a pretty big issue. Anyone else having it..?

**Comment by captainsafia** [comment]
@juliuscrn Can you reproduce this issue with other times out outputs (images and charts)?

**Comment by juliuscrn** [comment]
@captainsafia yes, the scroll bar is also missing when I try to render a large chart:

![image](https://user-images.githubusercontent.com/10067941/89125736-df292580-d4e0-11ea-83df-901d8b5b62be.png)

**Comment by domwolfy** [comment]
![scrollproblem](https://user-images.githubusercontent.com/15308128/89178647-6c4ba780-d5d1-11ea-8d69-defb0e1c21a4.PNG)
Same issue for me for a few weeks now

**Comment by BenRussert** [comment]
I looked at this and just opened #1995, take a look if you can @captainsafia or @aviatesk
