### ISSUE TITLE
When I install the hydrogen in terminal, it always gets stuck at this step ：zeromq@5.2.0 install /Users/XXX/node_modules/zeromq

### ISSUE THREAD

**Issue by Lee1125** [nteract/hydrogen#1972]
When I install the hydrogen in terminal, it always gets stuck at this step ：zeromq@5.2.0 install /Users/caolixia/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
And the installation could not be continued. 
__________________________________________________________
Atom version: 1.48.0
Hydrogen version:2.14.1
Mac version: MaOS 10.15.5

**Comment by aminya** [comment]
Please redownload the latest version.
