### ISSUE TITLE
Problem While Installing Hydrogen

### ISSUE THREAD

**Issue by ashishad14** [nteract/hydrogen#1979]
Installing “hydrogen@2.14.4” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...Sd1YhzDT/3GLBJhbUra8J'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ashis\.atom\.apm\_logs\2020-07-02T09_11_35_328Z-debug.log
[2020-07-02T09_11_35_328Z-debug.log](https://github.com/nteract/hydrogen/files/4863179/2020-07-02T09_11_35_328Z-debug.log)

**Comment by captainsafia** [comment]
@ashishad14 The error you're reporting seems like a download error with npm. Can you try re-installing?

**Comment by ashishad14** [comment]
Did it many and this took the whole day finding out the problem, I tried to install Node Package Manager [NPM] it didn't work though, and I tried to install it via command line also using NPM and the APM [atom package manager] and can we build it from the bottom root level is there any option to do it manually like building up the package from source.

**Comment by ashishad14** [comment]
please provide a solution to my problem, why it is not installing the hydrogen package.

**Comment by ashishad14** [comment]
please provide some solution I love atom and wanted to try Hydrogen in it please provide some necessary support for my cause.

**Comment by n-riesco** [comment]
`apm` should've been installed with your distribution of `atom`.
In general, it isn't a good idea to use `npm` to install `hydrogen` or `apm`.

First thing, I'd make sure is that you're running the `apm` installed with your `atom` distribution.

If uninstalling and installing `hydrogen` doesn't solve your problem, a possible workaround is to install an older version of `hydrogen`, e.g.:

```
apm install hydrogen@2.8.0
```

Alternatively, if you're familiar with git you could follow the instructions for developers and use `master`:

```
apm develop hydrogen
cd ~/github/hydrogen ## for windows, use the appropriate path
apm install
apm link --dev
```

**Comment by ashishad14** [comment]
Thank you it worked
