### ISSUE TITLE
[DISCUSSION] Introduce convention to identify private methods

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#198]
I've been reading through more of Hydrogen's code and I would like to introduce **the convention that the names of private methods and properties start with an underscore `_`**.

I'm going to use the `Kernel` class as an example to support this convention.

Currently, `Kernel` defines the following methods: `stderr, connect, interrupt, _execute, execute, executeWatch, complete, inspect, addWatchCallback, onShellMessage, onIOMessage, getResultObject, destroy, getGrammarForLanguage`.

As a user of an instance of Kernel, I'm not interested in methods like: `stderr, connect,  onShellMessage, onIOMessage, getResultObject`.

We could tell Kernel users what methods they're not intended to use, by renaming them as: `_stderr, _connect,  _onShellMessage, _onIOMessage, _getResultObject`.

This convention not only saves time to a person that needs to learn how to use `Kernel`, but also it helps the person that has to refactor `Kernel`, because it minimises the API exposed by `Kernel`.

**Comment by slavaGanzin** [comment]
:+1:

**Comment by n-riesco** [comment]
TODO
- Add a minimal coding style guide
