### ISSUE TITLE
No Kernel for Grammar Python Found

### ISSUE THREAD

**Issue by JBoundless** [nteract/hydrogen#1981]
Hello!  I just installed Hydrogen and have gotten the message "No Kernel for Grammer Python Found", and I have no idea how to solve it.  I have a Mac OS and have confirmed that ipykernel is installed (I did that after I installed Hydrogen).  The settings are still on default and my theme is Light mode.  Thanks in advance!

**Comment by n-riesco** [comment]
See our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#no-kernel-for-grammar-python-found-error-on-mac-os).
