### ISSUE TITLE
Can't import module in Python and wants to reference another py file

### ISSUE THREAD

**Issue by akald** [nteract/hydrogen#1986]
Hyrdogen refers to another unrelated py file ( saved on my Desktop titled 'yfinance.py')to import module. Problem doesn't occur on Spyder.

To import the yfinance module, it wants to open another python file i had previously made but that is completely unrelated to the current py file. It's not a module error since importing yfinance works in Spyder.

### Steps to Reproduce

import yfinance as pd

> `atom --version`
```
1.49.0
```

Hydrogen version: 2.14.4
### Screenshots

![image](https://user-images.githubusercontent.com/59920376/88231369-06bff880-cc6c-11ea-8ee5-81562bde9f18.png)

[Add any other context about the problem here.]

**Comment by aviatesk** [comment]
You can tweak this configuration:
<img width="582" alt="Screen Shot 2020-07-24 at 18 11 19" src="https://user-images.githubusercontent.com/40514306/88376785-14df5780-cdd9-11ea-852e-ee8cee62bee4.png">

**Comment by BenRussert** [comment]
See @aviatesk's comment, that's your solution!
