### ISSUE TITLE
Cannot import treetaggerwrapper module

### ISSUE THREAD

**Issue by rjalexa** [nteract/hydrogen#1988]
!pip3 install treetaggerwrapper
import treetaggerwrapper
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-b920a372b922> in <module>
----> 1 import treetaggerwrapper

ModuleNotFoundError: No module named 'treetaggerwrapper'

### Versions

OS version:
[Your OS's version]
MacOS 10.15.3

> `atom --version`

```
(base) bob@rja15 ~ % atom --version
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

> `apm --version`

```
(base) bob@rja15 ~ % apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 3.6.1
git 2.24.1
```

Hydrogen version:

[Your Hydrogen's version]
(base) bob@rja15 ~ % apm show hydrogen
Hydrogen
├── 2.14.4
├── https://github.com/nteract/hydrogen
├── Run code interactively, inspect data, and plot. All the power of Jupyter kernels, inside your favorite text editor.
├── 1879863 downloads
└── 736 stars
### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [0.08 yes ] hydrogen-python
- [2.14.4 yes ] Hydrogen Launcher
- [ no] Data Explorer

### Expected behavior

expect the library to be loaded just as it happens with the same code from the Mac command prompt

**Comment by aviatesk** [comment]
maybe dup of #1986

**Comment by rjalexa** [comment]
Found a solution 👍 Not sure it is a bug or just my system config being a wreck :)

My machine has TWO python environments managed with pyenv.

While pyenv listed 3.6.1 as the current and python -V from the command line confirmed this and Atom was also using it (as shown by python -V run from a terminal within Atom) and the library being installed for 3.6.1, the error remained UNTIL I reset my global python to 3.7.1 listed by pyenv as DEFAULT, used pip3 to install the library for it and voilà now all runs fine.

Suggestions to fix any Hydrogen or system environment errors very welcome, thanks.
