### ISSUE TITLE
[DISCUSSION] Avoid "Java getters"

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#199]
I've been reading through more of Hydrogen's code and I've noticed an inconsistent use of what I call here "Java getters" (sometimes, we use the method, `getElement`; sometimes, we access the property `element` directly).

For example, if I grep the code for `getElement` and `.element`:

```sh
$ grep -nr getElement lib
lib/main.coffee:86:            @setStatusBarElement kernel.statusView.getElement()
lib/main.coffee:131:            @setStatusBarElement kernel.statusView.getElement()
lib/main.coffee:153:        element = view.getElement()
lib/result-view.coffee:210:    getElement: ->
lib/status-view.coffee:24:    getElement: ->
$ grep -nr "\.element" lib
lib/watch-view.coffee:14:        @inputElement.element.classList.add('watch-input')
lib/watch-view.coffee:25:        @element.appendChild(@inputElement.element)
lib/watch-view.coffee:26:        @element.appendChild(@resultView.element)
lib/watch-view.coffee:106:            @element.removeChild(@resultView.element)
lib/watch-view.coffee:113:        @element.appendChild(@resultView.element)
lib/main.coffee:127:            else if @watchSidebar.element.contains document.activeElement
lib/watch-sidebar.coffee:47:            @watchesContainer.appendChild(watch.element)
lib/watch-sidebar.coffee:84:            @watchesContainer.appendChild watch.element
lib/watch-sidebar.coffee:88:        @createWatch().inputElement.element.focus()
```

There is no need for "Java getters" like `getElement`, we can always define them in Javascript like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get).

Unless there is a usage that I'm missing, I would like to remove all the "Java getters" in Hydrogen.

**Comment by slavaGanzin** [comment]
NP

**Comment by slavaGanzin** [comment]
@n-riesco Did you removed all of them? :smile:

**Comment by n-riesco** [comment]
On 11/06/16 15:28, Slava wrote:
> @n-riesco <https://github.com/n-riesco> Did you removed all of them? 😄

Avoid adding new one would be a good start!

https://github.com/nteract/hydrogen/blob/b50e192db05556aaaf24489ec5d02fb92425061e/lib/kernel-picker.coffee#L7

**Comment by slavaGanzin** [comment]
As I understand from [your link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) I can define getter only this way:
```
Object.defineProperty(o, "b", { get: function })
```
Which looks overcomplicated. And this:
```coffeescript
class Class
  get kernels: ->
```
will raise:

```
get is not defined
```

Any ideas?

**Comment by n-riesco** [comment]
This would do:
```coffeescript
class SignalListView extends SelectListView
    initialize: (@kernels)->
```

**Comment by slavaGanzin** [comment]
Someone(for example I in a month) will treat it as property and forget to call it.

**Comment by n-riesco** [comment]
On 13/06/16 18:45, Slava wrote:
> Someone(for example I in a month) will treat it as property and forget to call it.

Exactly, this is the main reason why the convention is verbs are used to name functions, and nouns to name properties.

Also note that getters and setter in Javascript aren't called (unlike in Java).

**Comment by slavaGanzin** [comment]
Great. But how can i define get(getter) property in coffeescript?

**Comment by n-riesco** [comment]
On 14/06/16 16:36, Slava wrote:
> Great. But how can i define get(getter) property in coffeescript?

You already posted the answer to this question above:

```coffeescript
Object.defineProperty foo, "bar", get: getFooBar
```

**Comment by n-riesco** [comment]
And a more through example:

```coffeescript
Object.defineProperty foo, "bar",
    get: getFooBar
    set: setFooBar
```

**Comment by n-riesco** [comment]
[This issue](https://github.com/jashkenas/coffeescript/issues/451) at the CoffeeScript repository is relevant.

**Comment by slavaGanzin** [comment]
Looks like overkill, that brings nothing new. Get/set in js is syntactic sugar, with object.defineProperty it's opposite. 

I think we should close issue

**Comment by n-riesco** [comment]
On 14/06/16 19:52, Slava wrote:
> Looks like overkill, that brings nothing new. Get/set in js is syntactic sugar, with object.defineProperty it's opposite.
> 
> I think we should close issue

This issue is not about using `Object.defineProperty`.

This is issue (as the title states) is about not using getters and setters. In other words:

* in the case of `getElement()` vs `element`, the property `element` is more common in the code, and thus I would remove `getElement()`.

* in the case of `KernelPicker`, `getKernels` is a property, and thus I would rename it to `kernels`.

* I can't think of any other examples at the moment.
