### ISSUE TITLE
hydrogen takes too long with df.shape or df.head()

### ISSUE THREAD

**Issue by Rcubes** [nteract/hydrogen#1993]
### Prerequisites

* [x ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

In Python scripts Atom takes long time while tryinng to do simple operations such as df.shape or df.head(). These operations are supposed to happen instantly. And the data is not large at all.

### Steps to Reproduce
I can share this files to reproduce the issue:

[CLASE_6.zip](https://github.com/nteract/hydrogen/files/5044590/CLASE_6.zip)

running the python script using the data provided results in this when running the last df.shape and df.head():

![image](https://user-images.githubusercontent.com/48638337/89701811-738fef80-d908-11ea-9e96-b744f913293c.png)

### Versions

OS version:
Windows 10

> `atom --version`

```
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

```

> `apm --version`

```
 Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
(MLprojects) PS C:\Users\fata2810> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 3.7.7
git 2.24.0.windows.2
visual studio
```

Hydrogen version:

2.14.4

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

I haven´t, since I´m using Hydrogen for Data Science in Python should install hydrogen-python?

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]
![image](https://user-images.githubusercontent.com/48638337/89701908-67586200-d909-11ea-8ae5-f56273503662.png)

### Expected behavior

df.shape or df.head() should take no longer than a second.

### Screenshots

[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/48638337/89701919-8d7e0200-d909-11ea-861b-410abad6e7df.png)

![image](https://user-images.githubusercontent.com/48638337/89701923-9b338780-d909-11ea-8aea-20ee8938b6dc.png)

### Additional context

If you run the provided script as is it will run super fast. If you delete lines 115 and 116 and type them again you should see the screenshots shown above.

I have no idea why this happens only sometimes, but only with commands that are supposed to be instant.

I will appreciate any help you can provide.

Thanks,

**Comment by Rcubes** [comment]
Just wanted to add that df.sum() totally kills the kernel making it completely unsuable. And interrupting kernel is not allowed in windows so I´m forced to restart kernel and start over.

**Comment by BenRussert** [comment]
I cannot reproduce on Windows 10 with the latest atom and hydrogen version. I used your example files.

Is this only when first starting up a kernel or anything else that you can clarify? Check what the kernel status is, I'm guessing it did not start up properly and somehow got in a state where any command will just hang waiting for the kernel.

**Comment by Rcubes** [comment]
Sorry the delay in the response. This is something super common. I´ve tried in my computer running WIndows and a friend´s computer running Linux, and everytime the kernel is set, I had run the commands and afterwards I re-run df.shape or df.head() takes a long time. Normally a df.shape should take no time, and in my case it takes up to 20 seconds.

Running some other tests I noticed it is the . notation commands the ones giving issues. df.shape, df.var (var being any column name of my df), df.dtypes, df.columns, etc.

I don´t know any other way to demonstrate the issue, and it is disappointing because I haven´t found anything like hydrogen that for me it is the perfect way to run data science scripts so having this kind of inconvenience is a huge setback.

Is there any way i could help to try to solve my issue?

Thanks in advance
