### ISSUE TITLE
Viewing full data

### ISSUE THREAD

**Issue by akald** [nteract/hydrogen#1997]
How can I view the whole dataset in Atom Hydrogen without it showing the three dots in Python?
For example:
df

year      price
2014        4
2012        4
...
2020        6

**Comment by BenRussert** [comment]
Assuming that `df` is a pandas `DataFrame` this is a pandas option they [document here](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html).

```
In [1]: import pandas as pd

In [2]: pd.options.display.max_rows
Out[2]: 15

In [3]: pd.options.display.max_rows = 999

In [4]: pd.options.display.max_rows
Out[4]: 999
```

You can also use `None` to have no limit, but please keep in mind that performance will suffer at some point and _you could crash atom_. In the past I've found that it ends up being much better to aggregate, filter, or somehow limit output to the rows you might reasonably want to read.

**Comment by akald** [comment]
I believe on Visual Studio it will show all columns if I decide to scroll all the way through the pandas dataframe.
