### ISSUE TITLE
[Discussion] modify Hydrogen icon

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#200]
What do you think about modifying the Hydrogen icon?
I played a bit with the colors and the stroke width. The color is from atoms default theme so it fits in well.
Old vs new:
<img width="253" alt="old" src="https://cloud.githubusercontent.com/assets/13285808/13788243/594dbcc2-eadf-11e5-9838-d21fee8b6323.png"><img width="257" alt="new" src="https://cloud.githubusercontent.com/assets/13285808/13788129/efd56f4c-eade-11e5-8059-9425c511a27e.png">
For me this looks a bit cleaner.

**Comment by rgbkrk** [comment]
Could we apply a filter based on the user's theme?

**Comment by lgeiger** [comment]
That would be great. But I don't know if this is possible.

**Comment by lgeiger** [comment]
I tried it but couldn't get a filter based on the user's theme to work.

**Comment by rgbkrk** [comment]
That's ok. I think we'd have to switch formats to use CSS filters well here.
