### ISSUE TITLE
Missing environment variables within Python kernel started from Hydrogen

### ISSUE THREAD

**Issue by mlangiu** [nteract/hydrogen#2000]
### Description

When starting a Python kernel through Hydrogen, the environment variables are different from those of the Python shell or IPython / Jupyter notebooks.
In particular variables that are defined in `.bash_rc` or similar seem to be ignored.
This is especially problematic for things like LD_LIBRARY_PATH or DYLD_LIBRARY_PATH which may be needed for the execution of other programs.

### Steps to Reproduce

1. Define environment variables, e.g., via `export TEST='HELLO WORLD'` in `.bash_rc`
2. from Python shell, IPython or Jupyter notebook
    ```python
    import os
    os.environ['TEST']
   >>>'HELLO WORLD'
    ```
3. from Python kernel started via Hydrogen in Atom:
    ```python
    import os
    os.environ['TEST']
    KeyError: 'TEST'
    ```
### Versions

OS version:
macOS Catalina 10.15.6 (19G2021)

> `atom --version`

```
Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

> `apm --version`

```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.27.0
```

Hydrogen version:

[Your Hydrogen's version]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [x] hydrogen-python
- [x] Hydrogen Launcher
- [ ] Data Explorer

### Expected behavior

Same as from Python shell, IPython or Jupyter notebook

**Comment by qchenevier** [comment]
@mlangiu For atom (& Hydrogen) to access your environment variables, you have to start `atom` from a shell environment containing those environment variables:

Example, if you type in your shell:
```bash
$ export MYVAR=MYVALUE
$ atom .
```

You should be able to access your env variable from within Hydrogen:
```python
import os
os.environ['MYVAR']
```
This should print `'MYVALUE'`

This is the same mechanism which allows you to access various conda environment with atom: you have to activate the conda env in your shell (modifying it env variables) before starting atom from this shell.

**Comment by mlangiu** [comment]
Ok got it, unfortunately the `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` still don't show up. However, that appears to be due to newer MacOS versions actively trying to prevent this and doesn't seem to be an issue of Hydrogen, so I'll close this issue.

Thanks for your help!
