### ISSUE TITLE
No kernel for grammar Python found

### ISSUE THREAD

**Issue by O-Developer** [nteract/hydrogen#2020]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hi, i'm sorry to bother the community but i've looked at other posts with the same issue i'm having and i've tried alot of solutions and it's not working, any help would be appreciated, thank you, sorry.

'No kernel for grammar Python found

Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.

To detect your current Python install you will need to run:

python -m pip install ipykernel
python -m ipykernel install --user'

Is there something i'm missing?

### Steps to Reproduce

1. Install hydrogen
2. python -m pip install ipykernel
    python -m ipykernel install --user
3. installed packages checked below
4. updated the kernel
5. tried to run my code

### Versions

OS version:
Windows 10 Home 1909

> `atom --version`

```
Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```

> `apm --version`

```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python
git
visual studio
```

Hydrogen version:

[2.14.6]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [x] hydrogen-python
- [x] Hydrogen Launcher
- [x] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

I would like it to run my code

### Screenshots

<img width="345" alt="Capture" src="https://user-images.githubusercontent.com/64183294/98310093-0bfb4600-1fc4-11eb-8a84-62f502ba277e.PNG">

### Additional context

I'd also like to use hydrogen for my c# code and maybe others

**Comment by captainsafia** [comment]
@O-Developer Have you confirmed that Atom is installed in the same environment where your Jupyter kernels are?

**Comment by O-Developer** [comment]
> 
> 
> @O-Developer Have you confirmed that Atom is installed in the same environment where your Jupyter kernels are?

I've managed to get c# to run, however there are some glitches with running my code (like not taking input) but python isnt working at all and is giving the above error. 
I tried to install globally (without virtual enviroment)
How do i check it's installed in the same enviroment?? 

Sorry,
Thank you

**Comment by captainsafia** [comment]
> I tried to install globally (without virtual enviroment)

Then it looks like you have it installed in the same environment since you are not using virtual envs. Do the kernels work if you connect to them from Jupyter Notebook?

**Comment by O-Developer** [comment]
> 
> 
> > I tried to install globally (without virtual enviroment)
> 
> Then it looks like you have it installed in the same environment since you are not using virtual envs. Do the kernels work if you connect to them from Jupyter Notebook?

Im sorry for the really late replies. Yes the kernels do work when i connect to them from Jupyter notebook
