### ISSUE TITLE
Kernel hardcode

### ISSUE THREAD

**Issue by slavaGanzin** [nteract/hydrogen#203]
Anybody knows is this lines actual?
https://github.com/nteract/hydrogen/blob/master/lib/kernel.coffee#L33-L45

This clobber should be removed.

**Comment by n-riesco** [comment]
In the past, it was possible for Hydrogen to run IPython without installing a kernel spec. Last time I tried this, it didn't work and I had to set the kernel spec in Hydrogen's settings.

**Comment by n-riesco** [comment]
Just to be clear:

To decide whether that piece of code should be fixed or removed, we need to decide whether Hydrogen will support only installed kernels.


I've just checked the `README.md` and I think it needs updating:

- the dependencies section should specify what versions (Atom. Node, IPython, Jupyter, ZMQ) are required.

- stress more the need to install a kernel.

**Comment by rgbkrk** [comment]
> stress more the need to install a kernel

I agree with this one. Jupyter assumes a default kernel of the python for that version of jupyter. We can't reliably start what the "default" is either. We need our instructions to include:

```
python3 -m pip install ipykernel
python3 -m ipykernel install --user
```

**Comment by lgeiger** [comment]
> the dependencies section should specify what versions (Atom. Node, IPython, Jupyter, ZMQ) are required.

Node is just a development dependency, isn't it? I remember using hydrogen in the past without a separate Node installation on my system. Or am I wrong?

**Comment by rgbkrk** [comment]
> I remember using hydrogen in the past without a separate Node installation on my system. Or am I wrong?

As long as Atom is able to build zmq from within Atom, you don't have to have node installed globally. Actually, as long as `apm` handles the node-gyp stuff correctly, we don't have to have node.

**Comment by n-riesco** [comment]
On 18/03/16 18:50, Lukas Geiger wrote:
> Node is just a development dependency, isn't it? I remember using hydrogen in the past without a separate Node installation on my system. Or am I wrong?

You're right. Specifying the Atom version is enough.
