### ISSUE TITLE
Zeromq doesn't build on Electron 9

### ISSUE THREAD

**Issue by aminya** [nteract/hydrogen#2034]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hydrogen fails to build on Atom with Electron 9. 

Full log is included in the log section. This is a summary:
```
❯ apm-dev rebuild --verbose
Rebuilding modules failed
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\aminy\\Documents\\GitHub\\JavaScript\\@atom-ide-community\\atom\\out\\Atom Dev x64\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\aminy\\Documents\\GitHub\\JavaScript\\@atom-ide-community\\atom\\out\\Atom Dev x64\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\.atom\packages\Hydrogen\node_modules\zeromq
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aminy\.atom\.apm\_logs\2020-12-16T23_12_45_444Z-debug.log
```

### Steps to Reproduce

1. Build Atom in https://github.com/atom/atom/pull/21805
2. Try to build Hydrogen with the included apm under `./out/Atom Dev x64/resources/app/apm/bin/apm`

### Versions

OS version:
[Your OS's version]

> `atom --version`

```
❯ atom-dev9 --version

Atom    : 1.56.0-dev-ffaba34b3
Electron: 9.3.5
Chrome  : 83.0.4103.122
Node    : 12.14.1
```

> `apm --version`

```
❯ apm-dev --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0-dev-ffaba34b3
python 3.6.8
git 2.29.2.windows.3
visual studio
```

Hydrogen version:

Hydrogen 2.14.6

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

Here is a full log:
[2020-12-16T23_12_45_444Z-debug.log](https://github.com/nteract/hydrogen/files/5705979/2020-12-16T23_12_45_444Z-debug.log)

### Expected behavior

[A clear and concise description of what you expected to happen.]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by joseph5119** [comment]
> 
#1369 
>

**Comment by aminya** [comment]
@ntract

**Comment by aminya** [comment]
I made a fix for this in Zeromq. We need to wait until that is merged to Zeromq and then Jmp.
https://github.com/zeromq/zeromq.js/pull/444

**Comment by dahaorendrm** [comment]
Same problem here.

**Comment by WhyBeU** [comment]
Regarding #2077 is this the fix : "We need to wait until that is merged to Zeromq "
Any recommendation meanwhile?
Thanks.

**Comment by aminya** [comment]
@captainsafia is registering the [a patched ZeroMQ](https://github.com/zeromq/zeromq.js/pull/445). After that one is registered, I will quickly create a PR to fix it. I will do my best to fix the issue as soon as possible, hopefully, tonight or tomorrow at the latest.


For now, you can use Atom 1.55. Fortunately, Atom doesn't remove the previous version, and you can actually use it. Here is my Atom installation which still has 1.55.

![image](https://user-images.githubusercontent.com/16418197/114662700-c2273200-9cbe-11eb-9e2e-c5f5c4882dc8.png)

**Comment by aminya** [comment]
Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉

**Comment by DOOMKEKER** [comment]
same problem with Hydrogen 2.15.3  :c
