### ISSUE TITLE
Traceback Error, Python3.9.1, Mac OS 11.0.1

### ISSUE THREAD

**Issue by kylemichaelreaves** [nteract/hydrogen#2036]
Hydrogen updates the kernel but then gives a Traceback Error. It was working fine a few days ago. 

<img width="605" alt="Screen Shot 2020-12-21 at 4 15 34 PM" src="https://user-images.githubusercontent.com/10997232/102822882-dd84cf00-43a7-11eb-9e18-322f40aafdfa.png">

Output of atom -- version: 
```
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

```
Output of apm --version: 
```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 2.7.18
git 2.24.3
```
OS version:
Mac OS 11.0.1

Hydrogen version:
2.14.6

Jupyter Labs is working fine, which is even more puzzling to me, as I thought Hydrogen was dependent on that kernel. 

```
jupyter --paths
config:
    /Users/kylereaves/.jupyter
    /usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/kylereaves/Library/Jupyter
    /usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/kylereaves/Library/Jupyter/runtime
```

Here is the location of the kernel:
```
jupyter kernelspec list
Available kernels:
  python3    /Users/kylereaves/Library/Jupyter/kernels/python3
```

Both the terminal and Jupyter Labs both execute from the same location. Here is the output from the terminal:
```
python3
Python 3.9.1 (default, Dec 20 2020, 23:21:19) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, platform
>>> sys.executable
'/usr/local/opt/python@3.9/bin/python3.9'
>>> platform.python_version()
'3.9.1'

```
And here is the output from Jupyter Labs:
<img width="1161" alt="Screen Shot 2020-12-21 at 4 35 13 PM" src="https://user-images.githubusercontent.com/10997232/102824376-b54a9f80-43aa-11eb-81ca-2166171530b6.png">

Thank you for your help in advance.

**Comment by kylemichaelreaves** [comment]
I uninstalled ipykernel and then reinstalled it according to https://nteract.io/kernels. I had done this before, and I am not sure what was different about this time. But I was I opened a new .py document, printed out the system version, and It worked. I'm still very confused but glad it's working again 
<img width="837" alt="Screen Shot 2020-12-22 at 6 19 35 PM" src="https://user-images.githubusercontent.com/10997232/102942448-57d65180-4483-11eb-8b41-c4f7fe7a54fb.png">

**Comment by willingc** [comment]
@kylemichaelreaves I'm not sure why it didn't work the first time. I suspect that one of the components that ipykernel installs was not fully updated. The uninstall/reinstall removed the out-of-date dependency. Thanks for using Hydrogen too. ☀️
