### ISSUE TITLE
Hydrogen fails after upgrading Atom

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#2038]
Atom is telling me this is the same issue, which is why I am posting this here, though it doesn't seem so to me… 

1. Try to run any cell in, with any kernel.
2. *Error*

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Failed to activate the Hydrogen package

```
At The module '/Users/avanavana/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/Users/avanavana/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

### Commands

```
     -1:08.9.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
Chromo-Color-Previews 1.8.3 
color-picker 2.3.0 
Hydrogen 2.14.6 
intentions 1.1.5 
jekyll 2.1.0 
jekyll-syntax-highlighting 0.1.0 
language-babel 2.85.0 
language-graphql 1.0.0 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.3.4 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
process-palette 0.17.0 
teletype 0.13.4 
termination 0.7.6 
zotero-citations 5.2.0 
```

Note:  this happened AFTER i tried `npm rebuild` in the `.atom/packages/Hydrogen` directory.   I had previously tried uninstalling/reinstalling, running `apm rebuild`, etc to no avail.    But I received the exact same error before doing these things as well, the only difference is after running `npm rebuild` Atom supplemented the error message with a button that linked here and a button to copy my error text.  Initially I could not do either, nor is the message with the "Rebuild Package" button showing up.   

I thought this might be happening because I upgraded my node to 14.15, but then I read that atom uses its own version—so I don't know what's going on.  Can't seem to fix it.   

EDIT: If I do `apm rebuild` in the package directory as recommended, nothing happens.  If I then do `apm install` in the package directory as also recommended, I am back to the original error:

```
internal/modules/cjs/loader.js:1122 return process.dlopen(module, path.toNamespacedPath(filename)); ^

Error: The module '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build/Release/zmq.node' 
was compiled against a different Node.js version using NODE_MODULE_VERSION 64. This version of Node.js
requires NODE_MODULE_VERSION 83. Please try re-compiling or re-installing the module (for instance, using
npm rebuild or npm install). at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18) at
Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object. 
(/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at
Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

_Originally posted by @avanavana in https://github.com/nteract/hydrogen/issues/2032#issuecomment-751430374_

**Comment by n-riesco** [comment]
@avanavana This type of error happens when Atom is upgraded and binary modules as `zeromq` haven't. Uninstalling Hydrogen and installing it again should solve the issue (`rebuild` didn't use to work in the past, even with `yarn`; I haven't tried recently).

Also note that `zeromq@5` doesn't provide binaries for `NODE_MODULE_VERSION 83`, so you'll need to make sure your installation has the necessary requirements ([see here](https://github.com/zeromq/zeromq.js/tree/5.x#installation---from-source)).

**Comment by avanavana** [comment]
@n-riesco Yes, I tried uninstalling and reinstalling through Atom's built-in package manager GUI several times, along with several permutations of the above highlighted terminal commands (`npm rebuild` `apm rebuild` `npm install` `apm install`).   I had seen a similar comment when searching this issue regarding specifying the electron runtime, but I am confused with regard to which `NODE_MODULE_VERSION` corresponds to which `--runtime=electron` `--target`…

**Comment by n-riesco** [comment]
It's not listed in the requirement, but if my memory serves me well, to build the binary for `zeromq@5`, you also need to install the zeromq header files. See https://zeromq.org/download/ .

**Comment by n-riesco** [comment]
if this doesn't solve the problem, the output of `apm install` may contain more info on what's wrong.

**Comment by hanryhu** [comment]
I had the same issue, and was able to resolve the problem by going to `~/.atom/packages` and doing `apm install Hydrogen`.  I did first go into `~/.atom/packages/Hydrogen/` and do `npm install zeromq`, but that didn't work.

**Comment by aminya** [comment]
Fixed by #2082

**Comment by aminya** [comment]
Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉

**Comment by avanavana** [comment]
I upgraded and still had the same problem.   However, I was then able to
```shell
cd /usr/local/lib/node_modules/ijavascript
npm rebuild
```
And it works like a charm now ;)
