### ISSUE TITLE
Plotting does not work.  

### ISSUE THREAD

**Issue by dpavlic** [nteract/hydrogen#204]
I have an odd problem where graphs will not show.  Sometimes they will show, but they pop up in a new window.  Most of the time, however, they just plain do not work.  I am reproducing a very simple matplotlib graph (indeed, this is on their example page) that works in qtconsole.  Code below:

`
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2*np.pi*t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()
`

I get an empty box inline when I try to run this.  Attached is a picture.
![no_graph](https://cloud.githubusercontent.com/assets/1075079/13861801/b5de710c-ec65-11e5-892c-23a4eafb477a.png)

**Comment by n-riesco** [comment]
What you see is the output of the last command `plt.show()`, which doesn't return anything.

Try adding `plt` at the end of your code:

```python
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2*np.pi*t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()
plt
```

**Comment by n-riesco** [comment]
This is working in master.

I will check if I can reproduce the issue in the package available on the Atom package repository.

**Comment by n-riesco** [comment]
It's working for me on v0.7.2.

@dpavlic Could you open the dev console in Atom (press shift-ctrl-i) and run the code again.

You will see many log messages in the console. The one I would like to see is the last IO message that has the `prefix` set to `"display_data"`. This is what I see in my case:

![untitled](https://cloud.githubusercontent.com/assets/6199391/13864257/e83e39c0-ec97-11e5-89dd-1abf1893d9f8.png)

**Comment by dpavlic** [comment]
Well, this definitely gets me somewhere!

`
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAEZCAYAAAC5AHPcAAAABHNCS…EYRlaYATEMwzCywgyIYRiGkRVmQAzDMIysMANiGIZhZMX/A2UzvhGjTNruAAAAAElFTkSuQmCC' because it violates the following Content Security Policy directive: "default-src *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
module.exports.ResultView.addResult @ result-view.coffee:126(anonymous function) @ main.coffee:136module.exports.Kernel.onIOMessage @ kernel.coffee:288emitMany @ events.js:108emit @ events.js:182Socket._flush @ /home/dpavlic/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:573_zmq.onReady @ /home/dpavlic/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:203
result-view.coffee:148 resultType after update: image
`

**Comment by n-riesco** [comment]
I've just noticed that the development version of atom that I'm using has a "Content-Security-Policy" awfully unsafe:

![untitled](https://cloud.githubusercontent.com/assets/6199391/13872708/4a8eb69e-ece4-11e5-9332-4832c41330a4.png)

@dpavlic Please, could you check what "Content-Security-Policy" your Atom installation is using?

- Open the dev console (press shift-ctrl-i).
- Press shift-ctrl-c to enable the inspect pointer and click on the pane where Hydrogen is running.
- Now the dev console should be showing the HTML content of that pane.
- Scroll up to the top and expand the `<head>` tag and you'll find a `<meta>` tag that sets the "Content-Security-Policy".

**Comment by n-riesco** [comment]
It seems to me that this is an issue in Atom, which is "fixed"  in Atom 1.7.0-beta0; more specifically, in this PR https://github.com/atom/atom/pull/9627 .

**Comment by dpavlic** [comment]
Content security policy is same as your example above.  I will pull the beta and report soon.

**Comment by n-riesco** [comment]
That's surprising! I posted what I get using the beta.

I believe Atom v1.6.0 is missing `img-src data: *;` in the `"Content-Security-Policy"` and that makes Hydrogen fail the security policy..

**Comment by dpavlic** [comment]
No -- you're absolutely right, I was too hasty to declare them the same.  I don't have img-src data *;

I cannot test at the moment, as Arch fails to load the beta.  I will see if I can dig out another distro and see how things stand there.

**Comment by dpavlic** [comment]
To confirm: there is _no_ problem with Atom 1.7.0-beta0.  Thank you very much for your help, I am closing this one.
