### ISSUE TITLE
Pandas dataframes cut off

### ISSUE THREAD

**Issue by dpavlic** [nteract/hydrogen#205]
Attempting to display a pandas dataframe returns a HTML representation (great!), however, scrolling around the dataframe does not seem to work: the display clips.
![dataframe_issue](https://cloud.githubusercontent.com/assets/1075079/13861880/24f68cb4-ec66-11e5-9996-9343370d2b0f.png)

**Comment by n-riesco** [comment]
I can confirm this is also happening in master.

@slavaGanzin , @lgeiger , @rgbkrk,  Perhaps, we should offer the option to show large results in a tab.

I've been also toying with the idea that large outputs are initially shown collapsed, and expand only when clicked.

**Comment by dpavlic** [comment]
Those are both great ideas... particularly the tab.  I should not the content clips horizontally if the dataframe is set as a watch, though it will scroll vertically.
