### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by bakananna** [nteract/hydrogen#2052]
OS version:
Windows 10
> `atom --1.54.0`
```
6.1.12
76.0.3809.146
v12.4.0
```

Hydrogen version:
2.14.7

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [yes] hydrogen-python
- [yes] Hydrogen Launcher
- [yes] Data Explorer

### Expected behavior
Module Not Found Error : pandas, numpy, etc
Already did everything I can find online including
- installing modules manually
- pip install pandas
- added modules to path

I have ipython and ipykernal installed
I have python version 3.8 and 3.9.1

### Screenshots
![image](https://user-images.githubusercontent.com/78588838/107009612-3e3d5f00-67d0-11eb-9f2f-039db25266f1.png)

**Comment by ramantehlan** [comment]
Hey @bakananna, I don't think this is an issue with hydrogen. 

I think the issue might be with your environment. Since you have two python versions installed.
you might have to add the module to the environment you are using by default.

Something like this...
`python3 -m pip install pandas`

**Comment by bakananna** [comment]
Hi, thanks for the reply.

But when I tried to run  `python3 -m pip install pandas` it says 

> Python was not found

So I ran `python -m pip install pandas` instead and it says

> Requirement already satisfied:
 > pandas in c:\users\neohu\appdata\roaming\python\python39\site-packages (1.2.1)
 > pytz>=2017.3 in c:\users\neohu\appdata\roaming\python\python39\site-packages (from pandas) (2021.1)
 > python-dateutil>=2.7.3 in c:\users\neohu\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.8.1)
 > numpy>=1.16.5 in c:\users\neohu\appdata\roaming\python\python39\site-packages (from pandas) (1.20.0)
 > six>=1.5 in c:\users\neohu\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

Does this mean I have to change to python3 somehow or is there a way to tell atom which version I'm using?

**Comment by ramantehlan** [comment]
Okay, `python` is pointing to `python39`.
Have you installed Python kernels https://nteract.io/kernels/python?

```
python -m pip install ipykernel
python -m ipykernel install 
```

**Comment by bakananna** [comment]
Yup, I did.

**Comment by bakananna** [comment]
![image](https://user-images.githubusercontent.com/78588838/107803262-55b2b400-6d9d-11eb-8599-9d88bbb763db.png)

I think I found the problem.. somehow the kernel is still pointing to python38. How can I change the specs?

**Comment by ramantehlan** [comment]
Okay, not sure if this will work, but try this. 

Install kernel again with python3.8.
```
python3.8 -m pip install ipykernel
python3.8 -m ipykernel install 
```

And then install your modules in that python. 
```
python3.8 -m pip install pandas
```

**Comment by bakananna** [comment]
Great! That works. Thank you so much
