### ISSUE TITLE
Uncaught ReferenceError: Jupyter is not defined

### ISSUE THREAD

**Issue by preethiraju-vungle** [nteract/hydrogen#2053]
I was trying to open an existing Jupyter notebook (ipynb) and it gives me the error Uncaught ReferenceError: Jupyter is not defined. 

### Stack Trace

Uncaught ReferenceError: Jupyter is not defined

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:6

ReferenceError: Jupyter is not defined
    at eval (/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/javascript.js:16:16), <anonymous>:6:33)
```

These are my packages: 
```
Hydrogen 2.14.7 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
ide-python 1.7.3 
```

When I try to install jupyter-notebook, it gives a long error: 
![image](https://user-images.githubusercontent.com/71674638/107118508-88b1f080-684f-11eb-926b-35e04ff642dc.png)

Other info: 
**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.7

**Comment by aminya** [comment]
Please redownload the latest version.
