### ISSUE TITLE
Hydrogen says Javascript variable is not defined, when it clearly is

### ISSUE THREAD

**Issue by rozay28** [nteract/hydrogen#2064]
Do you want to ask a question ? Are you looking for support? The #hydrogen channel in nteract slack is the best place for getting support. Feel free to ping us on: https://slack.nteract.io
**Do not have email with domain at any of the specified sites**

### Description

Hello, noob here so forgive the likely easily solvable question.  Didn't see anything in the already solved issues.

I have installed Atom, Hydrogen, Conda, and Jupyter, as well as the kernel for JavaScript.  Running on macOS.  When I try to run and console log my code, I get the error "Variable not defined" when it clearly is.

### Steps to Reproduce
Code: 

let x = 1
console.log(x)

Output:
evalmachine.<anonymous>:1
console.log(x)
            ^

ReferenceError: x is not defined
    at evalmachine.<anonymous>:1:13
    at Script.runInThisContext (vm.js:133:18)
    at Object.runInThisContext (vm.js:310:38)
    at run ([eval]:1054:15)
    at onRunRequest ([eval]:888:18)
    at onMessage ([eval]:848:13)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

### Versions
**Atom Version**
Atom    : 1.55.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

**OS version:**
macOS Big Sur 11.1

**apm version**
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.55.0
python 3.8.5
git 2.24.3

Hydrogen version:
2.14.7

Have you installed and activated any of the Hydrogen plugins below ?
- [No] hydrogen-python
- [No] Hydrogen Launcher
- [No] Data Explorer

### Logs
Doesn't look like there are any error logs, but here is the console data if it helps:

Hydrogen: findCodeBlock: 5
utils.js? [sm]:174 Hydrogen: CellManager: Cell [start, end]: (2) [Point, Point]0: Pointcolumn: 0row: 0__proto__: Object1: Pointcolumn: 0row: 6__proto__: Objectlength: 2__proto__: Array(0) anyPointInCell: Point {row: 5, column: 14}
utils.js? [sm]:174 Hydrogen: ZMQKernel.execute: console.log(x)
utils.js? [sm]:174 Hydrogen: IO message: Message {idents: Array(1), header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}buffers: []content: {execution_state: "busy"}header: {msg_id: "e0024e00-ce47-4e3e-8321-24cb9921a7b8", username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "status", version: "5.0"}idents: [Uint8Array(42)]metadata: {}parent_header: {username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_request", msg_id: "execute_9da073b6-e0c2-4a3b-805e-fc08046c8bf2", date: "2021-04-10T16:33:06.731Z", …}__proto__: Object
utils.js? [sm]:174 Hydrogen: IO message: Message {idents: Array(1), header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}buffers: []content: {execution_count: 3, code: "console.log(x)"}header: {msg_id: "3d2c3eb9-49df-4e49-bf05-e3784505f451", username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_input", version: "5.0"}idents: [Uint8Array(42)]metadata: {}parent_header: {username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_request", msg_id: "execute_9da073b6-e0c2-4a3b-805e-fc08046c8bf2", date: "2021-04-10T16:33:06.731Z", …}__proto__: Object
utils.js? [sm]:174 Hydrogen: shell message: Message {idents: Array(0), header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}buffers: []content: {status: "error", execution_count: 3, ename: "ReferenceError", evalue: "x is not defined", traceback: Array(14)}header: {msg_id: "c05132de-e2f0-4000-93ee-b0ead4ab078e", username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_reply", version: "5.0"}idents: []metadata: {}parent_header: {username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_request", msg_id: "execute_9da073b6-e0c2-4a3b-805e-fc08046c8bf2", date: "2021-04-10T16:33:06.731Z", …}__proto__: Object
utils.js? [sm]:174 Hydrogen: IO message: Message {idents: Array(1), header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}buffers: []content: {execution_count: 3, ename: "ReferenceError", evalue: "x is not defined", traceback: Array(14)}header: {msg_id: "9f829ce2-147c-438c-b2d5-bf3ac1230ab4", username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "error", version: "5.0"}idents: [Uint8Array(42)]metadata: {}parent_header: {username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_request", msg_id: "execute_9da073b6-e0c2-4a3b-805e-fc08046c8bf2", date: "2021-04-10T16:33:06.731Z", …}__proto__: Object
utils.js? [sm]:174 Hydrogen: IO message: Message {idents: Array(1), header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}buffers: []content: {execution_state: "idle"}header: {msg_id: "63a75d47-68e9-4cf5-ad3e-e10a459fbe06", username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "status", version: "5.0"}idents: [Uint8Array(42)]metadata: {}parent_header: {username: "rosslamerson", session: "00000000-0000-0000-0000-000000000000", msg_type: "execute_request", msg_id: "execute_9da073b6-e0c2-4a3b-805e-fc08046c8bf2", date: "2021-04-10T16:33:06.731Z", …}__proto__: Object
utils.js? [sm]:174 Hydrogen: watchview running: 

### Expected behavior
Console should display 1

### Screenshots
<img width="700" alt="Screen Shot 2021-04-10 at 11 35 35 AM" src="https://user-images.githubusercontent.com/82220715/114277467-efd75700-99f0-11eb-8f95-2f48aa28f003.png">

Thank you in advance!

Rozay

**Comment by n-riesco** [comment]
It looks like you've tried to run the line where the cursor is.
I guess what you're after is `hydrogren:run-cell`.

**Comment by n-riesco** [comment]
Please, see how to get started in the documentation: https://nteract.gitbooks.io/hydrogen/content/docs/Usage/GettingStarted.html

**Comment by aminya** [comment]
I think we should be able to somehow detect these kinds of errors and let the user know that they are using the wrong command.

**Comment by n-riesco** [comment]
perhaps, a visual cue, highlighting the code block that was run?

**Comment by aminya** [comment]
> perhaps, a visual cue, highlighting the code block that was run?

Yes, Atom Ink had this thing.
https://github.com/JunoLab/atom-ink

**Comment by aminya** [comment]
I am closing this in favor of #2065
