### ISSUE TITLE
Hydrogen stopped working

### ISSUE THREAD

**Issue by bcalvr** [nteract/hydrogen#2081]
After a computer restart which included a Windows update, my Atom would no longer run Hydrogen. I tried uninstalling and reinstalling hydrogen, and now hydrogen won't install, and kicks out a whole slew of errors around not being able to find python. I've attached the log file in case it's helpful, along with a screenshot of the errors - please help!

Ben

![image](https://user-images.githubusercontent.com/49484388/114807560-7d9da400-9d5b-11eb-82bf-4975dff74ce0.png)

[2021-04-15T02_36_05_824Z-debug.log](https://github.com/nteract/hydrogen/files/6314905/2021-04-15T02_36_05_824Z-debug.log)

**Comment by aminya** [comment]
Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉

**Comment by bcalvr** [comment]
> 
> 
> Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉

Amazing, thank you so much!
