### ISSUE TITLE
Does not work any more for markdown code blocks

### ISSUE THREAD

**Issue by matrix-ranger** [nteract/hydrogen#2098]
### Description

In the lastest version of Hydrogen and Atom, code blocks won't run in Markdown files. It says "No kernel for grammar Markdown found". BTW I am using the `language-markdown` extension in conjunction here. Though that extension has not been actively maintained for several years, I think it used to work well around two or three months ago, which was last time I checked.

### Versions

macOS Big Sur 11.3.1
Atom 1.56.0 x64
Hydrogen 2.15.3

**Comment by matrix-ranger** [comment]
Do people still use Hydrogen these days? Or is there anyone still use Atom at all? I thought Markdown editing should be a basic feature for an editor. But even such daily used tool is not maintained for Atom.

**Comment by aminya** [comment]
Use markdown-preview-plus

https://atom.io/packages/markdown-preview-plus

**Comment by matrix-ranger** [comment]
You misunderstood me. I mean even things like your example does not work in Hydrogen with the version provided. No code cells can be executed when you click ctrl/cmd+enter

**Comment by matrix-ranger** [comment]
When you click ctrl/cmd+enter in the code cell, it says "No kernel for grammar Markdown found" instead of running the cell.

**Comment by aminya** [comment]
I cannot reproduce your situation. Please upload the markdown file you are trying to run.

**Comment by matrix-ranger** [comment]
I see. I just found out that the problem is it does not recognize the code cell language if you use `Python` instead of `python` or `py`. It is case sensitive.
[a.md](https://github.com/nteract/hydrogen/files/6557600/a.md)
