### ISSUE TITLE
This package doesn't work!!!!!!!!!!

### ISSUE THREAD

**Issue by austino3** [nteract/hydrogen#2101]
I've now spent at least a dozen hours trying to make Atom.io work!!!  I've done countless google searches and watched dozens of videos.  I cannot find a package that will let me run my fucking code!  "script" worked but then when I ran a prgoram that asked for input it didn't work.  I downloaded Hydrogen and it won't work either!!  I don't understand what I'm doing wrong!! I'm just trying to take a fucking programming class and I've now spent all day just trying to get the software to work.  I haven't gotten to write a single line of code all day because of this stupid thing.  I downloaded Hydrogen.  I clicked run. I got an error message that I don't understand.  Hydrogen sucks.  Atom.io sucks.

**Comment by aminya** [comment]
I'm closing this issue as it violates [the code of conduct](https://github.com/nteract/hydrogen/blob/f6612adc66cabc3a1427c0a3ba1a7a3b75b15581/CODE_OF_CONDUCT.md). If you are looking for help, please provide reproduction steps with clear error messages in a respectful language.
