### ISSUE TITLE
Hydrogen package does not work. Won’t run the program. Just returns error message “kernel not installed”

### ISSUE THREAD

**Issue by austino3** [nteract/hydrogen#2102]
Are you kidding me??? Excuse me???? Someone just closed my comment? There is a problem with the product and you just silenced my complaint?  Wow! That’s rich.  I guess you don’t care about the product actually working or helping people figure out how to use it. I don’t know what reproduction steps are. You want me to take screenshots or something? I already closed it all. I don’t have time to go back through it and take pictures. I told you what the problem is. Either tell me how to fix it or tell me to go f*** myself and I’ll know never to use this software or website again. This community sucks.  Good thing I have other software that actually works lol

**Comment by austino3** [comment]
And you better not close the issue before you solve it

**Comment by aminya** [comment]
Install the missing kernel from here.
https://nteract.io/kernels

**Comment by austino3** [comment]
I’ve tried this. How do I run this code?? I tried typing it into a python window but got a syntax error. I can’t run it in atom because that’s the problem I’m trying to solve.

**Comment by aminya** [comment]
Follow the instructions written in the documentation:
https://nteract.gitbooks.io/hydrogen/content/

I don't understand what you mean by a python window.

**Comment by austino3** [comment]
I’m sorry but I do not understand what these instructions are telling me to do. —How/where do I run this code to install the python kernel?—
(By python window I meant the small coding window that you install from the windows store that you type code into.)

**Comment by austino3** [comment]
I have the two lines of code I need to run but WHERE DO I TYPE IT IN????

**Comment by aminya** [comment]
In a command window or terminal. 
https://www.wikihow.com/Open-Terminal-in-Windows

**Comment by austino3** [comment]
Thank you. That did it. I don’t think I like hydrogen lol. It displays your output in a weird way. Spider is so much easier to use.
