### ISSUE TITLE
Compatibility with autocomplete-python

### ISSUE THREAD

**Issue by orodbhen** [nteract/hydrogen#212]
Is this package inter-operable with `autocomplete-python`? As far as I can tell, it's working, but the autocomplete menu does flicker sometimes, and that could be related.

**Comment by lgeiger** [comment]
The flickering will be gone in the next release (https://github.com/nteract/hydrogen/pull/207).

Though some suggestions will appear twice. If you don't want duplicated suggestions and still want to use `autocomplete-python` you can deactivate hydrogen's autocompletion in the settings.

**Comment by orodbhen** [comment]
I don't mind duplicates. As long as the one doesn't break the other. Thanks.
