### ISSUE TITLE
Run code with indentation and whitespace

### ISSUE THREAD

**Issue by gnodix** [nteract/hydrogen#2122]
Hello ! 

I reached an issu with Hydrogen when I tried to run code with whitespace or indentation. 
Perhaps it's a common problem and because I'm a beginner in Python, I don't have the background to solve it by my own !

When I try to run code with cmd + enter, a message appear to show IndentationError : 
<img width="480" alt="Capture d’écran 2021-06-24 à 14 24 50" src="https://user-images.githubusercontent.com/86413647/123262248-f3f71900-d4f7-11eb-92be-521091b32e73.png">

This issu was reported on #1285 #862 #1363 and others. 

My file is saved on .py, Python is selected like main language

My versions : 

OS : Mac OS BigSur 11.2.3.
iPython : 7.24.1
Hydrogen : 2.16.3
Hydrogen-python : 0.0.8
Hydrogen-launcher : 1.2.2
Hydrogen-run : 0.1.10

**Comment by aminya** [comment]
That's a Python error. Read this article to become familiar with it. 
https://www.askpython.com/python/python-indentation#:~:text=Python%20Indentation%20Rules%201%20We%20can%E2%80%99t%20split%20indentation,indentation%20than%20the%20tab%20character.%20More%20items...%20
