### ISSUE TITLE
Is this going to be maintained?

### ISSUE THREAD

**Issue by contang0** [nteract/hydrogen#2171]
Last commit in this repo was half a year ago, Pulsar meanwhile has turned into a nice alternative for Atom. For me, Pulsar + Hydrogen offers the best Python development experience, and all other alternatives do not come even remotely close.

I would like to know if people at nteract plan to maintain Hydrogen going forward? If not, I think we have enough capable Hydrogen users to fork it and maintain it for Pulsar.

**Comment by aminya** [comment]
You can always make pull requests, and they will be reviewed and merged

**Comment by contang0** [comment]
Thank you, @aminya . It is reassuring that PRs are being merged.

**Comment by MarkWieczorek** [comment]
I don't think that this question was answered before the issue was marked as resolved. Will the people at https://nteract.io be maintaining Hydrogen going forward? It is great that they will continue to merge PRs from the community!

**Comment by contang0** [comment]
It would be useful to know, agreed.

**Comment by aminya** [comment]
As mentioned, the Atom packages including Hydrogen are in the maintenance mode. Hydrogen has been maintained by me voluntarily. I will review the pull requests if there are any.

You can checkout the Atom sunset notice here:
https://github.com/nteract/hydrogen#atom-sunset-notice
