### ISSUE TITLE
0.8.0 output messes up layout

### ISSUE THREAD

**Issue by sbromberger** [nteract/hydrogen#228]
See attached screenshot with Julia kernel. (There are no spaces before the statements; Hydrogen is repositioning the text.)

<img width="200" alt="screen shot 2016-03-27 at 3 14 25 pm" src="https://cloud.githubusercontent.com/assets/941359/14068132/a1b1840a-f42e-11e5-937f-eb1edc1d3bb7.png">

Here's python:

<img width="252" alt="screen shot 2016-03-27 at 3 18 29 pm" src="https://cloud.githubusercontent.com/assets/941359/14068155/3626429c-f42f-11e5-81b9-cd3301cd7848.png">

**Comment by lgeiger** [comment]
I think it's an issue related to the line height.

I'll take a closer look at this tomorrow. In the meantime it should help setting the line height to the default value (I think it's 1.5).

**Comment by sbromberger** [comment]
Ah, could be. I'm using Source Code Pro at 13px with a line height of 1.1.

**Comment by sbromberger** [comment]
Thank you both very much. I can confirm 0.8.1 does NOT have the display issue on my system.
