### ISSUE TITLE
[Feature Request] Side Panel for Results 

### ISSUE THREAD

**Issue by v3ss0n** [nteract/hydrogen#229]
Instead of clobbering the editor , how about side panel , like minimap for displaying the results?
at the right sidebar thre will be another gutter , which can be clicked for overview results of each lines.
should be awesome!

**Comment by n-riesco** [comment]
Hydrogen already provides watches (which are shown on a side panel).
See the command `Hydrogen: Add watch`.

At some point, we will add a framework to add plugins to Hydrogen,
so that it'll be easier to experiment with new UI.

**Comment by lgeiger** [comment]
Closing in favor of #760
