### ISSUE TITLE
Cannot install Hydrogen on Arch

### ISSUE THREAD

**Issue by dpavlic** [nteract/hydrogen#236]
Well, this is a doozy.  I wiped my atom folder the other day and went back to rebuild hydrogen.  I installed hydrogen before, so this cryptic error is all that much more odd:

```
> zmq@2.14.0 install /tmp/apm-install-dir-116229-14247-zds1mw/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116229-14247-zds1mw/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
zmq.target.mk:88: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: Leaving directory '/tmp/apm-install-dir-116229-14247-zds1mw/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq/build'

In file included from ../binding.cc:38:0:
../node_modules/nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
make: *** [Release/obj.target/zmq/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116229-14247-zds1mw/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/dpavlic/.atom/.apm/.apmrc" "--userconfig" "/home/dpavlic/.atom/.apmrc" "install" "/tmp/d-116229-14247-1abxrvp/package.tgz" "--target=0.37.3" "--arch=x64"
npm ERR! node v5.9.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116229-14247-zds1mw/npm-debug.log

```

Oddly, `npm install zmq` (which pulls 2.14.0) works just fine.

**Comment by lgeiger** [comment]
Are you using atom version 1.6.0?

**Comment by dpavlic** [comment]
Yes, it's 1.6.0.

**Comment by lgeiger** [comment]
You can try this: https://github.com/nteract/hydrogen/issues/59#issuecomment-194279876

**Comment by dpavlic** [comment]
There is no ~/.atom/packages/Hydrogen/ I assume since apm install fails. I'll see if I can pull Hydrogen repo and see if I can figure out what the heck is going on shortly.

**Comment by lgeiger** [comment]
What worked for me in the past is removing the `~/.atom/compile-cache` folder and doing `apm install hydrogen`

**Comment by dpavlic** [comment]
Atom is the first package I'm installing on once the .atom directory is wiped, so nothing in those. I've also tried to wipe ~/.atom in its entirety, but I'm afraid still the same error. What's so bizarre is that npm pulls the package without complaint.

**Comment by dpavlic** [comment]
Well, I am still at a complete loss as to why this is happening. This workaround does work:

```
git clone https://github.com/nteract/hydrogen.git
git checkout v0.8.1
npm install --save zmq
PYTHON=python2.7 apm install
apm link .
```

Works. Omitting the `npm install -save zmq` throws the same error as trying to do `apm install hydrogen`. I'm not really sure why getting zmq directly via npm works.

**Comment by lgeiger** [comment]
I'm glad to hear that it's working now!

@n-riesco Since you are working with linux, do you have an idea about why the normal installation is failing?

**Comment by n-riesco** [comment]
On 29/03/16 23:30, Lukas Geiger wrote:
> @n-riesco <https://github.com/n-riesco> Since you are working with linux, do you have an idea about why the normal installation is failing?

No, I don't.

I'm actually very surprised that Dejan's workaround fixed the problem. My understanding is that apm and npm don't even use the same version of Node.js. For example, in this machine:

```
$ node --version
v0.10.25
$ npm --version
1.4.21
$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```

I will investigate this issue (but most likely not tomorrow).

**Comment by lgeiger** [comment]
> I will investigate this issue (but most likely not tomorrow).

Awesome! There's no rush :smile:

**Comment by dpavlic** [comment]
So on this end:

```
$ node --version
**v5.9.1**
$ npm --version
3.8.3
$ apm --version
apm  1.7.1
npm  2.13.3
**node 5.9.1**
python 3.5.1
git 2.7.4
```

Well, while npm versions are certainly different, node is the same on my end. Maybe this could have something to do with how the arch repo is packaging Atom... I'm just taking a complete stab in the dark, though.

**Comment by slavaGanzin** [comment]
@dpavlic 

1. atom do not use node or npm installed on your system, it brings its own (outdated versions). You can see it - ```apm config list```
2. I had troubles with outdated atom releases from AUR. Pacman said it was 1.6, but ```atom --version``` shows 1.4.1. So check this.
3. I have node-gyp 3.3.1, and yours is 2.0.2. I don't even know how it works for you. node-gyp shouldn't work with modern glibc and other libs

**Comment by JCMais** [comment]
This is an issue with [jmp](https://github.com/n-riesco/jmp) which uses an outdated version of [zqm](https://github.com/JustinTulloss/zeromq.node) which in turn uses an outdated version of [NAN](https://github.com/nodejs/nan) not compatible with some new v8 API.

**Comment by n-riesco** [comment]
@JCMais Please, could open a new issue and an include information such as Atom and Hydrogen versions and any error messages?

**Comment by JCMais** [comment]
@n-riesco Sorry, but I didn't installed it, I said that based on the logs I saw on build errors of my own addon.

**Comment by lgeiger** [comment]
This is likely a issue with `apm` since it should download the newest version of `zmq`.
