### ISSUE TITLE
Scalling on High Resolution Display

### ISSUE THREAD

**Issue by JLCCI** [nteract/hydrogen#240]
First of all, thanks for the absolutely great package. Very useful.

I recently got a 4K screen and notices a small glitch. While the plots in Toggle Watch are nicely scaled, when I plot in the main editor body, the plot is to big to fit in the plotting window and I have to scroll horizontally and vertically. 

Any chance for an option to scale? It would be great if a full plot is shown in the box so no scrolling is necessary.

Also it would be useful if the plot is shown above the line from the 'wrap-guide' package. When using Atom on half of the screen the line always go through the plot.

Thanks for your work!

![scale](https://cloud.githubusercontent.com/assets/18163728/14138189/c5f582ba-f6a6-11e5-9222-0f56bba518bb.png)

**Comment by lgeiger** [comment]
Thanks for your feedback! I addressed the scaling issue in #242.

I'm afraid we can't do anything against the wrap-guide issue. We intentionally chose to move away from displaying the results as overlays because of #48.

You can make the wrap-guide a bit more subtle by modifying your custom stylesheet like this:
```
atom-text-editor::shadow .wrap-guide {
  background-color: yourcustomcolor;
}
```

**Comment by JLCCI** [comment]
Hi, thanks so much for a prompt reply, it's much appreciated!

No problem about the wrap-guide, it's not much of a bother. Also big thanks for adding the scaling option. Could you please let me know how to turn it on - should I wait for the package in Atom to be updated?

**Comment by lgeiger** [comment]
It will be included in the next update and will be the default behavior.
