### ISSUE TITLE
`No kernel for language python found` on Hydrogen run command

### ISSUE THREAD

**Issue by rkpatel33** [nteract/hydrogen#243]
I am new to Atom and Hydrogen so forigive me if the answer here is obvious, but I can't seem to get Hydrogen to run on a python file and not sure how exactly to adjust my Hydrogen options. Here is my situation, please advise!

I have a one-line python file open with `Python` indicated in the bottom right status bar.

![image](https://cloud.githubusercontent.com/assets/3799489/14152297/7c87aa52-f680-11e5-8598-ac0597c6e80f.png)

When I run `Hydrogen: Run`, I get the following 2 errors on startup:

```
No kernel for language python found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.
```

```
Can't parse neither 'ipython kernelspecs nor 'jupyter kernelspecs'

Use kernelspec option in Hydrogen options OR update
your ipython/jupyter to version that supports kernelspec option:
$ jupyter kernelspec list --json || ipython kernelspec list --json
```

Jupyter and python 2.7 are installed and Jupyter notebooks work great on my system.

I have run `$ jupyter kernelspec list --json || ipython kernelspec list --json` but does not help. Running `$ jupyter kernelspec list --json` alone yields this:

```
(global)[14:01:34] rishi:~ $ jupyter kernelspec list --json                                  
{
  "kernelspecs": {
    "bash": {
      "resource_dir": "/usr/local/share/jupyter/kernels/bash", 
      "spec": {
        "language": "bash", 
        "display_name": "Bash", 
        "env": {}, 
        "argv": [
          "/Users/rishi/Virtualenvs/global/bin/python", 
          "-m", 
          "bash_kernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }, 
    "python2": {
      "resource_dir": "/Users/rishi/Virtualenvs/global/lib/python2.7/site-packages/ipykernel/resources", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/Users/rishi/Virtualenvs/global/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}
```

**Comment by n-riesco** [comment]
Could you post your settings for Hydrogen?

**Comment by rkpatel33** [comment]
Sure, here they are:

![image](https://cloud.githubusercontent.com/assets/3799489/14152615/23018960-f682-11e5-9477-95bfe9d6a47d.png)

**Comment by n-riesco** [comment]
OK, those are the default values. It also shows Hydrogen was unable to run `jupyter kernelspec`.

Could you try to run Hydrogen again and then open the dev console (shift-ctrl-i) to see what errors have been reported?

**Comment by rgbkrk** [comment]
It looks like those were in a virtualenv, which Atom won't pick up unless Atom is launched as `atom .` within the virtualenv. The alternative is to [create a kernel specifically for a virtualenv](http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/).

**Comment by rkpatel33** [comment]
Thanks for that, makes sense. I have a global default env that get's activated automatically.

I fixed the problem by pasting the entire json from `jupyter kernelspec list --json ` into the package settings.

One thing I note in the settings view, you can't actually see the entire json field when there is something in there besides the default. Seems like a bug? Not sure who's it would be if it is one.

![image](https://cloud.githubusercontent.com/assets/3799489/14183451/6dd11f70-f73e-11e5-9a22-3dd9944eb6ba.png)

**Comment by n-riesco** [comment]
I'm running Atom 1.7.0-dev-7040035 and I don't this issue. What version are you using? Is there any one else seeing this problem?

**Comment by lgeiger** [comment]
I'm running Atom 1.6.0 and I don't have this issue.
But on my system this setting gets populated by hydrogen. Maybe that has something to do with it.

**Comment by rkpatel33** [comment]
Sorry for the delay, I am running 1.6.1, the latest release.

______________________________________
Rishi K. Patel
​, ​
Founder
​,
www.docnavapp.com
*​*
​
rishi@docnavlab.com
​,
917-647-0892​
LinkedIn <https://www.linkedin.com/in/rkpatel33>, @docnavlab
<https://twitter.com/docnavlab>

**Comment by mjamilrahman** [comment]
[ Problem solved ] " no kernel for python language found"

I am using Linux Operating System ubuntu 16:04
Atom 1.7.4

Open your beloved Terminal <3

$ sudo apt autoremove ipython
$ sudo apt install python-pip -y
$ pip install --upgrade pip

then, install ipython[notebook]

$ sudo pip install ipython[notebook]

Done

**Comment by n-riesco** [comment]
TODO
- [ ] Update TROUBLESHOOTING.md with https://github.com/nteract/hydrogen/issues/243#issuecomment-203686955

**Comment by alucinare** [comment]
I'm not sure if this is the right place to put this issue, but it seems appropriate because it is pretty much the same issue. I get the same message except the language is for ruby.

I copied and pasted the kernel specs default example into the kernel specs field which didn't solve the problem. I followed the instructions posted by jamil912 but when I got to the last -  sudo pip install ipython[notebook] - it was told that ipython[notebook] couldn't be found.

I'm not entirely sure what to do. I'm wondering if it has something to do with the language mappings, but I'm not sure how to change it or how to find the language name for the kernel.

Would someone be able to help me on this one?

**Comment by lgeiger** [comment]
The issue is quite old so things might have changed.

Let's start debugging from a clean state:

> I copied and pasted the kernel specs default example into the kernel specs field which didn't solve the problem.

This shouldn't be necessary, please remove this for now and run ("Hydrogen: Update Kernels") so we can be sure that this setting doesn't interfere 😄

1. Install jupyter with `pip install jupyter` or `conda` depending on your setup.
2. Could you post the exact error you get?
3. Could you post the output of `jupyter kernelspec list --json`?

**Comment by alucinare** [comment]
1. I installed jupyter. It seemed to install fine.

2. I ran Hydrogen and got this error:

`No kernel for language ruby found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.`

3. This is the output of `jupyter kernelspec list --json`

`{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python2", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "python", 
          "-m", 
          "ipykernel_launcher", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}`

I'm not sure where I run "Hydrogen: Update Kernels". Is this for the command line?

**Comment by BenRussert** [comment]
Are you trying to start a ruby kernel? If so you'll need to install this first as you only have a python2 kernel so far.

To run package commands in atom an easy way to remember is opening the "command palette" with ctrl-shift-p then searching for the command. Try this to run the update kernels command you mentioned.

**Comment by alucinare** [comment]
I don't know if I'm trying to start the Ruby kernel. I'm pressing `ctrl + enter` to run the inline calculations that are available with Hydrogen, but I'm getting the above error. Is the `ctrl + enter` command meant to run the kernel specific for the language that is being used to code? Do I get the error because it cannot load the ruby kernel?

I updated the kernel by running the "command palette" and it told me the python kernel update. I'm still having the same error as above.

**Comment by lgeiger** [comment]
This doesn't look likas a problem with Hydrogen itself.
Since `jupyter kernelspec list` cannot find the ruby kernel, it looks like you didn't install it properly.

Take a look at https://github.com/SciRuby/iruby#quick-start on how to install the ruby kernel.

**Comment by BenRussert** [comment]
@alucinare I'm guessing you have a ruby file open which is why Hydrogen is looking for a ruby kernel. If you post the code you are trying to run that would help.

**Comment by fznfire** [comment]
I had the same trouble. What worked for me was when I ran the atom as sudo atom.

**Comment by epifanio** [comment]
Hi, I guess I'm having a similar issue ... I'm trying to use a remote Jupyter notebook.
This are the steps I followed on a fresh OS X system:

* homebrew python3 
* Jupiter notebook installed in a virtual environment
* Atom 1.17.0-beta5

On the remote server I've installed with 'jupyter_kernel_gateway' using pip and then run it :
```
pip3.6 install jupyter_kernel_gateway
jupyter kernelgateway --ip="*"
```
I start atom-beta from the bash shell where I activated my virtualenv, In Atom I used this json configuration:

```
[{"name": "Remote Notebook", 
"options": { "baseUrl": "my.domain:8890" } 
}
]
```
Run from the editor toolbar: `Packages -> Hydrogen -> Connect to remote Kernel` : no errors

In Atom `kernel spec` I used this [gist](https://gist.github.com/c5825647c22456c5f483cb933de4121f)  (which is the output from the remote server)

Then as  `language mapping` I used: `{"python3": "python"}`

Now in the editor I've this simple code:

```
print('epi')
import sys
print(sys.executable)
```

From the atom toolbar I use:  `connect to remote kenrel` then  `run all`, this the output:

```
epi
/Users/epi/Envs/jupyter/bin/python
```

Which shows the local python executable, not the one on the server.

Have you any clue on what I'm doing wrong?

**Comment by codemeleon** [comment]
Hi,
I am unable to run Hydrogen and settings look different on my system (Please see the image). 
How can I fix it?

Thanks.
![image](https://user-images.githubusercontent.com/7693569/27730867-1f59d7ba-5d8b-11e7-842f-743f89cb2be5.png)

**Comment by BenRussert** [comment]
@codemeleon I'm guessing a reinstall of hydrogen will fix that. Let me know if that works!

**Comment by codemeleon** [comment]
@BenRussert Nope, it didn't. I also reset atom configurations by removing .atom folder from my home directory. Now hydrogen settings looks like attached image. I am using Atom 1.8 on ubuntu 16.04.

Thanks.

![image](https://user-images.githubusercontent.com/7693569/27751777-2fb0cf12-5dde-11e7-9f1e-bf430b2d623f.png)

**Comment by codemeleon** [comment]
Hi @BenRussert . I made it working by installing older version of Hydrogen using command "apm install Hydrogen@1.16.0".However, upgrading to latest version (1.18.0) breaks it.

Thanks.

**Comment by BenRussert** [comment]
When you said atom 1.8 did you mean atom 1.18?

**Comment by codemeleon** [comment]
I mean Hydrogen@1.18.0. 

Sorry for confusion.

**Comment by t9md** [comment]
Do you have custom config on config.cson?
If so I want to know if removing Hydrogen config from config.cson and restart Atom then reconfigire manually solve issue.

**Comment by codemeleon** [comment]
Hi @t9md . No I do not have custom config on config.cson. As  you can see in previous message, I deleted .atom folder from my home directory to reset whole Atom configuration.

**Comment by andrewbanchich** [comment]
I am having the same issue. I opened Atom 1.18 and installed Hydrogen via the settings GUI, but whatever type of code I try to run it on, like a JS file, it gives me "No kernel specs found" and "No kernel grammar for JavaScript found".

**Comment by lgeiger** [comment]
@andrewbanchich You'll need to have a kernel installed for the language you want to run (In your case e.g. IJavascript). Check out the [installation guide](https://nteract.gitbooks.io/hydrogen/docs/Installation.html#installation).

**Comment by sAs59** [comment]
Where should I run this command: `Hydrogen: Run`?

**Comment by rgbkrk** [comment]
Open the command palette (cmd-shift-p on Mac) then start typing hydrogen.

**Comment by madmansn0w** [comment]
For anyone still looking for a solution for this issue -- especially those who insert the kernelspec json details into Hydrogen and get "python can't be spawned. Is it in the path?" 

The solution for me was to write the installed python envs (Anaconda) to the kernel.json file for Jupyter. 
This link serves well for all purposes: https://ipython.readthedocs.io/en/latest/install/kernel_install.html
Specifically, this line of code was all I needed to push through the Anaconda prompt:
`python -m ipykernel install --user`

Do this for however many kernels you want to link back to Jupyter by activating each python env.

**Comment by wsjz** [comment]
Note that if you install a new kernel, you'll need to run Hydrogen: Update Kernels for Hydrogen to find it. For performance reasons, Hydrogen only looks for available kernels when it first starts.

**Comment by etmdchua** [comment]
Looking for solution. Error appeared when using Hydrogen --> Run
![python](https://user-images.githubusercontent.com/51946662/59662166-f32b9e00-91de-11e9-9de1-5ddba562ea17.jpg)

The output of jupyter kernelspec list --json as below: 

![image](https://user-images.githubusercontent.com/51946662/59662222-18201100-91df-11e9-9f10-43682b98afaf.png)

How to solve?

**Comment by aviatesk** [comment]
Maybe the path to your kernels is not recognised by Atom.
Make sure your environment variable includes paths to Jupyter kernels, not sure what the exactly path would be if you install Jupyter without Anaconda tho.

**Comment by tkind** [comment]
> Looking for solution. Error appeared when using Hydrogen --> Run
> ![python](https://user-images.githubusercontent.com/51946662/59662166-f32b9e00-91de-11e9-9de1-5ddba562ea17.jpg)
> 
> The output of jupyter kernelspec list --json as below:
> 
> ![image](https://user-images.githubusercontent.com/51946662/59662222-18201100-91df-11e9-9f10-43682b98afaf.png)
> 
> How to solve?

After running into the same error, the following steps worked for me:
Step 1: Install Python 3.6 
- open the conda prompt: conda create -n py36 python=3.6 anaconda
Step 2: Launch Atom 
- open the conda prompt: atom --new-instance
