### ISSUE TITLE
Ability to set breakpoints

### ISSUE THREAD

**Issue by uncreativename** [nteract/hydrogen#244]
Hi, I was just wondering if it's possible to set breakpoints inside loops/functions or conditional breakpoints.

**Comment by n-riesco** [comment]
On 31/03/16 01:16, uncreativename wrote:
> Hi, I was just wondering if it's possible to set breakpoints inside loops/functions or conditional breakpoints.

A debugger is language dependant (i.e. different languages will require different debuggers).
For functionality that is language/kernel dependant, we're planning to offer a plugin framework.

**Comment by uncreativename** [comment]
Oh gotcha, I wasn't even aware that hydrogen supported languages other than python. Sorry if this issue is a duplicate, I just noticed a previous issue with regards to support for stdin, that I assume is related. Thanks for the response!

**Comment by n-riesco** [comment]
Hydrogen can work with any language that has a Jupyter kernel. See here for a list:

    https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages

The things that Hydrogen can do with a kernel are defined by the Jupyter messaging protocol.

One of those things is the access to stdin. So, in principle, Hydrogen could provide stdin to the kernel.

The Jupyter messaging protocol doesn't provide any means to implement a breakpoint functionality.

**Comment by lgeiger** [comment]
Closed via #364
