### ISSUE TITLE
Weird characters in error message

### ISSUE THREAD

**Issue by huyiqun** [nteract/hydrogen#246]
For any error message I got in hydrogen, they all come with these long sequences of 0 34 36 m, e.g.

`[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-655-4128c4316f8c>[0m in [0;36m<module>[0;34m()[0m
[0;32m----> 1[0;31m [0mscores[0m[0;34m,[0m [0mpvalues[0m [0;34m=[0m [0mchi2[0m[0;34m([0m[0msampleA[0m[0;34m.[0m[0miloc[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;36m0[0m[0;34m:[0m[0;36m1000[0m[0;34m][0m[0;34m,[0m [0msampleA[0m[0;34m.[0m[0miloc[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;36m1000[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'chi2' is not definedNameError
name 'chi2' is not defined`

With the same kernel I connect else where, error messages are normal.
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-656-4128c4316f8c> in <module>()
----> 1 scores, pvalues = chi2(sampleA.iloc[:,0:1000], sampleA.iloc[:, 1000])

NameError: name 'chi2' is not defined`

**Comment by n-riesco** [comment]
This issue should be fixed in the latest release of Hydrogen. Note that the latest release requires at least Atom v1.6.0 or v1.7.0-beta.

**Comment by huyiqun** [comment]
Thanks! I updated Atom and Hydrogen and everything is good now.
