### ISSUE TITLE
[DISCUSSION] Hydrogen CSS namespace

### ISSUE THREAD

**Issue by rgbkrk** [nteract/hydrogen#252]
For the sake of readability in a user's config, we should start using a CSS (well, LESS) namespace for our outputs (and watch panel). Right now, as suggested in https://github.com/nteract/hydrogen/issues/160 to adjust the font-size you have to override `bubble-output-container`. Nested within other Atom stylesheets, it will begin to be unclear what `bubble` is when a user comes back to their stylesheet.

I'd love to see `hydrogen` in our class names and re-use existing styles where possible. We would still need to maintain the old classes for backwards compatibility, while moving ahead with new classes.

Thoughts?

**Comment by rgbkrk** [comment]
[Related Twitter conversation](https://twitter.com/treycausey/status/718131309474746368)

**Comment by n-riesco** [comment]
`hydrogen.less` could do with a clean up (not only font sizes, colours as well).

In the long term, I'd like to make possible the creation of plugins and themes.

**Comment by n-riesco** [comment]
Perhaps, we could add a setting to configure this font size.

**Comment by lgeiger** [comment]
I agree. A cleanup of `hydrogen.less` is much needed!

**Comment by BenRussert** [comment]
I have been experimenting w/ hydrogen.less in @lgeiger's fork #772, I was thinking of starting a README on namespace/styling hydrogen elements. This way we could have a reference for development and a guide for users who want to customize on their own styles,less.

**Comment by lgeiger** [comment]
@BenRussert That's a excellent idea!

I would also love to have support for different themes, though I haven't looked at how we can do this in Atom.
