### ISSUE TITLE
Kernelspec properly catched by Kernels not available

### ISSUE THREAD

**Issue by updiversity** [nteract/hydrogen#253]
Hi, 

in the hydrogen settings, I see that the tool has been able to fill on its own the "Kernel Spec" field, with this:

```
{
  "kernelspecs": {
    "venvpy2": {
      "resources_dir": "/usr/local/share/jupyter/kernels/venvpy2", 
      "spec": {
        "language": "python2", 
        "display_name": "Python Venv 2", 
        "env": {}, 
        "argv": [
          "/home/vagrant/.virtualenvs/venvpy2/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }, 
    "venvpy3": {
      "resources_dir": "/usr/local/share/jupyter/kernels/venvpy3", 
      "spec": {
        "language": "python3", 
        "display_name": "Python Venv 3", 
        "env": {}, 
        "argv": [
          "/home/vagrant/.virtualenvs/venvpy3/bin/python", 
          "-m", 
          "IPython.kernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }, 
    "python2": {
      "resources_dir": "/usr/local/lib/python2.7/dist-packages/ipykernel/resources", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/usr/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}

```

Also, if i trigger the command "Hydrogen: Update Kernels", it looks like Hydrogen finds successfully the kernels, as a little blue popup info window open on the upper right with the list of detected kernels.

However, when I open a *.py file, and that i want to switch kernel,  the list of kernels does not appear on the bottom left.

I am running Atom 1.6.2 on Ubuntu 14.04 and Hydrogen 0.8.3

What's wrong ?

**Comment by n-riesco** [comment]
This behaviour is not ideal at the moment. The functionality to switch kernels is enabled only after a kernel is already running.

Do you know that `GrammarToKernel` in the Hydrogen settings can be used to define the default kernel for a language?

**Comment by updiversity** [comment]
The workaround at the moment i have found is to launch atom from within the corresponding virtualenv.

In this case, at least I can use the corresponding kernel. 

I tried to put the following config in the GrammartoKernel box, but without success:
{"python2":"Python Venv 2"}

Thks for the quick reply

**Comment by n-riesco** [comment]
You can try this in grammarToKernel:

    {"python": "Python Venv 2"}

I use something similar to change the default between Python 2 and Python 3.

**Comment by n-riesco** [comment]
We should make these settings more user friendly, but we have to wait until we're done tidying up the code dealing with the kernel manager.

**Comment by updiversity** [comment]
Yep, trying in grammarToKernel:

    {"python": "Python Venv 2"}

confirmed it works !
