### ISSUE TITLE
Atom 1.7.0 failing with Hydrogen 0.8.4

### ISSUE THREAD

**Issue by sbromberger** [nteract/hydrogen#256]
Message is `zmq@2.14.0 – Module version mismatch. Expected 47, got 46.`

How does one go about upgrading the dependencies?

**Comment by sbromberger** [comment]
"Rebuild Packages" seems to have resolved it.

**Comment by rgbkrk** [comment]
I ran into that too and somehow rebuild packages worked flawlessly (I was surprised it fixed itself).
