### ISSUE TITLE
Strange message when restarting kernel

### ISSUE THREAD

**Issue by sbromberger** [nteract/hydrogen#258]
```
Uncaught Error: No grammar found for language scala211
/Users/me/.atom/packages/hydrogen/lib/kernel.coffee:483
Show Stack Trace
The error was thrown from the hydrogen package. hydrogen is out of date: undefined installed; 0.8.4 latest. Upgrading to the latest version may fix this issue.
Check for package updates
```

I'm running 0.8.4. The `scala211` kernel is there (I had been using it), but I have a language mapping in my settings: `{"scala" : "scala211"}`.

**Comment by lgeiger** [comment]
Try the language mapping the other way around: `{"scala211" : "scala"}`

**Comment by sbromberger** [comment]
@lgeiger the thing is, the language mapping works - that is, I am able to run scala211 kernel in hydrogen. This error only comes up when I go to restart the kernel.

**Comment by n-riesco** [comment]
There are three types of names used in Hydrogen:
- `@editor.getGrammar().name.toLowerCase()`
- `kernel.language`
- `kernel.display_name`

And two settings to link them:
- `grammarToKernel`
- `languageMappings`

I reckon I can fix this issue by getting rid of `kernel.language` and `languageMappings`.
