### ISSUE TITLE
make layout determined by actual size of the bubble and wrap lines

### ISSUE THREAD

**Issue by willwhitney** [nteract/hydrogen#26]
This is to better accommodate kernels like IRkernel which output rich text (e.g. HTML) for even small results.

Bubbles which only contain text (regardless of formatting) should have a multiline-result style bubble (pictured below) if they're larger than a single line, and should fit inline with no close button if they're small.

<img src="https://cloud.githubusercontent.com/assets/597829/7789115/82203eae-0223-11e5-8636-e93a2765af37.png" height=400px>

HTML results should also have the same close/new pane buttons as text ones if they only contain text.

**Comment by n-riesco** [comment]
@lgeiger Is this issue something you'd like to have a go?

**Comment by lgeiger** [comment]
> HTML results should also have the same close/new pane buttons as text ones if they only contain text.

I can give it a shot.

> Bubbles which only contain text (regardless of formatting) should have a multiline-result style bubble (pictured below) if they're larger than a single line, and should fit inline with no close button if they're small.

This is the current behavior, isn't it?

**Comment by n-riesco** [comment]
Yes, it's the current behaviour.

I think the only thing that it's left to close this issue is to add the "copy to clipboard" and the "open in new pane" buttons in HTML result bubbles.

**Comment by lgeiger** [comment]
I'll soon make a PR!
