### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by postoroniy** [nteract/hydrogen#265]
Having this issue https://github.com/atom/atom/issues/11282#issuecomment-216105739
no idea where's root cause

**Comment by n-riesco** [comment]
I will have a look a this issue next week.

If I understood correctly the issue report in https://github.com/atom/atom/issues/11282 , this issue can be reproduced by running twice the same selection of lines. Is my understanding correct?

**Comment by postoroniy** [comment]
1) run first time
2) check that decorator on right side is appeared.
3) on the same line type space and delete space
4) check that decorator is gone
5) run this line again
6) observe issue

**Comment by n-riesco** [comment]
I can't reproduce this issue with Hydrogen v0.9.0 and Atom 1.7.0-dev-7040035 . What versions are you using?

**Comment by postoroniy** [comment]
I saw this at first time with Atom Version: 1.8.0-dev-1548cef
and according to mine experiments branch 1.7 is totally ok rather than 1.8

**Comment by n-riesco** [comment]
I've reproduced the issue on Atom 1.9.0-dev-4d494e1

**Comment by n-riesco** [comment]
This bug is pretty annoying. Shall we release a patch revision straight away?

**Comment by lgeiger** [comment]
👍  for a patch release.
