### ISSUE TITLE
grammarToKernel cut

### ISSUE THREAD

**Issue by slavaGanzin** [nteract/hydrogen#271]
I write grammarToKernel mapper that automatically saved on kernel change.

And now it doesn't work and I can't find it in repo:
https://github.com/nteract/hydrogen/search?utf8=%E2%9C%93&q=grammarToKernel

While @n-riesco recommend to use it:
https://github.com/nteract/hydrogen/issues/253

And it's present in Readme:
```
Additionally, if you have two or more kernels for a particular language (grammar), you can select which kernel to use with the "Switch to <kernel>" option in the Kernel Commands menu. This change is automatically saved into the Hydrogen configuration's ```grammarToKernel``` map. For example, if Hydrogen is using the kernel for Python 2 by default, you could switch to Python 3. Then next time you open a `.py` file, Hydrogen will remember your selection and use Python 3.
```

So if someone just cut this functionality, please document this fact.

p.s. I liked when I don't need to write mappings from babel kernel to jsx grammar, so why that was cutted?

**Comment by n-riesco** [comment]
README.md needs updating. This changed in #260 . See [this comment](https://github.com/nteract/hydrogen/pull/260#issuecomment-212273724) for more details.

**Comment by slavaGanzin** [comment]
@n-riesco 
You cut this line:
https://github.com/nteract/hydrogen/pull/260/commits/a7106d109a988401ae78ffec54d4ece984511fe5#diff-2e1bb36917ff76ab7308da52bc968501L119

Saving kernels on switching them in atom does break something? Or this should be added again?

**Comment by n-riesco** [comment]
I believe settings should be updated by the user.
Having said that, I don't really feel strongly about this point.
cc/ @lgeiger @rgbkrk what are your thoughts?

**Comment by rgbkrk** [comment]
Having a way to map from grammar to a kernel certainly needs to exist. How the settings are stored and dealt with should rely on Atom APIs for settings as much as possible.

**Comment by lgeiger** [comment]
> Having a way to map from grammar to a kernel certainly needs to exist. How the settings are stored and dealt with should rely on Atom APIs for settings as much as possible.

I agree. However I never used this setting so I don't feel strongly about this.

**Comment by slavaGanzin** [comment]
We are not talking about storing options. We are talking about automatic update of "gramar to kernel" mapping on every change of kernel, for example: if I switch to python3 kernel on .py file, next time I start hydrogen on .py file it will launch python3 kernel and not default one.

This functionality was implemented, but cut out after Nicolas's refactor.

**Comment by slavaGanzin** [comment]
Another thing I want to discuss:

Autopopulated kernelspecs shouldn't be shown to user and should be merged with user's one on startup - this will ease adding your own kernels.

Additionally we should strongly recommend to create separate files for kernels, if ipython or jupyter is installed on machine. Hydrogen shouldn't be used for kernel management.

**Comment by rgbkrk** [comment]
I tend to assume that kernelspec files are managed by Jupyter within, for example, `~/Library/Jupyter/kernels` on OS X.

**Comment by n-riesco** [comment]
Let me focus the question in this issue. The question is which option do you prefer:

1. you'd like that the command `switch to kernel` will not only switch to the requested kernel, but also update the setting `grammarToKernel` (so that the kernel becomes the default choice for that grammar).

2. or you'd like that the command `switch to kernel` only changes the running kernel, and `grammarToKernel` remains unchanged (i.e. set to whatever the user had chosen before running the command `switch to kernel`).

**Comment by slavaGanzin** [comment]
1. you'd like that the command switch to kernel will not only switch to the requested kernel, but also update the setting grammarToKernel (so that the kernel becomes the default choice for that grammar).

2. or you'd like that the command switch to kernel only changes the running kernel, and grammarToKernel remains unchanged (i.e. set to whatever the user had chosen before running the command switch to kernel).

@rgbkrk @n-riesco @lgeiger and maybe @willwhitney 

Please vote too. I vote for 1 because i don't like editing json by hands.

**Comment by willwhitney** [comment]
I have no strong feelings. It seems probably easier to have switch change the setting persistently (#1) but if there's a good argument the other way, that's fine too.
