### ISSUE TITLE
Hydrogen install fails on OS 10.11.5

### ISSUE THREAD

**Issue by RobBW** [nteract/hydrogen#279]
When try to install Hydrogen from the Atom Install packages menu it fails as follows:

Installing “Hydrogen@0.9.1” failed.Hide output…

> zmq@2.15.2 install /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11652-53864-yjbq9p/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild

make: *** No rule to make target `Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/addon.gypi', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11652-53864-yjbq9p/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/robw/.atom/.apm/.apmrc" "--userconfig" "/Users/robw/.atom/.apmrc" "install" "/private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/d-11652-53864-1p4v9op/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11652-53864-yjbq9p/npm-debug.log

My $PATH value from a Terminal is: /Users/roxx/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Developer/NVIDIA/CUDA-7.5/bin 

I don't know if there are any commonalities with nbviewer code but it works fine in my Atom installation

**Comment by lgeiger** [comment]
Have you tried installing hydrogen via terminal with `apm install hydrogen`?

**Comment by RobBW** [comment]
Here is the result of running  apm install hydrogen


untitled

[robw]$ apm install hydrogen
Installing hydrogen to /Users/robw/.atom/packages ✗

> zmq@2.15.2 install /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11653-60949-1029y09/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild


make: *** No rule to make target `Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/addon.gypi', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11653-60949-1029y09/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/robw/.atom/.apm/.apmrc" "--userconfig" "/Users/robw/.atom/.apmrc" "install" "/private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/d-11653-60949-mbzavo/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/apm-install-dir-11653-60949-1029y09/npm-debug.log


[robw]$







Regards
Rob

**Comment by lgeiger** [comment]
Just to make shure, have you installed `pkg-config` and `zeromq` and used `python2` for installing hydrogen? (https://github.com/nteract/hydrogen/blob/master/README.md#homebrew-on-os-x)

Which version of atom are you using?

**Comment by n-riesco** [comment]
The log message reports an error on `node-gyp rebuild`. This suggests Atom in your machine is unable to build native modules.

@rgbkrk , are the OS installation instructions [here](https://github.com/nteract/hydrogen/blob/master/README.md#homebrew-on-os-x) complete? Is it enough to install `homebrew`, `zeromq` and `pkg-config`?

**Comment by lgeiger** [comment]
@n-riesco Thanks for taking a look!

On travis the installation works with `homebrew`, `zeromq` and `pkg-config`.

**Comment by n-riesco** [comment]
@lgeiger I've been quiet for a while, but I'm still working on Hydrogen and IJavascript. At the moment, my priorities for these projects are: get out the next release of IJavascript, develop a javascript-only kernel launcher and solve (hopefully) the situation with native modules.

**Comment by rgbkrk** [comment]
For my OS X machine, it's been enough to install homebrew, `zmq`, and `pkg-config`. This is assuming the node environment is set to use Python2 for `node-gyp`.

**Comment by RobBW** [comment]
Attached are the answers to your questions taken from a Terminal session:

Last login: Sat Jun  4 17:06:27 on ttys000

Current PATH is: /Users/robw/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Developer/NVIDIA/CUDA-7.5/bin:/Users/robw/torch/install/bin:/Users/robw/.local/bin:usr/local/Cellar/llvm38/3.8.0/bin

[robw]$ brew install pkg-config
Warning: pkg-config-0.29.1 already installed

[robw]$ brew install zeromq
Warning: zeromq-4.1.4 already installed

[robw]$ jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required

[robw]$ jupyter --version
4.1.0

[robw]$ jupyter —paths

config:
    /Users/robw/.jupyter
    /Users/robw/anaconda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/robw/Library/Jupyter
    /Users/robw/anaconda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/robw/Library/Jupyter/runtime

[robw]$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

robw]$ python --version
Python 2.7.11 :: Anaconda custom (x86_64)




Regards
Rob

**Comment by RobBW** [comment]
Following up on your query about node environment I updated from node 6.1 to node 6.2. No improvement.

Then found this link : https://github.com/npm/npm/issues/823 and followed its instructions to “  add $HOME/.homebrew/lib/node/ to my NODE_PATH.” The file .homebrew did not exist, and adding it made no difference anyway..

However finding that NODE_PATH is empty makes me wonder. Should it be set? and if so what to?

My whole Python working environment is 2.7 so I assume that is what node-gyp is using too. How do I check? 

I did find that node-gyp.js is tucked away in usr/local/lib/node-modules/npm/node-modules/node-gyp/lib so I added usr/local/lib to $PATH and usr/local/lib/node-modules/npm/ to $NODE_PATH as a test.
That did not work either.

I hope this negative information is helpful






Regards
Rob

**Comment by lgeiger** [comment]
On my machine `$NODE_PATH` is empty.

Try removing `~/.atom/packages/Hydrogen/` if anything is in there. Maybe this will help.

**Comment by RobBW** [comment]
lgeiger's advice to remove ~/.atom/packages/Hydrogen/ did not help because there were no packages to find.

However I found and deleted 4 identical copies of the unpacked Hydrogen  package in  /private/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/npm-39677-c351c005/unpack-d14c24747d76
There was no apm-install-dir or npm-debug file.

Further exploration of the build problem led me here: 
https://github.com/JustinTulloss/zeromq.node/issues/490  
where it says   "2.15.1 introduced Node 6 compatibility”
and
https://github.com/JustinTulloss/zeromq.node/wiki/Installation where it says:

"Then for every node.js project you have, you need to change to that directory and run
npm install zmq
(For installation on linux without root access, see Installation on Linux / bsd without root access )
Note that you can't do a global install. In node.js, once you require something, it needs to be in that directory (AFAIK), so don't try the '-g' global flag"

It seems that these links on the zmq developer's github site probably explain my problem.
But I still do not know enough about what  to do to compile Hydrogen.

**Comment by RobBW** [comment]
Following advice received on issue 318 this issue was resolved.
I replied there as follows:
n-riesco's suggestion worked.
"On MacOS 10.11.5 all I had to do was remove the space from the file path and do:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig to provide the link to libzmq.
Hydrogen installed without any further problems.
Thank you all"
