### ISSUE TITLE
Python 2.X syntax error

### ISSUE THREAD

**Issue by shichao116** [nteract/hydrogen#280]
I tried run a simple print statement in atom: `print 'haha'` it pops `SyntaxError: invalid syntax`. 

However, print('haha') works. I thought it was because atom default to run code with python 3, but there are other types of SyntaxError which works fine if run the script from shell and doesn't relate to python version. Does anyone encounter this problem? Thanks.

**Comment by n-riesco** [comment]
You should be able to determine what version of python Hydrogen is using by running `help()`.

Could you post all the other errors you've come across? (and a screenshot if possible).

**Comment by n-riesco** [comment]
@shichao116 I'm closing this issue. Please, feel free to reopen it if you need more help.
