### ISSUE TITLE
matplotlib image displayed in pop up window not in watch result area as demo shown

### ISSUE THREAD

**Issue by atmlvs** [nteract/hydrogen#281]
Atom: 1.7.4 on Ubuntu 15.04
Hydrogen: 0.9.1

matplotlib image displayed in pop up window not in watch result area as demo shown.
how to do that like demo show?
![screenshot from 2016-06-03 12 11 21](https://cloud.githubusercontent.com/assets/138501/15768609/db7734c4-2984-11e6-92e9-47829a9ea454.png)

**Comment by n-riesco** [comment]
This how matplotlib works.
You need to add the following line to your code:

    %matplotlib inline

**Comment by atmlvs** [comment]
cool! I went back the demo. I missed the top 2 lines :(
thanks for pointing out.
