### ISSUE TITLE
hydrogen autocomplete not working properly

### ISSUE THREAD

**Issue by nmiculinic** [nteract/hydrogen#282]
I cannot get hydrogen autocomplete working properly.

I'm using python3.5 and when using ordinary jupyter notebook everything works as expected.
I've tested in atom print(sys.version) that it correctly connects to the jupyter kernel and it works as expected. I'm not sure what more could I check to determine what is the issue.

**Comment by lgeiger** [comment]
Hydrogen's completions are displayed via the `autocomplete-plus` package.

Are  completions from the default providers of `autocomplete-plus` working for you?

**Comment by nmiculinic** [comment]
autocomplete-plus is displaying alright.

I did some debugging and culprit is autocomplete-python on packages which are big (such as numpy/tensorflow, in tensorflow example it never finishes) and it hangs quite a lot until it finishes leaving me without hydrogen autocompletions. My questions are now as follows:

Can I somehow force autocomplete-plus to display hydrogen completions first and not wait for the autocomplete-python?
Can I get inspector tooltip as autocomplete text when calling a function/class, that is when inspector would say something in jupyter notebook?

**Comment by rgbkrk** [comment]
I'm assuming you turned off autocomplete plus for Python in the meantime?

What was your solution/temp-fix @nmiculinic?

**Comment by nmiculinic** [comment]
Solution/temp fix is disable autocomplete-python

In the meantime I've submitted bug report to Jedi and autocomplete-plus. Jedi throws error on importing from tensorflow and autocomplete-plus for some reason doesn't display other providers once autocomplete-python Jedi fails (not even snippets, default nor hydrogen).

Related issues are:
davidhalter/jedi#730
atom/autocomplete-plus#727
