### ISSUE TITLE
Your Hydrogen config is broken: kernelspec

### ISSUE THREAD

**Issue by Kiminaka** [nteract/hydrogen#283]
Hi, I'm trying to use the extension but I have trouble setting up..
I got this error:
<img width="462" alt="screen shot 2016-06-05 at 10 27 30 pm" src="https://cloud.githubusercontent.com/assets/2072406/15812685/bf57f53c-2b6c-11e6-90a7-9d65f212484b.png">

My setting:
<img width="705" alt="screen shot 2016-06-05 at 10 34 39 pm" src="https://cloud.githubusercontent.com/assets/2072406/15812780/be74c0ae-2b6d-11e6-8829-f494f2de50c1.png">

Could someone tell me how to fix it?

**Comment by n-riesco** [comment]
To fix this problem, please delete `{jupyter kernelspec list --json}` in your Kernel Specs setting.

---

I'm leaving this issue open as a reminder to improve the error message.

**Comment by Kiminaka** [comment]
Thanks n-risesco! 
I deleted `jupyter kernelspec list --json` but I still get this error.. 
<img width="468" alt="screen shot 2016-06-06 at 8 35 51 am" src="https://cloud.githubusercontent.com/assets/2072406/15827858/ca0fd79c-2bc1-11e6-950d-c561e6676d16.png">

**Comment by n-riesco** [comment]
What OS are you using? If you are using the IPython distributed with Ubuntu 16.04, you'd need to edit the Kernel Spec setting as:

```json
{
  "kernelspecs": {
    "python2": {
      "spec": {
        "language": "python",
        "display_name": "Python 2",
        "env": {},
        "argv": [
          "/usr/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      }
    }
  }
}
```

**Comment by Kiminaka** [comment]
I'm using OSX El Captain

**Comment by lgeiger** [comment]
Have you saved the file you want to execute with a correct file extension (`.py` for python etc.)?

Otherwise Atom can't recognize the correct grammar and Hydrogen can't start the kernel.

**Comment by Kiminaka** [comment]
Thanks lgeiger! I see. I was testing it with an unsaved file. But if I try it with a .py file, I still get the same error.. 
`No kernel for language python found`

**Comment by lgeiger** [comment]
Can you run `jupyter kernelspec list --json` in the terminal and post the output.

**Comment by Kiminaka** [comment]
Here is the output!
```
{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python2", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/Users/kn/anaconda/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}

```

**Comment by lgeiger** [comment]
This looks OK.
Please paste this output into the Kernel Spec settings field.

However Hydrogen should do this for you on its own.
Which atom version are you using?

**Comment by Kiminaka** [comment]
Great! it worked when I pasted the output :) I'm using the latest version (1.7.4)

**Comment by lgeiger** [comment]
👍

**Comment by n-riesco** [comment]
TODO
- [ ] Update error message when Hydrogen config is broken
- [ ] Update README with installation instructions for Ubuntu 16.04
- [ ] Update README with installation instructions for Anaconda

**Comment by slavaGanzin** [comment]
1. Why jupyter don't know about anaconda? Please clarify
2. Why Kiminaka got ```null grammar```?
3. Can that copy/paste be done by hydrogen? Or conda doesn't expose itself to PATH? Or what?

**Comment by madmansn0w** [comment]
For anyone still looking for a solution for this issue -- especially those who insert the kernelspec json details into Hydrogen and get "python can't be spawned. Is it in the path?" 

The solution for me was to write the installed python envs (Anaconda) to the kernel.json file for Jupyter. 
This link serves well for all purposes: https://ipython.readthedocs.io/en/latest/install/kernel_install.html
Specifically, this line of code was all I needed to push through the Anaconda prompt:
`python -m ipykernel install --user`

Do this for however many kernels you want to link back to Jupyter by activating each python env.
