### ISSUE TITLE
Test instructions

### ISSUE THREAD

**Issue by slavaGanzin** [nteract/hydrogen#285]
@lgeiger, please, add to Readme test instructions in new Development paragraph.
I'm interested in way how can I launch tests on my local machine, not waiting for travis build.

**Comment by lgeiger** [comment]
Good idea! I'lll add a paragraph this evening.

You can launch the tests with `apm test` or in atom with View->Developer->Run Package Specs.

**Comment by slavaGanzin** [comment]
@lgeiger thanks
