### ISSUE TITLE
Installing “Hydrogen@0.9.1” failed.

### ISSUE THREAD

**Issue by erdemalpkaya** [nteract/hydrogen#288]
<img width="1303" alt="screen shot 2016-06-08 at 4 45 55 pm" src="https://cloud.githubusercontent.com/assets/18541694/15883048/ed314aa2-2d98-11e6-87d1-36fe95b3abd1.png">

Hey, Guys, I tried to install Hydrogen but I got this warning. Does anyone know about it?
Thank you

**Comment by n-riesco** [comment]
You need to install Hydrogen requirements. See [this section](https://github.com/nteract/hydrogen#homebrew-on-os-x) in the README.

**Comment by n-riesco** [comment]
@erdemalpkaya I'm closing this issue. Please, feel free to reopen it if you need more help.
