### ISSUE TITLE
Error while building tess-two

### ISSUE THREAD

**Issue by sagarnayak** [nteract/hydrogen#291]
C:\tess-two\eyes-two>ndk-build NDK_PROJECT_PATH=C:\tess-two\eyes-two\src\main NDK_APPLICATION_MK=C:\tess-two\eyes-two\src\main\jni\Application.mk AAPP_BUILD_SCRIPT=C:\tess-two\eyes-two\src\main\jni\Android.mk
[armeabi] Install        : libhydrogen.so => libs/armeabi/libhydrogen.so
[armeabi] Install        : libimageutils.so => libs/armeabi/libimageutils.so
[armeabi] Install        : libopticalflow.so => libs/armeabi/libopticalflow.so
[armeabi-v7a] Install        : libhydrogen.so => libs/armeabi-v7a/libhydrogen.so
[armeabi-v7a] Install        : libimageutils.so => libs/armeabi-v7a/libimageutils.so
[armeabi-v7a] Install        : libopticalflow.so => libs/armeabi-v7a/libopticalflow.so
[x86] Install        : libhydrogen.so => libs/x86/libhydrogen.so
[x86] Install        : libimageutils.so => libs/x86/libimageutils.so
[x86] Install        : libopticalflow.so => libs/x86/libopticalflow.so
[mips] Install        : libhydrogen.so => libs/mips/libhydrogen.so
[mips] Install        : libimageutils.so => libs/mips/libimageutils.so
[mips] Install        : libopticalflow.so => libs/mips/libopticalflow.so
[arm64-v8a] Install        : libhydrogen.so => libs/arm64-v8a/libhydrogen.so
[arm64-v8a] Install        : libimageutils.so => libs/arm64-v8a/libimageutils.so
[arm64-v8a] Install        : libopticalflow.so => libs/arm64-v8a/libopticalflow.so
make.exe: *** No rule to make target `C:\tess-two\eyes-two\src\main/jni/../../../../tess-two/libs/x86_64/liblept.so', needed by `C:\tess-two\eyes-two\src\main/obj/local/x86_64/libhydrogen.so'.  Stop.

**Comment by n-riesco** [comment]
Wrong project repository?

http://www.hydrogen-music.org/hcms/node/1851
