### ISSUE TITLE
Installation fail [ 'node-gyp rebuild' ]

### ISSUE THREAD

**Issue by AnthonyJacob** [nteract/hydrogen#292]
Output

>  zmq@2.15.3 install C:\Users\Anthony\AppData\Local\Temp\apm-install-dir-116512-4052-1bnepjc\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq
>  node-gyp rebuild
> 
> 
> C:\Users\Anthony\AppData\Local\Temp\apm-install-dir-116512-4052-1bnepjc\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> 
> gypnpm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\Anthony\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Anthony\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Anthony\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Anthony\\.atom\\.apmrc" "install" "C:\\Users\\Anthony\\AppData\\Local\\Temp\\d-116512-4052-16mclzk\\package.tgz" "--target=0.36.8" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the zmq package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls zmq
> npm ERR! There is likely additional logging output above.

**Comment by n-riesco** [comment]
This looks like an error with the installation of native modules.
In Windows this requires the installation python and visual studio.
See this link for up to date instructions:

https://github.com/nodejs/node-gyp#installation

**Comment by AnthonyJacob** [comment]
Hmm, I have Anaconda installed (Python 3.5), does it mean that hydrogen won't work for anaconda?

**Comment by AnthonyJacob** [comment]
I have installed both

-  Visual C++ Build Tools
-  Python 2.7

but I am still getting the same error.

**Comment by n-riesco** [comment]
To confirm atom is using Python 23.7, could you post the output of running `apm --version`?

**Comment by AnthonyJacob** [comment]
> apm  1.9.2
> npm  2.13.3
> node 0.10.40
> python 3.5.1
> git
> visual studio

Seems like not... How can I force it to use the right one?

**Comment by n-riesco** [comment]
To answer your question above: yes, it's possible to use Hydrogen with anaconda, but you need to set `kernelSpec` in Hydrogen's settings.

You need to run the command `jupyter kernelspec list --json` and copy the output to `kernelSpec`.

**Comment by n-riesco** [comment]
On 12/06/16 17:11, AnthonyJacob wrote:
>     apm 1.9.2
>     npm 2.13.3
>     node 0.10.40
>     python 3.5.1
>     git
>     visual studio
> 
> Seems like not... How can I force it to use the right one?


I haven't tested it, but something like this should work:

```
apm config set python /path/to/executable/python2.7
```

**Comment by n-riesco** [comment]
BTW, it seems Atom is able to see your installation of Anaconda, so I don't think you need to set `kernelSpec`. Hydrogen will do it, automatically.

**Comment by AnthonyJacob** [comment]
Done. But another error occurs.

> > zmq@2.15.3 install C:\Users\Anthony\AppData\Local\Temp\apm-install-dir-116512-2804-130uofa\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq
> > node-gyp rebuild
> 
> 
> C:\Users\Anthony\AppData\Local\Temp\apm-install-dir-116512-2804-130uofa\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Anthony\AppData\Local\Temp\apm-install-dir-116512-2804-130uofa\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq\build\binding.sln]
> 
> gypnpm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\Anthony\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Anthony\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Anthony\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Anthony\\.atom\\.apmrc" "install" "C:\\Users\\Anthony\\AppData\\Local\\Temp\\d-116512-2804-p9qj96\\package.tgz" "--target=0.36.8" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the zmq package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls zmq
> npm ERR! There is likely additional logging output above.

**Comment by n-riesco** [comment]
Node-gyp is complaining that it cannot run `VCBuild.exe`.
What version of visual studio are you using?
Sometimes `node-gyp` can be very picky about the version.

**Comment by AnthonyJacob** [comment]
I don't have any, I have `Visual C++ Build Tools` instead - since https://github.com/nodejs/node-gyp#installation claims that it is enough.
Do I still need to install visual studio?
Btw I am running on w8 and I don't see .NET Framework 2.0 listed in program manager, should I also install it?

**Comment by n-riesco** [comment]
On 12/06/16 17:53, AnthonyJacob wrote:
> I don't have any, I have |Visual C++ Build Tools| instead - since https://github.com/nodejs/node-gyp#installation claims that it is enough.

yes, I saw it.

> Do I still need to install visual studio?

I tried once with visual studio and it worked, but I imagine the Visual C++ Build Tools should work too.

> Btw I am running on w8 and I don't see .NET Framework 2.0 listed in program manager, should I also install it?

That's what the error message says.
It sounds like a reasonable thing to do.

**Comment by AnthonyJacob** [comment]
I have gave up and installed that heavy 5GB Visual studio thing.

And it works now! Thank you **very much**  for your time, NR.
:- )

**Comment by n-riesco** [comment]
I'm sorry about the VS install. I'm working towards providing a pre-compiled native module for ZMQ (when this happens, the VS install will be unnecessary).

**Comment by Meekdai** [comment]
Have you solved the ZMQ problem?

**Comment by lgeiger** [comment]
@Meekdai Yes since `v1.2.0` no more compilers needed.

**Comment by Meekdai** [comment]
Fail outpput:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:libzmq"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.2.1 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.2.1 build:libzmq script 'node scripts/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Meekdai\.atom\packages\hydrogen\node_modules\zeromq\npm-debug.log
Hydrogen@1.14.1 C:\Users\Meekdai\.atom\packages\hydrogen

**Comment by lgeiger** [comment]
@Meekdai Are you behind a proxy?

Downloading behind a proxy isn't supported yet since we need to fetch the prebuilt binaries.
