### ISSUE TITLE
Can I display animations?

### ISSUE THREAD

**Issue by AnthonyJacob** [nteract/hydrogen#293]
This code should update image every frame, but does not.
```
using Reactive, Interact, Compose, IJulia

function drawball(t)
  y = 1-abs(sin(t)) # The y coordinate.
  compose(context(), circle(0.5, y, 0.04)) # draw a circle
end

ticks = fps(60)
timestamps = map(_ -> time(), ticks)
map(drawball, timestamps)
```
Instead it just shows one non moving image, and you have to run the code again to see progress.
(It works in notebook but not in atom)

**Comment by n-riesco** [comment]
This is not possible at the moment. Atom's CSP policy changed in v1.6.0 and injected scripts aren't allowed.

We have issue #27 opened to track this feature.
