### ISSUE TITLE
General question on how to use the Code Introspection

### ISSUE THREAD

**Issue by Kiminaka** [nteract/hydrogen#296]
Hi, I'm loving Hydrogen! It's replacing my work on Ipython Notebook. 

But I am having trouble to use Code Introspection. It looks like a great feature coming from NB. But how exactly can I use it? 

Following the instruction, 

> You can use the "Hydrogen: Inspect" command from the Command Palette to get metadata from the kernel about the object under the cursor.

, I clicked on `"Hydrogen: Inspect"` but the below message pop up and the metadata wasn't shown.

<img width="467" alt="screen shot 2016-06-15 at 3 24 49 pm" src="https://cloud.githubusercontent.com/assets/2072406/16099572/ccaf5e70-330d-11e6-8537-4b00a5d1961f.png">

I was trying to get the metadata of `numpy.linspace`. 

Thanks!

**Comment by lgeiger** [comment]
Thanks for your feedback!

The completion result depends on the cursor position. Place the cursor somewhere inside the word `linspace` or highlight it and it should work.

Also make sure to run the `import numpy` before requesting the completion.

**Comment by Kiminaka** [comment]
Ah, this was a silly question.. Yes positioning the cursor inside the word worked! But highlighting it didn't work(?)

**Comment by Kiminaka** [comment]
Also this wouldn't be possible on Atom but if I can type `tab+shift` just like NB and metadata pops up, it'd be super useful :)

**Comment by lgeiger** [comment]
Ah sorry you have to highlight `numpy.linspace` to make it work. Or import `linspace` with `from numpy import linspace` or `from numpy import *`.

**Comment by lgeiger** [comment]
`tab+shift` is currently used by Atom itself for indentation.

But you can define a custom keyboard shortcuts for this function for yourself by adding
```
'atom-text-editor':
  'cmd-ctrl-i': 'hydrogen:inspect',
```
to your Atom keymaps file.
