### ISSUE TITLE
New install, problem with the output of hydrogen:run

### ISSUE THREAD

**Issue by AlexandreKempf** [nteract/hydrogen#298]
Dear hydrogen people,

First of all thank you for this incredible package ! It's a little revolution and it's helping a lot coder's lifes ! 

I reinstall atom and hydrogen from scratch in order to have the new version of both. Now when I'm executing my code with hydrogen the result is always a check. 
On the previous version, if only a variable was selected, the return value was the variable. Here it's a check ! 
Even if there is only a variable on a line or when I execute print(variable) I obtain a check.
The only way to get a different result is to plot something with matplotlib.

Unfortunately, I have no log or error message to help, just checks (:p) ! Is there a way to go back with the previous printing technique ? 

Thank you in advance ! 

Alex

PS : you know your package is badass when people are complaining about getting checks whenever they run a code ;)

**Comment by n-riesco** [comment]
I haven't tried to reproduce the issue in a new install.

I've sometimes seen a similar issue when using `libzmq` instead of `libzmq3`.

Could you post your OS, atom and ZMQ versions?

If you uninstall and install back Hydrogen, do you get any error messages?

**Comment by AlexandreKempf** [comment]
Sorry for the lack of details of the original post. 
I'm running a Ubuntu14 with the last version of atom (1.8.0 I guess).
I don't know how to know my ZMQ version but I know the libzmq3 is installed !

Finally I tried to uninstall and reinstall hydrogen and I get the same problem :)

I get an weird error message when I uninstall hydrogen saying :
Uninstalling hydrogen ✗
Failed to delete hydrogen: Does not exist

However I'm sure it is install :)

**Comment by AlexandreKempf** [comment]
I found the problem thanks to you !! 

**The package libzmq3-dev was missing**. After I install it I reinstall hydrogen and everything is working perfectly :) !!

Thank you very much for your help !

Alex
