### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by AnthonyJacob** [nteract/hydrogen#299]
When updating to hydrogen 0.10.0 I get this error:

> **Atom Version**: 1.8.0
> **System**: Microsoft Windows 8.1 Pro
> **Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1
> 
> 
> ### Stack Trace
> 
> Uncaught TypeError: Cannot read property 'substr' of null
> 
> ```
> At C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709
> 
> TypeError: Cannot read property 'substr' of null
>     at C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
>     at C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
>     at C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
>     at exit (C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
>     at triggerExitCallback (C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
>     at ChildProcess.<anonymous> (C:\Users\Anthony\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> ```
> 
> ### Commands
> 
> ```
> ```
> 
> ### Config
> 
> ```json
> {
>   "core": {
>     "autoHideMenuBar": true,
>     "disabledPackages": [
>       "gcc-make-run",
>       "autocomplete-snippets",
>       "autocomplete-atom-api"
>     ],
>     "projectHome": "D:\\Owncloud\\",
>     "themes": [
>       "one-light-ui",
>       "my-theme"
>     ]
>   }
> }
> ```
> 
> ### Installed Packages
> 
> ```coffee
> # User
> highlight-selected, v0.11.2
> ink, v0.4.4
> julia-client, v0.4.7
> jupyter-notebook, v0.0.9
> language-julia, v0.6.0
> latex-completions, v0.3.1
> my-theme, v0.0.0
> open_in_cmd, v0.6.1
> refactor, v0.6.0
> tool-bar, v0.4.0
> uber-juno, v0.1.1
> 
> # Dev
> No dev packages
> ```

**Comment by AnthonyJacob** [comment]
Solved by reinstalling he package...

**Comment by lgeiger** [comment]
Great! 🎉
