### ISSUE TITLE
Run-and-move-down doesn't display result on last line of file

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#306]
Activating run-and-move-down while on the last line in the file (no trailing newline) causes the result bubble to not displayed. In addition to not showing the output, this creates the false impression that nothing was executed.

I suspect the cause is that the move-down operation has to create a new line where one previously did not exist, which triggers the output bubble to be hidden.

**Comment by n-riesco** [comment]
I can't reproduce this issue. Could you post the file you're using to reproduce this issue?

**Comment by nikitakit** [comment]
Steps to reproduce (in parentheses are action names, and the keyboard shortcuts on my system):
* Open a new file (Application: New File; Cmd-N)
* Switch to Python syntax (Grammar Selector: Show; Cmd-Shift-L; also available via toolbar on bottom)
* Type "1"
* Do run-and-move-down (Hydrogen: Run and Move Down)

Expected behavior: output "1" is shown
Actual behavior: no output is shown

It helps to have line numbers enabled in the sidebar to see that the line you're typing on is actually the last (i.e. there is no line number greater than it).

On my system this issue actually can't be reproduced by opening an existing file and not modifying it, because Atom enforces the presence of terminating newlines on every save/load.

**Comment by n-riesco** [comment]
@nikitakit I couldn't reproduce this issue. Could you take a screenshot of what you see in the dev console (shift-ctrl-i)?

**Comment by nikitakit** [comment]
I'm surprised you can't reproduce. The dev console output is not useful, so I went and debugged it myself.

Video of the issue: http://imgur.com/a/Ux2zW

And a fix (not very good abstraction, but I can't come up with a better alternative offhand)
```
diff --git a/lib/main.coffee b/lib/main.coffee
index 74984ca..b30ca0d 100644
--- a/lib/main.coffee
+++ b/lib/main.coffee
@@ -264,14 +264,20 @@ module.exports = Hydrogen =
     runAndMoveDown: () ->
         codeBlock = @findCodeBlock()
         unless codeBlock?
             return

         [code, row] = codeBlock
         if code? and row?
+            if row >= @editor.getLastBufferRow()
+                @editor.moveToBottom()
+                @editor.insertNewline()
+                @editor.moveLineUp()
+                @editor.moveLineDown()
+
             @createResultBubble code, row
             @moveDown row

     runCell: () ->
         [startRow, endRow] = CellManager.getCurrentCell()
         if endRow > startRow
             for i in [startRow .. endRow - 1] when @blank(endRow)
```
The issue is the bubble is created, then `moveDown` calls `@editor.insertNewline()`, which immediately invalidates the bubble.

**Comment by n-riesco** [comment]
Apparently I can't follow instructions to the letter :disappointed: !
Anyway, I can now reproduce it and to trigger this issue is important that the file is untitled.

**Comment by lgeiger** [comment]
I think we could fix this, if we change the way the marker for the result bubble is set (https://github.com/nteract/hydrogen/blob/master/lib/main.coffee#L163). So it isn't invalidated if a new line is inserted.

**Comment by n-riesco** [comment]
@lgeiger I'm still trying to understand why it doesn't happen with named files.

**Comment by lgeiger** [comment]
I can reproduce this issue now with named files as well. The important thing is that no newline is inserted by atom at the bottom.

**Comment by n-riesco** [comment]
On 06/07/16 10:57, Lukas Geiger wrote:
> I think we could fix this, if we change the way the marker for the result bubble is set (https://github.com/nteract/hydrogen/blob/master/lib/main.coffee#L163). So it isn't invalidated if a new line is inserted.

Do you mean that we wouldn't ever invalidate markers?

**Comment by lgeiger** [comment]
I haven't thought about this in detail but I think marking the beginning of the line instead of the end would prevent this issue.

**Comment by n-riesco** [comment]
@lgeiger It works! Shall I submit a PR?

**Comment by lgeiger** [comment]
@n-riesco Great go ahead!

**Comment by n-riesco** [comment]
@lgeiger I spoke too fast. After further testing, having the marker located at the beginning of the line only invalidates the marker if the beginning of the line is changed.

**Comment by lgeiger** [comment]
@n-riesco Yes thats true. We could also mark the whole line and use an different [invalidate option](https://atom.io/docs/api/v1.8.0/TextBuffer#instance-markRange)

**Comment by n-riesco** [comment]
@lgeiger I've tried:
```coffee
        marker = @editor.markBufferRange [[row, 0], [row, lineLength]],
            invalidate: 'inside'
```
but it fails to invalidate when changing the end of a line.

I've also tried:

```coffee
        marker = @editor.markBufferRange [[row, 0], [row, lineLength]],
            invalidate: 'touch'
```
but it displays the same problem as `markBufferPosition`.

I think we could use `markBufferPosition` to improve how the result bubbles are invalidated, but I'd leave this for another PR.

I'm getting more convinced that, to solve this issue, we need to treat files not ending with an EOL as a special case.

**Comment by lgeiger** [comment]
@n-riesco Thanks a lot for investigating!

> I'm getting more convinced that, to solve this issue, we need to treat files not ending with an EOL as a special case.

I agree. We could simply don't call `@moveDown` if the cursor is at the last line.
