### ISSUE TITLE
Cell mode for easy code selection

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [nteract/hydrogen#307]
I just learned about this fantastic package and I'm wondering if there are any plans to implement "cells" for easy code selection and evaluation.

Let me explain. By "cells" I refer to **code blocks** that can be delimited by lines holding a certain combination of characters (e.g. `##` in Python). When the cursor is within a given cell, the user can use a keyboard shortcut to **quickly** select the code in the current cell and send it easily to the REPL.

Some additional context:
* [Cell mode in MATLAB](http://blogs.mathworks.com/videos/2011/07/26/starting-in-matlab-cell-mode-scripts/)
* [Cell mode in Python editors](http://stackoverflow.com/questions/6719972/cell-mode-in-python-editors)

Needless to say, jupyter notebooks are organized as collections of cells, although notebooks don't rely on lines with special characters to define them.

This is what cells may look like in raw source code:
```
%% This is the beginning of the 1st cell

a = 5;    
print(a)

%% This is the end of the 1st cell and beginning of the 2nd cell

% This is just a comment
b = 6;
c = a + b
print(c)

%% This is the end of the 2nd cell
```

**Comment by n-riesco** [comment]
We're currently working on similar feature that is language agnostic. See #227 and #309

**Comment by amelio-vazquez-reina** [comment]
Thank you @n-riesco! It looks like https://github.com/nteract/hydrogen/pull/227 was already merged, does it mean that the feature I am asking about in this issue is ready?

**Comment by n-riesco** [comment]
We haven't published this feature yet. If you want to try it out, [here](https://github.com/nteract/hydrogen#development) are some instructions to install Hydrogen's development version.

**Comment by lgeiger** [comment]
I close this issue in favor of #317.
