### ISSUE TITLE
help with question mark?

### ISSUE THREAD

**Issue by oztalha** [nteract/hydrogen#310]
My Atom fails to show the help menu as in IPython. When I succeed a function name with a question mark I would expect it to show what `help(my_function)` shows but instead nothing happens when I run `my_function?`

Wrapping the function name with `help()` is cumbersome, a question mark makes getting help way more convenient. Could you please implement this feature? (Indeed I'm very surprised that this issue has not been brought forward)

Thanks.

**Comment by n-riesco** [comment]
Hydrogen provides this functionality via the command `hydrogen:inspect`. See #296 for more information.

**Comment by oztalha** [comment]
doh! Thanks
