### ISSUE TITLE
How to run Hydrogen with Python2?

### ISSUE THREAD

**Issue by alexdrymonitis** [nteract/hydrogen#311]
Hi all,
New both to Atom and Hydrogen. I managed to install and active Hydrogen with help I got from Atom's forum, in this [thread](https://discuss.atom.io/t/how-to-use-the-hydrogen-package/30190). First I used pyvenv-3.4 (which was available in the Debian Jessie repositories I have in my apt-get), as advised [here](https://discuss.atom.io/t/how-to-use-the-hydrogen-package/30190/6), and then tried to use virtualenv instead, as advised [here](https://discuss.atom.io/t/how-to-use-the-hydrogen-package/30190/8), but it didn't really work.
Can anyone help me out as to how I can run Python2 with Hydrogen. I found [this](https://github.com/nteract/hydrogen/pull/138) in the closed issues, but I can't see in the .gif how to get the pop-down menu where I can switch to Python2.

Note: all the links above except from the last are from the same thread in the Atom forum.

Thanks

**Comment by n-riesco** [comment]
It's hard to tell without seeing the error messages Hydrogen displays.

I will guess the issue is that Debian Jessie provides an old version of IPython (v2.3.0) and this Hydrogen is unable to detect the python kernelspec automatically. Assuming you want to use the Python kernel, see [this comment](https://github.com/nteract/hydrogen/issues/176#issuecomment-196391464) for an example to set kernelspecs manually.

Also make sure Hydrogen's requirements are installed:
```sh
sudo apt-get install ipython libzmq3-dev
```

**Comment by alexdrymonitis** [comment]
When I first open a python file I get the following error message (if this is of any significance):
```
Provided path doesn't exist.
pylama
Please fix pylama path
```
It works fine though. If I run the following code:
```
import sys
sys.version
```
I get this:
```
'3.4.2 (default, Oct  8 2014, 10:45:20) \n[GCC 4.9.1]'
```

> Also make sure Hydrogen's requirements are installed:
> sudo apt-get install ipython libzmq3-dev
These are installed in my system.

> Assuming you want to use the Python kernel, see this comment for an example to set kernelspecs manually.

In ~/.atom/packages/Hydrogen/spec there's hydrogen-spec.coffee, in which I can see this:
```
describe "Kernel manager", ->
    firstKernelSpecString = """{
        "kernelspecs": {
            "ijavascript": {
                "spec": {
                    "display_name": "IJavascript",
                    "env": {},
                    "argv": [
                        "node",
                        "/home/user/node_modules/ijavascript/lib/kernel.js",
                        "--protocol=5.0",
                        "{connection_file}"
                    ],
                        "language": "javascript"
                },
                "resource_dir": "/home/user/node_modules/ijavascript/images"
            }
        }
    }"""
    secondKernelSpecString = """{
        "kernelspecs": {
            "python2": {
                "resource_dir": "/usr/local/lib/python2.7/site-packages/ipykernel/resources",
                "spec": {
                    "language": "python",
                    "display_name": "Python 2",
                    "env": {},
                    "argv": [
                        "/usr/local/opt/python/bin/python2.7",
                        "-m",
                        "ipykernel",
                        "-f",
                        "{connection_file}"
                    ]
                }
            }
        }
    }"""

    firstKernelSpec = JSON.parse firstKernelSpecString
    secondKernelSpec = JSON.parse secondKernelSpecString

    kernelSpecs = JSON.parse firstKernelSpecString
    kernelSpecs.kernelspecs.python2 = secondKernelSpec.kernelspecs.python2
```
There's Python 2 there but Hydrogen won't use it.  Is there something I should do manually?
In [this pull request](https://github.com/nteract/hydrogen/pull/138) it seems pretty easy, but I don't know how to do this...

**Comment by alexdrymonitis** [comment]
Ok, found how to open the command palette (sorry, I'm a noob in Atom), and selected
```
Hydrogen: Select Kernel
```
and I only get Python 3. Getting closer? How can I add Python 2 there?

**Comment by n-riesco** [comment]
To edit Hydrogen's settings, go to `Edit > Preferences > Packages > Hydrogen > Setting`.

Just to make sure that IPython 2 is accessible in your machine, could you post the output of running `ipython --version`?

**Comment by alexdrymonitis** [comment]
I edited the "Kernel Mappings" field, from:
`{"python":"Python 3"}`
to
`{"python":"Python 2"}`
but it didn't work.

The "Kernel Specs" field has this:
`{"kernelspecs":{"python3":{"resource_dir":"/home/alex/dev/hydrogen/src/venv/lib/python3.4/site-packages/ipykernel/resources","spec":{"env":{},"argv":["/home/alex/dev/hydrogen/src/venv/bin/python3.4","-m","ipykernel","-f","{connection_file}"],"display_name":"Python 3","language":"python"}}}}`
There's also a
`/home/alex/dev/hydrogen/src/venv/lib/python2.7/site-packages/`
directory, but there's no
`ipykernel/resources`
to match the rest of the JSON string in the "Kernel Specs", so I'm not sure what to write there.

Running
`ipython --version`
gives this
`2.3.0`
Is this OK, or should the version be the same with Python (2.7)?

**Comment by n-riesco** [comment]
Hydrogen can't detect IPython v2.3.0. You need to set KernelSpec manually.

The following setting for "Kernel Specs" should work:

```js
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "\/home\/alex\/dev\/hydrogen\/src\/venv\/lib\/python3.4\/site-packages\/ipykernel\/resources",
      "spec": {
        "env": {},
        "argv": [
          "\/home\/alex\/dev\/hydrogen\/src\/venv\/bin\/python3.4",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "display_name": "Python 3",
        "language": "python"
      }
    }
  },
  "python2": {
    "spec": {
      "display_name": "Python 2",
      "env": {},
      "argv": [
        "ipython",
        "kernel",
        "-f",
        "{connection_file}"
      ],
      "language": "python"
    }
  }
}
```

**Comment by alexdrymonitis** [comment]
Still not working. Can't see "Python 2" under "Select Kernel"...
Thanks though.

**Comment by n-riesco** [comment]
There shouldn't be any need for selecting the kernel, since you've already set `Kernel Mappings` to `{"python":"Python 2"}`. What happens when you try to run a line?

**Comment by alexdrymonitis** [comment]
I had switched that back to `{"python":"Python 3"}`. I changed it again to `{"python":"Python 2"}` and now I get an error:
`No kernel for language python found`
`Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.`

**Comment by n-riesco** [comment]
That was my bad. I made a mistake copy'n'pasting the "Kernel Spec" settings. This works for me:

```js
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "\/home\/alex\/dev\/hydrogen\/src\/venv\/lib\/python3.4\/site-packages\/ipykernel\/resources",
      "spec": {
        "env": {
          
        },
        "argv": [
          "\/home\/alex\/dev\/hydrogen\/src\/venv\/bin\/python3.4",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "display_name": "Python 3",
        "language": "python"
      }
    },
    "python2": {
      "spec": {
        "display_name": "Python 2",
        "env": {
          
        },
        "argv": [
          "ipython",
          "kernel",
          "-f",
          "{connection_file}"
        ],
        "language": "python"
      }
    }
  }
}
```

**Comment by alexdrymonitis** [comment]
That worked!
Don't really know what's going on, but I'm happy with it. Thanks a bunch for your help and time!

**Comment by n-riesco** [comment]
The problem is that IPython v2.3.0 doesn't provide the command `ipython kernelspec` (that Hydrogen uses to locate the kernels installed in a computer).

The setting `Kernel Spec` contains the output of running `ipython kernelspec`, so that if a computer cannot run `ipython kernelspec`, the user still has the possibility to set it manually.

It is really unfortunate that Debian and Ubuntu provide such an outdated version of IPython.
