### ISSUE TITLE
IRkernel doesn't work with CRLF line endings

### ISSUE THREAD

**Issue by econwang** [nteract/hydrogen#312]
thanks for providing this, very useful, I do use it with python and stata, but with R, as suggested by the readme, it should work with IRKernel, if I only select one line, it works well, but when select multi lines or the whole file, it shows:
```
Error in parse(text = x, srcfile = src): <text>:2:33: unexpected input
1: # test IRkernel
2: x <- seq(0, 2*pi, length.out=50)
                                   ^
Traceback:
```

the r code is:
```
x <- seq(0, 2*pi, length.out=50)
plot(x, sin(x))
```

**Comment by n-riesco** [comment]
I'm sorry for the delay in replying.

Could you open the dev console (by pressing shift-ctrl-i) and post an screenshot? This will help us debug the issue.

**Comment by igutierrezm** [comment]
I have the same problem. Here is the dev console. Help me please! :)

![captura de pantalla 2016-09-16 14 54 41](https://cloud.githubusercontent.com/assets/19560665/18595986/80959afa-7c1d-11e6-840c-be9f016c51c2.png)

**Comment by lgeiger** [comment]
Are you using the latest version of the IRkernel?

**Comment by igutierrezm** [comment]
yes

**Comment by lgeiger** [comment]
Hmm this is strange, on the Hydrogen side everything looks normal. I bet it has something to do with the line endings. Could you try running
```
x <- 1;
y <- x + 1;
```

I don't have IRkernel on my machine so I can only guess at the moment.

**Comment by igutierrezm** [comment]
same result :( 

![captura de pantalla 2016-09-22 16 42 40](https://cloud.githubusercontent.com/assets/19560665/18763393/938e8e26-80e3-11e6-9d65-e68b5431b415.png)

**Comment by lgeiger** [comment]
I'll try to get a r kernel running on my windows VM so I can debug it.

**Comment by igutierrezm** [comment]
thank you very much :)

**Comment by lgeiger** [comment]
OK I can reproduce this.

**Comment by lgeiger** [comment]
IRkernel doesn't like windows style line endings.

There is a easy fix for that: Click on `CRLF` in the status bar and select `LF`. This will switch to unix style line endings.

@rgbkrk @n-riesco Should we ensure unix style line endings before sending code to the kernel or should this be handled by the kernel it self?

**Comment by igutierrezm** [comment]
It works! Thanks!

**Comment by rgbkrk** [comment]
Interesting. I don't think that's specified anywhere in the messaging spec. I'll raise an issue on jupyter-client.

**Comment by lgeiger** [comment]
@igutierrezm In the next release this will be fixed so you can use `CRLF` line endings again.
