### ISSUE TITLE
Remote kernel in vagrant box

### ISSUE THREAD

**Issue by quintona** [nteract/hydrogen#315]
Rather than use your suggested docker approach, I opted to run my python kernel in a seperate vagrant box, for the following reasons: 

- The state of docker on OSX
- Even if docker was in a good state, my target environments are linux, not OSX
- It simulates actual environments correct, where my target workflow is to run the kernel on a remote box that has some GPUs in it.

To start with I decided to test just with a vagrant box, which is then easily transportable to the target later (it translates well) 

I have captured the vagrant box, and some utility scripts in a repo: https://github.com/quintona/charles. 

There are a few improvements that I would like to make:

- Secure the kernel connection (ssh tunnel) 
- Wrap up the remote kernel process (right now its just some scripts), into a PR against hydrogen so that the process is transparent whether it is a local or remote kernel

Please can you let me know if I should treat this work as a PR to hydrogen or if you would prefer me to run with separate tooling

**Comment by lgeiger** [comment]
I have never used remote kernels so I'm no expert on this. For me this sounds like an interesting addition to Hydrogen if it doesn't introduce any language dependent code.

@rgbkrk @n-riesco @slavaGanzin what do you think?

**Comment by rgbkrk** [comment]
If I had more time, I'd go after making a remote API that's simple to use and automatic to secure.

From both Electron apps and Atom (which is basically Electron under the hood), we can generate private and public key pairs to connect over TLS, launch a Docker container (or vagrant box), and connect with strict PKI that was setup before, relying on websockets to connect to the kernel (a la the the notebook server). When the work is finished, the keys can be deleted and the box can be torn down.

**Comment by n-riesco** [comment]
@quintona I think your PR should only update `README.md` (similarly to [this commit](https://github.com/nteract/hydrogen/pull/295/commits/65a242254b6636f193e437014937858a3226de11)).

Also, it'd be nice if the proposed the vagrant solution would offer a functionality similar to the docker solution (i.e. reuse the connection file created in the docker/vagrant container).

**Comment by lgeiger** [comment]
@quintona We are now supporting remote kernels via [jupyter kernel gatways](https://github.com/nteract/hydrogen#remote-kernels-via-kernel-gateways). Please try it out if it suites your needs.

I'm going to close this issue. If remote kernels via kernel gateways aren't working for you please reopen this issue so we can continue the discussion.
