### ISSUE TITLE
[DISCUSS] Save breakpoints

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#317]
It would be awesome to save the breakpoints even if atom is restarted.

I see two ways of doing this:
1. Save the position of the breakpoints to a separate file in the `./hydrogen/` folder. A downside would be, that it will break if the file is changed outside of atom.
2. Use text to identify breakpoints like `# %%` and parse the file before execution or add markers to those positions. We could make this language independent by using something like [this](https://github.com/atom/atom/blob/master/src/language-mode.coffee#L351) to get the right comment symbol.

I tend towards the second option. What about you?

**Comment by n-riesco** [comment]
Option 2 would go against the policy of having code specific to a language.

I would try to make option 1 as smart as possible. For example:
- record row number and row content
- if row number and content don't match the current file, then search the row content:
  - if only one row is found with the same content, the update then breakpoint record,
  - else remove the breakpoint and report this to the user.

**Comment by n-riesco** [comment]
I changed the title to get the other's attention.

**Comment by lgeiger** [comment]
I don't think option 2 would introduce language specific code, but it could lead to potential problems with certain languages.

A smart option 1 is a great idea, since parsing only need to happen on startup. The only problem arises if the file is renamed externally, but this is something we can tell users to watch out for.

**Comment by lgeiger** [comment]
We could even use something like [jsdiff](https://github.com/kpdecker/jsdiff) to make the parsing more robust.

**Comment by n-riesco** [comment]
On 28/06/16 08:34, Lukas Geiger wrote:
> I don't think option 2 would introduce language specific code, but it could lead to potential problems with certain languages.

If I understand correctly this would mean, the breakpoint save functionality would only work for languages that use '#' to mark comment lines.

> A smart option 1 is a great idea, since parsing only need to happen on startup. The only problem arises if the file is renamed externally, but this is something we can tell users to watch out for.

In the case of an external file rename, I'd advise the user to rename as well the file that stores the breakpoint records under `./hydrogen`.

**Comment by lgeiger** [comment]
> If I understand correctly this would mean, the breakpoint save functionality would only work for languages that use '#' to mark comment lines.

No. For example Atom uses [this](https://github.com/atom/atom/blob/master/src/language-mode.coffee#L351) for getting the correct comment symbol for the language. This is something we could do as well and search for `{comment symbol} %%`.

**Comment by n-riesco** [comment]
On 28/06/16 09:04, Lukas Geiger wrote:
>     If I understand correctly this would mean, the breakpoint save functionality would only work for languages that use '#' to mark comment lines.
> 
> No. For example Atom uses this <https://github.com/atom/atom/blob/master/src/language-mode.coffee#L351> for getting the correct comment symbol for the language. This is something we could do as well and search for |{comment symbol} %%|.

This sounds really useful and makes option 1 a possibility (which requires less effort than option 2).

I'd like to hear what the others think.

**Comment by Foucl** [comment]
I would find option 2 very attractive. I really enjoy defining sections with markup in the matlab IDE as described by amelio-vazquez-reina in #307. from a (my) user's perspective, having these definitions visible in the code itself would definitely be preferable.

**Comment by nikitakit** [comment]
As a user, I also find option 2 (special comment syntax) to be more attractive.

If I'm working on a small group project, I find it a lot more tenable to have the cell-split annotions be in comments that are commited to version control, than to have them break every time I pull code from people who used a different editor.

**Comment by n-riesco** [comment]
@lgeiger Looks like everyone supports option 2.

Since potentially we could make use of comments for many other purposes, I think the format of the comment should reflect somehow that it marks a Hydrogen breakpoint.

**Comment by lgeiger** [comment]
[Spyder](https://github.com/spyder-ide/spyder/blob/ef38c3837b4a08ee26435efff4d180e762f0cc00/spyderlib/utils/sourcecode.py#L35) uses `#%%`, `# %%`, `# <codecell>` or `# In[`. I think we should support them as well. The last option is quite handy, because this is what `jupyter notebook` exports.

**Comment by n-riesco** [comment]
@lgeiger nice finding!

**Comment by lgeiger** [comment]
I'll make a PR next week once I submitted my thesis and have some spare time :)

**Comment by n-riesco** [comment]
On 05/07/16 09:32, Lukas Geiger wrote:
> I'll make a PR next week once I submitted my thesis and have some spare time :)

Congrats on the thesis submission!

**Comment by lgeiger** [comment]
Thanks! It's only a bachelor thesis but it takes some time too ;)
