### ISSUE TITLE
'apm rebuild' command errors

### ISSUE THREAD

**Issue by RobBW** [nteract/hydrogen#318]
I have been trying to solve the problem I raised in Issue 279.
When I ran 'apm rebuild' I received very similar error messages concerning failure of the ' node-gyp rebuild' command.

I attach a record of my Terminal session and the npm-debug.log
[apm rebuild session.txt](https://github.com/nteract/hydrogen/files/336728/apm.rebuild.session.txt)

[npm-debug.log.txt](https://github.com/nteract/hydrogen/files/336734/npm-debug.log.txt)

**Comment by n-riesco** [comment]
The rebuild log complains that `pkg-config` cannot find `libzmq`. Could you post the output of `pkg-config libzmq --libs`?

**Comment by RobBW** [comment]
Output of pkg-config libzmq --libs:

[robw]$ pkg-config libzmq --libs
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found

[robw]$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
[robw]$ echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig
[robw]$ pkg-config libzmq --libs
-L/usr/local/Cellar/zeromq/4.1.4/lib -lzmq
[robw]$

**Comment by RobBW** [comment]
Forgot to say running apm rebuild with the PKG_CONFIG_PATH=/usr/local/lib/pkgconfig produces the same error message as posted in apm rebuild session.txt posted above

**Comment by n-riesco** [comment]
Does is work if you run instead `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig apm rebuild`?

**Comment by RobBW** [comment]
No, it still does not work.

Debug file attached
Regards
Rob

**Comment by n-riesco** [comment]
It seems Github dropped the email attachment.

**Comment by RobBW** [comment]
Forgot github doesn’t like the “log” extension.
This time

Rob

> On 30/06/2016, at 18:59, Nicolas Riesco <notifications@github.com> wrote:
> 
> It seems Github dropped the email attachment.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/nteract/hydrogen/issues/318#issuecomment-229576188>, or mute the thread <https://github.com/notifications/unsubscribe/AGLYJnaTWTR0C-u_3lXH1JQc95WyvZCJks5qQ2lngaJpZM4I_8JB>.
> 


0 info it worked if it ends with ok
1 verbose cli [ '/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/robw/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/robw/.atom/.apmrc',
1 verbose cli   'rebuild',
1 verbose cli   '--target=0.36.8',
1 verbose cli   '--arch=x64' ]
2 info using npm@2.13.3
3 info using node@v0.10.40
4 info readInstalled object
5 verbose rebuild path, id [ '/Users/robw/node_modules/bindings', 'bindings@1.2.1' ]
6 verbose rebuild path, id [ '/Users/robw/node_modules/nan', 'nan@2.3.5' ]
7 verbose rebuild path, id [ '/Users/robw/node_modules/zmq', 'zmq@2.15.3' ]
8 silly rebuild set [ '/Users/robw/node_modules/bindings',
8 silly rebuild set   '/Users/robw/node_modules/nan',
8 silly rebuild set   '/Users/robw/node_modules/zmq' ]
9 info build /Users/robw/node_modules/bindings
10 info preinstall bindings@1.2.1
11 info linkStuff bindings@1.2.1
12 silly linkStuff bindings@1.2.1 has /Users/robw/node_modules as its parent node_modules
13 verbose linkBins bindings@1.2.1
14 verbose linkMans bindings@1.2.1
15 verbose rebuildBundles bindings@1.2.1
16 info install bindings@1.2.1
17 info postinstall bindings@1.2.1
18 info build /Users/robw/node_modules/nan
19 info preinstall nan@2.3.5
20 info linkStuff nan@2.3.5
21 silly linkStuff nan@2.3.5 has /Users/robw/node_modules as its parent node_modules
22 verbose linkBins nan@2.3.5
23 verbose linkMans nan@2.3.5
24 verbose rebuildBundles nan@2.3.5
25 info install nan@2.3.5
26 info postinstall nan@2.3.5
27 info build /Users/robw/node_modules/zmq
28 info preinstall zmq@2.15.3
29 info linkStuff zmq@2.15.3
30 silly linkStuff zmq@2.15.3 has /Users/robw/node_modules as its parent node_modules
31 verbose linkBins zmq@2.15.3
32 verbose linkMans zmq@2.15.3
33 verbose rebuildBundles zmq@2.15.3
34 info install zmq@2.15.3
35 verbose unsafe-perm in lifecycle true
36 info zmq@2.15.3 Failed to exec install script
37 verbose stack Error: zmq@2.15.3 install: `node-gyp rebuild`
37 verbose stack Exit status 1
37 verbose stack     at EventEmitter.<anonymous> (/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/lib/utils/lifecycle.js:214:16)
37 verbose stack     at EventEmitter.emit (events.js:98:17)
37 verbose stack     at ChildProcess.<anonymous> (/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/lib/utils/spawn.js:24:14)
37 verbose stack     at ChildProcess.emit (events.js:98:17)
37 verbose stack     at maybeClose (child_process.js:766:16)
37 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
38 verbose pkgid zmq@2.15.3
39 verbose cwd /Users/robw
40 error Darwin 15.5.0
41 error argv "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/ Codingware/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/robw/.atom/.apm/.apmrc" "--userconfig" "/Users/robw/.atom/.apmrc" "rebuild" "--target=0.36.8" "--arch=x64"
42 error node v0.10.40
43 error npm  v2.13.3
44 error code ELIFECYCLE
45 error zmq@2.15.3 install: `node-gyp rebuild`
45 error Exit status 1
46 error Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
46 error This is most likely a problem with the zmq package,
46 error not with npm itself.
46 error Tell the author that this fails on your system:
46 error     node-gyp rebuild
46 error You can get their info via:
46 error     npm owner ls zmq
46 error There is likely additional logging output above.
47 verbose exit [ 1, true ]

**Comment by n-riesco** [comment]
I usually find `npm-debug.log` of little help.
The error messages on the console are usually more informative.
Having said that, I've noticed something that potentially can confuse many build scripts.
Atom in your computer is installed in a path that contains spaces `/Applications/ Codingware/Atom.app`.
Probably, the error messages in the console could help tell whether this is the issue.

**Comment by RobBW** [comment]
n-riesco's suggestion worked.
On MacOS 10.11.5 all I had to do was remove the space from the file path and do:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig to provide the link to libzmq.
Hydrogen installed without any further problems.
Thank you all

**Comment by n-riesco** [comment]
@RobBW Thanks for reporting back and investigating the issue with ZMQ v2.15.1
