### ISSUE TITLE
[Feature request] Show execution count in results bubble

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#331]
The Jupyter notebook numbers any return values from cells, e.g. `Out [3]`. This number is called the `execution_count` in the Jupyter messaging spec.

I often find myself wanting to refer to the output of a previous computation, but the reference is currently not exposed through hydrogen. I think it would be useful to render the number somewhere or add a copy-execution-count button to the right sidebar.

**Comment by nikitakit** [comment]
@lgeiger @rgbkrk Could I ask for your feedback about possible UI designs for this?

This feature would have a big impact on my workflow, so I'm trying to take a shot at implementing it.

The tricky thing is that hydrogen uses different display styles for one-line outputs (inline display) and multi-line (it embeds a little frame with the output and some buttons). This feature would need to fit in with both styles. What do you think about displaying the execution count on mouseover? (Add it to the little bubble that says "Copy to clipboard").

**Comment by rgbkrk** [comment]
Now that we have the inline decorators, I've wondered why we can't always show it below.

As for the mouse over, that sounds like a good idea.

The only other thing that comes to mind is showing Out[num]. I'll be thinking on this.

**Comment by lgeiger** [comment]
Closed by #472
