### ISSUE TITLE
`hydrogen:inspect` is broken for `text/html` results

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#336]
While testing the last PR I noticed that `hydrogen:inspect` has been broken for some time.

I won't be able to look at this until tonight or tomorrow.

**Comment by lgeiger** [comment]
Strange `hydrogen:inspect` works for me as expected.

**Comment by n-riesco** [comment]
Must be something to do with my setup.

**Comment by n-riesco** [comment]
It works with the Julia kernel but fails with IJavascript.

**Comment by n-riesco** [comment]
This bug seems to be trigger by inspection results returns in `text/html` format. Transform return an `el` that is a `#document-fragment` that has no `innerHTML`.

I'll wait to fix this issue until after #338 is merged.
