### ISSUE TITLE
`hydrogen:inspect` is broken for kernels speaking protocol v4

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#342]
Ubuntu  16.04 provides IPython v2.4.1 and this kernel doesn't understand v5 of Jupyter messaging protocol.

**Comment by rgbkrk** [comment]
What would it be like to translate the messaging protocol v4 <---> v5?

**Comment by lgeiger** [comment]
There were quite a few changes:
https://jupyter-client.readthedocs.io/en/latest/messaging.html#introspection

**Comment by slavaGanzin** [comment]
So you decide to downgrade protocol because of Ubuntu LTS maintain standard?

You wouldn't be rude if you push your user to install jupyter. Hydrogen is developer/scientific package, so it can ask user to use newest software
