### ISSUE TITLE
Logo looks very similar to Ionic Logo

### ISSUE THREAD

**Issue by cgav** [nteract/hydrogen#349]
The logo looks incredibly similar to the Ionic Logo (http://ionic.io/).

**Comment by rockymadden** [comment]
I've found many more too: https://www.google.com/search?q=hydrogen

As such, I propose we change the name to lawrencium.

**Comment by rgbkrk** [comment]
Lawrencium is definitely not happening as a name change.

Amusingly, our logo changed to purple some time ago (and flipped direction) to look less like the Ionic logo (we were unaware). Someone flipped this back to the "cool blue" again. Someone can certainly make a new one that continues to work well as the in-Atom logo.

**Comment by beginrescueend** [comment]
This is another look at Hydrogen -- its spectral lines:
  https://ch301.cm.utexas.edu/svg/H-emission-spectrum.svg

**Comment by n-riesco** [comment]
@beginrescueend Genius!

**Comment by lgeiger** [comment]
We could use some stylized version of the spectral series similar to this: http://chemwiki.ucdavis.edu/@api/deki/files/27811/=96ab7ad43a8411f966e5390c6781c1d0.jpg?revision=1

**Comment by rgbkrk** [comment]
Keep in mind that it has to fit as a 32x32px logo within the use of Atom. The logo we stick on the README can be almost anything.

**Comment by rockymadden** [comment]
@rgbkrk Reread with `/s` tag :)
