### ISSUE TITLE
Low priority: replace test image in README screenshot

### ISSUE THREAD

**Issue by jdeisenberg** [nteract/hydrogen#352]
Isn't it about time to retire the "Lenna" image (shown in the demo.lua screenshot after the text starting "But it *should* work with any kernel...") for reasons stated here: http://imagecompression.info/test_images/

**Comment by n-riesco** [comment]
cc/ @willwhitney :smile: 

Since this is proving a popular subject, maybe we should held a poll and see if people can come up with something *"better"* than [Boaty McBoatface](https://duckduckgo.com/?q=Boaty+McBoatface&t=canonical&ia=web).

**Comment by rgbkrk** [comment]
Totally on board.
