### ISSUE TITLE
remove lena image from docs

### ISSUE THREAD

**Issue by scopatz** [nteract/hydrogen#353]
Almost any other image would be better. Perhaps consider an image of Rear Admiral Grace Hopper

**Comment by n-riesco** [comment]
cc/ @willwhitney :smile:

**Comment by willwhitney** [comment]
Go for it! It's only there because it's built in to [torch/image](https://github.com/torch/image) so it was quick to show image rendering.

**Comment by rgbkrk** [comment]
Totally agree with switching that image out.

**Comment by montogeek** [comment]
What is the problem with the image?

**Comment by scopatz** [comment]
its history makes it inappropriate https://en.m.wikipedia.org/wiki/Lenna

**Comment by montogeek** [comment]
Let's remove he image please :)

**Comment by scopatz** [comment]
thanks a million, I really appreciate it
