### ISSUE TITLE
Hydrogen seems to work with iElixir (Jupyter Kernel for Elixir)

### ISSUE THREAD

**Issue by beginrescueend** [nteract/hydrogen#354]
It didn't seem to, at first, but I did a couple of small things and it worked:
  https://github.com/pprzetacznik/IElixir/issues/18

**Comment by n-riesco** [comment]
@beginrescueend Thank you for the report!

**Comment by beginrescueend** [comment]
Welcome (and thank you).  

I first heard about Hydrogen on YCombinator News today.  I read the comments afterward, and found that somebody else reported success with iElixir:
  https://news.ycombinator.com/item?id=12099646
  https://news.ycombinator.com/item?id=12101107
