### ISSUE TITLE
Hard Time Installing on Windows

### ISSUE THREAD

**Issue by sirinath** [nteract/hydrogen#358]
I am getting the following errors:

```
C:\Users\HP>apm install hydrogen
Installing hydrogen to C:\Users\HP\.atom\packages failed

> zmq@2.15.3 install C:\Users\HP\AppData\Local\Temp\apm-install-dir-116616-7976-17hs9k3\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq
> node-gyp rebuild


C:\Users\HP\AppData\Local\Temp\apm-install-dir-116616-7976-17hs9k3\node_modules\Hydrogen\node_modules\jmp\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\HP\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\HP\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\HP\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\HP\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\HP\\.atom\\.apmrc" "install" "C:\\Users\\HP\\AppData\\Local\\Temp\\d-116616-7976-197aeq\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.


C:\Users\HP>
```

My platform is Win10 x64. I have VS2013 installed. I have both Python 2 & 3 installed through the respective Anaconda installer. In the shell I am executing the above has only Python 2 in the path.

**Comment by n-riesco** [comment]
Unfortunately, the error message isn't very informative.
Could you post the output of running `apm --version`?

**Comment by n-riesco** [comment]
The comment [here](https://github.com/nteract/hydrogen#installation) about installations where Python 3 is the default may be relevant.

**Comment by sirinath** [comment]
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.8.1.windows.1
visual studio 2013
```

**Comment by lgeiger** [comment]
The easiest way is to install python 2.7 via anaconda (see [here](https://github.com/nteract/hydrogen#windows))

**Comment by sirinath** [comment]
I have tried with Anaconda 2 & 3 and tried with only Python 2 is in the path. See the original issue for details.

**Comment by n-riesco** [comment]
On 19/07/16 11:38, Suminda Dharmasena wrote:
> |apm 1.9.2 npm 2.13.3 node 0.10.40 python git 2.8.1.windows.1 visual studio 2013 |

This means Atom can't see your installation of Python.

**Comment by sirinath** [comment]
How can this be rectified?

**Comment by n-riesco** [comment]
You need to tell Atom where the executable for Python 2 is located, by running something like this:
```
apm config set python path/to/python2.7/executable
```

We've seen reports of Windows users having problems when the Anaconda installation didn't include Python 2. But this is the first one where Atom cannot see the Python installed by Anaconda. Could you make sure Python is accessible in the command line?

**Comment by sirinath** [comment]
Python is accessible at command line

**Comment by sirinath** [comment]
Any new insights on how to overcome this issue?

**Comment by n-riesco** [comment]
Did you try using [apm config](https://github.com/nteract/hydrogen/issues/358#issuecomment-233620647)? What happened?

**Comment by n-riesco** [comment]
To locate the path to the python executable, you can run:
```python
import sys
print sys.executable
```

**Comment by sirinath** [comment]
Initially I was trying: `apm config set python c:\Anaconda2\` hence was getting the above error. Since the above code included the exe name also I tried `apm config set python c:\Anaconda2\python.exe` and it worked!

```
C:\>apm config set python c:\Anaconda2\python.exe
C:\>apm install hydrogen
Installing hydrogen to C:\Users\HP\.atom\packages done
```

Perhaps you can include this in the documentation?

**Comment by n-riesco** [comment]
On 21/07/16 04:13, Suminda Dharmasena wrote:
> Perhaps you can include this in the documentation?

Will do. Thank you for reporting back.
