### ISSUE TITLE
[Question] Is starting Atom from the terminal really necessary?

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#360]
The README says:
> Make sure to start Atom from the command line (with atom <directory or file>) for this package to work! See Jank.

On OS X this isn't necessary. How about linux and windows?

**Comment by n-riesco** [comment]
As far as I know , it never was an issue in linux or windows.
If I remember correctly it was fixed for OS X in Atom v1.8.0.

**Comment by Foucl** [comment]
On Windows 10 with Atom 1.9.0-beta0, Hydrogen works fine without command line startup.

**Comment by lgeiger** [comment]
Great! I'll update the readme.
