### ISSUE TITLE
Close icon blocking part of output

### ISSUE THREAD

**Issue by Mungoid** [nteract/hydrogen#362]
Outputs are mostly fine if they are larger, but for smaller outputs the close icon is blocking part of the result. 

![image](https://cloud.githubusercontent.com/assets/5993205/16929797/e483c422-4cfe-11e6-9e5b-3cad2560b16b.png)

I tried a few different themes thinking that was the issue, but it doesnt seem to make any difference. I see most of the gifs on this repo show a rounded square to the upper right of the output, so im not sure if thats a Mac thing or if Im using a wrong theme? 

Atom 1.1.0
Win 10 x64

**Comment by Mungoid** [comment]
So i just remembered the apm hydrogen package is an older version than whats current on Github. I assume that is probably the issue?

**Comment by lgeiger** [comment]
Exactly. Hydrogen requires atom version `1.6.0` or newer for some time now. Please update your atom installation and everything should look quite a bit different ;)

**Comment by lgeiger** [comment]
By the way the new version of Hydrogen now supports mathjax output. Try using `sympy` with
```python
init_printing(use_latex='mathjax')
```

**Comment by Mungoid** [comment]
Yep that was it. Once I downloaded a more current version of Atom and updated Hydrogen, it worked great. Dunno why I didnt notice this sooner, but atom.io download link only downloads version 1.1 even though github is up to 1.8. Serves me right for assuming whats on atom.io is current ;-)

Thanks for the tip on the mathjax output! I'll use that instead.
