### ISSUE TITLE
Add console support

### ISSUE THREAD

**Issue by spencerlyon2** [nteract/hydrogen#365]
It would be great to have a hydrogen console. 

I often work where I leave semi-permanent code in the editor and turn to the console or REPL for experimental code. Being able to do this all inside with hydrogen connected to the same kernel would be _awesome_!

The [atom-ink](https://github.com/JunoLab/atom-ink) project provides the machinery for such a console. 

Is it within the scope of hydrogen to build something like this? If so, it is feasible to hook up atom-ink?

**Comment by n-riesco** [comment]
There is a similar request in #166  .

Note that during an Atom session, all the kernels for a given language share the same kernel. So you could simply open a new panel and use it as an REPL.

We also have some functionality to reuse kernel connections. See the section for docker containers [here](https://github.com/nteract/hydrogen#custom-kernel-connection-inside-docker).

**Comment by spencerlyon2** [comment]
What I had in mind seems different from both opening a separate buffer to act as a "repl" or spawning a qt-console. 

The atom-ink package provides a fairly standard REPL experience with partial readline support, command history, etc. Using ink might not be the right solution here, but I'm referring to it because I think it is a good example of what I had in mind.

**Comment by n-riesco** [comment]
I'm going to label this issue as feature enhancement.

I've also noticed this feature was already listed in our [mostly-ignored-by-us roadmap wiki page](https://github.com/nteract/hydrogen/wiki/Roadmap) :blush: .

**Comment by lgeiger** [comment]
@spencerlyon2 I created a new package called [`hydrogen-launcher`](https://atom.io/packages/hydrogen-launcher) which allows you to spawn a new terminal with a `jupyter console` or `qtconsole` connected to the running Hydrogen kernel.

**Comment by spencerlyon2** [comment]
That's great, thanks!
