### ISSUE TITLE
$$html$$ output size problem

### ISSUE THREAD

**Issue by jmatsushita** [nteract/hydrogen#369]
Hi there,

When trying to run the following [IJavascript example](http://n-riesco.github.io/ijavascript/doc/graphics.ipynb.html) 

```
$$html$$ = "<div style='background-color:olive;width:50px;height:50px'></div>";
```

I get 

![image](https://cloud.githubusercontent.com/assets/356097/16958217/a0639d26-4dad-11e6-9c78-bbd03e24dc48.png)

This is what happens if I add something in the div like:

```
$$html$$ = "<div style='background-color:olive;width:50px;height:50px'>test</div>";
```

![image](https://cloud.githubusercontent.com/assets/356097/16958242/b5c76a94-4dad-11e6-9eac-1ce2186a5957.png)

The next `$$svg$$` example works but it looks like the canvas size is too big:

![image](https://cloud.githubusercontent.com/assets/356097/16958300/f125fee8-4dad-11e6-987b-f8a27265d85a.png)

Cheers!

Jun

**Comment by n-riesco** [comment]
@lgeiger This issue isn't specific to IJavascript. Here's a snippet to reproduce it using IPython:

```python
import IPython.display
IPython.display.HTML("<div style='background-color:olive;width:50px;height:50px'></div>")
IPython.display.HTML("<div style='background-color:olive;width:50px;height:50px'>test</div>")
IPython.display.HTML("<svg><rect width=80 height=80 style='fill: orange;'/></svg>")
```


@jmatsushita Thank you for reporting this issue. As a workaround, you can do this:

```js
$$.html("<div style='background-color:olive;width:50px !important;height:50px'></div>");
```

Although I haven't advertised this yet, the latest version of IJavascript provides new functionality to customise output. See [here](https://github.com/n-riesco/ijavascript/blob/dev/doc/custom.ipynb) and [here](https://github.com/n-riesco/ijavascript/blob/dev/doc/async.ipynb).

**Comment by lgeiger** [comment]
@n-riesco thanks for the IPython snippet. It's an issue with the styling of hydrogen. I'll take a closer look tomorrow.

**Comment by jmatsushita** [comment]
@lgeiger Thanks the css fix works!

@n-riesco The new syntax is great. And I'm excited about $$.async() !!! I've been wondering when I'd run into a library that didn't provide synchronous versions :)

**Comment by jmatsushita** [comment]
![image](https://cloud.githubusercontent.com/assets/356097/16975119/4edb1542-4e11-11e6-82c1-1e9e9f1062ea.png)

**Comment by n-riesco** [comment]
![screenshot from 2016-07-20 14-21-51](https://cloud.githubusercontent.com/assets/6199391/16987665/654f0918-4e85-11e6-80ec-c9c976e8d251.png)

**Comment by lgeiger** [comment]
I couldn't fix the SVG example with fiddling around in the dev console. I don't know why this is happening.

**Comment by n-riesco** [comment]
@lgeiger If it isn't easy, I think there is no much point fix the SVG case now (we will have to find another solution when we use webviews).

**Comment by jmatsushita** [comment]
Setting height and width on the svg element does it! 

`$$.svg("<svg height=80 width=80><rect width=80 height=80 style='fill: orange;'/></svg>")`

![image](https://cloud.githubusercontent.com/assets/356097/16994767/ccf9e54c-4e76-11e6-870a-04fb3b9790c0.png)

**Comment by n-riesco** [comment]
@jmatsushita Thanks! That makes sense.
