### ISSUE TITLE
[ZMQ] Bundle up necessary components or binary dependencies

### ISSUE THREAD

**Issue by rgbkrk** [nteract/hydrogen#37]
To make things easier on users, we need to find a way to bundle up zmq (or improve things upstream).

If we bundle binaries though, we'll quickly be out of date (or so I assume), because Atom is constantly updating which also means updates to node necessitating updates to `nan` and `zmq`. If we force the development headers to be vendorized, that's a different story.

There's also the case of seeing what the Atom team thinks, including asking about zmq being part of Atom or electron directly.

**Comment by willwhitney** [comment]
Getting zmq being bundled into Atom would be the best outcome for us, but I don't know how many other Atom packages use it and if that would be a good move for Atom as a whole.

Why do you say that node updates would break our binaries? I don't know enough about it to see what components would break.

**Comment by rgbkrk** [comment]
As V8 changes, function signatures changes, structs change, etc. To adapt to this, [nan](https://github.com/nodejs/nan) abstracts above these changes for you. https://github.com/JustinTulloss/zeromq.node uses this for instance. My assumption here is that if we create a build, it's a build for that specific version of node on that architecture since we don't want to rebuild with nan again.

> Getting zmq being bundled into Atom would be the best outcome for us, but I don't know how many other Atom packages use it and if that would be a good move for Atom as a whole.

I think Hydrogen could easily change this. :smile: Yeah, it's a bit of a stretch for the moment.
