### ISSUE TITLE
`hydrogen/connection.json` broken in MASTER

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#374]
Moved from https://github.com/nteract/hydrogen/issues/367#issuecomment-233668341

We should fix this before next release.

**Comment by lgeiger** [comment]
I checked today and connecting to an existing kernel via `connection.json` works for me as long as the kernelspec is available on the local system.

**Comment by n-riesco** [comment]
@lgeiger what do you mean by *"as long as the kernelspec is available on the local system"*?

I've checked again and it doesn't work for me. I'm planning to debug this issue today.

**Comment by lgeiger** [comment]
[`ZMQKernel`](https://github.com/nteract/hydrogen/blob/master/lib/zmq-kernel.coffee#L14) needs the kernelspec. If they are not available, Hydrogen won't even connect to the kernel (see [this line](https://github.com/nteract/hydrogen/blob/master/lib/kernel-manager.coffee#L31)).
