### ISSUE TITLE
Cell boundaries

### ISSUE THREAD

**Issue by jmatsushita** [nteract/hydrogen#375]
Hi there,

> Please note I've only used Hydrogen with IJavascript so I'm not sure if my observations only apply to this combination.

I think I understand that compared to a Jupyter notebook, it's difficult for Hydrogen to determine the boundaries of cells to enable the display of intermediary computation results in Atom when the whole notebook is ran? Is that the reason why intermediary results aren't displayed or updated?

For languages (like Javascript) where an optional line delimiter (`;`) can be used, wouldn't it be possible to use the presence of the delimiter as a cue to render the cell?

For other cases, or in addition to this, maybe Hydrogen could remember where existing cell runs have been requested and when a `run all` command is issued, it would update these bubbles (it seems that currently - with IJavascript - its only updating the final checkmark).

I guess that the more general case is to try to introspect the code to define the appropriate cell boundaries. This seems almost like something that would fit in a Kernel extension if there was interest upstream in allowing this type of freeform notebook. 

Let me know if that's unclear and I can explain more visually what I'm suggesting.

Cheers!

Jun

**Comment by jmatsushita** [comment]
Just had a thought that this might allow to copy paste in between Jupyter and Hydrogen!

**Comment by n-riesco** [comment]
We haven't documented this yet, but Hydrogen already provides the option to define code cell (see #328 ). The relevant commands are `hydrogen:run-cell` and `hydrogen:run-cell-and-move-down`.

**Comment by n-riesco** [comment]
@lgeiger Perhaps, we need to add a command to run all cells, e.g. `hydrogen:run-all-cells`.

**Comment by jmatsushita** [comment]
Is it supposed to work with IJavascript?

I'm trying this

**Comment by n-riesco** [comment]
In Javascript, cell boundaries are marked by:
```javascript
// %%
```

In general, for any other language, one has to use the syntax of that language to write comments.

**Comment by jmatsushita** [comment]
Oops, now I see it was specified in the pull request.

Sorry but I've never used this feature before and I'm fairly new with Jupyter. I can't make it work.

Is `// %%`is equivalent to `// <codecell>` and `// In[12]`?

Where should I place the code to execute? Is there an opening of the boundary and a closing of it? 😲 

Here are my feable attempts: 
```
// %%
x = 2

// In[1]
y = 2+2

// In[2] 
z = x-2

// <codecell>
// t = "in the comments??"
```

**Comment by n-riesco** [comment]
On 23/07/16 23:17, Jun Matsushita wrote:
> Oops, now I see it was specified in the pull request.
> 
> Sorry but I've never used this feature before and I'm fairly new with Jupyter. I can't make it work.

We really need to document this.


> Is |// %%|is equivalent to |// <codecell>| and |// In[12]|?

Yes, they are equivalent.

> Where should I place the code to execute? Is there an opening of the boundary and a closing of it? 😲

At the moment there are only two commands to run code cells:
-`hydrogen:run-cell`
-`hydrogen:run-cell-and-move-down`

Your example defines three code cells:
- `x = 2`
- `y = 2+2`
- `z = x-2`

If the cursor is between `// %%` and `// In[1]` when the command `hydrogen:run-cell` is invoked, then the first cell will be executed.


If the cursor is between `// In[1]` and `// In[2]` when the command `hydrogen:run-cell-and-move-down` is invoked, then the second cell will be executed, and the cursor will be moved down to the third cell.

The first `// %%` and the last `// <codecell>` aren't necessary, Hydrogen assumes the first cell starts at the beginning of the file, and the last cell finishes at the end of file.

**Comment by lgeiger** [comment]
> Perhaps, we need to add a command to run all cells, e.g. `hydrogen:run-all-cells`.

I would suggest we add this behavior to `hydrogen:run-all` rather than adding a new command for this. I'll make a PR next week.

> We really need to document this.

@n-riesco I would really appreciate if you could add this to the readme since my written english isn't that great.

**Comment by n-riesco** [comment]
On 24/07/16 13:48, Lukas Geiger wrote:
> I would suggest we add this behavior to |hydrogen:run-all| rather than adding a new command for this. I'll make a PR next week.

+1

>     We really need to document this.
> 
> @n-riesco <https://github.com/n-riesco> I would really appreciate if you could add this to the readme since my written english isn't that great.

Your written English is good enough.

**Comment by lgeiger** [comment]
> Your written English is good enough.

Thanks! I'll try my best and add it to the readme next week 😉

**Comment by jmatsushita** [comment]
Thanks so much for the explanation! I really appreciate your time and effort. Hydrogen is great! I also found a bug :)

**Comment by jmatsushita** [comment]
Oh and +1 to adding the behaviour to `hydrogen:run-all` !
