### ISSUE TITLE
In[] or In[{number}] syntax problem

### ISSUE THREAD

**Issue by jmatsushita** [nteract/hydrogen#377]
In the image below I've done `hydrogen:run-cell` in all cells. As you can see the cells with the `// %%` and `// <codecell>` syntax work just fine, but the `In[]` or `In[1]` syntax doesn't seem to be picked up. In fact when running `hydrogen:run-cell-and-move-down` in any of the 4 top cells, the cursor moves to the 5th cell.

![image](https://cloud.githubusercontent.com/assets/356097/17086602/a7d7c8aa-51c4-11e6-9811-2771fe373a80.png)

**Comment by lgeiger** [comment]
The syntax for defining code cells is `// In[ ]:`. Notice the space (or a number) between the brackets and the colon at the end.
@n-riesco Should we remove the need for the space between the brackets?

@jmatsushita Which syntax theme are you using? There should be syntax highlighting for the correct breakpoints:
<img width="248" alt="bildschirmfoto 2016-07-25 um 08 17 08" src="https://cloud.githubusercontent.com/assets/13285808/17092153/d2a5af76-5240-11e6-9123-dcfddb5bbae7.png">

**Comment by n-riesco** [comment]
@lgeiger Is the issue caused by the missing space between the brackets or the missing colon `:`?

+1 for making the space and numbers optional. I'd feel tempted to make the colon optional too.

**Comment by lgeiger** [comment]
> Is the issue caused by the missing space between the brackets or the missing colon `:`?

Both.

The idea about the space and the colon was to adhere to the `jupyter notebook` export format. They are using `// In[ ]:` for not executed cells and `// In[1]:` for executed ones.

I'm OK with removing the need for the space but I think without the colon the syntax highlighting would look odd. However I don't feel strongly about this. What do you think?
<img width="237" alt="bildschirmfoto 2016-07-25 um 08 40 45" src="https://cloud.githubusercontent.com/assets/13285808/17092522/8fbd9658-5243-11e6-9d7d-ff3860750a13.png">

**Comment by n-riesco** [comment]
How does spyder deal with `// In[ ]:`?

The reason why I thought optional spaces and colons are better is that users can easily make the mistake of leaving them out. Syntax highlight should've helped. @jmatsushita , do you know why in your screenshot the syntax highlight doesn't distinguish between normal comments and breakpoints?

The grammar highlight issue with optional colons would be solved by:
```cson
'match': '%%| %%| <codecell>| In\\[[0-9 ]+\\]:*'
```

**Comment by lgeiger** [comment]
Spyder requires just `// In[` (see [here](https://github.com/spyder-ide/spyder/blob/ef38c3837b4a08ee26435efff4d180e762f0cc00/spyderlib/utils/sourcecode.py#L35)).

OK lets make them optional.
