### ISSUE TITLE
Not finding PATH of installed iHaskell kernel

### ISSUE THREAD

**Issue by OmanF** [nteract/hydrogen#390]
After installing Jupyter, IHaskell (and verified it working with the server/web-browser config), I've installed Hydrogen via CLI into atom.

The attached screenshots show the error I get when trying to run some Haskell code with Hydrogen, as well as my settings.

My configuration is `Stack`-based Haskell installation (meaning I don't have GHC per-se but rather run `stack ghc`). The `GHC` installed by `Stack` (after `stack init`) is 7.10.3. Everything related to `Stack` **is** on the `$PATH` (as I modified my `zshrc` file to include it and verify it daily by running `stack ghci` from the prompt).
There is no `Cabal` or related apps.

(I know it's almost certainly configuration issue I got wrong but I can't figure it out myself. I **HAVE** tried tweaking the settings to the best of my understanding and the other issues I saw resolved, but failing to get things to work I reverted to default settings).

Thanks in advance.

![errormessage](https://cloud.githubusercontent.com/assets/7848797/17353589/b844f532-5949-11e6-8b89-8325fdb98028.png)

![devconsole](https://cloud.githubusercontent.com/assets/7848797/17353595/c3aceaf6-5949-11e6-8380-a2c023403eee.png)

![kernelspeclist](https://cloud.githubusercontent.com/assets/7848797/17353599/c8756f9a-5949-11e6-852e-58d3fcb3c730.png)

![settingskeptatdefault](https://cloud.githubusercontent.com/assets/7848797/17353601/cb9f6c70-5949-11e6-948a-cd508d145622.png)

**Comment by n-riesco** [comment]
Does the problem disappear if you save the file before starting Hydrogen?

**Comment by OmanF** [comment]
Yes it does!
Thanks for solving it (for me, saving, **once per Atom session**, before using Hydrogen, **repeatedly**, is non-issue).

**Thank you!**

P.S. Not closing since there's now a "*Bug*" label. This is dev's call.

**Comment by n-riesco** [comment]
This bug is fixed in #386 . We will make a release with the this fix soon.
