### ISSUE TITLE
Remove a watch by clicking on the X icon in the watch result view.

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#397]
Moved from https://github.com/nteract/hydrogen/pull/395#issuecomment-237332230

**Comment by lgeiger** [comment]
Would simply moving the remove button like this
<img width="305" alt="bildschirmfoto 2016-08-22 um 19 25 07" src="https://cloud.githubusercontent.com/assets/13285808/17864515/ae66ecaa-689e-11e6-85b0-9565a27c959d.png">
make it clearer?

**Comment by lgeiger** [comment]
I totally forgot about this issue.

@n-riesco What do you think about the UI shown above?

**Comment by n-riesco** [comment]
:+1: That shade of red looks a bit too bright to me (at least in contrast to the light blue) (are there any UI guidelines for Atom? a quick google search didn't get me far)

**Comment by n-riesco** [comment]
Forget my comment about the colours (I see these colours have been defined by the `atom-dark-ui` theme).

**Comment by lgeiger** [comment]
Excellent I'll rebase my old branch and make a PR 👍
