### ISSUE TITLE
Connect jupyter console to existing kernel

### ISSUE THREAD

**Issue by neurotronix** [nteract/hydrogen#403]
I usually execute some python 3 code via hydrogen and then connect to the existing kernel via jupyter console. However, the directory where I would usually find the kernel config files must have changed since I am not able anymore to connect to an existing kernel. I would really appreciate a comment on that issue. Many thanks in advance!

**Comment by n-riesco** [comment]
We're now using https://github.com/nteract/spawnteract to launch a kernel.

I think the easiest way to locate the connection file is to use the dev console. After starting a kernel, press `shift-ctrl-i` to open the dev console and look for `ZMQKernel` in the console log. You should see something like this:

![screenshot from 2016-08-11 14-55-21](https://cloud.githubusercontent.com/assets/6199391/17591053/40f4ba62-5fd4-11e6-995a-3f1a6e1644be.png)

Alternatively, you could run `jupyter --runtime-dir` to get the runtime folder.

**Comment by neurotronix** [comment]
Perfect, thank you!

**Comment by lgeiger** [comment]
@neurotronix In version `v0.13.0` we added a command to copy the path to the connection file. In order to allow connecting to the same kernel via `jupyter console --existing <path to connectionfile>`.
