### ISSUE TITLE
Hydrogen does not install on macOS 10.11.6 from the Package Install button

### ISSUE THREAD

**Issue by RobBW** [nteract/hydrogen#417]
I have found that I can only update Hydrogen from the Terminal, not the main screen:
[xbw]$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
[xbw]$ apm install hydrogen
Installing hydrogen to /Users/xbw/.atom/packages ✓

The error messages from the main screen point to zmq not being available. This is fixed by setting PKG_CONFIG_PATH as per #318 'apm rebuild' command errors'. 

FYI I experimented with adding an export command to Atom's init file but this  doesn't  fix the problem. It looks as if the export PKG_CONFIG_PATH command must be included within the Hydrogen install script.

**Comment by n-riesco** [comment]
Is Atom able to install Hydrogen when you run `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig atom`?

**Comment by willingc** [comment]
If you install `zmq-prebuilt` using `npm install zmq-prebuilt` and then install Hydrogen using Atom's package manager, Hydrogen does work well with OS X 10.11.6.

Install [`zmq-prebuilt`](https://github.com/nteract/zmq-prebuilt) from the command line:

```bash
npm install zmq-prebuilt
```

From Atom, go to the Atom->Preferences->Settings menu, install Hydrogen:

<img width="1136" alt="screen shot 2016-09-25 at 8 32 38 am" src="https://cloud.githubusercontent.com/assets/2680980/18816291/1db4982a-82fb-11e6-8955-22b16518bcba.png">

From Packages->Hydrogen menu, run lines of code:

<img width="546" alt="screen shot 2016-09-25 at 8 32 05 am" src="https://cloud.githubusercontent.com/assets/2680980/18816298/393b208c-82fb-11e6-809e-fc659455a57a.png">

Enjoy!

<img width="1132" alt="screen shot 2016-09-25 at 8 31 51 am" src="https://cloud.githubusercontent.com/assets/2680980/18816302/428020ca-82fb-11e6-8678-40c5e7316a01.png">

**Comment by rgbkrk** [comment]
@willingc I think that works because you have a working zmq environment. Hydrogen is still doing `require('zmq')` within it's node environment (which doesn't match the node environment you run on the CLI).
