### ISSUE TITLE
Python syntax error with indented block followed by triple quoted string

### ISSUE THREAD

**Issue by matthew-brett** [nteract/hydrogen#418]
With this Python file:

```
if True:
    print(True)

"""
A string"""
```

Hydrogen: Run - with the cursor over `if True:` gives this output:

```
File "<ipython-input-18-0c40b3af1bc9>", line 4
    """
       ^
SyntaxError: EOF while scanning triple-quoted string literal
```

No error when selecting Python code (not string) before Hydrogen: Run.

No error for

```
if True:
    print(True)

"""A string
"""
```

**Comment by lgeiger** [comment]
Hydrogen determines the code block to execute via Atom's fold range, more precisely with the function `editor.languageMode.rowRangeForCodeFoldAtBufferRow`.

I'm abroad this week and haven't investigated yet but I'm afraid this is an issue within Atom itself. Maybe you could try if the code folding of atom works as expected.

**Comment by matthew-brett** [comment]
Thanks - I submitted a report, closing here.
