### ISSUE TITLE
Specify a kernel for GitHub Markdown files?

### ISSUE THREAD

**Issue by fasiha** [nteract/hydrogen#419]
I’d like to tell Hydrogen to load the ijs kernel when I’m editing a README in Markdown for JavaScript code. I.e., to load `ijs` when editing `GithHub Markdown` files. I see the “Language Mappings” settings for Hydrogen, but that won’t quite work since that converts a kernel language *to* an Atom name.

**Comment by lgeiger** [comment]
Try setting `Language Mappings` to:
```json
{"javascript": "github markdown"}
```
 I tested it with python inside Markdown files and it worked fine.

**Comment by fasiha** [comment]
Doh! Thanks!
