### ISSUE TITLE
handle ANSI colors

### ISSUE THREAD

**Issue by willwhitney** [nteract/hydrogen#43]
We already do this if Python is started without a kernelspec, but we need to do this regardless. Otherwise we get ANSI color codes as in #42.

**Comment by willwhitney** [comment]
Another option is to use [strip-ansi](https://www.npmjs.com/package/strip-ansi)

**Comment by TKCen** [comment]
An alternative could be to support ansi via [ansi2html](https://www.npmjs.com/package/ansi2html) and display outputs as rendered html.

**Comment by Carreau** [comment]
You can execute `%colors nocolor` IIRC to deactivate that live. 

One of the things we should do anyway in IPtyhon itself is to transform the `error` into a mimebundle, so that you can grab the html/text/ansi as you wish.
