### ISSUE TITLE
No output on fresh install of Hydrogen

### ISSUE THREAD

**Issue by sindhus** [nteract/hydrogen#437]
thanks for making this!

I am on OS X. I have installed Atom, Jupyter, pkg-config and zeromq (the last two via brew). 
Nothing happens/is displayed when I select code `print ("hello")` in file and click on "hydrogen run". Here's a screenshot of the same:

![screen shot 2016-09-07 at 7 56 25 pm](https://cloud.githubusercontent.com/assets/4291156/18315615/3c87fd60-7535-11e6-869e-dc818d57a978.png)

I have checked with `apm --version` that it detects Python 2.x:

```
➜  ~ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
```

Let me know if there is any other information I can provide for debugging. Thanks.

**Comment by lgeiger** [comment]
This looks like issue #326.
Check that you haven't disabled `Use Shadow DOM` under `Settings > Editor`. This option should be enabled.

**Comment by sindhus** [comment]
That worked! thank you so much :)
