### ISSUE TITLE
Update installation instructions for windows

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#440]
I just discovered that Microsoft now provides a standalone C++ compiler without the need for visual studio:
http://landinghub.visualstudio.com/visual-cpp-build-tools

I haven't tested this yet, but I'm pretty confident.

**Comment by lgeiger** [comment]
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#prerequisites

**Comment by mmagnuski** [comment]
I can confirm that standalone C++ compiler works well when installing hydrogen on windows. :)
