### ISSUE TITLE
Error: no such option -f

### ISSUE THREAD

**Issue by sindhus** [nteract/hydrogen#442]
![screen shot 2016-09-12 at 8 40 02 pm](https://cloud.githubusercontent.com/assets/4291156/18441131/783ce0e4-7929-11e6-98de-42fd44dca20e.png)

What does this mean?

**Comment by lgeiger** [comment]
That's an error thrown from your code, likely from the `click` package. Is this code working in the jupyter notebook or the console?

You can have a look at the dev console (`cmd-alt-i`) to see if any errors are reported there and post a screenshot.

**Comment by n-riesco** [comment]
`click` is a python package to develop command line interfaces.

Closing this issue, because this is the expected result of using `click` within Hydrogen (or Jupyter console and notebook).
