### ISSUE TITLE
Hydrogen fails to install on Atom Mac OS

### ISSUE THREAD

**Issue by Chibuikem709** [nteract/hydrogen#445]
I am trying to download Hydrogen onto Atom but I keep getting this error:
>Installing “Hydrogen@0.14.0” failed.Hide output…

> zmq@2.15.3 install /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116816-56245-1miui9c/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

>/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116816-56245-1miui9c
`-- (empty)

>Package libzmq was not found in the pkg-config search path.
>Perhaps you should add the directory containing `libzmq.pc'
>to the PKG_CONFIG_PATH environment variable
>No package 'libzmq' found
>gyp: Call to 'pkg-config libzmq --libs' returned exit status 1 while in binding.gyp. while trying to >load binding.gyp
>gyp ERR! configure error 
>gyp ERR! stack Error: `gyp` failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit >(/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
>gyp ERR! stack     at emitTwo (events.js:87:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
>gyp ERR! System Darwin 15.6.0
>gyp ERR! command >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116816-56245-1miui9c/node_modules/Hydrogen/node_modules/zmq
>gyp ERR! node -v v4.4.5
>gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
>npm WARN enoent ENOENT: no such file or directory, open >'/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116816-56245-1miui9c/package.json'
npm WARN apm-install-dir-116816-56245-1miui9c No description
npm WARN apm-install-dir-116816-56245-1miui9c No repository field.
npm WARN apm-install-dir-116816-56245-1miui9c No README data
npm WARN apm-install-dir-116816-56245-1miui9c No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ChibuikemNwizu/.atom/.apm/.apmrc" "--userconfig" "/Users/ChibuikemNwizu/.atom/.apmrc" "install" "/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/d-116816-56245-5p1ioc/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

>npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
>npm ERR! Make sure you have the latest version of node.js and npm installed.
>npm ERR! If you do, this is most likely a problem with the zmq package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get information on how to open an issue for this project with:
>npm ERR!     npm bugs zmq
>npm ERR! Or if that isn't available, you can get their info via:
>npm ERR!     npm owner ls zmq
>npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
>npm ERR!     /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir->116816-56245-1miui9c/npm-debug.log
>npm ERR! code 1

**Comment by bishshoy** [comment]
Are you trying to install hydrogen on Python 3.5? I'm not sure whether that works or not. I faced a ton of problems trying to make it work. Finally, I solved it by installing deuterium instead of hyderogen.
Try these:
install Node from https://nodejs.org/en/ (Latest version)
brew install zeromq
pip install ipython
pip install git+https://github.com/nikitakit/xdbg
PYTHON=python2.7 apm install deuterium

**Comment by nikitakit** [comment]
Hi, I see you mentioned my deuterium package here. FYI I don't recommend installing deuterium as a long-term workaround for hydrogen not working. That package is due for an update, and in the process I'll probably switch it to be a plugin for hydrogen proper.

That said, it would be useful to figure out how hydrogen can make the install process more streamlined.

Can you try the following for installing hydrogen on Mac:
```
brew install pkg-config
brew install zeromq
PYTHON=python2.7 apm install hydrogen
```

Deuterium uses an older version of the hydrogen code, so if there really is a difference that means there has been a regression in a recent hydrogen release. When I last installed a non-git version of Hydrogen on my Mac, pre-installing zeromq and setting the `PYTHON` env var was sufficient to make it work. Installing from inside atom (i.e. not CLI) has never worked for me.

**Comment by bishshoy** [comment]
Not sure what I didn't do when I was trying to install Hydrogen myself, but your code just worked!
Thanks!

**Comment by Chibuikem709** [comment]
For some reason that still does not work. I have already installed pkg-config and zeromq. And the last line yields the same error as the original post.

**Comment by lgeiger** [comment]
It looks like `pkg-config` doesn't find `libzmq`.

Before messing around with the `PGK_CONFIG_PATH`. Could you do a fresh install by running
```
brew uninstall zeromq
brew uninstall pkg-config

brew install zeromq
PYTHON=python2.7 apm install hydrogen
```
and post the errors that get reported?

**Comment by Chibuikem709** [comment]
I get the same error:

> zmq@2.15.3 install /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116818-2395-1k5kckm/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

>/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116818-2395-1k5kckm
└── (empty)


>Package libzmq was not found in the pkg-config search path.
>Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
>No package 'libzmq' found
>gyp: Call to 'pkg-config libzmq --libs' returned exit status 1 while in binding.gyp. while trying to >load binding.gyp
>gyp ERR! configure error 
>gyp ERR! stack Error: `gyp` failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit (/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/node->gyp/lib/configure.js:305:16)
>gyp ERR! stack     at emitTwo (events.js:87:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
>gyp ERR! System Darwin 15.6.0
>gyp ERR! command >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
>gyp ERR! cwd /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116818-2395-1k5kckm/node_modules/Hydrogen/node_modules/zmq
>gyp ERR! node -v v4.4.5
>gyp ERR! node-gyp -v v3.4.0
>gyp ERR! not ok 
>npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116818-2395-1k5kckm/package.json'
>npm WARN apm-install-dir-116818-2395-1k5kckm No description
>npm WARN apm-install-dir-116818-2395-1k5kckm No repository field.
>npm WARN apm-install-dir-116818-2395-1k5kckm No README data
>npm WARN apm-install-dir-116818-2395-1k5kckm No license field.
>npm ERR! Darwin 15.6.0
>npm ERR! argv >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" >"/Users/ChibuikemNwizu/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ChibuikemNwizu/.atom/.apm/.apmrc" "--userconfig" >"/Users/ChibuikemNwizu/.atom/.apmrc" "install" >"/private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/d-116818-2395-23ejkc/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
>npm ERR! node v4.4.5
>npm ERR! npm  v3.10.5
>npm ERR! code ELIFECYCLE

>npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
>npm ERR! Make sure you have the latest version of node.js and npm installed.
>npm ERR! If you do, this is most likely a problem with the zmq package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get information on how to open an issue for this project with:
>npm ERR!     npm bugs zmq
>npm ERR! Or if that isn't available, you can get their info via:
>npm ERR!     npm owner ls zmq
>npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
>npm ERR!     /private/var/folders/ny/jd4d9h_90hv7l27ykfmg141m0000gn/T/apm-install-dir-116818-2395-1k5kckm/npm-debug.log
npm ERR! code 1

**Comment by lgeiger** [comment]
Does `pkg-config libzmq --libs` report an error to?

**Comment by lgeiger** [comment]
If the command returns a error try the solution described in [this comment](https://github.com/JustinTulloss/zeromq.node/issues/283#issuecomment-51431863):

- `brew install zeromq`
- `export PKG_CONFIG_PATH=/usr/local/Cellar/zeromq/4.1.5/lib/pkgconfig/`
- `sudo visudo` and add `Defaults env_keep += "PKG_CONFIG_PATH"`
- `apm install hydrogen`

Usually I don't like to recommend doing something with sudo but it seams it's the only chance to fix the `Package libzmq was not found in the pkg-config search path`error.

**Comment by Chibuikem709** [comment]
I still am unable to install hydrogen even after adding Defaults env_keep += "PKG_CONFIG_PATH" to sudo visudo

**Comment by Chibuikem709** [comment]
this message is interesting:

```
zeromq-4.1.2 already installed, it's just not linked
You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

is it relevant?
