### ISSUE TITLE
Can't install hydrogen on Windows 10 because apm still sees VS 2015

### ISSUE THREAD

**Issue by mmagnuski** [nteract/hydrogen#447]
I first installed VS 2015 and only later discovered that I should use VS 2013. I uninstalled 2015 and installed 2013 version but still can't install hydrogen. The reason is most likely that apm still somehow sees VS 2015 because `apm --version` gives me:
```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.8.1.windows.1
visual studio 2015
```

How can I change the visual studio that is used by apm? I looked around but couldn't find an answer.
(I can post the error message I am getting during instll but I'm almost certain it's because of visual studio used by amp).

**Comment by lgeiger** [comment]
We need to change the readme for this. I discovered last week that visual studio 2015 will work as long as you install it with the C++ compilers.

I don't have a windows machine to test right now, but I remember someone on stackoverflow suggested running `set GYP_MSVS_VERSION=2013` before running `apm install hydrogen`.

**Comment by mmagnuski** [comment]
I tried changing apm vs via:
```
apm config set msvs_version 2013 -g
```
and `apm --version` still gives me vs 2015 :( :
```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.8.1.windows.1
visual studio 2015
```

bUT `set GYP_MSVS_VERSION=2013` does the trick, after setting that `apm --version` displays vs 2013 and hydrogen installs correctly! 🎉 
Thanks!

as a sign of gratitude: [a silly youtube video](https://www.youtube.com/watch?v=BR62lpsGK8s) :)

**Comment by lgeiger** [comment]
Awesome! I'm glad it worked 🎉 

If you like, you can add your experience and the difficulties to our [troubleshooting guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

**Comment by mmagnuski** [comment]
I'm not sure about vs 2015 working - I tried installing hydrogen after installing vs 2015 and it didn't work... I can't tell if I installed with C++ compilers, I thought it is the default.
I can check vs 2015 on some other windows machine (I have plenty of these around :) ) if you direct me to info on how to install vs 2015 with relevant compilers etc. Once I succeed I can also help changing the docs (I have documentend the steps that led me to successful install [here](https://github.com/mmagnuski/mozg-rozpajton/blob/rey/install_hydrogen.md) ).

**Comment by mmagnuski** [comment]
I'll happily update troubleshooting guide. :)

**Comment by lgeiger** [comment]
@mmagnuski That would be excellent (We are mainly linux and mac devs here).

> I can't tell if I installed with C++ compilers, I thought it is the default.

That's the problem. VS 2013 shipped the C++ compilers by default. With VS 2015 you have to select the custom installation and explicitly select the C++ compilers (at least that's what the microsoft docs say). There should also be a option to install them later.

One more thing worth trying are the standalone C++ compilers mentioned in #440.

Thanks a lot for taking the time. Any first hand experience is really appreciated.

**Comment by mmagnuski** [comment]
I'll be happy to help - I'll look into correct VS installation etc. in the upcoming week (that is - starting tomorrow, at least in my timezone :) ). I've opened a PR (#448) and will update it accordingly.

**Comment by lgeiger** [comment]
@mmagnuski That's really great!

As a side note: We are working on including a [prebuilt version of zmq](https://github.com/nteract/zmq-prebuilt) but aren't [100% there yet](https://github.com/nteract/zmq-prebuilt/issues/2). If we get this to work it will improve the installation a lot.

**Comment by rgbkrk** [comment]
There's an even "easier solution" that Microsoft is aiming for now:

```
npm install --global --production windows-build-tools
```

**Comment by lgeiger** [comment]
@rgbkrk That's interesting. Would this work if we include it as a `apm` dependency on windows? So the users don't even have to install `node`?

**Comment by lgeiger** [comment]
Wow I just discovered there's even a `apm install --check` command which check that native build tools are installed.

**Comment by rgbkrk** [comment]
@lgeiger no idea, I was trying to use that when debugging https://github.com/nteract/zmq-prebuilt/issues/2

**Comment by lgeiger** [comment]
I'll try, time to startup a windows VM without compilers.

**Comment by sheperdsonbrown** [comment]
I am trying to install hydrogen and am getting this error. 

 zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ALEXBR~1\AppData\Local\Temp\apm-install-dir-116826-6760-1l7meiv\npm-debug.log
npm ERR! code 1

Any suggestions would be appreciated. Thanks
