### ISSUE TITLE
VS Code Integration

### ISSUE THREAD

**Issue by kuza55** [nteract/hydrogen#449]
This concept is super cool and it would be great if it was integrated into my editor of choice, VS Code.

@rgbkrk mentioned that he has investigated this in the past

A windows release would be great, though I hear that is blocked on zmq binary issues.

A linux-only release would still be useful to me as well.

**Comment by rgbkrk** [comment]
Yeah, I think it's worth checking out. If I had more free time, I'd start mocking it up with some of the packages available from nteract on npm.

**Comment by kuza55** [comment]
I don't know if I'll have much time to put in work on this either, but
maybe you could outline the changes you think will be necessary to get this
to work?

**Comment by hebijiandai** [comment]
Look at this,vscode support  jupyter notebook and has no lag in Windows platform.
![qq 20170101174849](https://cloud.githubusercontent.com/assets/5127081/21580766/abf148d0-d04a-11e6-847a-eed6404a7ea7.png)

**Comment by malarinv** [comment]
@hebijiandai It does but it seems like it isn't language agnostic like hydrogen is.

**Comment by rgbkrk** [comment]
There's [vscodeJupyter](https://github.com/DonJayamanne/vscodeJupyter) for this, I'm going to go ahead and close the issue. @DonJayamanne has done stellar work on VSCode + Jupyter. 😄

**Comment by valmormn** [comment]
vscodeJupyter is far behind hydrogen as a tool.

**Comment by schlichtanders** [comment]
maybe wait for the following issue to be resolved
https://github.com/Microsoft/vscode/issues/3220

**Comment by joolius** [comment]
vscodeJupyter didn't have updates for a year, and yes, it doesn't come even close to Hydrogen.

Atom has been unusable for people behind corporate proxies for like a year now and devs don't care. I doubt that things are going to get better for Atom now that Microsoft has bought github. Its two editors targeting the same audience and they're even built using the same framework. I love Atom, but what I would love even more is to see Hydrogen on VS Code.

**Comment by jflam** [comment]
Hi Folks, you should try our Python extension for VS Code - it has the beginnings of what we call the “Python Interactive Window” which you can think of as an editor-centric way of interacting with Jupyter, i.e., we’re not just dropping Jupyter into a web view tab in VS Code. 

Extension: https://marketplace.visualstudio.com/items?itemName=ms-python.python
Docs: https://code.visualstudio.com/docs/languages/python

Please let me know what you think!

**Comment by rgbkrk** [comment]
Thanks @jflam! What should non-Python users install for interactive Jupyter usage in Visual Studio Code?

**Comment by joolius** [comment]
@jflam ,  I think it looks promising, but in my view demarcating cells with "#%%" is a hassle. In Hydrogen I either run code line by line or select a block of code and run it. Results then appear either in the output window ("Python Interactive" in VS Code Python extension), or right after a Line/Block of code in the editor itself.

Is there a way to Run Selection/Line with Jupyter? I only see an option to send it to the terminal

![image](https://user-images.githubusercontent.com/10067941/49688000-d9ace980-fb0b-11e8-9c05-37692cfb2674.png)

**Comment by ronglums** [comment]
@joolius, this is definitely on our list to resolve. The challenge, however, is that Shift+Enter used to run code in Python Terminal exclusively, and it may not be desirable to non-data science users if we were to take it over to run code in the Python Interactive window. Perhaps a user setting to toggle b/w the two? Would love to hear suggestions!

**Comment by joolius** [comment]
@ronglums, it could be any key. My comment was rather there appears to be no command to Run Selection/Line **in Jupyter**.  There is a Run Cell command, but that is different as it executes whatever is between "#%%" tags, and I want to execute only a single line (or selection) in Jupyter. Do you know what I mean? :-)

**Comment by neo-anderson** [comment]
There are many reasons why Jupyter+Hydrogen+pweave+Atom setup works well for me as a data scientist. It makes it possible to recreate the RMarkdown workflow for python along with the advantages of the powerful Atom editor.
- The source file is a plain markdown file with code blocks denoted using ``` string, which is consistent with the standard markdown syntax. This means that I can preview the markdown file in any markdown preview application without making any changes.
- You can run entire code blocks or select the statements to run and execute the selection only. This is a huge time saver when compared to the Jupyter notebook way of creating blocks even for running a single statement. For example, if I quickly want to see the shape of a dataframe, I can just type `df.shape` inside the code block, run it (Cmd+Enter/Shfit+Enter) and delete it after seeing the result.
- Inline output display. The output from Jupyter is displayed as a frame/bubble under the statement that was run. Clicking this frame would copy the result into the clipboard. Handy.
- If I feed the source markdown file into pweave, I can export it into a pdf/html/md file with the output of the code blocks inserted. This feature is a recreation of the knitr+Sweave feature in R Studio.  Extremely useful for creating reports. This is one of the main reasons I switched to Atom. I use pweave to create a markdown file with code blocks replaced with the output from Jupyter and then I use pandoc to convert it into a pdf using themes/templates. It offers a lot of customization options for each code block too. For example, hide/show the code block in the exported report, hide/show the output results in the report, skip evaluation of code blocks, etc. Examples: echo=False, eval=True, results="hidden"
- Ability to maximize the code and markdown preview tabs and quickly switch between them using shortcut keys. "Maximize editor group" feature in VS Code will not maximize the tab to the full width of the window for some reason.

I am so excited to see the new update to the Python extension in VS Code. If the above features can be added to VS Code or even improved upon, data scientists will be able to use VS Code to efficiently perform their tasks.

Sample source file:
```
# Title
Hello world! This is a simple markdown file.
```python echo=False
print("Run this code block using hydrogen. If you use pweave to export this file, this code block would not be exported because echo parameter is set to False for this block.")
```

**Comment by BenRussert** [comment]
> Inline output display. The output from Jupyter is displayed as a frame/bubble under the statement that was run. Clicking this frame would copy the result into the clipboard. Handy.

Compared to atom, [VSCode is pretty restrictive when it comes to extensions.](https://code.visualstudio.com/api/extension-capabilities/overview#no-dom-access) I check back every now and then to see if we should look into porting hydrogen over, but I am not expecting that it will happen.

**Comment by ronglums** [comment]
@neo-anderson , thanks for the detailed notes! This is very helpful. :)

We have just added in the VS Code Python extension the ability to run any code selection (with or without %##) in the Interactive window. It's not released yet, but you can try out our [insiders build](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix).

Inline output display isn't feasible with the current VS Code UI, but we've looked into this and have an idea for how to enable it. 

Source markdown scenario makes a lot of sense. It is not something we've closely looked at, but will keep in mind down the road.

Regarding the "maximize editor group" behavior, sounds like this issue: https://github.com/Microsoft/vscode/issues/62083. Please vote on it! :)

**Comment by neo-anderson** [comment]
@BenRussert Is it possible to use the interactive window of VS Code to display the output from Hydrogen? Are there other issues blocking the port?

Thanks for the response, @ronglums. Excited to hear the progress.
Unfortunately, I couldn't get the insiders build to work. I installed the extension and I tried running some code. But the Interactive window only shows "/Users/aswinraj/.vscode/extensions/ms-python.python-2019.2.5135-alpha/out/datascience-ui/history-react/index_bundle.js is not a valid file name". Not sure how to fix it. 

Good to know that you're thinking about inline output and markdown source. That would totally fit the data science workflow popularized by R Markdown.

**Comment by BenRussert** [comment]
@neo-anderson you can use the VSCode extension API to render outputs in a pane (some VSCode extensions do this) but not inline/block in an editor line we do with hydrogen. 

> Inline output display isn't feasible with the current VS Code UI, but we've looked into this and have an idea for how to enable it.

@ronglums I'd love to see what you are referring to here. Inline in an editor?

**Comment by ronglums** [comment]
@neo-anderson , not sure why the insiders doesn't work for you. :( @IanMatthewHuff @rchiodo, any thoughts?

@BenRussert , yes, inline results in the code editor. This requires changes in VS Code core.

**Comment by NavyAdmiral** [comment]
@BenRussert Actually with https://github.com/Microsoft/vscode/pull/66418 merged, vscode's exposed API should be enough now

**Comment by StevenLi-DS** [comment]
hydrogen is really an amazing extension and I've been using it for anything: python, r, stata, and even julia recently😂... I really wish there could be a vscode version of it.

@ronglums The python extension is indeed amazing. any plan we can a jupyter interactive window so that it can support another language or something?

**Comment by rchiodo** [comment]
Python was the main language for datascience, but we plan on adding others in the future.
You can vote on them here:
https://github.com/microsoft/vscode-python/issues/5078

**Comment by joolius** [comment]
@BenRussert , are there any plans for this now that the API seems to be exposed enough? I love Hydrogen, but Atom does not work behind many if not most corporate proxies, has been this way for a a couple of years now, and there are apparently no plans to fix it... meaning that I have to switch to VS Code.

**Comment by wadethestealth** [comment]
@joolius vscode-python is already popular and being maintained which is basically vscode hydrogen

**Comment by joolius** [comment]
> @joolius vscode-python is already popular and being maintained which is basically vscode hydrogen

They feel very different to me. vscode-python, at least currently, seems to be focused on just emulating jupyter inside of VS Code. You have to mark your code cells with "#%%", no way to print results inline, cumbersome execution line-by-line. It may seem like little, but it feels very different if your workflow is very interactive, which is the case when doing data science.

Some competition is always good, too. :) 

Just to be sure, vscode-python is already very good and probably satisfies most people's needs, but it does not cover what Hydrogen excels at - providing various productivity enhancements for highly interactive workflows.

**Comment by wadethestealth** [comment]
I think that it's just not the direction nteract is going. Hydrogen is an older now and most of nteract focuses on the desktop app.

**Comment by ronglums** [comment]
Thanks for your kind words for vscode-python! @wadethestealth @joolius  The upcoming update will support an inline execution workflow for notebooks, which is much closer to the classic Jupyter style. hope that will help! :)
https://twitter.com/davorabbit/status/1176314998806630400

**Comment by wadethestealth** [comment]
@ronglums no problem, and this is also very interesting news.

**Comment by joolius** [comment]
@ronglums unfortunately for me, i'm not really looking for Jupyter style :(. Hydrogen uses jupyter under the hood, but offers a very different experience, that fits me much better when doing data science. Inline evaluation and **not** having to deal with code cells is what I'm looking for.

Atom has become completely unusable for me (apm is not working behind corporate proxies), so I have just moved to VSCode, but sticking to the terminal for now.

**Comment by IDDT** [comment]
I agree with @juliuscrn, Atom+Hydrogen is currently the no-alternative combo for interactive programming that is dissimilar to Jupyter Notebook cells approach. Inline execution allows even more rapid prototyping with the end result being a git-ready pure python script.

**Comment by neo-anderson** [comment]
Atom+Hydrogen made R Notebook style workflow possible for data scientists working with Python. You can quickly preview the document using any markdown preview tool and you can specify whether specific code chunks/output should be excluded from the final report, etc. 
It's unfortunate that this issue has been closed. Ironically, R Notebook now supports Python. So, anyone who wants that workflow could probably download R Studio and give it a shot!

**Comment by juliuscrn** [comment]
> However, we also impose restrictions upon extensions to ensure the stability and performance of VS Code. For example, extensions cannot access the DOM of VS Code UI

Is this the reason why we don't have something like Hydrogen in VS Code yet?

https://code.visualstudio.com/api/extension-capabilities/overview

**Comment by rchiodo** [comment]
> Is this the reason why we don't have something like Hydrogen in VS Code yet?
>
> https://code.visualstudio.com/api/extension-capabilities/overview

Sort of I guess. That does it make it more difficult. Especially for our team (which don't own VS code itself). 

However VS code's new notebook work may make this more possible in the future. They're inventing a way to ensure that the output cells can talk to each other but still be isolated from the DOM with your code in it.

**Comment by Dvisacker** [comment]
Just for information, the quokka vscode extension (https://quokkajs.com) does something similar to what hydrogen and the light table editor does. Unfortunately it's only javascript/typescript.

**Comment by juliuscrn** [comment]
Wolf (https://marketplace.visualstudio.com/items?itemName=traBpUkciP.wolf) shows that inline evaluation is possible. However, Wolf itself quite different from Hydrogen. You type code and after half a second it will evaluate the code whether you want that or not.

**Comment by 2sls** [comment]
I would also love to see Hydrogen in vscode 

While Jupyter support is pretty good (comparable to what you see in docker output) - having more kernel support would be great.

**Comment by HenrikEckermann** [comment]
Looking for alternative to Atom + Hydrogen, which to me was by far the best way to do data science in R or Python. Since I found that, I never looked for alternatives anymore. Now, years later, I have to look and am surprised that nobody copied that idea yet...Whichever editor can copy that will be my goto.

**Comment by juliuscrn** [comment]
There is nothing. Zed and Fleet are in their infancy and there's some hope that they will become something similar like Atom (although Fleet will probably follow Micro$oft in not allowing extensions to modify the UI in any meaningful way).

It's depressing. It feels like technology is regressing.

**Comment by neo-anderson** [comment]
@HenrikEckermann I started using R Studio+Python to generate reports and such! Python compatibility isn't bug-free and the editor isn't as powerful as VS Code/Atom, but the experience is better (to me) than going the Jupyter notebook route

**Comment by oladimeji09** [comment]
+1

**Comment by kylebarron** [comment]
I wrote a quick [extension for vscode](https://github.com/kylebarron/vscode-jupyter-python) a couple months ago that implemented "automatically inferring a Python code block" so that you don't have to select it manually (i.e. press <kbd>Ctrl</kbd> + <kbd>Enter</kbd> on the `def` line and it'll send the entire function definition to the interactive Jupyter session in the right pane), which was a very helpful feature of Hydrogen for me.

vscode's interactive Python support is still inferior to Hydrogen IMO, but at least that made it _passable_ for me.

**Comment by giancarloantonucci** [comment]
+1
