### ISSUE TITLE
tarball.destroy

### ISSUE THREAD

**Issue by 1NAX2** [nteract/hydrogen#457]
Installing “Hydrogen@0.14.0” failed.Hide output…

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\nan\-\nan-2.3.5.tgz.311234656' -> 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\nan\-\nan-2.3.5.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\nan\-\nan-2.3.5.tgz.2716459496' -> 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\nan\-\nan-2.3.5.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz.337917317' -> 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz.14116387' -> 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz.567542684
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz.567542684' -> 'C:\Users\Conor\AppData\Local\Temp\npm-2304-4f985813\registry.npmjs.org\punycode\-\punycode-1.3.2.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Conor\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Conor\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Conor\\.atom\\.apmrc" "install" "C:\\Users\\Conor\\AppData\\Local\\Temp\\d-116827-42468-12bgwx5\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Conor\AppData\Local\Temp\apm-install-dir-116827-42468-13s1iin\npm-debug.log

**Comment by lgeiger** [comment]
It might be your anti-malware program. Check http://stackoverflow.com/questions/36835882/npm-err-tarball-destroy-is-not-a-function
