### ISSUE TITLE
Questions about Installation

### ISSUE THREAD

**Issue by pingshunhuangalex** [nteract/hydrogen#460]
Hi

I just started using Atom yesterday, and Hydrogen is exactly something I've been dreaming of for a long time. However, it's also one of the most confusing installation I've ever had. I really tried...

Previously, I had Anaconda3 as my default python3, I had a python2 virtualenv. I installed the 5G VS Community 2015, and tried to run:
1. Everything in python 2 virtualenv. Failed. (node-gyp rebuild)
2. Install python 2 and using command ```PYTHON=python2.7 apm install hydrogen```. Failed. (node-gyp rebuild)

Then I saw the troubleshooting section saying I need exact VS 2013 changed using
```apm config set msvs_version 2013 -g
set GYP_MSVS_VERSION=2013```
I tried, and then in ```apm --version``` VS doesn't have a year (version) after it, so I read again it means VS is not detected. I uninstalled everything, and read thing in https://github.com/nodejs/node-gyp#installation, saying you don't have to install the 5G things, you just need Visual C++ build tool. Ok, I did that again, no luck. (And then I read this thread. The guys said VS 2015 is fine... What?! https://github.com/nteract/hydrogen/issues/458)

Reading through trouble shooting again, ok we may need to set ```npm config set python /path/to/executable/python2.7``` and as well as ```apm config set python $(which python2.7)``` No luck again.

I ran ```apm --version``` again, now both python and VS doesn't have a version number after them, meaning it can't detect either of them. I tried to set npm and apm back to python3, then it just breaks everything. ```apm --version``` just stops working. So I ended up achieving nothing yesterday and uninstall all my coding packages...

So, back to the question:
1. I don't want to change python version ever again, I'll just follow exactly what you're asking for. I'm now downloading VS 2013. Will this solve my problem? So only installing the full package helps, install build tools or other methods won't. Am I correct?

2. I have to install python 2 (hopefully anaconda 2 will work) as my default python. Tricks like PYTHON=python2.7 won't work. Am I correct?

3. Does it mean, I can never upgrade my VS to 2015? Otherwise, I break everything?

4. Is there anything I should know that can help me start to use this package?

Thanks.

**Comment by pingshunhuangalex** [comment]
New Updates:

Now my laptop runs a python2 as default...

Meanwhile, I found a historical version of VS 2013 Update 4. Installed it and run ```apm --version```. The version no. after visual studio is surprisingly 2012... However, by running ```apm config ls -l``` I can see ```msvs_version = 2013```

Run your magic command again for no reason
```
apm config set msvs_version 2013 -g
set GYP_MSVS_VERSION=2013
```
Doesn't change anything... still 2012

Again try to install via ```apm install hydrogen```, no luck again still got node-gyp rebuild error...

Well, I'm uninstall VS2013 now, want to have another go with 2015 to see if I have any luck.

You know... any help would be appreciated.

**Comment by pingshunhuangalex** [comment]
I did everything perfectly, and strictly following the instruction and troubleshooting, but still no luck. I'm out of methods. Please see the log below, somebody please help...

```
 apm config list
; cli configs
globalconfig = "C:\\Users\\Pingshun Huang\\.atom\\.apm\\.apmrc"
user-agent = "npm/3.10.5 node/v4.4.5 win32 ia32"
userconfig = "C:\\Users\\Pingshun Huang\\.atom\\.apmrc"

; userconfig C:\Users\Pingshun Huang\.atom\.apmrc
GYP_MSVS_VERSION = "2013"
msvs_version = "2013"

; globalconfig C:\Users\Pingshun Huang\.atom\.apm\.apmrc
cache = "C:\\Users\\Pingshun Huang\\.atom\\.apm"
progress = false

; node bin location = C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe
; cwd = C:\Users\Pingshun Huang\Desktop
; HOME = C:\Users\Pingshun Huang
; "npm config ls -l" to show all defaults.
```

```
$ apm -v
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.0.windows.1
visual studio 2015
```
```
$ apm install hydrogen
Installing hydrogen to C:\Users\Pingshun Huang\.atom\packages failed

> zmq@2.15.3 install C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\node_modules\Hydrogen\node_modules\zmq
> node-gyp rebuild


C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\node_modules\Hydrogen\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7
`-- (empty)


module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\package.json'
npm WARN apm-install-dir-11691-11456-v4ild7 No description
npm WARN apm-install-dir-11691-11456-v4ild7 No repository field.
npm WARN apm-install-dir-11691-11456-v4ild7 No README data
npm WARN apm-install-dir-11691-11456-v4ild7 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apmrc" "install" "C:\\Users\\PINGSH~1\\AppData\\Local\\Temp\\d-11691-11456-krlso9\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\npm-debug.log
npm ERR! code 1
```

**Comment by n-riesco** [comment]
On 30/09/16 18:21, Pingshun Huang wrote:
> I did everything perfectly, and strictly following the instruction and troubleshooting, but still no luck. I'm out of methods. Please see the log below, somebody please help...
> 
> |apm config list ; cli configs globalconfig = "C:\\Users\\Pingshun Huang\\.atom\\.apm\\.apmrc" user-agent = "npm/3.10.5 node/v4.4.5 win32 ia32" userconfig = "C:\\Users\\Pingshun Huang\\.atom\\.apmrc" ; userconfig C:\Users\Pingshun Huang\.atom\.apmrc GYP_MSVS_VERSION = "2013" msvs_version = "2013" ; globalconfig C:\Users\Pingshun Huang\.atom\.apm\.apmrc cache = "C:\\Users\\Pingshun Huang\\.atom\\.apm" progress = false ; node bin location = C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe ; cwd = C:\Users\Pingshun Huang\Desktop ; HOME = C:\Users\Pingshun Huang ; "npm config ls -l" to show all defaults. |
> 
> |$ apm -v apm 1.12.5 npm 3.10.5 node 4.4.5 python 2.7.12 git 2.10.0.windows.1 visual studio 2015 |
> 
> |$ apm install hydrogen Installing hydrogen to C:\Users\Pingshun Huang\.atom\packages failed > zmq@2.15.3 install C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\node_modules\Hydrogen\node_modules\zmq > node-gyp rebuild C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\node_modules\Hydrogen\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "" rebuild ) C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7 `-- (empty) module.js:327 throw err; ^ Error: Cannot find module 'C:\Users\Pingshun Huang\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js' at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Function.Module.runMain
> (module.js:441:10) at startup (node.js:139:18) at node.js:968:3 npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\package.json' npm WARN apm-install-dir-11691-11456-v4ild7 No description npm WARN apm-install-dir-11691-11456-v4ild7 No repository field. npm WARN apm-install-dir-11691-11456-v4ild7 No README data npm WARN apm-install-dir-11691-11456-v4ild7 No license field. npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apmrc" "install" "C:\\Users\\PINGSH~1\\AppData\\Local\\Temp\\d-11691-11456-krlso9\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32"
> "--global-style" "--msvs_version=2015" npm ERR! node v4.4.5 npm ERR! npm v3.10.5 npm ERR! code ELIFECYCLE npm ERR! zmq@2.15.3 install: `node-gyp rebuild` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the zmq package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! node-gyp rebuild npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs zmq npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm owner ls zmq npm ERR! There is likely additional logging output above. npm ERR! Please include the following file with any support request: npm ERR! C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-11691-11456-v4ild7\npm-debug.log npm ERR! code 1 |


Atom sees an installation of Visual Studio 2015 (note that, by default, Visual Studio 2015 doesn't install a C++ compiler). Please, see my comment here:

https://github.com/nteract/hydrogen/issues/458#issuecomment-250800146

**Comment by pingshunhuangalex** [comment]
Thank you so much @n-riesco !! You are a true life saver!!! I came across your comment in #485 several times, but the most valuable part of the answer is actually folded. Therefore, it just slipped through...

I suggest you include the above reply in the documentation or troubleshooting. It is the missing of this single sentence that keeps me occupied for nothing for 2 days. It's now 4:11 in the morning, I can finally have a good rest.

Amazing package BTW, please keep up the good work!
