### ISSUE TITLE
Hangs while 'Existing kernel starting'

### ISSUE THREAD

**Issue by aornugent** [nteract/hydrogen#464]
I am trying to connect Hydrogen to a IJulia kernel running in a Docker container. Hydrogen detects an existing kernel but never progresses past start up.

My kernelspec (from inside the container) are as follows:
```
{
  "kernelspecs": {
    "julia-0.6": {
      "resource_dir": "/root/.local/share/jupyter/kernels/julia-0.6", 
      "spec": {
        "language": "julia", 
        "display_name": "Julia 0.6.0-dev", 
        "env": {}, 
        "argv": [
          "/usr/local/src/julia/usr/bin/julia", 
          "-i", 
          "--startup-file=yes", 
          "/root/.julia/v0.6/IJulia/src/kernel.jl", 
          "{connection_file}"
        ]
      }
    }, 
    "python2": {
      "resource_dir": "/usr/local/lib/python2.7/dist-packages/ipykernel/resources", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/usr/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}
```

My connection.json file, inside `./hydrogen/`:

```
{
  "stdin_port": 46167, 
  "ip": "172.17.0.2", 
  "control_port": 38650, 
  "hb_port": 56184, 
  "signature_scheme": "hmac-sha256", 
  "key": "c9feac24-eda7-4265-be5f-3ffbeb3faf2e", 
  "kernel_name": "", 
  "shell_port": 42655, 
  "transport": "tcp", 
  "iopub_port": 38724
}
```

I have tried running both IJulia and IPython kernels with `julia -i --startup-file=yes /tmp/hydrogen/connection.json` or `'python -m ipykernel -f /tmp/hydrogen/connection.json` respectively.

Any advice is appreciated!

**Comment by lgeiger** [comment]
To help us debug could you post a screenshot of the dev-console (cmd-alt-i) in Atom?

**Comment by aornugent** [comment]
![screen shot 2016-10-04 at 8 07 41 am](https://cloud.githubusercontent.com/assets/20387761/19054156/59bcbc6e-8a01-11e6-8378-0fa17b0a0380.png)

**Comment by n-riesco** [comment]
On 03/10/16 22:00, aornugent wrote:
> I am trying to connect Hydrogen to a IJulia kernel running in a Docker container. Hydrogen detects an existing kernel but never progresses past start up.
> 
> My kernelspec (from inside the container) are as follows:

Note that Hydrogen won't see kernel specs installed in a container.

We have a section in the README.md dedicated to running an IPython kernel in docker. See:

https://github.com/nteract/hydrogen#custom-kernel-connection-inside-docker

**Comment by person157** [comment]
Yes, I have followed these instructions. From the dev-console, ZMQ appears to find the correct connection.json file (created inside the container and mounted on host). Could port/IP settings be misconfigured? I usually access my notebooks at localhost:8888.

**Comment by aornugent** [comment]
Yes, I have followed these instructions. From the dev-console, ZMQ appears to find the correct connection.json file (created inside the container and mounted on host). Could port/IP settings be misconfigured? I usually access my notebooks at localhost:8888.

**Comment by n-riesco** [comment]
My bad! I should've paid more attention to the title of your issue and ignore the kernelspec.

Note that kernelspecs shouldn't be needed to connect to existing kernels (at some point we had an issue that prevented this).

What I understand now is that you need is to adapt the instructions to connect to an existing kernel so that they work with IJulia.

Am I correct in thinking the instructions still work for IPython?

**Comment by aornugent** [comment]
No dice. Pasting the command from the docker instructions
`echo "alias hydrokernel='python -m ipykernel "'--ip=$(hostname -I)'" -f /tmp/hydrogen/connection.json'" >> /etc/bash.bashrc` results in the same message of 'Existing kernel: starting" indefinitely.

In my original post I adapted the IJulia commands from the kernelspec args.

**Comment by polyma** [comment]
I'm having the same issue. I'm using docker-compose. I've deleted the 'ip' section of the command line input so it defaults to 0.0.0.0 (which I should be able to connect to in docker-compose). I have also forwarded all the ports mentioned in connection.json... to no avail. Is there a verbose connection output we could be using to debug?

**Comment by polyma** [comment]
Actually, it was a spelling error on my part, I got it working using this on the command line
`python -m ipykernel --stdin=45323 --iopub=43223 --shell=41454 --control=44186 --hb=40772 --ip=0.0.0.0 -f /tmp/hydrogen/connection.json`

with this as my docker-compose.yml
`  workspace:
    build: .
    ports: 
      - "45323:45323"
      - "44186:44186"
      - "40772:40772"
      - "41454:41454"
      - "43223:43223"
    volumes:
      - .:/usr/src/app
      - ./hydrogen:/tmp/hydrogen #hydrogen connection info
    command: python -m ipykernel --stdin=45323 --iopub=43223 --shell=41454 --control=44186 --hb=40772 --ip=0.0.0.0 -f /tmp/hydrogen/connection.json
`

**Comment by aornugent** [comment]
Thanks polyma, that's done the trick.
