### ISSUE TITLE
Spurious autocomplete when using MagicPython

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#465]
I recently installed the MagicPython package for atom, to get myself better syntax highlighting for python3-only features. However, this causes hydrogen to start autocompleting `%%!` after you type a `:`, which is extremely annoying.

Steps to reproduce:
- Install the MagicPython package, and disable the language-python package
- Set hydrogen's language mappings setting to include `{"python":"magicpython"}`
- Open a python file and make sure the grammar is set to MagicPython
- Start a hydrogen python kernel
- Type `while True:`, then press enter

Expected behavior: the cursor goes to a new line
Actual behavior: autocomplete menu suggesting `%%!` pops up right before you press enter, so you end up accidentally accepting the suggestion instead of moving to a new line.

I find that having to press ESC to close autocomplete any time I want to start an indented block is really irritating.

Does anyone have an idea about why this is happening, and if there's a way to address this?

**Comment by lgeiger** [comment]
I guess the autocomplete provider doesn't respect the language mappings setting. Hence the [python regex](https://github.com/nteract/hydrogen/blob/master/lib/autocomplete-provider.js#L12) isn't used to determine the completions.

**Comment by lgeiger** [comment]
@nikitakit I completely forgot about this issue. I made a PR to fix it: #581
