### ISSUE TITLE
Support carriage return symbol

### ISSUE THREAD

**Issue by kilotaras** [nteract/hydrogen#466]
Hydrogen doesn't respect `\r` symbol

`print('ab\rcd')` will produce `cd` in console and/or jupyter notebook. In hydrogen it will show up as

```
ab
cd
```

This is especially critical when working on scripts that report progress, e.g. use `tqdm`

Atom version: 1.10.2
Hydrogen version: 0.14.0

**Comment by n-riesco** [comment]
cc/ @rgbkrk 

I believe this is a bug in the latest version of Jupyter. Both Hydrogen and IPython 2.4.1 produce the expected output:

```
ab
cd
```

**Comment by lgeiger** [comment]
I add the `bug` label again since the output looks like this:
<img width="202" alt="bildschirmfoto 2016-10-12 um 11 23 28" src="https://cloud.githubusercontent.com/assets/13285808/19304804/7715f230-906e-11e6-97c5-b8ce40445190.png">
It should be a multiline bubble otherwise it breaks the layout of the following code line.

**Comment by kilotaras** [comment]
ipython 2.4.1 was released almost a year ago. Current version is 5.1.0 which produces `cd` in output. 
![selection_053](https://cloud.githubusercontent.com/assets/590292/19305631/8334c008-907a-11e6-9f3c-5940ea304cda.png)

This is used mostly in progressbars (e.g. keras model training).
In hydrogen output produced can span several hunreds lines.

**Comment by n-riesco** [comment]
@kilotaras Oh, I see. Now, I understand what the issue is. I'm going to label this issue as a feature request.

@lgeiger I reckon this is best implemented in `transformime`.

**Comment by lgeiger** [comment]
Yes we should definitely handle this in `transformime`.

I still don't fully understand the expected behavior.
Is the `\r` supposed to remove the two surrounding characters? How would that help with progress bars?

**Comment by rgbkrk** [comment]
\r (by itself with no newline) is a carriage return. It returns the console writer to the first position.

Historically, this "carriage" was the printer head on a type writer. When you hit the key, the printer head would go back to the start - allowing you to type over the line you were just on.

![carriage return](https://media.giphy.com/media/48zjXYRwBg5IQ/giphy.gif)

Using this, you can overwrite the previous line.

The more general problem is to handle more of the character codes to allow the cursor to move all over. You basically need to manage a TTY then, which, if you're interested I'm happy to explore.

**Comment by lgeiger** [comment]
Ahh thanks. I misread the expected behavior.
I read `ad` instead of `cd`. That makes sense now!

**Comment by lgeiger** [comment]
For reference: https://github.com/nteract/ansi-to-react/issues/2

**Comment by lgeiger** [comment]
The`jupyter notebook` handles it like this: https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/utils.js#L446

I tried:
```python
print('this sentence\rthat\nwill make you pause')
```

`jupyter notebook` prints:
```
that
will make you pause
```

`jupyter console` prints:

 ```
that sentence
will make you pause
```

**Comment by ivan-krukov** [comment]
As far as progress bars go, #474 does not resolve this:
![image](https://cloud.githubusercontent.com/assets/1881263/22233053/8886af22-e1aa-11e6-95ca-f82d6759c385.png)

It seems that since output is updated over time, `\r`s get ignored.

**Comment by rgbkrk** [comment]
@lgeiger - you may want to [check out stdout and stderr joining as is done in nteract](https://github.com/nteract/nteract/blob/5020b96454d29154f4540a37b6b5b9b93da07870/src/notebook/reducers/document.js#L148).

However, I'd probably combine stdout and stderr to be more like a terminal.

```js
function reduceOutputs(outputs, output) {
  const lastOutputIndex = outputs.length - 1
  if (outputs[lastOutputIndex].output_type === 'stream' && output.output_type === 'stream') {
    outputs[lastOutputIndex].text = outputs[lastOutputIndex].text + output.text;
    return outputs
  }
  outputs.push(output);
  return outputs;
}
```
