### ISSUE TITLE
Octave Kernel Hanging

### ISSUE THREAD

**Issue by init-random** [nteract/hydrogen#468]
In installed octave_kernel for jupyter and I installed language-matlab 0.2.1 in Atom so their would be an Octave grammar. 

Atom details:

```
> atom -version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

In jupyter I can connect and execute with the octave kernel. In Atom when I try to execute it just hangs and nothing happens. I do not see anything in the console as well (see below).

I start Atom on the command line with

```
> OCTAVE_EXECUTABLE=~/bin/octave atom
```

Is there a suggested way to connect to this kernel?

![screenshot from 2016-10-06 16 05 41](https://cloud.githubusercontent.com/assets/5600134/19168608/d8386f14-8bde-11e6-8e5b-7b09067dfa07.png)

Changed kernelspec in editor to

```
{
  "kernelspecs": {
    "Octave": {
      "spec": {
        "display_name": "Octave",
        "language": "octave",
        "argv": ["/home/slo/anaconda/envs/p3/bin/python", "-m", "octave_kernel", "-f", "{connection_file}"], 
          "mimetype": "text/x-octave", 
        "name": "octave",
        "env": {}
      }
    }
  }
}
```

but this did not help. Running the argv on the command line, the kernel starts. I also see that the kernel starts in the editor console.

**Comment by n-riesco** [comment]
Could you scroll up the log messages in the dev console to show the messages after `KernelManager: startKernelFor`?

**Comment by init-random** [comment]
Thank you for your reply. I apologize for the delay. Here is the message.

![screenshot from 2016-10-11 21 19 22](https://cloud.githubusercontent.com/assets/5600134/19294205/831b2012-8ff8-11e6-83c3-9b101f0aa5eb.png)
