### ISSUE TITLE
overlap problem

### ISSUE THREAD

**Issue by X-G** [nteract/hydrogen#48]
Sorry about my poor English. I'm trying to report this by screenshot.
It happens when the codes are long enough and you scroll down.
![qq 20150529195641](https://cloud.githubusercontent.com/assets/6829403/7889027/0dd2f050-063d-11e5-9d93-9c9e7f649d21.png)

**Comment by willwhitney** [comment]
This is a problem with the Atom API for markers. I've opened an issue at https://github.com/atom/atom/issues/6857 — I need them to fix it before I can address this, unfortunately.

**Comment by willwhitney** [comment]
Or rather, I could fix it for us, but at risk of breaking other packages (as I mention on that thread). I think it's unlikely that any packages depend on the exact `z-index` of the tab bar, so if they don't get a fix done soon I'll just do that.

**Comment by willwhitney** [comment]
Went ahead and did this. Shipped in `v0.4.0`!

**Comment by X-G** [comment]
Thanks Will.

**Comment by n-riesco** [comment]
This issue is still present in v0.7.1

**Comment by n-riesco** [comment]
[This comment](https://github.com/atom/atom/issues/6857#issuecomment-128684193) shows the issue clearly.

**Comment by rgbkrk** [comment]
Block decorations should be the way forward. http://blog.atom.io/2016/02/03/introducing-block-decorations.html

**Comment by n-riesco** [comment]
@rgbkrk I've tried the following in 1.7.0-dev-7040035 and it doesn't seem to work:

```
$ git diff
diff --git a/lib/main.coffee b/lib/main.coffee
index 7afdb18..10b2ef0 100644
--- a/lib/main.coffee
+++ b/lib/main.coffee
@@ -159,9 +159,9 @@ module.exports = Hydrogen =
         view.statusContainer.setAttribute('style', "height: #{lineHeight}px")
 
         @editor.decorateMarker marker,
-            type: 'overlay'
+            type: 'block'
             item: element
-            position: 'tail'
+            position: 'after'
 
         @markerBubbleMap[marker.id] = view
         marker.onDidChange (event) =>
```

![untitled](https://cloud.githubusercontent.com/assets/6199391/13718225/f5342d68-e7df-11e5-8f21-df6ae019e4ed.png)

**Comment by lgeiger** [comment]
@n-riesco if you remove [this line](https://github.com/nteract/hydrogen/blob/master/styles/hydrogen.less#L29) the result should be displayed. But of course the styling will be totally messed up.

**Comment by n-riesco** [comment]
@lgeiger Here's how it looks like after removing `position: absolute`:


![untitled](https://cloud.githubusercontent.com/assets/6199391/13795144/5723b48e-eaf7-11e5-8577-7a5f033fa62b.png)
