### ISSUE TITLE
Comms support

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#480]
Has anyone here put thought into getting comms working for hydrogen?

Comms are a form of direct communication between the frontend and code inside the kernel, mostly used for widgets. 

I'm also using them for my xdbg project, and trying to integrate that with hydrogen. Previously I had to create a fork called [deuterium](https://github.com/nikitakit/deuterium), but lately I've managed to get a good chunk of the functionality ported to a plugin version (see [hydrogen-xdbg](https://github.com/nikitakit/hydrogen-xdbg)). The missing bits are getting comms support for ZMQKernel, and exposing it through the plugin API.

Writing such a patch that works for my use-case is easy, but I'd like to check how it aligns with other people's vision of this project. In particular, comms are important if there are ever plans to support widgets in Hydrogen. (Maybe some of you have widgets experience from nteract notebook or other projects). Are there any particular desiderata/restrictions on comm support for hydrogen?

/cc @lgeiger @rgbkrk

**Comment by rgbkrk** [comment]
Ohhhhhh yes I could talk about comms at length. I'll point out some stuff happening in the nteract notebook when I get back to my laptop.
