### ISSUE TITLE
I can't update to 0.15.0

### ISSUE THREAD

**Issue by HaoranXue** [nteract/hydrogen#481]
hi, When I update atom to the latest version, here is the error message : 

''' 
zmq@2.15.3 install /private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/apm-install-dir-116918-2833-uf0qgz/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

/private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/apm-install-dir-116918-2833-uf0qgz
└── (empty)

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/apm-install-dir-116918-2833-uf0qgz/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/apm-install-dir-116918-2833-uf0qgz/package.json'
npm WARN apm-install-dir-116918-2833-uf0qgz No description
npm WARN apm-install-dir-116918-2833-uf0qgz No repository field.
npm WARN apm-install-dir-116918-2833-uf0qgz No README data
npm WARN apm-install-dir-116918-2833-uf0qgz No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/xuehaoran/.atom/.apm/.apmrc" "--userconfig" "/Users/xuehaoran/.atom/.apmrc" "install" "/private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/d-116918-2833-1admmwz/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/dh/xn75dlcj4q12827_rcn2kkph0000gn/T/apm-install-dir-116918-2833-uf0qgz/npm-debug.log
npm ERR! code 1
''''' 

Do u know how to figure it out ?

**Comment by HaoranXue** [comment]
Sorry, I mean when i try to update hydrogen to 0.15.0

**Comment by lgeiger** [comment]
It looks like node can't find your Xcode installation. Could you try running `xcode-select --install` before the upgrade?

**Comment by HaoranXue** [comment]
Thank you it works ! I think it is because of the update of new mac system cause this problem . 
Thanks again! 
Hydrogen is the Best package in ATOM for python.

**Comment by lgeiger** [comment]
Great! Thanks a lot for your feedback 👍
