### ISSUE TITLE
Do I need to install jupyter notebook locally if I only need to run python remote server?

### ISSUE THREAD

**Issue by xinzhou1023** [nteract/hydrogen#497]
I got hydrogen installed and set up a gateway to my remote notebook server. I can connect to the gateway but it keeps telling me no kernel found. I guess it's due to that I don't install jupyternote book locally. My question is that if I only need to run python remotely, what Kernel Specs should I put in the Hydrogen setting?
 
Below is my current setting.
![image](https://cloud.githubusercontent.com/assets/8029913/20229095/a16e5876-a822-11e6-871a-4dfa5ac284a7.png)

**Comment by lgeiger** [comment]
Hi @xinzhou1023,

you don't need to mess with the kernel specs settings if you run a remote kernel.

Are you sure the URL to your remote kernel is correct? You can check it by opening it in your web browser. I remember it usually is `http` instead of `https`.

**Comment by xinzhou1023** [comment]
Hi @lgeiger ,

Thanks for such a quick response. Yeah, you are correct. It should be http instead. I have two version jupyter notebook on my remote server. One is anaconda version which is working now. The other version require a login. Do you know how does Hydrogen handle that type of remote notebook? I already tired the normal gateway setup and it didn't work.

Thanks again!

**Comment by nikitakit** [comment]
@xinzhou1023 There is currently no good way to connect to notebook servers that require a login. The notebook authentication system was designed to run inside the browser, and doesn't play well with atom.

The recommended solution for setting up secured servers is to use SSH tunneling, or to set up HTTP basic auth via a proxy. See more at #473, which is the current tracking issue for this.

You can also try installing the [hydrogen-auth](https://github.com/nikitakit/hydrogen-auth) plugin I just pushed to github (you'll need to clone and install it manually). The code is a gigantic kludge so it'll be hit-or-miss on whether it works, but perhaps it may serve your needs.

**Comment by xinzhou1023** [comment]
Thanks, @lgeiger. I would like to try the hydrogen-auth plugin. Could you please tell me how to install it? I don't have any experience on javescript.

**Comment by xinzhou1023** [comment]
Thanks, @nikitakit. I got the hydrogen-auth installed. However, I got a error message below when I run it. My Hydrogen version is the latest I think, 0.15.0. How should I fix it?
![image](https://cloud.githubusercontent.com/assets/8029913/20250916/219bf89e-a9e2-11e6-8e1f-f191f638ec2b.png)

**Comment by nikitakit** [comment]
Could an admin close this issue? (original question has been resolved, and #473 is for the current tracking issue for secure connections)
