### ISSUE TITLE
Hydrogen successfully installed but wont execute

### ISSUE THREAD

**Issue by ksun91** [nteract/hydrogen#499]
I successfully installed hydrogen, but it doesn't seem to run. I try running it by clicking command shift p to run my line of code.

<img width="897" alt="hydrogenissue1" src="https://cloud.githubusercontent.com/assets/10409013/20238465/657449c8-a8ba-11e6-8078-6693713b2ec5.png">

hydrogen shows up and when I click run, nothing happens (I don't get a checkmark or anything). I then try to rerun the command again by searching for hydrogen, and then hydrogen doesn't even show up.

<img width="716" alt="hydrogenissue2" src="https://cloud.githubusercontent.com/assets/10409013/20238478/b03e3932-a8ba-11e6-8819-166c52a1f3d1.png">

**Comment by lgeiger** [comment]
@ksun91 Great that it worked!

We will release version 1.0 soon which simplifies the installation process a lot.

**Comment by rjbergerud** [comment]
I'm having the same issue.  What was your solution @ksun91 ?

**Comment by ksun91** [comment]
I believe I just restarted my computer and it worked. Was working off of a 2015 MacBook Pro at that time.

**Comment by wadethestealth** [comment]
@rjbergerud You may have a bad installation of hydrogen because if the commands disappear like this that means hydrogen has silently failed, which I doubt could happen in a current version since we have corner cased hydrogen to output errors when they occur.
