### ISSUE TITLE
Python Kernel/Import Issue

### ISSUE THREAD

**Issue by ksun91** [nteract/hydrogen#500]
I want to mention beforehand that this probably isn't a specific issue for Hydrogen itself, but I am pretty new to the development field and I would really appreciate any help.

I am trying to import a python class at the beginning and I get an ImportError. The error is a "no module named <name>" error. However, I am not trying to import a module, but instead I am trying to import a class that I made. From my research, it seems that I need to start the python from my directory of interest, namely api/dir. But I don't know how to do this. I tried using hydrogen's restart kernel function but I still get the same error.

![pythonkernel](https://cloud.githubusercontent.com/assets/10409013/20239438/deb9ee88-a8cd-11e6-8c87-30be35347b9c.png)

**Comment by nikitakit** [comment]
You can use the `%cd` and `%pwd` magic commands to change directories / figure out where you are. See https://ipython.org/ipython-doc/3/interactive/magics.html

I believe that kernels are started in the directory of the first file you run lines from. (Except for remote kernels, where I think they get started elsewhere). So you can either start the kernel from a different file, or cd into the right directory after starting. Hydrogen shares the same kernel between all open files that have the same language.
