### ISSUE TITLE
how to configure Python3+atom+hydrogen in virtual env?

### ISSUE THREAD

**Issue by lidymonteirowm** [nteract/hydrogen#501]
run script with input

**Comment by rgbkrk** [comment]
Last time I used this I had to run `atom .` from the command line to get it to pick up my virtualenv.

Nowadays I create a kernel spec for the virtualenv (or conda environment) like this:

```
workon someenv
ipython kernelspec install-self --user --name someenv
```

**Comment by BenRussert** [comment]
@lidymonteirowm The above answer looks like it should resolve the issue. Feel free to reply if you are still having trouble!
