### ISSUE TITLE
Hydrogen 1.0.0 installation fails on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by asmotrich** [nteract/hydrogen#506]
The new Hydrogen 1.0.0 both upgrade and clean install fail when run from inside Atom or on a command line with identical errors (see full installation trace below). The issue seems to be that the temporary location /tmp/apm-install-dir-.... created for zeromq build is removed by the apm before it has a chance to use it.

Thank you,
-Azary

[hydrogen-install.log.zip](https://github.com/nteract/hydrogen/files/596086/hydrogen-install.log.zip)

**Comment by lgeiger** [comment]
Since 1.0 we bundle zeromq which should make installation easier.

This is really strange. It seems like to be a problem with apm. I don't know why they are using temporary directories during the install.

**Comment by asmotrich** [comment]
Please let me know if I can help debug the issue. Unfortunately I'm rather new to JavaScript, Node and Atom. I have a newer instance of Node installed on the system, it did not interfere with Atom installation/upgrade before. Judging by description the #506 and #507 are the same.

Thank you,
-Azary

**Comment by lgeiger** [comment]
@asmotrich Your Node installation shouldn't interfere with Atom since it uses its bundled version.

It would be great if you post a issue on the [atom/atom](https://github.com/atom/atom) repo.

**Comment by lgeiger** [comment]
I'm going to close this and move the discussion to https://github.com/nteract/hydrogen/issues/507#issuecomment-261615483
