### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by pmlandwehr** [nteract/hydrogen#511]
The [Atom package repository](https://atom.io/packages/hydrogen) can't find the license for the package - can we get one added?

**Comment by lgeiger** [comment]
Thanks for noticing. We use the [MIT license](https://github.com/nteract/hydrogen/blob/master/LICENSE.md) which is correctly detected in our [github repository](https://github.com/nteract/hydrogen/).

Unfortunately we can't really do anything about the Atom package repository. It looks like we run into https://github.com/atom/atom.io/issues/68.
