### ISSUE TITLE
Limit results box width

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#512]
Right now, it doesn't appear that the result bubble size is suitably limited in the horizontal dimension. The limit is determined by the longest line of the file (assuming soft linewrap is disabled), not by the width of the containing window.

If the lines printed to stdout are long, the box expands to the point where the controls (close/copy/open in new tab) are no longer visible. This problem is especially noticeable if using multiple panes.

I would propose to limit the result box width to be smaller than the current pane width. Some extra padding on the right would be useful to not interrupt scrolling. This is because results boxes can interfere with scrolling through the file: partway through scrolling the mouse runs over a result box and starts scrolling the stdout contents instead. Having margins around the results box helps prevent this. (It's technically possible to avoid this by either using the minimap to scroll, or scrolling by placing the mouse over the line number indicators. But at least for me my muscle memory doesn't have me do that.)

In addition to providing a margin specified in terms of pixels, another option is to use the "preferred line length" setting for the current file and cut of the results box at that many characters.

Screenshot of the problem:
<img width="1440" alt="screen shot 2016-11-20 at 8 46 36 pm" src="https://cloud.githubusercontent.com/assets/252225/20471001/84c9371c-af62-11e6-921c-dcaf5ae065e0.png">

**Comment by lgeiger** [comment]
Yes, the multiline output bubbles doesn't handle big output very well. We should definitely change that.

We are using Atom's block decorations instead of overlays for displaying output bubbles for a while now. Recently I thought about completely redesigning the multiline/rich output bubbles to something more robust.

At the moment we have inline, multiline and rich output bubbles which are great for small outputs but doesn't handle anything beyond that very well.
What do you think of merging multiline and rich bubbles to a fullscreen one similar to a cell output in nteract?
![d95ad398-783b-11e6-8b23-d54cf7caad1e](https://cloud.githubusercontent.com/assets/13285808/20479277/ed379f5c-afdd-11e6-8b76-7ca44cbc4f01.png)

**Comment by nikitakit** [comment]
@lgeiger No issue with merging the two bubble types. In fact, I wouldn't even know that there are different bubble types if I didn't look at the source code.

I think having a standard box type that takes up most of the pane width would be great for multiline display. I'm still in favor of keeping the inline display for super short outputs, though.

**Comment by lgeiger** [comment]
> I'm still in favor of keeping the inline display for super short outputs, though.

Absolutely! 👍

**Comment by nikitakit** [comment]
@lgeiger Thanks for addressing this! I just had a chance to test, and the result boxes are much better now!

The one thing I noticed is that the width of the box doesn't change if you resize the current pane. I probably wouldn't have come across this without intentionally testing it, but it might still be worth looking at whether there's an easy fix.

**Comment by lgeiger** [comment]
Glad you like it!

Yes I noticed that too. The problem is we cannot rely purely on CSS since `max-width: 100%` would equal to the line length. So `max-width` is simply set [here](https://github.com/nteract/hydrogen/blob/master/lib/main.js#L311) once.

**Comment by nikitakit** [comment]
@lgeiger You're right. I tried looking for a pane-resize event that you can listen to from javascript, but I couldn't find one. Looks like this will probably have to remain as-is.

**Comment by lgeiger** [comment]
I think there is a event for that, let me see.

**Comment by lgeiger** [comment]
Oh yeah, here it is: https://atom.io/docs/api/v1.12.7/Pane#instance-onDidChangeFlexScale
