### ISSUE TITLE
connection.json flexibility

### ISSUE THREAD

**Issue by MaximilianR** [nteract/hydrogen#522]
Firstly, many thanks for the awesome package.

I'm using a docker-compose setup and so am depending on the `connection.json` file. A couple of questions:
- In a project with more than one root folder, is the path hydrogen looks for relative to the first root folder?
- Can the location of the file be flexible? Indeed it would be good to have this be a setting like the other hydrogen settings - maybe there's a good reason this is done differently?
- Is there a way of telling when the `connection.json` file is actually being used? While debugging it's not immediately clear whether it's being found or not
- Are there any other ways of simplifying this? While the functionality is very impressive, it's a decent amount of complication for "run this in a container", from an uninformed pov.

Thanks,
Max

**Comment by lgeiger** [comment]
@MaximilianR Since we now have the possibility to connect to a docker container via [kernel gateways](https://github.com/nteract/hydrogen#docker-execution-via-kernel-gateways) is this still a issue?

**Comment by n-riesco** [comment]
>   * In a project with more than one root folder, is the path hydrogen looks for relative to the first root folder?

It will whatever is the root folder when the kernel is started (hence, you need to make sure the first execution happens in a file located in the same folder where `./hydrogen/connection.json` is located).
 

>   * Can the location of the file be flexible? Indeed it would be good to have this be a setting like the other hydrogen settings - maybe there's a good reason this is done differently?

I'm not sure how the other maintainers feel about the idea, but I think this functionality should be replaced by a command that prompts the user for the location `connection.json`.


>   * Is there a way of telling when the |connection.json| file is actually being used? While debugging it's not immediately clear whether it's being found or not

There used to be a notification showing when a connection file was used. Please, open an issue if this is not the case.


>   * Are there any other ways of simplifying this? While the functionality is very impressive, it's a decent amount of complication for "run this in a container", from an uninformed pov.

If your use-case is just running a kernel inside a container, I would use a custom kernel spec. This custom kernel spec would invoke a script that would launch the kernel inside a container.

**Comment by lgeiger** [comment]
@n-riesco Thanks for the great explaination!

>I'm not sure how the other maintainers feel about the idea, but I think this functionality should be replaced by a command that prompts the user for the location `connection.json`.

Since we have support for remote kernel connection for a while now, I personally would be in favor of completely deprecating the `connection.json` feature unless there is a specific use case which remote kernels don't support. Less code is always easier to maintain 😄 

Though we would need to notify users in advance that we're considering deprecating this feature and invite them to join our discussion if they have a use case not supported by remote kernels.

What do you think?

**Comment by lgeiger** [comment]
> But I would keep it until it breaks. There is no need to cause unnecessary pain to any users.

👍 

> The kernel gateway is not a replacement for this functionality. I don't think it can connect to an existing connection (and also, my usual piece of criticism: jupyter isn't distributed in the Ubuntu 16.04 repositories).

You can connect to a kernel started by `jupyter kernelgateway` or `jupyter notebook`. I guess this should work with `ipython notebook` as well.

**Comment by n-riesco** [comment]
> You can connect to a kernel started by |jupyter kernelgateway| or |jupyter notebook|. I guess this should work with |ipython notebook| as well.

No, this isn't the case. I've tested it in Jupyter v4.3.0 and |jupyter notebook| only sees its own running kernels (i.e. it doesn't see kernels instantiated by a different instance of |jupyter notebook|).

**Comment by lgeiger** [comment]
@n-riesco Have you tried the workflow described [here](https://github.com/nteract/hydrogen#example-with-notebook-server)

I think without the token it should work for old ipython versions too.

**Comment by n-riesco** [comment]
> Have you tried the workflow described here <https://github.com/nteract/hydrogen#example-with-notebook-server>

Yes, I did. Please, try yourself:

1) open a terminal and run `jupyter console`
2) open another terminal and run `jupyter notebook --port=8888`
3) the notebook server is unaware of the kernel connection initiated at 1)


> I think without the token it should work for old ipython versions too.

I've tested this on Jupyter v4.3.0.

**Comment by lgeiger** [comment]
Hydrogen can now connect to the server started in 2) via "Hydrogen: Connect to Remote Kernel".

To connect the jupyter console you would need to first start the notebook and run `%connect_info` inside it (or hydrogen, then start the console via `jupyter console --existing <here the file from %connect_info>`.

**Comment by n-riesco** [comment]
The point I'm trying to make is that Hydrogen cannot access an existing connection through a notebook server, because the notebook server only sees the sessions started by the server.

**Comment by lgeiger** [comment]
> The point I'm trying to make is that Hydrogen cannot access an existing connection through a notebook server, because the notebook server only sees the sessions started by the server.

That's true 👍 

One thing I like to add for future readers:
If you are only concerned about connecting a ipython console to a kernel in a easy way, you can start the kernel with Hydrogen and use [Hydrogen Launcher](https://github.com/lgeiger/hydrogen-launcher) to open a console automatically connected to your current kernel.
