### ISSUE TITLE
Include current project path in kernel's path?

### ISSUE THREAD

**Issue by MaximilianR** [nteract/hydrogen#523]
If I'm working on a project, ideally I would want `import myproject` to reference the project's files (rather than any installed version of `myproject`).

If I start `ipython` from my project directory, this works. I believe that's because `ipython` maps my current path and so resolves the package locally.

But this doesn't seem to with `ipykernel`. Is this something people have encountered? 

Alternatively let me know if this is an issue with ipykernel rather than hydrogen.

Thanks!

**Comment by lgeiger** [comment]
Hydrogen starts the Kernel in the directory of the current file. So as long as you start the kernel in the root directory of your project this should work.

You can check in which directory the kernel was started by executing `!pwd` in Hydrogen or IPython.

**Comment by buyology** [comment]
> start the kernel in the root directory of your project

how would you do this?

 `Script`s `cmd`-`i` runs in the project root while `Hydrogen` runs in the directory of the actual file

**Comment by buyology** [comment]
@slavaGanzin sounds good, guess I'll have to patch it myself in the meantime

**Comment by buyology** [comment]
actually @slavaGanzin wouldn't it be relevant to submit the [`project path`](https://github.com/nteract/hydrogen/blob/a19dfd54b566ac02290c8aefd1dd3c169bfec67b/lib/kernel-manager.js#L128-L129)-patch in a separate PR?

I cannot see why this shouldn't be the default behaviour especially with lots of ppl coming from `Script` and using this with the `python` kernel

**Comment by lgeiger** [comment]
> start the kernel in the root directory of your project
@lgeiger how would you do this?

You can do this by starting the kernel in any python file that is in the root directory of your project.

@buyology Please feel free to submit a PR changing this behavior. That would be cool 🎉 

I personally like to start the kernel in the current file but I see that this becomes tedious when working in a bigger project. It's probably best to change that.
