### ISSUE TITLE
Add "Remote Server" to Packages->Hydrogen menu

### ISSUE THREAD

**Issue by hz** [nteract/hydrogen#529]
Thanks a lot for hydrogen project. 

In Hydrogen/menus/hydrogen.cson, I added:
`
       {
          'label': 'Remote server'
          'command': 'hydrogen:connect-to-remote-kernel'
        }
`
It is very convenient for me.  Would you like one pull request for it?

**Comment by lgeiger** [comment]
Sure! I'm happy to add more menu items. I'm looking forward to your PR 🎉 😄 

Though I would keep the label `Connect to Remote Kernel` for consistency.
