### ISSUE TITLE
Font size R plot too small

### ISSUE THREAD

**Issue by essicolo** [nteract/hydrogen#532]
Atom 1.12.5 on Linux. Screen resolution 1920 X 1080. The font sizes in R are very small (figure), even with very large values (figure 2). Is it possible to increase it?

![figure 1](https://cloud.githubusercontent.com/assets/5118227/21019004/11e3c242-bd3d-11e6-9eb2-a5375ad6bd39.png)
![figure 2](https://cloud.githubusercontent.com/assets/5118227/21019003/11decbca-bd3d-11e6-9ae4-ab95a2cec479.png)

**Comment by lgeiger** [comment]
Hydrogen rescales the image to fit the screen. It looks like your figure size is very large and therefor the font size relative to the figure size appears very small.

Unfortunately I don't know R, so I have no idea how to change the figure size.

**Comment by essicolo** [comment]
Thanks. After further testing it seems that the problem happens only when I use a specific function before plotting. This function might alter the default R graphic settings. Closing!
