### ISSUE TITLE
Make keyboard shortcuts configurable

### ISSUE THREAD

**Issue by plumps** [nteract/hydrogen#534]
In my current scenario, I often hit ```cmd+Enter``` on my mac to create a new line under my current cursor, which conflicts with default strategy to run the current cell in a Hydrogen enabled Python file. 

Thus I have to remove the preset keyboard shortcuts in the source, which is quite inconvenient to repeat after every update.

**Comment by lgeiger** [comment]
Try adding
```
'atom-text-editor, atom-text-editor:not([mini])':
  'cmd-enter': 'editor:newline-below'
```
to your `keymap.cson` (Atom->Keymap...) file.

This should overwrite Hydrogens default.

**Comment by nikitakit** [comment]
FYI for atom 1.10 you need to use `.platform-darwin atom-text-editor:not([mini])` as the selector instead. (However, I believe that this is fixed as of atom 1.12)

**Comment by plumps** [comment]
Fortunately 1.12 is already stable

**Comment by lgeiger** [comment]
Great! 🎉
