### ISSUE TITLE
Plot images do not show

### ISSUE THREAD

**Issue by gsportelli** [nteract/hydrogen#539]
I'm using a fresh install of atom with hydrogen on OS X 10.11 with IPython installed on a virtual environment. I'm doing this on an Macbook Air and on a iMac with two identical copies of the python virtual environment and the atom configuration directory.

I then open a new file, select Python language, and run "plot(arange(100))".

With the Macbook Air it shows the plot, with the iMac it prints the following message:

> <IPython.core.display.Javascript object>
> [<matplotlib.lines.Line2D at 0x1094e1cd0>]

I've tried to look at the console messages, but I couldn't fint anything meaningful to me.

Any help?

**Comment by lgeiger** [comment]
It guess that's a inconsistency in IPython (or the config).

Try one of the following examples:
```python
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(range(100))
```
```python
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()
```

**Comment by gsportelli** [comment]
Ahhh... that was it!

Both the examples work. Now I remember, I was messing with the IPython config folder a few months ago. Will have to fix it again.

Thanks!

**Comment by lgeiger** [comment]
Great! 🎉 

You can also add `%matplotlib inline` to the "startup code" setting in Hydrogen if you don't want to mess with the global IPython config.

**Comment by AtomicNess123** [comment]
How do you set up %matplotlib inline to the startup code?

**Comment by aminya** [comment]
> How do you set up %matplotlib inline to the startup code?

Have you seen the examples?
