### ISSUE TITLE
Syntax Error: EOF while scanning triple-quoted string literal

### ISSUE THREAD

**Issue by sparseinference** [nteract/hydrogen#541]
Before version 1.3.0, in Python source, this was parsed as a multi-line comment and skipped over:
```
"""
Hello
"""
```

Now an error is reported on every new line in the comment.
It looks like it doesn't treat the entire triple-quoted string as a block.

**Comment by MichaelStetner** [comment]
I've been having this problem too, and it affects other multi-line statements. In all of the following examples, I have the cursor at the beginning of the first line and push `Ctrl+Enter`. 

For example, the following causes an error:

```
print(
    "hello"
)
```

Error message:

```
File "<ipython-input-8-5d8744617373>", line 2
    "hello"
           ^
SyntaxError: unexpected EOF while parsing
```

It works if I indent the closing parenthesis, like this:
```
print(
    "hello"
 )
```

Same for triple quoted blocks. This triple quoted block evaluates just fine:
```
"""
 hello
 """
```

It seems like Hydrogen is detecting multi-line statements based on indentation only, not parentheses or triple quotes.

**Comment by lgeiger** [comment]
From #77
> Hydrogen relies on Atom's code-folding and indentation right now to figure out what a block is. This is so that the code for finding blocks works across languages.
This is definitely annoying behavior, but I don't know of a way to address this without writing a parser for each language that Hydrogen supports.

For now this needs to be fixed in Atom's [`language-python`](https://github.com/atom/language-python) package.

**Comment by mohitv789** [comment]
I am getting this error while running following code: :(


# Hierarchical Clustering Code

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Mall_Customers.csv')
X = dataset.iloc[:, [3, 4]].values
y = dataset.iloc[:, 3].values

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)"""

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

# Using the dendrogram to find the optimal number of clusters
import scipy.cluster.hierarchy as sch
dendrogram = sch.dendrogram(sch.linkage(X, method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean distances')
plt.show()

# Fitting Hierarchical Clustering to the dataset
from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters = 5, affinity = 'euclidean', linkage = 'ward')
y_hc = hc.fit_predict(X)

# Visualising the clusters
plt.scatter(X[y_hc == 0, 0], X[y_hc == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(X[y_hc == 1, 0], X[y_hc == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(X[y_hc == 2, 0], X[y_hc == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(X[y_hc == 3, 0], X[y_hc == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(X[y_hc == 4, 0], X[y_hc == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.savefig("plot_hc.png")

**Comment by kylebarron** [comment]
@mohitv789 	You have a random `"""` at the end of one of your lines
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)"""

**Comment by mohitv789** [comment]
@kylebarron Thanks!

**Comment by JiajunBao** [comment]
I meet problem with this piece of code.
<img width="681" alt="Screen Shot 2019-03-12 at 2 02 15 PM" src="https://user-images.githubusercontent.com/24786001/54224255-8615b780-44cf-11e9-909d-74d5f76c68e7.png">
But it works for this one:
![image](https://user-images.githubusercontent.com/24786001/54224313-a6de0d00-44cf-11e9-9042-176e59952739.png)

**Comment by affonsoviccari** [comment]
i am getting this error with this code: 

pilha=[]
j=len(pilha)
op=input("Digite um jogo de parenteses:")
print(op)
# ((())(
i=0
while i<len(op):
    if op[i]== "(":
        j+=1
        pilha.append(j)
        print(pilha)
    elif op[i]==")":
        if len(pilha)>0:
            pilha.pop(-1)
            print(pilha)
        else:
            print("Pilha vazia")
    else:
        print("Comando inválido")
    i+=1
if len(pilha)!=0:
    print("Erro")
else:
   print("OK")
