### ISSUE TITLE
Error importing Python packages

### ISSUE THREAD

**Issue by joseclcodes** [nteract/hydrogen#543]
>import scipy as sp
>>---------------------------------------------------------------------------
>>ImportError                               Traceback (most recent call last)
>><ipython-input-4-7e642d76ec1e> in <module>()
>>----> 1 import scipy as sp
>>
>>ImportError: No module named 'scipy'

Keep on getting this error message for any package I try to import such as numpy, matplotlib, etc.

**Comment by lgeiger** [comment]
Does `import scipy as sp` work in the IPython console?
You can start the IPython console by running `ipython` in your terminal.

**Comment by joseclcodes** [comment]
No, it's not working there either

**Comment by joseclcodes** [comment]
Igeiger thanks
I already solved the issue, your comment was of much help.

**Comment by lgeiger** [comment]
@joseclcodes Great to hear you got it working! 🎉
