### ISSUE TITLE
Don't override ctrl-backspace

### ISSUE THREAD

**Issue by vuki** [nteract/hydrogen#555]
Please don't override the `ctrl-backspace` shortcut.

It is a standard shortcut for "delete a word before the cursor". Overriding it confuses those who use it.

**Comment by lgeiger** [comment]
Would be `ctrl-alt-backspace` available?

Are you using Linux or Windows?

**Comment by vuki** [comment]
I'm on Windows, but I think that Linux uses the same shortcut.

    'atom-workspace atom-text-editor':
      'ctrl-backspace': 'editor:delete-to-beginning-of-word'

`ctrl-alt-backspace` seems to be already taken by the core module.

    '.platform-win32 atom-text-editor':
      'ctrl-alt-backspace': 'bracket-matcher:remove-matching-brackets'

**Comment by lgeiger** [comment]
Thanks for your feedback! I'm using macOS so I can't easily test Windows keybindings.

> `ctrl-alt-backspace` seems to be already taken by the core module.

Hmm, would `ctrl-shift-backspace` work for you?

In the meantime you can change the keybindings by editing `keymap.cson` (Atom->Keymap...).

**Comment by vuki** [comment]
Thanks for response. ` ctrl-shift-backspace`  seems to be available.

I know about keybindings, I did this, but it's cumbersome to do this on every machine I use Atom on.

**Comment by lgeiger** [comment]
That's great.
@vuki Would you like to send a PR to fix it?

**Comment by lgeiger** [comment]
I went ahead and already made a PR: #559 
@vuki Thanks a lot for your help!
