### ISSUE TITLE
Plotly and cufflinks code

### ISSUE THREAD

**Issue by erdemalpkaya** [nteract/hydrogen#557]
Hey,

Does anyone know plotly  ' .iplot' code is not working in Atom/Hydrogen or I missed something?
Below my code is working different platform but not in the Atom!

<img width="778" alt="ex_atom" src="https://cloud.githubusercontent.com/assets/24259112/21386898/fa84d38c-c7d9-11e6-965c-8a0ad53ddfb8.png">
<img width="580" alt="ex_web" src="https://cloud.githubusercontent.com/assets/24259112/21386899/fad062ac-c7d9-11e6-8eb8-97f0150e12aa.png">

**Comment by n-riesco** [comment]
@rgbkrk If I remember correctly, `nteract` handles this through `application/vnd.plotly.v1+json`. Is that how the notebook does it? Is there anything we could reuse in  Hydrogen?

**Comment by n-riesco** [comment]
Re #368

**Comment by rgbkrk** [comment]
We need to put pressure on the packages to use UMD bundles in their `text/html` payloads. It's failing in Hydrogen there because it's expecting `require` to be from requirejs when the `require` in Hydrogen/Atom is the node commonjs require.

**Comment by rgbkrk** [comment]
It's either that or Hydrogen has to provide a requirejs shim within the scope of the output somehow.

**Comment by hz** [comment]
Besides Plotly, could Bokeh be introduced with hydrogen remote gateway support?

**Comment by rgbkrk** [comment]
I've been using Bokeh in nteract, I don't see why it wouldn't work in Hydrogen unless there are still content security policies dictated by Atom that we need to play well with.

**Comment by erdemalpkaya** [comment]
Sorry, I wrote again but I would like work atom and still the same issue just I want to know how can we fix the problem?

**Comment by bu2** [comment]
@rgbkrk Hi, I confirm that Bokeh does not work in Atom/Hydrogen because of CSP.

I test the following example:

```
import numpy as np
from six.moves import zip
from bokeh.plotting import figure, show, output_notebook

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = ["#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)]
TOOLS="hover,crosshair,pan,wheel_zoom,box_zoom,reset,tap,save,box_select,poly_select,lasso_select"


output_notebook()
p = figure(tools=TOOLS)
p.scatter(x,y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)
show(p)
```

It works well in the browser, but fail in Atom with following error: 

> result-view.js [sm]:180 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-ogkYwsWoO1rOzslISuHG1VOYtS/i17cD7hIASgVCFsY='), or a nonce ('nonce-...') is required to enable inline execution.

I will let you know if I can fix it...
