### ISSUE TITLE
Altair visualization library doesn't work

### ISSUE THREAD

**Issue by idmit** [nteract/hydrogen#560]
Hello!

I've been working with your package lately and it's really great. Unfortunately, it fails to display the output of the [Altair](https://altair-viz.github.io/) library. I try running this code from their homepage:

```python
from altair import Chart, load_dataset

# load built-in dataset as a pandas DataFrame
cars = load_dataset('cars')

Chart(cars).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```

## Notebook

![screen shot 2016-12-27 at 01 35 51](https://cloud.githubusercontent.com/assets/2546728/21487211/dc56da64-cbd4-11e6-8a38-c4a5013dcba8.png)

## Hydrogen

![screen shot 2016-12-27 at 01 34 21](https://cloud.githubusercontent.com/assets/2546728/21487188/a17190ba-cbd4-11e6-9b20-b26223ef3846.png)

## Notebook output contents

```html
<div class="output_subarea output_html rendered_html"><div class="vega-embed" id="c21b9d22-57b7-4cc8-9edf-bac5abf1c864">
  <div class="vega" style="position: relative;">
    <canvas width="624" height="405" class="marks">
    </canvas>
  </div>
  <div class="vega-actions">
    <a href="#" target="_blank" download="vega.png">Export as PNG</a>
    <a href="#">View Source</a>
    <a href="#">Open in Vega Editor</a>
  </div>
</div>

<style>
.vega-embed svg, .vega-embed canvas {
  border: 1px dotted gray;
}

.vega-embed .vega-actions a {
  margin-right: 6px;
}
</style>
</div>
```

## Hydrogen output contents

```html
<div class="bubble-output-container">
  <div class="bubble-result-container">
    <div class="vega-embed" id="c8ff3624-14a1-4ad8-b422-bbaa30bdba13">
    </div>

    <style>
      .vega-embed svg, .vega-embed canvas {
        border: 1px dotted gray;
      }

      .vega-embed .vega-actions a {
        margin-right: 6px;
      }
    </style>
  </div>
  <div class="bubble-error-container plain-error">
  </div>
  <div class="bubble-status-container hidden" style="height: 21px">
    ...
  </div>
</div>
```

I am under the impression that the package that is used to embed Altair's graphics is https://github.com/vega/ipyvega, but I am not familiar with Altair's source enough to tell for sure.

So, does support for this library have to be added to Hydrogen by hand or is something broken here?

**Comment by rgbkrk** [comment]
What do the dev tools show with `View -> Developer -> Toggle Developer Tools`?

You'll want to check the console for error messages.

**Comment by idmit** [comment]
Oh, I forgot to include it, sorry. Nothing that looks like an error in there.

![screen shot 2016-12-27 at 04 34 45](https://cloud.githubusercontent.com/assets/2546728/21488212/e5bd665e-cbed-11e6-8ed1-8652acc68829.png)

**Comment by nikitakit** [comment]
Based on the Altair FAQ, it needs an nbextension in order to draw graphs. Link: https://altair-viz.github.io/faq.html#id2

Nbextensions are part of the notebook, not hydrogen, so it's not clear what can be done to fix this.

(On phone, sorry for brevity)

**Comment by rgbkrk** [comment]
The way we handle vega in nteract/nteract right now is a custom renderer/transform for mimetypes `application/vnd.vega+json` and `application/vnd.vegalite+json`. It currently requires the user to form a custom payload though:

```python
import IPython.display
def vegify(spec):
    IPython.display.display({
        'application/vnd.vegalite+json': spec.to_dict()
    }, raw=True)
```

```python
from altair import Chart, load_dataset

# load data as a pandas DataFrame
cars = load_dataset('cars')

spec = Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)

vegify(spec)
```

Resulting notebook:

![2016-12-26 1](https://cloud.githubusercontent.com/assets/836375/21488703/82527310-cba8-11e6-96ff-c9203896db9f.png)

**Comment by rgbkrk** [comment]
I'd like to support vega and plotly as standard transforms in all the jupyter environments so libraries don't have to dump JS and HTML payloads for these.

**Comment by idmit** [comment]
Wow, I didn't know about nteract/nteract until now – it looks super cool! 😃  I think that it makes sense to mention nteract somewhere in Hydrogen README, it can interest some of Hydrogen users.

So custom handling of these mimetypes is going to be added to Hydrogen eventually? Looking forward to it, thank you for your answer!

**Comment by rgbkrk** [comment]
> it makes sense to mention nteract somewhere in Hydrogen README, it can interest some of Hydrogen users

We would certainly welcome a pull request with that. 😄 

> So custom handling of these mimetypes is going to be added to Hydrogen eventually?

They wouldn't be too hard to add right now, it would probably be better to do it after nteract/nteract exports more modules so we don't have to maintain it in so many places.

**Comment by lgeiger** [comment]
Just some updates on this effort:

In #655 and #705 we added support for more transforms using the packages exported by nteract.

nteract also exports [`@nteract/transform-vega`](https://github.com/nteract/nteract/tree/master/packages/transform-vega) which is used by altair's output.

I wasn't able to get it working right out of the box, but I'm confident that it isn't too hard to implement with some tinkering. If anyone want's to pick up on this, any help is greatly appreciated 🎉

**Comment by lgeiger** [comment]
Will be fixed once Atom 1.20.0 is stable.

**Comment by lgeiger** [comment]
We will support Vega and Vega-Lite in the upcoming release:
![altair](https://user-images.githubusercontent.com/13285808/30343455-f85f5b00-97fd-11e7-9bd6-478280c50c0e.png)

**Comment by jakevdp** [comment]
Note for folks who come across this thread: For Altair version 2.0 or newer, the above ``vegify`` function is not required. nteract will display Altair plots by default once it updates its dependencies and supports Vega-Lite version 2.X; until then, it will not be possible to display Altair plots correctly in nteract.

If you want to use Altair in the meantime, please try another front-end, such as JupyterLab, Jupyter Notebook, or CoLab.

**Comment by rpalloni** [comment]
Thank you @jakevdp for adding the comment.
Here further info: https://github.com/altair-viz/altair/issues/710

 @lgeiger  should I open an issue?

**Comment by nikitakit** [comment]
We've had Vega 3 / Vega-lite support in github master for a little while, it just hasn't been published in a release yet. Everything should be compatible assuming that altair set up their display MIME types the same way as hydrogen and JupyterLab.

**Comment by rgbkrk** [comment]
@jakevdp is Altair only publishing the new spec now? Is it ok to deprecate the handling of the old spec at any point?

**Comment by jakevdp** [comment]
I think moving toward deprecating the old schema version (vega v2 and vega-lite v1) will be fine

Altair is now using the vegalite v2 mimetype, and I suspect that the vast majority of users will be using that soon.

That said, Altair does still have the ability to generate vegalite v1 mimetypes as well... JupyterLab and the classic notebook will still be able to handle those, though it will require explicitly enabling an extra extension in order to do so.

**Comment by rgbkrk** [comment]
@jakevdp - I just checked and vega v3 and vega-lite v2 are both supported in nteract desktop:

![screen shot 2018-04-09 at 1 06 28 pm](https://user-images.githubusercontent.com/836375/38520285-37426658-3bf7-11e8-9be4-c448cc0574fd.png)

Hydrogen needs to upgrade to the latest of the display area. nteract desktop is totally fine and has been since [nteract v0.6.0](https://github.com/nteract/nteract/releases/tag/v0.6.0), which was released at the end of January. We're now on v0.8.4 so any system that allows the auto-upgrades should be all set.

**Comment by jakevdp** [comment]
That's great to hear – thanks!

**Comment by rgbkrk** [comment]
As of today's release of Hydrogen, we [support Vega 3 and Vega-lite 2](https://twitter.com/nteractio/status/984257546985783297). Slick interactives!

**Comment by lgeiger** [comment]
Slick! Thanks for shipping
