### ISSUE TITLE
preview have a problem

### ISSUE THREAD

**Issue by wlccgp3** [nteract/hydrogen#564]
Thank you for this package,It's very nice.
But I found a petty problem
code:
```
for x in range(1, 11):
    print('{0:2d} {1:3d} {2:4d}'.format(x, x*x, x*x*x))
```
 the first line is doesn't work under the preview:
```
1   1    1
 2   4    8
 3   9   27
 4  16   64
 5  25  125
 6  36  216
 7  49  343
 8  64  512
 9  81  729
10 100 1000
```

**Comment by slavaGanzin** [comment]
It's not a problem at all. 
 Output of kernel is trimmed. And if in your case it breaks indentation, in many other cases it helps a lot. Hydrogen is just kernel runner, so it deals with all kernel differences. For example, some kernels(julia) add newline to any output and some only on special occasions, others don't do it at all. Which you should agree, will look more inconsistent.

**Comment by wlccgp3** [comment]
thanks a lot for your reply.
