### ISSUE TITLE
Autocomplete (not only the one Hydrogen provides) stops while the kernel is busy

### ISSUE THREAD

**Issue by ngr-t** [nteract/hydrogen#565]
Thank you for maintaining this cool package! I love to use this, but there is a thing I regret.
It is that autocomplete (not only the one Hydrogen provides) stops while Hydrogen is evaluating codes(at least in my environment, Windows 10 + Atom 1.12.7 + Hydrogen 1.5.0.) As below:
![hydrogen_completion](https://cloud.githubusercontent.com/assets/729653/21522969/63118986-cd4d-11e6-975f-f7a0289e6deb.gif)
I often run codes which take pretty evaluation time (several minutes or longer) and I want to work on other parts using autocomplete at the same time.
I know we can avoid this behavior by disabling the Hydrogen's autocomplete in advance, but I think it's convenient we can use it when its kernel is idle and use completions provided by some other packages even when the kernel is busy.

**Comment by lgeiger** [comment]
We definitely shouldn't block other completion providers. I'll submit a PR later today.

@rgbkrk If the kernel is busy we generally cannot receive any completions from the jupyter kernel, is that right?

**Comment by n-riesco** [comment]
@lgeiger In general you are correct, but there are exceptions, e.g. IJavascript allows execution requests to be asynchronous.

**Comment by lgeiger** [comment]
Closed by #567

**Comment by rgbkrk** [comment]
> If the kernel is busy we generally cannot receive any completions from the jupyter kernel, is that right?

To expand on what @n-riesco said, the Python kernel will not send completions when it is busy. Kernels can send completion information over ZMQ while the kernel is busy, regardless of if the frontend will handle it -- jupyter notebook avoids asking for completion when the kernel is busy.

**Comment by ngr-t** [comment]
Thank you for rapid fix!
