### ISSUE TITLE
Whole line, and the insertion cursor become invisible.

### ISSUE THREAD

**Issue by mda6** [nteract/hydrogen#575]
To reproduce select all the code and run hydrogen
than select the 'i' in the 2 line in the for loop  "for **i** in range(10):"

temp = 0
for i in range(10):
    temp += 1
    print i

This causes line 3 "temp +=1" to become invisible also the insertion cursor is gone in there
![forloophydrogen](https://cloud.githubusercontent.com/assets/24946938/21789435/535fc296-d6d5-11e6-900d-621092ada8fc.png)

If i restart the kernel it's ok
Or i can undo/redo to the point where i wrote the temp +=1 line

I am on Windows 10 if it matters.

**Comment by lgeiger** [comment]
This looks like a styling issue.
Which theme are you using and can you reproduce this with the standard theme?

**Comment by mda6** [comment]
@lgeiger you are right! I tried it with one dark everything is fine.. 
I am using the Atom Material theme.. can you try and reproduce it on your side?
Thank you!

**Comment by mda6** [comment]
Thanks man
