### ISSUE TITLE
How would i setup Hydrogen to work with another package that is sending the code in software, executes it and returns the result back to Atom?

### ISSUE THREAD

**Issue by mda6** [nteract/hydrogen#576]
I am pretty new to programming and i need some help.. it would be SUPER AWESOME for my workflow if i can set this up to work with Hydrogen!
I use https://atom.io/packages/Foundry-Nuke that sends the code to Nuke (software for compositing)

Normally Hydrogen can't initialize the variables by itself to work in a code written for Nuke.. (it actually needs the software to check what is selected in the comp, what nodes are there.. etc.. - that's where the atom-foundry-nuke package comes in)
Also how do i tell hydrogen to recognize "import nuke"?

Thanks!

**Comment by n-riesco** [comment]
> Also how do i tell hydrogen to recognize "import nuke"?

There is no different from any other python package. If `import nuke` works when you run it in the python console, then it should work when you run it using Hydrogen.

**Comment by mda6** [comment]
@n-riesco Thanks.. but what about everything else? Is it possible integrate Atom with Nuke so i can use Hydrogen on code writen for nuke directly inside Atom?

**Comment by n-riesco** [comment]
@mda6 I'm not familiar with Nuke. I've had a quick look at `Foundry-Nuke` and this package basically does:

```python
import nuke

result = nuke.executeInMainThreadWithResult(_exec, args=(data))
```

I guess that what you have in mind is something more involved, like having Nuke widgets embedded in the Hydrogen output.

Currently, Hydrogen doesn't support widgets (although it does provide a plugin API).

If what you're trying to achieve can be done in Python, then it'd be possible to do the same in Hydrogen and we could help you further.

**Comment by mda6** [comment]
@n-riesco If you mean by what can be done in Python..  take a look at this: https://github.com/Nvizible/NukeExternalControl (with my limited knowledge i am not sure i understand it completly, but i think this is it?) maybe we can go from there?
And thanks a ton for taking the time with me!

**Comment by mda6** [comment]
@n-riesco I got this thing working! But to a point am not sure where to go from here on..
What i did is added the code in Startup Code in Atom (i added the lines that starts the connection between python and nuke.

Now i can call nuke commands from Hydrogen inside Atom! i.e. "print nuke.selectedNodes()" I get result of selected nodes from Nuke (which is awesome!)


But i am not sure why some of my other variables are not printed by Hydrogen. i.e. 2 level for loop with if else statments working with default dictionary - and Hydrogen is giving me result as the dictionary is empty where it is not (if i run the code directly i get the correct result)

**Comment by BenRussert** [comment]
@mda6 Glad to hear you got your code working! If you post a code sample I'll see if I can spot an issue.

If you've moved on I'll probably close this issue as it is a specific use case that sounds mostly sorted out.
