### ISSUE TITLE
I am getting spammed with errors

### ISSUE THREAD

**Issue by mda6** [nteract/hydrogen#577]
![spammed](https://cloud.githubusercontent.com/assets/24946938/21792013/10981ac8-d6e7-11e6-9007-516a06621bcb.png)

**Comment by lgeiger** [comment]
Could you post the steps to reproduce this issue?

**Comment by mda6** [comment]
Actually not really.. the only thing that i noticed is when i was switching back to that buffer from another

**Comment by lgeiger** [comment]
I'm going to close this since the error is thrown from Atom itself and I can't reproduce it.
