### ISSUE TITLE
Hydrogen doesnt seem to detect python3 installation

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#583]
Atom:
1.13.0
Hydrogen
1.5.3

Hello,

Thanks for that cool package. Im using it quite frequently on different Mac Book Pros. On one of the machines running  OS X El Capitan ` 10.11.6` I get the following error:

![error kopie](https://cloud.githubusercontent.com/assets/18237090/21939675/2df32d88-d9c1-11e6-8edf-a64fe91ac163.png)

Not sure where it comes from.  Appreciate any suggestions.

`$echo $PATH`

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`

`$ which python3`

`/usr/local/bin/python3`

`ls`
`2to3-3.6		pydoc3			python3.6m`
`easy_install-3.6	pydoc3.6		python3.6m-config`
`idle3			python3			pyvenv`
`idle3.6			python3-config		pyvenv-3.6`
`pip3			python3.6		wheel3`
`pip3.6			python3.6-config`
`MacBook-Pro:bin$ pwd`
`/usr/local/opt/python3/bin`

**Comment by lgeiger** [comment]
It looks like it references the wrong Python version (3.5 instead of 3.6).

I had a similar error when upgrading my Python environment.
I'm sure there is a better way of doing it but this worked for me:
```
python3 -m jupyter kernelspec remove python3
python3 -m pip install ipykernel
python3 -m ipykernel install --user
```

**Comment by hugeme** [comment]
@lgeiger Thank you that worked!

**Comment by lgeiger** [comment]
Excellent!

**Comment by yildirimalici** [comment]
@lgeiger Thank you that worked!
