### ISSUE TITLE
long runtime of even fail hydrogen atom

### ISSUE THREAD

**Issue by orijjsjje** [nteract/hydrogen#584]
Everything was working fine. Until suddenly even a simple print('example') line didn't even run anymore with hydrogen. I use the atom editor.

See attached a screenshot. Hopefully someone can help me out :)

![image](https://cloud.githubusercontent.com/assets/25119961/21955490/87912d58-da6c-11e6-9f6f-21e35f6def04.png)

It is continuously showing that icon next to print(pay).

**Comment by lgeiger** [comment]
Could you open atom in dev mode (`View --> Developer --> Open in Dev Mode...`) and post a screenshot of the dev console (`View --> Developer --> View Dev Console...`) after running the command?

**Comment by orijjsjje** [comment]
Hi Igeiger, Thanks for the quick response. What is the difference with dev mode? I've done what you said, but couldn't find the view you meant called View Dev Console (see screenshot).

![image](https://cloud.githubusercontent.com/assets/25119961/21955637/882c2a1c-da6f-11e6-9922-43fa9a9270e0.png)

**Comment by lgeiger** [comment]
Oh I'm sorry I meant Toggle Developer Tools

**Comment by orijjsjje** [comment]
ah oke, I've run the code in the first screenshot I posted and did what you said resulting in this:

![image](https://cloud.githubusercontent.com/assets/25119961/21955734/2cee7aae-da71-11e6-87f9-858c86fce39f.png)

**Comment by orijjsjje** [comment]
@lgeiger  or anyone else who knows how to solve this issue?

**Comment by rgbkrk** [comment]
You next need to open the console so we can see the errors:

![console](https://cloud.githubusercontent.com/assets/836375/21957702/95595426-da51-11e6-9a0b-df8ff5f71295.png)

**Comment by orijjsjje** [comment]
![image](https://cloud.githubusercontent.com/assets/25119961/21963219/d9b3a870-db36-11e6-9cfd-54c6b57385ca.png)

Indeed very useful to learn how to debug this way. Above you can see the error I found. Could someone explain this error and tell me how to solve it?

**Comment by orijjsjje** [comment]
This is what I found on Stackoverflow: http://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected

It says that I've to run this line:

`process.setMaxListeners(0);`

However, I am new to Python/Atom so if this is the solution, where should I run this line then? Once I run this line in Atom I get this error:

```
Traceback (most recent call last):
  File "/Users/***/Documents/Pyhton/Project/test.py", line 1, in <module>
    process.setMaxListeners(0)
NameError: name 'process' is not defined
```

**Comment by lgeiger** [comment]
The error doesn't seem to come from Hydrogen directly.
Is it also there if Hydrogen isn't running? Which version of Atom are you using?

**Comment by orijjsjje** [comment]
I am using version 1.12.9 and it happens only with hydrogen. For example this line of code:

x = 1
print(x)

Then it keeps on running showing that icon in the first screenshot I posted saying that Python 3 is busy.

However, when I look at the console in dev mode, then it doesn't show an error, but the program just doesn't run. Only a couple of warnings (see screenshot):

![image](https://cloud.githubusercontent.com/assets/25119961/22124361/dc057fca-de8f-11e6-95fb-465e0afcf843.png)

This way I can't continue working in python so would be appreciated if anyone can help me to find the solution :)

**Comment by lgeiger** [comment]
Could you expand the Hydrogen logs like this?
![bildschirmfoto 2017-01-19 um 21 56 23](https://cloud.githubusercontent.com/assets/13285808/22125003/4e780594-de92-11e6-987f-1f32108c2b75.png)

In particular `Hydrogen ResultView: Add result` and the logs after that are interesting.

**Comment by orijjsjje** [comment]
Here it is:
![image](https://cloud.githubusercontent.com/assets/25119961/22125613/ab4b5b52-de94-11e6-8aa4-21f93513f510.png)

**Comment by lgeiger** [comment]
Thanks, everything looks normal here.

Please check that you haven't disabled `Use Shadow DOM` under `Settings > Editor`. This option should be enabled and was removed in Atom 1.13.

**Comment by orijjsjje** [comment]
I guess you mean atom > preferences > editor. I don't even see the option Use Shadow DOM there...   so what can I do to get hydrogen running?

**Comment by lgeiger** [comment]
Could you try updating Atom to the latest version?

**Comment by orijjsjje** [comment]
I am using the latest version already. Checked for it, but Atom itself says so.

**Comment by lgeiger** [comment]
Atom 1.13 is the latest stable version: https://github.com/atom/atom/releases/tag/v1.13.0

**Comment by n-riesco** [comment]
@orijjsjje

Does this issue only happy when you execute code that invokes `input`?
If so, does Hydrogen show a window prompting for an input?
Does the dev console log show any messages about the input?

**Comment by orijjsjje** [comment]
@lgeiger found out that installing 13.1.1 doesn't solve the issue. Restarting the kernel does temporarily. 

@n-riesco yes only when it invokes input and yes it shows that window, once I press enter the issue of endless runtime occurs. Here above you can see in the screenshots what the dev console communicates. Would be great if you could help me solving this.

**Comment by lgeiger** [comment]
@orijjsjje I just tried your original example multiple times and don't encounter this issue.

You said everything worked fine in the past. Have you changed your python environment in between?

**Comment by BenRussert** [comment]
@orijjsjje I'll close this for now, feel free to reply if you are still having trouble.
