### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by suranah** [nteract/hydrogen#59]
Trying to run Hydrogen for iPython kernel, but it threw this error. Various kernels are installed locally and work in Jupyter notebooks.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.9.2
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.3.15

### Stack Trace

Failed to activate the Hydrogen package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at bindings (/Users/harshitsurana/.atom/packages/Hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/harshitsurana/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:452:26)
```

### Commands

```
     -0:00.7.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.3.15
monokai, v0.7.0

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
Sorry for the delay — I was out of town and didn't touch a computer.

This is pretty weird. I usually see this when dependencies are out of sync with the package. Can you try going into `~/.atom/packages/Hydrogen/` (or wherever your packages are installed) and running `apm rebuild`?

**Comment by jkroso** [comment]
I just had the same issue and `apm rebuild` fixed it

**Comment by suranah** [comment]
Thanks Will! Apologies for the delay in replying, did not get time for hobbyist projects where hydrogen would have helped.

I could not run `apm rebuild`, due to some issue with hashring:

```
npm ERR! Darwin 13.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/harshitsurana/.atom/.apm/.apmrc" "--userconfig" "/Users/harshitsurana/.atom/.apmrc" "rebuild" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hashring@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1

npm ERR! Failed at the hashring@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hashring package,
npm ERR! not with npm itself.
```
And when I tried just `apm rebuild hydrogen` it unfortunately did not solve the issue inside Atom.

**Comment by willwhitney** [comment]
After a bunch of Googling, it's possible that this is an issue with the underlying `npm` being used: https://github.com/3rd-Eden/node-hashring/issues/28. Your Atom is up to date, though, so I'm not sure what to say about this...

**Comment by n-riesco** [comment]
@suranah `apm rebuild`didn't solve the problem for me. Something that has worked for me in the past is:

```sh
cd ~/.atom/packages/Hydrogen/
rm -rf node_modules
apm install
```

**Comment by n-riesco** [comment]
@suranah I'm closing this issue. Please, feel free to reopen it if you need more help.
