### ISSUE TITLE
exploring using `jmp` as a transport layer

### ISSUE THREAD

**Issue by willwhitney** [nteract/hydrogen#6]
[`jmp`](https://github.com/n-riesco/jmp) is an npm module for creating, parsing and replying to messages of the Jupyter Messaging Protocol.

**Comment by rgbkrk** [comment]
Also worth noting that the ijavascript developer,@n-riesco is [very responsive and open to ideas](https://github.com/n-riesco/ijavascript/pull/21#issuecomment-97832339). I've also enjoyed the amount of documentation he's put in.

**Comment by n-riesco** [comment]
It's great to see more interest in `jmp`. The package is a spin-off of [IJavascript](https://github.com/n-riesco/ijavascript). IJavascript uses it only for replying to Jupyter messages. I'd love to see other projects use it to write requests. I'm sure the interface to create requests could be made more convenient.

**Comment by n-riesco** [comment]
#197
