### ISSUE TITLE
How is the displayed figure size set in Atom/Hydrogen?

### ISSUE THREAD

**Issue by dnowacki-usgs** [nteract/hydrogen#600]
I'm not sure this is the right place to ask this question, but here goes.

I can't figure out how the displayed size of a pyplot figure in Hydrogen is determined. It seems like there is a maximum pixel area or something. Here are two example screenshots. Note that the widths of the two figures should be the same, but if I increase the height, the overall width is reduced (compare figure widths to the 80 character text width line). It's harder to tell, but the second figure is slightly taller than the first. What's going on? The overarching goal here is to get Atom/Hydrogen to display larger figures.

**figsize=(12,8)**
![screen shot 2017-01-27 at 17 42 46](https://cloud.githubusercontent.com/assets/13837821/22391671/3aa6b08e-e4b8-11e6-8d50-0dc662bbbe3b.png)

**figsize=(12,10)**
![screen shot 2017-01-27 at 17 43 09](https://cloud.githubusercontent.com/assets/13837821/22391689/504728ba-e4b8-11e6-92bd-526253750251.png)

**Comment by lgeiger** [comment]
If I recall correctly we scale images to fit the screen (in CSS). Therefor max-width and max-height are set and the image is scaled down accordingly.

I'm open to change that behavior. What would be your desired behavior for the output bubble?

**Comment by dnowacki-usgs** [comment]
Thanks for the reply. I generally want the real estate of a large figure/image and don't mind if I have to scroll a bit. I guess I would prefer Hydrogen scale the image according to the dpi of the screen and the specified figsize. If I specify a larger figure size, I'd like for it to keep getting larger and not run into an upper limit.

**Comment by lgeiger** [comment]
@dnowacki-usgs Would you like to submit a PR for this? It should by mainly a CSS change.

**Comment by Earthson** [comment]
I've noticed downscale by #242, it's really strange behavior. 

I think it should be configurable.

**Comment by lgeiger** [comment]
@Earthson You're very welcome to submit a PR. Feel free to ask any questions if you need help.

**Comment by Earthson** [comment]
@lgeiger I created a PR which remove all img style, is it OK?

https://github.com/nteract/hydrogen/pull/607

**Comment by Earthson** [comment]
scroll bar appear when figure size overflow,  I think it is acceptable.

**Comment by dnowacki-usgs** [comment]
Thanks a bunch for submitting this @Earthson. This is certainly an improvement; scrolling is better than downscaling. 500px still doesn't seem tall enough (to me). Increasing the `max-height` on line 26 of hydrogen.less to, say, `700px` does work, but more than that and you start to run into issues on smaller screens. I think something like `75vh` could be the way to go here to keep it flexible on smaller screens. Thoughts?

**Comment by Earthson** [comment]
It seems user can customize style using "~/.atom/styles.less", eg.

```css
.hydrogen.output-bubble {
  .bubble-output-container {
    max-height: 1000px;
  }
}
```

**Comment by lgeiger** [comment]
Yes, the user can customize it via a personal style sheet. Though we should definitely make this easier by cleaning up our CSS.

The relevant issue is [here](https://github.com/nteract/hydrogen/issues/252).

**Comment by ziyaotang** [comment]
Hello, I have the same question. It seems that I still cannot set the size of the image. Any improvement on this? Thanks!

**Comment by paul-grassl** [comment]
I'm also having trouble knowing how to customize the size of images in the inline output...R prints them very big, which is not practical.

I looked into the `hydrogen.less` sheet and also tried to add the code suggested by @Earthson  above to my own `style.less` sheet but it didn't solve the problem. Any advice is appreciated, thanks!
