### ISSUE TITLE
CPU usage of Kernel on Win7 64-bit

### ISSUE THREAD

**Issue by cdkorzen** [nteract/hydrogen#601]
**Description:**
When I start up hydrogen, after a small lag to find the available kernels, and run some code, the kernel starts.  One of the atom.exe processes goes to a constant 25%+ CPU  usage if I'm also doing profiling.  Since I have a 4 core, machine, this is at least one core at 100%.  Without profile, atom.exe runs at 5-7%

I'm not sure if #549 is related.

**Steps to Reproduce:**

1. Open a document with Python 2 code
2. Run some code.  When I generated a profile, I just ran a large group of imports.

**Versions:**

Atom: 1.12.9
Hydrogen: 1.5.4
Python (in Anaconda env): 2.7.13

IPython: 5.1.0
ipykernel: 4.5.2

**Captured data:**
Profile and timeline, same session, but not captured at the same time, both with kernel starting early on in the sequence.  Timeline shows a huge chunk of time in "other".  I don't see a pattern in the JS Profiling like I do in the Timeline, where you can see a clear uptick in CPU usage when I start the kernel.

(Note: I definitely captured data, saved it, Atom created files on the hard drive, but apparently those files are empty -- will go off and try to recreate, but that's really annoying)

**Comment by cdkorzen** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=435015 is possibly related to why I can't save profile/timeline data, but I'm not sure.

**Comment by n-riesco** [comment]
Does it happen when you run the same code in the python console?

**Comment by ionor** [comment]
I have the exact same problem with high CPU usage even during idle-time. 
- Using win 7 64-bits.
- Python 3.6 from latest anaconda 4.3.
- Atom 1.14.0-beta4 (tried stable relase as well)
- ipython 5.1.0, ipykernel 4.5.2 and latest hydrogen
- tried reinstalling anaconda (with all included packages), atom, hydrogen etc but without any noticeable progress.

And i also have the same problem with saving profile//data. 

When i run the same code in spyder or pycharm i dont se the same effect,

**Comment by BenRussert** [comment]
[I took a screen cast trying to duplicate on my windows 10 partition.](https://www.youtube.com/watch?v=EQX470oqXyo) I am able to get the CPU% to rise when starting kernels, but I dont notice the lag and overall everything seems fine.

I wonder if there is anything we can do about this or is the CPU rise normal?

**Comment by BenRussert** [comment]
We have a couple issues open regarding the CPU% issue (which is actually multi-platform). I will keep looking into the potential lag issue on windows, but for now I wasn't able to reproduce.

For more on the CPU rise issue, see #646 open for help/discussion
