### ISSUE TITLE
Hydrogen Status is not Correctly Aligned...

### ISSUE THREAD

**Issue by pingshunhuangalex** [nteract/hydrogen#604]
Sorry for being picky, but I just noticed that when Hydrogen is activated, the Hydrogen status sitting in the status bar is not accurately aligned...

![image](https://cloud.githubusercontent.com/assets/17170199/22494055/4d373df8-e888-11e6-9965-d64858419641.png)

I think the following tweak should do the work...
```
.hydrogen.status-container {
    display: inline-block;
    cursor: pointer;
    vertical-align: middle;
```

**Comment by lgeiger** [comment]
> Sorry for being picky,

No problem, thanks for opening a issue!

This looks like a issue with your Atom theme. It renders correct on my machine with the default Atom One Dark theme.

Which  theme are you using?

**Comment by pingshunhuangalex** [comment]
I'm using the material dark theme, which should also be quite popular I assume.

**Comment by lgeiger** [comment]
> Will changing the vertical-align from top to middle affect what it displays in Atom One Dark theme?

Unfortunately this doesn't work for Atom One Dark.

I'll take a look if there is an other solution.
