### ISSUE TITLE
MacOS X Sierra : Kernel not found issues.

### ISSUE THREAD

**Issue by evmin** [nteract/hydrogen#606]
Getting

"Use kernelSpec option in Hydrogen or update IPython/Jupyter to a version that supports: jupyter kernelspec list --json or ipython kernelspec list --json"

Yet when I run the required commands in shell - I get the required output:

```
#  jupyter kernelspec list --json
{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/Library/Python/2.7/site-packages/ipykernel/resources",
      "spec": {
        "language": "python",
        "display_name": "Python 2",
        "env": {},
        "argv": [
          "/usr/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      }
    }
  }
}
```

Copied it over into the Hydrogen config.
Now the kernel is listed, but I get 

```
No running kernel for language python found
```

Not sure where to look. What do I miss here?

```
# port installed | grep python
  mesa @12.0.1_2+osmesa+python27 (active)
  python2_select @0.0_2 (active)
  python27 @2.7.13_0 (active)
  python_select @0.3_7 (active)
  xorg-libxcb @1.12_2+python27 (active)
  xorg-xcb-proto @1.12_1+python27 (active)

# pip list | grep jupyter
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.1.0)
jupyter-core (4.2.1)
```

**Comment by lgeiger** [comment]
Could you post the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md)?

**Comment by evmin** [comment]
Thank you. Missed this link.

```
# atom --version
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

The logs after I have tried to select a Kernel
```
Hydrogen setWatchSidebar: undefined
Hydrogen Selected command: Object {name: "Python 2", kernelSpec: Object}
Hydrogen handleKernelCommand: [Object]0: Objectcallee: handleKernelCommand(_ref)length: 1Symbol(Symbol.iterator): values()__proto__: Object__defineGetter__: __defineGetter__()arguments: nullcaller: nulllength: 2name: "__defineGetter__"__proto__: ()<function scope>__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()

```

Not sure I am posting the correct thing though. Is there anything specific I should be looking for?

**Comment by evmin** [comment]
And when I try to run a cell:

```
'/Users/kn/anaconda/bin/python' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

Not sure what "kn" is - it is not my username

**Comment by lgeiger** [comment]
It looks like the Hydrogen config is somehow broken.
Could you reset the Hydrogen kernel spec settings, restart Atom and try again?

**Comment by evmin** [comment]
Done.

back to the original "No kernel specs found" and then "No kernel for language python found"

**Comment by lgeiger** [comment]
Thanks, let's track this down.

Could you now again post the entire log of the dev console before messing with the Hydrogen settings? It's best to see if you do a screenshot.

**Comment by evmin** [comment]
I think I might be onto something.
I am usually starting Atom from the Nimble Commander.

When I start from there - that's where I get the issue. 

If I start from the shell, or from Alfred - it seems to work (though Atom Helper consumes 400% and the fans a spinning like crazy).

**Comment by evmin** [comment]
Ok I can pinpoint the issue to running it to NC. 
Would you have an idea where to look?

**Comment by evmin** [comment]
![image](https://cloud.githubusercontent.com/assets/5507517/22622883/e9fefdd6-eb9b-11e6-8998-94d848ebfac7.png)

**Comment by lgeiger** [comment]
It looks like Nimble Commander doesn't forward the environment variables correctly.
You can check this by executing `process.env` in the dev console and see if there's a difference between the two launch methods. If they differ you may want to open a issue in the Atom repository.

> though Atom Helper consumes 400% and the fans a spinning like crazy).

Woa that shouldn't be the case. A small increase in CPU usage is expected because of the python process running in the background, but 400% is insane.

**Comment by evmin** [comment]
I appreciate your help and your guidance a lot - thank you. I will take it up with NC - indeed NC does not forward everything (I am a part of beta testing user team, so it is understandable, otherwise it is a great tool).

I have  not seen 400% ever since. Could be a one off fluke. I suspect PATH is at fault here.
In either case I consider the case solved.

Once again - thank you! Especially for teaching me the dev console.

**Comment by lgeiger** [comment]
If you still like to use Nimble Commander, you can add the output of `jupyter kernelspec list --json` to the kernel specs field in the Hydrogen settings.

Fell free to reopen this issue if you have any problems.
