### ISSUE TITLE
Multiple cell magics do not work with Run All

### ISSUE THREAD

**Issue by ajlai** [nteract/hydrogen#612]
**Description:**
When I have multiple cell magics in a document, only the very first one works with Run All.

**Steps to Reproduce:**

1. `Run All` on this document: ![image](https://cloud.githubusercontent.com/assets/384556/22763717/49aff63c-ee1b-11e6-98b1-b6f9033c9619.png)

2. Observe syntax error (cell magic is not being picked up.)

**Versions:**

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
Atom    : 1.13.1
Hydrogen: 1.5.5
```

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

**Comment by lgeiger** [comment]
Could you test if cell magics that don't change the kernel language work?

**Comment by ajlai** [comment]
here you go:
![image](https://cloud.githubusercontent.com/assets/384556/23345052/57451a8c-fc3c-11e6-9e51-09ac8a63eec5.png)

I looked a bit more into why this is happening and it seems to be because we pass the cell divider comment line as the first line of the cell when running it. (checked using %hist) For cell magics to work the first line must be the cell magic and cannot be a comment.
