### ISSUE TITLE
Output window bottom scroll bar cropping text

### ISSUE THREAD

**Issue by Trollgeir** [nteract/hydrogen#613]
**Description:**
The bottom of the output window is cropped 

![Problem](http://i.imgur.com/D2mSefF.png)

I propose adding some extra space before the scrolling bar.

**Steps to Reproduce:**

Print long text outputs inline

**Versions:**

Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by lgeiger** [comment]
We probably missed this one because on macOS the scrollbars are hidden by default :smile:

I don't know if there is a standard way of reserving space for scrollbars.

Would you like to make a PR to fix this?
