### ISSUE TITLE
Hydrogen fails on startup with incompatible native modules (zeromq) on OSX 10.11.6

### ISSUE THREAD

**Issue by davemssavage** [nteract/hydrogen#617]
I'm trying to use hydrogen with docker via docker-machine on OSX and all hydrogen commands fail silently in UI, in the background there is a developer log with the following:

```
Failed to require the main module of 'Hydrogen' because it requires one or more incompatible native modules (zeromq).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

**Steps to reproduce**

```bash
brew install zeromq
brew install pkg-config
apm install hydrogen
```

Start atom, CMD+SHIFT+P -> hydrogen: connect to remote kernel

**Versions:**

OSX: 10.11.6
zeromq: 4.2.1
pkg-config: 0.29.1_2
Hydrogen: 1.5.5
Atom: 1.14.3
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

Any help appreciated this looks like a great package!

**Comment by lgeiger** [comment]
Since hydrogen `1.0.0` you don't need to install `pkg-config` and `zeromq` separately anymore. We bundle all the necessary dependencies (except `jupyter`). It looks like `zeromq` is built against the wrong Node version. Do you have multiple versions of Atom installed?

Could you run `apm rebuild`, restart Atom and try again?

If this doesn't help please try:
```bash
apm uninstall hydrogen
apm install hydrogen
```

Please post any errors that might occur while running above commands.

**Comment by BenRussert** [comment]
I'll close this as it looks like reinstalling should work. Feel free to reply if you have any questions.

**Comment by dengemann** [comment]
@lgeiger @BenRussert moving to my new mac and doing a fresh install I run into the same issue with exactly the same error message as reported by @davemssavage. I tried the suggestions above but nothing worked. My Atom version is 1.19.9 x64 and Hydrogen is the latest (1.19.0). I'd be very grateful for your help, hydrogen became a hard dependency for my daily work.

**Comment by BenRussert** [comment]
@dengemann When you open atom do you see an [incompatible packages](https://github.com/atom/incompatible-packages/blob/master/README.md) view with a little button on the bottom that says "rebuild modules"? I think pressing this will resolve the issue.

To resolve from the command line you will need to cd to the directory where hydrogen is installed, then run `apm rebuild`, or if you are on atom beta and mac `apm-beta rebuild`

**Comment by dengemann** [comment]
@BenRussert woot! Indeed that little red bug in the bottom pane is not just cute but indeed revealed a built conflict plus a graphical resolution interface. Btw. rebuilding with apm from command line did not do the job, only the GUI way worked. Now everything works like a charm. Thank you for your help. Keep up the amazing work, hydrogen profoundly transformed the way I get things done.

**Comment by BenRussert** [comment]
@dengemann that is great to hear!

You are not the first to report that the GUI method works, but not via apm. I'm :man_shrugging: on that, so I've been pushing the GUI method.

**Comment by dengemann** [comment]
That's indeed amusing. It would not have occurred to me to search for a
solution inside the GUI. Thank you once more!

**Comment by adavidzh** [comment]
FWIW, I tripped on this today and the GUI solution worked while the CLI solution didn't.
