### ISSUE TITLE
Errors using Hydrogen with scala

### ISSUE THREAD

**Issue by hagaiattias** [nteract/hydrogen#618]
Installed jupyer, jupyter-scala and hydrogen. Using Atom 1.14.3.
When try to run scala code I'm getting:
"No kernel for language null grammar found
Check that the language for this file is set in Atom and that you have a jupyter kernel installed for it."

I think it's a scala only issue, tried with python and it worked.

**Comment by hagaiattias** [comment]
update: installed "language-scala 1.1.8" package and now the error is gone but when I run (cmd+Entr) nothing happens.

**Comment by lgeiger** [comment]
Scala may use a non default language name for their kernels. You can check the exact name by running `jupyter kernelspec list --json` and taking a look at the `language` field.

Modifying the `Language Mappings` settings in Hydrogen should help in that case.

**Comment by hagaiattias** [comment]
It actually says "scala":
{
  "kernelspecs": {
    "scala": {
      "resource_dir": "/Users/hattias/Library/Jupyter/kernels/scala",
      "spec": {
        "language": "scala",
        "display_name": "Scala",
        "env": {},
        "argv": [
          "java",
          "-noverify",
          "-jar",
          "/Users/hattias/Library/Jupyter/kernels/scala/launcher.jar",
          "launch",
          "-r",
          "sonatype:releases",
          "-r",
          "sonatype:snapshots",
          "-i",
          "ammonite",
          "-I",
          "ammonite:org.jupyter-scala:ammonite-runtime_2.11.8:0.8.1",
          "-I",
          "ammonite:org.jupyter-scala:scala-api_2.11.8:0.4.0-RC3",
          "org.jupyter-scala:scala-cli_2.11.8:0.4.0-RC3",
          "--",
          "--id",
          "scala",
          "--name",
          "Scala",
          "--quiet",
          "--connection-file",
          "{connection_file}"
        ]
      }
    },
    "python2": {
      "resource_dir": "/Users/hattias/Tools/anaconda2/lib/python2.7/site-packages/ipykernel/resources",
      "spec": {
        "language": "python",
        "display_name": "Python 2",
        "env": {},
        "argv": [
          "/Users/hattias/Tools/anaconda2/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      }
    }
  }
}

I created a mapping {"scala":"scala"} but still getting the error.

**Comment by lgeiger** [comment]
Thanks for trying, you can remove the mapping `{"scala":"scala"}` again, since it doesn't do anything.

Make sure you have a syntax highlighting package like [`language-scala`](https://atom.io/packages/language-scala) installed and activated. Otherwise Atom/Hydrogen won't recognize the language.

**Comment by hagaiattias** [comment]
Yeah, I actually just installed it and the error went away, however when trying to execute simplest code I see the "mini-icon of moving barcharts", but nothing happens.

**Comment by lgeiger** [comment]
Could you post a screenshot of the dev console as described in out [troubleshooting guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md#debugging-guide)?

**Comment by lgeiger** [comment]
Have you tried the Scala kernel with `jupyter`?

**Comment by hagaiattias** [comment]
I actually think I found the problem after looking in the console as you suggested - 

> Hydrogen ZMQKernel: stderr: Exception in thread "main" java.lang.RuntimeException: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
>   file:/Users/hattias/.m2/repository/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar: not found

I actually have another version of scala installed, how can I change it?

**Comment by hagaiattias** [comment]
ok, I installed 2.11.8 and now it works. thanks for the help!
