### ISSUE TITLE
handle pager request. 

### ISSUE THREAD

**Issue by Carreau** [nteract/hydrogen#62]
The pager messages (like `foo?`) don't seem to be handled. 
A quick and dirty way for IPython kernel would be to pass `--ZMQInteractiveShell.display_page` that basically do `pager() == display()`,

**Comment by willwhitney** [comment]
Wow, yeah, I hadn't thought about the pager. Much as I'd like to I can't do the IPython hack, since people use Hydrogen with all kinds of kernels, but implementing pager handling is now in the pipeline.

**Comment by Carreau** [comment]
Great, no problems. 
Feel free to give us feedback if you feel that some things are not well described/wrong.

**Comment by lgeiger** [comment]
https://github.com/nteract/hydrogen/pull/193
