### ISSUE TITLE
Config hydrogen for Atom and Python portable

### ISSUE THREAD

**Issue by jackjameshoward** [nteract/hydrogen#624]
I'm running everything portable on windows -  Atom, python2, python3 and ipython/jupyter 
Therefore nothing is in the PATH for python.
How can I change where hydrogen looks for the kernals?

**Comment by lgeiger** [comment]
It depends on your setup. How are you using your setup with jupyter notebooks or ipython?

Hydrogen only needs jupyter on the path to find the kernel specs. If that's not possible you add the output of `jupyter kernelspec list --json` to the "Kernelspec" settings in Hydrogen.

**Comment by jackjameshoward** [comment]
I'm using jupyter notebooks, so can I redirect Hydrogen to the correct path for jupyter notebooks?

**Comment by jackjameshoward** [comment]
I've resolved this now. I used the output of `jupyter kernelspec list --json` in the end because it allowed me to add multiple versions of python. Thanks

**Comment by lgeiger** [comment]
Sorry for not getting back to you. I'm glad you got it working 🎉
