### ISSUE TITLE
Images are higher than bubble output

### ISSUE THREAD

**Issue by tpoisot** [nteract/hydrogen#632]
**Description:**

When the output is a plot, the plot can be taller than the bubble container:

Observed behavior:

![screenshot from 2017-03-11 15-01-42](https://cloud.githubusercontent.com/assets/579329/23826530/e723fc20-066b-11e7-80c3-7170d361fea4.png)

Expected behavior:

![screenshot from 2017-03-11 15-01-47](https://cloud.githubusercontent.com/assets/579329/23826532/f4bc2902-066b-11e7-9df5-a721dd6c9252.png)

I realize that the "expected" behavior is eating up a lot of the screen space. Is this a feature, or should the figure be scaled down, or anything else?

**Versions:**
Atom 1.114.4 / Hydrogen 1.6.0

**Comment by lgeiger** [comment]
We had the discussion about downscaling in #600 and decided to not do rescaling in order to be able to change the figure size.

I think we should either have the ability to configure this behavior or add the possibility to expand the output by clicking or dragging the lower border.

**Comment by BenRussert** [comment]
My vote would be to explore the click and drag resize option.
