### ISSUE TITLE
Enlarge plot output

### ISSUE THREAD

**Issue by fox895** [nteract/hydrogen#640]
Hi, I really love this package, the only problem I have with it is the size of the plot, some times I would like to enlarge them but I still haven't found a way to do it... I'm wondering if it's possible or not

**Comment by lgeiger** [comment]
Hydrogen respects the figure size of the library you use to generate the plot. Wich language are you using?

For example in Python with matplotlotlib you can change the figure size like [this](http://stackoverflow.com/questions/332289/how-do-you-change-the-size-of-figures-drawn-with-matplotlib).

**Comment by fox895** [comment]
Ok thanks for the rapid reply!
