### ISSUE TITLE
Hydrogen can't spawn jupyter kernel

### ISSUE THREAD

**Issue by cripcate** [nteract/hydrogen#647]
**Description:**

```
opencv-3.2.0/opencvtest.py0001:11Python 3: starting
LFUTF-8Python
'/home/nils/anaconda3/bin/python' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process. issue]
```

Hydrogen stopped working completely. Seems like it can't start the kernel.  My anaconda installation is valid tho:

```
nils@Nils-thinkpad:~$ which python
/home/nils/anaconda3/bin/python
```

and I can also run it in terminal or the jupyter notebook.

When i start the hydrogen kernel, an ["inspect element" dialog](https://imgur.com/a/P2tOr) is also showing up in atom.

**Steps to Reproduce:**

It just suddenly stopped working. Maybe it's related to an update? I tried updating atom and all packages, reinstalling hydrogen. Still the same problem.

**Versions:**

Ubuntu 16.04

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

anaconda Command line client (version 1.6.2)

Hydrogen: 1.6.0

**Logs:**

```
Uncaught Error: spawn /home/nils/anaconda3/bin/python ENOENT

linter-registry.js [sm]:144 [Linter] Error running Flake8 Error: Failed to spawn command `/home/nils/anaconda3/bin/flake8`. Make sure `/home/nils/anaconda3/bin/flake8` is installed and on your PATH(…)(anonymous function) @ linter-registry.js [sm]:144_tickCallback @ internal/process/next_tick.js:103
linter-registry.js [sm]:144 [Linter] Error running Flake8 Error: Failed to spawn command `/home/nils/anaconda3/bin/flake8`. Make sure `/home/nils/anaconda3/bin/flake8` is installed and on your PATH(…)(anonymous function) @ linter-registry.js [sm]:144_tickCallback @ internal/process/next_tick.js:103
linter-registry.js [sm]:144 [Linter] Error running Flake8 Error: Failed to spawn command `/home/nils/anaconda3/bin/flake8`. Make sure `/home/nils/anaconda3/bin/flake8` is installed and on your PATH(…)(anonymous function) @ linter-registry.js [sm]:144_tickCallback @ internal/process/next_tick.js:103
linter-registry.js [sm]:144 [Linter] Error running Flake8 Error: Failed to spawn command `/home/nils/anaconda3/bin/flake8`. Make sure `/home/nils/anaconda3/bin/flake8` is installed and on your PATH(…)(anonymous function) @ linter-registry.js [sm]:144_tickCallback @ internal/process/next_tick.js:103

events.js:160
Uncaught Error: spawn /home/nils/anaconda3/bin/python ENOENT
exports._errnoException	@	util.js:1026
ChildProcess._handle.onexit	@	internal/child_process.js:193
onErrorNT	@	internal/child_process.js:359
_combinedTickCallback	@	internal/process/next_tick.js:74
_tickCallback	@	internal/process/next_tick.js:98
﻿
```

There seems to also be a problem with flake8 (which i also reinstalled and updated)

**Comment by lgeiger** [comment]
The error seams to be coming from the  `linter` and `linter-flake8` packages and not from Hydrogen itself.
Could you try if disabling them solves the issue?

**Comment by cripcate** [comment]
At this point it just randomly works or not, like on a 50% chance when starting the hydrogen kernel in atom. It's weird. Activating / deavtivating linter and flake8 has no effect, besides the 4 errors in the middle disappearing.

**Comment by lgeiger** [comment]
Could you check if `/home/nils/anaconda3/bin/python` exists and can be executed?

**Comment by cripcate** [comment]
It exists, and can be executed. It's my standard python path. Right now it seems to be working again, without me changing a thing :S

**Comment by cripcate** [comment]
It seems to be working again. And quite stable. Really weird because I haven't really changed anything before the issue occured, or anything particular to fix it. But i guess i can close the issue now.
