### ISSUE TITLE
Improve our README structure

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#654]
Our README has a lot of valuable information. Though it's a bit unstructured at the moment. I think we should either move a few sections into separate files or provide a table of content on the top.

For example:
https://github.com/RichardLitt/standard-readme
https://github.com/jakubroztocil/httpie

**Comment by willingc** [comment]
Here's another good example: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by lgeiger** [comment]
@willingc Thanks for the link!

**Comment by BenRussert** [comment]
To start the ball rolling I added a ["Contents" header with links to each section to my fork](https://github.com/BenRussert/hydrogen/blob/update-readme/README.md).

I think this small step helps organize a fairly lengthy README.

**Comment by willingc** [comment]
@BenRussert Looks good and the extra navigation helps.

Two small suggestions:
- Move the GIF up higher under so folks can see it without scrolling. I would grab the sentence about the Medium blog post with the image. So it would flow:
    - Title
    - badges
    - The intro sentence "This package lets you run your code ..."
    - "Checkout our Medium blog post to see what you can do with Hydrogen."
    - GIF
    - Contents
    - Background (less what was moved higher)

- At the very end of the file, it might be nice to add a "Return to top" link that brings you to the contents or top of file.

Nice job 👍

**Comment by BenRussert** [comment]
@willingc Great points. I made these changes and opened a pr.
