### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by pcuci** [nteract/hydrogen#666]
I would imagine it possible to select a piece of TypeScript, compile to es6, and pass it along to a JavaScript kernel.

Thoughs?

**Comment by lgeiger** [comment]
This would be the job of the (jupyter) kernel itself.

Here is a selection of kernels available: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

Apart from the "normal" [Javascript kernel](https://github.com/n-riesco/ijavascript) there's a [Typescript kernel](https://github.com/nearbydelta/itypescript) (haven't tried it)
and a [Babel kernel](https://github.com/n-riesco/jp-babel) for ES6.
