### ISSUE TITLE
Refactor code-manager as pure functions

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#672]
Right now [`code-manager.js`](https://github.com/nteract/hydrogen/blob/master/lib/code-manager.js) uses `store.editor` implicitly. This makes bugs like #669 a lot likelier since a user of the function may not check if `store.editor !== null` beforehand.

If we move to pure functions this will become more transparent and we can even add flow to this file to be reminded every time we don't check for the case `store.editor == null` before using a function.

For example `getTextInRange` right now looks like this (the output depends on the value of `store.editor`):
```javascript
export function getTextInRange(start, end) {
  const code = store.editor.getTextInBufferRange([start, end]);
  return normalizeString(code);
}
```

As a pure functions and with flow typings it would look like this (the output only depends on the input parameters):
```javascript
/* @flow */

export function getTextInRange(editor: atom$TextEditor, start: atom$Point, end: atom$Point) {
  const code = editor.getTextInBufferRange([start, end]);
  return normalizeString(code);
}
```

**Comment by BenRussert** [comment]
brb... reading up on [flow](https://flowtype.org/docs/five-simple-examples.html) 

At first glance it looks similar to [julia types](http://docs.julialang.org/en/latest/manual/types.html), one of the reasons julia is probably my favorite language.

**Comment by lgeiger** [comment]
Nice, and they even have a cool new website, just in time 😆 https://flowtype.org/

**Comment by BenRussert** [comment]
I'm going to take a crack at this after work today.

**Comment by lgeiger** [comment]
@BenRussert Very cool! 🎉 

There will be likely a few flow errors due to missing [declarations](https://github.com/nteract/hydrogen/blob/master/types/atom.js.flow) so feel free to submit a work in progress PR.

PS: If you need a nice flow linter I recommend the [flow-ide](https://github.com/steelbrain/flow-ide) plugin.

**Comment by BenRussert** [comment]
> PS: If you need a nice flow linter I recommend the flow-ide plugin.

Cool, I was going to ask about this. Tried Nuclide, but it was a little much for me at this point.

**Comment by BenRussert** [comment]
@lgeiger this is going pretty well so far. You were right that the stopping point was type declarations.

Is the plan just to add to the atom.js.flow file as we go? There were several missing methods/properties under `atom$TextEditor` and `atom$TextBuffer` that I could add to the file.

**Comment by lgeiger** [comment]
Great!

> Is the plan just to add to the atom.js.flow file as we go? There were several missing methods/properties under atom$TextEditor and atom$TextBuffer that I could add to the file.

👍 That's what I've been doing so far

**Comment by BenRussert** [comment]
This is working and passing tests (though I had to alter the code manger spec. I'll pr tomorrow for some feedback.

https://github.com/BenRussert/hydrogen/tree/refactor-cm-flow
