### ISSUE TITLE
Kernel specs of IRkernel

### ISSUE THREAD

**Issue by githubmpc** [nteract/hydrogen#679]
I'm having trouble launching IRkernel using Hydrogren. Reading the documentation, it seems like I need to update Kernel specs - what do I put in specifically for IRkernel? Thanks.

**Comment by willingc** [comment]
Hi @githubmpc, Did you use this documentation for IRkernel https://irkernel.github.io/installation/ ?

There are 3 main steps:
- Make sure that you have R installed.
- Next install IRkernel (binaries as described [here](https://irkernel.github.io/installation/) are simplest for Windows and Mac)
- In the R terminal console, enter the following command: `IRkernel::installspec()` which should install the IRkernel for use in Hydrogen.

Good luck!

**Comment by githubmpc** [comment]
Hi @willingc, Thanks for the reply. Actually completed those steps prior to posting but I should have been more clear apologies. The error I'm getting is as noted as a common problem in the troubleshooting guide - the "No kernel for language X found, but I have a kernel for that language" error. I don't quite understand the specifics in the guide on how to fix that error in terms of declaring the KernelSpec manually for IRkernel (this seems like what I need to do?)

Thanks!

**Comment by lgeiger** [comment]
@githubmpc Could you run `jupyter kernelspec list --json` in your terminal and post the output?

**Comment by willingc** [comment]
Do you have Jupyter installed? If so, what is the output of `jupyter kernelspec list`?

`jupyter kernelspec --help-all` provides more information about installing and removing language kernels.

For example, running this on my system returns:

<img width="642" alt="screenshot 2017-03-30 09 36 21" src="https://cloud.githubusercontent.com/assets/2680980/24515487/a3d9de88-152c-11e7-8d53-3f9677bed665.png">

**Comment by githubmpc** [comment]
Thanks @lgeiger @willingc . My output for those commands:

![output](https://cloud.githubusercontent.com/assets/15100825/24516396/6caf1b6e-1548-11e7-9c9e-dfacc79bf9a0.jpeg)

**Comment by lgeiger** [comment]
Thanks, looks normal to me.

What's the exact error message you get from Hydrogen?

**Comment by githubmpc** [comment]
Actually its working now. The only difference was that I restarted my computer since my first post. It popped up with the kernel updated message. I did try updating kernel after installing IRkernel yesterday but obviously didn't do it properly. Thank you both!

**Comment by lgeiger** [comment]
Excellent! 🎉
