### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ArisBar** [nteract/hydrogen#681]
Hydrogen can't seem to find any of the python modules I have in my package, any idea what I'm doing wrong ?

**Comment by BenRussert** [comment]
Can you list the steps you are going through to start hydrogen? Without any details I am guessing the package is not in your path.

If you start a console ipython session wherever the file you were working on w/ Hydrogen can you import the package there?

**Comment by lgeiger** [comment]
One thing to add is that the python process starts in the same folder as the first file you run commands from.

You can check the current directory of the kernel by running `%pwd`.

**Comment by BenRussert** [comment]
@ArisBar Just following up on this issue. Have you had a chance to try the suggestions above?

**Comment by BenRussert** [comment]
I'll close this for now, but feel free to reply if you're still looking for help.
