### ISSUE TITLE
Argument to path.dirname must be a string

### ISSUE THREAD

**Issue by JLCCI** [nteract/hydrogen#685]
Object.dirname - /usr/share/atom/resources/app.asar/src/electron-shims.js:9:10
KernelManager.startKernel - /home/user/.atom/packages/Hydrogen/lib/kernel-manager.js:121:43
<unknown> - /home/user/.atom/packages/Hydrogen/lib/kernel-manager.js:81:15
<unknown> - /home/user/.atom/packages/Hydrogen/lib/kernel-manager.js:191:11
<unknown> - /home/user/.atom/packages/Hydrogen/lib/kernel-manager.js:175:18
KernelManager.getAllKernelSpecs - /home/user/.atom/packages/Hydrogen/lib/kernel-manager.js:162:14

Many thanks!

**Comment by n-riesco** [comment]
@lgeiger I guess [this line](https://github.com/nteract/hydrogen/blob/2976b5d38480ca69496b252f1ab31edd390580c6/lib/kernel-manager.js#L93) gets called when there is not editor.

@JLCCI By any chance, are you using an old version of Hydrogen? I seem to remember a fix to a similar issue was applied recently.

**Comment by JLCCI** [comment]
@ n-riesco All up to date (at least on 1.15.0)

**Comment by BenRussert** [comment]
@JLCCI What about for hydrogen? You should be good on 1.8+

**Comment by JLCCI** [comment]
@BenRussert 1.9.0

**Comment by JLCCI** [comment]
And yes, it seems that it only appears where the file is not saved (i.e. new tab that was not saved anywhere).

**Comment by BenRussert** [comment]
Could be a bug, do you have any more info on how to reproduce? 

Recently we found a similar issue when using a Hydrogen keyboard shortcut from a package's console tab (the Julia/Juno package in that case).

**Comment by JLCCI** [comment]
Sure.

Open a new tab -> type 'plot(1:10)' -> Switch the language to 'R' -> execute the line using Ctrl-Enter

**Comment by BenRussert** [comment]
Hmm, i'm not seeing the issue. 

 Can you list the output from  `apm list -i ` in your terminal? Possible that there is another package interaction we haven't covered yet.

**Comment by JLCCI** [comment]
Here it is, pretty basic so hope it is easy to pinpoint. Thanks for looking into this!

![screenshot from 2017-04-01 21-49-03](https://cloud.githubusercontent.com/assets/18163728/24578863/28ab2d7a-1725-11e7-99ac-617adaf8d4a3.png)

**Comment by lgeiger** [comment]
@BenRussert I think to reproduce this you need to make sure the file isn't saved, otherwise `atom.workspace.getActiveTextEditor().getPath()` is always defined.

**Comment by BenRussert** [comment]
@lgeiger yep, I had no issue. You are able to reproduce?

**Comment by lgeiger** [comment]
I can try to reproduce this evening.

**Comment by BenRussert** [comment]
@JLCCI Thanks for all the info, I have some ideas about what could cause this.

**Comment by JLCCI** [comment]
@BenRussert No problem at all, happy to provide any additional details you might need.

Many thanks for maintaining this wonderful tool!

**Comment by lgeiger** [comment]
OK, I can reproduce this. Though I only get a deprecation warning.

Fix coming soon.
