### ISSUE TITLE
Switch to jest for unit testing?

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#691]
Atom's test runner uses Jasmine 1.3 which was released in 2012. Unfortunately they can't upgrade this easily since they would break all community packages.

With `nteract` slowly switching to [`jest`](http://facebook.github.io/jest/), I think we should evaluate if switching to `jest` makes sense for Hydrogen too. I recently saw that [`prettier-atom`](https://github.com/prettier/prettier-atom) also uses `jest` for testing despite beeing a Atom package. That's what got me thinking about using it as well.

Here are what I think are the Pros and Cons of `jest` for our use case:

Pros|Cons
---|---
far superior mocking capabilities | we would lose access to the `atom` global and can't use `require('atom')` (unless one writes a [Atom test runner](http://flight-manual.atom.io/hacking-atom/sections/writing-specs/#customizing-your-test-runner), which seams a bit flaky) so we definitely need those mocking capabilities
better support for async tests | more dependencies and initial setup, e.g. we need to set up `babel` for transpiling the tests
more features like snapshots, coverage, test watching, ... | devs need Node and npm installed
new and shiny (very subjective, only "real" benefit: devs may end up writing more tests) | no graphical UI for beginners

`prettier-atom` also has a custom `babel` transpile step, but I don't really see the benefit compared to our current setup, especially since we would need to check in the generated files due to `apm`s packaging system (https://github.com/atom/apm/issues/498)

Just putting this out there since `jest` seams pretty cool but I haven't used it much so I wonder if we would benefit from it despite loosing access to Atom's API.

What do you think?

**Comment by BenRussert** [comment]
Do you know of any other Atom packages using `jest`? Either way I was thinking it might be good to see if we could get a discussion started on the [atom forums.](https://discuss.atom.io) 

Maybe others have tried or have some input on the pros and cons. If we would be "pioneering" this there might be some good feedback on challenges we might face.
