### ISSUE TITLE
Undefined at the end of results when cmd+return on javascript code

### ISSUE THREAD

**Issue by jineshqa** [nteract/hydrogen#699]
**Description:**

Undefined at the end of results when cmd+return on javascript code

**Steps to Reproduce:**

1. Open atom and write a simple JavaScript code
2. Select the code and do cmd+return
3. results would show up with undefined at the bottom. See screenshot
![screen shot 2017-04-05 at 10 35 48 am](https://cloud.githubusercontent.com/assets/9420719/24719185/a3748900-19ed-11e7-8399-d60fd3387f34.png)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Mac   : 10.10.5

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

**Comment by lgeiger** [comment]
That's actually not Hydrogen itself.

You can configure this behavior in IJavascript upon install: http://n-riesco.github.io/ijavascript/

/cc @n-riesco

**Comment by n-riesco** [comment]
@lgeiger +1

@jineshqa If you reinstall the kernel spec for IJavascript using [ijsinstall](https://github.com/n-riesco/ijavascript#ijsinstall-ijavascript-kernel-spec-installer), it will default to hide `undefined` results.

**Comment by jineshqa** [comment]
@n-riesco @lgeiger could you point me to how to install IJavaScript using ijsinstall. I think I messed up my installation. Now I am getting this error after running ijsinstall from terminal.

![screen shot 2017-04-05 at 11 36 34 am](https://cloud.githubusercontent.com/assets/9420719/24721156/3da572ae-19f4-11e7-98e1-547866338e8c.png)

**Comment by n-riesco** [comment]
@jineshqa That looks like a bug in `ijsinstall`. I'll look into late. For the time being, try to run `ijsinstall --spec-path=full`. I haven't tested it, but I reckon it should work.

**Comment by jineshqa** [comment]
@n-riesco That did the trick. Thanks.

**Comment by n-riesco** [comment]
@jineshqa I've just tested `ijsinstall` and it works for me.

Are you using a custom kernel spec?
Could you post the output from running `jupyter kernelspec list --json`?

**Comment by jineshqa** [comment]
{
  "kernelspecs": {
    "javascript": {
      "resource_dir": "/Users/jinesh/Library/Jupyter/kernels/javascript",
      "spec": {
        "argv": [
          "/usr/local/Cellar/node/7.8.0/bin/node",
          "/usr/local/lib/node_modules/ijavascript/lib/kernel.js",
          "--hide-undefined",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "env": {},
        "display_name": "Javascript (Node.js)",
        "language": "javascript"
      }
    },
    "python3": {
      "resource_dir": "/Users/jinesh/Library/Jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/usr/local/opt/python3/bin/python3.6",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}

**Comment by n-riesco** [comment]
@jineshqa OK, that's the kernel spec I'd expect after running `ijsinstall --spec-path=full`?

Could you post the output from running this?

```sh
ijsinstall
jupyter kernelspec list --json
```

**Comment by jineshqa** [comment]
@n-riesco Nothing on running ijsinstall. See output and screenshot below.

```
{
  "kernelspecs": {
    "javascript": {
      "resource_dir": "/Users/jinesh/Library/Jupyter/kernels/javascript",
      "spec": {
        "argv": [
          "ijskernel",
          "--hide-undefined",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "env": {},
        "display_name": "Javascript (Node.js)",
        "language": "javascript"
      }
    },
    "python3": {
      "resource_dir": "/Users/jinesh/Library/Jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/usr/local/opt/python3/bin/python3.6",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}

```

![screen shot 2017-04-05 at 1 41 24 pm](https://cloud.githubusercontent.com/assets/9420719/24726017/b7216938-1a05-11e7-8372-763d2bffb7f7.png)

**Comment by n-riesco** [comment]
@jineshqa That kernel spec should work too. Please, could you test it?

**Comment by jineshqa** [comment]
Sure..what settings do I need to change?

**Comment by n-riesco** [comment]
No need to change the settings in Hydrogen.

If Hydrogen is already running in Atom, you could run the command `Hydrogen: Update Kernels`.

Otherwise, closing and opening Atom should update the list of kernels in Hydrogen.

**Comment by jineshqa** [comment]
@n-riesco OK, it worked just fine. Thank you again for all the help.

**Comment by n-riesco** [comment]
I'm not sure how the kernel spec in your first screenshot got there, but I'm happy to know that now it's working.

**Comment by sAs59** [comment]
What would be the custom kernel specs for _Babel ES6 JavaScript_?

**Comment by n-riesco** [comment]
@sAs59 

```js
{
    "kernelspecs": {
        "babel": {
            "spec": {
                "display_name": "jp-Babel",
                "argv": [
                    "jp-babel-kernel",
                    "--hide-undefined",
                    "--protocol=5.0",
                    "{connection_file}"
                ],
                "language": "Babel ES6 JavaScript"
            }
        }
    }
}
```

**Comment by sAs59** [comment]
@n-riesco How can I add it to the list?

**Comment by n-riesco** [comment]
@sAs59 It goes into Hydrogen's settings (`Settings > Packages > Hydrogen > Settings > Kernel Specs`).

You'll have to restart or run the command `hydrogen:update-kernels` for the changes to take effect.

**Comment by sAs59** [comment]
@n-riesco Thank you. I didn't know that you have a kernel for babel (jp-babel). Installing that kernel fixed my problem. Thanks again!
