### ISSUE TITLE
Failed to activate the Hydrogen package in CentOS

### ISSUE THREAD

**Issue by pashifika** [nteract/hydrogen#70]
[root@localhost src]# find /usr/local/lib -name "libzmq*" -ls
71139350 2628 -rwxr-xr-x   1 root     root      2688101  6月 27 14:34 /usr/local/lib/libzmq.so.3.0.0
71139746    0 lrwxrwxrwx   1 root     root           15  6月 27 14:34 /usr/local/lib/libzmq.so.3 -> libzmq.so.3.0.0

OS: CentOS Linux release 7.1.1503 x64

Error message:
The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 41.0.2272.76 and Node 1.5.1.

The packages listed should now ship versions of these native modules that are compatible with Node 1.5.1.

Updates for these packages may already be available that resolve this issue.

If no update is available you may want to notify the package author that their package isn't supported in Atom 1.0.0 because of the Chrome 41.0.2272.76 and Node 1.5.1 upgrade.

If you think a package is listed here and should no longer be, click the button below to reload Atom and recheck all packages.

---------------------------------------------------------------
Listed below are the incompatible native modules that this package depends on.

zmq@2.11.1
Error message: libzmq.so.3: å±æãªãã¸ã§ã¯ããã¡ã¤ã«ãéãã¾ãã: ãã®ãããªãã¡ã¤ã«ããã£ã¬ã¯ããªã¯ããã¾ãã

**Comment by willwhitney** [comment]
That's not the most useful error message I've seen, haha.

That's the most up-to-date version of the node `zmq` package, and it seems to work on other platforms. Maybe try an `apm rebuild` and see if that clears it up?

**Comment by pashifika** [comment]
[root@localhost src]# yum install zeromq3*
読み込んだプラグイン:fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * base: mirror.fairway.ne.jp
 * centosplus: mirror.fairway.ne.jp
 * epel: ftp.tsukuba.wide.ad.jp
 * extras: mirror.fairway.ne.jp
 * nux-dextop: li.nux.ro
 * rpmforge: mirror.fairway.ne.jp
 * updates: mirror.fairway.ne.jp
パッケージ zeromq3-3.2.5-1.el7.x86_64 はインストール済みか最新バージョンです
パッケージ zeromq3-devel-3.2.5-1.el7.x86_64 はインストール済みか最新バージョンです
何もしません
-----------------------------------------------------------
[pashifika@localhost ~]$ apm rebuild
Rebuilding modules ✓
[pashifika@localhost ~]$ apm list
Built-in Atom packages (88)
├── archive-view@0.58.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.0
├── autocomplete-css@0.8.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.17.4
├── autocomplete-snippets@1.7.0
├── autoflow@0.25.0
├── autosave@0.21.0
├── background-tips@0.25.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.35.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.52.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.25.0
├── find-and-replace@0.174.0
├── fuzzy-finder@0.87.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.33.0
├── language-c@0.45.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.6.0
├── language-css@0.32.0
├── language-gfm@0.77.0
├── language-git@0.10.0
├── language-go@0.27.0
├── language-html@0.40.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.80.0
├── language-json@0.15.0
├── language-less@0.27.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.26.0
├── language-php@0.26.0
├── language-property-list@0.8.0
├── language-python@0.36.0
├── language-ruby@0.56.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.39.0
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.25.0
├── language-toml@0.16.0
├── language-xml@0.30.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.56.0
├── one-dark-syntax@0.7.1
├── one-dark-ui@0.9.1
├── one-light-syntax@0.7.0
├── one-light-ui@0.9.1
├── open-on-github@0.37.0
├── package-generator@0.39.0
├── release-notes@0.53.0
├── settings-view@0.208.0
├── snippets@0.95.0
├── solarized-dark-syntax@0.35.0
├── solarized-light-syntax@0.21.0
├── spell-check@0.59.0
├── status-bar@0.74.0
├── styleguide@0.44.0
├── symbols-view@0.99.0
├── tabs@0.81.0
├── timecop@0.31.0
├── tree-view@0.172.0
├── update-package-dependencies@0.10.0
├── welcome@0.29.0
├── whitespace@0.30.0
└── wrap-guide@0.35.0

/home/pashifika/.atom/packages (11)
├── Hydrogen@0.4.1
├── atom-beautify@0.28.7
├── autocomplete-python@0.5.1
├── file-icons@1.5.8
├── file-templates@0.1.1
├── git-control@0.3.0
├── japanese-menu@0.7.0
├── linter@1.1.0
├── linter-flake8@1.4.2
├── minimap@4.10.1
└── save-session@0.15.6
-------------------------------------------------------------------

zeromq-3.2.5         build&make&install    no work
zeromq-4.0.5         build&make&install    no work
zeromq-4.1.2         build&make&install    no work

**Comment by terraqout** [comment]
@pashifika Did you resolve this issue? Or can you retest?

**Comment by n-riesco** [comment]
@pashifika I'm closing this issue. Please, feel free to reopen it if you need more help.
