### ISSUE TITLE
ImportError: cannot import name constants

### ISSUE THREAD

**Issue by cailmdaley** [nteract/hydrogen#718]
**Description:**

Hydrogen fails to run code. First time submitting an issue, please let me know if I should include any other information! Thanks.

**Steps to Reproduce:**

1. Run any line of code e.g `print(1)`
2. Select Python3

**Versions:**

Atom    : 1.16.0
Electron: 1.3.13
Hydrogen : 1.11.2

### Stack Trace:
**Titled `Python3`:**

```Traceback (most recent call last): File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main "main", fname, loader, pkg_name) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/init.py", line 2, in from .connect import File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/connect.py", line 18, in import jupyter_client File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_client/init.py", line 4, in from .connect import File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_client/connect.py", line 22, in import zmq File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/init.py", line 34, in from zmq import backend File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/init.py", line 40, in reraise(*exc_info) File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/init.py", line 27, in _ns = select_backend(first) File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/select.py", line 26, in select_backend mod = import(name, fromlist=public_api) File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/cython/init.py", line 6, in from . import (constants, error, message, context, ImportError: cannot import name constants```

### Logs

```Hydrogen: Could not enable dev tools Error: Cannot find module 'mobx-react-devtools'(…)
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: findCodeBlock: 0
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: Selected command: Object
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: KernelManager: startKernelFor: python
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: ZMQKernel: @kernelProcess: ChildProcess
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: ZMQKernel: monitor shellSocket
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: ZMQKernel: monitor controlSocket
/Users/cdaley/.atom/packages/Hydrogen/lib/utils.js:96 Hydrogen: ZMQKernel: monitor ioSocket
```

**Comment by n-riesco** [comment]
Could you tun the following and post the output?

```js
which python
jupyter kernelspec list --json
```

**Comment by cailmdaley** [comment]
I found the issue--my python build was corrupted. Thanks!

**Comment by cailmdaley** [comment]
In my case, I think this error was caused by something in the OS X distribution of Python ("/Library/Frameworks/Python..."). I solved this by installing a fresh Python build with Homebrew, and setting it to my default Python. Hope this helps!

**Comment by aazim-lakhani** [comment]
I encountered a similar problem. `pip install --upgrade pyzmq` did the trick for me
