### ISSUE TITLE
Python2/3 Mixup with IPython Kernels?

### ISSUE THREAD

**Issue by dhhagan** [nteract/hydrogen#720]
**Description:**

I just updated hydrogen and hydrogen-launcher to the newest versions and it somehow lost track of my ipython kernel locations?

**Steps to Reproduce:**

When I try to execute code with hydrogen, I get the following error message: 
![screen shot 2017-04-16 at 12 49 38 pm](https://cloud.githubusercontent.com/assets/4370504/25073252/b46d02b6-22b0-11e7-9255-238f2de4f46c.png)

I've always used Hydrogen with Python3.6 and it's worked great..not sure what happened..

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Atom v1.16.0
Hydrogen 1.11.2
Hydrogen-Launcher v1.2.1
OS 10.12.4 (Sierra)

**Logs:**
Nothing appeared in the dev console..just the error message pasted above.

**Comment by dhhagan** [comment]
Hmm. I fixed it by adding another python3 kernel mapping in the optional settings. When I run `jupyter kernelspec list --json` it gives me a python3 mapping that calls python2.7 ..? Not sure why, but changing the first argv to `python3` from `python` fixed it.

**Comment by n-riesco** [comment]
[Here's a link](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) with the instructions to install either the python2 or the python3 kernel with Jupyter. This should work for Hydrogen or any other Jupyter tool (e.g. nteract or the notebook).

The kernel spec setting is more convenient when you want to run both pytthon2 or python3 (Hydrogen will prompt you to choose one on first run).

I'm going to close this issue. Please, feel free to reopen if the instructions above don't work for you.

**Comment by rgbkrk** [comment]
Thank you for reporting this, I've heard others having trouble after the latest ipykernel update within other projects that had similar behavior. I may be able to help fix some other folks' setup.

**Comment by nullsquirrel** [comment]
Had the same issue and was able to resolve per dhhagan's solution above:

> changing the first argv to `python3` from `python` fixed it.

This arg is what specifies which binary to call for the kernel, and on most machines `python` is mapped to 2.7, thus changing this to `python3` actually tells the kernel to use python3.  Rather than making this change in the option settings of the Hydrogen plugin, I found it easiest to edit the kernelspec file... which can be located by running `jupyter kernelspec list`.  For my Mac (using Homebrew), this returned the following:
```
Available kernels:
  python3    /usr/local/share/jupyter/kernels/python3
```

**Comment by mmcguffi** [comment]
This issue still exists, I guess, in 2020 -- but as @dhhagan has stated, `changing the first argv to python3 from python fixed it.` for me, at least
