### ISSUE TITLE
Support language-sage package

### ISSUE THREAD

**Issue by gmd7** [nteract/hydrogen#721]
I can use the sagemath jupyter-kernel with a language mapping {"sagemath":"clojure"}. The atom package language-sage is working. But since sagemath is not a core language I havn't found  a way to get a a language mapping {"sagemath":"sagemath"} working.

**Comment by n-riesco** [comment]
The syntax of `languageMapping` is `{kernelLanguage: atomGrammar}`.

You can find `kernelLanguage` should be for sagemath by looking at the kernel spec installed in your machine. You can get the kernel specs installed in your machine by running:

```sh
jupyter kernelspec list --json
```

The `atomGrammar` is the language Atom thinks your sagemath file is. It should be displayed on the status bar.

**Comment by gmd7** [comment]
It's running in .sage files, but not in markdown:

\```python
3+4*9
\```

is fine.

\```sage
3+4*9
\```

does nothing. Dev-Console shows only:

Hydrogen: findCodeBlock: 1

**Comment by n-riesco** [comment]
Oh, I see. Does replacing `sage` by `closure` work? E.g.

\```closure
3+4*9
\```

**Comment by gmd7** [comment]
```java
diff(x^4,x)
```

with mapping {"sagemath":"java"} works!
