### ISSUE TITLE
SyntaxError when creating multi-line dictionaries

### ISSUE THREAD

**Issue by onewhaleid** [nteract/hydrogen#724]
**Description:**

A SyntaxError (unexpected OEF while parsing) is generated when creating a dictionary with a line break after the opening brace:
![syntaxerror](https://cloud.githubusercontent.com/assets/11261876/25156784/1cf75b16-24e0-11e7-8f70-e53d6c5656bb.png)

The syntax is valid, but Hydrogen will only execute the code properly if all the lines are selected first:
![noerror](https://cloud.githubusercontent.com/assets/11261876/25156760/eefe511a-24df-11e7-9694-5690696a4fcd.png)

**Steps to Reproduce:**

1. Create multi-line dictionary, with a line break after the opening brace.
2. With the cursor on the first line, run the command `Hydrogen:run`.

**Versions:**

`Atom : 1.16.0`
`Electron: 1.3.13`
`Chrome   : 52.0.2743.82`
`Node     : 6.5.0`

**Comment by lgeiger** [comment]
We rely on Atom's [`language-python`](https://github.com/atom/language-python) package to determine code blocks depending on the code folding.

Unfortunately this needs to be fixed in the `language-python` package because Hydrogen is language agnostic. It would be great if you would open a issue there.

**Comment by onewhaleid** [comment]
Interesting. I'll open an issue at `language-python` and `MagicPython`.

Thank you @lgeiger.

**Comment by vpetrovykh** [comment]
I'm a MagicPython developer. Could you be more specific in whether there's a particular scope that's missing or something like that, please?

**Comment by onewhaleid** [comment]
I can reproduce this in an otherwise empty file, so I guess it's in the global scope.

**Comment by vpetrovykh** [comment]
@lgeiger could you please give a little more detail on what information Hydrogen is relying on when determining code block boundaries? Is there some specific name that is given to the code block by the language parser that should be there?

**Comment by nikitakit** [comment]
@vpetrovykh 

To get code block boundaries in a language-portable way, hydrogen relies on Atom's code folding.

So for example here is some code:
<img width="108" alt="screen shot 2017-05-03 at 1 28 49 pm" src="https://cloud.githubusercontent.com/assets/252225/25680102/8c736514-3004-11e7-8d1a-618418570bd7.png">

And here is the same code after running the "Editor: Fold All" command
<img width="93" alt="screen shot 2017-05-03 at 1 29 00 pm" src="https://cloud.githubusercontent.com/assets/252225/25680106/8ee960dc-3004-11e7-8368-b8674b1a93c2.png">

Hydrogen considers the block to range from the start of the current line to the end of the folded section, which misses the closing `}` delimiter.

Also if as a MagicPython developer you know a more targeted way of getting block information that is commonly supported by Atom grammars, please let us know.

**Comment by vpetrovykh** [comment]
@lgeiger considering that Atom seems to have an known issue with code folding (e.g.  https://github.com/atom/first-mate/issues/48 and https://github.com/atom/atom/issues/1183) would it be viable for Hydrogen to try and check for some special syntax scope (e.g. `meta.foldable...` or maybe rely on some existing `meta...` scopes) and if present use it to fold the all contents marked by that scope. In case the scope is not present you could fall back on generic code-folding.

**Comment by lgeiger** [comment]
@vpetrovykh That's a good idea! We're very happy to accept a PR for this.

**Comment by kylebarron** [comment]
There's actually a setting named `foldEndPattern` that fixes this from the grammar side. Creating PRs for both language-python and MagicPython now.
