### ISSUE TITLE
Run All command doesn't work with PHP

### ISSUE THREAD

**Issue by AustP** [nteract/hydrogen#726]
**Description:**

After installing Jupyter and a PHP kernel, I ran a snippet of PHP code and it worked. Then I tried to run my whole file with `Run All` and I get the following error:

> PHP Parse error: Syntax error, unexpected '<' on line 1

This is of course because all PHP files start with `<?php` or `<?` and the actual PHP code follows after. The PHP tag should not be passed to the kernel for execution.

**Steps to Reproduce:**

1. With a PHP Jupyter kernel installed, execute the `Run All` command from a PHP script.

**Versions:**

OS: Xubuntu 16.04 LTS
Atom: 1.16.0
Hydrogen: 1.11.2

**Comment by rgbkrk** [comment]
Would it be appropriate for the PHP kernel to handle this by ignoring a `<?php` or `<?`? Then users could also copy paste whole snippets into other Jupyter environments as well. Which PHP kernel are you using?

**Comment by AustP** [comment]
Good question, I don't really know. I installed all of this Jupyter stuff to use your plugin. It might be more appropriate for the PHP kernel to handle it. The one I used was https://github.com/Litipk/Jupyter-PHP

**Comment by rgbkrk** [comment]
Great, thanks for reporting. We should definitely improve the UX there. I filed an issue on https://github.com/Litipk/Jupyter-PHP/issues/18.

**Comment by castarco** [comment]
Hi there, I'm the "maintainer" of the PHP kernel (when I find time...). As far as I know, using `<?php` is required to enable the pygments highlighting, but there is a trick that allows keeping the syntax highlighting without crashing the kernel, writing:
```php
// <?php
```

instead of 

```php
<?php
```

**Comment by AustP** [comment]
Thanks for the workaround. I'll close this issue in favor of the other one.
