### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/do...

### ISSUE THREAD

**Issue by ahsen1402** [nteract/hydrogen#734]
Hi Lukas,

Thanks for the great help. This is not so crucial but technically with irkernel one is able to run ggplot2 but in hydrogen i got this error.

```
Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
events.js:160
Hide Stack Trace
Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/instantiateReactComponent.js:74:250)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactCompositeComponent.js:367:22)
    at ReactCompositeComponentWrapper.mountComponent (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at mountComponentIntoNode (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactMount.js:104:32)
    at ReactReconcileTransaction.perform (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/Transaction.js:140:20)
    at batchedMountComponentIntoNode (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactMount.js:126:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at Object._renderNewRootComponent (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactMount.js:320:18)
    at Object._renderSubtreeIntoContainer (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactMount.js:401:32)
    at Object.render (/Users/mea/.atom/packages/Hydrogen/node_modules/react-dom/lib/ReactMount.js:422:23)
    at ResultView.addResult (/Users/mea/.atom/packages/Hydrogen/lib/result-view.js:193:14)
    at /Users/mea/.atom/packages/Hydrogen/lib/main.js:273:12
    at ZMQKernel.onIOMessage (/Users/mea/.atom/packages/Hydrogen/lib/zmq-kernel.js:355:7)
    at Socket.<anonymous> (/Users/mea/.atom/packages/Hydrogen/node_modules/jmp/index.js:347:17)
    at emitMany (events.js:127:13)
    at Socket.emit (events.js:201:7)
    at Socket._emitMessage (/Users/mea/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:631:15)
    at Socket._flushRead (/Users/mea/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:642:10)
    at Socket._flushReads (/Users/mea/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:678:15)
    at _zmq.onReadReady (/Users/mea/.atom/packages/Hydro
```

**Comment by lgeiger** [comment]
Could you post the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md)?

**Comment by ahsen1402** [comment]
here it is thanks,

Hydrogen: Could not enable dev tools Error: Cannot find module 'mobx-react-devtools'(…)
utils.js [sm]:75 Hydrogen: findCodeBlock: 16
utils.js [sm]:75 Hydrogen: KernelManager: startKernelFor: r
utils.js [sm]:75 Hydrogen: ZMQKernel: @kernelProcess: ChildProcess {domain: null, _events: EventHandlers, _eventsCount: 0, _maxListeners: undefined, _closesNeeded: 3…}
utils.js [sm]:75 Hydrogen: ZMQKernel: monitor shellSocket
utils.js [sm]:75 Hydrogen: ZMQKernel: monitor controlSocket
utils.js [sm]:75 Hydrogen: ZMQKernel: monitor ioSocket
utils.js [sm]:75 Hydrogen: ZMQKernel: controlSocket connected
utils.js [sm]:75 Hydrogen: ZMQKernel: shellSocket connected
utils.js [sm]:75 Hydrogen: ZMQKernel: ioSocket connected
utils.js [sm]:75 Hydrogen: ZMQKernel: all main sockets connected
utils.js [sm]:75 Hydrogen: KernelManager: startKernelFor: kernel for r connected
utils.js [sm]:75 Hydrogen: clearBubblesOnRow: 16
utils.js [sm]:75 Hydrogen: Kernel.execute: x=14
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: ResultView: Show status container
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: findCodeBlock: 17
utils.js [sm]:75 Hydrogen: clearBubblesOnRow: 17
utils.js [sm]:75 Hydrogen: Kernel.execute: x=matrix(0,3,5)
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: ResultView: Show status container
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: findCodeBlock: 18
utils.js [sm]:75 Hydrogen: clearBubblesOnRow: 18
utils.js [sm]:75 Hydrogen: Kernel.execute: library(ggplot2)
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: ResultView: Show status container
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: findCodeBlock: 19
utils.js [sm]:75 Hydrogen: clearBubblesOnRow: 19
utils.js [sm]:75 Hydrogen: Kernel.execute: qplot(1:3,2:4)
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: ResultView: Add result Object {data: Object, stream: "pyout"}
utils.js [sm]:75 Hydrogen: ResultView: Hide status container
events.js:160 Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.reactProdInvariant @ reactProdInvariant.js:31instantiateReactComponent @ instantiateReactComponent.js:74performInitialMount @ ReactCompositeComponent.js:367mountComponent @ ReactCompositeComponent.js:258mountComponent @ ReactReconciler.js:46mountComponentIntoNode @ ReactMount.js:104perform @ Transaction.js:140batchedMountComponentIntoNode @ ReactMount.js:126perform @ Transaction.js:140batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:97_renderNewRootComponent @ ReactMount.js:320_renderSubtreeIntoContainer @ ReactMount.js:401render @ ReactMount.js:422addResult @ result-view.js [sm]:193(anonymous function) @ main.js [sm]:273onIOMessage @ zmq-kernel.js [sm]:355(anonymous function) @ index.js:347emitMany @ events.js:127emit @ events.js:201Socket._emitMessage @ index.js:631Socket._flushRead @ index.js:642Socket._flushReads @ index.js:678_zmq.onReadReady @ index.js:297

**Comment by lgeiger** [comment]
Thanks. It would be helpful if you could expand the content of the following logs and post a screenshot:
```
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:75 Hydrogen: ResultView: Add result Object {data: Object, stream: "pyout"}
```

**Comment by n-riesco** [comment]
@lgeiger I think the problem is that [richestMimetype](https://github.com/nteract/hydrogen/blob/7fc352c8e638be19a24f6714fd9529721f2cef52/lib/result-view.js#L183) can return `undefined`.

**Comment by lgeiger** [comment]
This should only happen if the kernel doesn't fully adhere to the messaging standard.

From the [messaging docs](https://jupyter-client.readthedocs.io/en/latest/messaging.html#id6):
> A plain text representation should always be provided in the `text/plain` mime-type.

**Comment by n-riesco** [comment]
There is also the possibility that a kernel sends a `display_data` message that `transforms` can't handle.

This is just a guess (before @ahsen1402 replies), but I reckon we should guard against `undefined` anyway.

**Comment by lgeiger** [comment]
> I reckon we should guard against undefined anyway.

💯 👍

**Comment by ahsen1402** [comment]
hi guys i will reply once i get back to work, i am in a brief holiday. I agree with @n-riesco  as the ggplot2 package is a visualization package that does some plots. Do you guys have the irkernek installed? Why dont you just try this simple command
```
library(ggplot2)
qplot(1:3,2:4)
```
if you see a plot after this then there is something wrong on my side. But if you see the same error then maybe it is easy for you to debug?

**Comment by rgbkrk** [comment]
I get the same error. For non-R developers, you can install `ggplot2` with a fresh R kernel using:

```
install.packages("ggplot2")
```

**Comment by rgbkrk** [comment]
Side note -- this does work in the nteract desktop app:

![screen shot 2017-04-24 at 9 19 37 pm](https://cloud.githubusercontent.com/assets/836375/25368762/c6a3bd1a-2933-11e7-8f71-106a0394a8e7.png)

**Comment by rgbkrk** [comment]
I expanded those messages and this is just plain weird.

![screen shot 2017-04-24 at 9 21 45 pm](https://cloud.githubusercontent.com/assets/836375/25368808/15a78f90-2934-11e7-9728-cebc302240dc.png)

The `data` field on the `content` for the `display_data` message is an empty object.

**Comment by rgbkrk** [comment]
The expected payload from ggplot / irkernel is `{ "text/plain": "plot without title", "image/png": bigOldBase64Blob}`.

Oh wait, now I see it.

```json
    {
      "cell_type": "code",
      "source": [
        "qplot(1:3, 2:4)"
      ],
      "outputs": [
        {
          "output_type": "display_data",
          "data": {}, // Look it's empty!
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "plot without title"
            ],
            "image/png": [
```
