### ISSUE TITLE
execute whole file with one command

### ISSUE THREAD

**Issue by radix** [nteract/hydrogen#74]
I often forget to run blocks of code that are higher up in a file, and it's tedious to navigate to each one or even to select-all and then run hydrogen. It'd be useful to have a single command that automatically executes the whole file.

**Comment by willwhitney** [comment]
Yup, sounds good.

**Comment by rgbkrk** [comment]
:+1: That's the behavior I love in Atom Script.

**Comment by onyxfish** [comment]
Or, "run to selected line". This is the behavior I expected when I initially ⌘-⌥-↩ and hadn't executed lines above.

**Comment by lgeiger** [comment]
https://github.com/nteract/hydrogen/pull/164
