### ISSUE TITLE
Hydrogen violates CSP in  Atom 1.17.0-beta3

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#747]
**Description:**

Tests fail with `EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`.

**Versions:**

```
Using Atom version:
Atom    : 1.17.0-beta3
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
Using APM version:
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.3
git 1.8.5.6
```

**Logs:**

See Travis failure [here](https://travis-ci.org/nteract/hydrogen/builds/225036478)

**Comment by lgeiger** [comment]
I can reproduce this locally on a fresh install. I reported it on https://github.com/UziTech/atom-jasmine2-test-runner/issues/14.

If the issue persists we should revert #713.

**Comment by rodrigob** [comment]
I have the same problem when using
%matplotlib notebook

what is the suggested solution ?
