### ISSUE TITLE
Allow links to subsections in the gitbook

### ISSUE THREAD

**Issue by n-riesco** [nteract/hydrogen#754]
Today I wanted to link to the subsection `Multiple kernels inside one rich document` and I couldn't/didn't know how.

Is there a way to tell gitbooks to generate links for those subsections?

**Comment by lgeiger** [comment]
You want to link to it from an external site?

I'll take a look how to make this possible.

**Comment by n-riesco** [comment]
> You want to link to it from an external site?

In this case, it was an email.
I just wanted to show that Hydrogen can run multiple kernels for a markdown file.
