### ISSUE TITLE
eslint/prettier rules

### ISSUE THREAD

**Issue by BenRussert** [nteract/hydrogen#756]
I noticed we don't have [`no-undef`](http://eslint.org/docs/rules/no-undef) enabled, anyone opposed to adding this to .eslintrc.yml?

There may be some other useful rules missing, we could add another `extends` to our imported rules. Currently we import: [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier/blob/master/index.js).

**Comment by rgbkrk** [comment]
One cool thing about using flow (and making sure to increase flow coverage) is that you'll be alerted to when you use variables that can potentially be undefined. I've been going with less eslint rules and making the flow use more strict over time. Just food for thought.

**Comment by BenRussert** [comment]
Probably the better way to go at this point.
