### ISSUE TITLE
Unable to update to Hydogen 1.12.1

### ISSUE THREAD

**Issue by Bernalms** [nteract/hydrogen#759]
a) I think I have a permissions problem. Are updates run through the same user that opens atom or do they run as guest, root, other system process, etc?
a.2)I say this although I know as well that Ubuntu 14.04 has support no more. Unfortunately this is an institutional account and I have no control of OS as in terms of full upgrades.
b) I am attempting forcing the updates know but I know that this is risky so there should be more insight in to how handle issues like this in Ubuntu... any ideas?

thank you!
Bernal

**Description:**

[Description of the issue]

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Ubuntu 14.04
Atom 1.16.0X64
You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**
/tmp/apm-install-dir-117329-18533-cy0o1v.kshevobt9
└── (empty)

npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/1.2.7/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/es5-ext/0.10.15/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/lodash/4.17.4/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/2.4.1/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/1.2.7/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/lodash/4.17.4/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/es5-ext/0.10.15/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/2.4.1/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/1.2.7/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/es5-ext/0.10.15/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/2.4.1/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/lodash/4.17.4/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/1.2.7/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/es5-ext/0.10.15/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/1.2.7/package.tgz
npm ERR! tar.unpack untar error /home/bmanzani/.atom/.apm/core-js/2.4.1/package.tgz
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117329-18533-cy0o1v.kshevobt9/package.json'
npm WARN apm-install-dir-117329-18533-cy0o1v.kshevobt9 No description
npm WARN apm-install-dir-117329-18533-cy0o1v.kshevobt9 No repository field.
npm WARN apm-install-dir-117329-18533-cy0o1v.kshevobt9 No README data
npm WARN apm-install-dir-117329-18533-cy0o1v.kshevobt9 No license field.
npm ERR! Linux 3.13.0-117-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bmanzani/.atom/.apm/.apmrc" "--userconfig" "/home/bmanzani/.atom/.apmrc" "install" "/tmp/d-117329-18533-1hser3.8elxj62yb9/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall write

npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117329-18533-cy0o1v.kshevobt9/npm-debug.log
npm ERR! code 1

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by lgeiger** [comment]
The logs suggest you don't have enough disk space on the machine to update.

`apm` heavily uses the temp directory `/tmp/` to do its installs. Have you checked that your system  (especially the temp dir) has enough space left?

**Comment by BenRussert** [comment]
@Bernalms have you had any progress with this issue? I agree it looks like your `/tmp/` directory needs to be cleaned up to make space.
