### ISSUE TITLE
Output disappears when hitting enter/return/newline

### ISSUE THREAD

**Issue by radix** [nteract/hydrogen#76]
It seems that in general Hydrogen will keep output in place when you modify the line that you've just evaluated. For example,

```python
foo(3)  #output here
```
if you edit this to say `foo(2)` after evaluating it, the "#output here" will stay in place. You can even insert many more characters and the output will flow along to the right. But if you hit enter to go to the next line, it disappears. I try to remember to hit enter *before* evaluating, but it's difficult.

This would help screencasting go better :)

**Comment by willwhitney** [comment]
Currently I insert a marker at the end of the line, and when the marker gets changed, I remove it. This makes evaluating partial lines work well, but I'm not wedded to it.

What would be a better behavior for you?

**Comment by YoungxHelsinki** [comment]
I think hitting an 'esc' key would be a better choice? 

From time to time you get a really long line of return value and it's hard to close that result box. 
It's quite annoying to enter newline and hit backspace to remove the newline just to remove the output. 

Though 'esc' key might collide with other behaviors :\

**Comment by radix** [comment]
@YoungxHelsinki I think you may be misunderstanding the intent of my bug. I'm saying that I _don't_ want the output to disappear, but it does when I press enter. FWIW there's a keypress, cmd-alt-backspace, that removes all output from the current buffer.

@willwhitney I have no idea about the implementation details; I don't know anything about the internal model for atom buffers. I just think that if I hit enter after running a line, the output shouldn't disappear. Would it perhaps be feasible to put the secret marker at the beginning of the line instead of the end?

**Comment by willwhitney** [comment]
I can definitely make it stick around, I'm just looking for the best behavior (regardless of implementation) for you. Do you still want to be able to close a single inline result without closing all of them? Or is that totally unnecessary?

Making `esc` clear the results on the line might be a good option. I'll have to figure out if that breaks anything else.

@YoungxHelsinki you can also use the shortcut to remove all results (default `ctrl-alt-backspace`), but I understand you may want to clear only one of them.

**Comment by radix** [comment]
@willwhitney I guess it would be nice to clear individual results too. There are "x" icons to close on multi-line output, what about having the same for result bubbles? I guess a keystroke for "clear output on current line" could also be useful.

**Comment by ssfrr** [comment]
Adding a keymap-able command to clear the output from the current line would be really useful. I usually don' t need the output from the pop-up for very long after first seeing it, so I almost always end up clicking the 'X' with the mouse after reviewing the contents.

Also more on-topic for the original post, I agree that adding a new line below the current line shouldn't clear the output on that line. It feels unexpected when it happens.

**Comment by n-riesco** [comment]
I've tried to address this issue [here](https://github.com/n-riesco/hydrogen/tree/issue-76-bubble-removed-after-enter).

The idea is to move the cursor down automatically after showing the output.

If there are no lines after the executed code, then a new line is inserted.

If you like this behaviour, I will submit a PR.

**Comment by willwhitney** [comment]
@n-riesco that's a reasonable thing to do. You should probably only move the cursor down if it's on a line included in the code block being executed — Hydrogen also finds the first code block above the cursor, so this could result in unexpected behavior otherwise. Also should take into account the case of executing a selection that doesn't cover the whole line.

Maybe another improvement relevant to this is to use the presence of the output bubble as a clean/dirty indicator on the code that generated it. That is, have the output bubble associated with the region of the buffer that was sent to the kernel for execution, and when that region changes, remove the bubble.

**Comment by n-riesco** [comment]
On 02/09/15 16:27, Will Whitney wrote:
> You should probably only move the cursor down if it's on a line included in the code block being executed

OK, I will fix that.

> Also should take into account the case of executing a selection that doesn't cover the whole line.

How do you mean?

---

Here's an alternative idea (inspired by the jupyter notebook):

- [shit-alt-enter] to run a code block (current behaviour)
- [ctrl-alt-enter] to run a code block and move one line down

**Comment by willwhitney** [comment]
Like this:

<img width="238" alt="screenshot 2015-09-02 12 23 45" src="https://cloud.githubusercontent.com/assets/597829/9637214/7c42b7de-516d-11e5-922c-1ca4c7403e44.png">

If some text is selected when Hydrogen is run, it will execute exactly and only that text. So you don't want to move the cursor when they've selected `seventy` in the above example.

> - [shift-alt-enter] to run a code block (current behaviour)
> - [ctrl-alt-enter] to run a code block and move one line down

That's a great idea. I'd merge that PR.

**Comment by n-riesco** [comment]
OK, now I get it.

Let me sum up what the PR would do (please, correct me if I'm wrong):

- bind [shift-alt-enter] to the current behaviour

- for [ctrl-alt-enter], I can see 4 cases:

  1.1 (no text selected, cursor not on the last row) => execute code and move down

  1.2 (no text selected, cursor on the last row) => insert line, move down, and execute code

  2.1 (text selected, cursor not on the last row) => execute code and move down

  2.2 (text selected, cursor on the last row) => execute code, move down and insert line

**Comment by willwhitney** [comment]
We should include the possibility that the cursor is on the line below the code block:

<img width="380" alt="screenshot 2015-09-02 13 02 11" src="https://cloud.githubusercontent.com/assets/597829/9638137/d9310acc-5172-11e5-8adc-2a0ea0099f31.png">

Then the possibilities look like this:

```
(no text selected)
    (cursor within code block)
        (cursor not on last row) => execute and move down
        (cursor on last row) => execute code, move down and insert line
    (cursor below code block) => execute and do not move
(text selected)
    (cursor not on the last row) => execute code and move down
    (cursor on the last row) => execute code, move down and insert line
```

Does that make sense?

**Comment by n-riesco** [comment]
Yes, it does (again, I had forgotten about the case 'cursor below code block'!).

I'll give this PR a go.

**Comment by willwhitney** [comment]
Great!
