### ISSUE TITLE
local server connection override remote configuration

### ISSUE THREAD

**Issue by epifanio** [nteract/hydrogen#770]
Maybe a duplicate of https://github.com/nteract/hydrogen/issues/243

I'm trying to connect *Atom* editor to a remote Jupyter kernel.

Those are the steps I followed on a fresh OS X system:

* Install homebrew `python3` 
* Install `Jupiter notebook` via `pip` in a virtual environment
* Download and install `Atom 1.17.0-beta5`

* On the remote server:
```
pip3.6 install jupyter_kernel_gateway
jupyter kernelgateway --ip="*"
```

* Run `atom-beta` from the bash shell where I activated my `python virtualenv`

Below my `hydrogen` configuration In Atom:

 * `Kernel Gateways`:

```
[{
    "name": "Remote Notebook", 
    "options": { "baseUrl": "my.domain:8890" } 
}]
```

 * `kernel specs I used the output of `jupiter kernel spec list --json` from the remote server [gist](https://gist.github.com/c5825647c22456c5f483cb933de4121f) 

 * `language mapping`: 

`{"python3": "python"}`

In atom, from the editor toolbar i select: `Packages -> Hydrogen -> Connect to remote Kernel` 
no errors.

Testing:

in atom: `connect to remote kernel` then `run all` on this simple code:

```
import sys
print(sys.executable)
```

give me the following output:

```
/Users/epi/Envs/jupyter/bin/python
```

It shows the local python executable, which means I'm not using the remote jupyter kernel.

I guess I'm missing some fundamentals of how the `kernel gateways` and `hydrogen` works. 
Have you any clue on what I'm missing?

**Comment by lgeiger** [comment]
That's interesting. Can you check that you're connected to the remote kernel after running `Packages -> Hydrogen -> Connect to remote Kernel`? You can see this by looking at the kernel indicator in status bar.
If not `run all` would start a new local kernel per default.

@nikitakit Any ideas?

Sidenote: The mapping `{"python3": "python"}` isn't necessary for python.

**Comment by nikitakit** [comment]
@epifanio What options did you select in the menus shown by "Connect to remote Kernel"? If you don't follow the menus far enough you won't actually connect to a kernel.

**Comment by BenRussert** [comment]
@epifanio have you had any progress with this? I'll probably close this in a couple days, but we would be happy to help if you are still interested.

**Comment by epifanio** [comment]
@BenRussert I'll test it in the next hours and report here, thanks!

**Comment by epifanio** [comment]
it seems that when I tried the first time it failed to connect to the remote kernel and started one locally, thanks @nikitakit for the pointer. 

Now trying to connect to my gateway which was running on `my.domain:8888` 
Enabling the js console and looking at the shell output i saw a "forbidden" message:

```
[I 170614 05:11:47 web:2063] 200 GET /api/kernelspecs?1497409907075 (73.61.89.80) 388.24ms
[W 170614 05:11:48 web:1587] 403 GET /api/sessions?1497409908025 (73.61.89.80): Forbidden
[W 170614 05:11:48 web:2063] 403 GET /api/sessions?1497409908025 (73.61.89.80) 1.25ms
[I 170614 05:13:24 web:2063] 200 GET /api/kernelspecs?1497410004188 (73.61.89.80) 5.41ms
[W 170614 05:13:25 web:1587] 403 GET /api/sessions?1497410004656 (73.61.89.80): Forbidden
[W 170614 05:13:25 web:2063] 403 GET /api/sessions?1497410004656 (73.61.89.80) 1.10ms
```

I changed the way how I run the gteway to:

```
jupyter kernelgateway --ip="*" --certfile='/etc/letsencrypt/live/my.domain/fullchain.pem' --keyfile='/etc/letsencrypt/live/my.domain/privkey.pem'
```

and in the hydrogen settings I used:

```
[{"name": "Remote Notebook", 
  "options": { "baseUrl": "https://my.domain:8888" } 
  }
]
```

I left all the other fields as default.
After those changes It now works :)

Thanks!!!
