### ISSUE TITLE
[Feature Request] Auto Scroll

### ISSUE THREAD

**Issue by lr1100** [nteract/hydrogen#774]
When you run a block of code that has a lot of output, it would be awesome if the inline window would auto-scroll to the bottom with a button on the inline window that would toggle auto-scroll on or off (next to the copy to clip board and open in editor buttons).

**Comment by lgeiger** [comment]
Great idea! Do you think we should make auto-scroll the default?

**Comment by lr1100** [comment]
I am just a lonely guy, but for me I would love it as the default. 
I was running some RNN code and was desiring it to act more like a terminal in the sense of any new output was always displayed.

**Comment by BenRussert** [comment]
I think it would be intuitive to have `hydrogen:run-and-move-down` auto scroll and to leave `hydrogen:run` as is.

**Comment by lgeiger** [comment]
> I think it would be intuitive to have hydrogen:run-and-move-down auto scroll and to leave hydrogen:run as is.

We're only talking about scrolling inside of the output view and not scrolling inside the editor. I don't think the behavior should differ between the commands.

A button to toggle this behavior sounds good to me! A setting for the default would be cool as well.

@lr1100 Would you be interested in implementing this and doing a PR? We're happy to help!

**Comment by lgeiger** [comment]
Looks like there are a few possible solutions of doing this: http://stackoverflow.com/questions/37620694/how-to-scroll-to-bottom-in-react

**Comment by JGH1000** [comment]
I think it would be a great idea to have this as a default (with option to turn off for people who do not want it). I think in 95% of the cases the interesting bits are at the bottom.

**Comment by lgeiger** [comment]
> I think it would be a great idea to have this as a default (with option to turn off for people who do not want it). I think in 95% of the cases the interesting bits are at the bottom.

👍 Sounds good! A global config setting would also be the simplest to implement.

@JGH1000 Are you interested in doing a PR to fix this issue? We're very happy to help.

**Comment by JGH1000** [comment]
@lgeiger I am afraid I can't be of much help since I do not know anything about JavaScript or any web-related technologies. Will try to pick it up at some point so I can start contributing.
