### ISSUE TITLE
Exporting list to csv - not all lines are exported

### ISSUE THREAD

**Issue by frahlg** [nteract/hydrogen#786]
**Description:**

When exporting a list to a csv-file using a for-loop it exports only the first 799 lines of 934. I had a very hard time understanding why, and still does not. It works when running the Python-file from either Sublime Text or the command prompt.
**Steps to Reproduce:**

1. [First Step]

```
import pandas as pd
import numpy as np

data_path = '/Users/fredde/Database/'
df_load = pd.read_hdf(data_path + 'all_data_1year_comp.h5','table')

df_load.head()
list(df_load)
```
**In the console it shows a list of length 934**

```
headers = open(data_path + 'headers.csv','w')
a = list(df_load)
n = 0
for item in a:
    n = n+1
    headers.write('\n' + item + 'loop nr :' + str(n))

```
**It only exports the first 799 lines to the csv-file when running within Atom and Hydrogen. If I run the exact same file from CL or Sublime Text it gives the correct result.**

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Atom 1.1.17 and Hydrogen 1.13.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

There are no error messages.

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by buyology** [comment]
Do you have an actual input file to reproduce? 

(btws: 
a) you should close the file `headers.close()` after your loop if you are not doing that already, 
b) as you are are dealing with pandas `DataFrame`s, have you considered using `to_csv`?)

**Comment by frahlg** [comment]
I cannot share the actual database-file as it is under NDA. As I only want to export the headers for post processing and the most straight forward way is to make a list.

I did not do a `headers.close()`, and now when I do it works just as intended! Thank you!

In some way Hydrogen behaves different than Sublime Text or just the CLI interpreter, even if I did not close the file as I should.
