### ISSUE TITLE
Add more examples on how to use Hydrogen

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#787]
We started a collection of examples in our documentation: https://nteract.gitbooks.io/hydrogen/docs/Usage/Examples.html

It would be really cool if we could add more for other languages and kernels.

Add more examples by [editing this file](https://github.com/nteract/hydrogen/edit/master/docs/Usage/Examples.md).

Read our [Contributing Guide](https://github.com/nteract/hydrogen/blob/master/CONTRIBUTING.md) on how to locally build the documentation website to get a preview.

**Comment by jailsonfm** [comment]
I would like to have an example how to use hydrogen for R data analysis.
For python everything works perfectly like by using Jupyter, but for R I dont how to have the inline output and plots. Thanks Jai
