### ISSUE TITLE
Running R with hydrogen - examples

### ISSUE THREAD

**Issue by jailsonfm** [nteract/hydrogen#791]
Hi everybody,
I am very happy with the possibility to work with python in Atom by using the package hydrogen, especially because I can have the output, **including plots inside the working page (inline results). However, when I try to do the same with R I cannot get the same output experience**. 
I looked extensively for supports and examples but I didn't find anything. 
Appreciate any help. Thanks Jai

**Comment by buyology** [comment]
Have you installed the [R kernel](https://irkernel.github.io/)? Are you seeing any errors?
Can you provide more insight into your environment?

**Comment by jailsonfm** [comment]
Yes. After an extensive survey through several forums I finally figured out how to install rkernel. I can use both python and R in Jupyter but not in atom with hydrogen package. Atom recognizes both .R and .py but both can't run now.
Thank you for your kind attention Buyology!

**Comment by buyology** [comment]
Can you give some more details? Are you seeing errors of some sort?

**Comment by BenRussert** [comment]
@jailsonfm The other thing you will need to do is install [language-r](https://atom.io/packages/language-r)

**Comment by lgeiger** [comment]
> The other thing you will need to do is install language-r

👍  We should add this hint to our documentation or the troubleshooting page.

**Comment by jailsonfm** [comment]
Thanks to all. I installed the language-r and now it works fine!

**Comment by lgeiger** [comment]
Cool! Opened #803 to document this.
