### ISSUE TITLE
Use Atoms Docks API for our panels

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#795]
Atom 1.17 introduced a new docks API (Used by the [tree view](https://github.com/atom/tree-view), [GitHub](https://github.com/atom/github) and [Linter](https://github.com/steelbrain/linter-ui-default) packages).
We should use it as well. This will allow us better work in conjunction with other packages and makes our panels more flexible.

- [ ] **Inspector**
We should do this first since it's simpler to implement with less refactorings and we can get rid `react-resizable-box` then.
- [ ] **Watch Sidebar**

**Relevent resources:**
* http://blog.atom.io/2017/05/16/atom-1-17.html
* http://flight-manual.atom.io/hacking-atom/sections/package-active-editor-info/
* https://atom.io/docs/api/v1.17.0/Dock

**Example PRs from other projects:**
* https://github.com/atom/tree-view/pull/1056
* https://github.com/steelbrain/linter-ui-default/pull/256 and https://github.com/steelbrain/linter-ui-default/pull/302
* https://github.com/atom/github/pull/664

**Comment by BenRussert** [comment]
I will start working on this issue. I think we should ship a release before we finish this due to the atom v1.17 dependency. This way holdouts can still get the new result and watch-views!

**Comment by lgeiger** [comment]
Even more information on the Atom blog: http://blog.atom.io/2017/05/23/docks-deep-dive.html

**Comment by lgeiger** [comment]
I refactored the Watch Sidebar as a react component so we can easily use it in a dock.
@BenRussert I'd happy to pair with you in the next few days and move our panels to docks.
