### ISSUE TITLE
Hide open in editor button

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#797]
I often find the ["open in editor"](https://github.com/nteract/hydrogen/blob/master/lib/components/result-view/result-view.js#L122) button isn't useful enough to have this prominent placement.

What do think about moving the functionality to `cmd` clicking the "copy to clipboard" button? We could change the icon on hover if `cmd/ctrl` is pressed.

**Comment by BenRussert** [comment]
This is a great idea. I can take this one.

I'll push some WIP later. Just need to add the add the class change on ctrl+hover (which will make this a lot nicer I think).

**Comment by lgeiger** [comment]
Closed by #941
