### ISSUE TITLE
incorrect cursor_pos for non-BMP characters in Jupyter protocol

### ISSUE THREAD

**Issue by stevengj** [nteract/hydrogen#807]
It looks like you need an adjustment identical to jupyter/notebook#2509 to correctly report cursor positions for non-BMP Unicode characters (surrogate pairs) in completion and tooltip requests.

**Comment by stevengj** [comment]
@wadethestealth, where is the commit that closes this?  It has nothing to do with #975 — this issue is not about the display width of glyphs, it is about character offsets in UTF-16 for the Jupyter protocol.

**Comment by wadethestealth** [comment]
Apologies, I misunderstood. I thought it was related. There we quite a few issues left open even after a fix, so I was trying to just clean up issues

**Comment by stevengj** [comment]
As I understand it, it was fixed in nteract itself by nteract/nteract#1706.   If Hydrogen uses nteract to talk with Jupyter, maybe that resolves the issue for you as well?

**Comment by wadethestealth** [comment]
I apologize I have basically 0 understanding of what this issue means, do you have a test case for hydrogen that shows the bad behavior? @stevengj

**Comment by stevengj** [comment]
Detailed explanation and test case in https://github.com/jupyter/jupyter_client/issues/259

**Comment by stevengj** [comment]
In particular, if you try to tab complete `𝐚𝐚𝐚𝐚𝐚`, it sends `cursor_pos=10` instead of 5 (there are 5 characters, but JavaScript represents it via 10 UTF-16 code units). 

The fix is similar to the one in the Jupyter PR linked above: adjust `cursor_pos` and similar by 1 for every surrogate codepoint in the string up to that index.

**Comment by wadethestealth** [comment]
Ok I have replicated it and inspected our code. It seems like our problem is that we are using atom's buffer position instead we should be using screen position. At least I believe this should fix it.

**Comment by stevengj** [comment]
No, screen position is probably also incorrect, since the screen position probably counts graphemes.   (For example, `û` is actually two Unicode characters, even though it occupies only one cell on the screen.)

When *sending* a buffer position, you really need to take the buffer position and convert it to a character count by subtracting the number of surrogate codepoints up to that buffer position.  And you need to do the opposite conversion for buffer positions that you *receive*.

See the implementation in the Jupyter notebook here: https://github.com/jupyter/notebook/blob/6174498ab0c4047aaed81a1bb5aa71b1fd8c842b/notebook/static/base/js/utils.js#L1093-L1128 … it's a pretty simple computation.

**Comment by stevengj** [comment]
[This page](http://utf8everywhere.org/#characters) has a good explanation of the difference between codepoints, codeunits, graphemes, and glyphs.     The atom buffer position (what you are using) is in codeunits, whereas what the Jupyter protocol expects is codepoints.

**Comment by wadethestealth** [comment]
@stevengj yeah you are correct also thanks for the resources. I was just hoping there was something built in, but yes your links seem to be the best solution here

**Comment by wadethestealth** [comment]
@stevengj I believe #1658 should be all the areas where we deal with cursor positions relating to kernels

**Comment by williamstein** [comment]
Thanks for this discussion.  The example involving 𝐚𝐚𝐚𝐚𝐚 is a bit confusing!  E.g., if you type 𝐚𝐚𝐚𝐚𝐚=10 in the python3 or ipython3 command line, then do `𝐚𝐚[tab key]` we get no completions at all.   With `aa[tab key]` we get the completion for `aaaaa`.  The problem seems to be that `𝐚` and `a` are unicode equivalents, and the kernel (and even official python3) completions code gets that wrong because it doesn't canonicalize the unicode equivalents first.  So this is not the best test case for completion for me.

Fortunately, using `ΩΩΩΩΩ` works properly as a test case, since at least it isn't equivalent to something else.

**Comment by wadethestealth** [comment]
Apologies the test case wasn't actually for returning a real result. It was a test case to insure our cursor positions were being correctly translated, which we don't need a completion for to actually check. @williamstein

**Comment by williamstein** [comment]
Thanks -- I just wanted a full working example, so I could make sure my fix for CoCalc was working, and was very confused, so thought I would comment since it took me a while to get un-confused.

**Comment by stevengj** [comment]
> Fortunately, using ΩΩΩΩΩ works properly as a test case, since at least it isn't equivalent to something else.

No, that does *not* work as a test case, since `Ω` (U+03a9) is a BMP character that is stored as a single-UTF16 character.  You need to test with an "astral plane" (non-BMP) character.

**Comment by williamstein** [comment]
Does anybody know of a single example to illustrate this behavior that
actually works?

**Comment by wadethestealth** [comment]
I'm not sure what designates something that could be completed but for instance if you could create a variable in the kernel using the astral planes and have it try to autocomplete a variable name of astral planes. I am pretty sure that doesn't work, but you get the idea, make the kernel recognize something with astral planes in the completion.

**Comment by stevengj** [comment]
(As I noted [here](https://github.com/sagemathinc/cocalc/issues/1994#issuecomment-522137558), `𨭎𨭎𨭎𨭎𨭎` is a valid Python 3 variable name made of astral-plane chars.)
