### ISSUE TITLE
Checkmark bubble size doesn't scale correctly with font size

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#808]
I'm using a font size of 12 (rather than the default of 14), with the One Dark theme.

With these settings results bubbles with checkmarks are rendered slightly taller than one line, causing the line spacing to change when I run code.

**Comment by lgeiger** [comment]
I'll try and reproduce. Have you changed the line height (default 1.5)?

**Comment by nikitakit** [comment]
My line height is still at the default of 1.5. At font size 12, any line height less than 2.0 has this issue.
