### ISSUE TITLE
Problem with AVG anti-virus

### ISSUE THREAD

**Issue by Mike-MU10** [nteract/hydrogen#812]
**Description:**

Hi. I've been using Hydrogen for a while. 
The problem is that whenever I want to start the Hydrogen (which it calls the Julia kernel), the Atom stops (kindda freezes) until I shut down my AVG anti virus.
So basically the anti virus stops the ATOM and hydrogen. So I want into AVG Exceptions, I added folders like 

- .atom (which contains hydrogen inside),
- atom,
- and even the atom.exe and update.exe

but still I have the same issue.
Just being curios that  which engine of the AVG stops the process, I disables each engine one by one (by engine I mean web, software, computer, email, Firewall protector), but just when I stop them all everything works! 
So I was wondering if anybody has such issue or happen to know any solutions. I really don't like to disable my anti virus while I am using the hydrogen.
Thank you in advance guys!

**Steps to Reproduce:**

1. open Atom with any Julia file
2. press Shift+Enter on the first line of the code
3. and it will freeze

**Versions:**

Windows 7 SP1. ATOM 1.17.0 ia32. Hydrogen 1.12.1

**Comment by rgbkrk** [comment]
AVG has been pretty notorious for not liking the local network connections with zeromq for the kernels -- this affects jupyter notebook too. My only suggestions are to try a different antivirus or reach out to AVG.

**Comment by Mike-MU10** [comment]
Hi rgbkrk.
The problem is that this is company's computer and I cannot get rid of AVG. Any other solution?

**Comment by rgbkrk** [comment]
I don't have any suggestions other than you trying to ask for an exemption through your corporate IT policy for this application.

I _think_ you'll have to add exceptions to the directories for the kernels too `C:\Python34` etc.

**Comment by BenRussert** [comment]
@Mike-MU10 I think I'll close since this sounds like an AVG issue, feel free to reply if you have any other questions.
