### ISSUE TITLE
Code highlighting doesnt seem to work when specifying the type of a parameter and the type of the return type.

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#814]
**Description:**
Not sure whether its hydrogen related.

When specifying the type of a parameter and the type of the return type of a function like this:

def pick1(l: list, index: int) -> int:
    return l[index]

code highlighting doesnt work for subsequent functions:

def pick2(l: list, index: int) -> int:
    return l[index]

def pick3(l: list, index: int) -> int:
    return l[index]

It appears to be related to the output type. If its not included code highlighting is as expected.

**Versions:**
OS El Capitan 10.11.6 (15G31)
ATOM: 1.17.0 
Hydrogen: 1.14.1

**Comment by nikitakit** [comment]
This isn't an issue with hydrogen, it's just that Atom's default Python language package supports very little of the new syntax introduced in python 3.

To get better Python highlighting you should install the Magicpython package, set Hydrogen's "Language Mapping" setting to `{"python" : "magicpython"}`, and ensure that you're using Magicpython for your python files.

**Comment by hugeme** [comment]
Thank you!
