### ISSUE TITLE
Audit our Documentation

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#827]
At the moment our [documentation](https://nteract.gitbooks.io/hydrogen/) is pretty limited.

It would be great if we could improve on this to make it easier for new people to get started.

**Comment by MaximilianR** [comment]
The Remote Kernels section was in decent shape (I think I did a PR on this, or helped someone else to, IIRC). But I think a chunk has been repeated in a copy / paste (e.g. https://nteract.gitbooks.io/hydrogen/docs/Usage/RemoteKernelConnection.html#run-docker-container-with-docker-compose is there twice).

And it could do with a spring clean. Does anyone know why this is here? I've been very happily using the Kernel Gateway!

> As of December 2016, we recommend that you use a notebook server (version 4.3 or greater) instead of the Jupyter Kernel Gateway. We expect this to change in the future, and will update this README when that occurs.+

Happy to pitch in

**Comment by lgeiger** [comment]
Yeah the Remote Kernels section is great! I see myself referring to it a lot, everytime I set up new remote kernels.

> And it could do with a spring clean. Happy to pitch in

That's awesome! Thanks for helping out.

> Does anyone know why this is here? I've been very happily using the Kernel Gateway!

There used to be a combination of `kernel gateways` and `@jupyterlab/services` that didn't work well, though I'm pretty sure this has been fixed. I think we can remove this note.
