### ISSUE TITLE
Make use of all available space in external output area

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#833]
We added a new external output area in #825.

It uses the same CSS as the watch sidebar, meaning it doesn't make use of all available vertical space (it's limited to 450px max).

We should expand the result display to the full available space if necessary.

**Comment by tobiasbj** [comment]
I see that warnings and erros are outputted in separate "pages". Ex:

![test](https://cloud.githubusercontent.com/assets/7911343/26717819/1455b630-477f-11e7-9dc1-dc209a037327.png)

![image](https://cloud.githubusercontent.com/assets/7911343/26718011/c4a9208a-477f-11e7-8f2a-e484ca8ed24b.png)

![image](https://cloud.githubusercontent.com/assets/7911343/26718016/c89496a2-477f-11e7-85b8-e72dff56da3b.png)


Wouldn't it be nicer if the whole vertical space was used and they for example were displayed in 3 separate output windows on the vertical space (e.g. one for standard output, one for warnings and one for errors)? This is just from the top of my head is probably not the optimal solution.
