### ISSUE TITLE
CSP issues with Plotly using R kernel

### ISSUE THREAD

**Issue by bcdunbar** [nteract/hydrogen#841]
**Description:**

Content Security Policy errors when plotting with Plotly R package. The code below works in nteract notebook.

**Steps to Reproduce:**
```
library(plotly)

p <- plot_ly(x=1,y=1)
embed_notebook(p) 

# p (similar errors if you run without embed_notebook)
```
**Versions:**

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Hydrogen : 1.15.0

**Logs:**

<img width="1072" alt="2017-05-31 3" src="https://cloud.githubusercontent.com/assets/8393928/26693567/a107b6f8-46d2-11e7-801c-46c36b6a433d.png">

**Comment by lgeiger** [comment]
Unfortunately for us, the CSP policy in Atom doesn't allow the injection of scripts because of security reasons. Until we completely sandbox our display area we can't support embedded javascript in outputs.

Can you try to restart your kernel via the command pallet and try again without `embed_notebook(p)`?

**Comment by lgeiger** [comment]
Could you also try this solution: https://github.com/ropensci/plotly/issues/768#issuecomment-255639816

**Comment by bcdunbar** [comment]
Ah, okay.

Restarted and ran:
```
p <- plot_ly(x = 1, y = 1)
p
```

<img width="1075" alt="2017-06-01 2" src="https://cloud.githubusercontent.com/assets/8393928/26697777/43d0117e-46e1-11e7-8cea-8d695b0bb409.png">

**Comment by bcdunbar** [comment]
Yup, the above solution works in Atom.

**Comment by lgeiger** [comment]
>Yup, the above solution works in Atom.

Excellent! Would you be interested in adding it to our [examples collection](https://nteract.gitbooks.io/hydrogen/docs/Usage/Examples.html)?
