### ISSUE TITLE
Unable to copy from the External output area

### ISSUE THREAD

**Issue by tobiasbj** [nteract/hydrogen#845]
**Description:**
I like the new External output area feature, but it isn't currently possible to copy text from it. Making that possible would be a sweet addon :)

**Version**
I assume this is a global issue, but if not I am using:
Windows 10.
Atom 1.17.2
Hydrogen 1.15.0

**Comment by lgeiger** [comment]
@tobiasbj Would you be interested in implementing this feature?

It can be achived similar to how we're doing it in the normal [result view](https://github.com/nteract/hydrogen/blob/master/lib/components/result-view/result-view.js#L24).

**Comment by tobiasbj** [comment]
could be fun to try, but I don't think I have time to learn and do it right now. (I'm bascially just leeching off your glorious hydrogen :P ).

**Comment by callmeish** [comment]
Adressed in #954. I'm a bit new to this github thing, let me know if anything in that looks weird or needs changes.

**Comment by BenRussert** [comment]
@callmeish thanks for the PR! I'm looking forward to reviewing this weekend. Don't mean to leave you hanging.
