### ISSUE TITLE
kernelspec user config is ignored on update-kernels

### ISSUE THREAD

**Issue by t9md** [nteract/hydrogen#856]
**Description:**

`updateKernelSpecs` function ignore user config.
Because of bug.

```javascript
this._kernelSpecs = this.getKernelSpecsFromSettings;
```

Should be
```javascript
this._kernelSpecs = this.getKernelSpecsFromSettings();
```

https://github.com/nteract/hydrogen/blob/master/lib/kernel-manager.js#L244

[Description of the issue]

**Steps to Reproduce:**

1. Set JSON on `kernelspec` config with proper field with debug print insertion
2. See user config ignored and noticed code bug.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
- MacOS(10.12.5)
- ijavascript

You can get this information from copy and pasting the output of `atom --version`  from the command line.

```
Atom    : 1.18.0-beta2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by BenRussert** [comment]
@t9md Your proposed solution makes sense to me, want to make a PR to close this?

**Comment by t9md** [comment]
No.
