### ISSUE TITLE
[suggestion] Suppress console.log in dev-mode

### ISSUE THREAD

**Issue by t9md** [nteract/hydrogen#872]
**Description:**

When atom is running in dev mode(`atom -d .`), hydrogen write tons of log on chrome dev console.
This verbosity make more important log unnoticed/or difficult to find.

## Background: Example two situation why I want to suppress hydrogen's log

- While I'm hacking hydrogen, I add ad hoc console.log frequently, but without suppressing default log, finding this console.log is super difficult and easily scrolled over.
- I launch atom in dev mode to develop my own package, or Atom-core itself, and use hydrogen to check behavior of some code, but in this situation, I don't have interest of hydrogen's log itself. I want to watch log from other packages I'm working on, but hydrogen's log occupy console log.

**Steps to Reproduce:**

1. Launch atom with `-d` flag(run Atom in dev mode).
2. Start hydrogen and open chrome dev-console and see how much log is written on console"

## Suggestion to change

Make hydrogen write verbose log only when `Hydrogen.debug` was explicitly enabled regardless of atom's running mode.

**Comment by lgeiger** [comment]
Good idea!

Most amount of logs come from the mobx-devtools extension, so we'll need to disable it too.

**Comment by BenRussert** [comment]
I agree completely. PR incoming.

**Comment by t9md** [comment]
Wow thanks @BenTussert working on this.
