### ISSUE TITLE
Code evaluates, but no output bubble, only checkmark

### ISSUE THREAD

**Issue by smatting** [nteract/hydrogen#88]
Like the title says on my machine I never see the output of evaluations. The code however gets sucessfully evaluated in the python kernel. I can verify this by connecting to the running kernel via
`ipython console --existing [kernel-file.json]` and finding variables I defined in Hydrogen.

When I evaluate an expression there are only a few messages in the console:

```
Available kernels: [Object, Obje ...
main.coffee:277 row: 8
kernel.coffee:91 sending execute ...
kernel.coffee:116 ["<IDS|MSG>", ...
kernel.coffee:168 shell message: ... [ with type: "execute_reply" ]
result-view.coffee:141 resultType after update: null
```

On a different machine where Hydrogen is working there is a lot more output when you evaluate an expression. It seems that on my machine `onIOMessage` never gets called.

The kernel that is used is started like this:
`/usr/bin/python ["-m", "IPython.kernel", "-f", "/my/home/.atom/packages/Hydrogen/kernel-configs/kernel-f21e6a73-2f04-4470-85cf-1bc2d2b72f52.json"]`

This is contents of the `kernel-f21e6a73-2f04-4470-85cf-1bc2d2b72f52.json` file:

``` js
{
  "stdin_port": 57563, 
  "ip": "127.0.0.1", 
  "control_port": 34515, 
  "hb_port": 44148, 
  "signature_scheme": "hmac-sha256", 
  "key": "", 
  "shell_port": 38206, 
  "transport": "tcp", 
  "iopub_port": 54710
}
```

Here is how I install and run Hydrogen:

``` sh
rm -rf ~/.atom/packages/Hydrogen
apm install Hydrogen
atom .
```

I run a Ubuntu 14.04:

``` sh
apm -v
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

/usr/bin/python --version
Python 2.7.6

/usr/bin/python -m IPython.kernel --version
3.2.1
```

**Comment by n-riesco** [comment]
@smatting I'm trying to reproduce this issue. Please, could post the python expression you're trying to evalute?

**Comment by smatting** [comment]
Evaluate `x = 3` then `x` which yields no output even though the variable is successfully defined in the kernel.

**Comment by smatting** [comment]
After upgrading to jupyter, I can no longer reproduce this problem.

**Comment by rgbkrk** [comment]
:cake: :tada:

**Comment by worldsayshi** [comment]
It seems that installing `libzmq3-dev` and then reinstalling hydrogen solved it for me. 

Relevant: https://github.com/willwhitney/hydrogen/issues/73

**Comment by n-riesco** [comment]
I'm seen this issue with `libzmq3-dev`. Unfortunately, I can't trigger it in a reproducible way.

**Comment by n-riesco** [comment]
This seems to be a synchronisation problem. Sometimes the first few messages on the ioSocket don't reach Hydrogen (i.e. they don't show in the console log).

I don't understand how this is possible. @minrk , is it possible for a `sub` socket to miss messages?

I suspect this is also the cause of #53 .

**Comment by minrk** [comment]
It does take a finite amount of time for subscriptions to propagate from the subscriber to the publisher, and messages published before this time will be discarded by the publisher and the subscriber will not see them. Typically, this time is on the order of milliseconds. It would be very difficult for it to not have established this connection by the time a first execution request has been handled.

**Comment by n-riesco** [comment]
I don't know the reason, but in Atom, the ioSocket connection is not established immediately. In the cases when I see the issue reported here, the ioSocket connection happens after the second shell request.

**Comment by minrk** [comment]
One thing you can do is perform a kernel_info request at startup, prior to allowing execution. This allows you to ensure that the kernel is up and responsive before you start submitting execution requests. Each kernel_info request should also produce status idle/busy messages on the IOPub channel, so you can also use it to verify that IOPub is hooked up.

**Comment by n-riesco** [comment]
I've tried to send a kernel_info_request, but sometimes it's still fails.

**Comment by minrk** [comment]
You could keep trying kernel_info until you get the status messages:

```python
while True:
    kernel_info_request()
    wait_for_idle()
    if idle_received:
        break
```

If that takes more than one or two iterations, something is probably wrong.

**Comment by slavaGanzin** [comment]
Please don't use ```while true``` in synchronous atom it will freeze everything.

**Comment by n-riesco** [comment]
@minrk I've tried sending up to 5 `kernel_info_request` and sometimes it's still failing. The relevant code is [here](https://github.com/n-riesco/hydrogen/blob/161c8ffb484afc9f8480f4ee5ad17451e3dcc008/lib/kernel.coffee#L103-L128).

I wish I could imagine why initial connection of a ZMQ socket in Atom is stalled for so long.

I've noticed that saving the document triggers the connection. I'm not sure whether this is relevant.

**Comment by minrk** [comment]
@slavaGanzin I wasn't proposing anyone use `while true`. That was pseudocode for the logic of repeating kernel info requests until idle messages are received on the IOPub channel.

@n-riesco Sorry, I'm not familiar enough with the Hydrogen code, but I don't see the checks for IOPub messages related to that kernel_info request. Are they there, but I'm not seeing them?

**Comment by slavaGanzin** [comment]
@minrk Sorry didn't notice that. Thanks for you participating

**Comment by n-riesco** [comment]
@minrk It's perfectly understandable that you find difficult to see the checks. We're in the process of moving the code to use [jmp](https://github.com/n-riesco/jmp) and [enchannel-zmq-backend](https://github.com/nteract/enchannel-zmq-backend) with the hope that this will simplify Hydrogen's code.

The check is done [here](https://github.com/n-riesco/hydrogen/blob/161c8ffb484afc9f8480f4ee5ad17451e3dcc008/lib/kernel.coffee#L114-L119).

The hypothesis I'm pursuing now is that the issue is caused by the the multicontext nature of Atom. I'm struggling to find documentation, but I've seen some issues reporting bad interactions with `setTimeout`, `nextTick`, ... I've also found that Atom defines [process.activateUvLoop](https://github.com/atom/electron/search?utf8=%E2%9C%93&q=activateUvLoop).

If anyone has information on the execution contexts defined in Atom and how to interact with, please, help would be greatly appreciated.

**Comment by MilanQuentel** [comment]
I am experiencing the same problem, I believe. 

If I run the entire python file
`x = 3`
`print(x)`

it shows "Python - filename.py:2" as well as a checkmark and below it shows "3 [Finished in 0.157s]

If I run only the second line, the code runs through, there is no error and the screen shows
"Python - filename.py:2" as well as a checkmark and below it shows "[Finished in 0.157s] - in other words it omits the output. The code is just an example. Running line by line does not show output for any of the test codes I have tried.

Is there any solution to this? (Note, I am a beginner with Atom. Please let me know if I should report any other information.)

My atom version is 1.41.00
My hydrogen version is 2.13.00
My python version is 2.7.15
I am running on Windows 7.

Any help is appreciated. Thanks a lot in advance.

**Comment by wadethestealth** [comment]
@milanquentel I am unsure what you me by screen shows. If you wish you could also take a screenshot. Also if you could press Ctrl+shift+i it should open console. We will need you to expand the drop downs one level and screenshot those too. But do it in a new issue not this one.

**Comment by MilanQuentel** [comment]
@wadethestealth Thank you for your help and your hints on how this works. I will open a new issue and provide the screenshots.
