### ISSUE TITLE
hydrogen:restart-kernel doesn't work

### ISSUE THREAD

**Issue by homocomputeris** [nteract/hydrogen#880]
**Description:**

Restart kernel (or its keybinding) doesn't work after the latest update.

For instance, this worked fine:
```
'.platform-linux atom-text-editor':
  'ctrl-r': 'hydrogen:restart-kernel'
```

**Steps to Reproduce:**
Stopped working in 1.17
**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

**Logs:**

![2017-06-17 15-32-43](https://user-images.githubusercontent.com/7422433/27253318-4c317450-5372-11e7-961f-c9582784e703.png)

**Comment by BenRussert** [comment]
From the log it does appear your kernel is restarting. What behavior are you looking for that you are not seeing?

**Comment by BenRussert** [comment]
Also, are you up to date w/ v1.17.1 of hydrogen?

**Comment by homocomputeris** [comment]
It used to abort any computation, showing Python log with something like "interrupted by the user". Upon the second interruption Atom would pop up something like "No Python kernel used".

Now nothing happens: the calculation animation proceeds, no pop-ups appear.

Yes, I am using the latest version.

**Comment by homocomputeris** [comment]
Well, it seems that Atom actually disconnects from the kernel, but there are no indication of it.

**Comment by lgeiger** [comment]
Thanks for investigating.

We slightly changed the behavior of the kernel restart in b8ec0c3ffaa2841f9c62d333192e9a3f380ae70d. We don't clear result bubbles on restart anymore.

Looks like the spinner now also stays active, which in my opinion shouldn't be the case. I think we should should find a way to remove the spinners or fully revert the commit.

**Comment by stevencollinscn** [comment]
I was looking for the restart-kernel command and didn't find it at all. I tried to reinstall the package, but nothing appears. What did I miss? 
![snap1](https://user-images.githubusercontent.com/33796896/41195672-29030244-6c00-11e8-95f1-9016e3118995.jpg)

**Comment by BenRussert** [comment]
Try clicking the kernel status bar at the bottom of your editor (if a kernel is running). The status bar shows the name of your kernel and its status. Alternatively, you can find this command in the atom command palette.

(Look at the very bottom of the image I highlighted the status bar in pink)

![kernel-status-bar](https://user-images.githubusercontent.com/10860657/41196410-b4d89044-6bfc-11e8-8989-11b77e6efb32.png)

**Comment by stevencollinscn** [comment]
@BenRussert Thanks buddy.
