### ISSUE TITLE
Unable to detect remote kernels

### ISSUE THREAD

**Issue by xgb1206** [nteract/hydrogen#892]
**Description:**

I'm trying to use Hydrogen with a remote kernel, but it is unable to detect the available kernels. I have a VM running on Azure and I am able to connect and start kernels without any issues in my browser. Running connect to remote kernel in Hydrogen allows me to start a new session, but then it says "No kernel specs available".

**Steps to Reproduce:**

1. Start a Jupyter notebook on a Azure VM.
2. Run "Hydrogen: Connect to remote kernel" and choose new session

**Versions:**

OS X Sierra
Atom 1.18.0
Hydrogen 1.18.0
Jupyter 4.2.1

**Logs:**

There were no output in the console when doing this.

**Comment by BenRussert** [comment]
What grammar do you have set in your active editor? You can probably see this in your bottom status bar or by pressing `ctrl+shift+L` to bring up the grammar selector (the active grammar will be highlighted with a checkmark)

**Comment by alha02** [comment]
I have the Julia grammar in my active editor.

**Comment by lgeiger** [comment]
@alha02 What version of jupyter are you running in your VM?

**Comment by alha02** [comment]
I was running Jupyter 4.2.1.

**Comment by kylebarron** [comment]
Closing as stale
