### ISSUE TITLE
How to specify the conda environment in which hydrogen (jupyter) starts?

### ISSUE THREAD

**Issue by docsteveharris** [nteract/hydrogen#899]
I have tried working from #501 but can't make any progress.

I have Hydrogen 1.18.0 and want to be able to specify the conda environment that in which I launch my jupyter notebook.

From the command line, I'd do

```
source activate thisenv
jupyter notebook
``` 

How do I achieve the same thing from Hydrogen?

Many thanks

**Comment by lgeiger** [comment]
Guessing from #501 this should do the job:
```bash
source activate thisenv
python -m ipykernel install --user --name thisenv
```

**Comment by lgeiger** [comment]
It may also work if you start Atom from the command line after running `source activate thisenv` but then you can't switch between different envs in Atom.

**Comment by docsteveharris** [comment]
Thank you. But where do I put this? It doesn't match the JSON which seems to be required for Kernel specs

**Comment by lgeiger** [comment]
> It doesn't match the JSON which seems to be required for Kernel specs

As long as you have jupyter installed you don't need to manually add kernelspecs inside the Hydrogen settings, we automatically detect installed kernels. You can savely remove any JSON you added to the Hydrogen kernel specs settings.

You can run "Hydrogen: Update Kernels" or restart Atom for the changes to take effect. Next time you want to run Python code you'll be prompted to select the environment you just created.

**Comment by lgeiger** [comment]
One thing to add: You'll only need to run
```bash
source activate thisenv
python -m ipykernel install --user --name thisenv
```
once in the command line.

**Comment by docsteveharris** [comment]
thank you very much! all works.

**Comment by lgeiger** [comment]
Awesome

**Comment by g4nym3de** [comment]
Thx for the answer but the second line wouldn't work, it says **No module named ipykernel**
My kernelspec is 
{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/Users/spoc/anaconda2/share/jupyter/kernels/python2", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/Users/spoc/anaconda2/bin/python", 
          "-m", 
          "ipykernel_launcher", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}

**Comment by scarecrow21** [comment]
`source activate thisenv
python -m ipykernel install --user --name thisenv`

Hi. I am using Ubuntu 16 with conda 3.6 env. The above command returns `No module named ipykernel`.

How do I get hydrogen working from inside atom?

**Comment by Amsoht** [comment]
> 
> 
> One thing to add: You'll only need to run
> 
> ```shell
> source activate thisenv
> python -m ipykernel install --user --name thisenv
> ```
> 
> once in the command line.

This helped me a lot. Now I can see my envs in atom, when I try to start hydrogen. Unfortunately, I get an error and cannot run code: 
`Traceback (most recent call last): File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\jupyter_client\connect.py", line 21, in import zmq File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq__init__.py", line 55, in from zmq import backend File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\wagenhaeuser\Anaconda3\envs\toolpacenv\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

It seems, as if there is a "\" missing in several pathnames. Any ideas how to fix this very much appreciated.
Cheers
