### ISSUE TITLE
hydrogen failed install on mac

### ISSUE THREAD

**Issue by gyh75520** [nteract/hydrogen#903]
I use **apm install Hydrogen** then report error

> zeromq@4.5.0 install /private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)

prebuild-install info begin Prebuild-install version 2.1.2
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/howard/.atom/.node-gyp/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.5.0-zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.5.0/zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz
prebuild-install WARN install connect ETIMEDOUT 121.59.17.8:443

> zeromq@4.5.0 build:libzmq /private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i/node_modules/Hydrogen/node_modules/zeromq
> node scripts/preinstall.js

/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i
└── (empty)

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 121.59.17.8:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

npm ERR! Darwin 16.6.0
npm ERR! argv "/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/AppTranslocation/B84F93A1-5F3F-4452-8AAE-3B392072B1AF/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/AppTranslocation/B84F93A1-5F3F-4452-8AAE-3B392072B1AF/d/Atom.app/Contents/Resources/app/apm/node_modules/.bin/npm" "run" "build:libzmq"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.5.0 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.5.0 build:libzmq script 'node scripts/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i/node_modules/Hydrogen/node_modules/zeromq/npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i/package.json'
npm WARN apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i No description
npm WARN apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i No repository field.
npm WARN apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i No README data
npm WARN apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i No license field.
npm ERR! Darwin 16.6.0
npm ERR! argv "/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/AppTranslocation/B84F93A1-5F3F-4452-8AAE-3B392072B1AF/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/AppTranslocation/B84F93A1-5F3F-4452-8AAE-3B392072B1AF/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/howard/.atom/.apm/.apmrc" "--userconfig" "/Users/howard/.atom/.apmrc" "install" "/private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/d-11763-2101-3hu5z7.r7ipe3ik9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.5.0 install: `node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.5.0 install script 'node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/l6/4fy41n5d09dc91pbl_6yg79r0000gn/T/apm-install-dir-11763-2101-13od4uo.tsf6sf9a4i/npm-debug.log
npm ERR! code 1

**Comment by lgeiger** [comment]
Looks like the download timed out. Please make sure your internet connection works and you're not behind a proxy. Could you try again?

**Comment by n-riesco** [comment]
The installation script failed to download the zeromq binary.
Please, try to reinstall Hydrogen again.

**Comment by gyh75520** [comment]
I modify the hosts file.Does this belong to proxy？
I tried many times, always report this error.

**Comment by n-riesco** [comment]
If you can download the link https://github.com/zeromq/zeromq.js/releases/download/v4.5.0/zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz using a browser, then it's possible your computer is behind a webproxy.

**Comment by gyh75520** [comment]
I can not open this link. 
I have successfully installed other atom's plugins.
I'm so upset that I can not install hydrogen.

**Comment by willingc** [comment]
On MacOS 10.12.5, I have successfully installed hydrogen with the following versions of apm, npm, and node:

<img width="432" alt="screen shot 2017-07-03 at 11 01 21 am" src="https://user-images.githubusercontent.com/2680980/27803598-1b07c5e0-5fdf-11e7-8e51-7c0e7c5c28cd.png">

@gyh75520 If you are using a 32 bit system, double check that you are using Python 2 instead of Python 3 for installation. [ref](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html#installation-fails-on-linux-32-bit)

**Comment by gyh75520** [comment]
HowarddeMacBook-Pro:~ howard$ uname -a
Darwin HowarddeMacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64
HowarddeMacBook-Pro:~ howard$ apm -v
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

**Comment by willingc** [comment]
Well it looks like you have recent enough versions @gyh75520. 

Let's rule out one possibility. Do you already have `jupyter` installed? If not, you will need to do so following the installation directions [here](https://nteract.gitbooks.io/hydrogen/docs/Installation.html#installation).
If you do have `jupyter` installed, the following commands will help to troubleshoot your Jupyter installation:
- `jupyter troubleshoot`
- `jupyter kernelspec list`

**Comment by gyh75520** [comment]
HowarddeMacBook-Pro:~ howard$ jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/Library/Frameworks/Python.framework/Versions/3.5/bin
	/Library/Frameworks/Python.framework/Versions/3.5/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin

sys.path:
	/Library/Frameworks/Python.framework/Versions/3.5/bin
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages

sys.executable:
	/Library/Frameworks/Python.framework/Versions/3.5/bin/python3

sys.version:
	3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) 
	[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

platform.platform():
	Darwin-16.6.0-x86_64-i386-64bit

which -a jupyter:
	/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter
	/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter

pip list:
	appnope (0.1.0)
	astroid (1.5.3)
	bleach (2.0.0)
	decorator (4.0.11)
	entrypoints (0.2.3)
	flake8 (3.3.0)
	html5lib (0.999999999)
	ipykernel (4.6.1)
	ipython (6.1.0)
	ipython-genutils (0.2.0)
	ipywidgets (6.0.0)
	isort (4.2.15)
	jedi (0.10.2)
	Jinja2 (2.9.6)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.1.0)
	jupyter-console (5.1.0)
	jupyter-core (4.3.0)
	lazy-object-proxy (1.3.1)
	MarkupSafe (1.0)
	mccabe (0.6.1)
	mistune (0.7.4)
	nbconvert (5.2.1)
	nbformat (4.3.0)
	notebook (5.0.0)
	pandocfilters (1.4.1)
	pep8 (1.7.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	pip (9.0.1)
	prompt-toolkit (1.0.14)
	ptyprocess (0.5.2)
	pycodestyle (2.3.1)
	pydocstyle (2.0.0)
	pyflakes (1.5.0)
	Pygments (2.2.0)
	pylama (7.4.1)
	pylama-pylint (3.0.1)
	pylint (1.7.2)
	python-dateutil (2.6.0)
	pyzmq (16.0.2)
	qtconsole (4.3.0)
	setuptools (36.0.1)
	simplegeneric (0.8.1)
	six (1.10.0)
	snowballstemmer (1.2.1)
	terminado (0.6)
	testpath (0.3.1)
	tornado (4.5.1)
	traitlets (4.3.2)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	widgetsnbextension (2.0.0)
	wrapt (1.10.10)
HowarddeMacBook-Pro:~ howard$ jupyter kernelspec list
Available kernels:
  python3    /Library/Frameworks/Python.framework/Versions/3.5/share/jupyter/kernels/python3


I installed python3.5 and
vim ~/.bash_profile
add **alias python='/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5'**  at the end.

and then installed jupyter.
because I installed hydrogen failed, I Revoke  the file's modification.

HowarddeMacBook-Pro:~ howard$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

But it reported the same error.

**Comment by willingc** [comment]
Hi @gyh75520 I'm a bit confused as to whether you are using Python2 or Python3 for installation.

The following would install Hydrogen using Python 2:

1. `which python` should return a Python2 version.
2. `python -m pip install --upgrade pip`
3. `python -m pip install --upgrade jupyter`
4. `apm install hydrogen`

**Comment by gyh75520** [comment]
@willingc Thank you for your patience，-v-.
I followed your advice, but it also reported the same error.
be close to tears.

**Comment by lgeiger** [comment]
@gyh75520 I don't know what to do, since you cannot access https://github.com/zeromq/zeromq.js/releases/download/v4.5.0/zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz

You can try to manually copy this file to `/Users/howard/.atom/.node-gyp/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.5.0-zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz`. If you have the possibility to access the link from somewhere else.

**Comment by willingc** [comment]
@gyh75520 One other thing to check would be to see if the version of Atom itself and it's dependencies are up to date.

On my Mac:

<img width="309" alt="screen shot 2017-07-06 at 6 16 27 am" src="https://user-images.githubusercontent.com/2680980/27912790-e84d8d52-6212-11e7-8616-f061a2b454c1.png">

Digging a bit more into the original error log at the start of this issue:
> 
```
events.js:160
      throw er; // Unhandled 'error' event
```
You might try https://piotrkrzyzek.com/solved-events-js160-throw-er-unhandled-error-event/ to resolve.

**Comment by gyh75520** [comment]
I found my phone and windows can access the https://github.com/zeromq/zeromq.js/releases/download/v4.5.0/zeromq-v4.5.0-electron-v49-darwin-x64.tar.gz
, only my mac can't.

**Comment by studynon** [comment]
@gyh75520 Did you solve your installation ERROR? I also catch this error. After I copy the .tar.gz to `/.atom/.node-gyp/.npm/_prebuilds/`. The ERROR of `prebuild-install WARN install connect ECONNREFUSED 121.59.17.8:443` still exists. @lgeiger

**Comment by studynon** [comment]
@gyh75520 I have solved it! Maybe it is your hosts problem. You can change your `/etc/hosts` file according to [here](https://github.com/racaljk/hosts).

**Comment by gyh75520** [comment]
@studynon Thank you!!!!
 I'm so happy !!
