### ISSUE TITLE
How to import packages

### ISSUE THREAD

**Issue by andb0t** [nteract/hydrogen#906]
Hi all,

I would like to import matplotlib or numpy in the interactive hydrogen session but
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-5a0bd626bb1d> in <module>()
----> 1 import numpy

ModuleNotFoundError: No module named 'numpy'
```
I guess I have missed how I can import external packages in my kernel. It's also not written in the hydrogen documentation, probably because it's so obvious. Can anyone help me out? Could this be added to the documentation for the sake of newbies like me?

Thanks!

**Comment by BenRussert** [comment]
Do you have already have numpy installed? Most likely you would want to run `pip install numpy` from a terminal in order to install it (making it available for import going forward).

**Comment by andb0t** [comment]
Your comment triggered a deeper dig into my setup and I found the problem: I use anaconda on Windows and have a conda environment set up. Numpy and matplotlib are installed  I have installed ipykernel and use the kernel I get from executing in the very same shell. However, when changing conda environment **I had forgotten to add the path of the new conda environment python executable to the windows PATH environmental variable.**

**Comment by BenRussert** [comment]
Cool, sounds like you got it working? 

BTW, if you want to add anything to the docs feel free to submit a PR!
