### ISSUE TITLE
Add option to disable autocomplete

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#92]
Would be helpful for the use of hydrogen together with other autocomplete providers.

**Comment by terraqout** [comment]
> Would be helpful for the use of hydrogen together with other autocomplete providers.
@lgeiger Can you explain your idea?

**Comment by lgeiger** [comment]
I use [autocomplete-python](https://atom.io/packages/autocomplete-python) for code completion. Because it supports rich completions like displaying docstrings and metadata.

But in use together with hydrogen I get completions from both autocomplete-python and hydrogen.

![autocomplete](https://cloud.githubusercontent.com/assets/13285808/12184365/217894c2-b595-11e5-9839-118d1feedb74.png)

It would be nice to have the option to deactivate hydrogens autocompletion in the settings.

By the way I'm really looking forward to seeing this ideas implemented: https://github.com/jupyter/jupyter_client/issues/51. It would improve hydrogens own autocompletion a lot.

**Comment by DzamoNorton** [comment]
@lgeiger I was working the same way as you but realised that hydrogen / iPython has access to a lot more type information during an interactive session than Jedi is able to figure out.  So I added a key binding
```
'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'alt-shift-i': 'hydrogen:toggle-inspector'
```
and I now, admittedly with a couple of extra keystrokes, rely on hydrogen for docstrings too when I'm working interactively.

**Comment by n49o7** [comment]
I understand that this issue has been closed but this is the top result on Google for "nteract disable autocomplete". Using nteract, I spend half of my time erasing miscompletions. I've read about hydrogen and jupyter and ipython and jedi and auto-complete but I still don't know what setting to change or where.

If a solution exists, perhaps it would be useful to have it listed here. Anyone ?
