### ISSUE TITLE
line magic `%load` doesn't work

### ISSUE THREAD

**Issue by MatthewSteen** [nteract/hydrogen#924]
**Description:**

Running a cell using the `%load file.ext` line magic command returns a :ballot_box_with_check: rather than loading the contents of file.ext. https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-load

**Steps to Reproduce:**

1. `%##`
2. `%load file.ext`
3. CTRL + ALT + ENTER

**Versions:**

Windows 7 x64
Atom 1.18.0
Hydrogen 1.19.0

**Logs:**

NA

**Comment by rgbkrk** [comment]
On the implementation side, the jupyter message for this is on `execute_reply`. When `status` is ok, it can have a `payload` field that is an `Array<Object>` where the payload object for this is:

```js
{
  "source": "set_next_input",
  // text to insert
  "text": "some cell content",
  // If true, replace the current cell in document UIs instead of inserting
  // a cell. Ignored in console UIs.
  "replace": bool,
}
```

**Comment by MatthewSteen** [comment]
This would be helpful for developing in other languages (i.e. non-Python). For example, I mostly use develop in Ruby using the `%%script ruby` cell magic to run files, then change to `%%writefile name.rb` cell magic to overwrite the source file with changes. So basically I have a .ipynb file (or .py file when using Atom/Hydrogen, which I prefer for the Git integration) for each Ruby .rb source file.

Without the `%load file.ext` magic, I have to manually copy/paste the contents of a source file into Atom if a colleague makes changes to that file in a repo. Perhaps there's a better way to develop outside of Python using Jupyter.

**Comment by wadethestealth** [comment]
@rgbkrk so is the %load module using deprecated messaging?

**Comment by rgbkrk** [comment]
Yeah the `%load` module is using deprecated messaging, though I think we can basically interpret this as not deprecated at all... Perhaps we should support it?

**Comment by wadethestealth** [comment]
@rgbkrk If jupyter considers it deprecated, I think we should too. Although it would be nice for a replacement to eventually be thought out.
