### ISSUE TITLE
Scroll position lost when switching between tabs

### ISSUE THREAD

**Issue by dnowacki-usgs** [nteract/hydrogen#929]
**Description:**

Scroll position is lost in a tab with multiple Hydrogen output bubbles when switching to another tab and then back. Sometimes it seems to bring you back to the top of the editor, other times there is a jitter up and down and returns you close to the line you were at, but with the output bubble now off the bottom of the screen.

**Steps to Reproduce:**

1. Create a file, say a.py, and open another tab (either a file or the Settings pane, for instance)
2. Generate more than one output bubble in a.py such that you scroll down to run one of them.
3. Switch to other tab
4. Switch back to a.py. Editor returns you to a location that is not where you left off, generally (always?) higher up in the file. Cursor remains on the line you were on, however.

This is sorta similar to #785, but relates to editor scroll position and not result bubble scroll position, although that bug also is present in this issue.

**Versions:**

macOS 10.12.5
Hydrogen 1.19.0
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by BenRussert** [comment]
Thanks for the report!

I see your point about this being similar, but different than #785.  We think the underlying issue is probably something in atom core, probably the same case here. 

It might be possible to come up with a fix in hydrogen that takes into account whatever is going on in atom core.

**Comment by BenRussert** [comment]
@dnowacki-usgs are you on atom 1.19 yet?  I just upgraded this week and think the editor scroll position issue you describe might be resolved.

**Comment by dnowacki-usgs** [comment]
@BenRussert I just upgraded to 1.19.2 and Hydrogen 1.20.0 and I agree, it looks like this issue is resolved. Thanks.
