### ISSUE TITLE
The hook is not aligned with the Chinese

### ISSUE THREAD

**Issue by xiligey** [nteract/hydrogen#930]
**Description:**
When I run the command `hydrogen:run` on
 `initial_schedule = np.zeros((classes, courses_perday, days))  # initial schedule`, 
the"√" is after the note.
But when i change the note to Chinese like "初始化时间表", 
the "√" covered the note.
![1](https://i.loli.net/2017/07/26/5977fefbce243.png)

PS: coding=utf-8

**Versions:**
Win10+Hydrogen1.19.0+Atom1.18.0

**Comment by BenRussert** [comment]
Thanks for the report!

possibly related to #807?

**Comment by lgeiger** [comment]
@xiligey We get the number of characters in a line via [`editor.getBuffer().lineLengthForRow(row)`](https://github.com/nteract/hydrogen/blob/master/lib/components/result-view/index.js#L43) to determine the [placement of the check](https://github.com/nteract/hydrogen/blob/master/lib/components/result-view/result-view.js#L109). Unfortunately this works only for monospaced fonts.

If anyone knows a way to get the the line ending position from Atom in units of pixels we'd be more than happy to fix this.
