### ISSUE TITLE
Hydrogen cannot read triple quotes 

### ISSUE THREAD

**Issue by rachelfu** [nteract/hydrogen#934]
**Description:**

I have issues to print strings that are created with three quotes, `"""`.

**Steps to Reproduce:**

1. Here is the code I am using, and the error message:

```
snake_string = """Welcome to Python3!
             ____
            / . .\\
            \  ---<
             \  /
   __________/ /
-=:___________/
"""
```
2. When I hit `shift + enter`, there is what I get:

![screen shot 2017-07-30 at 8 07 55 am](https://user-images.githubusercontent.com/23180334/28753725-3f10ed2a-74fe-11e7-9674-02bb2a580631.png)

I tried single triple quotes `'''` and double `"""`, but neither of them works. 

3. It is OK to run using `Script`.

![screen shot 2017-07-30 at 8 09 26 am](https://user-images.githubusercontent.com/23180334/28753734-6ea900f4-74fe-11e7-8b37-8043406804a3.png)

**Versions:**

I am using macOS Version 10.12. Atom is 1.18

**Comment by rgbkrk** [comment]
Thanks for reporting. Seems we need to parse what the last statement or expression is rather than running the last line.

For now at least it looks like you'll have to select the entire block of code you want to execute.

**Comment by rachelfu** [comment]
Thanks for the reply! Sometimes, it has problem parse a function if I hit `shift+enter` at the last line. `Script` doesn't have similar issue. I will select the block for now.

**Comment by BenRussert** [comment]
@rachelfu the other thing you can do (at least for now) is use the [run cell functionality](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell).

**Comment by rachelfu** [comment]
@BenRussert 

This works too. Thanks!

**Comment by BenRussert** [comment]
I'll close this since it looks resolved. Let me know if you have any questions!
