### ISSUE TITLE
hydrogen can not add watch again after delete any watch.

### ISSUE THREAD

**Issue by bbsdkjdx** [nteract/hydrogen#936]
After I've deleted a watch of variable,I can not add any variable to watch again,unless restart atom,I hope to fix this bug.

**Comment by BenRussert** [comment]
@bbsdkjdx thanks for the report! 

I've been able to reproduce, but only inconsistently so far. Do you have specific steps that will reproduce the issue? This will help narrow down the cause.

**Comment by BenRussert** [comment]
Are you calling remove watch from the command palette or by clicking the button in the watches view?

**Comment by BenRussert** [comment]
Can anyone reproduce? I don't think I reproduced this issue exactly.

The issue I could find was that remove watch doesnt work when called from the command palette, but does work when clicking the "remove watch" button. That might be a different issue entirely though...

**Comment by chq-matteo** [comment]
In the zip file there is a .mp4 file of the issue
[Hydrogen Watch .zip](https://github.com/nteract/hydrogen/files/1246003/Hydrogen.Watch.zip)

**Comment by BenRussert** [comment]
Thanks @chq-matteo. Here it is below for reference. I think I can fix this pretty quickly, thanks for the report!

![hydrogen-watch-issue mp4](https://user-images.githubusercontent.com/10860657/29746514-30afac76-8aa2-11e7-9348-86528c37b1bd.gif)

**Comment by lgeiger** [comment]
This is fixed in Hydrogen v1.21.1

Thanks @BenRussert

**Comment by bbsdkjdx** [comment]
hydrogen is rally excellent with such an awesome team.
