### ISSUE TITLE
Hydrogen Kernel Help (sorry for stupid question)

### ISSUE THREAD

**Issue by ancientsigyl** [nteract/hydrogen#944]
I just downloaded Atom and Hydrogen. I want to use Hydrogen with Python 3.6, but whenever I try it returns the following errors:

Error 1 (I'm not sure what this error even means):
No kernel specs found
Use kernelSpec option in Hydrogen or update IPython/Jupyter to a version that supports "jupyter kernelspec list --json" or "ipython kernelspec list --json".

Error 2:
No kernel for grammar Python found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.

To remedy these problems, I tried entering the following commands in Powershell...

C:\Python36\Scripts\pip3 install jupyter
C:\Python36\Scripts\pip3 install ipython
cd C:\Python36
python -m pip install ipykernel
python -m ipykernel install --user

...but still get the same errors. Am I missing something? I'm new to Hydrogen, Atom, and Jupyter so I'd really appreciate any and all help. If it helps, here are the software versions I use (they should all be recent since I installed them via pip recently):

Python 3.6 x64
Atom 1.19.0 x64
Hydrogen 1.20.0

**Comment by BenRussert** [comment]
Could you try running `jupyter kernelspec list --json` from powershell? This will confirm jupyter installed and if you paste the results here it might help figure out what the issue is.

**Comment by ancientsigyl** [comment]
I tried this:
cd C:\Python36\Scripts\
jupyter kernelspec list --json
and got the following:
Suggestion [3,General]: The command jupyter was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\jupyter". 

So I tried:
.\jupyter kernelspec list --json
and got the following:
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "C:\\Users\\James\\AppData\\Roaming\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "c:\\Python36\\pythonw.exe",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    }
  }
}

**Comment by BenRussert** [comment]
I think this might be an issue w/ your environment path variable. You should be able to call `jupyter kernelspec list --json` from any working directory without appending the `./jupyter` part.

Is there a reason you dont seem to have `pip` in your path either? If you are not sure what I am talking about I can probably walk you through how to add `C:\Python36\Scripts` to your path.

**Comment by BenRussert** [comment]
@ancientsigyl try opening your settings view for hydrogen and pasting that json output from kernelspec list into the setting that says "kernelSpec" 

Ideally this would be picked up automatically by `jupyter kernelspec list --json`, but only if that same command works from your shell without navigating to `C:\Python36\Scripts` as you indicated.

**Comment by ssahaxd** [comment]
# Solution
Just make sure, Python is installed for all users and it is added to the environment variables.

![ss1](https://user-images.githubusercontent.com/11327529/29982063-cfa6d654-8f6d-11e7-8c8f-c434300617cb.jpg)

![python setup Wizard](https://preview.ibb.co/d8w8eF/Screenshot_48.png)
I was also facing the same problem, after adding it to the environment all my problems were solved.

**Comment by ssahaxd** [comment]
It is happening due to the fact that Python is not added to the system variables system environment variables.
Refer [#950](https://github.com/nteract/hydrogen/issues/950#issuecomment-326726163)

**Comment by lgeiger** [comment]
In Hydrogen 2.0.0 we changed our kernel detection method to improve the startup time and make setup easier. Checkout the updated [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html) and the [release notes](https://github.com/nteract/hydrogen/releases/tag/v2.0.0) for more information.

Feel free to open a new issue if you still experience problems with version 2.0.0.

**Comment by dlefcoe** [comment]
running Atom on windows 10.
I just downloaded Atom and Hydrogen. I want to use Hydrogen with javascript, but whenever I try it 

get this error message:
No kernel for grammar javascript found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.

i have no idea what this means...
how can i fix this / get this working please ?

**Comment by n-riesco** [comment]
@dlefcoe You need to install a Javascript kernel. See, for example, the kernel I'm maintaining: [IJavascript](https://github.com/n-riesco/ijavascript#installation).

**Comment by dlefcoe** [comment]
the installation instruction are for Linux and Mac,  but not windows.
Windows suggests install Anaconda...  

> In Windows, Anaconda offers a convenient distribution to install Python and many other packages, such as Jupyter and IJavascript.

However, anaconda is just for python from what i can see.

...am lost on how to do it ?!?

**Comment by n-riesco** [comment]
> However, anaconda is just for python from what i can see.
>
> ...am lost on how to do it ?!?

Hydrogen uses the kernels registered with Jupyter. Jupyter is written in python. and thus the need for a python distribution in your computer. Anaconda is a convenient distribution of Python that also comes with Jupyter.

**Comment by n-riesco** [comment]
@dlefcoe It's possible to install a kernel manually (i.e. without installing Jupyter, but I can't tell you how from the top of my head; I'd need to try on a Windows machine).

**Comment by dlefcoe** [comment]
would be appreciated if can.  my attempts so far have failed.

**Comment by n-riesco** [comment]
@dlefcoe you need to create the folder `%APPDATA%\jupyter\kernels\javascript` and store the followling files:

- a file named `logo-32x32.png` with [this logo](https://github.com/n-riesco/ijavascript/blob/8637a3e18b89270121f49733d03af0e3e6e0a17a/images/nodejs/js-green-32x32.png)
- a file named `logo-64x64.png` with [this logo](https://github.com/n-riesco/ijavascript/blob/8637a3e18b89270121f49733d03af0e3e6e0a17a/images/nodejs/js-green-64x64.png)
- a file named `kernel.json` with the following contents:
  ```json
  {
    "argv": [
      "ijskernel.cmd",
      "--hide-undefined",
      "{connection_file}",
      "--protocol=5.0"
    ],
    "display_name": "Javascript (Node.js)",
    "language": "javascript"
  }
  ```

This kernel spec assumes that you've installed Node and IJavascript, and that you can `ijskernel.cmd` in the terminal (if this isn't the case, you'll have to tell me how you've installed Node and IJavascript).

**Comment by dlefcoe** [comment]
have created the folders suggested. saved the files as stated.
I open terminal and type `ijskernel.cmd` and `ijskernel`, neither work.

Standard install of node from: [https://nodejs.org/en/download/](url)
for iJavascript:   just did this in the terminal  `npm install -g ijavascript`

Doesn't work.

**Comment by n-riesco** [comment]
@dlefcoe I can't reproduce the problem in your machine (in my case, both `where ijskernel` and `where ijskernel.cmd` work). Based on the results I get in my test machine, I'd update `kernel.json` as follows:
- confirm `ijskernel.cmd` is installed in `%appdata%\npm`
- update `kernel.json` like this:
```
{
  "argv": [
    "%appdata%\npm\ijskernel.cmd",
    "--hide-undefined",
    "{connection_file}",
    "--protocol=5.0"
  ],
  "display_name": "Javascript (Node.js)",
  "language": "javascript"
}
```

If this doesn't work, try to replace `%appdata%` with its value (to see its value run `echo %appdata%`):
```
C:\Users\User> echo %appdata%
C:\Users\User\AppData
```

```
{
  "argv": [
    "C:\Users\User\AppData\npm\ijskernel.cmd",
    "--hide-undefined",
    "{connection_file}",
    "--protocol=5.0"
  ],
  "display_name": "Javascript (Node.js)",
  "language": "javascript"
}```

**Comment by dlefcoe** [comment]
When i do this i get the following error:

`Error: Error: missing connection_file
    at parseCommandArguments (C:\Users\Owner\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js:182:19)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js:46:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

**Comment by n-riesco** [comment]
Judging by the error message, `ijskernel.cmd` is stored in `C:\Users\Owner\AppData\Roaming\npm`. Could you confirm that?

If that's the case, the `kernel.json` you need is:
```
{
  "argv": [
    "C:\Users\Owner\AppData\Roaming\ijskernel.cmd",
    "--hide-undefined",
    "{connection_file}",
    "--protocol=5.0"
  ],
  "display_name": "Javascript (Node.js)",
  "language": "javascript"
}
```

**Comment by dlefcoe** [comment]
yes,  this is the case.  `ijskernel.cmd`  is stored in `C:\Users\Owner\AppData\Roaming\npm` 

i have modified the kernel.json accordingly as recommended.  still does not run.


get this error message

> No kernel for grammar JavaScript found
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.

**Comment by vijaykarthik123** [comment]
Hi, 

I have the same issue on Atom with the hydrogen package. I have a small snippet of code here which doesn't seem to work at all.

`import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'png'

p = np.pi;
t = np.linspace(0,1,10000)
f = np.sin(2*p*0.1*t)

plt.figure()
plt.plot(t,f)
plt.show()
`

The kernel.json specified at the %APPDATA% env. variable seems to work fine when called with 

`jupyter kernelspec list --json`.

**Comment by n-riesco** [comment]
@vijaykarthik123 Please, let's continue the discussion on #1261 .
