### ISSUE TITLE
Question:How to import python 2 modules?

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#947]
**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

ATOM 1.19.1
MAC 10.12.5

**Description:**

I have a problem importing modules for python 2. I use multiple kernels for R, python 2 and python 3. 
R as well as python 3 works fine. When using Python 2 however, I cant import the corresponding modules newly installed. When launching python 2 from command line corresponding modules are available where `/Library/Python/2.7/site-packages` is the path to the site-packages

My Kernel Specs is as following:

    {
      "kernelspecs": {
        "python2": {
          "spec": {
            "display_name": "Python 2",
            "language": "python",
            "argv": ["python2.7", "-m", "ipykernel", "-f", "{connection_file}"],
            "env": {}
          }
        },
        "r": {
          "spec": {
            "display_name": "R",
            "language": "R",
            "argv": ["R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
            "env": {}
          }
        },
        "python3": {
           "spec": {
             "display_name": "Python 3",
             "language": "python",
             "argv": ["python3.6", "-m", "ipykernel", "-f", "{connection_file}"],
             "env": {}
          }
        }
      }
     }

How can I adjust the Kernel Specs in order to incorporate modules from python 2

Appreciate any suggestions

**Comment by BenRussert** [comment]
Are you able to start python 2 in your console and import the relevant modules there? This will help narrow down the issue if everything works fine there.

**Comment by hugeme** [comment]
@BenRussert Yes, that works fine via console

**Comment by BenRussert** [comment]
Thanks. Maybe try upgrading ipykernel with `pip install --upgrade ipykernel`. 

We had somewhat similar issue (maybe) in #730 with various fixes. It is hard to say if this is the same thing.

I am wondering if you have two separate python2 installations behind the issue, can you import standard lib modules? e.g. `import sys` ?

**Comment by hugeme** [comment]
Hi @BenRussert, yes I can `import sys`  from hydrogen. Hm, not 100% sure but #730  doesnt sound like the current problem, since I can launched python2 kernel and can do anything except importing modules, perhaps its path related.  when `pip install --upgrade ipykernel` I get `Operation not permitted` back with last line `Operation not perm
itted: '/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/pip-60uUj8-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/py
thon/_markerlib'")]` when `sudo pip install --upgrade ipykernel` I get an error as well with `Operation not permitted: '/tmp/pip-WM0jil-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/p
ython/_markerlib'")]` as the last line.

**Comment by hugeme** [comment]
@BenRussert I think I solved something here :) not sure whether that was correct on long run. I put  `export PATH="/usr/local/opt/python/libexec/bin:$PATH"` into my `.bash_profile`and reinstall all packages I need. So basically now I can import them all. Still thanks for your help!
