### ISSUE TITLE
imshow not working in the editor window

### ISSUE THREAD

**Issue by Jayu8** [nteract/hydrogen#949]
![capture](https://user-images.githubusercontent.com/18685151/29437122-fdaa7b16-837c-11e7-9c84-17bdd2739e44.PNG)

**Description:**

I am not able to see images when i use plt.imshow instead i get just the object address as seen at the bottom-right of the picture.  This works in spyder IPython console and doesnt work in jupyter. I dont know if this is an  actual problem though! 

**Steps to Reproduce:**

As seen in the picture

**Versions:**

Latest Hydrogen and atom , Windows 10

**Comment by lgeiger** [comment]
You'll either need to include `%matplotlib inline` somewhere in your script or run `plt.show()` right after `plt.imshow(...)`.

**Comment by Jayu8** [comment]
This works! sorry for the trouble
