### ISSUE TITLE
Hydrogen Kernel Issue

### ISSUE THREAD

**Issue by kychanbp** [nteract/hydrogen#950]
![settings](https://user-images.githubusercontent.com/17669769/29483766-b74ca430-84e1-11e7-9f96-b6d6c63c07bf.PNG)
![hydrogen](https://user-images.githubusercontent.com/17669769/29483756-7146ea18-84e1-11e7-9813-d153d71d241b.PNG)

I am very new to programming and atom. And 

I cannot install hydrogen in Atom. Can anyone help?

**Comment by BenRussert** [comment]
Do you have jupyter installed? [Here is a link](http://jupyter.readthedocs.io/en/latest/install.html) if you need to install.

**Comment by ssahaxd** [comment]
# Solution
Just make sure, Python is installed for all users and it is added to the environment variables.

![ss1](https://user-images.githubusercontent.com/11327529/29982063-cfa6d654-8f6d-11e7-8c8f-c434300617cb.jpg)

![python setup Wizard](https://preview.ibb.co/d8w8eF/Screenshot_48.png)
I was also facing the same problem, after adding it to the environment all my problems were solved.

**Comment by lgeiger** [comment]
In Hydrogen 2.0.0 we changed our kernel detection method to improve the startup time and make setup easier. Checkout the updated [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html) and the [release notes](https://github.com/nteract/hydrogen/releases/tag/v2.0.0) for more information.

Feel free to open a new issue if you still experience problems with version 2.0.0.
