### ISSUE TITLE
Hydrogen does not show any results 

### ISSUE THREAD

**Issue by ffwuestner** [nteract/hydrogen#959]
Hi there. I am completely new to Atom.
I installed it and it felt quite easy to use and set up. I read that the Hydrogen package enables functionality similar to the Jupyter Notebook. So I installed the package.
Unfortunately, I have no Idea how to use it. I read the entire documentation and searched for everything I could.
So here is my problem:
I created a file called testfile1.py
In that file i put the very simle line
`print(‘Hello’)`
just to see how it works. I marked the line and pressed Ctrl+Enter. At the top right, a window pops up saying “Hydrogen Kernels updated: Python 3”.
But then nothing happens. I dont see the result of the code that I tried to run anywhere. I tried different lines of codes, tried differen run-combinations, nothing gives me any results.
I am using arch linux, installed Anaconda through the installing script provided by anaconda and my installation is located at ~/anaconda3.
Using the terminal and running
`jupyter notebook`
for example works just fine and opens a Notebook in Firefox (as it should) and running code that imports modules that came along with Anaconda also work fine once i run them with the script package in Atom
(things like
`import numpy as np`
`import matplotlib.pyplot as plt`
is letting me plot graphs when i just run the python file as usual, but just no reaction when i try to run the code with Hydrogen. So I think that it shouldnt be any issues related to the Anaconda packages itself)
I tried to look everywhere I could, but I do not find any solution on why hydrogen would not give me any results.
Is there anything I am missing or did wrong?
I hope someone might be able to help me, thanks already in advance

**Comment by ffwuestner** [comment]
Alright. Solved it. My firewall didnt accept any traffic from and to localhost. Oh my..

**Comment by lgeiger** [comment]
Glad you solved it! 🎉 

Would you like to add your solution to our [troubleshooting guide](https://github.com/nteract/hydrogen/blob/master/docs/Troubleshooting.md#common-issues)?
