### ISSUE TITLE
Wonky Kernel Status

### ISSUE THREAD

**Issue by NeedsAdjustment** [nteract/hydrogen#96]
So (after much trial and tribulation) I got Hydrogen working on my Windows PC, I noticed a little aesthetic issue with the status bar:
![hydrogenissue](https://cloud.githubusercontent.com/assets/10917143/9572548/09b069b4-5005-11e5-88a5-d0b34e1d43e9.PNG)

I'm sure this is a trivial issue, but I have no clue around CSS/Less/styling/whatever, so I have no idea what to do. I'm using the 'metro' UI theme by Cirex, but I've noticed a slight, slight issue along the same lines with 'atom dark', so...

Hmm.

**Comment by willwhitney** [comment]
Wow, that's very weird. The kernel status isn't really styled. I'm not ruling out this being an issue with Hydrogen, but maybe it's some sort of layout error with another plugin? Does this still happen if the plugin that's adding the "Archive" button there is disabled?

Do you (or anyone else with this issue) know your way around the dev tools enough to poke around and try to see what's happening?
