### ISSUE TITLE
Hydrogen installed with kernel, but still not running

### ISSUE THREAD

**Issue by Razcore** [nteract/hydrogen#976]
Hello there,

I've been following the previous tickets in order to deal with my problem.
I've managed to install Hydrogen for Atom on Windows 7 platform.
Python 3 is the only package installed with jupyter and others.

From what I can see, when the code is selected, when I run, it doesn't seem to output anything. Although, it worked one time after I've upgraded the kernel. After a restart, things went back to 'normal'.
At the jupyter kernelspec list --json command I get:
{
  "kernelspecs": {
    "python3": {
      "spec": {
        "language": "python",
        "display_name": "Python 3",
        "env": {},
        "argv": [
          "C:\\Program Files\\Python35\\python.exe",

          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ]
      },
      "resource_dir": "C:\\Users\\razvan.caramalau\\AppData\\Roaming\\jupyter\\kernels\\python3"
    }
  }
}
which looks reasonable to me.
If I look in the code: kernel-manager-spec.js, the secondKernelSpecString constant is defined in the same way.

Let me know if you have any idea how to solve this issue.

Kind regards,
Razvan

**Comment by Razcore** [comment]
Update:
It looks that it works the first time when I install it. Second time when I open Atom, it just stops displaying anything. The only way to make it work it's just by uninstall - install procedure.
 Any help around this issue will be very appreciated as I'm a big user of Hydrogen ( in the past I was using Spyder which at least on the interactive side was better).

**Comment by n-riesco** [comment]
Could you enable debug messages (as described [here](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) and post a screenshot of the dev console?

**Comment by Razcore** [comment]
![capture](https://user-images.githubusercontent.com/31627945/30158965-e991a602-93be-11e7-9f26-a1cac444419c.JPG)

**Comment by lgeiger** [comment]
The dev console doesn't show any messages related to Hydrogen.

Which command are you trying to run?
Could you try running it from the command palette to make sure the keymap isn't overwritten by another package?

**Comment by Razcore** [comment]
It seems to work in when I run with ctrl+enter command. I have the Script package installed as well. My hot keys on running the entire script were shift+enter. I guess it was totally my confusion. Thanks for support nevertheless!
