### ISSUE TITLE
Plotly does not work with python (Content Security Policy), redux

### ISSUE THREAD

**Issue by dnowacki-usgs** [nteract/hydrogen#982]
There are already [several](https://github.com/nteract/hydrogen/issues/841) [closed](https://github.com/nteract/hydrogen/issues/368) [issues](https://github.com/nteract/hydrogen/issues/557) related to this, but none seems to work for me, or I'm just not getting it. This is Atom 1.19.5, Hydrogen 1.21.1, macOS 10.12.6.

I like using plotly with python, and it works great in Jupyter notebooks, but not in Atom+Hydrogen. It's the same Content Security Policy issue that prevents figures from being displayed in Atom. Despite code being on the [Documentation examples](https://nteract.gitbooks.io/hydrogen/docs/Usage/Examples.html) page, and seeing reports in the issues that the code should work, I can't get it to display anything other than a small blank box. What am I doing wrong? Thanks.

**Output of example code:**
<img width="359" alt="screen shot 2017-09-08 at 10 14 51" src="https://user-images.githubusercontent.com/13837821/30215635-970ccb94-947e-11e7-8a7d-463a24e7b34f.png">

**Developer pane screenshot:**
<img width="729" alt="screen shot 2017-09-08 at 10 16 47" src="https://user-images.githubusercontent.com/13837821/30215704-d8f2f5d8-947e-11e7-8773-888843f5b05c.png">

**Comment by lgeiger** [comment]
Could you try upgrading plotly with `pip install plotly --upgrade` or `conda update plotly`?

**Comment by dnowacki-usgs** [comment]
Thanks for the quick reply. I was at Plotly 2.0.12, now at 2.0.15, still same result.

**Comment by lgeiger** [comment]
I can't reproduce this issue on Atom 1.20.0-beta7 and plotly 2.0.15.

Could you try to reinstall Hydrogen (`apm uninstall hydrogen && apm install hydrogen`)?

Is anyone else able to reproduce this on Atom 1.19?

**Comment by dnowacki-usgs** [comment]
I installed 1.20.0-beta7 and can confirm that plotly now **works for me**. Still no go on 1.19. 

I'll start using the beta and hope that it doesn't explode my computer. Thanks!

<img width="829" alt="screen shot 2017-09-08 at 11 00 21" src="https://user-images.githubusercontent.com/13837821/30217702-f31e8020-9484-11e7-85f0-4d9bf412b49f.png">

**Comment by lgeiger** [comment]
Glad you got it working!

In Atom 1.20 they made the content security policy less restrictive but it used to work in 1.19 too. Since Atom 1.20 stable is right around the corner I think we don't need to worry too much.

**Comment by rpalloni** [comment]
Hi all. Same problem as above. If you try running the code [here](https://mfreeborn.github.io/blog/2020/03/15/interactive-coronavirus-map-with-jupyter-notebook) in notebook it is ok but if you try it in hydrogen it displays but you cannot use the animation because of the CSP. Any hints to bypass it?
![map_animated](https://user-images.githubusercontent.com/17080117/77564598-44ca2d00-6ec3-11ea-9fa8-32fba6b39097.png)
