### ISSUE TITLE
Document external output area and docks

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#984]
We added support for docks and a external output area in Hydrogen 1.15.0 but have only documented it in the release notes. It would be great to have it documented.

Some GIFs are available in the [release notes](https://github.com/nteract/hydrogen/releases/tag/v1.15.0).

**Comment by choudhary001** [comment]
@lgeiger I would like to take this up. Can you outline what is needed here?
Thanks!

**Comment by lgeiger** [comment]
@choudhary001 Thanks for being interested in contributing! 🎉 

Currently our [getting started guide](https://github.com/nteract/hydrogen/blob/master/docs/Usage/GettingStarted.md) doesn't mention the possibility of using the external output area. It would be really great if there would be a section that explains the usage of the external output area (how it's toggled, etc..). You can use to GIF in the [release notes](https://github.com/nteract/hydrogen/releases/tag/v1.15.0) or make your own screen shots.

> Can you outline what is needed here.

You can decide for yourself what the scope of the issue should be. We're happy with everything from a small added section all the way to a complete rewrite of our documentation 😄. Though I'd recommend to start with small changes, we can always iterate.

**Comment by lgeiger** [comment]
@choudhary001 Are you still interested in this issue? Feel free to join us at https://slack.nteract.io if you have questions.
