### ISSUE TITLE
Can't uninstall hydrogen atom package

### ISSUE THREAD

**Issue by xmen1412** [nteract/hydrogen#985]
Hi, i have problem with uninstalling hydrogen packages. 

![problem](https://user-images.githubusercontent.com/29954788/30267430-c41ccc84-970c-11e7-855f-d5d5020462d1.PNG)

it sayys : Failed to delete Hydrogen: EPERM: operation not permitted, unlink 'C:\Users\akbar\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node'

**Comment by lgeiger** [comment]
Looks like `apm` messed up some permissions.
You can try to run `apm uninstall hydrogen` from the command line.

If everything fails just manually remove the `C:\Users\akbar.atom\packages\Hydrogen` using the explorer or the command line. This will completely remove the Hydrogen package from your system.

**Comment by xmen1412** [comment]
@lgeiger  well thanks a lot man , it works...:D

**Comment by FlorinAndrei** [comment]
Just to add this for the benefit of others who may land here directed by Google:

I just had the same issue. `apm uninstall hydrogen` works but you have to close Atom first.
