### ISSUE TITLE
Why There is no Output in Print("Hello World")??

### ISSUE THREAD

**Issue by xmen1412** [nteract/hydrogen#986]
i already install hydrogen in package install. there's no mistake while i installed it but. why there's no output in my preview code.

![hello world](https://user-images.githubusercontent.com/29954788/30267745-bd4b3e08-970d-11e7-9610-2943fc310aad.PNG)

**i want my code just like this example. have a preview on the right side of the code**

![real hello world](https://user-images.githubusercontent.com/29954788/30267792-df27d0ae-970d-11e7-9f1f-8616dd1edb7b.PNG)

**Comment by lgeiger** [comment]
- What command did you try to run? Checkout our [documentation](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html) for different ways to execute code.

- Did you follow our [installation instructions](https://nteract.gitbooks.io/hydrogen/docs/Installation.html) and have a supported kernel installed on your system?

- Could you enable debug messages (as described [here](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html)) and post a screenshot of the dev console, please?

**Comment by xmen1412** [comment]
@lgeiger  
![kernel](https://user-images.githubusercontent.com/29954788/30379505-e65207c8-98c0-11e7-9c6e-2f5706a9d32b.PNG)

this is the error when i press shift + enter for information, i use windows 10  64 bit with anaconda version 3.4.4 includes python.

**Comment by lgeiger** [comment]
Do you have `jupyter` installed and are you able to run `jupyter kernelspec list --json` from the command line?

**Comment by xmen1412** [comment]
@lgeiger yess i do.
