### ISSUE TITLE
Font size and customization

### ISSUE THREAD

**Issue by boyali** [nteract/hydrogen#987]
Hello

Can you explain how to customize nteract, which file, where is it located etc. I have a big screen and font seems to be very big. I tried to search but there is no clue.

Thanks

**Comment by rgbkrk** [comment]
Is this for the nteract desktop app or hydrogen the atom plugin?

**Comment by boyali** [comment]
Thank you for response. I noticed that I wrote to Hydrogen issues. I asked for desktop application.

**Comment by rgbkrk** [comment]
The browser style zoom-in/zoom-out is available (`⌘`+`+`, `⌘`+`-`) for basic needs. There isn't configurable zoom that will persist across sessions though.

Feel free to open an issue on nteract/nteract for this feature request. If you've got a common pattern that you like for this UX, please detail it. At least for us, it could be as simple as us tracking the last zoom level in our config.
