### ISSUE TITLE
tput: terminal attributes: No such device or address

### ISSUE THREAD

**Issue by xiligey** [nteract/hydrogen#988]
**Description:**
When I  want to see what `ts` (the variable from the picture) looks like, atom told me that "tput: terminal attributes: No such device or address"

![hydrogen](https://user-images.githubusercontent.com/17290149/30317697-756f1426-97dd-11e7-9877-8458d4826202.png)

**Versions:**
System: Win10-64bit
Atom: 1.19.5 X64
Hydrogen: 1.21.1

**Comment by lgeiger** [comment]
I can't reproduce this on my machine.
The error is thrown from the Python process so I guess this is a problem with your Python installation and not with Hydrogen itself.

Does this code work in your Python or IPython console?

**Comment by xiligey** [comment]
Thank you. It works automatically after I reinstall python.@lgeiger

**Comment by lgeiger** [comment]
Great :tada:
