### ISSUE TITLE
problem with ipython 

### ISSUE THREAD

**Issue by xmen1412** [nteract/hydrogen#990]
first of all, my issues https://github.com/nteract/hydrogen/issues/986 is already fix it. but there's another one issues

when i'm print('hello') directly it works. but i tried another ways with variable and then the error comes with.

![hello](https://user-images.githubusercontent.com/29954788/30388767-ea82a360-98da-11e7-87e7-9efc3baaa973.PNG)

Then, i use the example of hydrogen's documenation and it also show up like.

![hello 2](https://user-images.githubusercontent.com/29954788/30388812-1b490124-98db-11e7-8299-8cd78b23be33.PNG)

**Comment by lgeiger** [comment]
Glad you got it working 🎉 

The command "Hydrogen: Run" will only run the current line (or the selected area). Take a look at our [Documentation](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html) to learn about the different ways to execute code in Hydrogen.

You're probably searching for the commands "Hydrogen: Run All" or "Hydrogen: Run Cell".
