### ISSUE TITLE
Add margins between items in output area scrolling list

### ISSUE THREAD

**Issue by teristam** [nteract/hydrogen#993]
Hi, 

Currently, in the scrolling list view of the output area, the output items are too close to each other and look not so good. 
![screen shot 2017-09-15 at 2 24 30 am](https://user-images.githubusercontent.com/3406709/30471262-b226906a-99bd-11e7-9ccf-8eb01d8bb623.png)

It will be nice if a small margin is added between the output items. It can be done by modifying hydrogen.less:
`.output-area{
  div {
    margin-bottom: 10px;
  }
}` 

I know I should probably submit a pull request but I am still very new to github and so not sure how to do so. Hope someone with the knowledge can help incorporate the change. Thank you so much!

**Comment by BenRussert** [comment]
> Hope someone with the knowledge can help incorporate the change.

Seems like a great opportunity for your first PR! You seem really close to having the knowledge you are referring to. I would help walk you through what to do if you are interested.

**Comment by teristam** [comment]
Hi BenRussert,

I will really appreciate the help! Now I managed to do `apm develop hydrogen` to clone the repository and I can also see the change to the package in my atom editor. But I am not sure what's the correct way to submit a pull request. Should I create a new git branch on my side first? Thank you!

**Comment by BenRussert** [comment]
You are getting close. What you will need to do next is fork the hydrogen repo (there is a button up top on github to do this). This will make your own copy of the repo.

Next you will need to add a remote which leads to your fork. Commit your changes (I recommend doing this on a new branch) and push the branch to your newly added fork. 

I know this sounds complicated, but i promise nobody knows how to do this until they do and it will be easier next time.

For example my fork is at `git@github.com:BenRussert/hydrogen.git` so, replacing that url with your own I would do these steps. Some steps below might depend on your setup, if you are using ssh or https etc:

* add the remote fork, ill call it `myfork`, but its up to you:
`git remote add myfork git@github.com:BenRussert/hydrogen.git`
* make a new branch and check it out, again what you call it is up to you:
`git checkout -b output-area-margins`
* modify `hydrogen.less`
* add the modified file and commit
`git add ./styles/hydrogen.less`
`git commit -m "Add margins between items in output area, closes #993"`
* Push your branch to the remote you added for your fork
`git push myfork output-area-margins`


Now just go back to your fork on github in your browser (https://github.com/benrussert/hydrogen in my case) and you will see a message that says something along the lines of "this was changed recently" and a button that says "new pull request".

**Comment by teristam** [comment]
Thank you so much for the detailed instructions. Will give it a try later today!
