### ISSUE TITLE
Always display results in Output Area

### ISSUE THREAD

**Issue by vuki** [nteract/hydrogen#995]
I don't understand how to configure Atom to use the Output Area pane to display all results. I have checked "Output Area Dock" in options, but results are still displayed in bubbles. If I open the Output Area from the command palette (which requires a lot of typing and can be found only after starting the kernel), then the results are indeed displayed in the Output Area. But if I close and reopen Atom, bubbles are used again.

Is there a way to use the Output Area by default instead of bubbles?

**Comment by BenRussert** [comment]
There is not a way currently to use the output area by default, what you need to do is search "toggle output area" in the command palette and run, after that your output will be in the output area. 

I added a keybinding to my keymap for this reason, ill paste that code here later and maybe add something to the docs about this.

BTW, the "Output Area Dock" option is (my badly named) setting to keep your dock open even if you switch to an editor without a kernel running. I'll have to add something to the docs for this as well, but the hydrogen default is to close the dock if you switch, which can be annoying if you use the dock for another package (like the github package). The setting resolves this problem.

**Comment by lgeiger** [comment]
@vuki I agree we should add a global setting to configure if the inline bubbles or the external dock should be used.

Would you like to send a PR to fix this? A additional check [here](https://github.com/nteract/hydrogen/blob/master/lib/main.js#L338) will maybe do the job.

**Comment by adrianoesch** [comment]
i just watched this talk by bret victors on [youtube](https://www.youtube.com/watch?v=PUv66718DII) where he outlines a very compelling for instant feedback. from what i've read in this [atlantic long-read](https://www.theatlantic.com/technology/archive/2017/09/saving-the-world-from-code/540393/) he was also an inspiration for LightTable. in one of his [demos](https://www.youtube.com/watch?v=PUv66718DII&feature=youtu.be&t=1003) he has a side by side view, which reminded me very much of hydrogen, apart from the fact that it's not side by side and not instantaneous. so i was wondering how much it would take to get even a little closer to that experience. i'd guess that the loops etc are probably not that easy, but the side by side view and and instant feedback might be feasible, don't you think so? is it possible already? figured this thread might get have the same goal, but not sure.

thank you anyway, love your work!

**Comment by rgbkrk** [comment]
The [watch expressions](https://github.com/nteract/hydrogen/blob/c365ed957303cd7493b2facad22388331f6cb362/docs/Usage/GettingStarted.md#watch-expressions) will give you instantaneous feedback for every time you run anything in the editor.

**Comment by lgeiger** [comment]
Closed by #1022 
Thanks @BenRussert for the work.
