### ISSUE TITLE
Inspector not showing documentation

### ISSUE THREAD

**Issue by catethos** [nteract/hydrogen#996]
**Description:**
hydrogen inspector is not showing the python documentation.
The developer tool shows that it did receive the doc string.

**Versions:**
OS: mac osx 10.11.6 
Atom: 1.19.7
Hydrogen: 1.22.0

**Logs:**

![image](https://user-images.githubusercontent.com/6882603/30492485-357d5f4c-9a73-11e7-8656-8a617e3a56f9.png)

**Comment by lgeiger** [comment]
We have fixed it in #991 but forgot to released a new version yet. Maybe we should also backport this fix since the next version of Hydrogen will require Atom 1.20.

For now you can explicitly set the fontsize of the output in the Hydrogen settings. This should fix the problem.

**Comment by catethos** [comment]
Thanks @lgeiger !
